### ISSUE TITLE
API Key Still in Static Map Component

### ISSUE THREAD

**Issue by SeaDude** [microsoft/powerapps-tools#10]
Just a heads up, there is still a Bing Maps API key in the Static Maps Component. If you haven't already, deactivate it :)

![image](https://user-images.githubusercontent.com/8636973/55679185-d0fed100-58bb-11e9-9799-fa45ccd9dd20.png)

Thanks for the awesome toolset!

**Comment by devinprejean** [comment]
You guys can probably close this one because I'm getting a white screen now, I imagine they have deactivated it.
