### ISSUE TITLE
Admin | Sync Template v3 (Flows): The response is not in a JSON format.

### ISSUE THREAD

**Issue by ericthomas1** [microsoft/powerapps-tools#1000]
**Describe the bug**
First runs of the `Admin | Sync Template v3 (Flows)` Flow results in error:
```
{
  "error": {
    "code": 404,
    "source": "unitedstates-002.azure-apim.net",
    "clientRequestId": "fbc0b4ac-8a2e-4f1f-9d93-b1acddb250f5",
    "message": "The response is not in a JSON format.",
    "innerError": "Cannot read server response."
  }
}
```

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 2.0.10
 - App or Flow: Flow

**To Reproduce**
1. Ensure the Sync Template flows are already turned on for the following object types:
Apps, Connectors, Custom Connectors, Flows, Model Driven Apps, PVA, RPA
2. Turn on Admin | Sync Template v3. When it completes, turn it back off.

**Expected behavior**
Flow would run as expected

**Screenshots**

![image](https://user-images.githubusercontent.com/42788729/117059204-660b6880-acd4-11eb-9a17-b1acc85b27ef.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. This is a known product bug and the product team has half the fix rolled and is working on the other half. 
Tracked by #941
