### ISSUE TITLE
[BUG]: Admin| Sync Template v3 (Flow Action Details) - 404 on default env during List Flows as Admin

### ISSUE THREAD

**Issue by formerghostlyform** [microsoft/powerapps-tools#1004]
**Describe the bug**
During List Flows as Admin, we're getting back a 404 when trying our default environment (Default-9bbbcb03-4dc3-44a3-a63e-0b490987f4cc).  All other environments are fine, including Teams environments. User running the Flow is a power platform admin and has access to the environment in question

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - Version 2.0.10
 - Admin | Sync Template v3 (Flow Action Details)

**To Reproduce**
1. Run the flow

**Expected behavior**
Complete without failures

**Screenshots**
![image](https://user-images.githubusercontent.com/34247316/117176703-290ba880-ad9e-11eb-80bb-44a90be6a736.png)
![image](https://user-images.githubusercontent.com/34247316/117176884-5eb09180-ad9e-11eb-9d45-25be96ab348d.png)

**Additional context**
Problems seem to have begun occurring about a week ago. Upgraded to the latest release and the issue persists.  Any help would be greatly appreciated.

**Comment by manuelap-msft** [comment]
Hello,

thanks for reaching out! 

There is a known product issue at the moment that's already under investigation, see: 
https://powerusers.microsoft.com/t5/I-Found-A-Bug/quot-List-Flows-as-Admin-quot-failure-quot-The-response-is-not/m-p/911149

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Tracking in our GitHub with #941
