### ISSUE TITLE
CoE Starter Kit Missing Governance Business Process Flows

### ISSUE THREAD

**Issue by drace3000** [microsoft/powerapps-tools#1006]
**Describe the bug**
Missing Business Process Flows from Governance
**Component (please tell us which flow or app you are experiencing issues with):**
 - Governance
 - April Release

- Power Apps App Approval BPF
- Flow Approval BPF
- Custom Conector Approval BPF
- Activate the Business Process Flows

**Comment by manuelap-msft** [comment]
These BPFs are part of the Core solution, can you not see them there?

**Comment by JeneferM-MSFT** [comment]
Did you install the teams or production version of Core? 
Note that teams does not support BPFs [Production vs Dataverse for teams environment](https://docs.microsoft.com/power-platform/guidance/coe/setup#production-vs-dataverse-for-teams-environment)
They surface in the install like this today
![image](https://user-images.githubusercontent.com/62659043/117304556-1d21f400-ae3b-11eb-9148-29cf5294ed12.png)

**Comment by drace3000** [comment]
Hi Jenefer
Appreciate the reply and will share with the team for to validate. This install is the production version or core

Many Thanks
Don

**Comment by manuelap-msft** [comment]
Hello,

just wanted to check in here and see if you need further assistance from our side?

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Closing issues without further action on our side.
