### ISSUE TITLE
Power Platform Admin View lacks Settings in the navigation, setup of CoE Kit not possible

### ISSUE THREAD

**Issue by KSoehner** [microsoft/powerapps-tools#101]
This is stated in the "CoE starter Kit - Setup instructions.docx", page 7, chapter "STEP 2: CONFIGURE THE COE SETTINGS ENTITY"/INSTRUCTIONS, bullet point 2: "**In the left navigation, click on Configure (under Settings)**"
There is no "Settings" or "Configure" in the left navigation of the app. I can't enter the configuration values anywhere and am experienced enough yet to fix this myself or find a workaround.
![image](https://user-images.githubusercontent.com/15190484/76418155-6ba24280-639e-11ea-91d9-7a50b96048f3.png) Please help!

**Comment by manuelap-msft** [comment]
Can I check what version of the CoE Kit have you installed? With the latest version, the left hand navigation should look like this
![image](https://user-images.githubusercontent.com/55705669/76423393-9e4c3b00-639e-11ea-88d9-30f69738d538.png)

**Comment by KSoehner** [comment]
Yes, I don't see anything below "Connectors", People and Settings are missing.
I'm pretty sure I installed "CenterofExcellenceCoreComponents_1_23_managed(Invalid Argument Fix).zip", because I got the Invalid Argument Error during my first installation attempt. However I don't know how to double check this. I could simply import that file again - I assume that would update the solution, right?

**Comment by KSoehner** [comment]
I found the site overview designer in the solution that seems to show that there should be the missing entries:
![image](https://user-images.githubusercontent.com/15190484/76513522-ba131800-6456-11ea-838a-8211ba02f552.png)

**Comment by manuelap-msft** [comment]
If you click on Solutions, the highlighted number should be the version you've installed
![image](https://user-images.githubusercontent.com/55705669/76513187-cfd00f80-644d-11ea-9fc8-4766ad5cfee1.png)

I'll walk you through how to add the Settings:

In your solution, click on Power Platform Admin View and be sure to select the one that says Site Map in the third column
![image](https://user-images.githubusercontent.com/55705669/76513370-1b82b900-644e-11ea-80fc-13867fbdeaba.png)

You should see the Site Map (Navigation) of the app, although yours will look slightly different to the below
![image](https://user-images.githubusercontent.com/55705669/76513440-36edc400-644e-11ea-8c77-c3a65405dc31.png)

Select a Group (typically written in bold and dark blue), and then select Components from the right hand side and drag a Subarea component onto the screen.
Set the type to Entity and select CoE Settings as the Entity
![image](https://user-images.githubusercontent.com/55705669/76513722-9f3ca580-644e-11ea-8d75-03bc49480f0e.png)

Select Save and then Publish from the top
![image](https://user-images.githubusercontent.com/55705669/76513755-a8c60d80-644e-11ea-93fc-4f162a2b2cc1.png)

**Comment by manuelap-msft** [comment]
Oh I just saw your second comment now, so the Site Map looks fine here - can you try and Save and Re-Publish that? I'm not sure why the Admin view isn't picking that up.

**Comment by manuelap-msft** [comment]
When you open the Model Driven App in Design View, is the CoE Settings entity listed here as well? It should be the first one under Entity View 
![image](https://user-images.githubusercontent.com/55705669/76513913-f3e02080-644e-11ea-91b0-cc1c913abd8f.png)

**Comment by KSoehner** [comment]
Looks like this:
![image](https://user-images.githubusercontent.com/15190484/76515329-afa64d80-6459-11ea-9390-3461c1d338d8.png)

**Comment by manuelap-msft** [comment]
Yes, that also looks fine - if you click Play from here, does it show the CoE Settings then?

**Comment by KSoehner** [comment]
I clicked on "Play" on the top right and the result loooks like my first posted screenshot.

**Comment by manuelap-msft** [comment]
If you click on the little Edit icon (pencil) where it says Siteubersicht, does that show the same Site Map  you posted earlier where CoE Settings is listed in the navigation options?

**Comment by KSoehner** [comment]
Do you mean here?
![image](https://user-images.githubusercontent.com/15190484/76516110-298b0680-645b-11ea-8277-a7c0fa3d5c31.png)
Here the pencil is greyed out.

**Comment by manuelap-msft** [comment]
No, here when you looked at the model driven app
![image](https://user-images.githubusercontent.com/55705669/76516249-f93f6a00-6452-11ea-851f-d9da80b47894.png)

Sorry for the back and forth, based on the Site Map and Model Driven App it looks like it should show the CoE Settings so just trying to figure out what went wrong.

**Comment by KSoehner** [comment]
Ah ok. Then it shows the correct items, looks like the screenshot i posted second. 
Never mind - I know how hard troubleshooting is doing it this way!

**Comment by manuelap-msft** [comment]
Can you try and add the CoE Settings again following the steps I highlighted here: 
You might need to remove them and add them again into the Site Map
https://github.com/microsoft/powerapps-tools/issues/101#issuecomment-598121213

And then select Save and Publish.

**Comment by KSoehner** [comment]
Here we are! I configured this:
![image](https://user-images.githubusercontent.com/15190484/76518226-05c9bf80-645f-11ea-9804-807b38a04659.png)
and now I get this:
![image](https://user-images.githubusercontent.com/15190484/76518323-2e51b980-645f-11ea-803e-2df240dccc5c.png)
Reason seems to be that the groups all have the same name "New group". When you change the name they appear!
Thanks for your help with this - I learned a lot about mode driven apps today!

**Comment by manuelap-msft** [comment]
Aha!! I'm glad you got there in the end. I learned a new thing as well! 
In our published version, the groups all have different names so I'm wondering if this is something to do with this being incompatible due to language (German on your end vs English on our end).
I'll do some testing regarding this on our end but will also reflect what you had to do to solve it in the documentation in case anyone else experiences this issue!
Thanks for your work on this!
