### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Connection Status) flow is failing

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powerapps-tools#1014]
**Description**
CLEANUP - Admin | Sync Template v3 (Connection Status) flow is failing in "Get App as Admin" step or "Parse JSON" step under "Clean App Connection Status" "Apply to each" loop. The instances of the loop for which it is failing.

"statusCode":404 "message":"The response is not in a JSON format.","innerError":"Cannot read server response." I searched for some of these apps using Get-AdminPowerApp cmdlet and it seems they really do not exist anymore.

**Component (please tell us which flow or app you are experiencing issues with):**
-Solution Core Component
-Version 1.98
-CLEANUP - Admin | Sync Template v3 (Connection Status)

**To Reproduce**
.Go to CLEANUP - Admin | Sync Template v3 (Connection Status) flow inside Core Solutions
.Click on Run
.Wait for 6-8 minutes
.Flow will fail with the mentioned error

**Screenshots**
![image](https://user-images.githubusercontent.com/78148795/117538169-90d22580-b022-11eb-86e4-28027ad47451.png).
![image](https://user-images.githubusercontent.com/78148795/117538177-9af42400-b022-11eb-9cbf-fb471c05d42b.png)
![image](https://user-images.githubusercontent.com/78148795/117538202-b95a1f80-b022-11eb-8029-12520dd2e841.png)

**Comment by JeneferM-MSFT** [comment]
Hello, you are also several months behind in updates. Please do the following:
Update to the latest version of Core following the instructions at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove any unmanaged layers as described there you will not receive updates. 

Then if this still repros, I believe you have actually hit a product bug in which calls to Get Apps as Admin is returning deleted apps, which then cannot (but correctly) be retrieved by Get App as Admin. 

If it still repros you will need to create a flow outside of the context of the toolkit and contact support for them to fix. 
You can use the attached flow and just select the envt where you repro here:
![image](https://user-images.githubusercontent.com/62659043/117541755-9273fd00-afd2-11eb-9942-c6134d4fda40.png)

[ProductBug-GetAppfails-TheresponseisnotinaJSONformat.zip](https://github.com/microsoft/powerapps-tools/files/6445935/ProductBug-GetAppfails-TheresponseisnotinaJSONformat.zip)

**Comment by JeneferM-MSFT** [comment]
Duplicate of #937
