### ISSUE TITLE
[QUESTION]: Use of Service Principal rather than Service Account

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#1016]
**Describe the bug**
Is it planned to use Service Principals rather than Service Account in the CoE ?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 2.0
 - App or Flow - All of the Admin | Template 

Service Accounts are considered by some as insecure as the password can be hacked.  Service Principals  are considered much more secure

**Comment by JeneferM-MSFT** [comment]
I'm not sure what you mean by support, can you calrify? 

In the latest version of Core (2.1) apps installed by service principles are recognized now, they use to be treated as orphans. 
Flows installed by service principles are not found for inventory at all per our [limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#flows-that-are-imported-or-owned-by-a-service-principle)
We have not migrated this logic to other objects yet, waiting to see how this goes before expanding.

You are able to setup the toolkit as a service principle today

**Comment by NPrice99** [comment]
Hi @Jenefer 
I dont think I used the word "Support" ?
What I was asking was that at the moment the connections use Service Accounts which are considered to be insecure.  A much more secure approach would be to use Service principals.  So would it be possible to make the connections use Service principals and not service accounts ?

Regards

Nigel

**Comment by mstrblueskys** [comment]
> aww thanks. I read very fast sometimes :)
> 
> We're limited by platform capabilities here. Only a handful of connectors support using Service Principals, the Dataverse connector is one of them but none of the Power Platform for Admins connectors support that. Connection References also don't support using Service Principals yet etc.
> 
> If you import the solution using a service principle today, all assets (flows, canvas apps) can be owned by the service principals today if pipelines are set up to do that. However, for connections itself you will still need to use interactive users / service accounts due to the above limitations.
> 
> Hope that all makes sense.

Is this still the case today? There seems to be some documentation that suggests we could use an HTTP request, but I'm not seeing anything specific anywhere. Thanks!
