### ISSUE TITLE
[Question]:  Center of Excellence (CoE) Kit PowerBI Dashboard not updating

### ISSUE THREAD

**Issue by JMMora** [microsoft/powerapps-tools#1017]
**Describe the bug**
I juts Deployed  CoE last week, all went well, including the PowerBI Dashboard, however I see today the Data Published is outdated, show last week information. my question is  how to the PowerBI Dashboard get updated Data everyday?

**Comment by JMMora** [comment]
I found the setting to get the PowerBI Dataset Refreshed daily, I hope this was the issue.

**Comment by JeneferM-MSFT** [comment]
Yes you need to setup automatic refresh if you would like that to be automatic for you. 
Thanks for using CoE!
