### ISSUE TITLE
"Core Components" is a managed solution - option 1 for activation of flows doesn't work

### ISSUE THREAD

**Issue by KSoehner** [microsoft/powerapps-tools#102]
The setup documentation "CoE Starter Kit - Setup instruction" on page 12 tells us in order to activate the flows: "Click on the flow name to get to the details screen, then select ‘Edit’ " However, the solution is managed and therefore you can't edit that flow, rendering option 1 unusable. Option 2 seems to work. Please fix this in the documentation (saves us time) or provide the unmanaged solution as well. Or is ist possible to turn a managed solution into an unmanaged one?

**Comment by manuelap-msft** [comment]
That’s actually a common misconception. Managed does not mean not editable. It just means that managed layer in CDS is locked. You can still edit managed components. Several components, including Power Automate Flows, allow launching of the designer from a managed solution. 

Have you encountered an issue doing this?

**Comment by KSoehner** [comment]
Yes, when I do as told, the "Edit" option becomes greyed out:
![image](https://user-images.githubusercontent.com/15190484/76423531-3e0dc700-63a7-11ea-96fc-802942cdbac5.png)

**Comment by manuelap-msft** [comment]
Please click on the Flow name, instead of the ..., and then select Edit from the Flow Designer page
![image](https://user-images.githubusercontent.com/55705669/76423740-23cfeb00-639f-11ea-801a-c46036e90bd0.png)

**Comment by KSoehner** [comment]
ooooh, ok, got it. Thanks for your help!
