### ISSUE TITLE
White Screen on mobile

### ISSUE THREAD

**Issue by seanmconnor** [microsoft/powerapps-tools#103]
When accessing the app using the PowerApps app on a mobile phone, the Emergency Contacts and Company News screens are white. It works fine on a desktop or an iPad.

**Comment by mr-dang-msft** [comment]
Hi @seanmconnor,
Can you share more details? Does this occur on the latest version?

You can use this template when submitting issues:

https://github.com/microsoft/powerapps-tools/issues/new?assignees=denisem-msft&labels=crisiscommapp&template=-crisis-communication-app--bug-report.md&title=%5BBUG%5D%3A+issue+title

**Comment by seanmconnor** [comment]
I presume it's the latest version, how would I know what version I have?
