### ISSUE TITLE
Need help!  - ALM Accelerator App of latest CoE Starter Kit

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#1030]
Hello Team,

Thank you for the latest CoE Starter Kit making available with more features and improvements!

I have a question regarding "ALM Accelerator App" of CoE Starter Kit ( 2.6 ) if I understand it correctly - I have not yet installed/reviewed/configured it in the environment yet, However, I was wondering if this app can be useful with respect to Azure DevOps or it's only meant for the GitHub source control?

Thank you for your time in advance!

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

this app is only working with GitHub, however we do have a more advanced version that works with Azure DevOps. You can learn more about it here https://github.com/microsoft/coe-starter-kit/tree/main/PowerPlatformDevOpsALM

Thank you
Manuela

**Comment by DiptiC-InsightRun** [comment]
Hello, I have just noticed that this link - https://github.com/microsoft/coe-starter-kit/tree/main/PowerPlatformDevOpsALM is broken, Could you please share new one?

Thanks and Regrads,
Dipti

**Comment by manuelap-msft** [comment]
The new link is https://github.com/microsoft/coe-starter-kit/tree/main/ALMAcceleratorForAdvancedMakers
