### ISSUE TITLE
[BUG]: Cloud Flow runs

### ISSUE THREAD

**Issue by JerryCRMI** [microsoft/powerapps-tools#1033]
I am not seeing any Cloud flow run records. Can't seem to find a flow that would do it in the solutions. I do see one for Desktop flow runs. 

What am I missing?

Jerry

**Comment by JeneferM-MSFT** [comment]
Hello we have moved to a new dedicated repository for the CoE Starter Kit - please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues

For this particular issue, we resolved in email as well. We do not yet have the ability to gather cloud flow runs.
