### ISSUE TITLE
[BUG]: Power BI template giving semaphore timeout expired

### ISSUE THREAD

**Issue by russrimm** [microsoft/powerapps-tools#1036]
**Describe the bug**
When launching the Power BI template, customer is getting a "Semaphore timeout period has expired"

**Component (please tell us which flow or app you are experiencing issues with):**
Power BI template
Dashboard-PowerPlatformAdminDashboard-2021-04-08

**To Reproduce**
Open Power BI template, enter fqdn of environment that the CoE is installed in (hostname.crm.dynamics.com)

**Expected behavior**
PowerBI dashboard should not time out.

**Screenshots**
![image](https://user-images.githubusercontent.com/10841574/118670254-0f198f00-b7bc-11eb-9f88-9176c5da155e.png)

**Additional context**
This issue is in one of my customer's environments.  It loads fine in my environment.

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit - please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues

Please see notes in https://github.com/microsoft/coe-starter-kit/issues/341 for this particular issue. 

Pasted from there:
Can you please try using this old version of the PBI while we work through the issues with the new direct query version?
[Feb Version of PBI](https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-02-02%20(1).pbit)

Note that you will need to enter the org url with the prefix included as shown here: https://yourcoe.crm.dynamics.com
