### ISSUE TITLE
nvvvv

### ISSUE THREAD

**Issue by avtech123** [microsoft/powerapps-tools#1037]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit - please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues
