### ISSUE TITLE
[BUG]: issue title: unable to view the app catalog

### ISSUE THREAD

**Issue by vishal4bhosale** [microsoft/powerapps-tools#1038]
**Describe the bug**
A clear and concise description of what the bug is.: when I open app catalog canvas app it's a blank

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version :1.9
 - App or Flow: power apps app table

**To Reproduce**
I can't see any app available in app catalog, as per advise I went to default solution and search for power apps app but can't find open in excel option  to change the Boolean value to true

Certainly I can go to Center of excellence core component and able to see a option  open in excel for Powerapps app however it's gray out for me.

I am seeing another msg 'you can't edit the components within managed solution'

![image](https://user-images.githubusercontent.com/82226691/119029827-0d5cf080-b9a1-11eb-952d-8b063490caf5.jpeg)
**Screenshots**
Please refer the screenshot for ref

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit - please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues

Please view [the app documentation](https://docs.microsoft.com/power-platform/guidance/coe/core-components#app-catalog) to understand how to use the app. It is expected to be blank at first. 
![image](https://user-images.githubusercontent.com/62659043/119034482-9b1de900-b96b-11eb-8972-e1109967c499.png)

**Comment by vishal4bhosale** [comment]
Exactly but even after as per the advise in the article it doesn't allow to click on edit for Powerapps app... please refer my screenshot for ref

**Comment by JeneferM-MSFT** [comment]
The thing you are trying to select in the screenshot is a Table, please view the documentation for the expected pathways for the process. You should use the Model Driven App and not edit the data directly

**Comment by vishal4bhosale** [comment]
I found the solution
Thanks a lot
