### ISSUE TITLE
[Question]: Cannot view the Default Environment Admin View Dashboard

### ISSUE THREAD

**Issue by leondarl** [microsoft/powerapps-tools#1039]
Dear all,

 I am very new to this COE kit installation.
I have installed the core components only on a Trial Environment on my tenant.
I can only see the Environments that I have created but cannot view the "Default" environment where we have  "ALL" our flows and apps.

Can you please help me understand why I cannot see although I have access to .

With much appreciation !!
Stay Safe
Leonidas

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit - please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues

Please see the [pre-reqs for the toolkit](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites). It sounds like you do not have the Power Platform Admin Role, and hence are only seeing the environments to which you have access. 

This might help determine if you have the correct role:
[PPAdmin Role.pdf](https://github.com/microsoft/powerapps-tools/files/6518899/PPAdmin.Role.pdf)

**Comment by leondarl** [comment]
Dear Jenefer,
It’s a pleasure to meet you virtually !!!
I appreciate your very helpful pointers and I will make sure to review and see if I can figure out the issue.

As I mentioned I am start starting.

Do you have any good pointers (additional information) about the environmental variables.

It will be great if you can share with me any Best Practices on how to define them.

I need to make sure I am using the proper security.


You are awesome !!!!
Stay safe
Thank you !!
Leonidas

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues
