### ISSUE TITLE
Notification Method Error for Admin Settings

### ISSUE THREAD

**Issue by CoderZMonkeyZ** [microsoft/powerapps-tools#104]
Attempting to set the Notification method on Admin Settings causes a failed save event. 

These are the values I used: 
Email, Teams notification, Push notification

From the documentation listed from here: 

https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#create-initial-content-for-the-app

Under the settings for "Admin Settings"

**Comment by mr-dang-msft** [comment]
Hi @CoderZMonkeyZ,
I'm unclear what you mean when you say you used those 3 values. The field for PreferredNotification accepts only one of them. Did you change it to a multiple selection? Or do you mean you tried them individually and with each one not working for you?

![image](https://user-images.githubusercontent.com/39354102/76500803-6ffe4800-63fe-11ea-8c1e-2ce916f3b927.png)

**Comment by CoderZMonkeyZ** [comment]
Hi, 

I wanted to clarify the PreferredNotification when I go to enter a value (ie Email) or from the documentation "Email, Teams notification, Push notification" I don't have any of these listed in the preferred notification method.  I am wondering if I need to set one up under the PreferredNotification value for it to show up.  It's unclear from the directions under admin settings if this needs to be setup before hand, cause I don't see it from entering 1 or more.  It's like it doesn't exist for me. 

Thanks for any help you can offer on this, we are attempting to stand this up no later than friday and this is kind of stopping my momentum at this point. 

Mark

**Comment by CoderZMonkeyZ** [comment]
Here's a visual, I don't have an option to select from: 

![image](https://user-images.githubusercontent.com/2415709/76561208-0d3d9880-6460-11ea-8a82-1f901a3cb5d3.png)

**Comment by mr-dang-msft** [comment]
@CoderZMonkeyZ ,
When you open the admin app in the studio, you will need to remove the existing SharePoint connections and wire up your own. Can you confirm you've done that?

**Comment by CoderZMonkeyZ** [comment]
Correct, when you mentioned remove the default Share Point from the set of instructions, I did so.  Than I connected to my share point site with the CL_FAQ, CL_configAdminSetup, etc.  The one thing I'd like to clarify is these "CL" I had to create them on my sharepoint site in order for them to show up.  However, when you said "wire up", I only created the name and nothing else.  

This is what it looks like on my side: 
![image](https://user-images.githubusercontent.com/2415709/76564489-d5395400-6465-11ea-9b23-dfefad69a16c.png)
And than when I open one of these say "CL_configAdminSetup" this is what I have for now: 
![image](https://user-images.githubusercontent.com/2415709/76564520-e7b38d80-6465-11ea-9611-13764725d3e5.png)
So when you said wire up, I wasn't sure what you meant beyond this point.  If I missed something, please let me know and I'll give that a approach a shot.  

Really do appreciate this help and response. Let me know if there's more info I can provide.  

Thanks, 

Mark

**Comment by mr-dang-msft** [comment]
I think you may have skipped these steps for deploying the lists:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#create-the-sharepoint-lists-for-app

Once you run the DeployLists flow, it creates the required lists for you. From there, you remove the connections from the admin app, add the lists that you created from the flow. The created list includes the options for the fields.

**Comment by CoderZMonkeyZ** [comment]
I am going to give that a try do I need to start over or can I just run the DeployList flow and be good to go? 

I'll update after I've tried this.

**Comment by mr-dang-msft** [comment]
I suggest removing the CL lists you created so it's not confusing. Then run the DeployLists flow.

**Comment by CoderZMonkeyZ** [comment]
Hi Mr Dang,

I rand the steps you mentioned and I received the following error: 

![image](https://user-images.githubusercontent.com/2415709/76648310-b1384a00-651b-11ea-935a-a19f7b6252c2.png)


Here is the details of this error: 

![image](https://user-images.githubusercontent.com/2415709/76648466-fb213000-651b-11ea-8070-a93615147ff4.png)

Any help on clearing this up would be great.  I feel like I am close.  

Thanks, 

Mark

**Comment by CoderZMonkeyZ** [comment]
Any follow ups to the 502 issues I am seeing above? I have folks needing to get this app up as soon as we can overcome the technical hurdles at the moment.  Appreciate the help thanks.

**Comment by mr-dang-msft** [comment]
@CoderZMonkeyZ 
Can you confirm that you have changed the Target Site for Lists to a SharePoint site that you have permissions to create lists on?

**Comment by CoderZMonkeyZ** [comment]
How do I check this? I go into my site permission and this is what I see: 

![image](https://user-images.githubusercontent.com/2415709/76782932-3d41b000-676e-11ea-9d7d-ee9b1fed403a.png)

**Comment by mr-dang-msft** [comment]
Hi @CoderZMonkeyZ, from your screenshot, it looks like you have lists for EmployeeStatus and the others created:
![image](https://user-images.githubusercontent.com/39354102/76783160-96114880-676e-11ea-942a-2b51c1874f5e.png)

Can you let me know if you had manually created these lists? The flow will fail if you have lists of the same name already (e.g. you either manually created lists or you successfully deployed before).

**Comment by CoderZMonkeyZ** [comment]
Also just checked my flow, not sure what's going on with the "Run" cycle, but it's successful at this point.  I will try the push notification piece again.  This is what I saw from the run record logs: 

![image](https://user-images.githubusercontent.com/2415709/76783375-ff915700-676e-11ea-89af-a34dd13ae828.png)

**Comment by CoderZMonkeyZ** [comment]
No, not manually entered. I got this from running the DeploySPList in the flow.  So I believe that is working, not sure how the 502 was overcome, but I'll go with it for now.  I am going to try the push notification setup and see if that works.

**Comment by CoderZMonkeyZ** [comment]
Mr Dang, 

I have been successful in getting to the next stage of this.  Here is my snapshot: 
![image](https://user-images.githubusercontent.com/2415709/76786225-16867800-6774-11ea-9200-969b71490252.png)


I will be working to finalize this, if I have any further I will make sure to update you here. 

Thank you sir, for your time, your patience, and more importantly your help. 

Mark

**Comment by CoderZMonkeyZ** [comment]
So I am super close and I am attempting to share this with folks in the organization (first a test group).  I have the teams setup with the app and I can see it as follows: 

MyView: 
![image](https://user-images.githubusercontent.com/2415709/76792163-a7af1c00-677f-11ea-8eac-49f39f980445.png)

However, when I shared with a few colleagues.  They reported seeing this error and a blank screen: 
![image](https://user-images.githubusercontent.com/2415709/76792189-bbf31900-677f-11ea-99c6-caf4df15987a.png)


Any idea what would cause that?

**Comment by CoderZMonkeyZ** [comment]
Working! Thanks Mr. Dang.
