### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Apps) faults on one or more apps.

### ISSUE THREAD

**Issue by andersidahl** [microsoft/powerapps-tools#1042]
**Describe the bug**
Admin | Sync Template v3 (Apps) faults on one or more apps.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 2.1.6
 - Admin | Sync Template v3 (Apps)

**To Reproduce**
Run Admin | Sync Template v3

**Expected behavior**
No faults

**Screenshots**
![image](https://user-images.githubusercontent.com/10434858/119094375-3f0da000-ba11-11eb-93e8-b7fe1bd1442b.png)
![image](https://user-images.githubusercontent.com/10434858/119094459-56e52400-ba11-11eb-8f1c-6c519fa86223.png)

**Additional context**
I've deployed the kit following https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components and have thoroughly been following the order. I am deploying this using a permanent GA.

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit - please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues

That said, this sounds similar to #999. If this repros consistanty (and not just a timing issue) then you have likely hit a product bug in which the product is improperly caching and returning old and deleted apps in the call to Get Apps as Admin. 

Please try the flow at the bottom of #999 to find a repro outside of the toolkit and let me know. We are trying to track these cases internally for the product team.
