### ISSUE TITLE
[BUG]: Installation of the COE in GCC High - Nurture Component

### ISSUE THREAD

**Issue by cdt2021** [microsoft/powerapps-tools#1047]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Nurture
 - Version - 1.51
 - App or Flow - Import

**To Reproduce**

I am working in a GCC High environment and it appears the Nurture component requires Excel Online (Business).  Can you provide a previous version that doesn't require Excel Online (Business)?  The documentation I've found states the connector is not available.  If I'm incorrect please tell me how to implement the component.

**Comment by cdt2021** [comment]
My ultimate goal is to use the Maker Assessment app.  Can I do so in GCC High without access to the Excel Online (Business) connector?

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues
