### ISSUE TITLE
[BUG]: Installation of the COE in GCC High -  Innovation Backlog - PowerAutomate Flow Error

### ISSUE THREAD

**Issue by cdt2021** [microsoft/powerapps-tools#1048]
**Describe the bug**
Error when running the "Update Software Tools" flow.  Details below.

**Component**
 - Solution - Center of Excellence - Innovation Backlog
 - Version - 1.30]
 - App or Flow - This is a flow

**To Reproduce**
I've installed the Center of Excellence - Innovation Backlog in our GCC High Tenant.  When I run the "Update Software Tools" flow I get the following error:

Action 'Mark_Common_-_ODB' failed

The 'inputs.parameters' of workflow operation 'Mark_Common_-_ODB' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'recordId'

Is there something I can do to change the value of the recordIdto be nullable?

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues
