### ISSUE TITLE
[BUG]: COE Starterkit installation in GCCHigh - Set up ALM Accelerator for Makers components

### ISSUE THREAD

**Issue by cdt2021** [microsoft/powerapps-tools#1049]
**Describe the bug**
This is an inquiry.  GitHub is not an available connector in GCCHigh.  What are the alternatives to installing the ALM Accelerators for Makers

**Component**
 - Solution - PowerPlatformGitHubALM
 - Version - 1.0.0.72
 - App or Flow -  App

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues
