### ISSUE TITLE
Error running DeploySPLists

### ISSUE THREAD

**Issue by ricky-rivera** [microsoft/powerapps-tools#105]
Configured both required variables but still getting this error when I run flow:
The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Null.'.

**Comment by mr-dang-msft** [comment]
Hi @ricky-rivera,
Where exactly in the flow did this error occur? Can you include the full details?

**Comment by ricky-rivera** [comment]
Error happens when executing the flow. Weird thing just re-tried this morning and its working now!
