### ISSUE TITLE
What is the significance of Environment variables such as FullInventory and Power Platform Make Office 365 Group?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/powerapps-tools#1051]
Hello,

As "FullInventory" and "Power Platform Make Office 365 Group" environment variables are the part of "CoE Core" ( 2.1.6 ) version - Would you please share the significance of the same? in which components they are being utilized?

![image](https://user-images.githubusercontent.com/13658386/119340865-1380f480-bc61-11eb-8b34-6961cfee27df.png)

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues
