### ISSUE TITLE
[BUG]: BadRequest supera el máximo permitido

### ISSUE THREAD

**Issue by JimmyMoralesH** [microsoft/powerapps-tools#1052]
**Describe the bug**![image](https://user-images.githubusercontent.com/84737793/119400499-47cbd380-bca8-11eb-8300-b28e4ab6c92d.png)Aparece un error "supera el máximo permitido". al activar los flujos asociados al Starter Kit del Centro de excelencia

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : CenterofExcellenceCoreComponents_2_1_6_managed.zip
 - Version : 2.1.16
 - App or Flow: Flow CLEANUP - Admin | Sync Template v3 (Check Deleted)

**To Reproduce**
1. Go to 'solutions --> Center of Excellence - Core Components --> Flow CLEANUP - Admin | Sync Template v3 (Check Deleted)'
2. Click on '....' --> click on 'Turn On'
3. See error :  No se pudieron activar los componentes. Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Error al guardar el flujo con el código \"InvalidPaginationPolicy\" y el mensaje \"La directiva de paginación de la acción de ejecución de flujo de trabajo \"Get_Environments\" de tipo \"OpenApiConnection\" que se encuentra en la línea \"1\" y la columna \"3169\" no es válida. El valor especificado de la propiedad \"minimumItemsCount\" supera el máximo permitido. Valor real: \"100000\"; máximo permitido: \"5000\".\"."}}".

**Expected behavior**
Flow Activo

**Screenshots**
![image](https://user-images.githubusercontent.com/84737793/119400607-66ca6580-bca8-11eb-918d-cf96e1cabeed.png)

**Comment by manuelap-msft** [comment]
closing as issues in this repo are no longer monitored, and you have raised the issue already in https://github.com/microsoft/coe-starter-kit/issues/476
