### ISSUE TITLE
CoE Core Components for Teams... pagination errors

### ISSUE THREAD

**Issue by StevenArn** [microsoft/powerapps-tools#1058]
**Describe the bug**
When attempting to turn on / run the CLEANUP - Admin | Sync Template v3 (Check Deleted) Flow, we received a pagination error.  We had to edit EVERY list action in the flow in order to save it.  This was for a client who is still on the Flow Plan 2 / Power Apps plan 2
![Error Screenshot](https://user-images.githubusercontent.com/84876635/119858748-beecac00-bee2-11eb-9bbb-115409fdff4d.jpg)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]  Core (Teams)
 - Version [e.g. 1.29] 1.992
 - App or Flow [e.g. Sync Template (v2)] CLEANUP - Admin | Sync Template v3 (Check Deleted)

**To Reproduce**
1. Go to '...'  Attempt to turn on 

**Expected behavior**
The Flow should allow a threshold of 100000

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on:
https://github.com/microsoft/coe-starter-kit/issues
