### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by sl1207** [microsoft/powerapps-tools#106]
**Describe the bug**
In the Crisis Comunication Admin app, I have the error "Submission failed" in the most of functions (Admins Settings, FAQ for sure).

**To Reproduce**
1. Run the Crisis Comunication Admin
2. Click on Admin setting
3. Change one parameter, eg. Admin email
4. Click save

**Expected behavior**
I don't know the app, I was following a tutorial, but probably the expectations was to save the parameter in the sharepoint list

**Interface(please complete the following information):**
 - Browser Chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)

**Additional context**
I'm new in PowerApps and I was trying to follow the tutorial, it could be I had a mistake on the way

**Comment by mr-dang-msft** [comment]
Hi @sl1207,
The PreferredNotification column is a required field in SharePoint. In the recent versions, we made it a required field and included an asterisk to make it more explicit. 

While it's best to run the latest version, on whichever version you are on, can you make sure you have a notification type selected in order to save?

**Comment by sl1207** [comment]
Hi there,
after posting the previous message I started the configuration fromt he beginning and now the admin app works perfectly.
I have now a problem with the Crisis Communication app, it doesn't go over the first screen... should I open a new ticket?
![2020-03-12_13-20-57](https://user-images.githubusercontent.com/62087725/76554889-a2429080-6464-11ea-8929-f7160559b9c8.jpg)

**Comment by mr-dang-msft** [comment]
Hi @sl1207,
In the Admin settings, you'll also see toggles for the screens you want in the main app:
![image](https://user-images.githubusercontent.com/39354102/76555107-3d7f3a00-6454-11ea-867e-b5112026d6df.png)

Once you toggle the ones you want, the main app needs to have the right SharePoint lists connected to it. The app fetches the configuration settings upon start, so you'll need to refresh the app to see the changes.

**Comment by sl1207** [comment]
Thanks!
And I'm sorry, I made studid questions, I'm new... the app is great, thanks again,
