### ISSUE TITLE
SharePoint library not visible

### ISSUE THREAD

**Issue by rahul9226** [microsoft/powerapps-tools#1064]
**Describe the bug**
SharePoint library not visible to select.

**Component (please tell us which flow or app you are experiencing issues with):**
 -  Nurture component
 - Version [e.g. 1.40]
 - App or Flow [e.g. Maker Assessment | Import starter data cloud flow]
 - Environment Variable - Maker Assessment SharePoint Library"
 
**To Reproduce**
1. Import Nurture component
2. While importing solution update Environment Variable
3. Scroll down to 'Maker Assessment SharePoint Library'
4. Can't see library.

**Expected behavior**
When trying to select "Maker Assessment SharePoint Library", the new site we created  does not show up in the list of sites. Checked with permission, user is owner as well as Admin for SharePoint site. Also created library, which is not displayed within the Maker Assessment | Import starter data cloud flow.

**Screenshots**
![image](https://user-images.githubusercontent.com/77864042/121602642-77930f00-c9fc-11eb-9286-10a035eb0fd9.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on: 
https://github.com/microsoft/coe-starter-kit/issues 

For this particular issue, you are facing a product issue and not an issue with the toolkit and so unfortunately we cannot support.
