### ISSUE TITLE
[Need Help]: What should be the timing to trigger Sync flow in the CoE Starter Kit 2.1.6 ?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [microsoft/powerapps-tools#1065]
Hello,

I need suggestions on Sync Flow timings!

The Sync process trigger which is dependent on  Flow "Admin | Sync Template v3"  shows UTC 15:00 as trigger time in the CoE Starter Kit version 2.1.6, which would be different in different time zones.

Could you please share if sync flow should be triggered at specific time in order to maintain CoE processes managed by other flows in the CoE Starter kit 2.1.6? or the default configured time will be fine regardless any time zone?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on: 
https://github.com/microsoft/coe-starter-kit/issues
