### ISSUE TITLE
[BUG]: CrisisCommunication.Request error

### ISSUE THREAD

**Issue by jbmortlock** [microsoft/powerapps-tools#107]
**Describe the bug**
When running the flow CrisisCommunication.Request there is an error in the last step "Notify the Team of the request"

Request to the Microsoft Graph failed with error: '{
  "error": {
    "code": "Forbidden",
    "message": "Trying to CreateTeamAppEntitlement for an App that is explicitly blocked by the tenant admin.",
    "innerError": {
      "request-id": "b0168217-31ff-4fb8-94b0-1825fce3c85c",
      "date": "2020-03-12T15:35:34"
    }
  }
}'.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Interface(please complete the following information):**
 - Version date[e.g. 2020.04.03]

**Smartphone (please complete the following information):**

**Additional context**
"8cf9565e-4998-bce4-b319-fedb7e9d835b"

**Comment by jbmortlock** [comment]
App seems to have necessary permissions to run in Teams, its just this last step in the flow that seems to error out

**Comment by mr-dang-msft** [comment]
Hi @jbmortlock,
The latest version of the Crisis Communication app changes this behavior for the request flow. Can you confirm once you've updated?
