### ISSUE TITLE
[BUG]: issue : My flow "Admin | Archive and Clean Up v2"  archive the apps and flows

### ISSUE THREAD

**Issue by sharmakhilesh** [microsoft/powerapps-tools#1078]
**Describe the bug**
Hi Team, 

I run below flows and it will going archive my many flows and apps from my tenant after 15days, It include my production app and flows. even I dont know where it gonna store my archive apps/flow. CoE is new for me. Could you please help me investigate about my issue.  

Admin | Archive and Clean Up v2 (Start Approval for Apps)
Admin | Archive and Clean Up v2 (Start Approval for Flows)

I am import below solution

CenterofExcellenceCoreComponents_2.2.20210707.3_managed
CenterofExcellenceAuditComponents_1.70.20210708.1_managed

**Comment by JeneferM-MSFT** [comment]
We have moved to a new dedicated repository for the CoE Starter Kit, and issues here will no longer receive attention. Please raise your issues here from now on: 
https://github.com/microsoft/coe-starter-kit/issues 

But per our conversation in other bugs. There is no archival by the toolkit. The archival is only done by the end user if they want to do a backup. 

You will need to contact support to get assistance in restoring apps and flows you approved to delete.
