### ISSUE TITLE
AppChangeFinder: Entities.json does not exist

### ISSUE THREAD

**Issue by jpaugh** [microsoft/powerapps-tools#11]
When opening a toy PowerApp, AppsChangeFinder aka 'PowerApps Review Tool' complains with the message:

> Could not find file 'C:\Users\Jonathan.Paugh\AppData\Local\Temp\N16602385-3883-4153-9a6f-a59afd6fe351-document_00000000-0000-0000-0000-000000000000\Entities.json'.

This happens because the `msapp` I'm looking at does not contain an `entities.json` file. Is there another way to retrieve data from the app, anyway?

[Here's the app I'm looking at](https://drive.google.com/open?id=1T4ZFFzEkORv14vdhawkvHNv2WTPojTGr). I exported this with "Create as new" selected; I've also tried the default of "Update."

**Comment by TreyPoint** [comment]
I am having the same issues - my guess is the PowerApps platform changed the way the .msapp is structured and saved.

**Comment by elcuevero** [comment]
Still having the same issue.

**Comment by quentin-r37** [comment]
Yes there is no anymore Entities.json file, apps are splitted in a new hierarchy. Same issue here.

**Comment by slaouist** [comment]
this issue should be fixed now
