### ISSUE TITLE
Audit Log Flow only returns 100 items

### ISSUE THREAD

**Issue by jathorpe** [microsoft/powerapps-tools#110]
I deployed the Admin | Sync Audit Logs flow and it is only returning 100 items from the Audit Logs. We have a very large environment and we go through more than 100 Power Apps Launches a day. How can I increase the return limit?

**Comment by manuelap-msft** [comment]
You would need to change the scheduled Flow so that it doesn't run daily but hourly for example, and modify the start and end time also to get hourly results.

**Comment by jathorpe** [comment]
I will try that but with our large environment I could easy get more than 100 app launches in a hour. Would be possible to add the ResultSize parameter to the custom connector, so we could extend the limit past 100? I have done this in PowerShell with Search-UnifiedAuditLog and it has worked well.

**Comment by jathorpe** [comment]
I was able to configure the flow to run every hour and adjusted the Start and End dates to include time, so that it was only requesting logs entries for the last hour and I was still hitting the 100 item limit. We have a large user base and a lot of different apps, so we need to be able to grab more than 100 events. If we can get the ResultSize parameter added then we could significantly increase the result size but we would still need to run the job every hour to ensure we are getting all the Power Apps launch events.

**Comment by manuelap-msft** [comment]
I have just looked at this, and was actually not able to replicate the issue - I've looked at a date span of three months in my demo tenant, and the ResultCount was 667.  

If you go to the Test tab in the Custom Connector and enter a date there, does it always return just 100? 
![image](https://user-images.githubusercontent.com/55705669/76652074-bcac6500-655d-11ea-9632-3f98d08269ee.png)

This solution is in use with some of our larger customers, and they've not reported an issue with the Audit Log return size.

**Comment by jathorpe** [comment]
If I used the test tool I get a Result count of "ResultCount": 26361 but when I copy out the body and put into Notepad++ and count the number "Operations": "LaunchPowerApp" there is only 100 events.

What happens when you copy out the body and count the number of items? Are you getting 667 or 100?

**Comment by manuelap-msft** [comment]
I have spoken to a colleague of mine and we had one customer configure this in 10 minute intervals to work for their log size. I have not played around with configuring the ResultSize. I have added it to the backlog, in the meantime you should be able to edit the Custom Connector yourself if you wanted to change the config there.

**Comment by jathorpe** [comment]
I have played around OpenAPI file and creating a test verison of Audit Log connector. I have been able to get up to 400 events returned but after that pagination kicks in and it gives me an odata.nextLink to go out and grab the next batch of events. 

As I play around with the API I am struggling on what settings are available. I have worked with getting the UnifiedAuditLog through PowerShell but that isn't exactly the same as the API. Do you know where I can find the documentation on the Outlook API "/psws/service.svc/UnifiedAuditLog"? I can some information doing online searches but not the complete documentation.

**Comment by manuelap-msft** [comment]
In the latest release, we've switched to using https://docs.microsoft.com/en-us/office/office-365-management-api/get-started-with-office-365-management-apis
The solution is available here
https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Audit%20Log%20(MFA)

This is a more reliable and supported service, and also supports oauth (rather than just basic auth). I would recommend using this one if you can.

**Comment by petepuu** [comment]
Hi, 

I just ran into paging issue in my customer using latest MFA version 1.0.0.7 of custom connector. The limit of events in 1 request seems to be 200. We haven't test to run more frequently than once per day yet but I think we should anyway implement paging support in the custom connector and/or flow. The paging happens when response contains **NextPageUri** header, so I guess need to add another loop which runs until that header is not returned anymore 

![image](https://user-images.githubusercontent.com/8307644/78564258-d53e3100-7824-11ea-87d6-570e7be78894.png)

**Comment by manuelap-msft** [comment]
Great point, adding @Jenefer-PA to work on this fix!

**Comment by tmcg19** [comment]
Hi Also having same Issue, Limited to 100 returns with Basic Authentication method when run within the flow and 200 with Oauth. any update on this to make sure we get all details returned for accurate reporting

**Comment by JeneferM-MSFT** [comment]
Sorry we are unable to make the recommended change in custom connectors due to product limitations. You will need to change the frequencies of the run and change the intervals in the flow in order to paginate as recommended by Maneula above.

**Comment by JeneferM-MSFT** [comment]
Closing out old issues without existing action.
Thanks for using the CoE
