### ISSUE TITLE
[BUG]: Office 365 Management API 

### ISSUE THREAD

**Issue by davidvansickle** [microsoft/powerapps-tools#1103]
**Describe the bug**
We've setup two CoE Environments, LAB and PROD (but both are production environments)
When setting up the second CoE Environment (LAB), the Office 365 Management API is in the DLP Policy for both environments.  
The ConnectionID in LAB is: 

ConnectionId      : /providers/Microsoft.PowerApps/scopes/admin/environments/d8769078-f1c6-4c35-8b94-bda7883324fe/apis/shared_admin-5foffice-20365-20management-20api-5fb797dc59658ede5f/connections/3a15a9b779db40daa850701952624dea

The ConnectionID in PROD is: 

ConnectionId      : /providers/Microsoft.PowerApps/scopes/admin/environments/21bb34e3-13ce-4415-90e5-b928a8b7ae28/apis/shared_admin-5foffice-20365-20management-20api-5f810e8001d7a977c0/connections/ef44a3b9535543d9a5efb04cb25feada

**Component: OFFICE 365 Management API (custom connector)**
 - Solution Audit Logs
 - Version [2.5]
 - App or Flow [e.g. Admin | Child Sync ]

**To Reproduce**
1. Go to 'Admin | Child Sync ]'
2. Click on 'Turn On'
3. See error
Turn on failed. Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ApiPolicyDataFlowViolation","message":"Admin data policy 'COE' restricts the use of /providers/Microsoft.PowerApps/apis/shared_office365 with /providers/Microsoft.PowerApps/apis/shared_admin-5foffice-20365-20management-20api-5fb797dc59658ede5f.","extendedData":{"violation":{"policyId":"/providers/Microsoft.BusinessAppPlatform/scopes/service/apiPolicies/3a30e2d8-1c44-41e2-8ccf-869bce477326","policyDisplayName":"COE","type":"BusinessAndNonBusinessConnector","parameters":["/providers/Microsoft.PowerApps/apis/shared_office365","/providers/Microsoft.PowerApps/apis/shared_admin-5foffice-20365-20management-20api-5fb797dc59658ede5f"]},"additionalInfo":{}}}}".
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9801374/137155677-d3441d3d-846f-498e-8624-797fa92ba89b.png)

![image](https://user-images.githubusercontent.com/9801374/137155508-723897a4-edfe-4453-9e65-75687dfc368b.png)

**Additional context**
The Audit Logs work fine in our Production environment 

Custom connectors get real confusing when they are environment specific, I'm wondering if I need to create a whole new Azure AD App Registration for the connector in the new environment?

**Comment by davidvansickle** [comment]
Moved to correct forum for CoE Starter Kit.

**Comment by jjg133** [comment]
Having the same issue!
