### ISSUE TITLE
[BUG]: Request fails when sender is not part of Teams

### ISSUE THREAD

**Issue by DmitryVorobyov** [microsoft/powerapps-tools#111]
**Describe the bug**

CrisisCommunication.Request flow fails on the last step (Notify the team of the request) if request is sent by a user, who is not a member of the team in Teams. 

The failure is only visible if opening CrisisCommunication.Request flow, neither the user nor the team owner or "Crisis communications admin" are notified.

**To Reproduce**

1. Make the powerapp available to all users
2. Open the app using an account that is not a member of the CrisisCommunicationApp team in Teams and send a request
3. CrisisCommunication.Request flow fails on the last step with the following error:

_The sender with objectId 'GUID' is not a member or an owner of the team._

**Note:** this happens regardles of whether the team is configured as public or private.

**Expected behavior**
1. User needs to be aware that their requiest has failed (needs to see an error message)
2. If a user is required to join the team before they are able to send requests, the error mesage should explain that and (ideally) give them an option to do so.

**Interface:**
 - Browser: Edge Chromium and Chrome
 - Version date: 2020.12.03

**Comment by DmitryVorobyov** [comment]
Update: even if a user is made team member the error persists. The error only goes away if a user is made team owner.

**Comment by mr-dang-msft** [comment]
Hi @DmitryVorobyov,
We have revised the flow in the most recent version. Can you import the CrisisCommunication.zip file for the app which contains the flow? After that, you will need to configure the trigger of the flow to use the connection of the account that will receive the requests.
![image](https://user-images.githubusercontent.com/39354102/76680065-c4422d00-65a2-11ea-868b-3b4ba58b4f24.png)
