### ISSUE TITLE
CoE Audit Log table not showing any data

### ISSUE THREAD

**Issue by timgiard** [microsoft/powerapps-tools#1114]
The Audit Log table within our CoE model-driven app does not contain any data. Our "Admin | Sync Audit Logs" and "[Child] Admin | Sync Logs" flows have been set up (Along with the Office 365 Management API) and are turned on. Both flows are running successfully each day since August but we are still not getting any data in the Audit Log table. Any ideas why this may be?

Please let me know if you need any more info.

Thanks,
Tim

**Comment by timgiard** [comment]
Following up here - I think I posted this issue in the wrong section. I've just re-posted it here: https://github.com/microsoft/coe-starter-kit/issues/1508

**Comment by NPrice99** [comment]
Hi check the custom connector - there is a bug in the product itself (NOT CoE) where the Custom Connector connection disappears and you have to recreate the connection.

**Comment by NPrice99** [comment]
Check this out https://github.com/microsoft/coe-starter-kit/issues/1146

**Comment by manuelap-msft** [comment]
Hello,

yes, this repo is no longer in use for the CoE starter kit and we do not monitor here anymore. Please raise issues here https://github.com/microsoft/coe-starter-kit/issues - I won't transfer this one as I see you've already raised it and got help!

Thank you
Manuela
