### ISSUE TITLE
Code Review App - review problem

### ISSUE THREAD

**Issue by beatrizlourenco7** [microsoft/powerapps-tools#1115]
I wonder if the Code Review app would have any limitations on errors and msapp file size. 
Because it works with some apps, it shows me the review, but there are two apps that they are stuck only in the processing stage and it shows me nothing.  I have already waited for more than hours and nothing comes back. 

I put in the attached image showing that two apps were analyzed but the others were not

![image](https://user-images.githubusercontent.com/73603489/142667408-8461c6bb-e15d-472b-9bad-15a9567d185e.png)

Please, if you could tell me how I can see why this application is not being processed it would help me a lot. 

thank you in advance for your help

**Comment by Diego1135** [comment]
Hi,

I see there is an issue with file size with more than 9M, giving the error: "File too large. Max size 9M".
Will be this limit permanent or will be eliminated in the future?
The app is very useful, but not so much with this limit on file size.

Thank you!

**Comment by RajeevPentyala** [comment]
@Diego1135 File size limitation has been removed. Please try installing the latest version from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview).
@beatrizlourenco7 Looks like you are using an older version of the App. Please try installing latest version from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview)

**Comment by RajeevPentyala** [comment]
@Diego1135 and @beatrizlourenco7 Closing this issue as there was no further update from you. If you are still facing the issue, feel free to log a new bug.
