### ISSUE TITLE
Presence status report

### ISSUE THREAD

**Issue by nicez30** [microsoft/powerapps-tools#112]
During the final steps of advanced editing the presence status report (PowerBI) where a connection is made to the employee status list inthe underlying sharepoint I am presented with 'The column 'Id' of the table wasn't found'.

**Comment by sl1207** [comment]
Hi, it is beucase there isn't any record in CI_Employee Status.
Try to add a value manually and it will work.
This list collects data from user status update.

**Comment by nicez30** [comment]
> Hi, it is beucase there isn't any record in CI_Employee Status.
> Try to add a value manually and it will work.
> This list collects data from user status update.

Thanks I tried this but no success unfortunately.

**Comment by nicez30** [comment]
> > Hi, it is beucase there isn't any record in CI_Employee Status.
> > Try to add a value manually and it will work.
> > This list collects data from user status update.
> 
> Thanks I tried this but no success unfortunately.

My apologies that does in fact work thank you however I still cant record wfh or ooo via the app to populate the underlying SharePoint list

**Comment by mr-dang-msft** [comment]
Hi @nicez30,
In the Edit Query screen, you may need to ensure you're not viewing the data anonymously:
![image](https://user-images.githubusercontent.com/39354102/76837544-fd231180-67ef-11ea-8c72-0f62ec21de15.png)
Can you change the login to your Microsoft account?
