### ISSUE TITLE
Microsoft.PowerApps.CodeReview - ReviewRequest.RequestStatus not updated 

### ISSUE THREAD

**Issue by hacarra** [microsoft/powerapps-tools#1121]
On Microsoft.PowerApps.CodeReview App, the ReviewRequest.RequestStatus is not been updated to "Completed" when processing a msapp file. It is only updated to "Completed" when the app exists in the instance.

I  manually set the RequestStatus from blank to "Completed" in order to review the report

**Comment by RajeevPentyala** [comment]
@hacarra Please try installing the latest review tool from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview)

**Comment by RajeevPentyala** [comment]
@hacarra Hope your issue resolved after installing the latest version. Closing this issue as there was no further update from you. If you are still facing issue, feel free to log a new bug or reopen the same issue.
