### ISSUE TITLE
Microsoft.PowerApps.CodeReview import failing

### ISSUE THREAD

**Issue by warrenroscoe** [microsoft/powerapps-tools#1125]
Hi,
I'm trying to import ArchitectureReview_1_0_0_43.zip to my environment and I just get a big red message "Something went wrong. Please try again later.".
What are the pre-requisites for importing the app and/or are there any more detailed instructions on how to import.
I've tried this in two different tenants and still get the same error. Not easy to troubleshoot the error with no additional info.
Thanks in advance.

**Comment by RajeevPentyala** [comment]
@warrenroscoe Please try installing the latest tool from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview). You must install 'Creator Kit Solution' first as prerequisite. Follow the instructions mentioned [here](https://github.com/microsoft/powerapps-tools/blob/master/Tools/Apps/Microsoft.PowerApps.CodeReview/readme.md)

**Comment by RajeevPentyala** [comment]
@warrenroscoe Closing this issue as there was no further update from you. If you are still facing issue, feel free to log a new bug.
