### ISSUE TITLE
[BUG]: Audit Logs Were Collected but Some Missed Due to Truncated Results

### ISSUE THREAD

**Issue by dragunwing** [microsoft/powerapps-tools#1126]
**Describe the bug**
I receive the following email notification when trying to collect audit logs on my large tenant. 

_Your audit logs were collected but some were missed do to truncated results in this run . 
You will need to use a smaller interval to gather all logs. 
Current chunking size: 1 Minute_ 

Most environments are being logged except for the large, default environment.  I've set the TimeInterval-Unit value to 1 minute.  How do I set a smaller interval to collect the logging information?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Audit Log Solution
 - Version 2.6
 - Admin | Sync Audit Logs & [Child] Admin | Sync Logs flows

**To Reproduce**
It occurs every time the Admin | Sync Audit Logs flow runs.

**Expected behavior**
The logs should be collected without the email stating that I need smaller chunks.

**Screenshots**
![AuditLogError](https://user-images.githubusercontent.com/11412139/151051142-80e5ee4f-f57b-4883-9329-2c45552e90ec.png)

**Comment by manuelap-msft** [comment]
This repo is no longer used for the CoE Starter Kit, please raise your issue here: https://github.com/microsoft/coe-starter-kit/issues/new?assignees=Jenefer-Monroe&labels=coe-starter-kit&template=coe-starter-kit-bug.yaml&title=%5BCoE+Starter+Kit+-+BUG%5D+your+issue
