### ISSUE TITLE
[BUG]: Office 365 Outlook Connection issue

### ISSUE THREAD

**Issue by erashutosh711** [microsoft/powerapps-tools#113]
**We are trying to import Crisis Communication App(GCC) in PowerApp but getting some error and not able to proceed further**
In my organization we have office 365 subscription(SharePoint, PowerApp & Power Automation) for all employees but we have not migrated email to office 365 outlook.
I can see in deployment guide that It doesn't require office 365 outlook connection as you can see in screen, but while I am importing CrisisCommunicationGCC.zip solution it is asking to provide mandatory connection for office 365 outlook as you can see in second screen.
![image](https://user-images.githubusercontent.com/62140449/76618799-ddb38c80-6542-11ea-9f41-9c68f0a7c121.png)

![image](https://user-images.githubusercontent.com/62140449/76618704-a7760d00-6542-11ea-99e5-9c6e876733b6.png)

Please let me know whether I am using wrong solution package or wrong deployment guide.

**Comment by mr-dang-msft** [comment]
Hi @erashutosh711,
The app and its flows as they are packaged work with Office 365 Outlook. The Outlook connector is used for sending email receipts of work status updates, requests, and updating the auto replies for your inbox. 

As each email connector has a different syntax, and email is used in both apps and flows, it is a non-trivial task to support multiple email services. We are not looking to package it with another connector at this time.

**Comment by erashutosh711** [comment]
Dear Team,

We don't have office 365 outlook mailbox for all employees and also we can't create that as per company policy. We have hybrid solution for mailbox which uses mailflow but I am not sure whether it will work with or not. I configured the app by using one mailbox which was created in office 365 outlook for testing. Now once users open the app it asks for office 365 outlook login and doesn't accept the users credentials but accepts the same user which has office 365 outlook mailbox.
Please let me know how can we use our existing settings and configurations.
your quick response is highly appreciated.
