### ISSUE TITLE
Admin | Sync Template v3 - Action 'Get_Maker' failed

### ISSUE THREAD

**Issue by maron1209** [microsoft/powerapps-tools#1139]
**Describe the bug**
Hi. My Admin | Sync Template v3 fails when running. Setting up the CoE, it initially ran, however, on the second run the flow failed along with the other sync templates.

**Component (please tell us which flow or app you are experiencing issues with):**
 -  Core
 - January 2022 version
 - Admin | Sync Template v3 

**To Reproduce**
1. Go to core
2. Click on Admin | Sync Template v3
3. Scroll down to Store environments in the CDS entity > Check if legacy environment > Get maker
4. See error below

> {
  "error": {
    "code": "NoResponse",
    "message": "The server did not receive a response from an upstream server. Request tracking id '08585567290480689261520781454CU117'."
  }
}

**Expected behavior**
Excepted the flow to find the maker of the app/flow and continue.

**Screenshots**
Screenshot attached.

![image](https://user-images.githubusercontent.com/57493048/154021731-d8558979-1ebe-4495-8249-2fcf8000f5e2.png)

**Additional context**

**Comment by cfosund** [comment]
I'm having the exact same issue after the seventh successful run.

Component (please tell us which flow or app you are experiencing issues with):
Core (3.31)
January 2022 version 
Admin | Sync Template v3

**Comment by manuelap-msft** [comment]
This repo is no longer used for the CoE Starter Kit. Please raise your issues here: https://github.com/microsoft/coe-starter-kit/issues
