### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by myatix** [microsoft/powerapps-tools#1148]
Hi All,

I have been using the Microsoft Doc setup guide to setup the COE solution. I would just like to point out the guide is somewhat out of date. There appears to be a fair bit of information missing in the guide, or at least it doesn't appear to be in chronological order, compared to the actual setup process.

EG: The requirement for an App Registration or (Key Vault) is needed when you upload the solution as you are asked to provide an things like App ID etc but this is first mentioned much later in the setup guide. This makes the configuration more difficult as you have to hop around the document a bit.

I hope you find the feedback useful!

**Comment by manuelap-msft** [comment]
This repo is no longer monitored for the CoE Starter Kit. Please raise issues via our dedicated repo: https://github.com/microsoft/coe-starter-kit/issues
