### ISSUE TITLE
Unable to get documentation on new environment variables

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#1150]
We upgraded COE starter kit to latest version but we are unable to get documentation on below new environment variables:

InnovationBacklogLink
Cleanup Old Objects App URL
Power Platform Maker Group ID
Environment Request Admin App Url
Community URL
Flow Approvals URL

Could you please help us on this

**Comment by manuelap-msft** [comment]
This repo is no longer used or monitored by the CoE starter kit team. The new repo where you can raise issues is https://github.com/microsoft/coe-starter-kit/issues/new/choose 

We have updated all our docs to point to the new repo; please update your bookmarks if you still have the old link. Thank you.
