### ISSUE TITLE
Power Automate Management  connector consent not suppressing

### ISSUE THREAD

**Issue by sandeep-mamidala** [microsoft/powerapps-tools#1151]
[](url)Hi Team,

We observed Power Automate Management  connector consent not suppressing while rest all connectors are logged in automatically with logged in user .

For Power Automate, you can (for now) establish connections in multipe ways - first party and third party (deprecated)

So when the deprecated third party connection will be [removed.](url)
<img width="912" alt="PowerAutomateConsentIssue" src="https://user-images.githubusercontent.com/29742556/166928225-521f42f2-9bbb-4687-a58a-81ef35b9b408.PNG">

**Comment by manuelap-msft** [comment]
Hello,

this issues here are only monitored for issues related to the tooling made available in this repository. For product features, please raise a support request through official channels https://docs.microsoft.com/en-us/power-platform/admin/get-help-support, or for questions you can post in our community forums https://powerusers.microsoft.com/

Manuela
