### ISSUE TITLE
Error when creating single environment policies

### ISSUE THREAD

**Issue by Rene-** [microsoft/powerapps-tools#1152]
Hi, 

I've been having trouble creating single environment policies. I was able to create two manually, but it's giving me the "The provided data loss prevention policy's type only allows selection of one environment." error. 

I can't find any documented issue on this other than a user having problems a year while using the DLP editor. https://githubhot.com/repo/microsoft/powerapps-tools/issues/964
According to this, it was a known issue a year ago. Has there been a fix since then? 

Please let me know if this isn't the proper forum for asking these questions. 

Thank you

**Comment by manuelap-msft** [comment]
Hello,

this issues here are only monitored for issues related to the tooling made available in this repository. For product features, please raise a support request through official channels https://docs.microsoft.com/en-us/power-platform/admin/get-help-support, or for questions you can post in our community forums https://powerusers.microsoft.com/

Manuela
