### ISSUE TITLE
[BUG]: Right nav button on the gallery does not work

### ISSUE THREAD

**Issue by khinethinzarsoe** [microsoft/powerapps-tools#117]
**Describe the bug**
Right Navigation button of 'Company news' does not work for the first time to navigate to right to see hidden news cards. But can be navigate after click "read more" and back to company news page.
Tested with laptop. 

**To Reproduce**
1.Create company news more than 4 or 5.
2. run the app and go to company news page
3. click right navigation button. 
4. Older news didn't show.
5. click " read more" and 'back"
6. click right navigation button.
7. older news are shown.

**Expected behavior**
navigate to older news

**Screenshots**

**Interface(please complete the following information):**
 - Browser : chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)

![CrisisCom_V2_NewsNavigationBug](https://user-images.githubusercontent.com/61639654/76700180-741eb400-66e3-11ea-8870-3d103fd70bcf.png)

**Comment by spamit** [comment]
We are also having the same problem.

**Comment by mrdbradshaw** [comment]
We are seeing the same issue.

**Comment by rvanluttikhuisen** [comment]
Seeing the same issue as well:
- Right arrow DOES NOT scroll right through the news cards when using a desktop browser
- Left arrow DOES scroll left through the news cards when using a desktop browser
- Clicking on the whitespace of a card then using left and right keyboard arrows does scroll the news cards left and right.
- Left and right work fine on mobile devices

https://powerusers.microsoft.com/t5/Building-Power-Apps/ShowNavigation-does-not-work-Horizontal-gallery/td-p/420188

**Comment by mr-dang-msft** [comment]
The latest version has changed the behavior to scrollbars instead. 

In the OnVisible property of the Home Screen, you can configure the colStyles collection to change show_gallery_scrollbars and show_gallery_nav to "true" or "false" if you want to override this behavior.

**Comment by rvanluttikhuisen** [comment]
Awesome! We will update our test app this morning then prod.
