### ISSUE TITLE
Getting number of PVAs in teams environment 

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#1176]
We are building lifecycle management for teams environments in our tenant and we want to see if there are any PVAs created in each environment. Could you please let us know where we can get this data on number of PVAs created in each teams environment.

**Comment by manuelap-msft** [comment]
This repo is no longer monitored for the CoE Starter Kit. Please raise issues via our dedicated repo: https://github.com/microsoft/coe-starter-kit/issues
