### ISSUE TITLE
Whether can we use COE Toolkit installation account enabled with MFA , If not could you please let us know the details why it not recommended

### ISSUE THREAD

**Issue by RamKan2019** [microsoft/powerapps-tools#1178]
As per the installation Pre-Requisite preparation we working on creating new service account (Power Platform admin role service account ) . Whether it is recommended to enable MFA for this account or not. If not recommended please kindly provide the details what will be the issue. Since centralized team expecting exact reason for creating Service account without MFA.

**Comment by manuelap-msft** [comment]
This repo is no longer monitored for the CoE Starter Kit. Please raise issues via our dedicated repo: https://github.com/microsoft/coe-starter-kit/issues
