### ISSUE TITLE
[BUG]: 401 Authorization has been denied for this request - Test StartSubscription Custom Connector Error

### ISSUE THREAD

**Issue by subhasishmukhopadhyay** [microsoft/powerapps-tools#1179]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Center of Excellence - Audit Logs]
 - Version [2.10]
 - App or Flow [Custom Connector - Office 365 Management API]

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/53398533/187738265-bb09c80b-376f-404d-8e5a-73c4ab1c415d.png)

![image](https://user-images.githubusercontent.com/53398533/187738414-6f17d855-360e-420a-bcbc-5604bcc2ffac.png)

**Additional context**
- Performed all troubleshooting as per the documentation (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)
- User is not connected to any VPN
- All configurations like Client ID, Secret, tenant ID and App Registration verified

**Comment by davidvansickle** [comment]
Did you grant the account access for the role to read the audit logs?

**Comment by subhasishmukhopadhyay** [comment]
Yes I have configured all well; next day I have created one more connection with this custom connector and this started working not sure what hapenned with initial instance.

**Comment by manuelap-msft** [comment]
This repo is no longer monitored for the CoE Starter Kit. Please raise issues via our dedicated repo: https://github.com/microsoft/coe-starter-kit/issues
