### ISSUE TITLE
PowerApps Code Review - Stale code issues

### ISSUE THREAD

**Issue by dave-jorgensen-xrm** [microsoft/powerapps-tools#1185]
I created a new code review of a canvas. Edited an issue, to change one of the items found in the review. Published app (several times).
Re-doing code review for that canvas app, it still shows the same error, even though the code it is finding no longer exists in the app.
Tried deleting the existing code reviews, closing and re-opening the code review app, all still seems to show the original issues, even though the no longer exist.

What am I missing, to refresh the code review? Thanks

**Comment by RajeevPentyala** [comment]
@dave-jorgensen-xrm Can you please retry by installing the latest 'Code Review Tool' from [Here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview)

**Comment by RajeevPentyala** [comment]
@dave-jorgensen-xrm Closing this issue as there was no further update from you. If you are still facing issue, feel free to log a new bug or reopen the same issue.
