### ISSUE TITLE
[BUG]: New review is showing processing status while it should be completed

### ISSUE THREAD

**Issue by vishalgoyal2472** [microsoft/powerapps-tools#1189]
While I am creating new review , its showing me in the processing status and after waiting many days its not completing.

**To Reproduce**
Open "Power Apps Review Solution"
Click on Apps in the left
Play Power App Review tool app
Click on New at the top left
Create New review

**Expected behavior**
Review should be completed 

**Screenshots**
![image](https://user-images.githubusercontent.com/36663570/199404659-e83a38b0-7977-4842-80ec-c547d4f21d95.png)

**Interface(please complete the following information):**
 - Browser- Chrome
 - Version -107.0.5304.88 (Official Build) (64-bit)

**Comment by ariclevin** [comment]
Experiencing the same issue as Vishal with version 1.0.0.81.

**Comment by RajeevPentyala** [comment]
@ariclevin Can you try by deploying the latest version of "Code Review Tool' from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview).

With @vishalgoyal2472 there was incompatible file uploaded.
