### ISSUE TITLE
[BUG]: I'm unable to make the connections in the Power Apps to install Crisis Communication App

### ISSUE THREAD

**Issue by VasuBonda** [microsoft/powerapps-tools#119]
Within the PowerApps, I'm unable to import CrisisCommunication.zip and connect to the Microsoft Teams.

![Unable to establish connections for Import button to highlight and import](https://user-images.githubusercontent.com/62208400/76703746-c2c05400-66cb-11ea-8826-3103f2d277e4.PNG)

**To Reproduce**
As per the instructions provided in this link
https://docs.microsoft.com/en-gb/powerapps/maker/canvas-apps/sample-crisis-communication-app#prerequisites

5. Complete the Import Setup for Microsoft Teams Connection and Office 365 Users Connection by selecting the appropriate connections using Select during import hyperlink. You may have to create new connection if it already doesn't exist.

6. Select Import.

Browser - Microsoft Edge

**Additional context**

**Comment by mr-dang-msft** [comment]
Hi @VasuBonda,
To complete this step, you will select the connection set up for Office 365 Users and Office 365 Outlook. If they do not exist, you will need to click create the connection. This launches another browser tab where you can create the needed connections.

And once the connection is created, you can return to the import experience and refresh the list. Select the connections you had just created (or an existing one).

Please clarify more details if I am misunderstanding you.

**Comment by mrosecook** [comment]
We have on premise exchange and cannot create connection to Office 365 Outlook.   FYI the documentation and screen shots do not show Office 365 outlook connection is required.   How do I skip that related source in the "Crisis Communication" import?

**Comment by mr-dang-msft** [comment]
Hi @mrosecook,
The first version of the app did not include email receipts for submissions. We updated the app to send a receipt of the date submission for personal records. We can update the screenshot to reflect this change.

As mentioned in Issue #113, removing the Outlook capabilities for another connector is not a version we're able to support right now.
Link: https://github.com/microsoft/powerapps-tools/issues/113
