### ISSUE TITLE
[BUG]: Unable to locate the asset for Flow

### ISSUE THREAD

**Issue by deba0912** [microsoft/powerapps-tools#120]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Interface(please complete the following information):**
 - Version date[e.g. 2020.04.03]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by deba0912** [comment]
Upload the DeploySPList.zip package from the GitHub repository.
This is where I am stuck as I can't locate the above file

**Comment by mr-dang-msft** [comment]
Hi @deba0912,
The required zip files are inside the CrisisCommunicationPackage.zip file.
![image](https://user-images.githubusercontent.com/39354102/76737853-c208db80-6726-11ea-95ae-61397bdcb1f2.png)

Find the package at https://aka.ms/CrisisCommunicationSolution.
Click the CrisisCommunicationPackage.zip file. 
Then click download.

Let me know once you have been able to locate it.

**Comment by deba0912** [comment]
thank you
