### ISSUE TITLE
[BUG]: Code Review Version 108 Missing Dependency

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#1205]
**Describe the bug**
Code Review Version 108 has a missing dependency and due to that, we are not able to import a new version. 

    <MissingDependencies>
      <MissingDependency>
        <Required type="61" schemaName="cat_expandmenu_icon" displayName="cat_expandmenu_icon" solution="Active" />
        <Dependent type="62" schemaName="cat_CodeReviewAdmin" />
      </MissingDependency>
      <MissingDependency>
        <Required type="61" schemaName="msdyn_/Images/AppModule_Default_Icon.png" displayName="msdyn_/Images/AppModule_Default_Icon.png" solution="AppModuleWebResources (2.5)" />
        <Dependent type="80" schemaName="cat_CodeReviewAdmin" displayName="Code Review Admin" />
      </MissingDependency>
      <MissingDependency>
        <Required type="66" schemaName="cat_PowerCAT.Icon" displayName="cat_PowerCAT.Icon" solution="Active" />
        <Dependent type="300" schemaName="cat_powerappsreviewtoolv1_931e7" displayName="Power Apps Review Tool" />
      </MissingDependency>
      <MissingDependency>
        <Required type="66" schemaName="cat_PowerCAT.Nav" displayName="cat_PowerCAT.Nav" solution="Active" />
        <Dependent type="300" schemaName="cat_powerappsreviewtoolv1_931e7" displayName="Power Apps Review Tool" />
      </MissingDependency>
      <MissingDependency>
        <Required type="66" schemaName="cat_PowerCAT.Pivot" displayName="cat_PowerCAT.Pivot" solution="Active" />
        <Dependent type="300" schemaName="cat_powerappsreviewtoolv1_931e7" displayName="Power Apps Review Tool" />
      </MissingDependency>
      <MissingDependency>
        <Required type="66" schemaName="cat_PowerCAT.SearchBox" displayName="cat_PowerCAT.SearchBox" solution="Active" />
        <Dependent type="300" schemaName="cat_powerappsreviewtoolv1_931e7" displayName="Power Apps Review Tool" />
      </MissingDependency>
      <MissingDependency>
        <Required type="66" schemaName="MscrmControls.Grid.GridControl" displayName="MscrmControls.Grid.GridControl" solution="BaseCustomControlsCore (9.0.2210.4014)" />
        <Dependent type="68" id="{493f4ad7-fe62-4339-bff5-e45e012d5bc4}" />
      </MissingDependency>
      <MissingDependency>
        <Required type="66" schemaName="MscrmControls.Grid.GridControl" displayName="MscrmControls.Grid.GridControl" solution="BaseCustomControlsCore (9.0.2210.4014)" />
        <Dependent type="68" id="{7a14c418-29c7-4760-9305-6d5e8341cb16}" />
      </MissingDependency>
    </MissingDependencies>

**Comment by andrewgaskins** [comment]
I am seeing the same thing when I tried to install today. I have Creator Kit 1.0.20221205.2 installed in this environment.

Thanks!
Andrew

**Comment by RajeevPentyala** [comment]
@andrewgaskins Can you try installing the latest version [ArchitectureReview_1_0_0_109_managed.zip](https://github.com/microsoft/powerapps-tools/blob/master/Tools/Apps/Microsoft.PowerApps.CodeReview/ArchitectureReview_1_0_0_109_managed.zip) of the 'Code Review Tool'?
Please post solution import error log if you encountered the issue again.

**Comment by RajeevPentyala** [comment]
Closing this issue as there is no further update from either @AkashPatel136 or @andrewgaskins. If any once else face similar issue, please log a new issue.
FYI @slaouist
