### ISSUE TITLE
Import and set up the Crisis Communication app[BUG]: issue title

### ISSUE THREAD

**Issue by zinag** [microsoft/powerapps-tools#121]
Complete the Import Setup for Microsoft Teams Connection and Office 365 Users Connection by selecting the appropriate connections using Select during import hyperlink. 

After upload the CrisisCommunication.zip package.
Does not possible to complete Import, no connection does not appears for Microsoft Team Connection and  Office 365 Users Connection .
Also I cannot create a new connection. 
I have premium license for Power Apps in Office 365

I'll very appreciate for help.
Zina

**Comment by mr-dang-msft** [comment]
Hi @zinag,
You will need to create a new connection for Microsoft Teams and any other connectors you do not have connections for.

![image](https://user-images.githubusercontent.com/39354102/76740733-950af780-672b-11ea-878a-26edda58c969.png)
Click Create New. It launches a new browser tab. Add the needed connection(s) there. Return to the previous screen and click Refresh so you can see the newly created connection.

**Comment by zinag** [comment]
Hi Brian,
Thank you very much, it's work, I have tried to add SharePoint connection🤔
