### ISSUE TITLE
[BUG] Code Review Tool - Cannot scroll to last App Review

### ISSUE THREAD

**Issue by Dlutchy** [microsoft/powerapps-tools#1214]
**Describe the bug**
In the Power Apps Review Tool the scroll bar cuts off just before the last App Review row is available.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Review option for a Project
2. Ensure there is more than a screen full of apps.
3. Scroll down to last App
4. Last row is cut off so cannot see the Review Option for that App

**Expected behavior**
Expect to see las row in Apps list to be able to access the Review

**Screenshots**
![2022-12-29 13_44_01-](https://user-images.githubusercontent.com/67881320/209896592-5c08d1cf-79fa-49c2-a0f1-9a9621aecb54.png)

**Desktop (please complete the following information):**
 - Browser Edge

**Comment by RajeevPentyala** [comment]
@Dlutchy Thanks for reporting. This issue will be fixed in next release.

**Comment by RajeevPentyala** [comment]
@Dlutchy Closing this issue as its fixed in last release. If you face any more issues, feel free to log a new bug.
