### ISSUE TITLE
[BUG] Security Management: Import Failure due to PCF Configuration "Property icon is not declared in the control manifest."

### ISSUE THREAD

**Issue by allandecastro** [microsoft/powerapps-tools#1215]
**Describe the bug**

When importing the Security Role risk assessment, it fails due to a configuration regarding the PCF Control used (even if the PCF is already installed in the target environment). I tried in two different vanilla environments.

**To Reproduce**

1. Install the PCF Solution from Diana and Creator Kit.
2. Publish
3. import the Security Role Risk management solution 

**Expected behavior**

The solution is well imported with a green notification saying the solution was successfully imported.

**Screenshots**

Error message:
![image](https://user-images.githubusercontent.com/9749002/210092199-c15d4a00-52be-43f0-957b-b06b0e5a3fc9.png)

**Comment by Ravi-Chada** [comment]
Thanks for reporting this @allandecastro. Let me setup some time with you next week to check out the import process. Based on the error message looks like the PCF control Solution - Colorful option set might not have been available for the Risk assessment solution.

**Comment by allandecastro** [comment]
Thanks for your answer :)
Sure not problem, i tried to import it again but still facing the same error :/

**Comment by Ravi-Chada** [comment]
Reinstalling the Colorful Option set solution helped complete the import the Risk Management solution.
