### ISSUE TITLE
Run Flow fails with null request

### ISSUE THREAD

**Issue by dgcDarrenClark** [microsoft/powerapps-tools#122]
**Describe the bug**
Whilst executing "Run Flow" within instructions it fails with a null request.

**To Reproduce**
1. Follow instructions at https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app.
2. At step "Run the SharePoint list deployment flow" under heading "Create a home for your data" click on "Run Flow" inside of Flow interface.

**Expected behavior**
That stage of instructions completed. Ie SharePoint lists created.

**Screenshots**
![flow-failure](https://user-images.githubusercontent.com/20906795/76741822-14b6b780-6768-11ea-9ad7-3c4ebfc058ff.png)

**Interface(please complete the following information):**
Edge latest
W10 latest

**Additional context**
Account is global admin for all online services and MFA disabled.

**Comment by audrieMSFT** [comment]
There is a dependency for the flow to run. Would you please confirm that the site variable towards the top of the flow, as a full site address within it? The site address would be a dependency, so that the flow knows where to put the new lists. Thank you for letting us know if that is the issue.

**Comment by dgcDarrenClark** [comment]
Hi Audrie and thanks for the reply :)

The site variable is filled in with the correct URI:
![site-uri](https://user-images.githubusercontent.com/20906795/76940697-a0f4e600-68f2-11ea-99d6-8cbc58a07297.png)

Here's the site itself running to show it's up:
![site-up](https://user-images.githubusercontent.com/20906795/76940720-ace0a800-68f2-11ea-90ff-70cdd621a3eb.png)

Any help gratefully received.

ATVB

Darren

**Comment by dgcDarrenClark** [comment]
Management have decided to not go ahead with this given the issues we've had with setting it up so far.
