### ISSUE TITLE
Code Review Admin has no Patterns

### ISSUE THREAD

**Issue by MajdMaghamez** [microsoft/powerapps-tools#1222]
I followed the installation instructions, and I am able to run both 
Code review admin and Power Apps review tools however when I submit an app for a review 
In the review checklist I get nothing (blank)
I go to the code review admin and notice there are no patterns, I tried older version but I am still getting the same thing.
I googled excel pattern list to import and I can' t find any 
I tried creating a pattern there aren't any documentation that explain how so.

Any help will be appreciated 
Thank you

**Comment by WinOnMarco** [comment]
I have noticed the same in the latest release (1.0.0.118).

**Comment by sbellew9** [comment]
I updated to this new version of the solution this week, I'm experiencing the same thing, empty pattern table.  I could create manual patterns in the model driven app but I'd rather not come up with that list on my own.

**Comment by gupneos** [comment]
Same issue here on 1.0.0.118, no patterns created on import
Also reproduced with 1.0.0.115

**Comment by NColes** [comment]
You can import the patterns using the cat_patterns_rules(_v2) web resource and a Dataflow as a quick workaround, but this would be great to have fixed.

**Comment by sbellew9** [comment]
Ours is on 1.0.0.118, I believe I did it as an upgrade.

**Comment by MajdMaghamez** [comment]
Thanks @RajeevPentyala, it was version 1.0.0.118 and a fresh install

**Comment by RajeevPentyala** [comment]
> Thanks @RajeevPentyala, it was version 1.0.0.118 and a fresh install

@MajdMaghamez 
Score 0 issue has been fixed in the latest build. Please get the latest solution from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview) and let me know the outcome.

**Comment by nelsoncerqueira** [comment]
@RajeevPentyala 1.0.0.124 has the same issue. I've installed it from a clean install and the patterns are empty.

**Comment by RajeevPentyala** [comment]
@nelsoncerqueira Patterns gets created automatically when you submit your first 'Review'. Can you recheck the patterns by submitting a 'Review' first.

**Comment by nelsoncerqueira** [comment]
> @nelsoncerqueira Patterns gets created automatically when you submit your first 'Review'. Can you recheck the patterns by submitting a 'Review' first.

Thank you, that was exactly my issue. All good.

**Comment by RajeevPentyala** [comment]
Thanks @nelsoncerqueira . Closing this issue.
