### ISSUE TITLE
Scores not calculating, defaults to grade F

### ISSUE THREAD

**Issue by myesri2022** [microsoft/powerapps-tools#1226]
@RajeevPentyala Tool is not reporting any score % after completing review

**Comment by RajeevPentyala** [comment]
@myesri2022 Can you please provide following details?
- Version of 'Code Review Tool'
- File type (i.e., Solution or .msapp) you uploaded.
- Would it be possible to share the file you tested?

I recommend you install the latest version from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview)

**Comment by myesri2022** [comment]
Pls see below.

***@***.***

Best,
Ajay Nellipudi | IST Collaboration & Communications
T. 909.369.4124 | ***@***.******@***.***>

**Comment by donaldngongang1** [comment]
I can't see the Code Review CheckList, and in the Code Viewer section i can't see all my controls

**Comment by RajeevPentyala** [comment]
> I can't see the Code Review CheckList, and in the Code Viewer section i can't see all my controls

Score 0 issue has been fixed in the latest build. Please get the latest solution from [here](https://github.com/microsoft/powerapps-tools/tree/master/Tools/Apps/Microsoft.PowerApps.CodeReview) and let me know the outcome.

**Comment by RajeevPentyala** [comment]
This issue has been fixed in the last release and you can find similar issue [here](https://github.com/microsoft/powerapps-tools/issues/1222). Closing this issue and If you are still facing issues, feel free to log a new bug or reopen the same issue.
