### ISSUE TITLE
[BUG]: Unable to run Flow

### ISSUE THREAD

**Issue by powershellpr0mpt** [microsoft/powerapps-tools#123]
**Describe the bug**
When trying to follow the procedure, I get stuck running the flow as described [in the documentation](https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#run-the-sharepoint-list-deployment-flow).

**To Reproduce**
1. Select the imported flow
2. Make sure the connection to SharePoint is correct
3. Make sure you've changed the variables accordingly
4. Make sure you've enabled Location services in both the browser [Edge Chromium] and Windows 10
5. Click on Run to Run the flow.
6. Get error message `The input body for trigger 'manual' of type 'Request' did not match its schema definition. Error details: 'Invalid type. Expected String but got Null.'.`
7. The Runs section displays there's a problem with the flow's trigger.
8. Click on Fix trigger to find more information, get error message `BadRequest`
```json
{
  "type": "object",
  "properties": {
    "location": {
      "type": "object",
      "properties": {
        "address": {
          "type": "object",
          "properties": {
            "city": {
              "title": "City",
              "type": "string",
              "x-ms-dynamically-added": false
            }
          },
          "required": [
            "city"
          ]
        },
        "coordinates": {
          "type": "object",
          "properties": {
            "latitude": {
              "title": "Latitude",
              "type": "number",
              "x-ms-dynamically-added": false
            }
          },
          "required": [
            "latitude"
          ]
        }
      }
    }
  },
  "required": [
    "location"
  ]
}
```

**Expected behavior**
I expect the flow to start running and creating the required components/lists within SharePoint

**Screenshots**
![alt text][step6]  
![alt text][step7]  
![alt text][step8]

**Interface(please complete the following information):**
 - IE Edge Chromium
 - Version 80.0.361.66 (Official build) (64-bit)

[step6]: https://powershellpr0mpt.com/wp-content/uploads/2020/03/2020-03-16-10_17_03-Run-History-_-Power-Automate.png "Issue step 6"
[step7]: https://powershellpr0mpt.com/wp-content/uploads/2020/03/2020-03-16-10_16_43-Run-History-_-Power-Automate.png "Issue step 7"
[step8]: https://powershellpr0mpt.com/wp-content/uploads/2020/03/2020-03-16-10_15_19-Run-History-_-Power-Automate.png "Issue step 8"

**Comment by audrieMSFT** [comment]
This is related to a requirement within the trigger. To resolve this issue, delete the trigger from the flow (the first object) using the 3 dots at the top right of the trigger. Then search for another manual button and add it again. Save and try the flow after that. Please let me know if that works for you.

**Comment by powershellpr0mpt** [comment]
That does the trick!
![alt text][ItWorks]

[ItWorks]:https://powershellpr0mpt.com/wp-content/uploads/2020/03/2020-03-25-09_27_06-Run-History-_-Power-Automate.png "It works"

**Comment by audrieMSFT** [comment]
Perfect! So glad that's working now.
