### ISSUE TITLE
[FEATURE] Security Management: Minor Feature Requests

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#1230]
**Describe the Feature**
We love the app, and we are using the app for our security risk assessment for our Dataverse security roles. We would like to provide some feedback on some minor & major improvements.

**Screenshots**
**Security Role Page** - we would like to be able to search for the user and also for the team. Also, for Team, it shows an ID of teams instead of a team display name. It will be good to see a team display name.
![image](https://user-images.githubusercontent.com/110540273/215172109-ca5ebacd-0bb4-4f30-a89e-2ca6fe9a531f.png)

**Teams Page** - It will be good to see a team's display name instead of the team's ID. 
![image](https://user-images.githubusercontent.com/110540273/215173924-d7b5304c-8f32-476b-8cd0-677229c0a2b4.png)

**Security Role Summary Page** - It will be good to see which Power Apps have which security role assigned because currently, it is hard to find which Power Apps have which security role assigned. 

I have deployed Solution version 2.0 in my environment.

Thank you

**Comment by Ravi-Chada** [comment]
Ack the ask. I will take this as a backlog item for next release - search for the user and also for the team.

As for the team's name, it is showing the value from the Name field. The value is not a GUID, which means probably the naming convention in your case may be giving a name with ID. Can you check again? Its consistent across the screens so please check your team's record name field. 

Security Role Summary Page - It will be good to see which Power Apps have which security role assigned - Are you looking for the names of the Power Apps as well? Right now, I am just showing the number of apps that are related to that Security Role. Let me know if my assumptions are correct, I will add that to backlog as well to show app names when you hover over the field.

**Comment by AkashPatel136** [comment]
@Ravi-Chada 

Sorry, I updated the solution to the 2.0 version and did not take effect right away, but I do see a Team name, not GUID. But When I Click on any Team it does not select the option I have selected, it goes back to 1st record. 

Security Role Summary Page - Yes that is true, we would like to see the application name.

One More feedback - The user Profile page is taking a long time like 20 to 30 minutes to load; can this be improved so it does not take this much long time.

**Comment by Ravi-Chada** [comment]
@AkashPatel136 - sorry I lost track of this. Thank you for your feedback. I have a couple of pages that need improvement on performance. I will add them to backlog. 

Regarding "Also, It will be good to see how many high, Medium and Low roles have in a security role" - these will light up only after an assessment is complete. You can click on the top shield icon to start an assessment if one is not already present.

**Comment by AkashPatel136** [comment]
I am looking for the search feature, Power Apps Name on security role, User Profile page does not load which I have discussed on this thread.

**Comment by AkashPatel136** [comment]
@Ravi-Chada Any update on when this will be available. Can we at least have this feature implemented before the new Dataverse Connector because new Dataverse connector will be GA in Sep 2023. We are not able to use the app as much we want because of the below roadblocks.

1. User Profile Page - The user Profile page is taking a long time like 20 to 30 minutes to load; can this be improved so it does not take this much long time.
2. Security Role Summary Page - It will be good to see which Power Apps have which security role assigned because currently, it is hard to find which Power Apps have which security role assigned.
3. Security Role Page - we would like to be able to search for the user and also for the team. Also, for Team, it shows an ID of teams instead of a team display name. It will be good to see a team display name.
image
![image](https://github.com/microsoft/powerapps-tools/assets/110540273/aec06871-6eef-4dbd-b451-8580ef04b1b2)
