### ISSUE TITLE
[BUG] Security Management: Cannot Add users to Field Security Profile

### ISSUE THREAD

**Issue by rich835** [microsoft/powerapps-tools#1235]
**Issue**
Cannot Add users to Field Security Profile

**To Reproduce**
1. When in Field Security Management
2.  I select the user, then click the "Add to this field security profile" button,
3. The pane closes with no message and the user is not added.

**Expected behavior**
User should be added to profile

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Edge (also tried with Chrome)
 - Version 110.0.1587.56 (Official build) (64-bit)

**Additional context**
Can remove users from the profile no problem, but unable to add them via the app.

**Comment by Ravi-Chada** [comment]
Acknowledge. Let me check on this amd get back.

**Comment by Ravi-Chada** [comment]
@rich835 - I am not able to replicate this, I would like to connect with you and see if we can work on this together. Can you reach out, post a message with a good time to connect on https://www.linkedin.com/in/ravi-chada/.

**Comment by Ravi-Chada** [comment]
@rich835 - I have a new zip file uploaded and ready for you. Please check the latest download. This should fix the issue.
