### ISSUE TITLE
[BUG]: Microsoft Teams Dependency On Import Canvas Package

### ISSUE THREAD

**Issue by karthickDhanapal** [microsoft/powerapps-tools#124]
**Description**
On Import crisis package into our environment, there is a dependency of Microsoft Teams on import. Is there any possibility to remove the teams dependency. 

**To Reproduce**
1.Import Package into environment 

**Expected behavior**
Remove the dependency of Microsoft Teams dependency on import

**Comment by hitendra72** [comment]
@karthickDhanapal 
Hey Karthick - I sent you an email on how to remove the dependency.

**Comment by juldzx** [comment]
@hitendra72 
Hello, I'm interested by removing this dependency also.
Thank you

**Comment by hitendra72** [comment]
@juldzx  
there are 2 ways - 
1. import the apps in a tenant which has Teams (like a trial tenant), edit the flows to remove use of Teams, save the apps, export them; and import them in your main tenant
2. edit the JSON files of the zip file (cumbersome and error prone as it is a manual process)

**Comment by juldzx** [comment]
I tried solution 2, but I did not succeed and it was quite painful.
I did not think about solution 1, thank you hitendra72 !
