### ISSUE TITLE
Request for Info: Crisis Communications Team

### ISSUE THREAD

**Issue by AdriaanJvR** [microsoft/powerapps-tools#125]
It is not clear if the Crisis Communications Team that should be created in Microsoft Teams should be a Private or Public team.

See https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#create-a-central-crisis-management-teams-team. 

Should the new team be Private or Public?

What impact will it have on the functionality of the App?

**Comment by mr-dang-msft** [comment]
If you choose to turn on this feature flag for requests, when someone submits a request, a receipt is sent to the requester and this response team. Please update to the latest version which includes a flow that can submit requests to the team by automation.
