### ISSUE TITLE
Admin | Sync Template v2 (Flows) authentication issue

### ISSUE THREAD

**Issue by mazubapl** [microsoft/powerapps-tools#127]
Dear Team,

i am trying to get CoE starter kit in one of our environments working. I am nearly done, but there are Flows, which use the "Connections", e.g. the Admin | Sync Template v2 (Flows) flow. My username, with which i try to create this connection is a Power Platform Admin user, but i am still not able to initialize this connection and get the following error message:
![image](https://user-images.githubusercontent.com/62251020/76769890-5e6dc500-679d-11ea-952b-869c24299afb.png)
May you please advise, which kind of roles are still missing?

Thanks a lot in advance for your kind help!

**Comment by manuelap-msft** [comment]
A Tenant Admins needs to consent to this connector being used - once that's done, the connector can be used by makers or admins both. It's do with the permission scope the Flow connector is published with (https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-admin-consent).

To run the Flow, you only need Power Platform Service Admin permission but to use the connector, a Tenant Admin needs to consent to it's usage.

**Comment by JeneferM-MSFT** [comment]
Hi there. I'm checking in to see if this issue was resolved for you. 
Thanks,
Jenefer

**Comment by JeneferM-MSFT** [comment]
Closing out old issues without existing action. Please let us know if you have issues in the future!
