### ISSUE TITLE
[BUG]: Request flow is not responding

### ISSUE THREAD

**Issue by kempert** [microsoft/powerapps-tools#129]
Hello, the Request Help Funktion is not Responding, in the POWERAPP the Connector chrisis.Communication.Request is not requested. 

The Connector Logic Flow is not realiesed jet.

**Comment by mr-dang-msft** [comment]
Hi @kempert,
It sounds like when you run the Request flow, it is not successful.

We updated the flow on 2020-03-12 with a new flow. Can you download the latest version of CrisisCommunicationPackage.zip and reimport the CrisisCommunication.zip file?
