### ISSUE TITLE
Location Issue when Embedded on Teams Desktop App

### ISSUE THREAD

**Issue by ggfieder** [microsoft/powerapps-tools#130]
Location (Lat/Long) not captured when embedded on Teams Desktop App. It works fine on Teams web.

![image](https://user-images.githubusercontent.com/15006690/76818046-84e43c80-683f-11ea-9a0b-718b24e836a4.png)

**Comment by audrieMSFT** [comment]
In the Settings of the desktop app, is location enabled?

![image](https://user-images.githubusercontent.com/26467011/77533478-2c6ef980-6e54-11ea-8909-3f646f72b039.png)

**Comment by ggfieder** [comment]
> In the Settings of the desktop app, is location enabled?
> 
> ![image](https://user-images.githubusercontent.com/26467011/77533478-2c6ef980-6e54-11ea-8909-3f646f72b039.png)

Yes the location is enabled on my teams desktop app.  
![image](https://user-images.githubusercontent.com/15006690/77596377-c9a25e80-6f36-11ea-880e-9dadd55d17dc.png)

**Comment by mr-dang-msft** [comment]
Hi @ggfieder ,
This is a known limitation at this time:
https://powerusers.microsoft.com/t5/Building-Power-Apps/Crisis-Communication-solution-feedback/m-p/506778#M154320
