### ISSUE TITLE
[BUG]: Status update date range - Submit button not working

### ISSUE THREAD

**Issue by mr-zedly** [microsoft/powerapps-tools#131]
**Describe the bug**
When a user selects the date range to update their status, the "Submit" button does nothing.

**To Reproduce**

1. Open the Crisis Communication app
2. Click on "Share Status"
3. Choose either "Working from home" or "out of office"
4. Select a date range the click "Submit"
5. Nothing happens

**Expected behavior**

**Screenshots**
![Crisisapp-UserStatusUpdate](https://user-images.githubusercontent.com/60603322/76818088-c7fed980-6858-11ea-804e-4b5813e7dedf.png)

**Interface(please complete the following information):**
 - Browser  - Edge
 - Version date - 44.17763.831.0

**Smartphone (please complete the following information):**

**Additional context**
Date Range Screen, btnDateRange, Advanced, Action, OnSelect - shows a red cross with the message "Invalid argument type"
![InvalidArgument](https://user-images.githubusercontent.com/60603322/76818567-08ab2280-685a-11ea-870d-c5e9a74a6c73.png)

**Comment by mr-dang-msft** [comment]
Hi @mr-zedly ,
From your screenshot of the formula, it looks like you're running an old version of the app or applied an old formula.

Can you download the latest CrisisCommunicationPackage.zip file from this github repository and reimport CrisisCommunication.zip?

**Comment by mr-zedly** [comment]
thanks @mr-dang-msft . I tried updating the app, but got multiple errors so I blew it away and re-installed from scratch. That got it working. Much appreciated.
