### ISSUE TITLE
[BUG]: Crisis Communication Admin - Can't add links

### ISSUE THREAD

**Issue by mr-zedly** [microsoft/powerapps-tools#132]
**Describe the bug**

**To Reproduce**
Open the Crisis Communication Admin app
click on "Links"
click on "Create New Link"
Error message "no data source provided"

**Expected behavior**
a form appears to add a new Link item to the underlying SharePoint list

**Screenshots**
![NoDataSource](https://user-images.githubusercontent.com/60603322/76821035-ecf74a80-6860-11ea-97f1-05e49f841495.png)

**Interface(please complete the following information):**
 - Browser - Edge
 - Version date-  44.17763.831.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mr-dang-msft** [comment]
Hi @mr-zedly,
This may have occurred when you created a link and decided to edit it right away. The Form was pointing to GalleryTips.Selected which may have been refreshing when the new item was created. 

I've changed the behavior of each form to have a static item and each successful submission to refresh the data source upon success. This will be available in the next version.

**Comment by mr-zedly** [comment]
thanks @mr-dang-msft I tried updating the app, but got multiple errors so I blew it away and re-installed from scratch. That got it working. Much appreciated.

**Comment by jennyosh88** [comment]
Hi @mr-dang-msft , I face the same issue - No Data Source Provided, Is there a way to fix this without going through the whole re-installation steps. Thanks!!!
