### ISSUE TITLE
[BUG]: Access Crisis PowerApp without MFA

### ISSUE THREAD

**Issue by RamanathanCT** [microsoft/powerapps-tools#133]
We could able to access the crisis powerapp connecting to network but we couldn't access the app connecting from personal network

**Comment by mr-dang-msft** [comment]
Hi @RamanathanCT,
Can you share more about what you experienced and your steps?

You generally will not need to do this, but if you're having access issues, you may need to whitelist certain IP addresses:
https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/limits-and-config#ip-addresses
