### ISSUE TITLE
[BUG]: Something went wrong. Please try again later.

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#134]
**Describe the bug**
When Importing latest Package (16/03/2020) I get the error "Something went wrong. Please try again later."

**To Reproduce**
1. Go to 'make.powerapps.com.'
2. Click on 'Import Package at the top of the screen.'
3. browse to the downloaded package, click on Import.

**Expected behavior**
The Package should be imported successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/76856385-0f7e6900-684b-11ea-9fa7-fe2485eeac24.png)

**Interface(please complete the following information):**
Microsoft Edge - Microsoft Edge 44.18362.449.0

**Comment by mr-dang-msft** [comment]
Hi @NPrice99,
The CrisisCommunicationPackage.zip file contains zip files for each of the parts:
- Crisis Communication app
- Admin app
- flows, etc.

Can you extract the zip that you want to update?

**Comment by NPrice99** [comment]
Hi @8bitclassroom

I was able to import the CrisisCommunication.zip file successfully.

Thanks for your help.

Nigel
