### ISSUE TITLE
Suggestion: Documentation in Markdown instead of Word docs

### ISSUE THREAD

**Issue by ltwlf** [microsoft/powerapps-tools#135]
I suggest to use Markdown instead of Word for all documentations and instructions. Word/Binary is really not great in Git.

Best wishes & stay healthy!
Christian

**Comment by manuelap-msft** [comment]
Thank you! Great suggestion! We are actually looking at moving the documentation and instructions to docs.microsoft.com soon. I'll close this comment for now but will update here with a link once we've moved to docs!

**Comment by ltwlf** [comment]
That's great! I think I also have a good solution for the issue with the basic auth. How can I contribute?

**Comment by manuelap-msft** [comment]
We have just updated the repo with a new solution to work with MFA: https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Audit%20Log%20(MFA)

Would be great to get your feedback on this!

**Comment by ltwlf** [comment]
Hey Manuela,

it works - good job! :)

Suggestion for an security improvement. For the current CoE setup you only need the following permissions App Permissions from Management API:
ActivityFeed.Read (delegated)
![image](https://user-images.githubusercontent.com/965766/77200883-c0a32e80-6aeb-11ea-8146-29d67237654d.png)

Best wishes 
Christian
