### ISSUE TITLE
[BUG]: "Cds" datasource in Power Platform CoE App for PowerBI can not be changed

### ISSUE THREAD

**Issue by kpinhack** [microsoft/powerapps-tools#136]
![Anmerkung 2020-03-17 155251](https://user-images.githubusercontent.com/20367079/76868773-b1ac4a00-6867-11ea-81fb-39e04b0da9b8.jpg)
![Anmerkung 2020-03-17 155251a](https://user-images.githubusercontent.com/20367079/76868777-b244e080-6867-11ea-8547-3ebda836e2f9.jpg)
![Anmerkung 2020-03-17 155251b](https://user-images.githubusercontent.com/20367079/76868782-b244e080-6867-11ea-84ce-47be55f263e1.jpg)

**Describe the bug**
The app for PowerBI contains a dataset with a Data source credentials for "Cds" with extensionDataSourcePath "https://contosocoe.crm.dynamics.com", which can not be deleted or updated. Entering the environment URL (as described in the documentation does add a second "Cds" data source, but the data of the actual environment is not shown in the dashboard.

**Component (please tell us which flow or app you are experiencing issues with):**
 - "New Power Platform CoE Toolkit Tenant Adoption" app for PowerBI
 - Version 12 of 16 Mar 2020

**To Reproduce**
1. Get the "New Power Platform CoE Toolkit Tenant Adoption" app via App Source
2. Go to app once it finished installing
3. Click "Connect" on "Get started with your new app"-dialog
4. Enter the correct EnvironmentUrl ( not "https://contosocoe.crm.dynamics.com" )
5. Confirm your login to finish setting up the app
6. Open the dashboard and see the message "You're viewing sample data. After the data is connected and refreshed, reload the page

**Expected behavior**
See actual data of the specified environment, not sample data

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
A new version has just been published to App Source, let me know if you are still experiencing issues!

**Comment by kpinhack** [comment]
With the new version of the app there is only one Cds Connection, but the Dashboard still shows demo data. 
Error Message: "The 'admin_companyname' column does not exist in the rowset. Table: admin_COESettings
![Anmerkung 2020-03-17 155251g](https://user-images.githubusercontent.com/20367079/76980235-3dda7200-6939-11ea-8430-fb86a8bf6e81.jpg)
"

**Comment by manuelap-msft** [comment]
Can you try and upgrade the Core components solution that has updated entities with the fields you got an error for - it was just uploaded:
https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_32_managed.zip

Sorry there was a disjoint in publishing the Power BI template and the Core solution
