### ISSUE TITLE
[QUESTION]: Steps to upgrade app

### ISSUE THREAD

**Issue by GradyD** [microsoft/powerapps-tools#137]
With the latest version released, how does one go about upgrading to this version properly without losing everything?

**Comment by mr-dang-msft** [comment]
Hi @GradyD ,
I can update the readme later with steps.

So that you're unblocked, here's some steps:
https://github.com/MicrosoftDocs/powerapps-docs/issues/1148#issuecomment-600213848

**Comment by mr-dang-msft** [comment]
Readme.md has been updated with instructions for importing an updated app or flow 👍
aka.ms/CrisisCommunicationSolution
