### ISSUE TITLE
[BUG]: Step 2: Configure the CoE Settings Entity

### ISSUE THREAD

**Issue by lapr0ct0r** [microsoft/powerapps-tools#139]
**Describe the bug**
All install steps up to this point went fine.  When I select the Power Platform Admin View - the Play button is grayed out. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - Version - CenterofExcellenceCoreComponents_1_23_managed(Invalid Argument Fix)
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**
According to the installation instructions, I should be able to open the Power Platform Admin View model driven app in Play mode - to see the Configure option in the left navigation.

**Screenshots**
![image](https://user-images.githubusercontent.com/62308962/76901030-752d1e00-6868-11ea-9b78-3feb5afbf413.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Click on just the app name (Power Platform Admin View) to open the app, rather than on the ... and Play.
