### ISSUE TITLE
Can't modify the solution items as suggested in the documentation.

### ISSUE THREAD

**Issue by devinprejean** [microsoft/powerapps-tools#14]
Step 3 option 1 in the documentation suggest I can modify the connections or update actions however the Edit option is not available.
At the top of the screen I'm getting this message.

> You cannot directly edit the components within a managed solution. If the managed properties for solution components are set to allow customization, you can edit them from another unmanaged solution.
![image](https://user-images.githubusercontent.com/12751900/60106076-295ea580-972a-11e9-93ed-e039c462a250.png)

**Comment by Craig-Humphrey** [comment]
I suspect you need to make sure you imported the unmanaged version of the ZIP file.

**Comment by devinprejean** [comment]
I realized about a week later I was trying managed solution. I’m sorry for not updating sooner.
