### ISSUE TITLE
[BUG]: CrisisCommunication.Request BadGateway

### ISSUE THREAD

**Issue by michael-kubala** [microsoft/powerapps-tools#141]
**Describe the bug**
Running the CrisisCommunication.Request Flow times out on the "Notify the Team of the request" action.  It times out with an error "BadGateway". 

**To Reproduce**
1. Follow steps to import the Flow and update the required fields
2. Run the Flow

**Expected behavior**
The Flow runs successfully.

**Screenshots**

**Interface(please complete the following information):**
Microsoft Edge Version 82.0.446.0 (Official build) dev (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
There was another error with this Flow where I had to escape the quotes in the comments first because it broke the JSON. That doesn't matter though because eventually I stripped out the body except for the bare minimum to get it to work, but I still get BadGateway. Also it seems like we don't need the Team or Channel ID since you can just populate those manually in the interface. I've tried using both the IDs and using the interface to select the Team / Channel. I am an owner on the Team and am connecting under my account. 
![BadGateway1](https://user-images.githubusercontent.com/62298597/76910990-90565880-687d-11ea-98c2-e8135739476a.png)
![BadGateway2](https://user-images.githubusercontent.com/62298597/76910996-93e9df80-687d-11ea-851f-2fb1987e621a.png)

**Comment by mr-dang-msft** [comment]
@michael-kubala,
Can you clarify what changes you have made to the flow?

**Comment by michael-kubala** [comment]
> @michael-kubala,
> Can you clarify what changes you have made to the flow?

Hey there. Thanks for the quick response. I did some more testing last night and this morning and it looks like something is wrong with my Team. Flow doesn't have access to write as a Flow Bot to my Team in any channel. I can write adaptive cards to other Teams, but not my Crisis Management Team which was created exactly the same way. Not sure what the issue is, but after unsuccessfully trying to get Flow added to my Team, I'm giving up and going to recreate the Team. Hopefully that fixes the issue. 

I do think there are a couple of issues with the Flow though. For one, I originally got JSON errors with the "Notify team of request" action until I modified the Comments variable with the following to escape the quotes:

replace(triggerBody()?['body'],'"','\"')

Also I feel it is much easier to just type in the Team and Channel names in the "Notify team of request action" so you don't need the Team ID and Channel ID variables. This saves you the step of having to parse out the Team and Channel ID from the URL.

Thanks.

**Comment by michael-kubala** [comment]
Got the Flow working. The issue was that the Team was private. Had to make it public, add the Flow app to the Team, then make it private again. 

Also escaping the quotes in the trigger Body, did not work. It just dumped raw HTML into the card. I switch to use the body preview and that works better.
