### ISSUE TITLE
[BUG]: Power BI Dashboard columns do not exist in rowset

### ISSUE THREAD

**Issue by m3ngi3** [microsoft/powerapps-tools#144]
**Describe the bug**
(First of all: love this toolkit and what you are doing 💪👍)
When connecting the Power BI Dashboard from sample data to actuel environment of which I am Environment Admin / System Admin besides being Global Admin --> the data source errors with the notification: _The 'admin_companyname' column does not exist in the rowset. Table: admin_COESettings._ & _The 'admin_applastlaunchedon' column does not exist in the rowset. Table: App._

**Component (please tell us which flow or app you are experiencing issues with):**
 - Center of Excellence Starter Kit = Version 2020.02.12 (got argument error)
 - CenterofExcellenceCoreComponents_1_23_managed(Invalid Argument Fix)
 - Power BI Dashboard from App Source = https://appsource.microsoft.com/en-US/product/power-bi/powerapps_pbi.powerapps_coe

**To Reproduce**
1. Install Power BI Dashboard from App Source link above
2. Open Workspace in Power BI of New Power Platform CoE Toolkit Tenant Adoption
3. Select Connect your data from Notification ribbon to stop viewing sample data
4. Enter URL of environment where Core Components is installed
5. Connect through OAuth2 (Privacy level None) with account that is Global Admin & Power Platform Admin
6. Check Datasets status and see error notification mentioned above
7. Sample data shown in Dashboard

**Expected behavior**
To show real data of environment where CoE kit is installed

**Screenshots**
![CoEStarterKit_Error_PowerBI_Dataset_Column_not_existing](https://user-images.githubusercontent.com/47530580/76976440-3e243e80-6934-11ea-9bcb-e73ac65d285d.png)

**Additional context**
Tried Update app but issues remain

**Comment by manuelap-msft** [comment]
Thanks for the feedback! 
You were too fast! We just updated the Core components solution that has updated entities with the fields you got an error for. Could you try updating the solution please!
 https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_32_managed.zip

**Comment by m3ngi3** [comment]
LOL
I already saw an update on Toolkit level but because that was about MFA, I just reported this one. WIll check the individual component and get back asap 🤓

**Comment by m3ngi3** [comment]
Center of Excellence - Core Components 1.32 indeed does not have this issue 🙏

**Comment by manuelap-msft** [comment]
That's awesome, thanks for confirming so quickly!
