### ISSUE TITLE
Unable to setup COE Starter Kit Power BI

### ISSUE THREAD

**Issue by RonRohlfs** [microsoft/powerapps-tools#146]
Hi,

We're stuck on Step 6: Configure the Power BI Dashboard in CoE Starter Kit - Setup Instructions.docx. We tried both the "Get the Power BI Dashboard from App Source", and "Configure the Power BI Dashboard using the PBIX file" options.

A screen capture history for the App Source option is in COEStarterKitPowerBISetup.zip.

It looks like login credentials are accepted, and the setup appears to follow what is described in the instructions. However, we only see the sample data. It appears there is no connection to our data after repeated attempts to connect.

The pbix file option uses the Edit Queries button in the Ribbon of Power BI Desktop. However, this button does not seem to exist in our recently updated version of Power BI Desktop.

[COEStarterKitPowerBISetup.zip](https://github.com/microsoft/powerapps-tools/files/4350259/COEStarterKitPowerBISetup.zip)

**Comment by manuelap-msft** [comment]
In the new version of Power BI, can you try going to Transform Data
![image](https://user-images.githubusercontent.com/55705669/77008861-dafbd180-695e-11ea-882c-ab9e19311a56.png)

And then selecting OrgUrl there and updating it (from there the steps should be similar to the ones outlined in the documentation)
![image](https://user-images.githubusercontent.com/55705669/77008913-ed760b00-695e-11ea-8ba4-16c2e96b8078.png)

It looks like the ribbon has recently changed with a new version of Power BI Desktop, so we do need to update our documentation to reflect that.

**Comment by RonRohlfs** [comment]
Hi,

Was able to set the OrgUrl, and Publish, the .pbix. Published it to the existing New Power Platform CoE Toolkit Tenant Adoption workspace. The new screen capture shows our data with me as the #1 App Maker. :-)

However, it also still shows, "You're viewing sample data. After the data is connected and refreshed, reload the page."

We removed the sample report "Dashboard-PowerPlatformAdminDashboard_2020-02-12" from Reports, but are not allowed to Delete the sample dataset, "Dashboard-PowerPlatformAdminDashboard_2020-02-12" from Datasets.

So the "Get the Power BI Dashboard from App Source" option won't work for us, and the "Configure the Power BI Dashboard using the PBIX file" sort of works for us.

Thanks,

Ron

![COEStarterKitPowerBISetup18](https://user-images.githubusercontent.com/62032705/77011672-a1f53a00-6929-11ea-82dd-f9780fcb25a4.png)

**Comment by manuelap-msft** [comment]
The AppSource option is still very new, looks like we might need to fix some bugs there! When you refresh the page, does the warning message go away? 

It does look like it refreshed properly with your environments, so might just be an issue with the warning message being displayed incorrectly.

Congrats on being Top Maker!

**Comment by RonRohlfs** [comment]
Hi,

Yup ctrl-F5 did it.

The AppSource option definitely seems more user friendly. I'll be looking for a chance to try it again,

Thanks again for all your help!

Ron

**Comment by manuelap-msft** [comment]
Awesome, really appreciate your detailed error messages and explanations - very helpful for us updating the documentation!
