### ISSUE TITLE
CoE Starter Kit - Admin | Sync Template Flow - invalid references cause errors when Flow runs

### ISSUE THREAD

**Issue by mathyousee** [microsoft/powerapps-tools#15]
In the managed solution and the standalone file, the *Flow - Admin | Sync Template* Flow has references in certain actions that reference fields that do not exist. When these paths are followed in the Flow it causes an error. 

Below are the 4 steps I followed to fix the errors.

*1) Removed value from admin_objectid field **Create Maker record for SYSTEM** step*
Old Value: guid()
New Value: [blank]
Reason: Field does not exist in entity schema. It appears to be extraneous to the function of the rest of the Flow.
![image](https://user-images.githubusercontent.com/418063/60355749-c6247b80-9994-11e9-8e44-5877d667cc52.png)

*2) Updated value in **Set systemMaker with new record** step*
Old Value: admin_objectid
New Value: Maker [Dynamic content from _Create Maker record for SYSTEM_ step] 
Reason: The referenced field does not exist in entity schema, using the actual record GUID from the immediate previous step. 
![image](https://user-images.githubusercontent.com/418063/60355839-ff5ceb80-9994-11e9-8b7a-ca0ca391f486.png)

*3) Removed value from admin_environmentcreated field **Upsert Environment (SYSTEM maker)** step*
Old Value: Created Time
New Value: [blank]
Reason: Field does not exist in entity schema. The actual field is corrrectly set and can be seen under the "advanced options" of the step.
![image](https://user-images.githubusercontent.com/418063/60355790-e18f8680-9994-11e9-87ac-f1c192132bc4.png)

*4) Removed value from admin_objectid field **Upsert Connector Maker record** step*
Old Value: guid()
New Value: [blank]
Reason: Field does not exist in entity schema
![image](https://user-images.githubusercontent.com/418063/60355776-da687880-9994-11e9-9a88-3c1e4adf19ee.png)

This appears to be in the version of the Flow in the Managed solution as well as the separate Flow that can be imported.

**Comment by mathyousee** [comment]
Note, this is similar to #13 and includes several additional items related to the same issue

**Comment by devinprejean** [comment]
I could have saved myself a lot of frustration if I would have come here first! I found the same issues a while back. Thanks for sharing!

**Comment by denisem-msft** [comment]
@mathyousee  thanks for reporting this. This should no longer be a problem in the most recent update, please download the latest version and test if you can.
