### ISSUE TITLE
[BUG]: No Documentation on Setup

### ISSUE THREAD

**Issue by russgove** [microsoft/powerapps-tools#157]
Hi,
The document at https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/CoE%20Starter%20Kit%20-%20Documentation%20and%20Setup%20Instructions.pdf

says

![image](https://user-images.githubusercontent.com/2412956/77213124-14a81600-6ae0-11ea-8c38-5e31505dd1d4.png)

The link is not clicakbe in the PDF! Where are the setup docs?

**Comment by manuelap-msft** [comment]
All documentation can be found in the top level CoEStarterKit GitHub folder https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit

There is a doc called Setup Instructions there
