### ISSUE TITLE
[BUG]: [Crisis Communication] "chat" button on the adaptive card in Teams

### ISSUE THREAD

**Issue by asifkhawaja** [microsoft/powerapps-tools#158]
**Describe the bug**
"chat" button on the adaptive card in Teams does not work as expected. When I click on the "Chat" button, it opens the chat with the Flow itself and not with the user who sent the request message.

**Expected behavior**
We expect the "Chat" button to open the chat with the user who sent the request, just like the "Email" button as it opens the new email to that user.

<img width="427" alt="Untitled" src="https://user-images.githubusercontent.com/40859317/77241625-e4c85200-6c48-11ea-8c4b-7f81f0617626.png">

**Comment by mr-dang-msft** [comment]
Hi, 
This happens when you try to start a chat with yourself. It will return to the current view of your chat.

**Comment by asifkhawaja** [comment]
Hey Brian,
Good to see your message. Thanks and that makes sense. I was actually trying to open the chat from the message I sent myself. It works as expected with other users.
