### ISSUE TITLE
CoE Starter Kit - Admin | Sync Template Flow - Model Apps not upserted

### ISSUE THREAD

**Issue by mathyousee** [microsoft/powerapps-tools#16]
After running the Admin | Sync Template Flow the Model-driven PowerApps were not being listed for any environment. The fix I applied is to modify the *Run-after* property for the **Condition: Check if Environment has CDS for Apps** action from *Is Skipped* to *Is Successful*.

![image](https://user-images.githubusercontent.com/418063/60453071-b22b8480-9bf5-11e9-86a6-86a61d2ac00c.png)

After making this change, I was able to re-run the Flow and all Model-driven PowerApps were correctly upserted.

**Comment by denisem-msft** [comment]
@mathyousee, thanks for reporting this issue. We're working on this and will update here with a subsequent flow dedicated to this task.

**Comment by DS2019** [comment]
I, too am having issues and did change the "Is Skipped" to "Is Successful." After I make the change and save, it says that: 
'admin_recordmodified' is no longer present in the operation schema. It should be removed before the workflow is re-saved.
General error:
Error
Action 'Upsert_Environment_(SYSTEM_maker)' failed

I can't seem to get any of the versions of the Admin |Sync Template to work - the Sync Template V2 runs, but I don't see any App data in the PowerBI dashboard. 

Any help greatly appreciated!

**Comment by manuelap-msft** [comment]
We have released a new version of the CoE Starter Kit today, where this should be fixed. I'm closing this issue, but please let us know if you're facing issues still.
