### ISSUE TITLE
[App not showing in the app setup policy]

### ISSUE THREAD

**Issue by JoaoLucindo** [microsoft/powerapps-tools#164]
I uploaded the zip exported in Power Apps portal to Microsoft Teams using the option "upload for Contoso". The app is showing in the app catalog for all users, however I was not able to setup the app policy in the Teams admin portal (I've waited for 12 hours)

![image](https://user-images.githubusercontent.com/23638259/77452610-e58def00-6dd4-11ea-9250-7db6bca90160.png)

![image](https://user-images.githubusercontent.com/23638259/77452712-06564480-6dd5-11ea-86e4-28c42e6b5481.png)

**Interface(please complete the following information):**
 - Browser [chrome]
 - Teams desktop client

**Additional context**

**Comment by Rahber** [comment]
It usually takes 12-24 hours for the app to appear in the teams.

**Comment by JoaoLucindo** [comment]
tks!
