### ISSUE TITLE
[BUG]:  Error submitting work status

### ISSUE THREAD

**Issue by timp3261** [microsoft/powerapps-tools#165]
**Describe the bug**
My colleague can't report the work status after clicking the submit button on Date Range Screen.
The screen will show "You did not successfully save your work status"

**To Reproduce**
1. Go to Date Range Screen
2. Click on Submit
3. See error

**Expected behavior**
"You successfully submitted your work status. An email has been sent to you with a summary."

**Screenshots**
![image](https://user-images.githubusercontent.com/47614603/77514307-8c47bd80-6eb1-11ea-8027-cf8757917493.png)

**Interface(please complete the following information):**
 - Browser Edge

**Additional context**

**Comment by audrieMSFT** [comment]
This submission depends on the list named: CI_Employee Status. Is it possible for you to validate that the list has been created, and that you have access to it?

**Comment by timp3261** [comment]
Hi AudrieMSFT,
Thanks for responding.
I can access CI_Employee Status without problem.
Other colleagues can submit the work status but myself, so probably is about authorization.
I didn't receive an email regarding the date range selected
PS: I can "Make a request" without problem.

**Comment by mr-dang-msft** [comment]
@timp3261 ,
Were you able to check the permissions on the list and submit dates successfully?

**Comment by timp3261** [comment]
@mr-dang-msft 
Thanks for help out.
I've changed the List Permission on SharePoint from read to edit so the members can now submit the work status without error!
