### ISSUE TITLE
[BUG]: Flow: CrisisCommuniction.Request showing not connected. How to solve it ?

### ISSUE THREAD

**Issue by pravindmaha6** [microsoft/powerapps-tools#166]
![image](https://user-images.githubusercontent.com/62536395/77516183-e1d19980-6eb4-11ea-8cec-73f7210bb439.png)
![image](https://user-images.githubusercontent.com/62536395/77516326-278e6200-6eb5-11ea-8d39-331c6448f941.png)

In the app the connection for flow CrisisCommuniction.Request showing not connected. Due to this the flow is not running. How to connect it back to the app ?

**Comment by audrieMSFT** [comment]
I do not believe that this will cause a problem. If you've followed the instructions on this page (search for .Request), you should be good: https://docs.microsoft.com/powerapps/maker/canvas-apps/sample-crisis-communication-app 

Have you seen any symptoms in the app that would indicate something is not working as expected?
