### ISSUE TITLE
[BUG]: Admin | Welcome Email - It never sends Welcome Email to new App and Flow owners.

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/powerapps-tools#167]
We are using Welcome Email Flow from COE Starter Kit . We want whenever someone creates a new PowerApp or Flow ; the owner should be notified via Outlook with the App Name details . We believe , this flow is capable of doing the same, but this flow is not working as expected.

 - Center of Excellence - Nurture Components
 - Latest Version
 - Admin | Welcome Email

**To Reproduce**
Create an Office365 group as mentioned in the COE Starter Kit Documentation and configured as Environment variables. Also saved the flow as "Copy of - Admin | Welcome Email"

1. Created a test app
2. Open "Copy of - Admin | Welcome Email" flow
3. Click on Edit
4. Run test to start the flow , it keeps on spinning but nothing happens and then it errors out as below :

![image](https://user-images.githubusercontent.com/62638075/77520275-f6a73080-6ea6-11ea-88ab-571f29966613.png)

![image](https://user-images.githubusercontent.com/62638075/77520486-4a197e80-6ea7-11ea-98ca-d94506111459.png)

**Expected behavior**
It should send email notifications whenever a new PowerApp or Flow is created. This is what we want to achieve using this flow.

**Comment by manuelap-msft** [comment]
This Flow gets triggered when a new Maker is detected. New makers are detected from the CDS "Maker" entity. This entity gets populated during the Sync of tenant resource, which is part of the core components (see Sync Template v2 (Apps) and Sync Template v2 (Flows). 

The only way to Test this flow using the Test action is to click Test and at the same time enter a new Maker in the Maker CDS entity to trigger the Flow.

**Comment by VimmiRawat** [comment]
Hi Manuela,

So, if I understood it correctly ; whenever a new PowerApp or Flow is created ; “Maker”  CDS entity detects a new entry . Right ? So, in our case; I do see all new Apps and Flows are getting added to Maker entity ; but even then Welcome Emails are not getting triggered.

Thanks & Regards,
Vimmi Rawat
Messaging & Collaboration Office 365 Design
Accenture Technology | Intelligent Cloud and Infrastructure | Infrastructure Services for Accenture
Contact No :+91 8884837711
Time Zone: Delhi (India) (GMT +05:30)

**Comment by manuelap-msft** [comment]
The Sync Template for Apps and Flows is set up to run daily overnight, so the Welcome email would get fired only once a day to all new makers that were detected.

**Comment by Jenefer-PA** [comment]
A new entry is only added to the Maker table if a flow or app is created by someone who has never created a flow or app in the past. If an existing Maker creates another flow or app, it will not create an entry, and will not trigger this email generating flow. This is because the scenario is to welcome Makers who are new to the technology. 

To see this visually, go to the Maker table and view the data. You will see each maker listed once along with an aggregate of the number of flows and apps they have made:
![image](https://user-images.githubusercontent.com/62659043/77559180-13c50a80-6e79-11ea-9ab4-27c32183391f.png)

To see this flow run, have someone not listed create a flow or app. 
For your scenario, of an email about a new flow or app from any Maker, whether they be new to the technology or not, you will want to use triggers on these two entities: PowerApps App, Flow.

Please let me know if this is unclear, happy to discuss further.

**Comment by JeneferM-MSFT** [comment]
Hi there. I'm checking in to see if this issue was resolved for you. 
Thanks,
Jenefer

**Comment by VimmiRawat** [comment]
Hi,

I did comment on this but can't see updated thread here. This flow never worked for us , and status is still the same . Even , when a new user created a flow ; he didn't receive any notification .

**Comment by JeneferM-MSFT** [comment]
Hey Vinmi, given the age of your install, and the amount of problems you are having, I would suggest you upgrade to the latest version of the CoE toolkit before we continue to work through issues.

I will also suggest that we close these issues as they change rather than continuing with a single issue for multiple concerns.
This one, for example, was originally to track an ask the flow did not work for existing makers. 

Please upgrade the toolkit, see how you proceed with the newer bits, and then post new issues for new problems you see.
Thanks
Jenefer

**Comment by VimmiRawat** [comment]
Hi Jenefer ,

This flow doesn't work and it never worked for us even if we didn't know initially what it was suppose to do . And status is still the same even after upgrading the solution . Can you please go ahead and re-open this ?

Regards ,
Vimmi
________________________________

**Comment by JeneferM-MSFT** [comment]
Can you please share a screenshot of the failing flow so we can see the error?

**Comment by VimmiRawat** [comment]
![Welcome_Error](https://user-images.githubusercontent.com/62638075/80915469-2b44bc80-8d70-11ea-9dbb-ca82075019c5.JPG)

**Comment by VimmiRawat** [comment]
Nothing happens and it's like this from the beginning . Multiple new users have created flows and power apps but no one received this Welcome email . I tried testing using Trigger the action now when new user created the flow but still no luck.

**Comment by JeneferM-MSFT** [comment]
Can you please validate that the user was not in the Makers table before you ran the test, and that they are in the Makers table after? Then also confirm the created on date for that maker is correct? 

Please share a screenshot like the below showing the maker that you expected to trigger the flow

![image](https://user-images.githubusercontent.com/62659043/80915704-ea658d00-8d08-11ea-98b5-5a098dfb5911.png)

**Comment by manuelap-msft** [comment]
Just wanted to clarify how the Welcome Email works:

The Sync Flows - Sync Flow (Flow) and Sync Flow (Apps) - sync your tenant resources into CDS entities called PowerApps App, Flow and **Maker**. These flows run over night (check the Admin | Sync Template v2 recurrence trigger to find out when yours is set to run) and add or update resources in the CDS entity. 

The Admin | Welcome Email runs when an item is created in the Maker table - so it does not run instantly when someone creates a new app or flow, but instead runs the next day when your Sync flows have run. For it to work, your Sync Flows need to be configured and Switched On.

**Comment by VimmiRawat** [comment]
![Maker1](https://user-images.githubusercontent.com/62638075/80949617-f38e5100-8e11-11ea-9169-ca3885ef1ab1.JPG)

**Comment by VimmiRawat** [comment]
We had the understanding about this flow . We opened the ticket with Microsoft Support Team earlier and they couldn't find the reason why flow is not sending Welcome Email and asked to reach out to GitHub . There are multiple new users created in last one month , but none of them received the email. I have shared one screenshot above for the reference.

**Comment by VimmiRawat** [comment]
![Maker2](https://user-images.githubusercontent.com/62638075/80950215-10775400-8e13-11ea-88fb-97a75834d3fb.JPG)

**Comment by VimmiRawat** [comment]
Above are more test users, these were created on 29th April; but they didn't receive any Welcome Email either.

**Comment by VimmiRawat** [comment]
Hi,

Updated thread https://github.com/microsoft/powerapps-tools/issues/167

Regards,
Vimmi

**Comment by manuelap-msft** [comment]
Although the underlying features and components used to build the Center of Excellence (CoE) Starter Kit (such as Common Data Service, admin APIs, and connectors) are fully supported, the kit itself represents sample implementations of these features. Our customers and community can use and customize these features to implement admin and governance capabilities in their organizations. Microsoft Support won't help you with issues related to this kit, but they will help with related, underlying platform and feature issues.

Can you confirm the trigger of the Welcome Email looks like this:
![image](https://user-images.githubusercontent.com/55705669/80951561-0bed7400-8df0-11ea-8d70-6b2a4f3670c6.png)

And the status of the Welcome email flow is
![image](https://user-images.githubusercontent.com/55705669/80951626-2293cb00-8df0-11ea-891b-8c7c3ac7f521.png)

When you look at the flow, is there any information showing up under Runs?
![image](https://user-images.githubusercontent.com/55705669/80951655-30495080-8df0-11ea-80ed-b81185314d04.png)

**Comment by VimmiRawat** [comment]
![Scope](https://user-images.githubusercontent.com/62638075/80954212-91861980-8e1a-11ea-913b-5eae4cdfe77c.JPG)

![Pagination](https://user-images.githubusercontent.com/62638075/80954220-98ad2780-8e1a-11ea-961d-fde90790ca39.JPG)

**Comment by VimmiRawat** [comment]
Sorry, above ones were for https://github.com/microsoft/powerapps-tools/issues/168

**Comment by VimmiRawat** [comment]
![WelcomeEmail_1](https://user-images.githubusercontent.com/62638075/80957173-4a9b2280-8e20-11ea-8625-3efdf3a71d0c.JPG)

![WelcomeEmail_2](https://user-images.githubusercontent.com/62638075/80957184-51c23080-8e20-11ea-9a45-a4b224de2f1e.JPG)

**Comment by manuelap-msft** [comment]
The Welcome Email adds users to an Office 365 Group - this group is then used to check if a maker is new or already existing. It looks like the group you configured doesn't exist.

Can you confirm you have set up an Office 365 Group, and specified the Group ID as per
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#update-environment-variables

It's the Power Platform Maker Office 365 Group that needs to hold this value
![image](https://user-images.githubusercontent.com/55705669/80957504-2547ed80-8dfb-11ea-8707-1f6f02f8b027.png)

**Comment by VimmiRawat** [comment]
Yes, group is in place already . 


![PowerPlatform_Make_Office365Group](https://user-images.githubusercontent.com/62638075/80963892-85f01e00-8e2d-11ea-81f9-11f4325c6100.JPG)

![PowerPlatform_Make_Office365Group](https://user-images.githubusercontent.com/62638075/80963907-8f798600-8e2d-11ea-92f6-e9784e931392.JPG)

**Comment by VimmiRawat** [comment]
![PowerPlatform_Make_Office365Group_AzureAD](https://user-images.githubusercontent.com/62638075/80963950-a0c29280-8e2d-11ea-9bab-5be7c1339090.JPG)

**Comment by manuelap-msft** [comment]
The Office 365 Group ID needs to be set as Default Value, not as current value. In your screenshot, Default Value is empty.

**Comment by VimmiRawat** [comment]
Oh, sorry for that. Let me check it.

**Comment by manuelap-msft** [comment]
Can you confirm  if this is now working and the issue can be closed?

**Comment by manuelap-msft** [comment]
Closing out old issues without existing action.

Please be sure to read the new and updated documentation
https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit

And raise issues using this template, providing as much information as you can about the error you are experiencing
https://aka.ms/coe-starter-kit-issues

Please let us know if you have issues in the future!
