### ISSUE TITLE
CoE Starter Kit - Admin | Sync Template Flow - Flow Maker Display Name and City field values not set

### ISSUE THREAD

**Issue by mathyousee** [microsoft/powerapps-tools#17]
As part of this process, when the Flow records are upserted into the Flow entity, the *Flow Maker Display Name* and *City* fields are not being set. This is because the definition is blank for this fields. 

The impact of this is that the PowerPlatformAdminDashboard (Power BI Dashboard) does not display Flows by Flow Maker and the Flow map does not show any items.

![image](https://user-images.githubusercontent.com/418063/60464398-18bf9b00-9c14-11e9-9da9-554be236ca50.png)

The fix is to set the value to the Display Name of the Maker record from the immediate previous step.

![image](https://user-images.githubusercontent.com/418063/60464589-a7341c80-9c14-11e9-889f-4461643781db.png)

After applying this update the Flow completes and the fields populate and the report renders with Makers and the City.

![image](https://user-images.githubusercontent.com/418063/60464539-7d7af580-9c14-11e9-9ea3-93282c5d5cfe.png)

**Comment by devinprejean** [comment]
Thanks for letting us know! I found this fix earlier and was going to mention it.

**Comment by denisem-msft** [comment]
Thanks for reporting this @mathyousee, this has been resolved in the most recent update. Please check out the updated dashboard and let us know if there's still an issue here. Also please look at the new sync template v2 (set of Flows) for an optimized experience.
