### ISSUE TITLE
[BUG]: Error importing new CrisisCommunicationNewsNotification.zip - Pagination Policy issue

### ISSUE THREAD

**Issue by davidMbrooke** [microsoft/powerapps-tools#170]
**Describe the bug**
When importing the new (2020.03.23) version of CrisisCommunicationNewsNotification.zip into Flow, getting an error message and the Flow fails to import. No option to fix this from the UI.

**To Reproduce**
1. Download the 2020.03.23 [CrisisCommunicationPackage.zip](https://github.com/microsoft/powerapps-tools/blob/master/Apps/CrisisCommunication/CrisisCommunicationPackage.zip)
1. Extract `CrisisCommunicationNewsNotification.zip` from the Package .zip
1. Go to https://flow.microsoft.com/
1. Click on 'My Flows'
1. Click on 'Import'
1. Click on 'Upload' and browse to the extracted `CrisisCommunicationNewsNotification.zip`
3. Authenticate the Connections ("Select during import" etc.)
4. Click on 'Import'
5. Get the error message:

> The pagination policy of workflow run action 'Get_group_members' of type 'ApiConnection' at line '1' and column '5770' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.

**Expected behavior**
Import should complete without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/18105328/77532646-277a6c00-6e8d-11ea-853e-cd88bb96c92c.png)

**Interface(please complete the following information):**
 - Browser: Chrome

**Additional context**
Manually editing `definition.json` within the .zip file, changing 100,000 to 1,000 then reconstructing the .zip file and importing that works OK.

**Comment by audrieMSFT** [comment]
Is the import setting "Create as New", or "Update"?

**Comment by davidMbrooke** [comment]
"Create as New". This is into a fresh environment without the previous version of the Flow.

**Comment by PaulieShore** [comment]
We are having the exact same issue.

**Comment by audrieMSFT** [comment]
The workflow that is iterating the Office Groups has a pagination limit which exceeds policy constraints. You should be able to unblock yourself if you can export the flow, and revise the pagination settings. An example of what you could do is to export and edit the action to a maximum of 5,000.

**Comment by davidMbrooke** [comment]
That's what I figured as the underlying issue; thanks.
Since the Import doesn't complete I don't get any opportunity to Export.

As I noted at the bottom of my original post, I've been able to work around this issue by unpacking the .zip and hand-editing `definition.json` to reduce the limit as you describe - then reconstructing the .zip and importing as normal.

Not everyone will be comfortable doing that though, so would be good if you could fix for the next release of the Package.

**Comment by audrieMSFT** [comment]
We will consider your ask. Either we will revise the documentation to how the easiest way to do this, or we will release an update. I am very happy though that you are unblocked for now. We appreciate your expertise in this area.

**Comment by linden-seitz** [comment]
I think it may beneficial to post a working version of the file with the new value in tact.  Performed the same operation as the earlier poster a few times from both Windows and Mac devices and still results in a generic "try again later" error at Import.

**Comment by linden-seitz** [comment]
What just worked for me below.  Follow davidMbrooke's recommendation but use this as well (apologies for cross-posting if I did):

"I believe I figured out what was wrong. I was zipping the containing folder in addition to the manifest.json and Microsoft.Flow folders. That created an extra folder layer that is incompatible with what MS Flow expects for the structure of the zipped files.

So, the solution for me is to navigate INTO the folder containing the manifest.json and Microsoft.Flow files/folder, select all, and then create the zipped archive."

**Comment by davidMbrooke** [comment]
That matches what I did; it's important to reproduce the exact same file and folder structure from the original .zip - the import process isn't remotely forgiving.

It's good that you clarified the procedure for other people facing the same issue.

**Comment by denisem-msft** [comment]
Thank you @davidMbrooke for reporting this. We have updated the solution to fix this issue, and updates to the documentation will be published later today.
