### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by gdnaidu** [microsoft/powerapps-tools#171]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Interface(please complete the following information):**
 - Version date[e.g. 2020.04.03]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gdnaidu** [comment]
The pagination policy of workflow run action 'Get_group_members' of type 'ApiConnection' at line '1' and column '5689' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.

**Comment by gdnaidu** [comment]
Could you Please Help me

**Comment by gdnaidu** [comment]
![image](https://user-images.githubusercontent.com/26797999/77571393-51667980-6ef3-11ea-8f88-88e284346938.png)

**Comment by denisem-msft** [comment]
We have just pushed a new version that should fix the error. Please try downloading the most recent version and installing the News Notification flow: https://github.com/microsoft/powerapps-tools/tree/master/Apps/CrisisCommunication

Can you please confirm if this fixes the issue for you?
