### ISSUE TITLE
[BUG]:Notify users on new crisis communication news

### ISSUE THREAD

**Issue by gdnaidu** [microsoft/powerapps-tools#177]
The pagination policy of workflow run action 'Get_group_members' of type 'ApiConnection' at line '1' and column '5689' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'.

![image](https://user-images.githubusercontent.com/26797999/77633659-c8dced00-6f75-11ea-927a-9f177278a3e7.png)

Thanks in advance

**Comment by mr-dang-msft** [comment]
Hi @gdnaidu,
You can download the latest version V2.20200325 for an update to the flow:
[https://aka.ms/CrisisCommunicationSolution](https://aka.ms/CrisisCommunicationSolution)
