### ISSUE TITLE
[BUG]: Audit Log Sync Error "Not Found (404)"

### ISSUE THREAD

**Issue by skb-can** [microsoft/powerapps-tools#178]
In the instruction guide (CoE Starter Kit - Documentation and Setup Instructions.pdf) 
We are doing step 6 - setup audit log sync.

We can import the Json, we used an Security Reader admin account, without MFA.
When testing the connection, we receive the error as can be seen in the attachment.

![Json connector error](https://user-images.githubusercontent.com/62689505/77633579-f31bb400-6f4f-11ea-8e1f-30f3ffca1e9e.jpg)

We have tried to change the starting link from the Json file to protection.office.com, this gives the same error.

Thanks for looking into this.

**Comment by manuelap-msft** [comment]
When configuring, the custom connector can take a few minutes to be provisioned. 
At the top it says "this resource is being provisioned, please try again in a few minutes" - have you given it 10-15 mins and then tested again, and is it still failing now?

**Comment by skb-can** [comment]
> When configuring, the custom connector can take a few minutes to be provisioned.
> At the top it says "this resource is being provisioned, please try again in a few minutes" - have you given it 10-15 mins and then tested again, and is it still failing now?

It is still failing, even after 2 days of waiting.

**Comment by skb-can** [comment]
@manuelap-msft Any other ideas?

**Comment by manuelap-msft** [comment]
We've actually had this issue earlier this week too.

1. If you edit the custom connector and go to the General tab, can you confirm the host is set to outlook.office365.com
![image](https://user-images.githubusercontent.com/55705669/78764544-9cb26a80-797e-11ea-9657-71544edbba0c.png)

2. If this is the case, but it still fails, I would recommend downloading the connector again and re-creating it.

**Comment by skb-can** [comment]
Hi @manuelap-msft 
We did change that, as I saw that was wrong indeed.
Already tried to re-download it as well. It keeps giving the same error.

**Comment by manuelap-msft** [comment]
Are you able to access the Audit Log from the Office 365 Admin Center and see the Launch details there?

**Comment by JeneferM-MSFT** [comment]
Hi there. I'm checking in to see if this issue was resolved for you. 
Thanks,
Jenefer

**Comment by JeneferM-MSFT** [comment]
Closing out old issues without existing action. Please let us know if you have issues in the future!
