### ISSUE TITLE
CoE Upgrades

### ISSUE THREAD

**Issue by leozak06** [microsoft/powerapps-tools#179]
Hi I am just wondering since the CoE team is constantly working to improve the CoE starter kit and always making updates, is there a place where we can find a list of all the updates that have been made so we can just import the specific components that have been updated or do we have to import the solutions from scratch every time there is an update? Is there a way to get upgraded as simply as possible? Thanks in advance!

**Comment by Bryand13** [comment]
Hi there,

Somebody knows how can i set the environment variables again? Thanks in advance
Sorry if this is not the right way to ask.

Bryan

**Comment by JeneferM-MSFT** [comment]
Hi there. Sorry we never commented here to let you know, but we added a work item on our side to make understanding the content in new updates easier.

**Comment by JeneferM-MSFT** [comment]
Hello, please see the [release notes section for CoE Releases](https://docs.microsoft.com/power-platform/guidance/coe/release-notes) in the future. 
Thanks for helping make CoE great!
