### ISSUE TITLE
Emergency Response - Cannot import Locations sample data

### ISSUE THREAD

**Issue by hitendra72** [microsoft/powerapps-tools#180]
**Describe the bug**
Loading of sample data for Locations fails.
1. Tried importing using the MDA - import job fails with error code "-2,147,220,653" for each row (total 360 rows with same error code)
2. Tried importing into the entity - throws the error "The file could not be uploaded for Location: Excel file with more than one sheet is currently not supported."

**To Reproduce**
Steps to reproduce the behaviour:
1. Select Location from the area picker and then select Locations.
2. Click on "Import from Excel" from the ribbon/toolbar
3. Choose "04 - Load Locations.xlsx" sample data file
4. Review the import job - 360 error rows are shown

**Expected behaviour**
Data should be loaded without errors

**Screenshots**

![image](https://user-images.githubusercontent.com/46102183/77720237-50803580-7022-11ea-83b3-5c67f0cd60dd.png)

**Interface(please complete the following information):**
 - Browser - Edge Chromium
 - Version 80.0.361.69 (Official build) (64-bit)

**Additional context**
- Other imports (Systems and Regions) complete successfully
- Facilities sample data imports 65 successful records, 7 records fail

**Comment by hitendra72** [comment]
Fixed the missing data (7 records) in the Facilities entity and ran the data import for locations again - and this time import succeeded.

Closing the issue

**Comment by hitendra72** [comment]
Fixed the missing data (7 records) in the Facilities entity and ran the data import for locations again - and this time import succeeded.

Closing the issue

**Comment by jengregory** [comment]
can you provide more details around what was missing in the Facilities entity?

**Comment by hitendra72** [comment]
actually i couldn't really see anything that was missing in Facilities sample data - which is why I was surprised as to why 7 records failed to upload...
