### ISSUE TITLE
[BUG]: App launcher hardcodes Public Preview cloud runtime URI, breaking regions other than Preview

### ISSUE THREAD

**Issue by jjclancy** [microsoft/powerapps-tools#181]
**Describe the bug**
App launcher page linking to the five apps hardcodes the Public cloud runtime URI, such that one cannot get to any of the apps in deployments other than the Preview stamp.

**To Reproduce**
1. Deploy to anywhere _other_ than a Preview stamp via the public instructions, https://docs.microsoft.com/en-us/powerapps/sample-apps/emergency-response/deploy-configure, including inputting the five Canvas appids
2. Import sample data
3. Run the Canvas root app
4. Click on any individual app, which navigates to
https://apps.preview.powerapps.com/play/980e2c01-2bad-4ad0-8ebf-4946aecc1713?FacilityID=c738f79c-e06f-ea11-a811-001dd801898c

**Expected behavior**
Navigation instead to
https://apps.gov.powerapps.us/play/980e2c01-2bad-4ad0-8ebf-4946aecc1713?FacilityID=c738f79c-e06f-ea11-a811-001dd801898c for GCC, or apps.powerapps.com for Public, or ...

**Comment by narpad** [comment]
We will be rolling out a fix for this issue.

**Comment by narpad** [comment]
Issue resolved with latest update.
