### ISSUE TITLE
[BUG]: Check Approvals and Archive Flow fails at Approve Archive - get msapp file content because of Authentication

### ISSUE THREAD

**Issue by m3ngi3** [microsoft/powerapps-tools#182]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - CoE Toolkit
 - 2020.02.12
 - Admin | App Archive and Clean Up - Check Approvals and Archive

**To Reproduce**
1. Approve an Archive Request
2. See **Approve Archive - get msapp file content** error out because of authentication issue

**Expected behavior**
Get msapp file from Blob and proceed with flow.
If additional configuration needed to get HTTP to work --> did I miss this in instructions?

**Screenshots**

**Additional context**
Body of error:
`<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:768---00
Time:2020-03-27T09:39:24.8131269Z</Message><AuthenticationErrorDetail>Signed expiry time [Tue, 24 Mar 2020 00:00:00 GMT] must be after signed start time [Fri, 27 Mar 2020 09:39:24 GMT]</AuthenticationErrorDetail></Error>`

**Comment by m3ngi3** [comment]
So the URL of the Blob storage where all Power Apps .msapp files are stored, is currently being added to the Approval Record in the flow that start the ownership approval: **Admin | App Archive and Clean Up - Start Approval**.
`@{items('Apply_to_each_App')?['properties']?['appUris']?['documentUri']?['readonlyValue']}`

This URL to get the msapp file is valid for a limited amount of time. So if the approval is taking too long (only one day from what I can see now), Power Automate will not be able to get the msapp file from Azure Blob.

My solution for now is to extend the flow: **Admin | App Archive and Clean Up - Check Approvals and Archive** with the _Get App as a Admin_ action to get a fresh URL right after approval. Let me know if I can help to incorporate this in the last CoE version 👍

**Comment by manuelap-msft** [comment]
That's a super good point, thanks for figuring that out! Awesome!

We don't have a good way to collaborate on the solution yet, but I have made a note and we'll include this with the next version.

**Comment by manuelap-msft** [comment]
Adding @Jenefer-PA

**Comment by maheshau1** [comment]
> So the URL of the Blob storage where all Power Apps .msapp files are stored, is currently being added to the Approval Record in the flow that start the ownership approval: **Admin | App Archive and Clean Up - Start Approval**.
> `@{items('Apply_to_each_App')?['properties']?['appUris']?['documentUri']?['readonlyValue']}`
> 
> This URL to get the msapp file is valid for a limited amount of time. So if the approval is taking too long (only one day from what I can see now), Power Automate will not be able to get the msapp file from Azure Blob.
> 
> My solution for now is to extend the flow: **Admin | App Archive and Clean Up - Check Approvals and Archive** with the _Get App as a Admin_ action to get a fresh URL right after approval. Let me know if I can help to incorporate this in the last CoE version 👍

@m3ngi3 I am new to PowerApps and Power Automate world and facing same issue. I would truly appreciate if you can please share how have you extend existing flow? Any screenshots would greatly help. Thank you!

**Comment by manuelap-msft** [comment]
@maheshau1 we have incorporated this change into the latest version that went live earlier this week!

**Comment by maheshau1** [comment]
> @maheshau1 we have incorporated this change into the latest version that went live earlier this week!

@manuelap-msft  Thank you. Does this mean that I have to import Compliance and Report Components solution again to see/implement these changes? Is there a documentation available on how to upgrade CoE from its current version to a newer version?

**Comment by manuelap-msft** [comment]
Yes, you will have to upgrade - it's explained here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates
