### ISSUE TITLE
[BUG]: Unable to Import PowerApp due to Content Conversion

### ISSUE THREAD

**Issue by ledgerg** [microsoft/powerapps-tools#183]
**Describe the bug**
I am unable to import the PowerApp due to a Content Conversion connection error

**To Reproduce**
1. Go to 'Follow Instructions on Import'
2. Change Connection Settings for MS Teams and Office365 Users'
3. I have an option for Content Conversion but not sure how to set this up
4. Import Button Stays Grey and cant import

**Expected behavior**
No clear how to set a connection for Content Conversion so PowerApp will not import

**Comment by johnmsaxton** [comment]
Same issue

**Comment by ledgerg** [comment]
I have found a way around it.

There is a content converter connection that you need to add – once I did that I could import.

I created the connection like you would for sharepoint but selecting content converter – took some finding.

Graham

**Comment by johnmsaxton** [comment]
Perfect. Thanks. That's a new connector on me. I learned something new and that always makes my day. Appreciate the help.

**Comment by mr-dang-msft** [comment]
Hi @ledgerg @johnmsaxton ,
The Content Conversion was added to clean up the HTML and turn it into plain text for the Request flow. And a subsequent step removed double quotes that interfered with the JSON structure. Depending on screen resolution, some may need to scroll down to see it during the import experience.

Please open another issue if anything else comes up 👍
