### ISSUE TITLE
[BUG]: error executing powershell / step 6 of guide

### ISSUE THREAD

**Issue by miagner** [microsoft/powerapps-tools#185]
**Describe the bug**
Following step 6 (bypass consent for mobile apps) but getting error executing powershell - "...running scripts is disabled on this system..."

**To Reproduce**
1. Copy and paste powershell script in step 6 onto notepad
2. Save as .ps or .ps1 and execute in powershell
3. See error/s

**Expected behavior**
powershell to bypass will run successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/62812870/77832674-afed5b00-7172-11ea-922c-d5b3456db320.png)

**Interface(please complete the following information):**
 - Browser [e.g. chrome, safari] - Microsoft Edge 44.18362.449.0
 - Powershell and Powershell ISE

**Smartphone (please complete the following information):**
 - NA

**Additional context**

**Comment by iamoverrated** [comment]
Don't you need to set the execution policy on the local machine?

**Comment by narpad** [comment]
Please set execution policy on the machine and rerun
