### ISSUE TITLE
[IMPROVEMENT]: autoDeleteApps improvement

### ISSUE THREAD

**Issue by m3ngi3** [microsoft/powerapps-tools#186]
**Describe the bug / improvement**
In the Flow Admin | App Archive and Clean Up - Check Approvals and Archive there is an variable initialized: autoDeleteApps. This determines if the Flow should Remove the app if approved by the owner in the Approval step. However more flexibility would make this feature better.
Make it possible for organizations to determine if app should be automatically deleted per environment and per app. Let Admins manage a setting (new Field) on Environment entity level that is taken over in App entity setting (new Field) to determine if the app should be automatically deleted after owner approval. This way an environment would determine the autodelete setting, the sync flow would take over that setting from environment to app level and admins can change the setting on app level if desired.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Center of Excellence - Compliance and Report Components
 - 1.9
 - Admin | App Archive and Clean Up - Check Approvals and Archive

**To Reproduce**
Not a bug but possible improvement.

**Expected behavior**
Managing the settings on environment level and on app level possible for most flexibility.

**Comment by manuelap-msft** [comment]
This is a great idea, really like it!
Adding @Jenefer-PA

**Comment by JeneferM-MSFT** [comment]
Thanks for this feedback to CoE. I have added the implementation locally and it will release with the next release of the toolkit.

**Comment by manuelap-msft** [comment]
This fix was incorporated in the new version that was released again! Thanks again for making the CoE Starter Kit greater with every release :)
