### ISSUE TITLE
[BUG]: Crisis Communication Solution - Flow failing at "Add_Admin_Logo_to_Default_View"

### ISSUE THREAD

**Issue by RicoVNA** [microsoft/powerapps-tools#187]
**Describe the bug**
Following the instructions [here](https://docs.microsoft.com/de-de/powerapps/maker/canvas-apps/sample-crisis-communication-app#run-the-sharepoint-list-deployment-flow), the Flow I created did not generate the SharePoint lists and failed at Action **"Add_Admin_Logo_to_Default_View"** with error **400** and Message: 

> Die angegebene Ansicht ist ungültig.\r\nclientRequestId: 45f5c7a3-83cd-4db6-bad3-07ffa4176ed1\r\nserviceRequestId: 8cd2439f-c059-1000-4028-9102dca6d0bf

(sorry for the German)

**Component:**

 - App: Crisis Communication Solution 
 - Version: 2020.03.25
 - Flow: DeploySPLists
 -  Browser: Chrome

**Error Details:**
Body
```
_{
  "status": 400,
  "message": "Die angegebene Ansicht ist ungültig.\r\nclientRequestId: 45f5c7a3-83cd-4db6-bad3-07ffa4176ed1\r\nserviceRequestId: 8cd2439f-c059-1000-4028-9102dca6d0bf",
  "source": `"https://*****.sharepoint.com/sites/Crisis_Communication_App/_api/web/lists/GetByTitle('CI_configAdminSetup')/views/getbytitle('All%20Items')/ViewFields/AddViewField('Logo')",`
  "errors": [
    "-2147024809",
    "System.ArgumentException"
  ]
}_
```
Header
```
{
  "Pragma": "no-cache",
  "x-ms-request-id": "8cd2439f-c059-1000-4028-9102dca6d0bf",
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Timing-Allow-Origin": "*",
  "x-ms-apihub-cached-response": "true",
  "Cache-Control": "no-store, no-cache",
  "Date": "Mon, 30 Mar 2020 10:28:05 GMT",
  "Set-Cookie": "ARRAffinity=9a53c9d953bbdfc85fcb9bc388522492211961687fcde0ee871a9a717de0c346;Path=/;HttpOnly;Domain=sharepointonline-we.azconn-we.p.azurewebsites.net",
  "Content-Length": "455",
  "Content-Type": "application/json",
  "Expires": "-1"
}
```
Status Code
`400`

**Expected behavior:**
Flow should finish and create all needed Lists in Sharepoint

**Screenshots**
![Error](https://user-images.githubusercontent.com/62878796/77910882-29c73680-7290-11ea-9f08-089d186c9675.JPG)

**Comment by pedrorja** [comment]
I had the same problem and I'll follow this Thread for discover how to solve it!

**Comment by diegovduarte** [comment]
Same problem, please help us.

**Comment by robbertvanarkel** [comment]
Same issue here. Can't figure out what is going wrong..

**Comment by JoaoLucindo** [comment]
looks like some language related problem. In a english tenant all works fine! have you tried deploying to a english sharepoint site  ?

**Comment by mayleni** [comment]
Hi!!

I already try with an English Tenant and all works good. 
But in my Spanish tenant, no :( 
And also I tried with a Sharepoint site in English

**Comment by mayleni** [comment]
Hi Everyone, I tried with an admin account.  It works!!
I guess the warning its because the user don´t have enough rights in SharePoint.

**Comment by RicoVNA** [comment]
Hi all,

thanks @JoaoLucindo, creating the Sharepoint Site in English did the trick :-)
The flow succeeded now.

Many Thanks and kind regards

Rico

> looks like some language related problem. In a english tenant all works fine! have you tried an english sharepoint site ?

**Comment by med44600** [comment]
Does the App continue working after putting back the Sharepoint Site to our language (not english) ?

**Comment by med44600** [comment]
I tried almost 5 times, recreating Sharepoint Site in English, changing account .. and it's allways stopping at "Add_Admin_Logo_to_Default_View" with error 400.
I really d'ont know what t do more!!! Can someone help me

**Comment by mayleni** [comment]
Try creating the SP site un English and also with an Admin Account.
