### ISSUE TITLE
[BUG]: Unable to Import the Solution Error 8004801F

### ISSUE THREAD

**Issue by craig-karl** [microsoft/powerapps-tools#188]
Unable to import the solution into the PowerApps Environment.

Clicked Solution, import - picked the zip file and waited.  See attached errors
![Error](https://user-images.githubusercontent.com/62895216/77929168-5b7fd380-7277-11ea-9b30-153a4785b226.PNG)
[importlog_COVID19Solution_2_2_0_12.zip](https://github.com/microsoft/powerapps-tools/files/4403710/importlog_COVID19Solution_2_2_0_12.zip)

**Comment by craig-karl** [comment]
Hello, seems to be tied specifically to the region selected.  I was choosing my region as Canada, as I am a Canadian Customer.  If I deploy to an Environment that has region US the deployment is successful.

**Comment by narpad** [comment]
This is currently being investigated

**Comment by narpad** [comment]
This should now be resolved.
