### ISSUE TITLE
[BUG]: Unable to import

### ISSUE THREAD

**Issue by mokoenae** [microsoft/powerapps-tools#193]
**Describe the bug**
When I try and import I get a 80048060 Error. 

**To Reproduce**
From make power app --> Solution...
1. Go to 'import'
2.Select the zip file 
3. Click on 'Next'

**Expected behavior**
Expected to import the solution 

**Screenshots**
 
![Screenshot 2020-04-01 at 17 13 36](https://user-images.githubusercontent.com/63005628/78153195-1c9a7b00-743b-11ea-9222-34e721722319.png)

**Interface(please complete the following information):**
 - Browser : Chrome
 - Version date 80.0.3987.149 (Official Build) (64-bit)

**Additional context**

The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.
--

**Comment by jengregory** [comment]
Did you extract the zip file that was downloaded from github? There should be a solution folder included that has the solution file. Please reference https://docs.microsoft.com/en-us/powerapps/sample-apps/emergency-response/deploy-configure#step-2-download-the-deployment-package for more details.

**Comment by mokoenae** [comment]
Thank you, didn't extract the zip from Github
