### ISSUE TITLE
[BUG]: Admin | Sync Template v2(flows)

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#196]
Error : Rate limit is exceeded. Try again in 5 seconds. 

Description - When i try to run the flow it get failed becuse of the rate limit is exceeded. Please help

Failed Step - Get Flow As Admin

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - Version 1.32
 - Flow Sync Template (v2) Flows

![image](https://user-images.githubusercontent.com/59940632/78287169-1cf44e00-74ef-11ea-8b38-70c852270970.png)

**Comment by manuelap-msft** [comment]
Could you share what the error is? You should see it by clicking on the blue bar of the action.

**Comment by manuelap-msft** [comment]
Great, thanks for confirming
