### ISSUE TITLE
Power Platform Dashboard- Model-Driven app count does not show

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#197]
When I refresh the dashboard in App tab it does not show how many model-driven apps I have in my tenant. I have many model-driven app in my tenant. Please advise

**Component (please tell us which flow or app you are experiencing issues with):**
 - Version 1.32
 - PowerBI Dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/78299581-2e942080-7504-11ea-8df1-63a7f4c168e3.png)

**Comment by manuelap-msft** [comment]
Hello,

in the Core solution, can you check if the Admin | Sync Template v2 (model driven apps) ran succesfully?

**Comment by aakashpatel660** [comment]
> Hello,
> 
> in the Core solution, can you check if the Admin | Sync Template v2 (model driven apps) ran succesfully?

Admin | Sync Template v2 (Model-Driven) flow failed because in my default environment j have 2 app called resource schedule and project, which owner shows as a provision user and it can not find it, for that reason flow is getting failed. MSFT told me that those are the dynamic default application so I cannot delete them but do you know how can I change the owner or anything like that so the flow does not fail. 

Thank you

**Comment by manuelap-msft** [comment]
The flow runs once per environment you have to sync all environment resources into the entities. So if you have three environments, the flow will run three times. 
If you open up the Admin | Sync Template v2 (Model Driven Apps), can you check if there's error handling like the below built on (to handle abandoned and system apps)

![image](https://user-images.githubusercontent.com/55705669/78574736-5942e980-7822-11ea-80b4-c66aa186c9fd.png)

**Comment by aakashpatel660** [comment]
I do not have the parallel branch after getting user profile -> Action Abandoned App, can you please show what is under that action, and I can try to see if that resolves the issue.

**Comment by aakashpatel660** [comment]
> The flow runs once per environment you have to sync all environment resources into the entities. So if you have three environments, the flow will run three times.
> If you open up the Admin | Sync Template v2 (Model Driven Apps), can you check if there's error handling like the below built on (to handle abandoned and system apps)
> 
> ![image](https://user-images.githubusercontent.com/55705669/78574736-5942e980-7822-11ea-80b4-c66aa186c9fd.png)

Any update on, what should be the action look like? 

Thank you

**Comment by manuelap-msft** [comment]
If you copy the Upsert Model Driven App action and insert it underneath Get user profile, and remove the App Owner value
![image](https://user-images.githubusercontent.com/55705669/79576473-400c2980-80bb-11ea-8dd5-e84d0c5826b3.png)

and then select the ... > Configure run after, and configure this action to only run when Get user profile has failed 
![image](https://user-images.githubusercontent.com/55705669/79576515-50240900-80bb-11ea-938f-9e9ca00b7ff4.png)

That should work

**Comment by manuelap-msft** [comment]
Closing out old issues without existing action.
Please be sure to read the new and updated documentation
https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit

And raise issues using this template, providing as much information as you can about the error you are experiencing
https://aka.ms/coe-starter-kit-issues

Please let us know if you have issues in the future!
