### ISSUE TITLE
Wrong link to theme editor zip download link

### ISSUE THREAD

**Issue by sir79** [microsoft/powerapps-tools#20]
The download link to the Theme Editor in the readme.md points to the review tool zip file which is in the theme editor folder.

**Comment by Qualicon** [comment]
Does anyone have the zip-file to download the theme editor for Powerapps ? The application cannot be downloaded anymore because of the wrong link tot the zip for theme editor.

**Comment by iAmManCat** [comment]
Here you go @Qualicon @sir79 
[themeeditor.zip](https://github.com/microsoft/powerapps-tools/files/3646286/themeeditor.zip)

**Comment by manuelap-msft** [comment]
Fixed and updated GitHub links
