### ISSUE TITLE
[BUG]: Unable to import solution error code  8004801F

### ISSUE THREAD

**Issue by dipankardasind** [microsoft/powerapps-tools#202]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Interface(please complete the following information):**
 - Version date[e.g. 2020.04.03]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX, SamsungS10]
 - OS: [e.g. iOS12.1]
 - Browser [e.g. Edge (Chromium), safari]

**Additional context**

**Comment by narpad** [comment]
This should now be resolved. Please reactivate if that is still not the case
