### ISSUE TITLE
Error Loading Component

### ISSUE THREAD

**Issue by tmcg19** [microsoft/powerapps-tools#204]
HI when following the guide, stepping through each connector in the Sync Template V2, all worked fine and saved. then went on to Admin|Sync Template v2 (Apps) I have an error in the Upsert Maker record and Upsert App record connection, there is a red ! icon and when I hover over get message "Error Loading Component" I'm unable to edit, delete or save? so cant move forward.
![Error Loading Component](https://user-images.githubusercontent.com/56071180/78562322-0f9dd300-7811-11ea-8f2c-c88c22db6737.jpg)

**Comment by manuelap-msft** [comment]
Are you able to just close the Flow studio and open it again to try editing it again?

**Comment by tmcg19** [comment]
I am accessing via browser. I closed all last night, and logged back in this morning and tried again and exact same issue?

**Comment by tmcg19** [comment]
is there any details specs of these flows so we can see the details then in this case I could try and remove the connection that is giving the error and I could recreate from the spec. as I cannot see this connector or its content I am unable to build the connection myself.  aDesign and spec document and diagram woulds also help  correct issue when some fields don't populate automatically and you need to fill in manually, but if you have no where to check what to fill in how can you do it manually?

**Comment by manuelap-msft** [comment]
We have been able to reproduce this error on our end, and are investigating this at the moment.

**Comment by tmcg19** [comment]
any progress on this error, anything I can try here?

**Comment by manuelap-msft** [comment]
Have you tried recently? I have just tested this again, and where I was able to repo the issue, it is working fine now.

**Comment by tmcg19** [comment]
I have been able to get one flow, Apps updated and saved now. but will need an explanation as to what the error was here and what was done to fix it?

**Comment by manuelap-msft** [comment]
It looks like there was a temporary glitch in the Flow Studio (Editor) that caused this issue. I don't have any details on the fix, it was not an issue caused by the CoE Starter Kit itself.
