### ISSUE TITLE
[BUG]: failed at « Add_Admin_Logo_to_Default_View »

### ISSUE THREAD

**Issue by NoNoNeo** [microsoft/powerapps-tools#205]
**Describe the bug**
Following the instructions here, The Flow also failed after a while.

**To Reproduce**

1. Following the instructions in https://docs.microsoft.com/fr-fr/powerapps/maker/canvas-apps/sample-crisis-communication-app (in french version)
2. I created the SharePoint site called "Site_crise"
3. I followed the flow instructions, including uploading DeploySPLIsts.zip.
4. In editing the Flow, I matched the site and the AppName "communication de crise".
5. I ran the Flow.
6. The Flow failed on "Add_Admin_Logo_to_Default_View"
Detail:
> L'affichage spécifié est incorrect.
> clientRequestId: 15092f65-2f33-45c0-8700-7fd783a5fc54
> serviceRequestId: 8128469f-806f-2000-6ccb-5bd10932de96

**Screenshots**
![image](https://user-images.githubusercontent.com/42837259/78583560-4686df80-7837-11ea-8ebf-505b4927f176.png)

**Interface(please complete the following information):**
 - Browser [chrome]
 - Version date [80.0.3987.149]

**Additional context**

**Comment by med44600** [comment]
Same problem for me yesterday. French install also.
I run the flow and get the Flow failed on "Add_Admin_Logo_to_Default_View"
I used it from Chrome -  80.0.3987.163 (Build officiel) (64 bits)

Error label:
L'affichage spécifié est incorrect.
clientRequestId: 05d8afb0-e2df-478a-9236-6638095f8fb5
serviceRequestId: e5cc469f-8020-2000-0853-d532418cd3cb

![image](https://user-images.githubusercontent.com/58919432/78865050-350f2480-7a3d-11ea-9093-fa7d2fa5504e.png)

**Comment by med44600** [comment]
I tried almost 5 times, recreating Sharepoint Site in English, changing account .. and it's allways stopping at "Add_Admin_Logo_to_Default_View" with error 400.
I really d'ont know what t do more!!! Can someone help me

**Comment by NoNoNeo** [comment]
It's the same for me, trying in English for the sharepoint do not solve the problem, same error.

**Comment by NoNoNeo** [comment]
Find alone. Creating the SP site in English was not enough. I had to go in the "all site settings", "Site Administration", "Language settings" and here, uncheck all the others languages. And only then, start the flow.
