### ISSUE TITLE
Solution import fail on Australian based PowerApps Environment

### ISSUE THREAD

**Issue by Craig-Humphrey** [microsoft/powerapps-tools#21]
Tried a number of times today, to import the CoE solution into my Australian based PowerApps environment.... failed repeatedly:

`An error has occurred. Try this action again. If the problem continues, check the Microsoft Dynamics 365 Community for solutions or contact your organization's Microsoft Dynamics 365 Administrator. Finally, you can contact Microsoft Support. : Microsoft.Crm.Metadata.EntityMetadataNotFoundException: The entity with a name = 'CanvasApp' with namemapping = 'Logical' was not found in the MetadataCache. MetadataCacheDetails: ProviderType=Dynamic, StandardCache=False, IsLoadedInStagedContext = True, Timestamp=729848, MinActiveRowVersion=729848
   at Microsoft.Crm.Metadata.DynamicMetadataCache.GetEntity(String entityName, NameMappingType mapping)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.UpdateCanvasAppEntityWithResponse(CanvasApp canvasApp, AppDefinition appDefinition, IOrganizationContext context)
   at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem()`

Tried on a USA based environment - imported without a hitch.

**Comment by cromwelldelarosa** [comment]
Following this discussion as we are also facing the same issue with a solution with canvass-app

**Comment by fmms** [comment]
We are facing the same deploying to a Europe Power App environment.

**Comment by denisem-msft** [comment]
This was an issue with the product and should be resolved by now. Please let us know if there's still an issue with importing.
