### ISSUE TITLE
[BUG]: Documentation for Developer Compliance Center missing

### ISSUE THREAD

**Issue by rsch136** [microsoft/powerapps-tools#210]
**Describe the bug**
There is no documentation on the Developer Compliance Center (App) other than a single screenshot and a very breif description of the makers POV.

**Component:**
 - Compliance Components
 - Developer Compliance Center
 - CoE Starter Kit Documentation (pdf)

**Expected behavior**
I would expect more documentation what the individual fields in the developer compliance center (specifically under "support details") mean, so that I can explain it to my makers.

**Screenshots**
![developerComplianceCenter](https://user-images.githubusercontent.com/44471683/78646763-d53c4080-78b9-11ea-8eaf-58949a74b2b5.png)
Description of Developer Compliance Center in Documentation
![cdsflow](https://user-images.githubusercontent.com/44471683/78646789-dff6d580-78b9-11ea-8725-989df775c03d.png)
Description of one field in CDS entity

**Additional context**
Opened forum entry here: https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/Documentation-for-Developer-Compliance-Center/m-p/518340#M2253

**Comment by manuelap-msft** [comment]
Adding @JeneferM-MSFT

**Comment by JeneferM-MSFT** [comment]
Hello there. Thank you for this suggestion, concur that this could be better. We've added it to our backlog.

**Comment by JeneferM-MSFT** [comment]
Hello, we have updated our documentation now. Please see here. [Governance Components-Developer Compliance Center](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#developer-compliance-center)
Thanks for helping make CoE great!
