### ISSUE TITLE
BPF In Canvas - cannot create custom connector

### ISSUE THREAD

**Issue by hitendra72** [microsoft/powerapps-tools#222]
When creating the custom connector using the Swagger, there is an error thrown as below:

Specified swagger has the following errors: 'Definition is not valid.  Error: 'Error : paths/~1api~1data~1v9.0~1{entityname} : The path '/api/data/v9.0/{entityname}' is defined multiple times with different capitalization. Paths must be unique when compared case-insensitively.'

**Comment by txh57** [comment]
The Swagger editor throws 23 Semantic errors of kind
- "Declared path parameter "xxx" needs to be defined as a path parameter at either the path or operation level" and
- "Equivalent paths are not allowed."

The swagger file also relates to "contosodev.crm.dynamics.com" . Will that url be overwritten when the connector is created?

**Comment by hitendra72** [comment]
@txh57 - you must overwrite/replace the contosodev.crm.dynamics with the URL of your own CDS instance.

**Comment by hitendra72** [comment]
@manuelap-msft - checking in if there's any luck with the swagger - the issue persists

**Comment by manuelap-msft** [comment]
Adding @mehdislaoui

**Comment by hitendra72** [comment]
seems there is no plan of resolution

**Comment by txh57** [comment]
Replace {entity**N**ame} by {entity**n**ame} in the swagger file - That's it.
