### ISSUE TITLE
[BUG]: DeploySPLists flow fails... 

### ISSUE THREAD

**Issue by agilancolbert** [microsoft/powerapps-tools#223]
**DeploySPLists.ZIP flow fails**
During the execution of the flow "DeploySPLists", the flow fails at the step "Scope - Logo library".

Thanks in advance for your support.

**Comment by mayleni** [comment]
Hi, I had the same error. I solved it creating a SP site in english and create run the flow with an Admin  account :)

**Comment by SandraTeixeira** [comment]
Também estou com o mesmo erro na execução do fluxo "DeploySPLists", meu fluxo também falha na etapa "Escopo - Biblioteca de Logo". 
Alguma sugestão para solucionar este problema?

**Comment by agilancolbert** [comment]
Thanks mayleni. It was the problem. Changing sharepoint site to English solved the issue.
