### ISSUE TITLE
[BUG]: issue title Admin | Sync Template v2 (Model Driven Apps) run ends as failed for abandoned app

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/powerapps-tools#227]
**Describe the bug**
When the Office 365 user profile of a creator of a Model Driven App cannot be found (user account no longer active - azureactivedirectoryobjectid property in systemuser record is empty) the app will be correctly upserted as abandoned app, but the flow run will still end as failed. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]: Core
 - Version [e.g. 1.29]: 1.32
 - App or Flow [e.g. Sync Template (v2)]: Sync Template v2 (Model Driven Apps)

**To Reproduce**
First run the Sync Flow for an environment with a model driven app created by an account that is no longer active. 
Flow run
Get user profile (V2) step,.
NotFound
**Expected behavior**
If the upsert action of abandoned app was successful the failing of the Get user profile (V2) step should not result in a failed flow run. 

**Screenshots**

**Additional context**

**Comment by RebekkaAalbers** [comment]
I have a fix for the issue. Issue occurs because of parallel branches after Get user profile action. One running after success, the other running after failure. Suggested solution:
Use switch on status output of Get user profile, running for both success and failure. Determine next steps based on status. 
200 = Upsert Model Driven App Maker + Upsert Model Driven App
404 = Upsert Model Driven App (Abandoned App)
![image](https://user-images.githubusercontent.com/30928094/79460137-aed27f80-7ff4-11ea-921b-38ae0efdc8b8.png)

**Comment by JeneferM-MSFT** [comment]
Thank you for this great suggestion! We have added it to our backlog.

**Comment by JeneferM-MSFT** [comment]
Thanks again Rebekka for driving improvements to the CoE. This fix has been incorporated into the sync flows locally and will ship with the next release.

**Comment by manuelap-msft** [comment]
This fix was incorporated in the new version that was released again! Thanks again for making the CoE Starter Kit greater with every release :)
