### ISSUE TITLE
Deleting existing solution and importing new version

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#228]
**Describe the bug**
I am trying to upload a new solution to my environment. I am trying to delete my existing solution and import a new solution. In my current environment, I have version 1.32 for core solution but somehow I do not see any changes in my model-driven flow for the abandoned app. So I thought I should import it again. But receiving an error when I delete the solution. I  tried to import the solution and since it is existing in my environment it gave me 2 options but not sure which one should I choose. Any guidance will help.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version e.g. 1.32
 - Delete the existing solution
Error - Failed deleting solution. Solution dependencies exist, cannot uninstall.DependencyCount : 25 RequiredComponentObject details: Type: EntityRelationshipRole,.........

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/79468004-6f903880-7fcc-11ea-8966-06aa0f8e5e83.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
It sounds like you don't have any customizations to the flows or powerapps that you made  since you first installed. Is that correct? If so, you can chose to overwrite. 

Can you also let me know why you initially thought to delete the solution instead of upgrade?

Thank you!

**Comment by aakashpatel660** [comment]
i did choose upgrade when i had version 1.23 to 1.32 but did not do the upgrade properly. For that reason i choose to delete.

**Comment by JeneferM-MSFT** [comment]
We do not suggest that you delete the solutions. 
Please Let us know how the upgrade proceeds now.
Thank you

**Comment by JeneferM-MSFT** [comment]
Hi there. Checking in to see if you were able to resolve this.

**Comment by aakashpatel660** [comment]
Yes I was able to resolve this issue. 

Best Regards,
Akash Patel

**Comment by JeneferM-MSFT** [comment]
So glad to hear that. Thanks for helping make CoE great!
