### ISSUE TITLE
[BUG]: Flow error - List Model Driven Apps error for Community plan environments with CDS

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/powerapps-tools#229]
**Describe the bug**
The Admin | Sync Template v2 (Model Driven Apps) gives an error when trying to load Model Driven Apps for a Community Plan environment (type Development) stating _CRM organization with unique name 'orgd804a008' not found._

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture] - Core
 - Version [e.g. 1.29] - 1.32
 - App or Flow [e.g. Sync Template (v2)] - Flow Sync Template v2 (Model Driven Apps) 

**To Reproduce**
Run the flow on a tenant with an Developer environment where CDS is enabled.
Check the run info. 
List Model Driven Apps action.
NotFound

**Expected behavior**
The Flow would also run correctly to get Model Driven Apps for Developer environments.

**Comment by RebekkaAalbers** [comment]
I checked: the way to collect model driven apps from a community plan environment as done in this flow only works when the credentials of the owner of the community plan environment are used.

**Comment by JeneferM-MSFT** [comment]
Thank you for the issue. We have added an item in our backlog to better document this limitation.

**Comment by manuelap-msft** [comment]
Thanks Rebekka; this is a known limitations on the entity unfortunately. We will document this better in the documentation under limitations!

**Comment by RebekkaAalbers** [comment]
I think it is a good idea to also update the flow so it will skip Developer environments. That way you do not have the flow run failures every day.

**Comment by JeneferM-MSFT** [comment]
Thanks Rebekka, I'll add that to the work item to see if that is something we can do.

**Comment by JeneferM-MSFT** [comment]
Rebekka, when you say you are skipping dev environments, do you mean sandbox environments made here: [http://aka.ms/ppadmin](http://aka.ms/ppadmin)?
![image](https://user-images.githubusercontent.com/62659043/80105588-a6ff6780-852d-11ea-8cdf-7efa2d388503.png)

**Comment by JeneferM-MSFT** [comment]
Good suggestion Rebekka. Thank you! I have added this fix on our end, and it will release with the next update to the toolkit

**Comment by RebekkaAalbers** [comment]
Hi Jenever,

No, I skip these. Listing the Model Apps from those environments works well.

I skip the environments that are of type 'Developer'. That is the type of environment that you get with the free Community Plan license. You can have only one per person and the name always contains the name of the user. Service Admins do have access to those environments, but they cannot perform the action the collect Model Apps from these environments using the CDS connector.

Best
Rebekka



________________________________

**Comment by JeneferM-MSFT** [comment]
Yep, I discovered those after posting the other question :) That is exactly what my fix does too. 
Thanks again for helping make CoE great!

**Comment by manuelap-msft** [comment]
This fix was incorporated in the new version that was released again! Thanks again for making the CoE Starter Kit greater with every release :)
