### ISSUE TITLE
Power Platform Dashboard- Environment Count is Wrong 

### ISSUE THREAD

**Issue by hovbiebo** [microsoft/powerapps-tools#231]
Hello,

I'm having issues with my environment count. I deleted a bunch of test environments but the report still shows more than i actually have. I have less that 30 environments but the count shows 70

Please advise

Thanks
![PPDashboardEnvCountError](https://user-images.githubusercontent.com/30634365/79596866-e7cb2c80-80a6-11ea-8f6a-9ca8683c1930.PNG)

**Comment by manuelap-msft** [comment]
Thanks for reporting this issue, it looks like the filter on this page was not correctly set. If you are looking at this report in Power BI Desktop, you can change the filter to "Environment Deleted is false". 

I have also just uploaded a new version of the Power BI Dashboard to make this change.

![image](https://user-images.githubusercontent.com/55705669/79736607-fa857180-82f1-11ea-879b-861d5f1b3a71.png)

**Comment by hovbiebo** [comment]
I went in and applied the filter as advised but the environment count still appears wrong. 

Here is what we are thinking - If the flow (Admin | Sync Template V2) runs and the permission set for the user/ID that is running it, is not an admin at runtime, it does not fail but gets what it can and marks all the other environments it was unable to get as "deleted"

We use PIM to assign the Power Platform admin role, so it expires and have to be renewed at various intervals.

I've attached the screenshot of what we have with the filter applied. what we really have is 27 environments but it shows 3.

![PPDashboardEnvCountError1](https://user-images.githubusercontent.com/30634365/79757530-d5890280-82e1-11ea-9054-65ad4a40d56f.PNG)

**Comment by manuelap-msft** [comment]
That thinking is correct, yes. The Admin | Sync Template V2 will work for Environment Admins, System Admins of specific environments as well as Power Platform or Global Admins. If at the runtime of the flow the user does not have access to all environments but has access to some environments due to Environment / System Admin permissions, the flow will not fail but mark environments as deleted as the user can't "find" them.

**Comment by hovbiebo** [comment]
Thanks for confirming that but we were told a while back that when a user is signed in as an admin to schedule a job, the token persists for 90 days. Is this also a correct statement?

**Comment by manuelap-msft** [comment]
You will need to have the correct admin access at the time the flow runs.

**Comment by manuelap-msft** [comment]
Closing out old issues without existing action.

Please be sure to read the new and updated documentation
https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit

And raise issues using this template, providing as much information as you can about the error you are experiencing
https://aka.ms/coe-starter-kit-issues

Please let us know if you have issues in the future!
