### ISSUE TITLE
New app connector notification and reporting

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/powerapps-tools#232]
Hi there,

We're looking to setup a new flow that notifies my team via email whenever a new app connector is added by Microsoft to any of our environments. We then want to create a record for the new addition either to a spreadsheet that lists existing app connectors or ideally a 3rd party database.

Can you advise what the best way is to do the above? I've setup a basic flow that lists our connectors on a daily basis and sends an email notification for each connector. However, I only want to be notified of and report on new additions.

Regards,

Mel

**Comment by manuelap-msft** [comment]
This template https://flow.microsoft.com/en-us/galleries/public/templates/0b2ffb0174724ad6b4681728c0f53062/get-list-of-new-powerapps-flows-and-connectors/ provides you with a digest of new apps, flows, and connectors. I believe the template is set to run weekly but you can change the occurrence to daily.

When you create the flow from this template, you will have branches to gather new apps, new flows, and new connectors. You can remove the apps and flows branches to only get new connectors.

**Comment by melmgcoe** [comment]
Thanks Manuela, let me take a look at the template and come back to you shortly.

Regards,

[cid:image007.png@01D616FF.115BD1B0]
[M&G Plc Logo]
[cid:image008.png@01D616FF.115BD1B0]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D616FF.115BD1B0]


[cid:image009.png@01D616FF.115BD1B0]
[cid:image009.png@01D616FF.115BD1B0]
[cid:image011.png@01D616FF.115BD1B0]

**Comment by manuelap-msft** [comment]
Hello,

just quickly checking in to see if this worked for you?

**Comment by melmgcoe** [comment]
Apologies Manuela, I've not had a chance to implement the flow. I aim to do this next week and will provide an update then.

Regards,

[cid:image007.png@01D61A51.64192150]
[M&G Plc Logo]
[cid:image008.png@01D61A51.64192150]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D61A51.64192150]


[cid:image009.png@01D61A51.64192150]
[cid:image009.png@01D61A51.64192150]
[cid:image011.png@01D61A51.64192150]

**Comment by melmgcoe** [comment]
Hi Manuela,

Do you recommend installing this flow as part of our CoE environment running under our dedicated service account? Or would it be ok to use my own admin account?

Regards,

[cid:image001.png@01D61C79.60E02090]
[M&G Plc Logo]
[cid:image002.png@01D61C79.60E02090]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image004.png@01D61C79.60E02090]


[cid:image004.png@01D61C79.60E02090]
[cid:image004.png@01D61C79.60E02090]
[cid:image006.png@01D61C79.60E02090]

**Comment by manuelap-msft** [comment]
I would recommend the best practices you have in place for your CoE environment for this flow as well!

**Comment by melmgcoe** [comment]
Thanks Manuela, we'll go ahead and customise the flow as part of our CoE as you suggested.

One last query for you - is it possible to send notifications for new connectors to a 3rd party database or Excel spreadsheet in addition to email? I believe Excel is possible through the options I've seen, are there any existing guides available that explain how to do this step-by-step?

Regards,

[cid:image007.png@01D61E15.3EE83480]
[M&G Plc Logo]
[cid:image008.png@01D61E15.3EE83480]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D61E15.3EE83480]


[cid:image009.png@01D61E15.3EE83480]
[cid:image009.png@01D61E15.3EE83480]
[cid:image011.png@01D61E15.3EE83480]

**Comment by manuelap-msft** [comment]
Hello,

yes, Power Automate can connect to Excel, SQL, SharePoint and many other data sources for you to add data to.

You can either learn about this through exploring templates, for example this template adds a row to excel when a new SharePoint item is created - you can explore how that works and add that to your own flow for your scenario
https://us.flow.microsoft.com/en-us/galleries/public/templates/1a600d803c8c11e7b9809da41e7af698/add-a-row-to-excel-when-a-new-item-is-added-in-sharepoint-list/

The Power Automate User Community is also a great way to get help with questions like this
https://powerusers.microsoft.com/t5/Get-Help-with-Power-Automate/ct-p/FL_GeneralDiscussions

You will also be able to find videos created by community members and MVPs to help with scenarios like that
https://www.youtube.com/watch?v=ibqFGgkZ1Cs

I will close this case for now, but please let me know if you have any further questions regarding the CoE Starter Kit!

**Comment by melmgcoe** [comment]
Thanks for the links, that's useful to know.

Regards,

[cid:image007.png@01D61E17.A19BC630]
[M&G Plc Logo]
[cid:image008.png@01D61E17.A19BC630]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D61E17.A19BC630]


[cid:image009.png@01D61E17.A19BC630]
[cid:image009.png@01D61E17.A19BC630]
[cid:image011.png@01D61E17.A19BC630]
