### ISSUE TITLE
'Office 365 Management API' Custom Connector not identified

### ISSUE THREAD

**Issue by Daleyon** [microsoft/powerapps-tools#233]
**Describe the bug**
The Power BI dashboard is not identifying my custom connector (MFA _Office 365 Management API_).

![image](https://user-images.githubusercontent.com/17080282/79765559-c65f8000-82f4-11ea-9690-64e1bf163345.png)

I checked the _Admin | Sync Template v2 (Custom Connectors)_ and the custom connector value is blank [].
![image](https://user-images.githubusercontent.com/17080282/79765254-5ea93500-82f4-11ea-959b-72a796a3e244.png)

The Entities a) _Connection Reference "admin_connectionreference"_ identifies the custom connector as _Office 365 Management API_ and b) _Connector_ identifies the custom connector as _admin_5Foffice-20365-20management-20api_.

![image](https://user-images.githubusercontent.com/17080282/79765494-b182ec80-82f4-11ea-8a41-45f4e377084d.png)

![image](https://user-images.githubusercontent.com/17080282/79765319-72ed3200-82f4-11ea-8ba0-bacd9060ae21.png)

All other data within the Power BI dashboard looks great!

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [e.g. 1.39]
 - Solution [Audit Logs]
 - Version [e.g. 1.0.0.7]
 - Dashboard-PowerPlatformAdminDashboard_2020-04-20_advanced

**To Reproduce**
1. Go to 'Power BI Dashboard'
2. Click on 'New Power Platform CoE Toolkit Tenant Adoption'
3. Select 'Custom tab'
![image](https://user-images.githubusercontent.com/17080282/79765954-56052e80-82f5-11ea-9681-22ef647d7347.png)

**Expected behavior**
Show the custom connector MFA _Office 365 Management API_

**Comment by Daleyon** [comment]
All works today. It took multiple manual triggers and refreshing DataSet.
![image](https://user-images.githubusercontent.com/17080282/79891877-9df88400-83cf-11ea-8e14-947b25542ea7.png)

**Comment by JeneferM-MSFT** [comment]
Thanks Daleyon. Glad its working, I had been struggling to reproduce all morning.

**Comment by Daleyon** [comment]
@JeneferM-MSFT you are welcome! That method did not work yesterday when I created the issue ticket.
