### ISSUE TITLE
[BUG]: Delete environment and its impact in Apps

### ISSUE THREAD

**Issue by gilbertofloreztella** [microsoft/powerapps-tools#237]
Hello,

I have a question, if an enviroment is deleted, the entity field "**Environment Deleted**" is updated correctly but, in the case of the apps of that enviroment, the field "**App Deleted**" in the Power Apps entity is not updated to "yes". Is this the correct behaviour? Don't should be updated as well? I guess is the same thing with Flows, etc. but I didn't have time to check it out.

Thanks in advance for your answer.

**Comment by JeneferM-MSFT** [comment]
Thank you for this suggestion. We did not implement this but you are correct in that it may be useful. We have added it to the backlog. 

Thanks again for helping to make CoE great!

**Comment by JeneferM-MSFT** [comment]
There is a new sync flow which mark environments and all their content as deleted when the env is deleted. 
There is also a helper flow to run once to get to a clean state.
Please upgrade to the new CoE to find these assets
Thanks for using the CoE!
