### ISSUE TITLE
[BUG]: Reopen - CoE Components (Template Catalog)

### ISSUE THREAD

**Issue by DennisGaida** [microsoft/powerapps-tools#238]
**Describe the bug**
This is in reference to issue #225 which should not be closed until the components are removed from the CoE Starter Kit or fixed in a way they work with other tenants.

Currently the CoE Components are included in "/SharePoint Setup/CoE Components.zip". This is a weird location for Power Apps components to begin with. The documentation still talks about the components: https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components#controls-provided-in-the-template-catalog-app

**To Reproduce**
See ticket #225 

**Expected behavior**
Import components without issue or remove components from the download. Also move components out of "SharePoint Setup"

**Comment by JeneferM-MSFT** [comment]
I have removed the reference locally to the section you reference. Thanks I had missed that. Once we re-release the documentation this reference will be hidden as well.

**Comment by DennisGaida** [comment]
Great!
Additionally to the documentation it would be great to remove the components from the download for now as well. Otherwise this confuses users as to what those "Components" are.

**Comment by manuelap-msft** [comment]
The latest version of the download and documentation are now live, the reference for components has been removed for now in the documentation and also from the download. We will add it back in once this feature is working!
