### ISSUE TITLE
[BUG]: Audit Log via O365 Manamagent API error 400

### ISSUE THREAD

**Issue by DennisGaida** [microsoft/powerapps-tools#239]
**Describe the bug**
When running through the steps to set up the Center of Excellence - Audit Log via the Office 365 Management API App connector, I get an error 400 while trying to start the subscription.
The error message itself is misleading and also revealing information that shouldn't be revealed (CWE-209). The error message states that my tenant doesn't exist.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence Audit Logs
 - Version 1.0.0.7
 - Flow with Azure App ID registration

**To Reproduce**
1. Follow the steps in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
2. Follow all steps until heading **Start a subscription to the Audit Log Content**, Step 5. "Test Operation"
3. Status with error 400 appears when trying to test the connection
4. Error message states "tenant does not exist"

**Expected behavior**
Receive a 200 status

**Additional context**
The error message is as follows (anonymized).

- Please note that the error comes from tenant ID XYZ and also states "Tenant XYZ does not exist". 
- Also please note the information disclosed in this error message, i.e. \v\sources\dev\auditing... etc. this internal stack trace shouldn't be visible

```
{
  "error": {
    "code": "StartSubscription [CorrId=68a50e00-22a9-48f5-8c52-26118d28a576][TenantId=XYZ,ContentType=Audit.General,ApplicationId=e19d728b-9382-4ef5-9c08-45ed78dad0c0,PublisherId=e19d728b-9382-4ef5-9c08-45ed78dad0c0][AppId",
    "message": "19d728b-9382-4ef5-9c08-45ed78dad0c0] failed. Exception: Microsoft.Office.Compliance.Audit.DataServiceException: Tenant XYZ does not exist.\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetSubscriptionTableClientForTenantAsync>d__50.MoveNext() in d:\\dbs\\sh\\nibr\\0413_071452\\cmd\\v\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 1786\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetAPISubscriptionAsync>d__23.MoveNext() in d:\\dbs\\sh\\nibr\\0413_071452\\cmd\\v\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 498\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.StartController.<StartSubscription>d__0.MoveNext() in d:\\dbs\\sh\\nibr\\0413_071452\\cmd\\y\\sources\\dev\\auditing\\src\\auditapiservice\\apifrontendservicerole\\Controllers\\StartController.cs:line 75"
  }
}
```

**Comment by JeneferM-MSFT** [comment]
Two things periodically result in an error like this:
1) doing this step too soon after set up of the connector, before its ready to be tested
2) typing / pasting the tenant incorrectly. 

Can you try again now that the connector is surely ready (for issue #1 above)

**Comment by JeneferM-MSFT** [comment]
One more thing to check. Please browse here to ensure that audit logs are enabled for your organization, and that you have access to them: https://protection.office.com/unifiedauditlog

**Comment by DennisGaida** [comment]
Jenefer, great! Thanks for your very quick support!

- I did enable audit logs beforehand 
- I did try this step like the minute I created everything, to maybe I was too quick.

Could you please add the information about relying on audit logs being enabled and the step taking a couple of minutes / hours to the documentation.

Additionally: Maybe you can escalate the error message somewhere to O365 Management API - the stack trace really shouldn't be visible like that.

**Comment by JeneferM-MSFT** [comment]
Good idea. I have added these to the **_(i) important_** note at the end of the section in our local copy of the documentation and it will release with the next edition.  

I will also follow up with that owning team your suggestion. 

Thanks for helping make CoE great Dennis!
