### ISSUE TITLE
[BUG]: DLP Editor

### ISSUE THREAD

**Issue by gilbertofloreztella** [microsoft/powerapps-tools#240]
I have a problem with the DLP Editor App. I'm trying to create a DLP Policy but It's not possible (see attached screenshot). My role is "**Environment Admisntrator**" and I can create a new DLP Policy if I use the standard way to create it (PowerApps Center of Administration). It seems the DLP Editor App is not identifying me as an Environment Administrator (I'm  not a global administrator of the O365 tenant and also I'm not admisnitrator of the Power Platform)

![image](https://user-images.githubusercontent.com/64275038/80538317-d25ada00-89a5-11ea-8162-b9185b03ca19.png)

**Comment by manuelap-msft** [comment]
This is a known limitation, highlighted under Limitations in the documentation
https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#dlp-editor

The DLP Editor currently can't write back environment type policies. 
We'll make sure to also call this out as part of the DLP Editor documentation.

**Comment by gilbertofloreztella** [comment]
Thank you Manuela, but maybe I don't undestand very well the limitation because  we've been trying to create a new policy with an user with the Global Administrator role using DLP Editor App, and it was posible!! Actually, we checked the policy out in the Power Platform environment.

**Comment by manuelap-msft** [comment]
There are two types of DLP Policies:
Tenant policy are created by a Global or Power Platform Admin, and can be for one environment, for all environments, or for specific environments.
Environment policies are created by an Environment Admin and are only for one environment.

Environment policies, created by Environment Admins, is not supported by the DLP Editor. Tenant policies created by Global or Power Platform Admins are supported by the DLP Editor.

**Comment by gilbertofloreztella** [comment]
OK Manuela, it's very clear now!!! Thanks a lot!

**Comment by gilbertofloreztella** [comment]
Do you have the idea, in your roadmap, to extend the DLP Editor capabilities to an Environment Admin? Thanks again.

**Comment by manuelap-msft** [comment]
I have added this to our roadmap now, but we don't have a timeline for this at the moment as we are working on some higher priorities.

**Comment by gilbertofloreztella** [comment]
OK, thanks!! Sounds good!
