### ISSUE TITLE
[BUG]: Preview / Legacy environments adding multiple records to Environment entity

### ISSUE THREAD

**Issue by petepuu** [microsoft/powerapps-tools#242]
When Admin | Sync Template v2 flow detects preview environment it will generate new GUID for it which causes new record to be added to environment entity. This relates to duplicate GUID issue #36 with default environment but with this solution there will be multiple records for each preview environments. Could alternate key be used to define other identifier for the record which could then be used in a flow to detect does environment already exists? 

![image](https://user-images.githubusercontent.com/8307644/80624441-59668b80-8a54-11ea-98cf-6b753f149026.png)

In following case there is only 1 preview environment but multiple records in Environment entity

![image](https://user-images.githubusercontent.com/8307644/80627755-0e02ac00-8a59-11ea-9b5a-5681dc7aa946.png)

**Comment by petepuu** [comment]
There is environment name stored as in in the entity, so maybe check that in flow before adding new

![image](https://user-images.githubusercontent.com/8307644/80675520-5358c500-8abd-11ea-89d9-01eeaca86054.png)

**Comment by JeneferM-MSFT** [comment]
Thanks Pete. That is exactly the direction I was going! If that fixes it for you, along with cleaning up the duplicates, let me know. I'll be fixing this in our local copy to send out with the next shipment as well.

**Comment by petepuu** [comment]
Hi @JeneferM-MSFT , yes that fixed the issue but I did cleanup of those duplicate entries "manually" using "Edit data in excel"

**Comment by JeneferM-MSFT** [comment]
Glad you are unblocked now! And thanks for helping make CoE great.

**Comment by JeneferM-MSFT** [comment]
We have a local fix based on a repro from another customer. I wanted to be sure your case was also captured. 

Can you please confirm that the following property is set when the Power Platform is queried for the environment of interest?
- "creationType": "CommonDataModelLegacy"

You can check this by using the following call, and then looking in the output body:
![image](https://user-images.githubusercontent.com/62659043/81115345-69f58680-8ed8-11ea-9667-857f50674b11.png)

Thanks so much for your help!

**Comment by petepuu** [comment]
The creationType in our case is "Legacy"

**Comment by JeneferM-MSFT** [comment]
Thanks! I will update my fix to be sure to cover your case.

**Comment by JeneferM-MSFT** [comment]
Thanks again for helping us make CoE great. This is fixed in the new release shipped yesterday.
