### ISSUE TITLE
forbidden

### ISSUE THREAD

**Issue by gregwilliams14** [microsoft/powerapps-tools#244]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Unfortunately, your bug description or any screenshots didn't come through. Could you please explain the bug you are experiencing?

**Comment by gregwilliams14** [comment]
I am installing COE kit.  I have 4 flows that i can not start.  see error below.
![starterror](https://user-images.githubusercontent.com/51127244/80643097-89eafd00-8a35-11ea-9523-0c6cf971911e.PNG)
i create a DLP that contains the following connectors.
![dlp](https://user-images.githubusercontent.com/51127244/80643337-eb12d080-8a35-11ea-8c91-b7ab9f8b60a2.PNG)

**Comment by manuelap-msft** [comment]
Are you an Environment Admin or Global Admin or Power Platform Service Admin? Could there be other DLP Policies also applying to the environment where you have installed the CoE Kit such as tenant wide policies?

**Comment by gregwilliams14** [comment]
there is a tenant wide policy

**Comment by manuelap-msft** [comment]
If there are multiple policies applying to the same environment, either all of them have to have the connectors the CoE Starter Kit uses in business data only or if you have a policy that applies to all environments that you don't want to change you could exclude the CoE environment from that.

**Comment by gregwilliams14** [comment]
thanks.  i will try that.

**Comment by manuelap-msft** [comment]
Have you been able to activate your flows now?

**Comment by gregwilliams14** [comment]
It works now.  Thanks for checking.  I will update the thread.

**Comment by manuelap-msft** [comment]
Amazing, thank you!
