### ISSUE TITLE
Dashboard-PowerPlatformAdminDashboard

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/powerapps-tools#245]
**Describe the bug**
Tring to open the pbix file but it is failing with an error "

Required property 'Connections' not found in JSON. Path '', line 1, position 136.

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.GetStackTraceInfo(Exception e)
   at Microsoft.PowerBI.Client.Windows.Telemetry.PowerBIUserFeedbackServices.ReportException(IWindowHandle activeWindow, IUIHost uiHost, FeedbackPackageInfo feedbackPackageInfo, Exception e, Boolean useGDICapture)
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.<>c__DisplayClass14_0.<HandleException>b__0()
   at Microsoft.Mashup.Client.UI.Shared.UnexpectedExceptionHandler.HandleException(Exception e)
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

**Component (please tell us which flow or app you are experiencing issues with):**
 
**To Reproduce**
1. Go to 'Dashboard-PowerPlatformAdminDashboard_2020-04-20_advanced.pbix'
2. Double click on it
3. Power BI Client errors out
4. Error - Required property 'Connections' not found in JSON. Path '', line 1, position 136.

**Screenshots**
If applicable, add screenshots to help explain your problem

**Comment by manuelap-msft** [comment]
Having had a brief search of this error message in the Power BI community it appears that this could be an issue with Power BI Desktop, and an uninstall / reinstall seemed to have fixed it for users in this thread https://community.powerbi.com/t5/Issues/Can-t-open-my-Power-BI-files/idi-p/973115 (not related to the CoE Starter Kit dashboard). 

Could you try that and let us know if you are still experiencing issues?

**Comment by VimmiRawat** [comment]
Hi,

After uninstalling , it went through . But after providing instance URL by clicking “Enter Data” as mentioned here<https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#configure-by-using-pbix-file>, it is failing with some query error. Please find the screenshots above.

Regards,
Vimmi

**Comment by manuelap-msft** [comment]
Unfortunately, the screenshot didn't come through!

**Comment by VimmiRawat** [comment]
Hi,

Please find attached the error.

Regards,
Vimmi

**Comment by manuelap-msft** [comment]
Hello,

it doesn't look like attachments or images are coming through when you reply via email to a GitHub issues. Can you please navigate to https://github.com/microsoft/powerapps-tools/issues/245 and drag & drop your image into the comment box to send it.

**Comment by VimmiRawat** [comment]
Weird . Drag & Drop or upload also not working ☹

Regards,
Vimmi

**Comment by VimmiRawat** [comment]
![PowerBI_Error_pbix1](https://user-images.githubusercontent.com/62638075/80699754-2676d300-8afa-11ea-97ba-b254128121fb.JPG)
![PowerBI_Error_pbix2](https://user-images.githubusercontent.com/62638075/80699771-2f67a480-8afa-11ea-9514-1372dd09b626.JPG)
![PowerBI_Error_AppSource](https://user-images.githubusercontent.com/62638075/80699788-368eb280-8afa-11ea-9e98-dfa77115556d.JPG)

**Comment by VimmiRawat** [comment]
Through either of the option , appsource or pbix ; it shows the sample data . Doesn’t show data from our instance . You should be able to see the screenshots here #245<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_powerapps-2Dtools_issues_245&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=ccR22dIkPbTrMlwDpX7pxelNfy-qvvkj_7GDkPIzp78&s=M_5cRehP-Gv6tbS2x_rRaBumGrKvTOYbKviYUjyObws&e=> here.

Thanks,
Vimmi

From: Rawat, Vimmi
Sent: Thursday, April 30, 2020 3:46 PM
To: microsoft/powerapps-tools <reply@reply.github.com>; microsoft/powerapps-tools <powerapps-tools@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [External] Re: [microsoft/powerapps-tools] Dashboard-PowerPlatformAdminDashboard (#245)

Weird . Drag & Drop or upload also not working ☹

Regards,
Vimmi

**Comment by manuelap-msft** [comment]
Thank you, I can see the screenshots now

In Power BI Desktop, if you select Transform Data
![image](https://user-images.githubusercontent.com/55705669/80704190-13550a80-8adc-11ea-80bf-a1bc96c38a7f.png)

And then enter your Org Url here
![image](https://user-images.githubusercontent.com/55705669/80704249-2b2c8e80-8adc-11ea-8429-76241b358a9d.png)

Are you getting an error message?

**Comment by VimmiRawat** [comment]
So, after connecting to the instance , it just gives the query errors as below . And I see, the same status in app.powerbi.com



![PowerBI_Error_pbix3](https://user-images.githubusercontent.com/62638075/80731861-14605900-8b29-11ea-9af8-219b8ab15a99.JPG)
![AppPowerBIError](https://user-images.githubusercontent.com/62638075/80731879-1aeed080-8b29-11ea-8f01-d6b0d84286a8.JPG)

**Comment by VimmiRawat** [comment]
![PowerBI_Error_pbix4](https://user-images.githubusercontent.com/62638075/80733014-c2203780-8b2a-11ea-82aa-733dff88b3c4.JPG)

**Comment by VimmiRawat** [comment]
What's the exact process of upgrade ? How can we make sure that my existing flows and apps will not be affected ?

**Comment by VimmiRawat** [comment]
Hi,

A couple of questions here. 


What this doesn't for the appsource option ? Is the reason same ?

We didn’t make any changes in the solution .Just imported all three components and saved all flows as “Copy of …” ; so all appear under “My Flows” now . And Apps were also imported separately to my make.powerapps.com from GitHub sites directly . So, can we just install the latest version and then upgrade it ?

![Latest](https://user-images.githubusercontent.com/62638075/80734645-19270c00-8b2d-11ea-832a-e1676eef632d.JPG)

Regards,
Vimmi

**Comment by manuelap-msft** [comment]
Closing out old issues without existing action.

Please be sure to read the new and updated documentation
https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit

And raise issues using this template, providing as much information as you can about the error you are experiencing
https://aka.ms/coe-starter-kit-issues

Please let us know if you have issues in the future!
