### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Model Driven Apps) always fails

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/powerapps-tools#248]
**Describe the bug**
Admin | Sync Template v2 (Model Driven Apps) always fails

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version [e.g. 1.29]
 - Flow - Admin | Sync Template v2 (Model Driven Apps)

**To Reproduce**
1. Go to "Last Run"
2. Click on 'Edit'
3. Scroll down till "Get Model Driven Apps fails - Error Handling"

![Model_Driven1](https://user-images.githubusercontent.com/62638075/80704867-01d32900-8b03-11ea-9040-83f57b47dc30.JPG)
![Model_Driven2](https://user-images.githubusercontent.com/62638075/80704872-07c90a00-8b03-11ea-9323-c40d666c82a2.JPG)

**Expected behavior**
We expect this flow to complete successfully .

**Additional context**
We also need understanding around what this flow is expected to do as we don't find any details here :https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components

**Comment by JeneferM-MSFT** [comment]
Good catch on the documentation here, we missed this flow. I have added it to our local copy and it will be present in the next release. Thanks for helping make CoE great! 

Note that this flow is the same as the other sync flows but it does it for Model Driven Apps: 
Runs when an environment is created or modified, and gets model driven app information.

**Comment by JeneferM-MSFT** [comment]
Can you please go into the block above "Get Model Driven Apps and store in CoE CDS Entity" for the failing record and see what happens in that block?

**Comment by manuelap-msft** [comment]
Can you confirm that the two scopes "Get Model Driven Apps and store in CoE CDS Entity2 and "Get Model Driven Apps fails - Error Handling" are connected by a red dotted line and not a straight black line, see below
![image](https://user-images.githubusercontent.com/55705669/80715407-3f798700-8aee-11ea-8101-7abfd6abb9e2.png)

If they are connected by a straight black line, please click on the ... next to "Get Model Driven Apps fails - Error Handling" select "Configure run after" and ensure only **has failed** is checked here

![image](https://user-images.githubusercontent.com/55705669/80715515-5ae49200-8aee-11ea-9359-004708564750.png)

This was missed in a previous version of the CoE Starter Kit and has been fixed since, but based on your comment it looks like you are using an older version of the CoE Starter Kit.

**Comment by VimmiRawat** [comment]
Hi Manuela,

Yes, it succeeded this time . I will monitor it for a day or two to confirm if runs are successful . Can you tell me one thing ? We installed the solution in the month of January but never received any updates. What’s the best approach to remain updated ?

Regards,
Vimmi

**Comment by VimmiRawat** [comment]
Hi,

Followed below and looks like it is working fine now . We will monitor it for a few days .

Two scopes "Get Model Driven Apps and store in CoE CDS Entity2 and "Get Model Driven Apps fails - Error Handling" were connected by a red dotted line and not a straight black line, see below
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_55705669_80715407-2D3f798700-2D8aee-2D11ea-2D8101-2D7abfd6abb9e2.png&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=CKZtO8tTy1vFkuavZ1cTO9ouoAQAEaBUkGChc_ziBB8&s=C1dadyWPCMUxJrfwpF6R1gTm3oTgA3NploPB2HzCnjc&e=>

Click on the ... next to "Get Model Driven Apps fails - Error Handling" select "Configure run after" and checked “has failed” as below :

[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_55705669_80715515-2D5ae49200-2D8aee-2D11ea-2D9359-2D004708564750.png&d=DwMCaQ&c=eIGjsITfXP_y-DLLX0uEHXJvU8nOHrUK8IrwNKOtkVU&r=RxdAoBPFsyo_ysmJ6Zhb1B-Y7gjfjYc0tMXS6bZlNCM&m=CKZtO8tTy1vFkuavZ1cTO9ouoAQAEaBUkGChc_ziBB8&s=ZURRQEbgCRD0SAjeKtZy0NrJx9GbEGzYag14_6fT3KE&e=>
Regards,
Vimmi

**Comment by manuelap-msft** [comment]
Awesome, thanks for confirming! 

Good question, at the moment we don't have a good way of notifying users when a new update is released - we do document new releases here under Updates https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit 

We are looking at a better way for users to subscribe to updates! 

I will close this issue for now, but please let us know if you experience any further issues.
