### ISSUE TITLE
[BUG]: Unable to turn on the flow

### ISSUE THREAD

**Issue by pchintam** [microsoft/powerapps-tools#253]
**Describe the bug**
Unable to turn on the flow in Deployment Step 13: "Verify the Flow supply tracking flow is enabled"

**To Reproduce**
1. Go to Step 13: Verify the Flow supply tracking flow is enabled.' Follow instructions to arrive at the flow listed there
2. Click on 'Turn On' for "Flow Supply Tracking" flow
4. Get an error saying : Cannot start unpublished flow. Authenticate the flow connections and resave the flow to activate.error

![image](https://user-images.githubusercontent.com/9437215/80895479-4f35ce80-8c9a-11ea-8f3a-5affac713037.png)

**Screenshots**

**Interface(please complete the following information):**
 - Version date[e.g. 2020.04.03]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX, SamsungS10]
 - OS: [e.g. iOS12.1]
 - Browser [e.g. Edge (Chromium), safari]

**Additional context**

**Comment by daimaukr** [comment]
Hi @pchintam 
For this flow we should  authenticate the flow connections like described for the flows from step [Step #14](https://docs.microsoft.com/en-us/powerapps/sample-apps/regional-emergency-response/deploy#step-14-update-the-details-of-flows-for-sending-emails)
in other words -> click Edit -> click on the first connector tile, click Add Connection or select existing -> do the same with another cds connector, save-> go back and turn-on.

**Comment by di-gupta** [comment]
@pchintam,
Before you can turn the Flow on, you would need to fix/add connections - sub-step #5 under Step 13. Click Edit to Edit the Flow and then specify the connection to use or add new connection to CDS. You can also refer to the steps and screenshots under Step 14 in the deployment guide as well.

**Comment by pchintam** [comment]
> @pchintam,
> Before you can turn the Flow on, you would need to fix/add connections - sub-step #5 under Step 13. Click Edit to Edit the Flow and then specify the connection to use or add new connection to CDS. You can also refer to the steps and screenshots under Step 14 in the deployment guide as well.

@di-gupta , unable to edit the flow. The edit option is greyed out. See the message. The same message is there in the screen shot on the deployment instructions as well.
![image](https://user-images.githubusercontent.com/9437215/81343637-3185b200-906a-11ea-8848-6f26675d9084.png)

**Comment by pchintam** [comment]
> @pchintam,
> Before you can turn the Flow on, you would need to fix/add connections - sub-step #5 under Step 13. Click Edit to Edit the Flow and then specify the connection to use or add new connection to CDS. You can also refer to the steps and screenshots under Step 14 in the deployment guide as well.



> Hi @pchintam
> For this flow we should authenticate the flow connections like described for the flows from step [Step #14](https://docs.microsoft.com/en-us/powerapps/sample-apps/regional-emergency-response/deploy#step-14-update-the-details-of-flows-for-sending-emails)
> in other words -> click Edit -> click on the first connector tile, click Add Connection or select existing -> do the same with another cds connector, save-> go back and turn-on.

Hi @daimaukr , i am unable to edit the flow and add the data connections. I have the data connections created but unable to edit the flow / update it. Please see my previous reply to @di-gupta for the screenshot.

**Comment by di-gupta** [comment]
> > @pchintam,
> > Before you can turn the Flow on, you would need to fix/add connections - sub-step #5 under Step 13. Click Edit to Edit the Flow and then specify the connection to use or add new connection to CDS. You can also refer to the steps and screenshots under Step 14 in the deployment guide as well.
> 
> @di-gupta , thanks. I am unable to edit the flow. The edit option is greyed out. See the message in the screen shot. The same message is there in the screen shot on the deployment instructions as well.
> ![image](https://user-images.githubusercontent.com/9437215/81343637-3185b200-906a-11ea-8848-6f26675d9084.png)

**Comment by di-gupta** [comment]
> > @pchintam,
> > Before you can turn the Flow on, you would need to fix/add connections - sub-step #5 under Step 13. Click Edit to Edit the Flow and then specify the connection to use or add new connection to CDS. You can also refer to the steps and screenshots under Step 14 in the deployment guide as well.
> 
> @di-gupta , thanks. I am unable to edit the flow. The edit option is greyed out. See the message in the screen shot. The same message is there in the screen shot on the deployment instructions as well.
> ![image](https://user-images.githubusercontent.com/9437215/81343637-3185b200-906a-11ea-8848-6f26675d9084.png)

@pchintam, click on the Flow name to open it in Flow (Power Automate) and click Edit from the top left.
![image](https://user-images.githubusercontent.com/64987910/81345830-069d5d00-906e-11ea-9a75-504f94e6e507.png)

**Comment by pchintam** [comment]
> > > @pchintam,
> > > Before you can turn the Flow on, you would need to fix/add connections - sub-step #5 under Step 13. Click Edit to Edit the Flow and then specify the connection to use or add new connection to CDS. You can also refer to the steps and screenshots under Step 14 in the deployment guide as well.
> > 
> > 
> > @di-gupta , thanks. I am unable to edit the flow. The edit option is greyed out. See the message in the screen shot. The same message is there in the screen shot on the deployment instructions as well.
> > ![image](https://user-images.githubusercontent.com/9437215/81343637-3185b200-906a-11ea-8848-6f26675d9084.png)
> 
> @pchintam, click on the Flow name to open it in Flow (Power Automate) and click Edit from the top left.
> ![image](https://user-images.githubusercontent.com/64987910/81345830-069d5d00-906e-11ea-9a75-504f94e6e507.png)

Thanks. Almost there, I think.  I remember going into Flow/Automate to edit the flow with the connection like you suggested. **2 new issues now:**

1. After I click on the flow name and inside Automate, when i click on  "Edit" on the Connections tile, I am taken to "Owners" edit function. I was able to repro this multiple times. 
2. When I click on the "Edit" button , like you mention, I am able to begin editing the flow. However, when attempting to save the updated connection, (after I specify a new / existing connection), I get this message when i attempt to save the updated flow. 
"Some of the connections are not authorized yet. If you just created a workflow from a template, please add the authorized connections to your workflow before saving."

![image](https://user-images.githubusercontent.com/9437215/81348738-84b03280-9073-11ea-8244-393175afaaa5.png)

Thanks!

**Comment by daimaukr** [comment]
Looks like you need to authorize another connection here.
For that click to "Apply to each" to expand it and you will see another connection:

![image](https://user-images.githubusercontent.com/33906449/81369880-8516f080-90a8-11ea-9fc8-6d9e013f6da7.png)

Please  authorize it the same way as first one.

**Comment by pchintam** [comment]
> Looks like you need to authorize another connection here.
> For that click to "Apply to each" to expand it and you will see another connection:
> 
> ![image](https://user-images.githubusercontent.com/33906449/81369880-8516f080-90a8-11ea-9fc8-6d9e013f6da7.png)
> 
> Please authorize it the same way as first one.

Thank you! That did it.
