### ISSUE TITLE
[BUG]: schemaname eq 'admin_PowerAutomateEnvironmentVariable'

### ISSUE THREAD

**Issue by tmcg19** [microsoft/powerapps-tools#258]
**Describe the bug**
Setting up CoE and cannot get working.
So going to log each issue.
Todays issue affects :
Admin | Sync Template v2 (Flows)
Admin | Sync Template v2 (Apps)
The error is from a connector not edited just from CoE Download

Error with Connector Titled: "List Environment variable - admin PowerAutomateEnvironmentVariable
On Filter Query : schemaname eq 'admin_PowerAutomateEnvironmentVariable'

Error:
{
  "status": 400,
  "message": "Could not find a property named 'schemaname' on type 'Microsoft.Dynamics.CRM.account'.",
  "error": {
    "message": "Could not find a property named 'schemaname' on type 'Microsoft.Dynamics.CRM.account'."
  },
  "source": "orged82fdc8.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 8983961b-16c6-44e0-be52-66f41449c6f4"
}

**Comment by tmcg19** [comment]
@manuelap-msft

**Comment by manuelap-msft** [comment]
What version of the CoE Starter Kit are you using? 
What environment are you in - commercial or GCC cloud?
When you open the solution and Filter by Environment Variables, do the below Environment Variables show?
![image](https://user-images.githubusercontent.com/55705669/81069895-6cf17680-8eda-11ea-9af1-3a77a277ea53.png)

When in this view you click on Power Automate Environment Variable, have you configured a Default Value?
![image](https://user-images.githubusercontent.com/55705669/81069948-8397cd80-8eda-11ea-899b-3beb67143188.png)

When you click on Data > Entities and set the Filter to All, do the Environment Variable Definition and Environment Variable value entities show?
![image](https://user-images.githubusercontent.com/55705669/81070072-aaee9a80-8eda-11ea-9202-2e19fc1eb4ea.png)

When you open the Environment Variable Definition entity and click on Data there, does the highlighted entity show.
![image](https://user-images.githubusercontent.com/55705669/81070236-db363900-8eda-11ea-82fb-bfbcb651f15c.png)

Please provide as much information as you can, so we can quickly get to the bottom of this issue.

**Comment by tmcg19** [comment]
I could not see anything different from our test environment that worked and this one in production, so decided to start again in production and take diffenet approach and not update connectors in solution but to save copies of the flows and then update connection and save and seems to be much quicker now and none of the same issues, so I can close this issue

**Comment by tmcg19** [comment]
thank you
