### ISSUE TITLE
Publish the Power BI dashboard for Emergency Response App

### ISSUE THREAD

**Issue by Renieroc** [microsoft/powerapps-tools#263]
**Describe the bug**
When attempting to complete step 10 Publish the Power BI dashboard the Power BI app displays "Almost done" and do not move onto where it is completed.

**To Reproduce**
Steps to reproduce the behaviour:
1. From Step 10: Publish the Power BI dashboard
2. Click on 'Connect to the Hospital Emergency Response Decision Support Dashboard'
3. The "Connect to the Hospital Emergency Response Decision Support Dashboard" guide is displayed.
Then select the Click the following link to get to the app: Hospital Emergency Response Decision Support Dashboard template app
4. On the AppSource page for the app, select **GET IT NOW**.
5. The user is then requested to sign into Power BI where the the message **Almost Done** is displayed and tis does not change at all.
**Expected behavior**
Power BI to complete for the process to continue to continue to connect to data sources

**Screenshots**
![image](https://user-images.githubusercontent.com/64575230/81290482-70b30380-9068-11ea-8119-21ce02d1d9fc.png)

**Interface(please complete the following information):**
 - Browser [ chrome]
 - Version date[Version 81.0.4044.129 (Official Build) (64-bit)]

**Comment by narpad** [comment]
Does the user have the right permissions to connect to the CDS org?

**Comment by Renieroc** [comment]
Good day

The user is the administrator of the system and has all the necessary permissions for this task.

Please advise?

Thank you

Regards

**Comment by Renieroc** [comment]
This issue has been resolved, Thank you.
