### ISSUE TITLE
Power BI "access to the resource is forbidden"

### ISSUE THREAD

**Issue by tmcg19** [microsoft/powerapps-tools#264]
**Describe the bug**
Opening:
Dashboard-PowerPlatformAdminDashboard_2020-02-12_basic.pbix
OR
 Dashboard-PowerPlatformAdminDashboard_2020-05-04_advanced.pbix
in Power BI Desktop and go to transform data
Update connection and enter account and password that has access to the CDS for my CoE data

after logging in it will try to connect and refresh data then I get the message:
access to the resource is forbidden

I will attach a screen shot.

**Comment by tmcg19** [comment]
I'm unable to attach an image, something wrong on git hub no matter what browser I use

**Comment by JeneferM-MSFT** [comment]
Did you sign in after you changed the data source?
To clear / reset these: 
Go back to transform data> Data Source Settings > Select your CDS data source > Clear Permissions. 
This will force you to sign back in to refresh.

**Comment by tmcg19** [comment]
yeah, and same error every time, even changed to another account that has access and same

**Comment by JeneferM-MSFT** [comment]
can you share what value you used for the orgurl?

**Comment by tmcg19** [comment]
https://orged******.crm.dynamics.com/

**Comment by JeneferM-MSFT** [comment]
and can you browse to that url with the account you used to sign in on PBI?

**Comment by JeneferM-MSFT** [comment]
it sounds from this blog like sometimes PBI needs to have its permissions cleared/reset. Please try these things if you are able to browse with your sign in
https://windowsreport.com/access-to-resource-forbidden/

**Comment by tmcg19** [comment]
yes I have just browsed to the address and logged in no issue.

I have also done the resets suggested on that link, I'm stummed

**Comment by JeneferM-MSFT** [comment]
This sounds like a product issue then. We don't have any special logic in our connection. If you want to try a few other things before contacting support, I suggest seeing if other PBI's work, and creating one from scratch to the backend.

**Comment by manuelap-msft** [comment]
When you open Power BI Desktop, can you make sure you are signed in there as well (see top right corner)
![image](https://user-images.githubusercontent.com/55705669/81334273-b6d68a00-909d-11ea-8c28-5c600541fdce.png)

When you go to Transform Data and enter your Org Url, click back onto Environment in the same view and it might ask you to Apply Changes and log in there as well. 

A screenshot would be helpful - if you have GitHub open in the browser you should be able to copy&paste an image into the "Write" message window from the Snipping Tool for example

**Comment by tmcg19** [comment]
I got a Power BI pro license assigned and changed Data source Settings privacy lever from none to Organizational it worked.
Then when I went back to the Free license cleared all permission and set privacy lever from none to Organizational logged in again all worked???
But its working
