### ISSUE TITLE
[BUG]: Import Power BI Embedded Apps (Import of .zip file fails - 80048060)

### ISSUE THREAD

**Issue by masi2602** [microsoft/powerapps-tools#265]
**Describe the bug**
I tried to import the PowerAppsButtonArchiveApp solution but the error messages says there are some files missing. I also noticed that for the other two solutions in the Import Power BI Embedded Apps folder. What should I do?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.44
 - App or Flow : PowerAppsButtonArchiveApp

**To Reproduce**
1. Go to environment where CoE is installed
2. Click on Solution
3. Try to Import solution

**Expected behavior**
Import should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/64970706/81306326-a1526780-907f-11ea-9b32-0287c01c4774.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hi thanks for posting. We know that the zip file is correctly formatted as others have installed with it. Can you please validate that you have covered all the pre-req's needed?
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

**Comment by JeneferM-MSFT** [comment]
actually just saw another person have this. You need to extract the original zip file you downloaded. within it are the individual components. Please let me know if this resolves and I will close.

**Comment by masi2602** [comment]
Hi..prerequisites are covered because I already imported the Core components successfully. I did download the entire CoE kit new and extracted it. In the first level there are Core, Nutrition and Audit component zipped file - those included the missing files - but in the other folders (PowerBI Embedded Apps), which is a normal folder, it looks like those files are missing in the zipped ones. E.g. PowerAppsArchivButton
![CBE9B1EB-FA96-424A-A7E9-5CD1729CD188](https://user-images.githubusercontent.com/64970706/81323743-1d57aa00-9096-11ea-80c6-85c07e506747.jpeg)
![9100F0EF-3AE2-4394-ADD9-D89FACDE18A9](https://user-images.githubusercontent.com/64970706/81323749-20eb3100-9096-11ea-8dd6-dbd7786cc115.png)

**Comment by JeneferM-MSFT** [comment]
Ahh I think I see the issue. Are you are trying to import apps at this point rather than a solutions? If so, you are at the wrong import ux. 
See the instructions from here the [embedded apps in the coe dashboard](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#optional-configure-embedded-apps-in-the-coe-dashboard) section of the setup docs.
![image](https://user-images.githubusercontent.com/62659043/81324769-4c492e00-904c-11ea-968e-3926789ae5d8.png)

**Comment by masi2602** [comment]
Ahh...damn I missed that part. What a stupid mistake. Sorry for the troubles and thanks for you quick support.

**Comment by JeneferM-MSFT** [comment]
No worries at all. Thanks for using CoE!
