### ISSUE TITLE
Import of .zip file fails - 80048060

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#266]
**Describe the bug**

Error when uploading CoEStarterKit.Zip into Solutions

![image](https://user-images.githubusercontent.com/8484048/81306178-179e9c00-9077-11ea-89cb-e65064dbc2d4.png)

**Component (please tell us which flow or app you are experiencing issues with):**
.zip file

**To Reproduce**
1. Select Solutions on the left navigation bar.

2. Select Import. A pop-up window appears. (If the window doesn't appear, be sure your browser's pop-up blocker is disabled and try again.)

3. In the pop-up window, select Choose File.

4. Choose the Center Of Excellence Core Components solution from the file explorer (CenterOfExcellenceCoreComponents_x_x_x_xx_managed.zip).

**Expected behavior**
The .zip file imports successfully

**Screenshots**
See above image.

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hi thanks for posting. We know that the zip file is correctly formatted as others have installed with it. Can you please validate that you have covered all the pre-req's needeD? 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

**Comment by NPrice99** [comment]
Extracting Components from .zip and importing each one seperately works with warnings

**Comment by JeneferM-MSFT** [comment]
oh i gotcha. Yes you need to extract the starter kit into individual components. I'll make sure this is clear in the documentation. Thanks!
