### ISSUE TITLE
Power BI report - UI Flow number

### ISSUE THREAD

**Issue by tmcg19** [microsoft/powerapps-tools#270]
in the Advances Power BI report under the flow Tab across the top there are 5 boxes, th 2nd last one is titled Ui Flows

We have no Ui Flows and are not even licensed for them but its has 2906 UiFlow count here.
What is this number or what is it representing?

**Comment by tmcg19** [comment]
![BITop](https://user-images.githubusercontent.com/56071180/81414427-e1c4ea80-913e-11ea-838b-954295ef25c2.gif)

**Comment by tmcg19** [comment]
![image](https://user-images.githubusercontent.com/56071180/81414472-f30df700-913e-11ea-886d-5e76e30847b3.png)

**Comment by JeneferM-MSFT** [comment]
it looks like the filter came off for this tile. please select it, and in the filter pane reset these values for admin_operation. 
![image](https://user-images.githubusercontent.com/62659043/81415282-16b04d80-90fd-11ea-9ed3-dee562a77fcd.png)

**Comment by JeneferM-MSFT** [comment]
Can you please confirm if this is resolved for you?

**Comment by tmcg19** [comment]
@JeneferM-MSFT  @manuelap-msft 
Sorry for not getting back on this. but no I was unable to resolve. within the Dashboard I do not have the filters you have listed I only have "executePassThroughNativeQuery"

And Again my browsers (Chrome & EDGE Chromium) will not allow me to upload Images to gethub, keep getting something went really wrong error??

**Comment by manuelap-msft** [comment]
It looks like there's an issue in the filter for tenants that do not have any UiFlows, we'll fix that with the next version.

In the meantime, can you change the Filter to
> Advanced Filter
> Contains
> UIFlow (type the word, there won't be a drop down)

![image](https://user-images.githubusercontent.com/55705669/83005480-c2680180-a008-11ea-9dc8-01933126c031.png)

This should return 0 in your case.
