### ISSUE TITLE
Configured data policies prevent activation of flows which use the 'shared_commondataservice' and 'shared_sharepointonline' connectors

### ISSUE THREAD

**Issue by gregwilliams14** [microsoft/powerapps-tools#271]
Getting this error when trying to start the flow to create document library.

**Comment by JeneferM-MSFT** [comment]
It sounds like your DLP policy doesn't allow you to use both CDS and SPO in a flow.  You'll either need to change your DLP policy or make this table by hand.

**Comment by gregwilliams14** [comment]
i added the connectors while ago.  after i posted the question i tried again - and now it is wokring,

**Comment by JeneferM-MSFT** [comment]
Wonderful. I also just noticed that we didn't include this in the list of connectors needed, so I updated the pre-reqs documentations to note. 
Thanks for using CoE!
