### ISSUE TITLE
COE installed - Flow Ran - No data

### ISSUE THREAD

**Issue by gregwilliams14** [microsoft/powerapps-tools#277]
I installed the COE.  Opened the Power BI and change the url to point to my COE environment.  I have no data.  I know I have approx. 69 Environments and 2600 apps.  What am I missing?

**Comment by JeneferM-MSFT** [comment]
Can you confirm that the sync flows ran already? 
Please go to the core solution, and look at the runs for this flow: Admin | Sync Template v2.
Note that if that has run, you should see the environments, but all the apps and such may not show up yet unless those flows have completed as well.
![image](https://user-images.githubusercontent.com/62659043/81594051-2e920680-9375-11ea-9c75-4c5e4fff7244.png)

**Comment by JeneferM-MSFT** [comment]
Another thing to check, is that you are logged in with the correct account for your CoE, and that the data has refreshed. 
Please check that your identity is correct in the upper corner as shown here:
![image](https://user-images.githubusercontent.com/62659043/81597756-12916380-937b-11ea-918d-c68965a45095.png)

And validate that you sign in after you changed the data source. To clear / reset these permissions:
Go back to transform data> Data Source Settings > Select your CDS data source > Clear Permissions.
This will force you to sign back in to refresh.

**Comment by gregwilliams14** [comment]
i reloaded and all is working now.

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thank you.
