### ISSUE TITLE
Last launched

### ISSUE THREAD

**Issue by gregwilliams14** [microsoft/powerapps-tools#281]
how does the last launched column get updated?

**Comment by JeneferM-MSFT** [comment]
The audit logs flow populates this. 
If you are using the basic authentication method, this works as shown below, but we overlooked this change in the AAD solution. Have made a local workitem to fix this for the next release.
![image](https://user-images.githubusercontent.com/62659043/81702726-82a5f500-9420-11ea-95b5-d078fa7c55be.png)

**Comment by gregwilliams14** [comment]
i used AAD.  When is next release?  And can I modify the existing?

**Comment by JeneferM-MSFT** [comment]
We're not sure when we will release next. But likely some time in the next few weeks. 

You are welcome to make the change locally if you'd like to try. But I wont be able to support you through that unfortunately. Once we make the change, if we arent releasing soon, we can respond here with the set of changes needed.

**Comment by manuelap-msft** [comment]
We have just released an update to fix this. You will need to upgrade to the latest version of the Audit Log solution for this to work:
https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Audit%20Log%20(MFA)

**Comment by gregwilliams14** [comment]
I downloaded the new zip and imported.  should I see a new flow or updated has show above?  if so, I do not see that.

**Comment by manuelap-msft** [comment]
You should see those two steps in the [Child] Admin | Sync Logs flow now.
![image](https://user-images.githubusercontent.com/55705669/81831351-2680c500-9535-11ea-9ddd-17e383f851c0.png)

**Comment by gregwilliams14** [comment]
I do not see that.  the solution displays as 1.0.0.13.  and the flow show that they were modified.

**Comment by manuelap-msft** [comment]
When you upgraded and looked at the Flows, did you have to configure the Flow actions and setup steps again or was everything still in place?
If everything was still in place, the upgrade didn't complete. 
Please try and choose Upgrade > Overwrite Customizations when you upgrade.

I have tested this upgrade on my end and the new elements are showing in the flow, but you will need to configure the flows again https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration

**Comment by gregwilliams14** [comment]
I did that.  I also reran the upgrade and selected overwrite.  now I can not edit the child flow.  can I just remove the solution and start fresh?

**Comment by gregwilliams14** [comment]
it is running now.  update when complete

**Comment by gregwilliams14** [comment]
Thanks for the help.  The flow has completed and the launch data is displaying.  however, It only is displaying for about 20 of 3000 apps that we have.  also the ones that have a display date have the same date 5/11 just a different time.

**Comment by manuelap-msft** [comment]
Thanks for confirming!

The Audit Log flow doesn't look back but only looks at your daily data, so it will populate with time. Likely by running it now it recorded your app launches from today.

**Comment by gregwilliams14** [comment]
but today to is 5/13 not 5/11

**Comment by manuelap-msft** [comment]
You an configure what time frame will be looked at in the Admin | Sync Audit Logs

1. Time intervals specified the interval you want to look at, so 1 day, 10 minutes etc
2. Start Time configures the start time in "get past time" - e.g. 2 days ago, 1 day ago
3. End time configures the end time, and must be within 24hrs of start time

See Step 4 and 5 here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

![image](https://user-images.githubusercontent.com/55705669/81840861-76658900-9541-11ea-90a3-f8380cdd8780.png)

**Comment by manuelap-msft** [comment]
If you need to look further back, you can do this out of the box in the Audit Log
https://protection.office.com/unifiedauditlog

By filtering by the "Launched app" event and setting your start and end time here - you can find more details here https://docs.microsoft.com/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-begin and https://docs.microsoft.com/office365/servicedescriptions/office-365-platform-service-description/office-365-securitycompliance-center

This is an out of the box functionality of Office 365.
