### ISSUE TITLE
Office 365 Management API cannot create a new connection

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#283]
**Describe the bug**
When I try to create a new connection in custom connector I am getting an error message. I have attached a screenshot below. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Audit Logs
 - Version - 1.0.0.7
 - Office 265 Management API

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/81755103-dac31280-9485-11ea-8ffe-74988c132a29.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Can you please provide some context here about which part of the CoE you are installing, and the step you are at in the instructions? Thank you!

**Comment by aakashpatel660** [comment]
Hello 

I am installing the Audit Logs solution. In the audit log, I am trying to set up an Office 365 Management API custom connector so I can run the audit logs flow. 

The issue I am facing is that when I try to test a connection in step 4 (As shown below Image). When I try to click on New connection to test custom connector. 

Instruction step > Under the Governance Component > Collect Audit Logs Data > Option 2> Start a subscription to the Audit Log Content > Step 1. 

Please let me know if there is anything else I need to do.

![image](https://user-images.githubusercontent.com/59940632/81764222-0c94a300-949f-11ea-85e3-4a51a600fb5d.png)

**Comment by manuelap-msft** [comment]
This error message usually indicates that the Azure App Registration has been set up incorrectly or that you have copied an invalid value into the Client ID field in the Security tab.

Can you confirm you have followed all the steps here
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration

And then updated the Security settings of the Custom Connector as outlined in Step 6 here 
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector

**Comment by aakashpatel660** [comment]
I was able to resolve issue. I selected the wrong permission in Azure. Thank you so much for your help. Quick question, Is COE  allowing or planning to develop something where we can see who has which role assigned in the environment?

**Comment by JeneferM-MSFT** [comment]
That wasnt on the backlog, but I have added it. Thanks for the idea!
Thanks for using CoE!
