### ISSUE TITLE
[BUG]: automatic archive of unused app

### ISSUE THREAD

**Issue by jsarkantyu** [microsoft/powerapps-tools#284]
**Describe the bug**
Not neccessery a bug but in the Center of Excellence - Compliance and Report Components part the flow "App Archive and Clean Up - Check Approvals and Archive" has a par wher it archive the unused application, by getting a http access to the app url and creating it to a new sharepoint file with the extension ".msapp", then it deletes the app. 
My problem is that we tried to restore the app from this file it is not possible, and clearly this way a lot of components are missing, like used pictures, etc, which is in an export package if we export the app manually. 
Our question is that how can we get an automated archive export zip package instead of the single .msapp file what can be used to restore the actual application? Or if the .msapp file can be used this way, how can we restore the app from that?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [CenterofExcellenceAuditComponents_1_9_managed]
 - Version [CenterofExcellenceAuditComponents_1_9_managed]
 - App or Flow [AdminAppArchiveandCleanUp-CheckApprovalsandArchive-311BCA28-F92B-EA11-A810-000D3A31C867.json]

**To Reproduce**

**Expected behavior**
Able to have an automated archive export zip package instead of the single .msapp file what can be used to restore the actual application, or if the .msapp file can be used this way, to be able to restore the app from that.

**Screenshots**
![image](https://user-images.githubusercontent.com/65290514/81815111-e536e800-9529-11ea-903c-6e0d5d9a2a14.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hi there. Can you please let me know how you are reloading the app? Here is how I do it, and media come through. 

- Go to the document library in which the app was saved in the flow
![image](https://user-images.githubusercontent.com/62659043/81826245-71c2b580-94ec-11ea-94eb-d413466d6150.png)

- Download the msapp file
- Go to the environment where you want to re-load, create new canvas app, open the file. 
![image](https://user-images.githubusercontent.com/62659043/81826538-c0704f80-94ec-11ea-969b-1b5144aacf21.png)

**Comment by Bryand13** [comment]
Hello

Could you explain how you do the process for archive only one app? Is there another way where you don't need to use the flow to archive one app?

Thanks in advance and sorry for bothering you.

**Comment by jsarkantyu** [comment]
> Hi there. Can you please let me know how you are reloading the app? Here is how I do it, and media come through.
> 
> * Go to the document library in which the app was saved in the flow
>   ![image](https://user-images.githubusercontent.com/62659043/81826245-71c2b580-94ec-11ea-94eb-d413466d6150.png)
> * Download the msapp file
> * Go to the environment where you want to re-load, create new canvas app, open the file.
>   ![image](https://user-images.githubusercontent.com/62659043/81826538-c0704f80-94ec-11ea-969b-1b5144aacf21.png)

I'll check this out soon, thanks. I have more than one things to work on. We're not using the COE kit word by word so maybe it will help solving this problem.

**Comment by JeneferM-MSFT** [comment]
To send out approval request for one app, or to change the criteria generally speaking, you will need to edit the following flow, which exists in the same solution as this one: **Admin | App Archive and Clean Up - Start Approval.** 

You can change the logic however you would like but the easiest way would be to capture a single app would be to change the condition shown below to look for it. 
![image](https://user-images.githubusercontent.com/62659043/81945190-9f723200-95b2-11ea-9ccf-12cd89788601.png)

**Comment by JeneferM-MSFT** [comment]
Hello. Checking in to see if this issue is resolved. 
Thank you for using CoE.

**Comment by JeneferM-MSFT** [comment]
Closing old issues with no action items on MSFT. Please return with a new issue if you need help in the future.
