### ISSUE TITLE
[BUG]: [Child] Admin | Sync Logs DLP error (No Connections)

### ISSUE THREAD

**Issue by rsch136** [microsoft/powerapps-tools#285]
**Describe the bug**
[Child] Admin | Sync Logs cannot be turned on. Error message: "Your flow could not turn on: [Child] Admin | Sync Logs. Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow '' cannot be activated due to admin API policies."}}"."

Set up according to Option2 of Doc: [https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog)

Custom connector added to DLP via PowerShell. 
```
Add-CustomConnectorToPolicy -PolicyName {PolicyName}
-ConnectorName shared_admin-5foffice-20365-20management-20api-5f15a5431e9ca2e1e2 
-GroupName hbi 
-ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/{environementID}/apis/shared_admin-5foffice-20365-20management-20api-5f15a5431e9ca2e1e2 
-ConnectorType Microsoft.PowerApps/apis
```
This was successful. Checked via PowerShell `Get-AdminDlpPolicy {PolicyName}`

Furthermore, child flow does not show any connections.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CenterofExcellenceAuditLogs_1_0_0_7_managed.zip
 - 1.0.0.7

**Screenshots**
![image](https://user-images.githubusercontent.com/44471683/81818254-19aca300-952e-11ea-801a-4ffca1b041f4.png)

![image](https://user-images.githubusercontent.com/44471683/81818487-61332f00-952e-11ea-807a-b6fbcc267d3d.png)

**Comment by manuelap-msft** [comment]
1. Is the PowerShell script exactly the one you used, I think your id contains a // between environments and apis environments//apis 
2. Have you tested the custom connector and set up a connection to it? This is important to complete before configuring the Child Flows https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-the-audit-log-content
3. You need to configure the Connections of the Child Flow following those steps https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow

**Comment by rsch136** [comment]
1. The actual parameter I used was -ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/<environementID>/apis/shared_admin-5foffice-20365-20management-20api-5f15a5431e9ca2e1e2

2. I have success fully set up the custom connector and set up a connection to it as per the cited instructions. I also added the custom connector to the necessary DLP after completing this step.

3. I have followed those instructions. Step 10. is the step where the bug occurs. I am not able to turn on the child flow. Attempting to do so produces the DLP error. Additionally, the (child) flow appears not to have any connections.

**Comment by manuelap-msft** [comment]
The DLP Violation might not have anything to do with the custom connector.

The environment must have a DLP policy that allows the following connectors to be used together: Common Data Service, Common Data Service (current environment), Office 365 Users, Power Platform for Admins, Power Automate Management, Office 365 Outlook, Power Apps for Admins, Power Apps for Makers, and SharePoint. Those connectors must be in the business data–only bucket of the DLP policy for this environment.

Are all of those connectors in your business data only group? Do you have multiple DLP policies set up that might affect this environment?

**Comment by rsch136** [comment]
While looking through all the DLP policies I noticed that I added the connector to a policy that is not assigned to our CoE Environment! Once I moved the connector, I was able to turn both flows on. Thank you!

We had originally created a policy that is only assigned to the CoE environment that includes all connectors. Perhaps we will reduce this to the listed connectors now.

Thanks again :)
