### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Model Driven Apps) failing for some environments

### ISSUE THREAD

**Issue by leozak06** [microsoft/powerapps-tools#287]
**Describe the bug**
Hi there, we updated our core components solutions with the newest version (1.45) and still facing the failed model driven app flow issue. The flow failed for 11 environments and giving me an error saying "CRM organization with unique name 'orgf38f21e8' not found." We are unable view model driven apps for those environments.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.45
 - Admin | Sync Template v2 (Model Driven Apps)

**Expected behavior**
Display ALL model driven apps in the tenant on Power Platform Admin View Model driven apps

**Screenshots**
<img width="765" alt="Capture" src="https://user-images.githubusercontent.com/22460241/81973501-128e9f00-95d9-11ea-9edc-7b4f6bf95738.PNG">

**Comment by JeneferM-MSFT** [comment]
Can you please look at the output of the **_Get Environment as Admin_** call up above your screenshot? And then validate that you have access to view the environments? Follow the links from the output as shown here:
![image](https://user-images.githubusercontent.com/62659043/81985782-8d60b580-95eb-11ea-9a5a-c3b1fa927997.png)

**Comment by leozak06** [comment]
Hi I don't see a Get Environment as Admin call
![image](https://user-images.githubusercontent.com/22460241/81987089-e5002080-95ed-11ea-9bf2-058aeb6cc648.png)

**Comment by JeneferM-MSFT** [comment]
I've pointed to it from your first screenshot
![image](https://user-images.githubusercontent.com/62659043/81987418-72dc0b80-95ee-11ea-97c8-d433da161107.png)

**Comment by leozak06** [comment]
Oh my bad sorry I will double check now

**Comment by JeneferM-MSFT** [comment]
No problem, there's a lot of collapsed steps. Let me know

**Comment by leozak06** [comment]
Hi Jenefer, we validated if the account that was used to set up CoE had access to the environments that caused the flow to fail and turns out even with admin role in the tenant, the account had environments with no access. We granted the account access and are able to see more and more model driven apps in the PowerApps App table.  Thanks so much for your help!

**Comment by JeneferM-MSFT** [comment]
Of course. Thanks for using the CoE.
