### ISSUE TITLE
Admin | Sync Flow (Custom Connector) causing DLP Violation

### ISSUE THREAD

**Issue by achaganti** [microsoft/powerapps-tools#288]
**Describe the bug**

**Component (Core Component -Custom Connector):**
 - Solution [Core]
 - Version [e.g. 1.44]
 - App or Flow [Admin | Sync Template v2 (Custom Connectors)]

**To Reproduce**
1. Trying to turn ON the custom connector results in the error although all the underlying connectors are already in the BUSINESS DATA..'

Your flow could not turn on: Admin | Sync Template v2 (Custom Connectors). Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow '' cannot be activated due to admin API policies."}}".

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/34516164/82061983-0c86e400-96e7-11ea-871a-5212ee887f38.png)

**Additional context**
Rest of the connectors are UP and running fine. This connector alone is throwing up this error.

**Comment by manuelap-msft** [comment]
The Admin | Sync Template v2 (Custom Connectors) is the only one of the sync flows that uses a HTTP call. Can you confirm HTTP is part of your business data only group?

You can find out how to achieve that here
https://powerapps.microsoft.com/en-us/blog/new-data-loss-prevention-capabilities-in-public-preview/

**Comment by achaganti** [comment]
Brilliant. Worked like a charm after adding http. Was this documented or I missed? Thanks so much.

**Comment by JeneferM-MSFT** [comment]
Thank you for letting us know. This was documentation we missed, but we are adding it now.
