### ISSUE TITLE
[BUG]: 'DLP Editor' and 'Set New App Owner' apps don't open

### ISSUE THREAD

**Issue by EditK** [microsoft/powerapps-tools#289]
**Description**
Unable to open the following Canvas apps:
- DLP Editor
- Set New App Owner

when clicking on the corresponding display names.

**Component**
 - Solution: Core Components
 - Version 1.39
 - Apps: DLP Editor and Set New App Owner

**To Reproduce**
1. Go to Solutions
2. Click on 'Center of Excellence - Core Components'
3. Sort to list canvas apps
4. Click on 'DLP Editor' or 'Set New App Owner' display name
4. I get redirected to 'Power Apps > Apps' view, none of the apps opens.

**Comment by JeneferM-MSFT** [comment]
Can you please share a screenshot of what you see?

**Comment by EditK** [comment]
**The following:**

![image](https://user-images.githubusercontent.com/4035464/82076505-3b4c8c80-96de-11ea-8bd1-a1dcfd1c2669.png)

**Comment by JeneferM-MSFT** [comment]
oh i see. I think you do not have permissions to the app. Did you do the setup of the CoE or did someone else?

**Comment by EditK** [comment]
Yes, I did the installation and setup, meaning via this Felix-user who is a power platform admin:

![image](https://user-images.githubusercontent.com/4035464/82089733-78237e00-96f4-11ea-9382-7ea98575d8c0.png)

**Comment by JeneferM-MSFT** [comment]
But you are not logged in as that user when you are hitting this correct? 
You will log in as the user that did the install to grant yourself permissions to apps.

**Comment by EditK** [comment]
I used that user to install, configure and run every COE component. That's my admin user.

**Comment by JeneferM-MSFT** [comment]
Is that the user seeing the bug you describe?

**Comment by manuelap-msft** [comment]
Hello,
can you please follow the below steps and describe the behaviour you are experiencing.

1. Navigate to make.powerapps.com
2. Select the Center of Excellence - Core Components solution and Filer to only show Canvas Apps components
![image](https://user-images.githubusercontent.com/55705669/82196271-6529cd00-98f1-11ea-9971-af11770d6330.png)
3. Select DLP Editor by clicking on the name (not the ...) 
4. This should open the App Detail View
![image](https://user-images.githubusercontent.com/55705669/82196390-8985a980-98f1-11ea-8ea2-93b4a7ca650b.png)
5. When you click on the Web Link on this page, what happens?
6. When you click on Share at the top of this page, is the user you are logged in with listed as owner, co-owner or user?
![image](https://user-images.githubusercontent.com/55705669/82196479-a621e180-98f1-11ea-83b0-ab9eee4b952d.png)

**Comment by JeneferM-MSFT** [comment]
Hello. Checking in to see if this issue is resolved. 
Thank you for using CoE.

**Comment by JeneferM-MSFT** [comment]
Closing old issues with no action items on MSFT. Please return with a new issue if you need help in the future.
