### ISSUE TITLE
Office 365 Management API custom connector not able to add to DLP

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#291]
**Describe the bug**
Hello, I was trying to add a custom connector into my DLP policy so I can run a flow. What i have found out is that if the custom connector is inside a solution and solution is managed. we can not add a custom connector into the DLP policy. I have tried using the PowerShell get-adminpowerappsconnector and did not return the custom connector information. To add a custom connector it does require connectorid and some other information. can you please provide a solution how should I add a custom connector into DLP policy if it inside a managed solution? 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Audit Logs
 - Version 1.0.0.15
 - Office 365 Management API

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
We have this iterated here: [Custom Connectors and DLP](https://docs.microsoft.com/power-platform/guidance/coe/limitations#custom-connectors-and-dlp)

Please let us know if this resolves the issue for you.

**Comment by aakashpatel660** [comment]
Hello

After adding the custom connector still not be able to turn on the flow. 

Error - Your flow could not turn on: [Child] Admin | Sync Logs. Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow '180da2e7-d7d9-4618-86d4-bfa465c58981' cannot be activated due to admin API policies."}}".

**Comment by JeneferM-MSFT** [comment]
The environment must have a DLP policy that allows the following connectors to be used together: Common Data Service, Common Data Service (current environment), Office 365 Users, Power Platform for Admins, Power Automate Management, Office 365 Outlook, Power Apps for Admins, Power Apps for Makers, and SharePoint. Those connectors must be in the business data–only bucket of the DLP policy for this environment.

Are all of those connectors in your business data only group? Do you have multiple DLP policies set up that might affect this environment?

**Comment by aakashpatel660** [comment]
Yes, all this connector are added into DLP policy. Yes, I do have multiple DLP policy setup. 

Best Regards,
Akash Patel

**Comment by JeneferM-MSFT** [comment]
If there are multiple policies applying to the same environment, either all of them have to have the connectors the CoE Starter Kit uses in business data only or if you have a policy that applies to all environments that you don't want to change you could exclude the CoE environment from that.

**Comment by aakashpatel660** [comment]
I was able to fix the issue by reconfiguring the connection and deleting my existing connection.
