### ISSUE TITLE
[Feature Request] Governance and audit approach to Flows - as done for APPs

### ISSUE THREAD

**Issue by tmcg19** [microsoft/powerapps-tools#292]
Not really a bug but a question.
the Flows for governance and audit logs are all for **APPS**, not Flows:
Admin | **APP** Archive and Clean Up – Start Approval
Admin | **APP** Archive and Clean Up – Check Approval
Audit Log Sync flow connects to the Office 365 Audit Log to gather telemetry data (unique users, launches) for **APPS**. 

The 'Admin | Sync Template v2' all these core flows gather data on Apps and Flows within all environments. 

Can Archive and Clean Up flows and Audit Log Sync flow be duplicated and edited in a some way to cover and provide the same governance and audit approach to Flows in the Environments as has been provided for the PowerApps.

Maybe I missed details on this, but is there guidance on getting the same set up for Flows.
And if not possible what are the reasons why for that?

Thank you.

**Comment by JeneferM-MSFT** [comment]
Thanks for the suggestion. This is on our backlog now, but isnt something we will likely do in the near term due to conflicting priorities. It shouldnt be a terribly difficult amount of work, so if you do take a stab and get it working before us. Please let us know!

**Comment by JeneferM-MSFT** [comment]
We have Power Automate versions of these two flows now ready in our local environment, so they will be able to ship with our next update.
- Admin | APP (Flow) Archive and Clean Up – Start Approval
- Admin | APP (Flow) Archive and Clean Up – Check Approval

For this one, the Flow team does not submit data to the office logs, they are working on a telemetry story but for today we don't have those to gather for you. 
- Audit Log Sync flow connects to the Office 365 Audit Log to gather telemetry data (unique users, launches) for APPS.

Thanks for helping CoE be great!

**Comment by JeneferM-MSFT** [comment]
This is now available in the new version of the CoE. We have also included a helper app for re-hydrating old flows that you archive.

Thanks for using the CoE!
