### ISSUE TITLE
[QUESTION]: Flows - App Archive and Clean Up

### ISSUE THREAD

**Issue by gilbertofloreztella** [microsoft/powerapps-tools#293]
Hello, this is more a question, do you have in yor roadmap the incorporation of cleaning up model-driven Apps?

**Comment by JeneferM-MSFT** [comment]
Can you clarify more what you mean by cleanup?

**Comment by gilbertofloreztella** [comment]
Sure!! The flows "App Archive and Clean Up - Check Approvals and Archive" and "App Archive and Clean Up - Start Approval" are not taking into account the model-driven apps to archive them. IDo you have this implementation in your roadmap?

**Comment by JeneferM-MSFT** [comment]
Thanks for the feedback. Unfortunately applying this solution to model driven apps is not on our backlog. However if this is something you work on and find a solution you like, we'd love to hear about it. 

Thanks for using CoE!
