### ISSUE TITLE
[Request]: Fails reported - Admin | Sync Template v2 (Custom Connectors)

### ISSUE THREAD

**Issue by tmcg19** [microsoft/powerapps-tools#294]
**Describe the bug**
Each Day I get the email form Admin | Sync Flow Errors.
The Errors are not from that day always, but sometimes they are. so the email will  highlight errors recorded in total. 
First question is there mechanism to rest these error messages so once viewed and confirmed they can be remove. and second question is on the Error I'm getting. 
Th error is always related to the Flow  Admin | Sync Template v2 (Custom Connectors), 
the error is in the Get Connection Swagger JSON:
Details
Start time
May 13, 01:17 AM (1 wk ago)
Duration
00:00:02
Status
Failed
Error
Action 'GET_connector_swagger_JSON' failed
Error Details
Unable to process template language expressions in action 'GET_connector_swagger_JSON' inputs at line '1' and column '1957': 'Required property 'uri' expects a value but got null. Path ''.'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**
The Error in does not happen all the time within the Flow, it seems to be once every 1-2 weeks,

**Comment by JeneferM-MSFT** [comment]
Hi. Thanks for the feedback. This does seem like an area we could make better. I have put it on our backlog, but we likely wont get to it soon. 

If you would like to change this before we get to it, one simple thing you could do is add an ODATA filter query here in Core's **_Admin | Sync Template v2 (Sync Flow Errors)_** to only get the last day or two of items. I wont be able to help you create that, but if you do and would like to share here for others, please do! :)

![image](https://user-images.githubusercontent.com/62659043/82458912-22d8cb00-9a6c-11ea-81b8-1608978617d2.png)

Thanks for helping make CoE great!

**Comment by JeneferM-MSFT** [comment]
Hi there. As I started to investigate this, I noticed that we do, in fact, already have a clean up mechanism in the flow. Can you validate that you see the following at the bottom of this flow? **_Admin | Sync Template v2 (Sync Flow Errors)_**

![image](https://user-images.githubusercontent.com/62659043/83303193-786e4f80-a1b1-11ea-9dcc-1a8f8d7f5ee7.png)

**Comment by JeneferM-MSFT** [comment]
Hi there. Can you confirm that you see this, or that the issue persists after multiple runs of the sync flows? Otherwise I presume this is resolved for you after upgrade and multiple runs. 
Thank you!

**Comment by JeneferM-MSFT** [comment]
Closing old issues with no action items on MSFT. Please return with a new issue if you need help in the future.
