### ISSUE TITLE
[BUG]: Audit Logs Flow failing after update

### ISSUE THREAD

**Issue by leozak06** [microsoft/powerapps-tools#295]
Hi there, We updated the Audit Logs solution in our center of excellence and now the flows are failing. The Admin|Sync is failing when it tried to trigger the child flow. Please see the error message in the screenshot below. I am using a global admin connection and struggling with setting up the connection. I re-entered the security information for the custom connector, and when I try to add a connection to test, it authenticates for a second but does not add the connection. I am not sure if I am missing a step here. Please let me know if there is a solution to this issue. Appreciate the help.
![image](https://user-images.githubusercontent.com/22460241/82484932-832d3400-9a8f-11ea-8bbc-faf147bedac0.png)

**Comment by JeneferM-MSFT** [comment]
Were you able to successfully test and start the subscription as described here: [Connect to the Audit Log by using an Azure App Registration](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration)

**Comment by leozak06** [comment]
Yes, it was running successfully before I updated the solution

**Comment by JeneferM-MSFT** [comment]
Thanks for that information. 
For upgrade, you don't have to set the Azure App Registration up again, but everything else in the solution you would have to configure again - so you will have to configure the custom connector Security Authentication again, test it to create a new connection and then update the Admin Sync Flow with their tenant ID.

I hope that helps.

**Comment by leozak06** [comment]
Hello, I did not set up Azure App Registration again but I did configure the custom connector security authentication again with the client id/secret and url that I had saved in my computer when I first set up the Azure App Registration and tried testing it. When I tried to create a new connection, I saw the loading symbol for 3 seconds and then nothing happened so no new connection was created, probably why I am getting the error at the top.

**Comment by leozak06** [comment]
Hi there, please close the ticket. We were able to get the flows to work. I was using the redirect url for the resource url.

**Comment by JeneferM-MSFT** [comment]
Oh wonderful. Thank you for the update!
