### ISSUE TITLE
Not a bug: How to import only an app from the solution, rather than the entire solution 

### ISSUE THREAD

**Issue by tstjohnsfg** [microsoft/powerapps-tools#296]
I unfortunately overwrote the App Catalog app with the Admin - Access this App canvas app. Would it be possible for me to import only the App Catalog canvas app or should i reconfigure the entire Nurture solution?

**Comment by JeneferM-MSFT** [comment]
There is an msapp copy of the canvas app in the the CanvasApps folder of the unzipped solution. 
You can then create a new app > Open > Select this file. 

Hope that helps. Please do let me know.

**Comment by tstjohnsfg** [comment]
Thank you! That was exactly what I was looking for.
