### ISSUE TITLE
[BUG]: Power Platform Admin View (model driven app) - App Sharing functionality not working. 

### ISSUE THREAD

**Issue by palak-hub** [microsoft/powerapps-tools#299]
Bug Details : 

In the Power Platform Admin View (Model-driven app), on selecting any application from the list, Share option is available for sharing that particular app with a user or a specific group. This sharing panel includes a number of permissions which we can assign to the selected users. Even after selecting proper inputs , this functionality is not working. We are not able to share the application via this panel.

PFA for the steps we followed.

![PowerPlatformAdminViewAppIssue](https://user-images.githubusercontent.com/58728605/82549571-c4e6d900-9b7a-11ea-8abc-28da19ad8718.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : Core
 - App or Flow : Power Platform Admin View

**To Reproduce**
1. Go to 'Power Platform Admin View Application'
2. Click on 'Apps', and select any Application from the list.
3. Click on the 'Share' button on the upper bar.
4. Select the user and assign the permissions for the application.
5. Click on 'Share'.

But the application is not shared with the selected User.

**Expected behavior**
The Application should be shared with the selected User with the assigned permissions.

**Screenshots**
![PowerPlatformAdminViewAppIssue](https://user-images.githubusercontent.com/58728605/82550184-c49b0d80-9b7b-11ea-98c0-6579c553f369.png)

**Comment by manuelap-msft** [comment]
The Sync Flows of the CoE Starter Kit sync your tenant resources into Common Data Service entities  (https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/entities). Each record in the entity represents one resource - e.g. if you look at the PowerApps App entity, you will find one row (one record) per app that you have in your environment.

The Power Platform Admin View is a Model Driven App (https://docs.microsoft.com/en-us/powerapps/user/use-model-driven-apps) that is based on those CDS entities. 

Model Driven Apps come with a lot of out of the box functionality, such as the ability to assign or share records - find out more here https://docs.microsoft.com/en-us/powerapps/user/assign-or-share-records

The Share button you are highlighting is to share the record, not the app. There is no link between the Share button here and the app itself, but you can use PowerShell cmdlets, the Set New App Owner app or the Management connectors to share apps. 

This is not a bug, just looks like a misunderstanding of how model driven apps work.

**Comment by palak-hub** [comment]
The highlighted Statement in the attached screenshot  clearly indicates that we can 'share' the PowerApps app with the given permissions to the selected User.

If  this is not the functionality then what is the actual significance of the 'Share'  which is available once we select a particular Application from the List.

Please find the attachment.
![PowerAdmin_Share](https://user-images.githubusercontent.com/58728605/82564063-bf4abc80-9b95-11ea-95b6-2462decdc93c.png)

**Comment by manuelap-msft** [comment]
The Entity in the background is called PowerApps App - it is the name of the Entity that is surfaced in the model driven app form and view. It does not refer to a Power Apps application. You can share the record, for other users to see this specific record (so see the app details you have in the record).

Here's a great Learn model on understanding model driven apps and Common Data Service entities
https://docs.microsoft.com/en-us/learn/paths/create-app-models-business-processes/
