### ISSUE TITLE
Environment names that include quotes cause the flows to fail

### ISSUE THREAD

**Issue by stmccartney** [microsoft/powerapps-tools#30]
In the v1 flow "Admin | Sync Template", if an environment display name includes a single quote, this causes the flow to fail.  Wherever the environment display name is used, it needs to be escaped and replaced as per the below:
replace(items('Apply_to_each_Environment')?['properties']?['displayName'],'''','''''')
![image](https://user-images.githubusercontent.com/4559521/66397568-03f16100-e9d4-11e9-9aee-9f6af1e55033.png)

**Comment by manuelap-msft** [comment]
Thank you for pointing this out, we've published a new version yesterday that includes this fix.

**Comment by stmccartney** [comment]
Confirmed that works now, thanks for the quick response!
