### ISSUE TITLE
[Office 365 Management API]: Authorization has been denied for this request

### ISSUE THREAD

**Issue by Bryand13** [microsoft/powerapps-tools#300]
**[Office 365 Management API]: Authorization has been denied for this request**
Hello,
Its not a bug itself. After create the API in Azure and set up the conector, when we want to test it, we get the following error:

Header:
{
  "cache-control": "no-cache",
  "content-length": "61",
  "content-type": "application/json; charset=utf-8",
  "date": "Thu, 21 May 2020 11:06:19 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "www-authenticate": "Bearer",
  "x-aspnet-version": "4.0.30319",
  "x-powered-by": "ASP.NET"
}

Body:
**{
  "Message": "Authorization has been denied for this request."
}**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Center of Excellence - Audit Logs]
 - Version [1.0.0.15]
 - App or Flow [Office 365 Management API]

**To Reproduce**

**Expected behavior**

**Screenshots**

Permission on the API:
![image](https://user-images.githubusercontent.com/50946094/82553714-df15bc80-9b64-11ea-81fb-2632823ea129.png)

**Additional context**
Maybe we are doing something wrong but everything seems set up correctly.
My user has global admin rol and we have enabled the auditlogs

**Comment by manuelap-msft** [comment]
The Azure App Registration permissions look okay to me, can you confirm you have configured the custom connector as described here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector

The main part here is the configuration under Security - make sure you've copy&pasted the correct IDs under Client ID and Client Secret

**Comment by Bryand13** [comment]
Hello @manuelap-msft ,
Thank you for your response.

Yes, I've been following the documentation step by step. Copying the necessaries ID's correctly. Still not working, its quite strange.

**Comment by manuelap-msft** [comment]
I have recently had a user have an issue where they had to activate VPN and then it worked. Could it be there's something in your network blocking the activity?

**Comment by Bryand13** [comment]
Hello @manuelap-msft 

It works. But trust me, yesterday i was working outside the VPN and still it wasn't working. Right now i disconnected the VPN, rebuild a new conexion for the conector, set the security variables and guess what, it works!.

Thank you so much.

**Comment by JeneferM-MSFT** [comment]
Thank you for using CoE!
