### ISSUE TITLE
[BUG]: Daily Report email confusing when there are no DLP violations 

### ISSUE THREAD

**Issue by briangre** [microsoft/powerapps-tools#301]
**Describe the bug**
Admins receive an email that says "the following PowerApps are using unauthorized connectors and have been shared with the Power Platform Admin Security Group"; however, there are no Power Apps listed. This is very confusing and could be alarming to an admin wanting to know why there are no apps listed.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Compliance]
 - Version [1.17]
 - Flow [SETUP REQUIRED | Admin | Find and add admins as owners for apps that leverage certain connectors]

**To Reproduce**
1. Configure components as in setup doc and wait for first run of this flow when you have no unauthorized connectors in use.

**Expected behavior**
I would expect one of two things. Either a) the daily report text is conditional and if there are no violations, then say "there are no violations" or b) sending of the daily report is dependent on actually having violations.

**Screenshots**
![image](https://user-images.githubusercontent.com/16060122/82561000-8a604a80-9b40-11ea-94cb-2a4cc1036bf9.png)
![image](https://user-images.githubusercontent.com/16060122/82561025-9b10c080-9b40-11ea-8f8a-459483a3fd97.png)
![image](https://user-images.githubusercontent.com/16060122/82561034-a237ce80-9b40-11ea-8b3f-fc183c59d612.png)

**Additional context**
Two other things (maybe these should be filed separately, but apply to the same flow?):
1. to adhere to marketing the text of the email should separate "Power" and "Apps"
2. the name of the flow says "SETUP REQUIRED" in capital letters, but I didn't see anything in the setup documentation around the two flows that are so named. I have since found that content regarding the empty array of disabled connectors, but there should be a link in the setup documentation to the page on the additional configuration
3. even if there are connectors in the disabled connectors array, but no violations the email is still confusing without the conditional text

**Comment by briangre** [comment]
it appears that this is not an issue with "SETUP REQUIRED | Admin | Find and disable flows that leverage certain connectors" as evidenced by this screenshot:

![image](https://user-images.githubusercontent.com/16060122/82561841-145ce300-9b42-11ea-961e-f7ad534c7fad.png)

**Comment by JeneferM-MSFT** [comment]
Hi Brian. Thanks and good catch. Yes we did not do that condition in the other similar flow:
![image](https://user-images.githubusercontent.com/62659043/82580500-0ad47a80-9b44-11ea-9be1-e310066c7a5e.png)
 
I'm looking at this now.

**Comment by JeneferM-MSFT** [comment]
I have updated this in our local version of the solution, and have also made the other small changes you recommend. Will close here with that release. 
Thanks for the feedback and for helping to make CoE great!

**Comment by JeneferM-MSFT** [comment]
A new version of the CoE is now available including these changes. 
Thanks for using CoE!
