### ISSUE TITLE
403 Forbidden - privilege issues

### ISSUE THREAD

**Issue by ltwlf** [microsoft/powerapps-tools#302]
Hello,

we get a 404 in all "Power Apps for Admins (Preview)" Flow actions. 
We configured a service user with 
the following permissions:
![image](https://user-images.githubusercontent.com/965766/82655711-e7ccc800-9c22-11ea-9d2f-bb85c340fad5.png)

The documentation states:
"**Microsoft Power Platform service admin, global tenant admin, or Dynamics 365 service admin** for access to all tenant resources through the Power Apps APIs" 

So our user has every permission except of the global admin. We want to configure the CoE with minimal privileges and the documentation says **or** global tenant admin. 

Same issue with Audit Log Connector: 
Documentation:
You must have access to the Office 365 Audit Log. The Power Platform Service Admin role does not give you access to the Audit Log. Which permissions are this exactly? We assigned the service user "security reader"
![security admin](https://user-images.githubusercontent.com/965766/82656283-c7513d80-9c23-11ea-8353-f69f7983467a.png) which should have audit log read permissions, but we also get 404.

Would be great when the documentation would be more explicit about the privileges. 

Hope you can clarify this.

Thanks, best wishes & take care

Christian

**Comment by JeneferM-MSFT** [comment]
For the Audit Log, the Power Platform Service Admin or Dynamics 365 Admin role do not give you access to the Audit Log so higher permission is required for that. 

The second bullet point here describes the permissions a Global Admin must give you to be able to view the Audit Logs: [Before You Begin Searching the Audit Logs](https://docs.microsoft.com/microsoft-365/compliance/search-the-audit-log-in-security-and-compliance?view=o365-worldwide#before-you-begin)

- You have to be assigned the View-Only Audit Logs or Audit Logs role in Exchange Online to search the audit log. By default, these roles are assigned to the Compliance Management and Organization Management role groups on the **Permissions** page in the Exchange admin center. Note global administrators in Office 365 and Microsoft 365 are automatically added as members of the Organization Management role group in Exchange Online. To give a user the ability to search the audit log with the minimum level of privileges, you can create a custom role group in Exchange Online, add the View-Only Audit Logs or Audit Logs role, and then add the user as a member of the new role group.

I will add a link to this from our documentation

**Comment by JeneferM-MSFT** [comment]
The Power Platform Admin role will be sufficient to use the management connectors, and will have access to all Power Platform environments. 

Are you able to navigate to the [Power Platform Admin Center](https://aka.ms/ppac) with the logged in user? What other action are you getting the 404 on? Is it just the Power Platform Management connector ones or other actions (e.g. if the Office 365 Users action fails, it could be there user doesn't have an Office 365 License assigned)

Most of the customers that have the CoE Kit installed aren't Global Admins and get it working, so I believe this is something with your user. 

Let me know if you need more help.

**Comment by ltwlf** [comment]
Thanks @JeneferM-MSFT we have it finally running with a non-admin. It seems there were some connections issues, because we didn't use the service user for the setup and changed the connection afterwards. Can't really say what issue finally was, but my recommendation is to use the service user also for setup. 
Thanks for your help!
