### ISSUE TITLE
[BUG]: Developer Environments are not visible on Power BI Report Dashboard

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#303]
**Describe the bug**
In Power Platform, I  have two developers environments created by different users via"Power Apps Community Plan" plan, one trial environment, and one default environment, however in COE Power BI dashboard, As a Global Admin, I see only trial and default environments, Can you please share why developer environments are not visible? Is it expected behavior by design?

**Note:** As a Global Admin, I see trial and default environments including Developer environments created by "Power Apps Community Plan" in COE Report Dashboard.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Component Solution
 - Version 1.44
- Power BI Dashboard

**To Reproduce**
1. Go to published report - Dashboard-PowerPlatformAdminDashboard
2. Click on "Overview - PowerApps"
3. Look at "Top 20 Environments by App Count" - This tile doesn't show developer environments.
Also, against the default and trial environments, Apps and Flow counts are "0" while, there are a couple of apps and flows in default and trial environments.

**Expected behavior**
"Top 20 Environments by App Count" tile should display developer environments as well as the total number of apps and flows against the environment

Thank you in advance!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hello. I'm not sure which screen in the PBI you are referencing, so if the below doesnt answer your question, please do share a screenshot.

We don't track model driven apps from developer type environments as the product does not give admin permissions to view them by default. If your developer environment does not have any canvas apps, it will not show up in the apps view as a result as the CoE will not think it has any apps at all. 

If you would like to track model driven apps in dev environments in your CoE
1) Make sure you have given permissions to the user that will run the sync flows
2) Remove this condition from the Model Driven App sync flow.
 
![image](https://user-images.githubusercontent.com/62659043/82923317-9dec2680-9f2f-11ea-80d6-46a24ca80af9.png)

I hope that helps and thanks for using CoE

**Comment by dips23** [comment]
Thank you very much for your response!

However, I have created an app in Dev environment created by "Power Apps
Community Plan" - which did not appear in below screen:

[image: image.png]

It only shows "Trial" and "default" environment while it doesn't show "Dev"
environments created by "PowerApps Community" plan.

Kind Regards,

Dipti

**Comment by JeneferM-MSFT** [comment]
Can you please look at the data in the "Environment" entity? 
Either **_Edit Data in Excel_** or go to the **_Data tab_** and show _**All fields**_
![image](https://user-images.githubusercontent.com/62659043/83434922-3848e000-a3f0-11ea-97a0-9dd6379c9a9c.png)

1) Are the environments you expect to see but do not see present? 
2) In the **_Environment Deleted_** column, does it say "no" or blank?

**Comment by dips23** [comment]
I do not have the "Environment" entity available in  CDS. Can you please
share how can I make that available?

Kind Regards,

Dipti

**Comment by JeneferM-MSFT** [comment]
when you are viewing entities, be sure to change the view to show all entities. 
![image](https://user-images.githubusercontent.com/62659043/83885074-b5c76580-a6fa-11ea-8452-7b2ebc0676e7.png)

**Comment by dips23** [comment]
Got it, Thanks!

Actually it's displaying totally wrong data as per the "Environment
Deleted" column:

For example CDS Data shows as follows:
Display Name Status Environment CDS Instance URL Environment Created
On Environment
Deleted
Default Env Active https://cdsenv.crm8.dynamics.com/ 2016-10-12T03:46:45Z No
User 1 Dev Env created by PC plan Active   2020-05-20T10:51:07Z No
User 2 Dev Env created by PC plan Active   2020-05-20T11:07:13Z No
User 3 Dev Env created by PC plan Active   2020-05-20T11:02:10Z Yes
Trial Environment Active https://cdsenv.crm.dynamics.com/
2020-05-01T09:14:02Z Yes

While the Power BI Report shows the following environment:
Top 20 Environments by App Account
Default Env
Trial Environment

What could be wrong?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Sorry I'm having trouble following the textual format above, can you please include pictures of what you see in the Power BI report?

**Comment by dips23** [comment]
Hi Jen,

Sorry about this, Please find the same information in image form:

CDS Data shows as follows:
![image](https://user-images.githubusercontent.com/13658386/84103484-c6e0e100-aa30-11ea-9323-88b62bc1d1f0.png)

While the Power BI Report shows the following environment:
![image](https://user-images.githubusercontent.com/13658386/84103511-d829ed80-aa30-11ea-80cc-348caff2c550.png)

I am referring to this image for Power BI dashboard - https://user-images.githubusercontent.com/13658386/83408703-b036fa80-a430-11ea-9f32-28b7dfa0712a.png

I hope this would be clear, please let me know if you require any further information.

Thanks for your time!

**Comment by dips23** [comment]
Hi Jen,

just to check with you if any updates on this, I am still unable to see dev environments.

Looking forward to hearing from you soon!

Thanks,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hi it seems like your PowerBI report doesnt have the same filters as we do at release. I would expect to see the first three in your list, and not the last two as we filter out deleted by default. 

Can you please [re-install with the PBIX file](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi#option-2-configure-the-power-bi-dashboard-by-using-the-pbix-file) and see if you still see the issue?

**Comment by JeneferM-MSFT** [comment]
Hi there. Checking in to see this is resolved for you.

**Comment by JeneferM-MSFT** [comment]
Closing issues with no additional steps to be done. Please reach out or post a new bug if you experience additional problems. 
Thanks for using CoE!
