### ISSUE TITLE
[BUG]: Admin Flow add admins as owner for apps which use certain connectors

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#304]
**Describe the bug**
I was running this flow and based on the title it should add an owner to the certain app which are using a certain connector but when I run this app it sends me an email saying that it disabled the app. It should say that it added the group to the app. Also when it tries to add a security group into an app it throws an error message saying could not add a group. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Compliance and Report Components
 - Version - 1.17
 - Flow - SETUP REQUIRED | Admin | Find and add admins as owners for apps that leverage certain connectors

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/82928493-532ed680-9f50-11ea-9fb5-9ae62206a513.png)

![image](https://user-images.githubusercontent.com/59940632/82928643-75c0ef80-9f50-11ea-919b-1d8c9d1fb96e.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
The note in the email is a typo from copy-pasting that email step from another flow. Thanks for letting us know, we've updated for the next version of the CoE. 

For the failure to add the group, can you please show what you have for the environment variable for Power Platform Admin Security Group? 
Note that it needs to be the Object Id, not an email address, as shown here:
![image](https://user-images.githubusercontent.com/62659043/82938888-55406780-9f47-11ea-8661-0b6fa52864c8.png)

**Comment by aakashpatel660** [comment]
Error Message{  "error": {    "code": "SolutionAppCanEditShareNotAllowedWithGroups",    "message": "The solution aware canvas application could not be shared with a security group with edit or share permissions"  }}
Action 'Check_if_connection_references_are_not_null' failed

    On Tuesday, 26 May, 2020, 02:55:56 pm GMT-4, Jenefer Monroe <notifications@github.com> wrote:  
 
 


The note in the email is a typo from copy-pasting that email step from another flow. Thanks for letting us know, we've updated for the next version of the CoE.

For the failure to add the group, can you please show what you have for the environment variable for Power Platform Admin Security Group?
Note that it needs to be the Object Id, not an email address, as shown here:

**Comment by JeneferM-MSFT** [comment]
We are able to reproduce this. It seems there is a product limitation on this feature for apps in solutions. We are seeing if there is a workaround.

**Comment by JeneferM-MSFT** [comment]
Hello. Unfortunately there isnt a workaround for this. We have put a fix on the backlog for the product team. 
Thanks for using CoE!
