### ISSUE TITLE
[BUG]: SaveAs option is throwing an error for "Admin | Sync Template v2"

### ISSUE THREAD

**Issue by Somu76** [microsoft/powerapps-tools#307]
**Describe the bug**
When trying to Save the Flow as per instructions on setting up the Flows for COE Core Components, I am getting the following error:
The pagination policy of workflow run action 'List_Makers' of type 'ApiConnection' at line '1' and column '3932' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '10000'. Maximum: '5000'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture] : Core Components
 - Version [e.g. 1.29] : 1.45
 - App or Flow [e.g. Sync Template (v2)] : FLOW (Admin | Sync Template v2)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12059785/83158548-e5f77e80-a0d2-11ea-8a47-3b585898bb5f.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

it looks like the license plan you have is enforcing some limits regarding pagination. Can you please edit the flow, find the List Makers action, click on the ... and select Settings and change the Pagination from 10000 to 5000.

![image](https://user-images.githubusercontent.com/55705669/83161477-654f7700-a100-11ea-8fd5-e490f3fc88ca.png)

![image](https://user-images.githubusercontent.com/55705669/83161510-6f717580-a100-11ea-9538-b5e7a0373340.png)

**Comment by JeneferM-MSFT** [comment]
We have local fixed these all to have 5,000 threshold instead so you wont have to go through this again with the next update.

**Comment by martindr** [comment]
How does one edit the flow, since the error prevents 'save  as' from the solution?

**Comment by manuelap-msft** [comment]
In the same screen you were on when you selected "save as", one of the options in the navigation bar is "Edit". From there you should be able to edit the flow directly in the solution.

**Comment by martindr** [comment]
Thanks. That option is disabled for me, although I'm in the Power Platform Administrator role (which is how I installed the starter kit). Is there a further permission one needs in order to edit?

**Comment by martindr** [comment]
Alternatively, I'll wait for the next update if it is coming soon. Any idea when?

**Comment by martindr** [comment]
**Update:** I found that a colleague was able to execute this without encountering the pagination error. As far as I can tell she has the same rights as me but I'm guessing there is some subtle licensing difference at some layer that yields different experiences for each of us.

**Comment by manuelap-msft** [comment]
That's great that you got it working! I am closing the issue for now, but please feel free to reach out again if you have further issues.

Thanks for using the CoE Starter Kit!

**Comment by shortboard** [comment]
I'mm having this same issue currently. I've tried editing as suggested but i'm receiving this error when trying to save it again:
_Some of the connections are not authorized yet. If you just created a workflow from a template, please add the authorized connections to your workflow before saving._

I'm not sure how to proceed, when is the fix expected to be available?

**Comment by manuelap-msft** [comment]
This error

> Some of the connections are not authorized yet. If you just created a workflow from a template, please add the authorized connections to your workflow before saving.

stems from some connections not being authorized yet, you can identify them by a small yellow triangle being shown. They could be hiding in Conditions or Loops so make sure to expand every action in the Flow to check if you have authorized all connections.

**Comment by shortboard** [comment]
Thanks,

I thought i had caught them all but one was hiding deep in a switch statement. I've run into a new issue now; trying to use "Save As" on the flow returns this error:
_The XRM workflow entity could not be found._

It then won't allow me to save a copy. I've tried googling around but i can't find any info on the issue.

Regards,
Damien

**Comment by maxknu** [comment]
Hi All, ### make sure you have REAL power Apps Per User license and not the Office 365 license which is restricted to maximum 5000 calls.
