### ISSUE TITLE
[BUG]: PowerBI Dashboard reports duplicate values

### ISSUE THREAD

**Issue by breakpoint7** [microsoft/powerapps-tools#309]
I setup PowerBI Dashboard following the instructions for AppSource via https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi

The data source is throws an error:
Data source errorColumn 'createdby' in Table 'admin_COESettings' contains a duplicate value '<pii>5ddb78ad-a782-442c-a840-e540785cee00</pii>' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table. Table: admin_COESettings.

Any idea how to correct this?

**Comment by JeneferM-MSFT** [comment]
Can you please go and make sure you only have one row of data in the CoE Settings table? Here is how to [access the CoE Settings Entity](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#configure-the-coe-settings-entity).

You should only have one record as shown here:
![image](https://user-images.githubusercontent.com/62659043/83291887-ffb1c800-a19d-11ea-8933-830b4eb233d1.png)

**Comment by breakpoint7** [comment]
Bingo. That was it.  Thanks... I should have caught that.

**Comment by JeneferM-MSFT** [comment]
Glad to help. Thanks for using CoE!
