### ISSUE TITLE
Issue with looking up unpublished model driven apps

### ISSUE THREAD

**Issue by melmgcoe** [microsoft/powerapps-tools#312]
Hi there,

We've devleoped an app within our CoE that allows our Service Desk staff to perform a lookup for details relating to canvas and model driven apps in all environments. The aim is to help our Service Desk gather details if an issue is reported for a particular app.

I believe the app has been developed using the PowerApp app solution bundled as part of the CoE core compononent installation. However it's unable to look up certain model driven apps that exist in our default environment. I can see these apps directly via make.powerapps.com but the app can't which points to an issue with how the details for gathered and passed onto the app. I assume this is done through the audit flow which tracks model driven apps, please can someone assist me to troubleshoot this issue.

Regards,

Mel

**Comment by melmgcoe** [comment]
Hi there,

Is someone able to pick up this issue ASAP and come back to me with an update?

Thanks

**Comment by manuelap-msft** [comment]
Hello,

apologies, I only just saw this - this GitHub repo is used for many projects, and therefore raising the issue through the appropriate link will tag it and automatically assign it to the right team. For the CoE Kit that link is https://aka.ms/coe-starter-kit-issues

If you navigate to make.powerapps.com in your CoE environment, and open the Power Platform Admin View 
1. Navigate to Apps
2. Select Model Driven Apps from the View drop down

**Comment by melmgcoe** [comment]
Hi Jenefer,

I see Manuela has assigned this ticket to yourself. I'm assuming our service account does have permission to the environment as we some model driven apps appear in the view Manuela asked me to check.

I've looked at the admin flow which syncs model driven apps as part of the CoE core component solution and see that it's failing for our default environment at the point where it's attempting to store a record of model driven apps in the CDS. Specifically it's going wrong at the stage where it gets the user profile for a certain app. See screenshot below:

![Capture](https://user-images.githubusercontent.com/62425530/84790247-0e470e80-afe9-11ea-9a1e-a3b74ac370c2.JPG)

This looks like it's failing to collect info about the user who created the app as that user has since left our company. Can you confirm if that's the case and if so, would this prevent the sync template from collecting info for other model driven apps that are missing from the Power Platform Admin view?

Mel

**Comment by melmgcoe** [comment]
I can see there's a new version of the core components available to install. We'll get this installed tomorrow and report back on whether it resolves this issue.

**Comment by melmgcoe** [comment]
We installed the latest version of the core component solution and the model driven app sync template is still failing to discover all model driven apps in our default environment. Can you please get back to me ASAP.

Thanks

**Comment by manuelap-msft** [comment]
Hello,

Can you confirm the account running the Sync Flow has System Administrative access to the environment? 
Can you navigate to aka.ms/ppac > select the Default environment > Select Power Apps (under Resources) can can you confirm you can see all model driven apps you are expecting in that view?
Can you share the error message you are receiving?
The Admin | Sync Template v2 (Model Driven Apps) has error handling built in if the app maker has left the organisation and therefore can't be found in your directory any more, can you confirm the logic in the flow looks like this
![image](https://user-images.githubusercontent.com/55705669/85005277-782df800-b150-11ea-9399-677ba8afd4ac.png)

I also want to set expectations here in that the CoE Starter Kit represents sample implementations of admin features. Our customers and community can use and customize these features to implement admin and governance capabilities in their organizations. The Starter Kit is not officially supported, and there is no SLA for support issues.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/feedback-support

**Comment by melmgcoe** [comment]
Hi Manuela,

The sync flow runs under a service account and it has access to the SA access to the environment:
 
![Capture-SAPerms](https://user-images.githubusercontent.com/62425530/85276218-5e0a5780-b479-11ea-8c6d-1dc7200adb60.JPG)

I can see all the model driven apps in our default environment for the view you mentioned:
 
![Capture-ModelDrivenApps](https://user-images.githubusercontent.com/62425530/85276236-65316580-b479-11ea-8732-3726ceee7574.JPG)

Here’s what our flow looks like, it’s a bit different to what you showed me so could this be part of the issue?

![Capture-FlowLogic](https://user-images.githubusercontent.com/62425530/85276265-6e223700-b479-11ea-8245-ace872a090e1.JPG)

Here’s a copy of the error itself:

![Capture-FlowError](https://user-images.githubusercontent.com/62425530/85276373-97db5e00-b479-11ea-9fde-8fef8b743df3.JPG)

Thanks,

Mel

**Comment by JeneferM-MSFT** [comment]
Hi Mel. Yes that error is being caught in the newer version of the toolkit with the pieces shown in the screenshot by Manuela. It seems like your upgrade did not complete. 

When upgrading, in order to get all upgrades, you need to pick Import > Upgrade > Overwrite customizations.

**Comment by melmgcoe** [comment]
Hi Jenefer,

Thanks for the advice, I've chosen the option to overwrite customisations and the updated flow now looks correct.

Let me see what happens tonight when the flow runs. I'll come back to you with an update tomorrow morning.

Regards,

[cid:image007.png@01D64950.08477380]
[M&G Plc Logo]
[cid:image008.png@01D64950.08477380]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D64950.08477380]


[cid:image009.png@01D64950.08477380]
[cid:image009.png@01D64950.08477380]
[cid:image011.png@01D64950.08477380]

**Comment by melmgcoe** [comment]
Hi Jenefer,

The flow now runs correctly as expected but we still have the bigger issue of the flow not discovering all the model driven apps in our default environment.

This is what I see when the flow runs the discovery process:

![Capture1](https://user-images.githubusercontent.com/62425530/85542433-fdae1e00-b610-11ea-985b-24d8e32dfdf5.JPG)

I've attached an output of the capture:

![Capture1](https://user-images.githubusercontent.com/62425530/85542484-09014980-b611-11ea-8dfc-a06d39a4470d.JPG)

Let me know if you have any other suggestions. We have 15 model driven apps available in the default environment and only 4 apps showing in the view Manuela asked me to check.

**Comment by melmgcoe** [comment]
I'm attaching the output capture again, it didn't appear to come across:

[capture output.txt](https://github.com/microsoft/powerapps-tools/files/4824886/capture.output.txt)

**Comment by JeneferM-MSFT** [comment]
You are saying that there are 15 total model driven apps in default, and that the CDS is only capturing 4. Correct? 
Can you please validate that the apps are accessible? 
Navigate to aka.ms/ppac > select the Default environment > Select Power Apps (under Resources) > click the 3 dots and share
![image](https://user-images.githubusercontent.com/62659043/85552045-38e82700-b5e8-11ea-840a-55c9be7548c8.png)

Grab the URL in option 4 and see if you can browse to it.

**Comment by JeneferM-MSFT** [comment]
Can you also confirm from the Maker UX that the 
https://make.preview.powerapps.com/ > chose the default env > apps

Select one of the offending apps and hit the 3 dots. Do you see that edit is enabled but not play?
![image](https://user-images.githubusercontent.com/62659043/85560283-1f4add80-b5f0-11ea-8512-2aaea0d86da6.png)

And if you hit edit, do you see that the app is still in draft?

**Comment by melmgcoe** [comment]
I browsed to the URL for an affected app and see the following error:

![Capture](https://user-images.githubusercontent.com/62425530/85679684-8a181980-b6c1-11ea-9fe2-6718ecaa793a.JPG)

The app is also in draft mode. Does this mean all the affected apps need to be published before they can be picked up by the sync template?

**Comment by JeneferM-MSFT** [comment]
We are investigating if this is possible.

**Comment by melmgcoe** [comment]
Thanks, I'll wait to hear back from you on this point.

So just to confirm - the sync flow template can't pick up unpublished model driven apps by design as it currently stands. Does the same principle apply to the canvas apps sync template?

Regards,

[cid:image001.png@01D64BBB.36EC9450]
[M&G Plc Logo]
[cid:image008.png@01D64BBB.36EC9450]
Melvin Uy
Collaboration Technical Specialist
Workspace Collaboration O365
melvin.uy@uk.pgds.com <mailto:melvin.uy@uk.pgds.com>
t. 02039770030 (Internal: 60030)

10 Fenchurch Avenue
London EC3M 5AG
[cid:image009.png@01D64BBB.36EC9450]


[cid:image009.png@01D64BBB.36EC9450]
[cid:image009.png@01D64BBB.36EC9450]
[cid:image011.png@01D64BBB.36EC9450]

**Comment by JeneferM-MSFT** [comment]
No, canvas apps do not have the same limitation thanks to the way they are accessible within Power Automate. 
I am hoping to find a way to cover this and will get back to your here. 
Thanks for helping make CoE great!

**Comment by JeneferM-MSFT** [comment]
Hello. Unfortunately this isnt something we can easily fix. We have put an item on our backlog for tracking though. 
Thanks for using CoE!
