### ISSUE TITLE
[BUG]: Template Catalog doesn't display the content

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#313]
**Describe the bug**
Template Catalog App doesn't display the content with the Document library in place with the right permission.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Nurture
 - Version 1.44
 - App 

**To Reproduce**
1. Go to 'Power Apps - Apps section'
2. Click on 'Template Catalog" app
3.shows following message:
![image](https://user-images.githubusercontent.com/13658386/83409193-9813ab00-a431-11ea-86a0-59f24a259036.png)

while editing an app, formula in Homescreen shows following error, even though user is a global administrator:
![image](https://user-images.githubusercontent.com/13658386/83409269-b8436a00-a431-11ea-8dc9-f523c976c320.png)

**Expected behavior**
It should display the content to share as per the App expectation

Thanks and Regards,

**Comment by dips23** [comment]
Ohh. I assumed I did that already, but it was pending.

This is working now after updating the connector - sorry for this
interruption.

Please close this issue.

Kind Regards,

Dipti

**Comment by JeneferM-MSFT** [comment]
No problem, glad to help. Thanks for using CoE!
