### ISSUE TITLE
App Usage PowerBI Tab Contents are blank - No data shown from Audit Log

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#315]
**Describe the bug**
App Usage PowerBI Tab Contents are blank

**Component (please tell us which flow or app you are experiencing issues with):**
Center of Excellence Dashboard

**To Reproduce**
Lets synchronisation flows run overnight.

Load up advanced .pbix

click on refresh

**Expected behavior**
I expect to see some Apps Usage information.  CDS says there are 384 rows in the Apps Entity.  Apps Launched Trend pane is empty.
![CoENoAppsdata](https://user-images.githubusercontent.com/8484048/83428736-dd80aa00-a42a-11ea-859f-f4b345ae86d7.JPG)

I have tried this on two different tenants.

Apps tab has list of PowerApps and the number of unique users, Sessions and users shared columns filled in.

**Screenshots**

**Additional context**
The Office 365 Audit Logs custom connector when Tested brings back lots of results and a 200 response.

**Comment by JeneferM-MSFT** [comment]
Audit logs start tracking from the first run, they do not go back and find old launches. 
Can you validate that data exists in the audit logs table? 
![image](https://user-images.githubusercontent.com/62659043/83430342-5a3f6400-a3ea-11ea-934d-57de753c4f31.png)

The Audit Logs custom connector brings back all office logs, and then a flow filters out launches. So its possible that you dont have any launches returned.

**Comment by NPrice99** [comment]
Hi Jenefer

I will leave it a couple of days and see what happens.

Regards

Nigel

**Comment by NPrice99** [comment]
![powerbievidence](https://user-images.githubusercontent.com/8484048/83498766-3b0d0900-a4b4-11ea-9d5d-37c3074cc00a.jpg)
I think one of these filters is the wrong way round and might be why nothing is being displayed.

**Comment by NPrice99** [comment]
Latest update from @manuelap-msft to the advanced.pbix file has fixed this
