### ISSUE TITLE
COE Updates

### ISSUE THREAD

**Issue by leozak06** [microsoft/powerapps-tools#316]
Hi there, this is not a bug but an inquiry. I am just wondering when we update solutions in our COE, if the entities are affected in anyway. We are customizing the developer compliance center for one of our clients to implement admin and governance capabilities in their organization, and are required to add new fields to the form. We are trying to decide if we should create a new entity or modify the existing one. Please let us know. Thanks!

**Comment by JeneferM-MSFT** [comment]
This question is about the behavior of the underlying platform. You will need to explore the complexities of upgrade, here is a good starter: [How managed solutions merge](https://docs.microsoft.com/power-platform/alm/how-managed-solutions-merged). 

My expectation is that your changes would be fine and not be interrupted by upgrade, but my advice would be that you test this in a sample environment to be sure. 

Sorry that I cannot answer with more certainty.
