### ISSUE TITLE
Theme Editor - Download link points to the review tool

### ISSUE THREAD

**Issue by totalitarian** [microsoft/powerapps-tools#32]
Any chance of the correct link please

**Comment by iAmManCat** [comment]
I have it and the other tools stored on my personal site https://www.iammancat.dev/powerapps/ until they accept the PR I submitted.

**Comment by totalitarian** [comment]
Perfect, thanks!

**Comment by manuelap-msft** [comment]
The link is https://pahandsonlab.blob.core.windows.net/tools/ThemeEditor.zip and has been updated on the GitHub page as well.
