### ISSUE TITLE
[BUG]: PowerBI Dash board keeps loosing List of environments

### ISSUE THREAD

**Issue by tmcg19** [microsoft/powerapps-tools#320]
**Describe the bug**
when I run all core components and once complete I will refresh the data set again, with the first few loots at the total environments in th dash board all looks fine shows all 11 we have.
But after looking browsing through the other data, the environments seem to disappear and only the default is shown??
I check the filter and it seems to think environment Deleted is true for all my non default environments and will  not display in dashboard??

**Comment by tmcg19** [comment]
Just  comment and may not be caused the issue, one thing that did happen was the account lost the PowerAdmin Role for a few days due to Security approvals within the enterprise but this is corrected now, wondering by loosing this Role and the account might not of been able to see all environments would it marked previous seen environments as deleted... but I would of expected that once all access corrected that the flows should see all environments again and mark anything as active as active and not just keep as deleted??

**Comment by manuelap-msft** [comment]
Hello,

thanks for sharing that additional information, that was useful in helping me debug the issue! 

The Sync flow looks at Environments in your tenant that you have access to and compares them to environments the sync flow previously picked up and stored in the CoE Environment entity. The difference is marked as deleted. If your account lost access, it would have marked all environments you don't have access to as deleted.

It does look like, once an environment is marked as deleted, we don't "recover" from that status on the next run - i.e. we don't update the Deleted status.

I have tried fixing this and was wondering if you could help me test this?
Could you
1. In the solution, Turn Off the Admin | Sync Template v2 run (this is the one that marks environments as deleted)
2. Go to flow.microsoft.com > My Flows > Import the attached flow, and enable it. It is updating the same entities, so needs to be imported in the same environment you have the CoE Kit installed but doesn't need to be part of the solution to work. 

If you run that, does that then show your environments again?


[AdminSyncTemplatev2_20200603115110.zip](https://github.com/microsoft/powerapps-tools/files/4723039/AdminSyncTemplatev2_20200603115110.zip)

**Comment by tmcg19** [comment]
Hi 
This seems to brought back most of the environments but different view give different counts.
in the Overview - power apps tab, and in the overview page I get 8 total environments. where as in the Overview-  flow tab I get total environments of 11(maybe a cache or refresh issue). The actual number of environments is 11. the Power app over view seems to to not count or display the  other SYSTEM created environments, except for the DEFAULT environment, is this by design, and why?

**Comment by manuelap-msft** [comment]
If you open the Power BI Dashboard in Github, and hover over the Environments visual and select the Filter icon it will show you what filter is applied to that visual - it should only say Environment Deleted is false.
Each page has it's own filters that, when selected, apply to all visuals on the page so it's likely that the underlying data is now actually correct but you have just applied an additional filter to a page or visual.
![image](https://user-images.githubusercontent.com/55705669/83760484-e95bae80-a66c-11ea-8254-c55cc21d3b5b.png)

**Comment by tmcg19** [comment]
it looks to of been a refresh issue as all show same now, 8 environments, but not the 11 as expected, as 11 is the total number of environments in the admin portal. so looked at your flow and it seem to remove the 3 SYSTEM create environments as legacy. is this correct, and whats the decision behind doing this?

**Comment by manuelap-msft** [comment]
Are you on the latest version of the Core components solution, it should show up as 1.45?

**Comment by tmcg19** [comment]
All 11 were showing up, before I had this issue

**Comment by tmcg19** [comment]
I'm using the version I last downloaded and got fully working, which was downloaded on May6th. CenterofExcellenceCoreComponents_1_44_managed

**Comment by manuelap-msft** [comment]
We had a bug with Legacy environments, which was fixed on May 13. See latest updates https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit#latest-update

The Flow I send you above will include that update, but it doesn't "recover" Legacy environments marked as delete. Please update them manually for now, and the next Sync Flow should then not mark them as deleted anymore. 

Let me know if you need step by step instructions on how to mark them as not deleted.

**Comment by tmcg19** [comment]
can you help where I manually correct?

**Comment by manuelap-msft** [comment]
Of course

1. Navigate to make.powerapps.com
2. Select Solutions and open the Center of Excellence - Core Solution
3. Select the "Environment" entity
4. Select the Data tab and click Edit data in Excel in the top navigation
![image](https://user-images.githubusercontent.com/55705669/83879936-59823700-a736-11ea-8a44-3ed1ef0374bf.png)
5. This will download an Excel file, you might have to install the PowerApps Office add-in if not already done so. Follow the steps when prompted as you open the Excel
6. Find the Environments that you want to un-delete and set the Environment Deleted column to No for those. 
![image](https://user-images.githubusercontent.com/55705669/83880157-a9f99480-a736-11ea-9248-23ac0ad2fc87.png)
7. On the right hand side as part of the PowerApps Office plugin, select Publish to publish your changes
![image](https://user-images.githubusercontent.com/55705669/83880232-c09feb80-a736-11ea-8443-968f2d2bed96.png)

**Comment by tmcg19** [comment]
our admin control and have blocked add-ins, is there any other way to edit this?

**Comment by tmcg19** [comment]
would deleting the environments marked as deleted "YES", and then run the sync v2 flow that you sent again would that add these environments back in to the list and correct the issue?

**Comment by manuelap-msft** [comment]
Yes, actually that should work!

**Comment by tmcg19** [comment]
deleted the the entries and the ran sync v2 flow, and then pulled the data again in PowerBI, refreshed dashboard and looks OK now. 
Question for future work do I use the the flow you attached, or do I download that one from the COE github. or do I need to download all components again and update all

**Comment by manuelap-msft** [comment]
That's awesome, thanks for confirming!

For now, please use the Sync flow that I attached outside of the solution as that includes the bug fixes for recovering Environments from deleted state if access is lost. 

We have incorporated those changes in our local development environment now, and they will be included with the next release of the CoE Kit. The next time you upgrade, you can disable the sync flow I send you and download&update the components from GitHub.

Thank you for using the CoE Starter Kit!
