### ISSUE TITLE
[BUG]: Cannot Import CenterofExcellenceAuditComponents_1_17_managed.zip

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#323]
**Describe the bug**
![image](https://user-images.githubusercontent.com/8484048/83866070-23858880-a71f-11ea-9f84-eb88d2c15ece.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: governance components
 - Version [1.17]
 - App or Flow - Package

**To Reproduce**
1.Follow the instructions detailed under Set up core components.

2.Import the CenterOfExcellenceAuditComponents_x_x_x_xx_managed.zip file.

**Expected behavior**
The package to be imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/83866288-7f501180-a71f-11ea-97d8-7c60f4ee7d2d.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

just based on the screenshots it looks like you are in the App Import experience, and not the solution import experience.

Can you try
1. Navigate to make.powerapps.com
2. Select Solutions on the left hand side in the navigation
3. Select Import from there

It should look like this
![image](https://user-images.githubusercontent.com/55705669/83866545-de158b00-a71f-11ea-8001-014c91400d38.png)

**Comment by NPrice99** [comment]
Hi Manuela

I did that and got a couple of warnings 

![image](https://user-images.githubusercontent.com/8484048/83868231-7280ed00-a722-11ea-937a-a806d433d4ec.png)

and this in the log : Flow client error returned with status code "BadRequest" and details "{"error":{"code":"FlowMissingConnection","message":"The flow is missing a connection for api 'shared_commondataservice'. Reauthenticate the connection or remove from the flow and re-save."}}".

I assume I can fix most of these 

REgards

Nigel

**Comment by manuelap-msft** [comment]
Hello,

yes, those will be fixed when you authenticate the connections and configure the flows. The warnings are nothing to worry about, if the import succeeded.

Best Regards,
Manuela

**Comment by NPrice99** [comment]
Thanks Manuela
