### ISSUE TITLE
[BUG]: CenterofExcellenceAuditComponents_1_17_managed.zip asks for value of  Developer Compliance Center URL not Archive Site (URL) Environment Variable.

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#325]
**Describe the bug**
CenterofExcellenceAuditComponents_1_17_managed.zip asks for value of  Developer Compliance Center URL not Archive Site (URL) Environment Variable.

**Component (please tell us which flow or app you are experiencing issues with):**
CenterofExcellenceAuditComponents
Version 1.17
 - Environment Variable

**To Reproduce**
1. Import CenterofExcellenceAuditComponents_1_17_managed.zip
2. Create the site 
3. click on "See Environment Variable" 

**Expected behavior**
I expect to see Archive Site URL not Developer Compliance Center URL

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/83870464-394a7c00-a726-11ea-9f32-5c459883683e.png)

**Additional context**

**Additional context**

**Comment by NPrice99** [comment]
I think this may well be a documentation issue - The missing Environment variable is probably setup later - It appears as Developer Compliance Center environmental variable is blank whilst the Archive Site URL is present so does not appear when you so to solutions.  The one we needed (Archive Site URL) is accessed using the "Update Environmental Variable" section.

**Comment by JeneferM-MSFT** [comment]
Can you confirm that you got to your list of Env Vars by clicking on something that looks like this:
![image](https://user-images.githubusercontent.com/62659043/83880591-3b93e280-a6f4-11ea-92d4-af4d17407896.png)

If so, you are only seeing the ones that didnt have a default value already filled. To view all environment variables in the environment, open the default solution for the environment, and set the Type filter to Environment variable.

**Comment by NPrice99** [comment]
Hi Jenefer

The PowerApps UI has moved on since the CoE was documented. You now have to click on the down arrow head next to “All” in the top right hand corner of the Solutions screen, followed by Environment variable.


[cid:image003.jpg@01D63B45.57ADD2C0]

Then you get this screen :-


[cid:image004.jpg@01D63B45.57ADD2C0]

Where you can edit the environment variables.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
Hi Nigel, your screen shots did not come through, are you not writing in the GitHub UX, I think they wont share.

**Comment by NPrice99** [comment]
Hi Jenefer

In was just responding to your email.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
I see. I'm talking you in GitHub. Technology is fun :) 

Can you confirm you are not blocked here? You are able to see the env variables you need?

**Comment by NPrice99** [comment]
Hi Jenefer

Yes I can see all of the variables.

Sorry for not getting back to you I have been in meetings.

Regards

Nigel

**Comment by NPrice99** [comment]
Hi Jenefer

The PowerApps UI has moved on since the CoE was documented. You now have to click on the down arrow head next to “All” in the top right hand corner of the Solutions screen, followed by Environment variable.

 https://user-images.githubusercontent.com/62659043/83880591-3b93e280-a6f4-11ea-92d4-af4d17407896.png

Then you get this screen :-

![compliant and Report Components](https://user-images.githubusercontent.com/8484048/83895700-fbac1a00-a74a-11ea-890c-1bca8ba34a11.jpg)

 

Where you can edit the environment variables.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
There are actually two entry points to the Env Vars, so glad you were able to find it. And glad you are unblocked. 
Thanks for using CoE!
