### ISSUE TITLE
[BUG]: CenterofExcellenceCoreComponents_1_45_managed.zip fails with environment for linked resource could not be found

### ISSUE THREAD

**Issue by fs366e2spm** [microsoft/powerapps-tools#334]
**Describe the bug**
Installation of "CenterofExcellenceCoreComponents_1_45_managed.zip" following the steps here
[https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components) fails (after 89.08%) with this general Component error message:
_CanvasApp   import: FAILURE: One or more errors occurred._

and this detailed error message:
An error has occurred. Try this action again. If the problem continues, check the Microsoft Dynamics 365 Community for solutions or contact your organization's Microsoft Dynamics 365 Administrator. Finally, you can contact Microsoft Support. : System.AggregateException: One or more errors occurred. ---> Microsoft.Crm.CrmException: Code: ServiceToServiceEnvironmentNotFound Message: The environment for linked resource 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found in the tenant 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'. Client Request Id: .    at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)    at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<GetPowerAppsResourceStorageContainer>d__17.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)    at Microsoft.Crm.Tools.ImportExportPublish.ImportCanvasAppHandler.ImportItem() ---> (Inner Exception #0) Microsoft.Crm.CrmException: Code: ServiceToServiceEnvironmentNotFound Message: The environment for linked resource 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found in the tenant 'yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy'. Client Request Id: .    at Microsoft.Crm.ObjectModel.PowerAppsValidation.PowerAppsServiceResult[T](ResourceResult`1 powerAppsServiceResult)    at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<GetPowerAppsResourceStorageContainer>d__17.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)    at Microsoft.Crm.Tools.Core.ImportExportPublish.ImportCanvasAppHandlerInternal.<ImportAppToPowerAppsService>d__14.MoveNext()<--- 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [CoEStarterKit, CenterofExcellenceCoreComponents_1_45_managed.zip]
 - Version [1.45]
 - App or Flow [CenterofExcellenceCoreComponents_1_45_managed.zip, CenterofExcellenceCoreComponents, CanvasApp]

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components'
2. Create environment
3. Import CenterofExcellenceCoreComponents_1_45_managed.zip

**Expected behavior**
Success message, import of components without error

**Screenshots**
-

**Additional context**
-

**Comment by JeneferM-MSFT** [comment]
Can you confirm, was this a new setup of the CoE? Or an upgrade of an existing CoE?
Did you create the CoE environment to include a CDS instance? (Select Yes for creating the database)

**Comment by fs366e2spm** [comment]
Hi @JeneferM-MSFT 
Yes, that was a complete new (first time) setup of CoE and yes, also a new environment with option enabled to created a CDS database.
![1_CoE_environment_creation_with_database](https://user-images.githubusercontent.com/52791126/84052318-b1c46d80-a9b0-11ea-909f-7f2dd7d9c019.png)
![2_CoE_environment_creation_with_database](https://user-images.githubusercontent.com/52791126/84052327-b426c780-a9b0-11ea-8d82-aa5aaab32bc0.png)

**Comment by JeneferM-MSFT** [comment]
I have just confirmed that the import is working successfully so there isn't anything wrong with the package itself. Can you please confirm that you have you everything needed from the [prerequisites list](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) and try to import again?

**Comment by fs366e2spm** [comment]
Checked the prerequisites, do you see something missing? The only point I see is, that we don't have Dynamics but that should not be the problem I guess.

Prerequisites
The following are prerequisites for installing the CoE Starter Kit as it's included in the solution.

- [x] Admin account: => global admin
   
  - [x]  - Microsoft Power Platform service admin, **global tenant admin**, or Dynamics 365 service admin for access to all tenant resources through the Power Apps APIs.
  - [x] This solution will work for environment admins, but the view will be restricted to only the environments an environment admin has access to. => environment admin configured for my user via security group
  - [ ] **_Dynamics 365 service admin is required for getting details about model-driven apps and solution-aware flows._ => No, no we don't have Dynamics, dynamics licenses** 

- [x]  - Power Apps Premium license (per app, **per user**, or Dynamics 365 Online licenses) is required for using Common Data Service. => Power Apps Plan 2 license / per user license assigned

- [x] Environment with a Common Data Service instance, where the user installing the solution has the System Administrator security role. => yes, new environment with CDS created for CoE

- [x] The environment must have a DLP policy that allows Common Data Service, Common Data Service (current environment), Office 365 Users, Power Platform for Admins, Power Automate Management, Office 365 Outlook, Power Apps for Admins, Power Apps for Makers, SharePoint and HTTP to be used together. Those connectors must be in the business data–only bucket of the DLP policy for this environment. => no DLP created for the new environment and existing DLPs are environment specific and not impacting the new CoE environment

- [x] If there are multiple DLP policies applying to the same environment, either all of them have to have the connectors the CoE Starter Kit uses in business data only or if you have a policy that applies to all environments that you don't want to change you could exclude the CoE environment from that. => no DLP for the CoE environment defined
Learn more about DLP Policy Scope.

- [x] Download of the Center of Excellence Solution and CoE Power BI dashboard files to your device. The entire content package can be downloaded directly at aka.ms/CoEStarterKitDownload. => yes, downloaded from there

- [x] Both the Governance Components and Nurture Components solutions require the core solution before they can be installed. => Installing core solution fails already

These are the requirements for using the solution.
- [x] Power Apps Premium license (per app, **per user**, or Dynamics 365 Online licenses). => per user

- [x] For the Core Components solution, only the admins need a Power Apps Premium license. For the Governance Components solution, all makers require a Premium license. For the Nurture Components solution, everyone will require a Premium license. => Power Apps Premium, per user license assigned

**Comment by JeneferM-MSFT** [comment]
A DLP may be applied to your environment assuming an org wide DLP is in place, though that should not impact import. 
Did you try the import a second time?

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid you will need to create a support ticket here. We have validated that the package is in working order with the product.
