### ISSUE TITLE
[BUG]: issue title Developer Compliance Centre - clicking on the App Settings results in Hmmm Can't reach this page

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#335]
**Describe the bug**
If you go into the Developer Compliance Centre, click on an App, get App Overview Screen displayed.  Click on App Settings and get error Hmmmm. can't reach this page.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App Developer Compliance Centre

**To Reproduce**
1. Start Developer Compliance Centre
2. Click on 'a App'
3. get App Overview screen
4. Click on"App Settings" at top of the screen.
5. Get error Hmmm   cant reach this page.

**Expected behavior**
I expected to get to the Apps Settings page.

**Screenshots**

**Additional context**
Found errors in the Developer Compliance Centre OnStart - The app reads the CDS entity "COE Settings".  THis doe not include 'Maker URL' and 'App Player URL' so that in lblOption the variable vPowerAppsMakerURL is unassigned.
<img width="890" alt="developercompliance centreerror1" src="https://user-images.githubusercontent.com/8484048/84019870-cdf8e800-a979-11ea-8c43-a04107d05416.PNG">

**Comment by NPrice99** [comment]
Hi

The above results in the following URL which is invalid :-

![invalidurl](https://user-images.githubusercontent.com/8484048/84024503-e8cf5a80-a981-11ea-8c07-17758e45aea7.png)


Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
There is a new setting in the CoE Settings table, which defaults to Commercial in the event that you do not fill it. When you last updated the Compliance solution, did you also update the Core solution? It would have  included the new field.

**Comment by NPrice99** [comment]
Its a bit better :-  https://make.powerapps.com/environments//apps/fd41c8bf-6f90-ea11-a811-000d3a38a57d/details

**Comment by JeneferM-MSFT** [comment]
Sorry I'm not following you. What state are you in now? Do you have the new field in CoE settings now?

**Comment by NPrice99** [comment]
Hi Jenefer - the new setting has fixed one problem but cased another one.  ie make.powerapps.com is now there (the fix you mentioned), but the environment ID has disappeared.

Regards

Nigel

**Comment by NPrice99** [comment]
ie the variable canvasApp (.properties.environment.name) is blank. (AppDetailScreen -> galAppOptions -> lblOption -> OnSelect)

**Comment by JeneferM-MSFT** [comment]
Did you enter the details screen without selecting an app on the home screen?
The variable in question is set when you select an app from the home screen:
Set(vSelectedApp, LookUp('PowerApps Apps', App = ThisItem.App));

**Comment by NPrice99** [comment]
vSelectedApp has a value, canvasApp does not. 
vSelectedApp.App has the correct GUID. 
But PowerAppsforAppMakers.GetApp(vSelectedApp.App) is returning blank.

**Comment by JeneferM-MSFT** [comment]
Ah I see. Do you have permissions to the app? That call only works if you have permissions to the app.

**Comment by NPrice99** [comment]
Developer Compliance Centre ? - I can run it, I can edit it.

The connector is in my DLP as "Business".  I have taken the environment out of the Policy and get same result.

**Comment by JeneferM-MSFT** [comment]
I am asking about permissions on the selected app, not on this compliane center tool 
You have selected an app (the vSelectedApp), do you have permission to it?

**Comment by NPrice99** [comment]
Yes I am the owner of the selected app.
One thing I have noticed is the app I have selected is a Model Driven App.  The title for the Gallery on the Home page is "Canvas Apps" could that be a problem ?

**Comment by JeneferM-MSFT** [comment]
Correct, those links only work for Canvas Apps.

**Comment by JeneferM-MSFT** [comment]
Alright I have added a filter so that only Canvas apps will show with the next download until we can do a more thorough we-work of this app. 
Thanks for helping make CoE great!

**Comment by JeneferM-MSFT** [comment]
New version of the CoE and this app available now. 
Thanks for using CoE!
