### ISSUE TITLE
[BUG]: Admin | App Archive and Clean Up - Start Approval - Approve or Reject

### ISSUE THREAD

**Issue by Daleyon** [microsoft/powerapps-tools#336]
Not an issue, only a question regarding Entity role access.

Regarding the Accept or Reject Approval Notification via Flow and via Outlook - 
"Please confirm this app can be archived by approving this task; or provide a business justification if you reject",
which entity does a User need access to? Is it the Archive Approval Entity?

Currently, users are receiving error message 'Encountered a general permissions error trying to access the CDS database. This could be caused by modification of the approvals administrator or user roles, or by an incompatible plugin'.
I tested with my System Admin role and received the same error for a SharePoint Form and a standalone Power App.

**Comment by JeneferM-MSFT** [comment]
Can you confirm, did this work for you in the past or are you new to this functionality? 
If it used to work, have you recently switched to using Security Groups to manage the environments?

**Comment by Daleyon** [comment]
@JeneferM-MSFT new to this functionality Admin | App Archive and Clean Up - Start Approval.

I am very familiar with the Security Groups / Security Roles process.
Normally, if facing this scenario, I would assign the Common Data Service user and Approvals User Roles... All would be good.
However, even with my Power Platform Admin role + Security Admin role, I am unable to approve or reject my own.

**Comment by JeneferM-MSFT** [comment]
You are correct, the permission needed is the Approval User Security Role. 

We haven't seen this specific error before for customers, 
Can you please let me know:
1) Are you able to use approvals in this environment outside of the context of the CoE? IE, just create a dummy flow that sends an approval
2) Are you using a security group on this environment?
![image](https://user-images.githubusercontent.com/62659043/84052598-a730b680-a965-11ea-87e5-695605519259.png)

**Comment by Daleyon** [comment]
@JeneferM-MSFT 
1. Yes, I am able to conduct full functionality of Approvals outside of the CoE context.

2. Yes, on the CoE Environment I have an AAD security group. All affected users are members of the group.

Is there something in the CoE managed solutions that causes a negative affect when a user has multiple security roles that "conflict"?
Example: Power Platform User SR + Approval User Security Role.
Power Platform US SR (this is from an earlier release version of the CoE Kit) does not allow Approvals.
Approval Security Role does allow.

**Comment by JeneferM-MSFT** [comment]
For #1, not sure if I was clear in my question: Are you able to do approvals **_in this environment_**, other than the ones created by this flow?

**Comment by Daleyon** [comment]
Yes. I am able to do approvals in this environment.

Sent from Outlook<https://aka.ms/qtex0l> mobile app for iOS

Kind regards / Mit freundlichen Grüßen
Dale Yon
________________________________

**Comment by JeneferM-MSFT** [comment]
that is odd. We arent doing anything special here. I wonder if your connection is just messed up. 
Can you please go and delete and re-create the Approvals connection? 

Go in here to delete it, and then re-create the approvals connection in the flow.
![image](https://user-images.githubusercontent.com/62659043/84083483-8e8cc480-a996-11ea-9070-6996049d296f.png)

Run the flow after doing this, and validate that new entries are being created in the **_Approval_** entity.
See if approving works now that we've cleared the connector, and if not try to approve through the flow ux

**Comment by Daleyon** [comment]
@JeneferM-MSFT before I delete and re-create.
I noticed the main error being related to 'missing prvReadAsyncOperation privilege'. I know that error is related to Read access on the System Job Entity. Which to be honest made no sense, because the Approvals User Security Role has that value accomplished by default.
So I started comparing CoE Environment Security Roles vs Default Environment Security Roles.

The screenshots are of the Approvals User Security Group:
CoE Environment (Left Side of Image) vs Default Environment (Right Side of Image).
As you can see, there is a major difference. 

Will following your instructions resolve the differences automatically?

![image](https://user-images.githubusercontent.com/17080282/84124050-ae5cd080-aa08-11ea-8326-3d66f12a566f.png)

![image](https://user-images.githubusercontent.com/17080282/84124079-b9affc00-aa08-11ea-9687-a6e4366e9ef9.png)

**Comment by manuelap-msft** [comment]
Hello,

the Approvals Users is a Security Role that's automatically created and not shipped with the CoE Starter Kit. If there's any issues with how it is populated out of the box, please raise a Service Ticket and Support can log this as an issue accordingly.

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE and posting this. The product team made some shifts which require we make some changes too. 
Can you please see if the attached resolves this for you? 
[CenterofExcellenceAuditComponents_1_19_managed.zip](https://github.com/microsoft/powerapps-tools/files/5066170/CenterofExcellenceAuditComponents_1_19_managed.zip)

**Comment by JeneferM-MSFT** [comment]
Sorry someone had added components to the solution I was unaware of. Try this instead. 
[CenterofExcellenceAuditComponents_1_20_managed.zip](https://github.com/microsoft/powerapps-tools/files/5066425/CenterofExcellenceAuditComponents_1_20_managed.zip)

**Comment by Russel-Thomas** [comment]
Have also picked this up and just updated latest managed components to try and address it (latest component version level is higher that solution component posted above) - weird thing is, creating a normal approval outside of the CoE solution (in same environment) as a user (not admin) - creating the flow works, sending the approval works, but responding to the approval fails with this general permission error...seems odd that the user can create the approval, but not approve it themselves.  Tried deleting and recreating connections for both admin (requestor) and user (responder) - same result.
if the approval is run out of the governance environment, then all users in the org need to be able to respond to the approval request - presumably this should happen by default, I didn't notice any chances to security config requirements in the setup?

**Comment by JeneferM-MSFT** [comment]
when you updated to the newer version of CoE, did you chose to overwrite? You will also need to turn off old versions of the check flows if you have any separate. 

Basically all the triggers need to now look like this:
![image](https://user-images.githubusercontent.com/62659043/90442804-13c7e000-e090-11ea-911c-0cd9b25e499c.png)


If you have any flows with a trigger based on changes to the Approval Responses table, then your approvals wont work now.

**Comment by Russel-Thomas** [comment]
Perfect, thanks Jenefer, all working now
