### ISSUE TITLE
[BUG]: CoE Core Components Import solution error

### ISSUE THREAD

**Issue by samrutur** [microsoft/powerapps-tools#337]
**Describe the bug**
When the CoE Core Components solution is imported, it gives me the error below. You do not have permission to access 1 records.

![image](https://user-images.githubusercontent.com/19577299/84063284-d3acf880-a98e-11ea-829e-0940addc35be.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture] Core
 - Version [e.g. 1.29] 1.45
 - App or Flow

**To Reproduce**
1. Go to 'Solutions' in PowerAPps portal
2. Click on 'Import' 
3. Upload the Core components solutions and click 'Next'.

**Expected behavior**
I would have expected to have the import to be successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/19577299/84063513-25ee1980-a98f-11ea-83c4-85af7d89cbbe.png)

**Additional context**
The environment I am  importing is non-default, production, with database created, no sample apps and in US region. I am a Power Platform admin with per app user license with no DLP policy applicable to this environment. I am not a tenant global admin but a Power Platform admin.

Thank you,
Sreeni

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid you will need to create a support ticket here. We have validated that the package is in working order with the product.

**Comment by samrutur** [comment]
Thank you! Can you let me know if the account that is importing the solution has to be tenant global admin?

**Comment by JeneferM-MSFT** [comment]
Nope, to setup the CoE you can use a Microsoft Power Platform service admin, global tenant admin, or Dynamics 365 service admin for access to all tenant resources through the Power Apps APIs.

**Comment by samrutur** [comment]
Thank you! When you say support ticket, do you mean support ticket from the Power Platform Admin Center or a different channel?
