### ISSUE TITLE
Building Power App

### ISSUE THREAD

**Issue by wesredman** [microsoft/powerapps-tools#338]
When creating the power app following the directions, it tells me the following:

![image](https://user-images.githubusercontent.com/66689306/84172092-948fad80-aa49-11ea-89e4-38c2e95a0e10.png)

Is it me or my permissions?

**Comment by manuelap-msft** [comment]
You will need to configure what shows up in the app using the Admin App, it's explained here https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#create-initial-content-for-the-app
