### ISSUE TITLE
[BUG]: Emergency Response App, All Entries are not going through to the system

### ISSUE THREAD

**Issue by JuliaPerera** [microsoft/powerapps-tools#339]
**Describe the bug**
Users (2 thus far) are finding that after submitting entries front the front end of the app, some entries are not going through as inventory numbers for a few items are not changed. Checking the admin side of the app we noticed the inventory numbers which remained unchanged after the submission do not appear as entries in the back end (no records). Submitting the item updates one at a time works however, this is not efficient.

**To Reproduce**
1. Open the Supplies Reporting Tool and select a specific region
![image](https://user-images.githubusercontent.com/65044743/84275000-88195c80-aafe-11ea-8344-27ee3189ab56.png)
2. Enter new consumption and received values, press submit
![image](https://user-images.githubusercontent.com/65044743/84275119-ad0dcf80-aafe-11ea-97cb-8c07715a1b42.png)
3. Check the admin side of the app for all entry records
![image](https://user-images.githubusercontent.com/65044743/84275386-ff4ef080-aafe-11ea-9e64-a9af68319539.png)
4. See error, only one item's update has been logged for June 10th, 2020

**Expected behavior**
All items which were updated should appear as records in the back end.

**Interface(please complete the following information):**
 - Browsers Tested: Chrome (V 81), Microsoft Edge (V 42), Internet Explorer (V 11)
- Devices Used: Toshiba Tecra Z40-A

**Additional context**
So far, two users are experiencing this issue. The first one had this issue occur a month ago and using a private browser/clearing browser cache helped. Just recently the bug returned once again for this individual and around the same time, another user also reported having a similar issue. Using a private browser/clearing cache did not work at all for this second user. User 1 has a system user role, user 2 has a system admin role.

**Comment by zubinalex** [comment]
This is not reproducible in our environment. Btw we have released a new version of this app, feel free to try this.

**Comment by narpad** [comment]
Closing based on above comment
