### ISSUE TITLE
Admin | Sync Template v2 (Apps) not correctly handling abandoned apps

### ISSUE THREAD

**Issue by stmccartney** [microsoft/powerapps-tools#34]
If Try -> Apply to each app -> Get powerapp maker profile fails then even though Upsert App record (abandoned app) catches the failure, Apply to each app still shows failed.  This means the flow fails overall even though it's actually behaving nominally.

Setting "list Existing Apps" to run after "has failed" as well as "is successful" resolves this, but then if the Upsert App record (abandoned app) step failed this would not cause the overall flow to fail as it should.

I think the better way to resolve this would be to add another action within "Apply to each app" that runs if either "Upsert app record (abandoned app)" or "check if connection references are not null" is successful.

**Comment by manuelap-msft** [comment]
We have worked hard on improving the Sync Template Flows, and this should be corrected now with the latest version. Closing the issue, but please let me know if you experience any issues.
