### ISSUE TITLE
[BUG]: issue title PowerPlatform Admin View Approval Step - Business Justification Not Recognised

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#343]
**Describe the bug**
When in The PowerPLatform Admin View and trying to Approve a PowerApp is compliant the first step says the Business Justification is not filled in when it is (see screenshot)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Compliant
 - Version [e.g. 1.29]
 - PowerApp Admin View 

**To Reproduce**
1. Go to 'PowerApp Admin View 
2. Click on  PowerApps App Approval -> Validate Business Requirements 
3. Note drop down says Maker Provided Business Requirements -> No 
4, Click on Audit Tab and see that Business Requirements have been provided.

**Expected behavior**

**Screenshots**
![POwerApps Admin View](https://user-images.githubusercontent.com/8484048/84364585-2d4c3780-abc8-11ea-94f2-6f947a73c2a6.png)

**Additional context**
CenterofExcellenceAuditComponents_1_17_managed

**Comment by manuelap-msft** [comment]
This step validates Business Requirements, and not just the Business Justification. It therefore requires the Business Justification, Dependencies and Access Management to be filled out.

There is a field called Maker Submitted Requirements on the PowerApps app entity, that is a calculated field and set to yes when all those three contain data:
![image](https://user-images.githubusercontent.com/55705669/84375761-f3832d00-abd7-11ea-9421-d3e26972babb.png)

Here's what it should look like: 
![image](https://user-images.githubusercontent.com/55705669/84375690-db131280-abd7-11ea-9714-73265c23b86b.png)

**Comment by manuelap-msft** [comment]
(We do have an existing ask in our backlog to make the documentation here better https://github.com/microsoft/powerapps-tools/issues/210)

**Comment by NPrice99** [comment]
Thanks Manuela – That works
