### ISSUE TITLE
[BUG]: Sync Audit Log child rate limit exceeded

### ISSUE THREAD

**Issue by rsch136** [microsoft/powerapps-tools#346]
**Describe the bug**
Hello,

Due to the size of our tenant, we have set the time interval in the parent flow to 10 Minutes. This presumably causes the child flow to run into the "rate limit exceeded" error.

**Component (please tell us which flow or app you are experiencing issues with):**
 - CoE - Audit Logs
 - Version 1.0.0.7
 - Sync Adit Logs (parent and child)

**Screenshots**
![image](https://user-images.githubusercontent.com/44471683/84986780-68f27e80-b13f-11ea-9cd8-356340a806c5.png)

![image](https://user-images.githubusercontent.com/44471683/84986795-6e4fc900-b13f-11ea-87a9-6c2741ce295d.png)

**Comment by JeneferM-MSFT** [comment]
Thanks for posting, I believe we have an internal repro and will investigate.

**Comment by manuelap-msft** [comment]
Would you be able to make the following change to the [Child] Admin | Sync Logs flow and letting me know if that eliminates the throttling. We have seen good results with another customer and want to test further before releasing it into production. 

- Add a Filter array step to filter down the messages where an action is needed and only feeding these actions into the Switch action. Do so by selecting + Add Step > Filter > set the from to "Body" from Parse JSON and set the Filter to _@or(equals(item()?['Operation'], 'LaunchPowerApp'), equals(item()?['Operation'], 'DeletePowerApp'), equals(item()?['Operation'], 'DeleteFlow'))_ and then changing the input for the Switch statement to that of the Filter.
![image](https://user-images.githubusercontent.com/55705669/86228171-f8f3e780-bb85-11ea-9392-d61953aaf145.png)
- Decreased the concurrent number of sessions for the Apply to each cluster action by clicking on the ... next to Apply to each cluster > Settings > Reduce the Degree of Parallelism by using the slider. The default value is 50; we suggest gradually lowering the number.

It would be great if you could test these steps, and let us know if the flow then runs successfully!

**Comment by rsch136** [comment]
Hi @manuelap-msft ,
I noticed that in the version we currently have installed, we do not have a switch. I have been dreading updating the solution because according to [this](https://github.com/microsoft/powerapps-tools/issues/295#issuecomment-632732923) github issue we would have to set up the custom connector again.

**Comment by manuelap-msft** [comment]
Hello,

I have attached here the latest version of the Audit Log solution, which includes the above changes and latest updates so you won't have to do them yourself. This will require you to upgrade your existing solution - you will have to reconfigure the Custom Connector but you can use the same App Registration that you have used previously, so there's no need to set this up again. 
[CenterofExcellenceAuditLogs_1_0_0_16_managed.zip](https://github.com/microsoft/powerapps-tools/files/4864764/CenterofExcellenceAuditLogs_1_0_0_16_managed.zip)

**Comment by JeneferM-MSFT** [comment]
New version of the audit log is now available with the fix provided for Manuela here. Please reach out if you have additional issues. 

Thanks for using CoE
