### ISSUE TITLE
Question to "Admin | App Archive and Clean Up - Start Approval"

### ISSUE THREAD

**Issue by baxist** [microsoft/powerapps-tools#348]
**Describe the bug**
It's a question not a bug.
I've created an environment for the CoE and added an Security Group. In this Security Group are only myself and other admins.
But the names Approval flow runs into this error, because most of the users don't belong to this Security Group? Must the end users have access to the CoE environment? That makes no sense for me. But it seems that it is not possible to create an Approval for the CoE environment, if the end user has no rights for the CoE environment.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Center of Excellence - Compliance and Report Components
 - Version 1.9
 - Admin | App Archive and Clean Up - Start Approval

**To Reproduce**
Flow Run in step: Create approval.
Output Body:
```
{
  "error": {
    "code": "XrmApplyUserNotMemberOfSecurityGroup",
    "message": "Could not create a CDS system record representing user 'XXXXXXXXXXXXX'. Please ask a database administrator to add the user to the authorized security group."
  }
}
```

**Comment by JeneferM-MSFT** [comment]
Thanks for the issue, we have been tracking this issue internally but in the meantime we suggest you not use security groups to secure the CoE environment.

**Comment by baxist** [comment]
Thanks for your feedback.
Just to insure that we have no missunderstanding: 
I followed the step 3d in [https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-the-solution]( https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-the-solution):

"3. Create an environment in which to set up the CoE.
[...]
    d. Leave sample apps and data set to No, and then **select a security group** who can view this environment. Then select Save. [...]"

**Comment by JeneferM-MSFT** [comment]
Thanks for pointing out that we have that in the documentation! We will remove until the issue is resolved. Expect to see that change in the next release of the documentation.

Thanks for helping to make CoE great!

**Comment by baxist** [comment]
If i delete the security group, everybody in my organization will have access to the CoE environment. How can I handle this? They should be only able to answer approval requests. Nothing more.

**Comment by JeneferM-MSFT** [comment]
On an environment without an associated Security Group, users that receive an approval are automatically added to the "Approvals User" Security Role - there is no action on the admin to allow these users to use Approvals.

**Comment by baxist** [comment]
If I don't secure the environment with a Security Group, all users have access to the environment. But I don't really want that the users create anything in this CoE environment. How can I handle this?
(sorry forthis is basic questions)

**Comment by JeneferM-MSFT** [comment]
You can secure environments to users. Please go read about how to do this in the [CDS Security Model](https://docs.microsoft.com/powerapps/developer/common-data-service/security-model) documentation, or in this more targeted document, [Add Users to Environments](https://docs.microsoft.com/power-platform/admin/add-users-to-environment).

**Comment by baxist** [comment]
Ok, got it.
Thank you very much!

**Comment by JeneferM-MSFT** [comment]
Glad to help, thanks for using the CoE!
