### ISSUE TITLE
[BUG]: Audit Log via O365 Manamagent API - different seruity screen as in documentation

### ISSUE THREAD

**Issue by baxist** [microsoft/powerapps-tools#349]
**Describe the bug**
If I setup the Custom Connector I have other fields to fill out as discribed in the documentation.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence Audit Logs
 - Version 1.32
 - Flow with Azure App ID registration

**To Reproduce**
Follow the steps in:
[](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration )
API-Permission in Azure is granted.
And I have saved the Secret ClientKey, the Client Key and the Tenant ID.

But in the Security Tab in the custom connector setup I don't have these fields:
• Login URL
• Tenant ID
• Resource URL

But i have these fields:
• Authorization URL
• Token URL
• Refresh URL
 
![Security](https://user-images.githubusercontent.com/67257572/85273176-901db880-b47d-11ea-873b-dbc69faa5d7a.jpg)

How must I fill out these fields?

**Comment by JeneferM-MSFT** [comment]
Are you installing via option 1 or option 2?
 
If [option 1](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-1-connect-to-the-audit-log-by-using-basic-authentication), please note:
(Step 5) Select Create Connector. You don't need to change the Security and Definition information.

If [option 2](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration), please note:
(Step 6) Select Edit at the bottom of the OAuth 2.0 area to edit the authentication parameters.

**Comment by baxist** [comment]
I'm using option 2 and If i select "Edit" I can modify the fields in my screenshot. 
But my attached screenshot looks different than the one in the documentation.
As mentioned, I have these 3 fields in my screenshot:
• Authorization URL
• Token URL
• Refresh URL

But in the documentation, these fields are listed to fill out:
• Login URL
• Tenant ID
• Resource URL

**Comment by JeneferM-MSFT** [comment]
Oh I see now, you seem to have gotten the incorrect identity provider, which is why you are seeing the incorrect input options. Can you please try the steps again? 

![image](https://user-images.githubusercontent.com/62659043/85320356-8e0d2700-b488-11ea-8366-bc7ad3911d44.png)

**Comment by baxist** [comment]
Perfect. Thanks. This not really fixed the problem. But because of this hint, I re-installed the solution and now it works.

Thank you very much!
