### ISSUE TITLE
Admin | Sync Template v2 (Flows) sometimes failing with Environment access denied error

### ISSUE THREAD

**Issue by stmccartney** [microsoft/powerapps-tools#35]
This flow is failing in several of my environments on the step "List Flows as Admin", with an error saying that access is denied.  I have confirmed that with the same user account I can view all of the Flows in the environment in the Power Apps admin portal, so it does have permission.

I can resolve the error by substituting the Environment variable in that step from triggerBody()?['admin_Environmentid'] to triggerBody()?['admin_environmentname'], but I'm not 100% sure why this works.

**Comment by MikkoKoskinen** [comment]
Do you have an older tenant where you have done database upgrades on some point (like 2017, etc.)? Do you have two SYSTEM created the environment?
Like ORGNAME (default) (Upgrade) (orgxxxx) and ORGNAME (Upgrade) (orgxxxx)?

I do and facing issues with the environment id that is saved to the CDS. In these environments, the id is the same, but they have Default- and Legacy- in front. Those a stripped away, though, but then we have two different environments with the same id.

For me, this creates multiple issues, and for example, I'm missing one environment completely.

**Comment by MikkoKoskinen** [comment]
Do you have an older tenant where you have done database upgrades on some point (like 2017, etc.)? Do you have two SYSTEM created the environment?
Like ORGNAME (default) (Upgrade) (orgxxxx) and ORGNAME (Upgrade) (orgxxxx)?

I do and facing issues with the environment id that is saved to the CDS. In these environments, the id is the same, but they have Default- and Legacy- in front. Those a stripped away, though, but then we have two different environments with the same id.

For me, this creates multiple issues, and for example, I'm missing one environment completely.

**Comment by stmccartney** [comment]
Yes, that's exactly it, we had a tenant migration done in 2016.  If you see [this other issue](https://github.com/microsoft/powerapps-tools/issues/36) I've put more detail in, and how I've worked around it.

**Comment by manuelap-msft** [comment]
This should be fixed with the newer releases of the Starter Kit.
