### ISSUE TITLE
[BUG]: Power BI Dashboard - Sign in not possible (Authentication method is empty?)

### ISSUE THREAD

**Issue by baxist** [microsoft/powerapps-tools#353]
**Describe the bug**
If I try to connect to the data for the Power BI Dashboard, I cannot sign in. I cannot select an Authentication method, because there are no selectable entries:

![2020-06-24_12-33-19](https://user-images.githubusercontent.com/67257572/85540988-e292dc80-b617-11ea-91bb-4944244f00a5.jpg)

I'm following these steps with 
Option 1: Get the Power BI dashboard from AppSource
[https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#option-1-get-the-power-bi-dashboard-from-appsource](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#option-1-get-the-power-bi-dashboard-from-appsource)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Center of Excellence - Audit Logs
 - Version 1.0.0.15
 - Power BI dashboard from AppSource

**To Reproduce**
1. Open the BI App, Enter the Environment URL and select "Next"
2. Sign in "authentication method" is missing. If clicking "Sign in" nothing happens.

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid I can't help you here. The template is set up correctly as it works for most people, you are experiencing a problem with App Source and Power BI, and will need to reach out to support there.

**Comment by baxist** [comment]
Found my mistake: I missed the "https://" in the beginning of the data source URL.

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thanks for letting me know!
