### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Model Driven Apps)

### ISSUE THREAD

**Issue by baxist** [microsoft/powerapps-tools#354]
**Describe the bug**
If a user was deleted, the Flow runs into an error when trying go get the user profile.
(Office 365 Users Connector, Get user profile (V2)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Center of Excellence - Core Components
 - Version 1.32
 - Admin | Sync Template v2 (Model Driven Apps)

**Error message**
```
{
  "error": {
    "code": "-1, Microsoft.SharePoint.Client.ResourceNotFoundException",
    "message": "Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown.",
    "innerError": {
      "request-id": "c89f4458-07e9-4ad8-b30e-61012afbbfc7",
      "date": "2020-04-22T00:44:12"
    }
  }
}
```

**Comment by manuelap-msft** [comment]
It looks like you're running a pretty old version of the Core Components  the latest version (1.45) has this fixed already. Could you please upgrade the solution?
