### ISSUE TITLE
Missing xml files in CreateCoEArchivalDocLibraryinSP.zip and CreateCoETemplateLibaryDocLibraryinSP.zip 

### ISSUE THREAD

**Issue by bocESMI** [microsoft/powerapps-tools#356]
**Describe the bug**
Missing solution.xml,customizations.xml and [Content_Types].xml when importing CreateCoEArchivalDocLibraryinSP and CreateCoETemplateLibaryDocLibraryinSP solutions

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core component, CreateCoEArchivalDocLibraryinSP and CreateCoETemplateLibaryDocLibraryinSP

**To Reproduce**
1. Go to Solutions
2. Click on Import
3. Point to CreateCoEArchivalDocLibraryinSP.zip or CreateCoETemplateLibaryDocLibraryinSP.zip 

**Expected behavior**
Expected to be able to download both solutions .. 

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello, that is not a solution zip, its just a flow. You install by going to [https://flow.microsoft.com/](https://flow.microsoft.com/) > Select the Environment of the CoE > My Flows > Import

**Comment by JeneferM-MSFT** [comment]
I've updated documentation to make this more clear. 
Thanks!

**Comment by bocESMI** [comment]
Thank you.
