### ISSUE TITLE
Developer Compliance Center App cannot type Descriptions

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#357]
**Describe the bug**
The developer compliance center app does not allow to type the description of the app. when selecting the field to type it does not place the cursor.  

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Compliance and Report Components
 - Version 1.17
 - App or Flow Developer Compliance Center App

**To Reproduce**

**Expected behavior**
It should let users to type the description of the app. 

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/86025784-9f13e600-b9fc-11ea-8bb8-67ecf8153e8f.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. Correct, you cannot edit the description within this app itself, per the content written there, you go to App Settings, update it there, and then hit the refresh button shown below the box.

**Comment by aakashpatel660** [comment]
What I thought that if the app does not have descriptions user can go to the Developer Compliance Center and write a description of the app there. The issue is that user is not able to write the descriptions at all.

**Comment by JeneferM-MSFT** [comment]
Sorry I'm not following you. 

Please Note: 
1. This functionality is for Canvas Apps only, not Model Driven or SharePoint Forms, next version of the CoE will filter to those only.
1. We are not able to offer the description edit from within this  power app directly, as its not provided in the connector for Power Apps, you have to edit the description in the Power Apps UX directly. Shown here:

Are you saying that the user cannot edit the description in teh product?

**Comment by aakashpatel660** [comment]
okay got it. I thought the user can type the description of the app from the Developer com[pliance app. Thank you for the clarification. When is the next version release just curiosity?

**Comment by JeneferM-MSFT** [comment]
Wonderful. Your issue also helped me realize that we were showing deleted apps in the list, so that is now also fixed in the next version. So thanks again for using CoE and helping make it great! 

Next version is targeted to be out in the next week or two.

**Comment by JeneferM-MSFT** [comment]
New version of the CoE is now available including the change described here. 
Thanks for using CoE!

**Comment by AhmadiRamin** [comment]
Hi @JeneferM-MSFT, we also found that you can not put a description for SharePoint Form App and it confuses the end users to where they need to update their apps, I think it's a good idea to hide the description field when a SharePoint Form App is selected
