### ISSUE TITLE
[BUG]: Last Launch not being populated (non-MFA / basic Authentication version)

### ISSUE THREAD

**Issue by m3ngi3** [microsoft/powerapps-tools#359]
**Describe the bug**
Already saw the issue reported https://github.com/microsoft/powerapps-tools/issues/281 but that seems to be the MFA version. In the ZIP and in the individual components it still seems to be the version without the update App Entity with Last Launch field.

**To Reproduce**
1. Download individual component: https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Individual%20Components or download the ZIP: https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/CoEStarterKit.zip 
2. Import Flow
3. See screenshot below without update of App data --> Last Launch field

**Expected behavior**
Probably not all components updated

**Screenshots**
![image](https://user-images.githubusercontent.com/47530580/86245353-a298a000-bba9-11ea-8053-a5eee255f355.png)

**Comment by JeneferM-MSFT** [comment]
It looks like you dont have the latest version of the flow. Our current version has more items in the switch statement as shown below. When you upgrade, be sure to chose overwrite or you wont receive the updates to your flow. 
We are shipping again in the next week or two, so if you'd rather wait to try again until that happens, I can respond here and let you know. 
Thanks for using CoE!
![image](https://user-images.githubusercontent.com/62659043/86258898-f4790000-bb80-11ea-95e1-b160bbc58cb1.png)

**Comment by m3ngi3** [comment]
Yes I know ☺️.
I reported this issue because you seem to forgot to update the **Basic Authentication Audit Log Sync Flow** as part of the CoE package and as an individual component.

![16DB44C3-CDBB-4ADB-B293-0F2FE1B1AF97](https://user-images.githubusercontent.com/47530580/86259948-f3fe5a80-bbbc-11ea-934f-e65ec793a547.jpeg)

I have downloaded today and both downloads seem to be the older version without switch / last launch update. (Please note that this is not the MFA version)

**Comment by JeneferM-MSFT** [comment]
oh wow, thanks for that note. I will let the release driver know.

**Comment by JeneferM-MSFT** [comment]
Hello. A new version of this flow is now available for download, along with a bunch of other great new stuff for the CoE. 
Enjoy!
