### ISSUE TITLE
Admin | Sync Template v2 failing due to duplicate environment name GUID

### ISSUE THREAD

**Issue by stmccartney** [microsoft/powerapps-tools#36]
This flow sets the record identifier for SYSTEM created environments by removing any text from the environment name, and using the remaining GUID.  However in our tenant (and therefore probably in others) we have two environments whose name only differs by the text prefix.  E.g. one environment has the name "62f78fb7-c6b8-4cd3-b7ef-b8ea01ea5e2d" and the other one has the name "default-62f78fb7-c6b8-4cd3-b7ef-b8ea01ea5e2d".  This causes the flow to fail as it tries to upsert a second environment with the same unique identifier. 

As the identifier requires a GUID, I think the only way to resolve this is to rework this flow so that it first pulls all existing environments from the Environment entity, and then compares to the live list of environments, and then generates a random GUID for any new ones, and uses that

**Comment by MikkoKoskinen** [comment]
We had to implement this workaround, because Record identifier, where env id is used, needs to be a GUID. Not ideal, but we are hoping to get rid of the old Legacy environment soon. 

Then you need to update the Flow Sync also, like @stmccartney is saying in the issue linked above.

**Comment by manuelap-msft** [comment]
We have had some issues with this as the Default and Preview environment apparently get the same GUID with a prefix. We have fixed this in the new version by assigning the preview environment a made-up GUID.
