### ISSUE TITLE
[BUG]: "App Archive and Clean Up - Check Approvals and Archive" Error in action "_get_msapp_file_content"

### ISSUE THREAD

**Issue by baxist** [microsoft/powerapps-tools#361]
**Describe the bug**
Flow "Admin | App Archive and Clean Up - Check Approvals and Archive" runs sometimes into Error in action 'Approve_Archive_-_get_msapp_file_content'

Ouputs of this action:
Status Code: 403
Body:
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:cc6eb2fc-201e-0062-4989-5081ad000000
Time:2020-07-02T15:54:32.2647643Z</Message><AuthenticationErrorDetail>Signed expiry time [Tue, 26 May 2020 00:00:00 GMT] must be after signed start time [Thu, 02 Jul 2020 15:54:32 GMT]</AuthenticationErrorDetail></Error>

I would say the error appears in 50% of the cases.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Center of Excellence - Compliance and Report Components
 - Version 20.4.2020
 - Admin | App Archive and Clean Up - Check Approvals and Archive

**Comment by JeneferM-MSFT** [comment]
This is resolved in newer versions of the toolkit. You will need to upgrade.

Thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
#182

**Comment by baxist** [comment]
Thanks for your answer. But I'm using Version 1.17 and seems to be the newest version?

**Comment by JeneferM-MSFT** [comment]
Did you chose override when asked about customizations on import? Default is maintain, but you need to chose overwrite. 
![image](https://user-images.githubusercontent.com/62659043/86595808-e6e7bf80-bf5e-11ea-9080-7aa9f81a48e9.png)

When you have the new flow, it will have this added re-fetch call
![image](https://user-images.githubusercontent.com/62659043/86596091-4e9e0a80-bf5f-11ea-98e3-e87993d2ac7c.png)

**Comment by baxist** [comment]
damn. Sorry, you're right.
Thanks very much for that hint!

**Comment by JeneferM-MSFT** [comment]
No problem at all. Thanks for using CoE!
