### ISSUE TITLE
[BUG]: List Flows as Admin returning FlowNotFound (Error 404) when using Get Flow as Admin from same data

### ISSUE THREAD

**Issue by m3ngi3** [microsoft/powerapps-tools#363]
**Description**
Because this is not really a CoE Kit issue (I think), I placed this as a community post so see: https://powerusers.microsoft.com/t5/Connecting-To-Data/List-Flows-as-Admin-returning-FlowNotFound-Error-404-when-using/m-p/616060#M9350

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Solution
 - 1.45
 - Admin | Sync Template v2 (Flows)

**To Reproduce**
1. Run Flow on Default Environment and see a Flow being listed that cannot be found
2. Both are admin connections where the Get Flow looks at the Flows Listed so should be same source right?

**Expected behavior**
I expect the Get Flow action to look at the same source as the List Flows action but apparently it is not? 

**Screenshots**
![PowerAutomate_ListFlowsAdmin_01_Default](https://user-images.githubusercontent.com/47530580/86566021-359a5700-bf69-11ea-8b2b-7784e2844fb0.png)
![PowerAutomate_ListFlowsAdmin_02_FlowNotFound](https://user-images.githubusercontent.com/47530580/86566026-392dde00-bf69-11ea-9431-82a0d582d4a6.png)
![PowerAutomate_ListFlowsAdmin_03_FlowNotFound](https://user-images.githubusercontent.com/47530580/86566033-3af7a180-bf69-11ea-8221-7f4767d63c50.png)

**Comment by JeneferM-MSFT** [comment]
Does this repro again if you re-submit? Sometimes when a flow is newly created/deleted, or other timing circumstances, calls to fetch it fail. 

Do you have access to that flow?

**Comment by m3ngi3** [comment]
Hi @JeneferM-MSFT,
Thank you for the quick response!
Been happening for a few days now and always the same Listed Flow with the same GUID that the Get Flow cannot find... Strange right!

When I try to visit the flow using the URL, tha page also says flow not found... 
If it was found and I do not have access, it would show a different message so the flow seems to be really "missing" but the List Flows action gets it in the response 😭

**Comment by JeneferM-MSFT** [comment]
Can you repro outside of the context of the CoE? 
Be sure to add pagination to the list flows call, and then loop through the return with apply to each and call Get Flow As Admin.
See attached as a start, you'll need to set the environment in both the calls to the Power Automate Management connector

[getflowfromlist_20200706160049.zip](https://github.com/microsoft/powerapps-tools/files/4880038/getflowfromlist_20200706160049.zip)

**Comment by m3ngi3** [comment]
Thanx @JeneferM-MSFT !
Flow is running so will give update tomorrow (had to add a delay within Apply to each loop because of connector limits so Flow can take up to 6 hours)

**Comment by m3ngi3** [comment]
Same result:
![image](https://user-images.githubusercontent.com/47530580/86882246-3e696500-c0f0-11ea-842e-7b0bdba8deb0.png)
 Always not finding that specific listed flow: 
`Could not find flow '1f2995ac-90ca-4310-9f91-152f5e845d79'.`

My first run I thought it could be coincidence that someone deleted that flow during the flow run, but it has been the same flow guid for a week now...

**Comment by JeneferM-MSFT** [comment]
In this test flow, in the Get Flow as Admin call, under settings, can you please change:

- **_Retry Type_** from _**Default**_ to **_Exponential_**
- **_count_** to 10 
- **_Interval_** to PT10S

Then run and let met know if it still fails?

**Comment by m3ngi3** [comment]
Same result!

One fail of 1635 loops and again that same GUID... so I really think there is difference in where the List Flows checks, compared to where the Get Flow checks?

**Comment by JeneferM-MSFT** [comment]
Thanks for trying that, I had hoped it was a retry error. It seems like this is a product issue now that we have this repro out of the CoE Toolkit. I'm afraid you'll need to contact product support as a result. Please let me know what you find as if there is a workaround to whatever bug you are hitting, I can put it into the toolkit.

**Comment by m3ngi3** [comment]
You are great! Will definitely keep you updated on the Microsoft Ticket 👍

**Comment by JeneferM-MSFT** [comment]
Hi there. I'm wondering what you were able to find here.

**Comment by m3ngi3** [comment]
It is a bit of a hassle at the moment because of my leave and the leave at the team of the customer where this issue occurred, so the ticket with Microsoft is in a idle state now. Will update immediately if progress is made 👍

**Comment by JeneferM-MSFT** [comment]
Enjoy your leave! I'll stay patient on this one so I can see what comes of this. Thanks so much!

**Comment by m3ngi3** [comment]
An update from the Microsoft Engineers:

> It looks like we ran into an issue, where the Flow is deleted , but the logic app which runs behind the Flow did not, which is why it is not there for ‘Get Flow’ but List Flow under admin pulls it. It’s a rare occurrence, however, we are working towards this issue and fix the actions.
> Can` you confirm from the user whether they want this Flow or not. We can either perform cleanup and remove it, or restore it back for this user. Upon your response, we will proceed with the cleanup, and post that you won’t see this issue.

So I guess there could be a difference in where the two actions look. Microsoft will fix this for us in this specific tenant 👍
