### ISSUE TITLE
[BUG]: New 08072020 version of Admin | Sync Template v2 (Check Deleted) fails in Get Apps as Admin

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#369]
**Describe the bug**
The latest version of the flow Admin | Sync Template v2 (Check Deleted) fails "The Request Failed With the environment <null> could not be found in tenant"  The environment specified in the call does exist.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version V2 08072020
 - Flow Admin | Sync Template v2 (Check Deleted)

**To Reproduce**
Run the Flow

**Expected behavior**
The Flow should run to completion successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/87027373-fa03c500-c1d4-11ea-9251-a0c095928b5f.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
My guess is that the data in your environments tables has somehow gotten corrupted. I havent seen an env't null error before. 

Can you please add here the results of these two calls? 
- List CoE Environments not marked deleted - pre new deletes
- List CoE Environments not marked deleted

**Comment by NPrice99** [comment]
Hi Jenefer  What Am I looking for ?  the admin_environmentname is correct in both. Nigel

**Comment by JeneferM-MSFT** [comment]
The error message is indicating that the environment name is null, which is never should be. 
You are looking for the two actions named as I listed above, the first one is at the top of your screenshot and the other is a few calls up.

Another approach would be to delete all the records in your Environment entity and re-run sync. That woudl get you in a clean state for that entity.

**Comment by NPrice99** [comment]
So you are saying that field admin_environmentname could be null in one of the records returned by List CoE Environments not marked deleted - pre new deletes or List CoE Environments not marked deleted ?  I will take a look.

**Comment by NPrice99** [comment]
I have just checked and admin_environmentname has a value in every entry in both List CoE Environments not marked deleted - pre new deletes List CoE Environments not marked deleted

**Comment by JeneferM-MSFT** [comment]
If you expend these two actions in the run history for your failure, can you please show me what is shows? Be sure to click "show more".

Here is what mine look like (success case for me):
![image](https://user-images.githubusercontent.com/62659043/87083262-f16db780-c1f1-11ea-9b05-a61a02ffb51c.png)

**Comment by brunoboucher** [comment]
As per request by @JeneferM-MSFT I continue there.
Here the sprint screen and error description from Admin | Sync Template v2 (Power Apps User Shared With)
Admin | Sync Template v2 (Power Apps User Shared With)
The failing action is Get_App_Role_Assignments_as_Admin 
![getAppRole](https://user-images.githubusercontent.com/32851166/87796828-e3ceb800-c817-11ea-8811-27ecb586c669.gif)

**Comment by brunoboucher** [comment]
{
  "error": {
    "code": "AzureResourceManagerRequestFailed",
    "message": "The request failed with error: 'The environment '<null>' could not be found in the tenant 'c21157ca-bce3-41a8-8aa7-a23c4639610a'.'. The tracking Id is '8b01e7e6-9354-4f11-8384-65cc6fe92a20'.",
    "details": [
      {
        "code": "MultipleErrorsOccurred",
        "message": "There were multiple errors from the API Hubs service. Please see the details for more information.",
        "details": [
          {
            "code": "EnvironmentNotFound",
            "message": "The environment '<null>' could not be found in the tenant 'c21157ca-bce3-41a8-8aa7-a23c4639610a'."
          }
        ]
      },
      {
        "code": "FullNonLocalizedError",
        "message": "{\"error\":{\"code\":\"EnvironmentNotFound\",\"message\":\"The environment '<null>' could not be found in the tenant 'c21157ca-bce3-41a8-8aa7-a23c4639610a'.\"}}"
      }
    ]
  }
}

**Comment by JeneferM-MSFT** [comment]
oh sorry I didnt realize this second bug was in that flow. I believe we have a fix for your bug (Bruno) in 1.53 of Core. Can you please udpate and see if that resolves?

**Comment by osbornecc** [comment]
Hi Jenefer,
I've been following this thread since I am experiencing the same "The environment '<null>' could not be found" error but only in the "Admin | Sync Template v2 (Power Apps User Shared With)" flow.  I'm using version 1.53 of Core, which I applied on July 16.

Yesterday, I deleted the solution (and all my data) so I could have a "fresh" start, but still every time the Power Apps User Shared With flow runs it fails on all apps in our Default environment.  It runs successfully against apps in all my other environments.  It seems to be only unhappy with Default.

I have also verified that the data in the Environment and PowerApps App entities are valid (no corruption).

Is there maybe an update to 1.53 that I missed?
Thank you,
Christi

**Comment by JeneferM-MSFT** [comment]
When you upgraded, did you chose to overwrite the components? That is necessary to receive updates.

**Comment by osbornecc** [comment]
Hi,
Yes, sorry.  Actually I ended up performing the upgrade but then I deleted the entire solution and my copied flows and started from scratch.  As of yesterday, it's as if I imported the Core Components fresh (no upgrade).

Did that make sense?
Thanks.

**Comment by brunoboucher** [comment]
> oh sorry I didnt realize this second bug was in that flow. I believe we have a fix for your bug (Bruno) in 1.53 of Core. Can you please udpate and see if that resolves?

ok i'll try and give you an update

**Comment by brunoboucher** [comment]
I already run the 1.53.

**Comment by brunoboucher** [comment]
I do a test on my pre-prod environment.
I got some excution errors and success
the fail run is the same error I got in my PROD environment

**Comment by brunoboucher** [comment]
I didn't start the process...it's seem to be launch by the "CoE process"
![image](https://user-images.githubusercontent.com/32851166/88120578-3d751080-cb91-11ea-9a66-17dc9bb73512.png)

**Comment by JeneferM-MSFT** [comment]
ok I have a repro finally. I will investigate.

**Comment by JeneferM-MSFT** [comment]
Those of you experiencing this via the Power Apps Shared With flow, can you please see if this update resolves the issue for you? 

[FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip](https://github.com/microsoft/powerapps-tools/files/4960362/FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip)

**Comment by osbornecc** [comment]
Jenefer,
The updated Power Apps Shared With flow ran successfully against all of my environments (including Default).  
Thank you!

**Comment by brunoboucher** [comment]
> Those of you experiencing this via the Power Apps Shared With flow, can you please see if this update resolves the issue for you?
> 
> [FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip](https://github.com/microsoft/powerapps-tools/files/4960362/FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip)

ok I'll do it and give you some news

**Comment by NPrice99** [comment]
Works for me !

**Comment by brunoboucher** [comment]
The flow is currently running and seems to running fine,
But in some execution I got an error ... but the majority of execution is successful
![image](https://user-images.githubusercontent.com/32851166/88207512-e8331080-cc1d-11ea-8ae9-e7fda3514909.png)

And the error content:
{
  "error": {
    "code": "0x80040203",
    "message": "Invalid type for entity id value",
    "innererror": {
      "message": "Invalid type for entity id value",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.CreateInternal(Entity entity, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.CreateOrganizationResponse(Entity entity)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.CreateEdmEntity(CrmODataExecutionContext context, String edmEntityName, EdmEntityObject entityObject, Boolean isUpsert)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.PostEntitySetImplementation(String& entitySetName, EdmEntityObject entityObject)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass10_0`2.<InvokeActionAndLogMetric>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    }
  }
}

**Comment by brunoboucher** [comment]
And in some applications when I look the details I got this issue:
![image](https://user-images.githubusercontent.com/32851166/88209212-5d074a00-cc20-11ea-99e5-38f819cb0447.png)

**Comment by JeneferM-MSFT** [comment]
Thanks all for using CoE! I'm going to assume the original issue here is fixed then thanks to your testing, and will close this out once we release the fix.

**Comment by JeneferM-MSFT** [comment]
Bruno, can you please post a separate issue for this new issue around the upsert step? We try to keep these to one issue one bug.

**Comment by brunoboucher** [comment]
oh yes sorry for that !

**Comment by JeneferM-MSFT** [comment]
We have just released this fix with 1.54 of core . [aka.ms/CoEStarterKitDownload](aka.ms/CoEStarterKitDownload)
