### ISSUE TITLE
Admin | Sync Template v2 (Apps) incorrectly marks model driven apps as deleted

### ISSUE THREAD

**Issue by stmccartney** [microsoft/powerapps-tools#37]
In this flow the apply to each "Apply to each existing App to find deleted apps" loops through the existing apps in the entity PowerApps Apps and compares to the live apps retrieved from the environment.  Any that are in the entity and not in the live apps list are marked as deleted.

However the step "List existing apps" that extracts apps from the entity inadvertently includes model driven apps.  Because these apps are not in the canvas app live list, they are then marked as deleted.

This could be resolved either by adding a filter to the action "List existing apps" - e.g. admin_powerappstype_display eq 'Canvas' or by adding a filter step

**Comment by manuelap-msft** [comment]
I have applied this fix, and it will be published with the next version in the next few days. Apologies for missing this earlier.
