### ISSUE TITLE
[BUG]: Unable to deploy solution in GCC

### ISSUE THREAD

**Issue by daharsh4** [microsoft/powerapps-tools#370]
**Describe the bug**
Unable to deploy solution in GCC. Error occurs when following Step 2.02 (https://review.docs.microsoft.com/en-us/powerapps/sample-apps/return-to-workplace/deploy?branch=rtw-docs#step-2-install-the-package)

"An error has occurred while processing your request. Please resubmit your request. If problems persist contact customer support."

**To Reproduce**
Follow Step 2.02 (https://review.docs.microsoft.com/en-us/powerapps/sample-apps/return-to-workplace/deploy?branch=rtw-docs#step-2-install-the-package)
1. Go to App Source, select "Get it Now"
2. Sign-in, navigate to a Dynamics page (https://port.crm.dynamics.com/G/Marketplace/Index.aspx....)

**Expected behavior**
App to install in my GCC environment

**Additional context**
Different error occurred when trying to navigate to: https://port.crm9.dynamics.com/G/Marketplace/Index.aspx

**Comment by narpad** [comment]
The solution has not been released to production yet.
