### ISSUE TITLE
[BUG]: Required Dynamics 365 licenses erro

### ISSUE THREAD

**Issue by bocESMI** [microsoft/powerapps-tools#371]
**Describe the bug**
The following error message is displayed when create the CoE envionment. 
"You do not have the required Dynamics 365 licenses to create databases with Dynamics apps"

**Component (please tell us which flow or app you are experiencing issues with):**
The message appears when I try to create a new envronment.

**To Reproduce**
1. Go to https://admin.powerplatform.microsoft.com/environments
2. Click on 'New' fill out Name , Type -> Production
3. Choose Yes to "Create a database for this environment"
4. Hit "Next" and the above Warning appears

**Expected behavior**
Expected database to be created for the new enviroment.

**Screenshots**
See attached.

**Additional context**
We are using Global Admin account to install the CoE
![2020-07-09_10-58-09](https://user-images.githubusercontent.com/32463806/87056338-785f6780-c1d3-11ea-9de4-c2d20e87afa7.png)

**Comment by JeneferM-MSFT** [comment]
There are licensing requirements in order to use the CDS, which is required for the toolkit.
Please see near the bottom of the [pre-req list](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites).
