### ISSUE TITLE
[BUG]: When I tried to "Save As" the "Admin | Sync Template v2" I got error - pagination issue

### ISSUE THREAD

**Issue by kevinnoo** [microsoft/powerapps-tools#373]
**Describe the bug**
When I tried to "Save As" the "Admin | Sync Template v2" I got this error: "The pagination policy of workflow run action 'List_Makers' of type 'ApiConnection' at line '1' and column '4028' is not valid. The value specified f...".

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.45
 - "Admin | Sync Template v2"

**To Reproduce**
I try to "Save As" the "Admin | Sync Template v2"

**Expected behavior**
Get this error: "The pagination policy of workflow run action 'List_Makers' of type 'ApiConnection' at line '1' and column '4028' is not valid. The value specified f...".

**Screenshots**
![image](https://user-images.githubusercontent.com/48028930/87258099-91cc1200-c466-11ea-97f2-1c20cb8a50c4.png)

**Comment by JeneferM-MSFT** [comment]
Are you able to see the rest of the error message?

**Comment by manuelap-msft** [comment]
Hello,

you are using an old version of the CoE Starter Kit! Please use the latest published version 1.52, where this issue was addressed.

Root cause: Pagination on all CDS actions was set to 10,000 but we recently learned that some license types only allow pagination of 5,000 so we have updated all CDS actions to this value. If you install the latest version you won't experience this issue.

**Comment by MoMajad** [comment]
@manuelap-msft Hi, I just downloaded the Starter Kit today from aka.ms/CoEStarterKitDownload and got the exact same error on two of the Flows, the zip file version is "CenterofExcellenceCoreComponents_1_54_managed", the two flows were:
Admin | Sync Template v2 (Custom Connectors) & Admin | Sync Template v2 (Flows)
I fixed it locally by changing the settings:
![image](https://user-images.githubusercontent.com/14158313/88487729-8953fb00-cf7f-11ea-83d8-1f6b43d41a64.png)
![image](https://user-images.githubusercontent.com/14158313/88487735-940e9000-cf7f-11ea-8027-d0b12bd2fd11.png)
![image](https://user-images.githubusercontent.com/14158313/88487736-9a047100-cf7f-11ea-9c75-11f83f239a2c.png)
![image](https://user-images.githubusercontent.com/14158313/88487737-a1c41580-cf7f-11ea-80ba-d681da923e93.png)

So it seems to have been fixed for Admin |Sync Template v2 but for me at the very least was causing an error on two others

**Comment by manuelap-msft** [comment]
Could you confirm you are using a premium license to install the CoE Kit? We have investigated this issue further and the [5000 limit](https://docs.microsoft.com/en-us/power-automate/limits-and-config#looping-and-debatching-limits) should only apply to users with O365 or free licenses.

**Comment by MoMajad** [comment]
I am using the Community plan, I have fixed it locally as per above setting but may block other admins/developers exploring the CoE before taking to client instance. Apart from this everything else installed correctly across all components on community plan instance.

**Comment by manuelap-msft** [comment]
We will amend those two instances with the next release, but I do want to mention that a pre-requisite for using the kit is a premium license. Next to the pagination, with a free license you will also hit further throughput limits (see calls allowed under throughput here): https://docs.microsoft.com/en-us/power-automate/limits-and-config#looping-and-debatching-limits
