### ISSUE TITLE
Orphaned Power Apps and Flows

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#377]
Hi, I'm investigating the "Set App Permissions" and "Set Flow Permissions" app of the Center of Excellence.
In both Power Apps, there is a section "Orphaned apps" and "Orphaned flows".
Until now, I always understood that when a Power App or Flow only has one owner, and when that owner's account is deleted in AD, the flow and apps are also deleted.
But now that I see this "Orphaned" in the CoE apps, it looks like apps/flows without owner just keep existing and can be assigned a new owner? Or am I wrong?
Thanks in advance.

**Comment by manuelap-msft** [comment]
You are correct!

Apps or Flows are not deleted if the owner is removed from the AD.

With Apps, they will continue working for end users (who will use their own connection to data sources to connect and thus not depend on the owner who might have left). A new owner will be required for maintenance and changes.

With Flows, they will stop working as it depends on the owners connections to run. A new owner will be required for the flow to continue working, if it's needed. 

From both apps, you can also choose to delete orphaned apps and flows if they are no longer needed.

**Comment by manuelap-msft** [comment]
Thanks for using CoE! Closed due to no follow up actions.
