### ISSUE TITLE
[BUG]: Flow Admin | Sync Template v2 (Model Driven Apps) - Wrong Environment name

### ISSUE THREAD

**Issue by txh57** [microsoft/powerapps-tools#380]
The flow fails for all environments that are located in Europe (and maybe other regions too).

Not all environments have a _Linked Metadata Host Name Suffix_ of _name.**crm**.dynamics.com_. Some of them (f.e the ones located in Europe) have a suffix of _name.**crm4**.dynamics.com_.

There are actually two flow steps that work with hardcoded strings building the environment that fail for these environments (404):

- List Model Driven Apps, and

- Get MDD App Creator.hardcoded

The formula could be replaced by the following formula to build a dynamic value:
`concat(
  body('Get_Environment_as_Admin')?['properties']?['linkedEnvironmentMetadata']?['uniqueName'], 
  '.',
  substring(
    body('Get_Environment_as_Admin')?['properties']?['linkedEnvironmentMetadata']?['hostNameSuffix'], 
    0, 
    indexOf(body('Get_Environment_as_Admin')?['properties']?['linkedEnvironmentMetadata']?['hostNameSuffix'], '.')
  )
)`

This code can be posted in a Compose Action placed below step _Get Environment as Admin_.

**Comment by JeneferM-MSFT** [comment]
Thank you for providing such detailed notes. We will investigate.

**Comment by NPrice99** [comment]
Could this be an issue for other flows ? eg Flow Admin | Sync Template v2 (Canvas Apps)

**Comment by txh57** [comment]
I'm not 100% sure, but all the other Admin | Sync Templates v2 ... flows are running fine with me.

The patch I suggested has to be adapted for environments (e.g. Preview) for which no database has been created. For these cases indexOf() will actually throw an error.

**Comment by JeneferM-MSFT** [comment]
This only repros for objects that dont have a supported connector (model driven apps, PVA), it doesnt repro for calls about canvas apps as they have a supported connector to use, and so we dont have to go through these CDS entities to fetch information. 
From my investigation so far, the new PVA and Delete flows did this correctly (though differently). 

I have this local fixed for the MDA flow and am running testing.

**Comment by JeneferM-MSFT** [comment]
We have just released this fix with 1.54 of core . [aka.ms/CoEStarterKitDownload](aka.ms/CoEStarterKitDownload)

**Comment by NPrice99** [comment]
Hi Jenefer

Can I assume that 1.54 = 1.53 + the two fixes you released earlier ?

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
There are 3 fixes in the new version:
Fix to a bug in **_Admin | Sync Template v2 (Power Apps User Shared With)_**, which caused fetching user permissions in Default environment to fail.

Fix to a bug in **_Admin | Sync Template v2 (Model Driven Apps)_**, which caused environments with crm urls not ending in .crm to fail to sync. Example impact are environments like those with .crm4 in the url.

Fix to a bug in **_Admin | Sync Template v2 (PVA)_**, which caused a failure when syncing a PVA Component’s flow, when that flow has not yet been added to the Flow entity.
