### ISSUE TITLE
Feature : Power Automate Approval from PowerApps

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#381]
Hello, 

I was trying to see, is there a way to have a PowerApps where user can go and do the all approvals within that app. So we do not have to send emails for approvals. I came across 1 app but did not see the read me to see how to setup. I have pasted the link below. Can you please tell me is it feasible to do a 1 App where users can approve there request using the app. 

https://github.com/microsoft/powerapps-tools/tree/master/Apps/Approvals

**Comment by manuelap-msft** [comment]
The solution you are referring to is documented and described in this blog post:
https://powerapps.microsoft.com/en-us/blog/building-an-approval-experience-in-canvas-apps/

It describes how to set this up, so it would be possible to achieve this yourself - you can learn from the solution on how to do this.

Hope that helps.

**Comment by manuelap-msft** [comment]
Hello,

the Approvals solution and template are not part of the CoE starter kit, and thus not supported by the CoE Starter Kit team. You can try and get support from the Power Users community https://powerusers.microsoft.com/t5/Power-Apps-Community/ct-p/PowerApps1

**Comment by aakashpatel660** [comment]
Thank you

Best Regards,
Akash Patel
