### ISSUE TITLE
[BUG]: Activate the Sync Template flows steps doesn't work - pagination issue

### ISSUE THREAD

**Issue by Sachdesai** [microsoft/powerapps-tools#382]
**Describe the bug**
when try to follow Activate the Sync Template flows steps from documentation. it givens and error listed in screenshot 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core 

**To Reproduce**
1. Follow steps in "Active the sync template" section - Here is link to doc https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

**Expected behavior**
it shows allow to follow that step 

**Screenshots**
attached 

**Additional context**
None 
<img width="347" alt="PowerAppsCoE Error" src="https://user-images.githubusercontent.com/31678434/87965422-ba1cc780-ca89-11ea-90cd-70fac5ec5718.png">
<img width="347" alt="PowerAppsCoE Error" src="https://user-images.githubusercontent.com/31678434/87965480-d15bb500-ca89-11ea-9ad8-8c6f064fe077.png">

**Comment by manuelap-msft** [comment]
Hello,

are you using the latest version of the CoE Starter Kit? Please make sure you [download ](https://aka.ms/coestarterkitdownload) the latest version of the kit as this issue was addressed and fixed there.

Thanks for using the CoE Starter Kit,
Manuela

**Comment by NPrice99** [comment]
Yes , Version 1.53 of the Core Components.

**Comment by joerodgers** [comment]
Seeing the same error on different flows. Screenshot attached.

![err](https://user-images.githubusercontent.com/28455042/88092973-5533a100-cb5f-11ea-93ab-88de9c87b2e0.jpg)

**Comment by Sachdesai** [comment]
That is correct, I get similar error on another flow. I am using 1.53 version 
![image](https://user-images.githubusercontent.com/31678434/88094276-506fec80-cb61-11ea-844a-307a88d5f0e5.png)

**Comment by JeneferM-MSFT** [comment]
Rather than doing a save-as, can you please edit the flow and reconnect the connectors there? Go to the settings and see what the pagination setting is for the gets. Here is one you can use to find:
![image](https://user-images.githubusercontent.com/62659043/88095323-c49e9600-cb49-11ea-92d4-de832179f365.png)

**Comment by TM-68** [comment]
The threshold is set to 5000

**Comment by JeneferM-MSFT** [comment]
Can you please enable the flow using this methodology (enable all these connectors instead of save as) and see if the flow runs?

**Comment by Sachdesai** [comment]
for me, it is not the case, it shows this and I see settings disable. I am global admin
![image](https://user-images.githubusercontent.com/31678434/88104884-19a1d280-cb71-11ea-8803-f58996414b03.png)

**Comment by JeneferM-MSFT** [comment]
Sachdesai, you need to add a new connection first.

**Comment by Sachdesai** [comment]
I did but still it gives same message, anyone available to troubleshoot this live?

**Comment by JeneferM-MSFT** [comment]
Our support model does not afford us to do calls with our GitHub users unfortunately. 
When you say it gives the same message, what do you mean. Can you share a screenshot? 
I'm hoping you guys can change the value down (try 2,000 for example) and see where you are allowed to use/save as the flow.

**Comment by manuelap-msft** [comment]
Hello @Sachdesai,

can you please find this action in the Flow called "Find connector record", it's under the "apply to each connector" loop and go the ... > Settings > and change the Pagination there to 5000. It will currently be set to 10000. Looks like we missed one action when we reduced the pagination for all. 

![image](https://user-images.githubusercontent.com/55705669/88424323-3d6d4e80-cde5-11ea-96b8-ec49eae110e1.png)

**Comment by Sachdesai** [comment]
I tried to do that today, here is message it gives 

![image](https://user-images.githubusercontent.com/31678434/88564688-826dcc80-d001-11ea-9c1c-87f939a106b6.png)

**Comment by NPrice99** [comment]
It looks like one of your connections is not authorised.

Look for a Flow step with an exclamation mark on it.

**Comment by Sachdesai** [comment]
Yeah, somehow I don't see that, there were few triangle but after adding connection, it goes away

![image](https://user-images.githubusercontent.com/31678434/88570110-84d42480-d009-11ea-91ae-6c2fce89eace.png)
![image](https://user-images.githubusercontent.com/31678434/88570132-8d2c5f80-d009-11ea-8ea0-1d761284de38.png)
![image](https://user-images.githubusercontent.com/31678434/88570149-95849a80-d009-11ea-829b-978472944e6d.png)
![image](https://user-images.githubusercontent.com/31678434/88570165-9ae1e500-d009-11ea-9936-9e47bc944938.png)

**Comment by NPrice99** [comment]
Hi

They must be there somewhere or else you would not get the message.

I suggest you expand all of the workflow steps.  You should then find where the unauthorised connections are.

I would certainly expand the switch statement (The one which is grey)

Regards

Nigel

**Comment by Sachdesai** [comment]
It was issue with Flow license. Once flow license is assigned to admin, it solved all this issue.

**Comment by JeneferM-MSFT** [comment]
Thank you for following up with us on the resolution, and for using CoE!
