### ISSUE TITLE
[BUG]: AF20023 error when setting up custom connector for audit log components

### ISSUE THREAD

**Issue by giustis5** [microsoft/powerapps-tools#384]
**Describe the bug**
When i setup the audit log component and come to the stage of testing the custom connector. Instead of getting the expected response:

You should see a (200) status returned, which means the query was successful.

Instead I'm getting error AF20023 with a message that says 'the subscription was disabled'. I have confirmed the details within the settings are correct. 

**Component (please tell us which flow or app you are experiencing issues with):**
Setup audit log components - Custom Connector

**To Reproduce**
Follow the guide: https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-auditlog

**Comment by JeneferM-MSFT** [comment]
Can you please confirm, are you setting up via Option 1 or Option 2? 
Did you look through this list already?
![image](https://user-images.githubusercontent.com/62659043/88098598-de8ea780-cb4e-11ea-9715-4bf23516ca84.png)

**Comment by giustis5** [comment]
Hi, option 2 and yes i have eliminated all things on this list, i went through the process again with 2 other people to confirm i wasnt missing a step or getting some of the data wrong, but it was all as stated in the instructions.

**Comment by giustis5** [comment]
Hi, we tried again this morning and it has worked. Weird but at least its working. Thanks

**Comment by manuelap-msft** [comment]
Thanks for confirming! If you have only recently enabled the Audit Log, it can take a while for it activate and be available through the API. Maybe that was the case! Glad it's resolved, and thanks for using the CoE Starter Kit!
