### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Power Apps User Shared With)

### ISSUE THREAD

**Issue by giustis5** [microsoft/powerapps-tools#386]
**Describe the bug**
When the flow 'Admin | Sync Template v2 (Power Apps User Shared With)' runs, of the 30 or so runs that happens, only around 5 are successful, with the remainder reporting the error:

The request failed with error: 'The environment '<null>' could not be found in the tenant '<GUID>'.'. The tracking Id is '<GUID>'.

5 of them are successful but the others are not. When i then use the 'Power Platform Admin View' power app, when i select an app, it says there are users that the app is shared with but the panel to show you those users is blank (Screenshot attached).

Any ideas?
![ss](https://user-images.githubusercontent.com/68608137/88171146-bff3e380-cc16-11ea-8ae9-ca1e6541bf21.PNG)

**Comment by NPrice99** [comment]
Which version of the Core Components are you  using 1.53 ?

**Comment by giustis5** [comment]
yes, the latest one, i just downloaded it and installed it yesterday

**Comment by JeneferM-MSFT** [comment]
ok I have a repro finally (this is being tracked in multiple bugs). I will investigate.

**Comment by JeneferM-MSFT** [comment]
Can you please see if this update to the flow resolves the issue for you? 

[FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip](https://github.com/microsoft/powerapps-tools/files/4960346/FixtoNullEnvBuginPowerAppsUserSharedWith_20200722134720.zip)

**Comment by giustis5** [comment]
Testing now, will update you shortly.

**Comment by giustis5** [comment]
![ss2](https://user-images.githubusercontent.com/68608137/88187297-3fd97800-cc2e-11ea-8135-27827b938247.PNG)

Im afraid the same thing happened, 5 succeeded and the rest failed. The error message is however different now. See attached screenshots.

![ss3](https://user-images.githubusercontent.com/68608137/88187423-67c8db80-cc2e-11ea-97b2-30209e6820f3.PNG)

**Comment by JeneferM-MSFT** [comment]
Can you please go up and see what value gets put in the EnvironmentName variable in the "Get Environment" scope?
![image](https://user-images.githubusercontent.com/62659043/88188515-cf5e3700-cbec-11ea-8536-3a7273f33236.png)

**Comment by giustis5** [comment]
Here are all the steps:

![ss1](https://user-images.githubusercontent.com/68608137/88189034-8334e600-cc30-11ea-95c0-cd7b24128974.PNG)

![ss2](https://user-images.githubusercontent.com/68608137/88189042-85974000-cc30-11ea-9caa-c274e6fb9d3a.PNG)

![ss3](https://user-images.githubusercontent.com/68608137/88189057-88923080-cc30-11ea-8133-ed1c7bd8352d.PNG)

![ss4](https://user-images.githubusercontent.com/68608137/88189066-8af48a80-cc30-11ea-8c1b-51824a1f150c.PNG)

![ss5](https://user-images.githubusercontent.com/68608137/88189072-8cbe4e00-cc30-11ea-9872-72a24a6adbe9.PNG)

![ss6](https://user-images.githubusercontent.com/68608137/88189080-8e881180-cc30-11ea-9730-0f634d4a6b87.PNG)

**Comment by JeneferM-MSFT** [comment]
That appears to be the wrong flow. 
The flow I sent for testing was this one: Admin | Sync Template v2 (Power Apps User Shared With), which does not have those steps.

**Comment by giustis5** [comment]
ok yes, here you go. 

![ss1](https://user-images.githubusercontent.com/68608137/88192841-e9236c80-cc34-11ea-8b70-22127ac7d084.PNG)

![ss2](https://user-images.githubusercontent.com/68608137/88192850-eaed3000-cc34-11ea-8d97-2237e0dcdfee.PNG)

**Comment by JeneferM-MSFT** [comment]
Do you know the name of the environment for which this is failing? Is it your default environment? 
If so know which environment, can you please make a quick test flow to get the properties of that environment like so? 

![image](https://user-images.githubusercontent.com/62659043/88201907-f1f84c00-cbfc-11ea-9b51-0b2d375183cf.png)

**Comment by giustis5** [comment]
Hi, its working. I tried what you suggested and my account didnt have permission to get the environment, i have updated it and its working.  Thank you

FYI, whilst doing this when i sent you the wrong screenshots, i found another one of the flows that has an issue. The others all work fine :) but Admin | Sync Template v2 (Model Driven Apps) does not. Its a similar thing, some work, some dont. The error message reported is:

CRM organization with unique name '<Org ID>' not found.

Should i raise a new ticket for this one?

**Comment by JeneferM-MSFT** [comment]
I believe the CRM issue you are seeing in the model driven flow is issue #380 
Can you please try the following which is the local fix to that? And if not, please post a separate issue. 
[fixtoMDflow_20200722175736.zip](https://github.com/microsoft/powerapps-tools/files/4961603/fixtoMDflow_20200722175736.zip)

**Comment by giustis5** [comment]
Hi, yes i think that has fixed it. I still get errors but they are related to permissions in the various environments available. Thank you so much for your support, its been fantastic :).
