### ISSUE TITLE
[BUG]: Cannot update Office 365 Management API custom connector

### ISSUE THREAD

**Issue by janwillemkeizer** [microsoft/powerapps-tools#387]
**Describe the bug**
After I paste the required values in the Security edit form for the Office 365 Management API custom connector those values are not saved. They go back to the default values.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [ Center of Excellence - Audit Logs ]
 - Version [1.0.0.17 ]
 - App or Flow [Office 365 Management API custom connector]

**To Reproduce**
I followed the steps outlined under https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector

**Expected behavior**
The entered values are saved and visible after clicking on "Update Connector"

**Screenshots**
![CoE](https://user-images.githubusercontent.com/15108648/88172996-26323380-cc22-11ea-9f60-ff630c86a858.PNG)

**Additional context**
As I work for a Dutch company the language on the platform is also Dutch.

**Comment by JeneferM-MSFT** [comment]
Hello there. That product is not part of the Center of Excellence, just something we use. You will need to go through support channels if you need help with that. 
Thanks for using CoE!
