### ISSUE TITLE
Group Email for Failed Admin Flows

### ISSUE THREAD

**Issue by KeithWhatling** [microsoft/powerapps-tools#39]
Would be Great if there was an admin o365 group setting that could be configured in the settings entity so that all failed emails for the flows could route to that email address rather than use the ADM account that was used to authenticate the flow.

**Comment by manuelap-msft** [comment]
The error handling has improved with the new release, rather than sending emails for each Sync Flow failure, we know store Sync Flow errors in a CDS entity and a daily update of errors is sent to the admin. The admin email address can now be configured using an Environment Variable.
