### ISSUE TITLE
[BUG]: Sync Template V2 fails 429 - consistently (ie more than once consecutively)

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#394]
**Describe the bug**
Sync Template V2 fails 429 - consistently (ie more than once)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version 1.54
 - Sync Template (v2)

**To Reproduce**
Run Flow Sync Template V2

**Expected behavior**
I expected the flow to complete

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/88657946-8fa2be00-d0ca-11ea-97d9-f5842f6475d1.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

a 429 error means a Threshold has been reached; the Throughput limits in a Flow vary by license and are described here
https://docs.microsoft.com/en-us/power-automate/limits-and-config#throughput-limits

Likely, you are hitting one of those limits - those will depend on the size of your environments and number of apps and flows. Here's some tips on what you can change in the flow to overcome throttling limits. You can either increase the retry policy, or - if this action occurs in a loop - reduce the degree of parallelism on the loop
https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#timeouts-in-the-admin--sync-template-v2

Thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
Hi Nigel. It looks like you are using a stale version of the flow as well. While I know that you have uploaded the new version (1.54) did you chose overwrite on upgrade? It is not the default but without it you wont get the new flows. 

The calls to mark the environment as deleted have been moved out to a separate flow in the new versions. 

![image](https://user-images.githubusercontent.com/62659043/88675299-a67feb00-d09f-11ea-86a5-9e115e38c8dc.png)

**Comment by NPrice99** [comment]
Thanks for pointing that option out Jennifer.  As it was not recommended I did not use it.

**Comment by JeneferM-MSFT** [comment]
I added a note in the upgrade section for the next release of the Docs. 
Thanks for using CoE!
