### ISSUE TITLE
[BUG]: Flow description of Create CoE Archival Doc Library in SP points to Crisis Communication App

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/powerapps-tools#398]
**Describe the bug**
The Flow description of the flow _Create CoE Archival Doc Library in SP_ points to the Crisis Communication App instead of CoE

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: SharePoint setup
 - Version [July 16, 2020]
 - App or Flow [Flow: Create CoE Archival Doc Library in SP]

**Screenshots**
![image](https://user-images.githubusercontent.com/30928094/88787671-854cf680-d194-11ea-92e0-9a16a9c192f3.png)

**Comment by JeneferM-MSFT** [comment]
Thanks Rebekka. We'll update these with the next release.

**Comment by manuelap-msft** [comment]
This has been updated just now, thanks for the feedback!
