### ISSUE TITLE
[BUG]: CoE Kit Sync Flows throttling

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/powerapps-tools#399]
**Describe the bug**
A lot of the sync Flows have as one of the first steps an action to load Power Automate Environment Variable. A lot of the sync flows are triggered when records in the environment entities are created or updated. In larger enterprise environments this means that multiple sync Flows runs will start around at the same time and around the same time load the Power Automate Environment Variable. As a result some of the runs will fail with a 429 error specifically on the _List Environment Variable - admin PowerAutomateEnvironmentVariable_ action. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Solution
 - Version [e.g. 1.53]
 - Sync Template (v2) Flows:
   - Admin | Sync Template v2 (Apps)
   - Admin | Sync Template v2 (Custom Connectors)
   - Admin | Sync Template v2 (Flow Action Details)
   - Admin | Sync Template v2 (Flows)
   - Admin | Sync Template v2 (Model Driven Apps)
   - Admin | Sync Template v2 (Power Apps User Shared With)
   - Admin | Sync Template v2 (PVA)
   - Admin | Sync Template v2 (Sync Flow Errors)
  

**Screenshots**
![image](https://user-images.githubusercontent.com/30928094/88788856-34d69880-d196-11ea-9fb0-352a9e8fffdd.png)

**Additional context**
Consider changing the setup of the sync flows so this environment variable does not have to be loaded for every run of all the different Flows. For example by making use of a parent - child Flow construction. Load the environment variable in a parent Flow and the different sync flows as child flows. Pass the value of the environment variable from the parent to the child flows instead of loading it on every single run.

**Comment by NPrice99** [comment]
Hi Rebekka
Have you tried 1.54 and also look at #394 as there is an update how you deploy the updated flows which might help fix the problem.
Regards
Nigel

**Comment by RebekkaAalbers** [comment]
He Nigel,

Thanks. Did not know there was an updated version.
I'll try that one.

**Comment by NPrice99** [comment]
Hi Rebekka

When you update the version please see Jenefer’s note on how the update should be configured. Its on Issue #394.

Hi Nigel. It looks like you are using a stale version of the flow as well. While I know that you have uploaded the new version (1.54) did you chose overwrite on upgrade? It is not the default but without it you wont get the new flows.
The calls to mark the environment as deleted have been moved out to a separate flow in the new versions.
[image]<https://user-images.githubusercontent.com/62659043/88675299-a67feb00-d09f-11ea-86a5-9e115e38c8dc.png>


Regards

Nigel

**Comment by manuelap-msft** [comment]
Rebekka, it's a good idea to update the Sync Flows to use Child Flows. When we originally created them, Child Flows weren't available but architecturally it would make more sense now to use Child Flows rather than triggers. I admit we have had this change as a task on our backlog for a while now but haven't gotten round to doing it yet!

**Comment by RebekkaAalbers** [comment]
> Rebekka, it's a good idea to update the Sync Flows to use Child Flows. When we originally created them, Child Flows weren't available but architecturally it would make more sense now to use Child Flows rather than triggers. I admit we have had this change as a task on our backlog for a while now but haven't gotten round to doing it yet!

@manuelap-msft, maybe I'll spend some free time on this as a community contribution to the CoE Kit. Need to do some other stuff first, though.

**Comment by manuelap-msft** [comment]
@RebekkaAalbers If you could, that would be wonderful - @JeneferM-MSFT has been spending some time on the sync flows in the past week to make them more performant and consume less API calls, for example by exiting the flow at the beginning. Once Jenefer is done, we can provide you with this latest update and you can work from there to make the Child Flow changes.

**Comment by RebekkaAalbers** [comment]
@manuelap-msft, yes please!

**Comment by JeneferM-MSFT** [comment]
Modern Soln import doesnt support child flows yet. We will resolve this for now and return once that experience gets better.
