### ISSUE TITLE
NumericUpDown Value is blank

### ISSUE THREAD

**Issue by MikeGuzowski** [microsoft/powerapps-tools#4]
In NumericUpDown control if user won't click increment/decrement button the NumericUpDown.Value will be blank. 
Fix:
Value (Output) function should be:
If(IsBlank(numValue),NumericUpDown.Default,numValue)

**Comment by jlandgrave** [comment]
![image](https://user-images.githubusercontent.com/4333469/58492300-9f2d1c80-813e-11e9-9299-0794c61098fd.png)
