### ISSUE TITLE
[BUG]: PowerBI Dashboard -  Top App Maker Cities shows Warrington in the USA rather than Warrington England

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#400]
**Describe the bug**
PowerBI Dashboard - The Top App MAker Pane on the Overview - PowerApps Tab Shows Warrington in the USA rather than Warrington in England

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution- Core
 - Version - 1.54
 - PowerBI -  Dashboard-PowerPlatformAdminDashboard_2020-07-07

**To Reproduce**
1. Go to 'the Overview - PowerApp Tab.'
2. See error

**Expected behavior**
Should show Warrington England not Warrington USA

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/88793909-829ed100-d195-11ea-836f-16252992bf32.png)

**Additional context**
![image](https://user-images.githubusercontent.com/8484048/88794332-399b4c80-d196-11ea-8185-18fcbd8f7b22.png)

**Comment by NPrice99** [comment]
Hi Manuela

I followed your instructions and If I right click on the Bing Map I see Column Country, City has a value United Kingdom, Warrington.

But the Bing Map is just of the whole world.

What have I done wrong ?  (I have also set the data category of the Country, City field to “City” as per the article.)

Regards

Nigel

**Comment by manuelap-msft** [comment]
I have had the same, and had to set mine to Place (instead of City) and then it worked. 
![image](https://user-images.githubusercontent.com/55705669/88957279-8ebe8780-d296-11ea-8d18-daf406b83d3a.png)

**Comment by NPrice99** [comment]
Yes, that worked.

**Comment by manuelap-msft** [comment]
Fantastic, thanks for confirming! I'm glad it worked for you, and thanks for reporting an issue that has gone unnoticed for a long time. It'll be included with the next version, too.

**Comment by NPrice99** [comment]
I have one glitch – as well as united kingdom, Warrington I also have “ . “ ie a blank record which now gets plotted on the map in a random place.

**Comment by manuelap-msft** [comment]
If you select the Maker table and then show Data and scroll to the admin_city and admin_country column, do all of your makers listed there have a City and Country? And if one is blank, could you verify if they have a City and Country in their Office 365 Profile - that's where we pull the information from

![image](https://user-images.githubusercontent.com/55705669/88958456-659ef680-d298-11ea-9d08-f05f2bbe66bb.png)

**Comment by NPrice99** [comment]
Hi Manuela

Its their Office 365 which is the problem there is no city or country there in Delve.

Regards

Nigel
