### ISSUE TITLE
[Clarification]: Do App Owners OR employees accessing Apps/Flows of COE environment would be done with O365 with PowerApps license or everyone would require PowerApps per user plan??

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#402]
**Describe the bug**
Do App Owners approving decisions OR employees accessing Apps of COE environment would require premium license? OR all external actions by app owners/employees against COE environment can be done with Office 365 with PowerApps Plan?

**Component (please tell us which flow or app you are experiencing issues with):**
Core Solution
CoE Starter Kit - v2.1
All COE Resources

Hello,

In COE Environment, there are couple of flows that sends an approval emails to App Owners, while couple of apps that are accessible via all employees of the organization, I assume that they can perform their actions without premium license.However can you please clarify on followings:

1. For example, archival approval email for canvas/SP forms can be approved by app owners with Office 365 with PowerApps license? OR they would need PowerApps Per User license? 
2. Similarly is this the same for all external actions what Apps Owners/Employees would execute against COE Environment via COE Apps/Flows?
3. Also, which are those external actions that App Owners/employees have to make against COE Environment in COE Starter Kit? Can you please provide the list if available?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Yes, app maker can perform approvals in the archival process without a license to CDS, so they will be able to approve/reject from the email. 
I dont follow your other questions. But do note that all flows / apps that use CDS require a CDS license to use. 
The only exception to this is approvals, which do use CDS under the covers, but which have been given a license exception.   

Please refer to [Power Platform Licensing FAQ](https://docs.microsoft.com/power-platform/admin/powerapps-flow-licensing-faq) for more details. 

Thanks for using CoE

**Comment by dips23** [comment]
Thank you for the response Jenefer!

I have noticed that user with "Microsoft 365 with PowerApps" Plan, was able to submit the form of "Developer  Compliance Center" App. that updates data in CDS Entity "PowerApps App" - does it mean that, "App Owners" of MPP don't require "PowerApps Per User plan" to update data behind the scene in COE database?

My only concern is, whether to govern the Power Platform via COE Starter Kit, do all App Owners must have "PowerApps Per User Plan" assigned OR "Microsoft 365 with PowerApps" licenses would be enough? 

Thanks and Regards,
Dipti
