### ISSUE TITLE
Admin | Sync Template v2 (Flows) - Create a New record Fails for long SourceType strings

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#403]
**Describe the bug**
Create a new record fails due to validation error, The length of the 'admin_sourcetype' attribute of the 'admin_flowresource' entity exceeded the maximum allowed length of '1000'. Probably need to increase the length. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.54
 - Flow - Sync Template (v2) Flow

**To Reproduce**
Run Admin | Sync V2 Flow 

**Expected behavior**
Successfully run flow

**Screenshots**

![image](https://user-images.githubusercontent.com/59940632/88816307-3ef29a00-d18a-11ea-94a9-2901703d8c95.png)

**Additional context**
{
  "status": 400,
  "message": "A validation error occurred.  The length of the 'admin_sourcetype' attribute of the 'admin_flowresource' entity exceeded the maximum allowed length of '1000'.",
  "error": {
    "message": "A validation error occurred.  The length of the 'admin_sourcetype' attribute of the 'admin_flowresource' entity exceeded the maximum allowed length of '1000'."
  },
  "source": "org12345.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 66870571-019f-4a00-a8cc-87974dcf1139"
}

**Comment by JeneferM-MSFT** [comment]
I've local fixed this and will release with the net version. Thanks for using CoE!

**Comment by manuelap-msft** [comment]
This has been fixed in the release just now, thanks for reporting this!

**Comment by aakashpatel660** [comment]
Hello 

This issue has not been fixed in today release. the issue still appears.
![image](https://user-images.githubusercontent.com/59940632/90439625-d66d4d80-e0a3-11ea-9445-5fb8d38f92cc.png)

**Comment by JeneferM-MSFT** [comment]
Thanks not sure why that change didnt go with the release but I see it at 1000 still as well. 
It will be a while before we release again, so to change it yourself locally, update as shown here
![image](https://user-images.githubusercontent.com/62659043/90443246-cbf58880-e090-11ea-98e7-2b6c313a0dac.png)

**Comment by aakashpatel660** [comment]
Hello 

since it is a managed solution. It does not let me to change the value.

Best Regards,
Akash Patel

**Comment by JeneferM-MSFT** [comment]
oh yep. Re-opening. Will hold and re-resolve with next release

**Comment by JeneferM-MSFT** [comment]
We had to do a release for another bug, and I just upgraded, looks like it shipped this time. 
Thanks for helping make CoE great!
