### ISSUE TITLE
[BUG]: It doesn't allow me to import Flow in Set up governance components

### ISSUE THREAD

**Issue by Sachdesai** [microsoft/powerapps-tools#406]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CenterofExcellenceAuditComponents_1_18_managed
 - Version: 1_18
 - App or Flow: Flow - SharePoint Setup - CreateCoEArchivalDocLibraryinSP

**To Reproduce**

1. Download and import this flow into your CoE environment. To import: Go to https://flow.microsoft.com/ > Select CoE Environment > My Flows > Import
2. Ensure that the flow is turned on, and run it.
3. When the flow is completed, you'll have a document library named PowerAppsArchive.

**Expected behavior**
It should allow to import

**Screenshots**
![image](https://user-images.githubusercontent.com/31678434/89066097-d696ea80-d33a-11ea-90bc-161cf7219836.png)

**Additional context**
Import button is grayed out

**Comment by JeneferM-MSFT** [comment]
Hello. You need to set up the connections. 
Please see [Import/Export Packages](https://flow.microsoft.com/blog/import-export-bap-packages/).

Given that this is not an issue with CoE, I am closing. 
Thanks for using CoE!
