### ISSUE TITLE
Flow “Admin | Sync Template v2 (Power Apps User Shared With)”

### ISSUE THREAD

**Issue by Facun84** [microsoft/powerapps-tools#408]
Hello, 
I’d like to get more detailed information about the Flow “Admin | Sync Template v2 (Power Apps User Shared With)”, such as what is it used for and why does it require the following permissions for the Azure AD connection:

- Group.ReadWrite.All
- User.ReadWrite.All
- Directory.ReadWrite.All

Thanks in advance. Regards,
Facundo.

**Comment by manuelap-msft** [comment]
Hello,

it is used to retrieve information of who an App is shared with. When you look at the App Role Assignments you see individual users and AD groups an app is shared with, but many organisations are interested in the actual number of unique users that have access to an app. For that, we perform a call to get the group information from Azure AD > to get the number of users in that group and give you a true picture of how many unique users an app is shared with.

Hope that helps, and thanks for using CoE!
