### ISSUE TITLE
[Question]: Little issue Audit log data for more than 7 days using auditlogs(MFA)

### ISSUE THREAD

**Issue by Bryand13** [microsoft/powerapps-tools#409]
**Describe the bug**
This is not a bug. My question: Is it possible to search audit logs data for more than 7days using auditlogs(MFA) at once? Or
Can we achieve this goal using auditlog(basic authentication)? We want to achieve this because there was a failured for more than 25 days with the connection created  between the API and the Flow. 

Thanks in advance.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Audit Logs
 - Version 1.0.0.17
 - App or Flow Child] Admin | Sync Log and Admin | Sync Audit Logs

**To Reproduce**

**Expected behavior**
Search auditdata for more than 7 days. 

**Screenshots**
![image](https://user-images.githubusercontent.com/50946094/89317263-6ca17c80-d67d-11ea-9f20-3441219d8d03.png)

**Additional context**

**Comment by manuelap-msft** [comment]
The Office 365 Management API currently does not support this, you can read more about the API this Flow is using and it's limitations here https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#list-available-content

**Comment by Bryand13** [comment]
Hello @manuelap-msft ,
Thank you for your response.

If using the first option exposed here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog "**Option 1: Connect to the audit log by using basic authentication**" has it the same limitation days?

Thanks in advance

**Comment by manuelap-msft** [comment]
Basic Auth does not have the same limitations, and can retrieve Audit events from longer ago (I just tested for a month ago and it worked) however it can only return 200 events at once so you wouldn't be able to pull a month all at once but would have to set up a loop of some sort.

Hope that helps, and thanks for using the CoE Starter Kit!

**Comment by Bryand13** [comment]
ok @manuelap-msft  i'll try out what you say.

Thank you for you help and for answering to my questions.
