### ISSUE TITLE
CoE Starter Kit and API thresholds: Will the Starter Kit work with the new licensing model?

### ISSUE THREAD

**Issue by mschaefer85** [microsoft/powerapps-tools#411]
Dear all,

while monitoring the API calls on my demo tenant where I also have an installation of the CoE Starter Kit running, I noticed the high number of API calls:

![image](https://user-images.githubusercontent.com/10259284/89382109-8339e900-d6fa-11ea-9648-e837169f9a61.png)

MOD Administrator is the user that owns the flows from the Core Components Package.

As you can see, even on my demo tenant with only a handful of users and apps, we're easily over 2,000 API calls per day. In order to be able to run the CoE Starter Kit, I've added a trial Per User Plan which allows me 5,000 API calls per day (refer to: https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)

Still, this number seems far too small when thinking about productive installations where hundreds or thousands of users are active: There will be more to index, more to record.

Does that mean that, with the new licensing model, the CoE Starter Kit won't work?

**Comment by JeneferM-MSFT** [comment]
We have been investigating this. Note that most of our calls are to the CDS which have a [different limit](https://docs.microsoft.com/power-platform/admin/api-request-limits-allocations#non-licensed-usersapplication-usersusers-with-special-free-licenses). 

That said, we'd like to ensure this keeps working. Could you give us the numbers for your non-demo tenant?

**Comment by mschaefer85** [comment]
Thanks for the follow-up!

As I'm in consulting, I do not have a non-demo/ productive tenant, only our clients have. Some of them do have the CoE Starter Kit running, though. I'll align with them concerning the numbers as soon as possible.

**Comment by JeneferM-MSFT** [comment]
From our review of customers, this has not been an issue for people. That said we did just release a streamlining of the sync flows to reduce calls in the event that there isnt data to be found in a particular environment. 
Please return if you find impacted customers. 
Thanks for using CoE!
