### ISSUE TITLE
[BUG] Theme Editor color modification

### ISSUE THREAD

**Issue by Gemita258** [microsoft/powerapps-tools#413]
I have a problem when modifying a color, the alpha component change from integer to float number and when I load the .msapp file into my PowerApp environment, it seems like the RGBA function has 5 components instead of 4 (for example RGBA (234; 256; 234; **1; 0**) instead of RGBA (234; 256; 234; **1**)).
Any solution to this?

Thanks in advance

**Comment by Gemita258** [comment]
![DetailsDatePicker](https://user-images.githubusercontent.com/15980799/89492095-0cabf280-d7b1-11ea-9c57-95710f477cbe.PNG)

**Comment by slaouist** [comment]
Hello, what's the locale you are in ? seems like this issue might be related to the specific locale you are using.

**Comment by Gemita258** [comment]
I'm in Spain. And it's my local configuration. And yes, you're right, it seems that this is the problem. Thanks for your answer
