### ISSUE TITLE
[BUG]: [Child] Admin | Sync Logs Do not recognize Model Driven LaunchApp event

### ISSUE THREAD

**Issue by hradawski** [microsoft/powerapps-tools#416]
We discover that model driven apps has no data in it's Last_Lauched_On column,

We are using the old version on the child flow.

**Comment by JeneferM-MSFT** [comment]
The old Audit Log solution did miss events, you should upgrade (and be sure to use overwrite when you do). 

Can you please further clarify as well, are you saying that none of your Model Driven apps have data in the last launched column? Or just one?

**Comment by hradawski** [comment]
All the modelo deriven apps.



Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by JeneferM-MSFT** [comment]
This works for most people, so there isnt a simple issue here. 
Can you please
1) See if you are missing last lauched for some canvas apps as well
1) Return with screenshots showing how you deduced that all MDA's are missing the data.
1) Upgrade to, and run, the latest audit log solution
1) Be sure to hit overwrite customizations in the upgrade ux
1) Always use matching parent-child, meaning from the same download
1) See if you can find these launches in [the audit log](https://protection.office.com/unifiedauditlog) directly

**Comment by manuelap-msft** [comment]
Actually, Model Driven App launches are not logged in the Office 365 Audit Log at the moment so this is expected behaviour and currently not supported in the product.

**Comment by JeneferM-MSFT** [comment]
Thanks Manuela. 
Sorry for the confusion all
