### ISSUE TITLE
[BUG]: PowerBi Dashboard - key values missing

### ISSUE THREAD

**Issue by Grant-R** [microsoft/powerapps-tools#417]
The Power Bi Dashboard functions by default, no problems there. 

We support a shared tenancy and will need to create filters and publish workspaces displaying limited datasets based on the different business groups.  In attempting to do so, have found that the relationship between the App table and Environment table is defined as below with key values highlighted. 

![image](https://user-images.githubusercontent.com/60246683/89869646-fdd19f80-dbf7-11ea-8793-290c334bfbc1.png)

The key values in the App  table is blank.

In the Starter Kit supplied dashboard, this works fine because values from both tables are not used together in any visualisation but to implement Row Level Security, the relationships have to exist between tables to apply the security across the model. 

Missing key values will produce mixed bag of results.

In this model row level security should be applied on the Environment table because the filtering direction flows outward from the Environment table(please see snapshot of the model below)

But, because the adjoining tables have blank key values, model cannot be filtered across all tables and therefore filtering by agency will not be possible in this model.

Please let me know if you need clarification on this.

**Comment by JeneferM-MSFT** [comment]
Hi Grant. Thanks for the clear description and for using CoE. The sync flows to fill these do work for us and for most people so I wonder if your table got into a confused state at some point. 

Can you please let me know
1) What version of the Core solution are you using? 
1) When you upgraded to this version, did you overwrite customizations? 
1) Are you saying that all rows are blank for that field or only a few? 
1) Do the dashboards seem to work for apps showing the correct apps per environment? 

My advice will likely be to delete all the rows in the apps table and rerun the main sync flow. This will re-populate the apps table, and you wont lose any data other than information about deleted apps.

**Comment by JeneferM-MSFT** [comment]
Hi there, checking in to see if you are able to sort this out now.

**Comment by Grant-R** [comment]
Hi Jenefer

Thanks for checking in.  At this stage, no further investigation is required.

The Power Bi guru who was assisting in customising the dashboard was just using the pbix file rather than connecting it to live data.  I must admit, I took his claims at face value and didn't dig much deeper... I'm still fairly new to Power Bi.   The post on Github was pretty much all from his statement.

I reopened the  pbix file, refreshed the data again and the tables now all have information in them.  Much facepalming did take place.  He hasn't responded to me yet as to whether this solves his dilemmas, but I would assume you can close this one.

Sorry for the inconvenience.

regards
Grant


________________________________

**Comment by JeneferM-MSFT** [comment]
No problem at all Grant. I've done plenty of face palming in my day :)

Thanks for using CoE!
