### ISSUE TITLE
[BUG]: Can't share custom connector Office 365 Management API

### ISSUE THREAD

**Issue by Bryand13** [microsoft/powerapps-tools#418]
**Describe the bug**
Can't share custom connector Office 365 Management API.  I'm not able to click on save button.

Is there anything that we did wrong when the custom connector was imported?

Thank you in advance

**Component (please tell us which flow or app you are experiencing issues with):**
 - Custom connector Office 365 Management API

**To Reproduce**
https://docs.microsoft.com/en-us/connectors/custom-connectors/share
1. Go to Data --> Custom connectors
2. Click on ellipsis button --> Invite another user

**Expected behavior**
Be able to share the custom connector Office 365 Management API

**Screenshots**
![image](https://user-images.githubusercontent.com/50946094/90002322-ce23a580-dc92-11ea-9955-8b4125a0754a.png)

**Additional context**

**Comment by Daleyon** [comment]
@Bryand13 where the custom connector resides (environment), is that environment controlled by an O365 Group / Azure AD security group?

**Comment by Bryand13** [comment]
Hi @Daleyon ,

Thank you for comment.

Yes, the access to the environment where CoE is installed is controlled by a security group. But i don't know if that could be the reason, because we have the custom connector Office 365 Audit Logs also, and I'm able to share it with other users.

Thanks

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid this is outside of the scope of the CoE Toolkit. You'll need to contact customer support for assistance. I will also leave it open here for a few days to see if other users can offer advice. 
Thanks for using CoE!

**Comment by Bryand13** [comment]
Hello @JeneferM-MSFT 

What a pitty! I'll raise a ticket with MSFT support. Please don't close the issue, As you said maybe someone could help us with this matter.

Thanks in advance

**Comment by JeneferM-MSFT** [comment]
Hello, from a colleague: Custom connectors shipped in a solution currently can't be shared, it's a product limitation.

The product team is continuing to shore up solutions, but for now you wont be able to do this. 

Sorry about that, and thanks for using CoE

**Comment by JeneferM-MSFT** [comment]
Closing as the product limitation will not surface a workaround. Thanks for using CoE!

**Comment by Bryand13** [comment]
Hello @JeneferM-MSFT ,

No problema at all. Thank you for letting me know.

Greetings
