### ISSUE TITLE
[BUG]: Problem with Approvals relating to 'Admin | App Archive and Clean Up - Check Approvals and Archive'

### ISSUE THREAD

**Issue by lrarbin** [microsoft/powerapps-tools#419]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
Governence - Version 1.18
 - 'Admin | App Archive and Clean Up - Check Approvals and Archive' and maybe 'Admin | Flow Archive and Clean Up - Check Approvals and Archive'

**To Reproduce**

The 'Admin | App Archive and Clean Up - Check Approvals and Archive' is switched on.

Then there is an error if ANY Approval is attempted e.g. even with the 'Dummy' Test approval.

**Encountered a general permissions error trying to access the CDS database. This could be caused by modification of the approvals administrator or user roles, or by an incompatible plugin.**

**Expected behavior**
For approvals / rejections to work, when the flows are switched on.

There was a ticket with the same issue that has been closed. I don't think this can be a platform issue as I have created the COE on our Tenant in Another environment and have the same issue.

Thanks
Laurence

**Comment by JeneferM-MSFT** [comment]
Hello. Are you saying that you get a permissions error running any flow approval in the CoE environment?

**Comment by lrarbin** [comment]
Yes, but only when 'Admin | App Archive and Clean Up - Check Approvals and Archive' is switch on. If I switch it off, the approval will then work.

**Comment by JeneferM-MSFT** [comment]
We have a local repro of this. Will let you know what we hear.

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE and posting this. The product team made some shifts which require we make some changes too. 
Can you please see if the attached resolves this for you? 
[CenterofExcellenceAuditComponents_1_19_managed.zip](https://github.com/microsoft/powerapps-tools/files/5066164/CenterofExcellenceAuditComponents_1_19_managed.zip)

**Comment by JeneferM-MSFT** [comment]
Sorry someone had added components to the solution I was unaware of. Try this instead. 
[CenterofExcellenceAuditComponents_1_20_managed.zip](https://github.com/microsoft/powerapps-tools/files/5066424/CenterofExcellenceAuditComponents_1_20_managed.zip)

**Comment by lrarbin** [comment]
Thanks, I will try this out and let you know. Do you know if the problem was caused by the rollout of Dataflex?

**Comment by lrarbin** [comment]
I've tested in our environment and that looks like it has resolved the issue:
![image](https://user-images.githubusercontent.com/8376969/90120751-068ab880-dd53-11ea-8619-46894b2c70c8.png)

Thanks for the help
Laurence

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thank you for using CoE!
