### ISSUE TITLE
[BUG] Admin | Flow Archive and Clean Up - Check Approvals and Archive : all runs Failed

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/powerapps-tools#422]
**Describe the bug**
All Flow runs failed with error : Error - Action 'Check_Approval_Status' failed
And for each app the flow failed at the same action with the same error:
_{
  "error": {
    "code": "ConnectionAuthorizationFailed",
    "message": "The caller with object id '2743fc1f-XXXXXXXXXXe87f71a8db2d' does not have permission for connection '6b92544eYYYYYYYYYYY7320' under Api 'shared_logicflows'."
  }
}_

**Component (please tell us which flow or app you are experiencing issues with):**

 - Solution: Governance

 - Issue experimented in versions  1.18 and 1.20 (fix for similar bug : issue [419]([https://github.com/microsoft/powerapps-tools/issues/419]))

 - Admin | Flow Archive and Clean Up - Check Approvals and Archive

**To Reproduce**
1. Start the flow

**Expected behavior**
Approved archiving requests work properly

**Screenshots**
![image](https://user-images.githubusercontent.com/32851166/90083323-32b92180-dce0-11ea-9684-81393157da14.png)

**Additional context**
All others flow is working properly.  The flow "check Deleted" is working fine and use the same connexon.
The user is "global admin" and has all proper licenses

**Comment by JeneferM-MSFT** [comment]
Can you please delete that connector in the flow and re-create?

**Comment by brunoboucher** [comment]
> Can you please delete that connector in the flow and re-create? 

It's the same result. 
But if I create a flow and do a request the connector it's working. Fine. 
It's work correctly in the others flow...

**Comment by JeneferM-MSFT** [comment]
Can you please browse to the connections and show me what it shows? 
Here are mine, yours should look the same except be your identity for the connection:

![image](https://user-images.githubusercontent.com/62659043/90165862-29669e00-dd4e-11ea-9481-604c4a461b91.png)

**Comment by brunoboucher** [comment]
![image](https://user-images.githubusercontent.com/32851166/90177272-4f089d00-dd78-11ea-80f6-10bb5d72c4db.png)

**Comment by brunoboucher** [comment]
there is my connection all the same ;)

**Comment by JeneferM-MSFT** [comment]
ok thanks for the catch. it looks like you dont have access to the flow even though you are an admin. 
I can have the flow add you and then do the fetch. let me get that to you for testing.

**Comment by brunoboucher** [comment]
Now it's seems to work after I installed the fix you gave in the issue 423 [ AppArchival-fixestocheckupflow_20200813192151.zip ]

**Comment by brunoboucher** [comment]
maybe the connection has "been" reset with the update ?

**Comment by JeneferM-MSFT** [comment]
ok great. I added a step to add permissions anyway, in the event someone else hits that. 
thanks for helping me make CoE great!

**Comment by JeneferM-MSFT** [comment]
This has shipped, thanks for helping make CoE great!

**Comment by AhmadiRamin** [comment]
Hi,

We have the same issue:

![image](https://user-images.githubusercontent.com/15119083/99675139-c2543600-2a6e-11eb-8deb-d2174ea238f8.png)

but seems it's the new step you added in the latest release.
