### ISSUE TITLE
[BUG]: Admin | App Archive and Clean Up - Check Approvals and Archive | Errors 404

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/powerapps-tools#423]
**Describe the bug**
For some powerapp si working but for some other flows runs got error 404
{
  "error": {
    "code": 404,
    "source": "unitedstates-002.azure-apim.net",
    "clientRequestId": "48fdf57f-8736-491d-94a3-4cd743d3cc0c",
    "message": "The response is not in a JSON format.",
    "innerError": "Cannot read server response."
  }
}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Governance
 - Version 1.18 and 1.20 (fix for similar bug issue 419)
 - Admin | App Archive and Clean Up - Check Approvals and Archive

**To Reproduce**
1. Run the flow

**Expected behavior**
approved Powerapps  archiving request working properly

**Screenshots**
![image](https://user-images.githubusercontent.com/32851166/90083984-11f1cb80-dce2-11ea-90ca-105d668ca824.png)

**Comment by JeneferM-MSFT** [comment]
1. Does this happen for all the apps you are testing or just some?
1. Does the app which causes the failure still exist or was it removed by the approver? 
1. If you create a separate flow and call for this app, does it return correctly?

**Comment by JeneferM-MSFT** [comment]
I think this is because our new technique allowed for double approvals. Can you try the attached instead? 
This attachment is just the app-checking flow, not the whole solution, so you'll need to import via [flow.microsoft.com](https://flow.microsoft.com/)

[filteroutcompletedapprovals_20200813170933.zip](https://github.com/microsoft/powerapps-tools/files/5070412/filteroutcompletedapprovals_20200813170933.zip)

**Comment by JeneferM-MSFT** [comment]
And here there are with the fix above for double approvals as well as a fix for double deletes:

[AppArchival-fixestocheckupflow_20200813192151.zip](https://github.com/microsoft/powerapps-tools/files/5071030/AppArchival-fixestocheckupflow_20200813192151.zip)
[FlowArchival-fixestocheckupflow_20200813192220.zip](https://github.com/microsoft/powerapps-tools/files/5071032/FlowArchival-fixestocheckupflow_20200813192220.zip)

**Comment by brunoboucher** [comment]
ok i'll install 👍 
1 - filteroutcompletedapprovals
2 - appArchival-fix...
3 - FlowArchiva;-fix

and give you somes news

thanks for your amazing support ! ;)

**Comment by brunoboucher** [comment]
All seems to be fine now
No error on the flow !

thanks

**Comment by JeneferM-MSFT** [comment]
These are now shipped. 
Thanks for helping make CoE great!
