### ISSUE TITLE
[BUG]: Hard coded environment and flowname in Admin | Flow Archive and Clean Up - Check Approvals and Archive

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/powerapps-tools#425]
**Describe the bug**
Msft hard coded data has not been removed before 08/14 release
See screen shot

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Governance
 - Version 1.21
 - Admin | Flow Archive and Clean Up - Check Approvals and Archive

**Screenshots**
![image](https://user-images.githubusercontent.com/32851166/90298616-ed702d80-de60-11ea-9f3a-a1421e8adf4f.png)

**Additional context**
I change the value for get the data frpm the parse json action and it's working

**Comment by JeneferM-MSFT** [comment]
Well that's embarrassing. Thanks for the catch! Here is the flow with that fixed for folks that need it before we release again.
[flowarchivecheck_20200816210502.zip](https://github.com/microsoft/powerapps-tools/files/5081371/flowarchivecheck_20200816210502.zip)

**Comment by manuelap-msft** [comment]
Thanks for highlighting this! We did a release just now to fix this.
