### ISSUE TITLE
Admin | Sync Template v2 (Model Driven Apps)

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#426]
**Describe the bug**
This environment does not exist in my tenant and not sure where it is getting that value. The environment is getting is org534feca0.crm.dynamics.com

{
  "status": 400,
  "message": "Invalid value: org534feca0.crm.dynamics.com provided for data set",
  "error": {
    "message": "Invalid value: org534feca0.crm.dynamics.com provided for data set"
  },
  "source": "commondataservice-eus.azconn-eus.p.azurewebsites.net",
  "debugInfo": "clientRequestId: b8c7a10c-8ab8-43bf-b577-b282bb0c3d89"
}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.60
 - Flow -  Admin | Sync Template v2 (Model Driven Apps)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/90440499-53e58d80-e0a5-11ea-8523-4ce4d0f6f6b7.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
We had a breaking change here. And I believe it should be local fixed now. The change is actually to the driving sync flow: 

> Admin | Sync Template v2

Can you please install the fix and run it? See if your Model Driven Apps work then.  
[AdminSyncTemplatev2_20200817233434.zip](https://github.com/microsoft/powerapps-tools/files/5087300/AdminSyncTemplatev2_20200817233434.zip)

Note that it is a single flow and not a solution and so will need uploaded from the [flow ux](https://flow.microsoft.com/)

**Comment by aakashpatel660** [comment]
Hello

The flow was successfully run. Thank you
