### ISSUE TITLE
Admin | Sync Template v2 (Apps) Created On value throwing RecordcrmDateTime value error

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#427]
**Describe the bug**
When it Get PowerApp Owner Profile and Owner profile is not found it goes throws switch for 404 File not found and upsert App record(Abandoned App). Error is throws is that **DateTime is less than minumum value supported by CrmDateTime. Actual value: 01/01/0001 00:00:00, Minimum value supported: 01/01/1753 00:00:00**. The actual date which needs to enter is "admin_appcreatedon": "2016-10-18T15:49:15.3078305Z",

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.60
 - Flow - Sync Template (v2) (Apps)

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/59940632/90523911-6f02dc80-e13b-11ea-915a-0f0573616f55.png)

**Additional context**
{
  "status": 400,
  "message": "--batchresponse_757e69e8-d10f-4e91-9925-2a859376a0c3\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 400 Bad Request\r\nREQ_ID: 36b592a7-ddf3-4c95-8d35-129c1f3ae306\r\nContent-Type: application/json; odata.metadata=minimal\r\nOData-Version: 4.0\r\n\r\n{\"error\":{\"code\":\"0x80040239\",\"message\":\"DateTime is less than minumum value supported by CrmDateTime. Actual value: 01/01/0001 00:00:00, Minimum value supported: 01/01/1753 00:00:00\",\"innererror\":{\"message\":\"DateTime is less than minumum value supported by CrmDateTime. Actual value: 01/01/0001 00:00:00, Minimum value supported: 01/01/1753 00:00:00\",\"type\":\"System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]\",\"stacktrace\":\"   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Upsert(Entity entity)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Update(Entity entity, UpdateOption updateOption)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.UpdateEdmEntity(CrmODataExecutionContext context, String edmEntityName, String entityKeyValue, EdmEntityObject entityObject)\\r\\n   at Microsoft.Crm.Extensibility.OData.EntityController.PatchEntityImplementation(String& entityName, String key, EdmEntityObject entityDelta)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass10_0`2.<InvokeActionAndLogMetric>b__0()\\r\\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\\r\\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\\r\\n   at lambda_method(Closure , Object , Object[] )\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\"}}}\r\n--batchresponse_757e69e8-d10f-4e91-9925-2a859376a0c3--",
  "error": {
    "message": "--batchresponse_757e69e8-d10f-4e91-9925-2a859376a0c3\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 400 Bad Request\r\nREQ_ID: 36b592a7-ddf3-4c95-8d35-129c1f3ae306\r\nContent-Type: application/json; odata.metadata=minimal\r\nOData-Version: 4.0\r\n\r\n{\"error\":{\"code\":\"0x80040239\",\"message\":\"DateTime is less than minumum value supported by CrmDateTime. Actual value: 01/01/0001 00:00:00, Minimum value supported: 01/01/1753 00:00:00\",\"innererror\":{\"message\":\"DateTime is less than minumum value supported by CrmDateTime. Actual value: 01/01/0001 00:00:00, Minimum value supported: 01/01/1753 00:00:00\",\"type\":\"System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]\",\"stacktrace\":\"   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.Execute(OrganizationRequest request, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, ExecutionContext executionContext, Dictionary`2 optionalParameters)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Upsert(Entity entity)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.Update(Entity entity, UpdateOption updateOption)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.UpdateEdmEntity(CrmODataExecutionContext context, String edmEntityName, String entityKeyValue, EdmEntityObject entityObject)\\r\\n   at Microsoft.Crm.Extensibility.OData.EntityController.PatchEntityImplementation(String& entityName, String key, EdmEntityObject entityDelta)\\r\\n   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass10_0`2.<InvokeActionAndLogMetric>b__0()\\r\\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\\r\\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\\r\\n   at lambda_method(Closure , Object , Object[] )\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\\r\\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\\r\\n--- End of stack trace from previous location where exception was thrown ---\\r\\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\\r\\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\\r\\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\"}}}\r\n--batchresponse_757e69e8-d10f-4e91-9925-2a859376a0c3--\r\n"
  },
  "source": "org529025b60.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 599251d5-6a02-4168-9d0d-cede945c8630"
}

**Comment by JeneferM-MSFT** [comment]
Can you please try to repro outside of the CoE? 

This simplified flow, should do it for you: [testforCreatedTime_20200818153945.zip](https://github.com/microsoft/powerapps-tools/files/5091326/testforCreatedTime_20200818153945.zip)

When you import the flow at [flow.microsoft.com](https://flow.microsoft.com/), you will need to update the identifier (shown in yellow here) to be yours (5bc7...). See if you repro the failure there. 

![image](https://user-images.githubusercontent.com/62659043/90534102-30b2f080-e12e-11ea-836f-164eca365eb7.png)

**Comment by aakashpatel660** [comment]
Hello

I imported the new flow and this is the error i am getting, 

{
  "status": 404,
  "message": "admin_app With Id = 5bc7f435-28dc-42b4-badb-1e4834259db3 Does Not Exist",
  "error": {
    "message": "admin_app With Id = 5bc7f435-28dc-42b4-badb-1e4834259db3 Does Not Exist"
  },
  "source": "org9125ca9b.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 7d2e2b28-1661-4a31-a450-685405bb43c8"
}


Since the error says it cannot find that app then I do not understand why the Admin | Sync Template V2 (App) flow is getting the value from where? 

As you can see below screenshot it is pulling the app information
![image](https://user-images.githubusercontent.com/59940632/90658992-2ec25d80-e212-11ea-9226-cfaa6c19d3c5.png)

Test flow which you provided cannot find that value in PowerApp App entity then how come the Sync Template V2 (App) flow is finding that value?

**Comment by JeneferM-MSFT** [comment]
The CoE starts from the tenant and returns all apps from there. So lets do that instead. I tried to avoid it so that you could get a smaller repro.

Please try with the attached instead
[testforCreatedTime_20200819160147.zip](https://github.com/microsoft/powerapps-tools/files/5097679/testforCreatedTime_20200819160147.zip)

Note that this time you will need to enter the environment name in the spot shown, which can be taken from the trigger in your failing case:
![image](https://user-images.githubusercontent.com/62659043/90660638-0844f800-e1fb-11ea-9252-070b7231bb4a.png)

**Comment by aakashpatel660** [comment]
Hello, 

I have run the new flow which was provided by you and it run successfully. 

![image](https://user-images.githubusercontent.com/59940632/90701246-ec227480-e255-11ea-8a1d-08ca222d38ca.png)

**Comment by JeneferM-MSFT** [comment]
And if you re-trigger the original failure now, from the CoE, does it still reproduce?

**Comment by aakashpatel660** [comment]
It did fix the issue. Thank you so much for your help.

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE!
