### ISSUE TITLE
Cannot turn on Flow "Admin | Sync Audit Logs - 2"

### ISSUE THREAD

**Issue by diegolaz** [microsoft/powerapps-tools#431]
Hello, I followed all the instructions for the CoE starter kit, and now we are on the step "[Import the flow template compressed (.zip) package named SyncAuditLogs.zip](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#import-the-flow-template-compressed-zip-package-named-syncauditlogszip)"

All the steps went well, but on the last part of turning the flow on, it shows the following error:

_Configured data policies prevent activation of flows which use the 'shared_commondataservice' and 'shared_office-20365-20audit-20logs-5f00002899be750755ba--781800000089132' connectors. Visit the Power Automate Admin Center to view applied policies for your organization._
(the GUID numer that is part of the name I changed some letters and numbers)
We found a similar issue [here](https://github.com/microsoft/powerapps-tools/issues/271), but still cant solve it

We checked and there are no connectors listed on the current policy applied with those names, and the common data service are already added.

This is running with a service account that has all the required permissions in Azure AD to get up to this point.

This is also a screenshot from the flow checker that also shows some DLP issues. The flow import run with 0 errors.
![flowChecker](https://user-images.githubusercontent.com/3466466/90827257-513ba000-e312-11ea-92c5-c5fc9e988cf6.PNG)

Are we missing a setting?

Thank you
Diego

**Comment by JeneferM-MSFT** [comment]
Can you please look at the notes on this from this recent issue?
   #429 

Specifically validate that you did steps 7-9, and see if you accidently run the cmdlet twice.

**Comment by JeneferM-MSFT** [comment]
Closing out non-actionable issues. Please let us know if you continue to have issues, and thanks for using CoE!
