### ISSUE TITLE
Is it possible for an administrator to use the CoE starter kit to delete approval requests after a certain period of time?

### ISSUE THREAD

**Issue by tanalove** [microsoft/powerapps-tools#433]
継続実行時間の制限で30日過ぎたものは強制的にワークフローが終了します。
しかし、承認依頼は残り続け[実施項目]-[承認]-[受信済み]の一覧に存在し続けます。
承認や拒否をしてもワークフローは終了しているため、そのあとの処理が継続されず意味のない承認操作となります。

そのため承認依頼を自動で削除する方法を検討しています。

管理者側でCoEスタータキットを利用して、一定期間経過した承認依頼を一括削除するような仕組みは実現できますでしょうか。

なお、弊社ではCommon Data Serviceコネクタが利用できないため、Power Automateなどでの自動削除はできません。

machime translation-------------------------------------------
The duration execution time limit of 30 days will force the workflow to terminate.
However, the approval request remains in the [items to be implemented] - [approval] - [Received] list.
If you approve or reject the workflow, the workflow is terminated and the subsequent process does not continue, resulting in a meaningless approval operation.

Therefore, we are considering how to automatically delete the approval request.

Is it possible for an administrator to use the CoE starter kit to delete approval requests after a certain period of time?

Note that we cannot use the Common Data Service connector, so it cannot be automatically deleted by Power Automate.

**Comment by JeneferM-MSFT** [comment]
My backlog is in reference to the CoE Toolkit backlog, and not the product. 
Thanks again

**Comment by JeneferM-MSFT** [comment]
Closing this out since we arent funding this soon. But have noted this bug to return to you if/when we do the work.
