### ISSUE TITLE
Does the CoE Starter Kit work in GCC?

### ISSUE THREAD

**Issue by dianaberson** [microsoft/powerapps-tools#44]
Has this been reproduced in a GCC tenant? GCC tenants have limitations with Power Platform functionalities. I would like to know if the CoE kit can be installed in a GCC tenant.

**Comment by desmay** [comment]
I agree would be nice to have this solution working for GCC Power Platforms

**Comment by manuelap-msft** [comment]
Currently, the Flow Management connector is not available in GCC so parts of the CoE Kit don't work in GCC yet.

**Comment by manuelap-msft** [comment]
The CoE Starter Kit now works in GCC.

**Comment by nasilvae** [comment]
> The CoE Starter Kit now works in GCC.

Team, does all of the CoE kit work fully in GCC? or do we have parts of it that are not "compliant with gcc tenants" if so which parts are?
