### ISSUE TITLE
[BUG]: Unable to perform 'Transform Data' action to load my environment data

### ISSUE THREAD

**Issue by shilpakyj** [microsoft/powerapps-tools#440]
**Describe the bug**
I'm following as per 'Configure the Power BI dashboard by using the .pbix file' section in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi to perform 'transform data' action in Power BI Desktop, but unable to load my environment. 

When I change the environment URL and click 'close and apply', it is asking me to sign in to my environment and when I give try to do so, it throws the error: "Make sure the web address https://login.microsoftonline.com is correct."
And when i tried to refresh it, got another error: "AADSTS90014: The required field 'request' is missing from the credential. Ensure that you have all the necessary parameters for the login request. "

**To Reproduce**
1. Go to 'Power Bi Desktop'
2. Open the .pbix file provided in the CoE kit
3. Click on 'Transform Data'
4. Change URL to my(in my case) Environment URL
5. click 'close and apply'
6. Environment Sign in Dialogue box opens and credentials are entered
7. See error : Make sure the web address https://login.microsoftonline.com is correct.

**Expected behavior**
Sign in should be successful and my environment data must be loaded
**Screenshots**
![image](https://user-images.githubusercontent.com/58719074/91551405-b7927500-e947-11ea-80a5-502159a7a0e1.png)

After the credentials are given, this error is seen.
![image](https://user-images.githubusercontent.com/58719074/91551539-f4f70280-e947-11ea-9dab-7671a04a63b5.png)

When I click refresh, I get the below error.
![image](https://user-images.githubusercontent.com/58719074/91551591-093aff80-e948-11ea-9eaf-005e3709b39b.png)

**Comment by JeneferM-MSFT** [comment]
Sorry this issue is not an issue with a toolkit, you are having issues using Power BI that are not specific to us. 
If you need support here from Microsoft you will need to use Product Support.
