### ISSUE TITLE
[BUG]: Flow Shared With not Populating

### ISSUE THREAD

**Issue by seanmcev** [microsoft/powerapps-tools#442]
**Describe the bug**
For some reason, no data is being written to the Power Platform User Roles entity for Flows. Thus there is no data populating. I am not sure if this functionality is not released yet because the Shared With for Power Apps works fine. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Components
 - Version [1.60]
 - App or Flow [Admin View Model-Driven App]

**To Reproduce**
1. Go to 'Flows'
2. Click on 'a flow that is shared with other users'
3. Scroll down to 'Flow Shared With (List) Grid'
4. No information is populating

**Expected behavior**
I would expect this to display data just like Power Apps

**Additional context**
The solution came with a Shared with us Flow for Power Apps. It did not come with one for flow so I am unsure if this functionality is released yet.

**Comment by JeneferM-MSFT** [comment]
Correct, this feature is not yet exposed for Power Automate, so we only store it for Power Apps. 
Thanks for using CoE!

**Comment by seanmcev** [comment]
@JeneferM-MSFT Great thank you for confirming!
