### ISSUE TITLE
[Bug]: Cannot use Current Value to set environment variables in CoE, must use Default Values.

### ISSUE THREAD

**Issue by mschaefer85** [microsoft/powerapps-tools#448]
**Describe the bug**
After an update of the Core Components from 1.44 to 1.60 the environment variable "admin_AdminMail" does not seem to have a valid value anymore. Thus, the flow "Admin | Sync Template v2 (Sync Flow Errors)" fails with the following message:

![image](https://user-images.githubusercontent.com/10259284/91995083-aa0a3000-ed37-11ea-8aae-3bd66ed496d9.png)

I can open the variable within the solution, but it shows me an empty value:

![image](https://user-images.githubusercontent.com/10259284/91995205-cefea300-ed37-11ea-95ac-2c79d25a1698.png)

Adding a new current value does not save, no matter how often I click on the button:

![image](https://user-images.githubusercontent.com/10259284/91995280-e89fea80-ed37-11ea-8d6c-ca16f1349ff1.png)

I've seen this thread: https://github.com/microsoft/powerapps-tools/issues/432

Accordingly, I've deleted the line from Excel and was able to set it afterwards to a new value, but then I have the very same behaviour.

It does not work either to directly modify the data value within the CDS entity:

![image](https://user-images.githubusercontent.com/10259284/91995512-31f03a00-ed38-11ea-8564-96c6135fcf87.png)

No matter what I put in there, the flow cannot read the value for "admin_AdminMail".

Any help on that? Currently, this behaviour occurs for a client of ours as well as on our test tenant. The only workaround I see is editing the flow and adding a local variable with the admin's email address.

Thanks a lot!

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 1.60 (updated from 1.44)
 - App or Flow: Admin | Sync Template v2 (Sync Flow Errors)

**To Reproduce**
1. Upgrade from 1.44 to 1.60
2. Execute flow "Admin | Sync Template v2 (Sync Flow Errors)" with sync errors present (i.e. a mail needs to be sent to the admin)
3. See error

**Comment by JeneferM-MSFT** [comment]
You need to set the Default value, not the current value. 
When the flows were made, current values were not yet accessible in flow and so we relied on Default. 
We do have a backlog item to update this but for the near term, you will need to continue setting Default Value.

**Comment by mschaefer85** [comment]
Hello Jenefer,

thanks for your quick reply.

Unfortunately, it is not possible to set the default value. Just as in thread https://github.com/microsoft/powerapps-tools/issues/432 the entry/ the default value does not save.

**Comment by JeneferM-MSFT** [comment]
The UX shown there (still referencing a Current Value) indicates that you did not remove all the current values in the list. 
You can have more than one current value. 
Please go and ensure that you deleted all instances of current values from that table.

**Comment by mschaefer85** [comment]
Sorry, I think I might not have mentioned this in my entry above - I did indeed perform these steps/ the deletion in Excel before, but to no effect.

I'll try again:

1. I delete the row:

![image](https://user-images.githubusercontent.com/10259284/92005850-433f4380-ed44-11ea-8163-ccbef54a8ca9.png)

2. I publish the changes:

![image](https://user-images.githubusercontent.com/10259284/92005902-56521380-ed44-11ea-80d5-8cc7b329a07e.png)

3. I close the workbook and move back to my solutions. I need to set the variable again:

![image](https://user-images.githubusercontent.com/10259284/92005993-7255b500-ed44-11ea-9d4e-ef8f40ee6c93.png)

4. I click on "See environment variable" and add new data:

![image](https://user-images.githubusercontent.com/10259284/92006027-80a3d100-ed44-11ea-840f-bad879277559.png)

![image](https://user-images.githubusercontent.com/10259284/92006055-8b5e6600-ed44-11ea-9c2f-dedc6cf3e039.png)

5. After saving and closing and then reopening the environment variable, I get the same behaviour:

![image](https://user-images.githubusercontent.com/10259284/92006148-a8933480-ed44-11ea-89db-6e34a47b0dde.png)

Am I missing something here?

**Comment by JeneferM-MSFT** [comment]
yes it appears that biz bar now sets the current value instead of the default one. 
Can you please 1-2 again, and then set the default value without using the biz bar ux? 
You can do by opening the default solution for the environment, and set the Type filter to Environment variable.

**Comment by mschaefer85** [comment]
Okay, thanks - I'm trying this:

1. I've deleted the row in Excel.

2. Back in the solution:

![image](https://user-images.githubusercontent.com/10259284/92007432-3e7b8f00-ed46-11ea-93e8-ec4e781db99e.png)

3. Edit is inactive again:

![image](https://user-images.githubusercontent.com/10259284/92007467-4affe780-ed46-11ea-9f33-eca4d599f979.png)

4. Clicking on the variable's name unfortunately gives me the same dialog as before:

![image](https://user-images.githubusercontent.com/10259284/92007517-58b56d00-ed46-11ea-993e-1bf93506493d.png)

**Comment by JeneferM-MSFT** [comment]
Yes but see how it now no longer says something about a current value being removed ? That means it's gone now while you are here. 
Does setting the default in this new state still not work?

**Comment by mschaefer85** [comment]
Yes, there is a difference, indeed - didn't notice that :)

But unfortunately, saving does not do anything:

![image](https://user-images.githubusercontent.com/10259284/92008732-d0d06280-ed47-11ea-8ec3-2309a4fd9256.png)

The dialog does not close.

Cancelling asks me:

![image](https://user-images.githubusercontent.com/10259284/92008786-e0e84200-ed47-11ea-9a20-696b2ffd08bc.png)

So I apparently cannot save that value

**Comment by JeneferM-MSFT** [comment]
I see. Well unfortunately this is a product issue, not an issue with our toolkit. 
And we have exhausted my workarounds which usually fix it. 
You will need to create a ticket with support to engage. Please let me know what you hear.

**Comment by JeneferM-MSFT** [comment]
This should be working now. There was a product bug that has been resolved. Please return to the ticket if you still see this
