### ISSUE TITLE
[BUG]: Error when launching DLP Editor (GetAdminApps failed)

### ISSUE THREAD

**Issue by mschaefer85** [microsoft/powerapps-tools#449]
**Describe the bug**
While opening the DLP Editor an error message for GetAdminApps is displayed after some loading time has passed:

![image](https://user-images.githubusercontent.com/10259284/91997046-f5bdd900-ed39-11ea-9f85-5a61125615d5.png)

This still occured after updating to the latest version.

The number of environments is around 750 - could that be one of the reasons? According to the [limitations](https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#dlp-editor), the DLP editor could handle a lot more, so I guess it's something different.

Any ideas?

Thanks a lot!

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core Components
 - Version: 1.60 (but also occured with 1.44).
 - App or Flow: DLP Editor

**To Reproduce**
1. Open "DLP Editor"
2. Wait a few seconds while it's loading 
3. See error

**Comment by JeneferM-MSFT** [comment]
Can you clarify, 

- Has this app worked for your in the past? 
- If so, are you saying it stopped working and then you tried an upgrade to fix? 
- Have you tried using other admin personas to open the app?

**Comment by JeneferM-MSFT** [comment]
These have been deprecated from the CoE for now. 
Thanks for using CoE!
