### ISSUE TITLE
Issue with Governance Components

### ISSUE THREAD

**Issue by shannonfas** [microsoft/powerapps-tools#451]
**Describe the bug**
Having issues with creating the library and updating environment variables. 

**Component (please tell us which flow or app you are experiencing issues with):**

Archive Site URL (SharePoint Site) 
Archive Folder 
Auto Delete On Archive 
Developer Compliance Center 
Power Platform Admin Security Group

**Comment by JeneferM-MSFT** [comment]
Hello. We'll need more information in order to help you. 

What issue are you seeing with the env var? Please note
1) you need to set the default variale, not the current variable
2) if you are seeing issues trying to save an env var, please look through #448

**Comment by shannonfas** [comment]
I'm not seeing the environment variables at all. I've imported the solution, but can't see the environment variables to save them

**Comment by JeneferM-MSFT** [comment]
Please view the Tip in the [Env Vars section](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-environment-variables)

![image](https://user-images.githubusercontent.com/62659043/92609556-8da45100-f26b-11ea-8802-cb9b059299ee.png)

**Comment by shannonfas** [comment]
Yes - I don't have any of the environment variables.

**Comment by JeneferM-MSFT** [comment]
Did you install Core? Governance relies on Core being installed. 
Can you please show me what you see when you browse to the solution you installed? 
Both when you filter to Env Vars (shown here) and when you filter to flows? 
![image](https://user-images.githubusercontent.com/62659043/92618434-34d9b600-f275-11ea-9f02-ed2790870efb.png)

**Comment by shannonfas** [comment]
It doesn't look like i have installed the Center of Excellence - Governance Components. Here is what i see for Solutions:

![image](https://user-images.githubusercontent.com/70645111/93208338-6b5a7980-f72a-11ea-8625-aa3bf1628584.png)

**Comment by shannonfas** [comment]
Can you please send me a link for the instructions on how to download the govnernance core components? I thought i did that, but i guess not. Thanks

**Comment by shannonfas** [comment]
I found the insturctions and have imported the governance components. I get the update ennvironment variable error. Can you walk me through this?

![image](https://user-images.githubusercontent.com/70645111/93210668-ff7a1000-f72d-11ea-90b6-598ef7d1aa44.png)

**Comment by JeneferM-MSFT** [comment]
In order to update the environment variable, please view the Tip in the [Env Vars section](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#update-environment-variables)

![image](https://user-images.githubusercontent.com/62659043/92609556-8da45100-f26b-11ea-8802-cb9b059299ee.png)

So go to your solutions > Default Solution > and chose your env var. 
Be sure to edit the **default** (not current) variable.

**Comment by JeneferM-MSFT** [comment]
Closing out old issues. Please return if you still see problems here.
