### ISSUE TITLE
[BUG]: Cannot enable Admin | Sync Template V2 due to licence error

### ISSUE THREAD

**Issue by stmccartney** [microsoft/powerapps-tools#452]
**Describe the bug**
I am following the instructions to set up core components, and have got to step 8 of the section [Activate each of these flows](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-each-of-these-flows)
When I click the "Turn On" button I get the following error:
`Your flow could not turn on: Admin | Sync Template v2 - Live. Error: The user 'e3fad9e1-341c-42ca-86a0-ebdbfcd30464' does not have a service plan adequate for the non-Standard connection. https://go.microsoft.com/fwlink/?linkid=2123710`

The account has a Microsoft M365 E3 licence, and the environment has a Power Apps Per App licence assigned to it.  According to the [FAQ](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#faq) this should be sufficient to setup and run the solution.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.6
 - Flow Admin | Sync Template v2

**Comment by JeneferM-MSFT** [comment]
Hi there. Our documentation was a little off, thanks for the catch. 
The per-app license doesn't give you permissions to flows. You'll need a Per Flow or Flow Per User license for that, 

We will update documentation.

**Comment by JeneferM-MSFT** [comment]
This has been resolved in documentation. 
Thanks for using CoE!
