### ISSUE TITLE
Questions about CoE usage

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/powerapps-tools#457]
Question 1:
I deactivate Archivals approvals request trough the app; how can i reactive it ?

Question 2:
How can I restore a flow with his connection from the json files export in the sharepoint librairy when I used Archival flow ?  Import allow only Zip....

Thanks for your help

**Comment by JeneferM-MSFT** [comment]
Hello. We created the following app+flow to recreate archived flows. Please let us know if you have issues using it, as you will be one of the early folks using it: [App and Flow to Re-Create Flow saved during Archive](https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Helper%20Components/AppandFlowtoRe-CreateFlowssavedduringArchive_20200605214049.zip)

Regarding question 1, I dont follow you, can you please show me where you disabled?

**Comment by brunoboucher** [comment]
Print screen Question #1 
![image](https://user-images.githubusercontent.com/32851166/92960987-86806d00-f43c-11ea-9f5c-1e359a678f7f.png)

**Comment by brunoboucher** [comment]
And I have this message box when cliick on Deactive
![image](https://user-images.githubusercontent.com/32851166/92961192-d9f2bb00-f43c-11ea-9c2b-6e8250416b27.png)

**Comment by JeneferM-MSFT** [comment]
It appears you can filter to the innactive ones with this filter ux and then re-enable. 
![image](https://user-images.githubusercontent.com/62659043/92966082-be32e900-f42b-11ea-8e9f-23bb63c53faa.png)

**Comment by brunoboucher** [comment]
Hi Jenefer

Again, thanks for your support !
All Deacticate flow has been reativated and I restore tje flow who has benn archive by mistake !
you can close this issue !

thanks

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thanks for using CoE!
