### ISSUE TITLE
App Entity not showing model driven apps

### ISSUE THREAD

**Issue by KeithWhatling** [microsoft/powerapps-tools#46]
The app entity view "All Apps" does not show all apps only canvas. The filters are Active and not deleted, somewhere the model driven apps must not have this field or its set wrong.

Version used was downloaded today and should be 1/0/0/0

**Comment by manuelap-msft** [comment]
There was an issue with marking Model Driven Apps as deleted. I have fixed this now in the development environment, and it will be published with the next new version (likely next week).

**Comment by manuelap-msft** [comment]
Fixed
