### ISSUE TITLE
[BUG]: Core installation - Flow Save as fails - Power Automate - invalid connection

### ISSUE THREAD

**Issue by b0bbyB** [microsoft/powerapps-tools#465]
**Describe the bug**
When following the guide to install CoE Core and you have to copy/save as the solution flows - 3 flows fails with the connection error "Invalid connection" for the connection "Power Automate Management"

Flows affected:
Admin | Sync Template v2 (Check Deleted)
Admin | Sync Template v2 (Flows)
Admin | Sync Template v2 (Flow Action Details)

User has reported it on forum and found a workaround:
https://powerusers.microsoft.com/t5/Power-Apps-Governance-and/CoE-Starter-Kit-Invalid-connection-when-copying-flows/m-p/645258#M3072

Workaround:
Edit the flow even though you can't save it - find the RED (not yellow/orange) exclamation mark in the flow for connection to Power Automate Management. Click thru them to fix it. Then go back without saving - then press "Save as" now you can save a copy with a fatal connection blocking error

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution CenterofExcellenceCoreComponents_1_60_managed
 - Version 1.60
 - Flows:
Admin | Sync Template v2 (Check Deleted)
Admin | Sync Template v2 (Flows)
Admin | Sync Template v2 (Flow Action Details)

**To Reproduce**
1. Attempt to copy the highlighted flows 

**Expected behavior**
Expected connection to be able to work when pressing save as

**Screenshots**
See URL for screenshot

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Thanks for posting and for using CoE!
We are releasing with the new import experience soon so that will make these issues moot. 
Will let you know when that release is available.

**Comment by manuelap-msft** [comment]
Hello,

we have just released a new version of the kit, that works with the [modern solution import ](https://powerapps.microsoft.com/en-us/blog/announcing-the-new-solution-import-experience-with-connections-and-environment-variables/) experience and won't require you to "save as" the flows anymore as they'll be configured correctly during import. 
The setup instruction in the docs are not updated yet (should happen later today), but if you want to give it a go the new solution is available now to download under [aka.ms/coestarterkitdownload](aka.ms/coestarterkitdownload)

**Comment by b0bbyB** [comment]
Perfect - thank you. I would like to upgrade to test it out - but I'm not sure how to do an upgrade of the existing solution?

**Comment by manuelap-msft** [comment]
You can choose Import and select the new file > once you click next, you can select "Upgrade" as the option for this solution.
