### ISSUE TITLE
[BUG]: Approvals are created in an environment that all users do not have access to.

### ISSUE THREAD

**Issue by StephenCouch** [microsoft/powerapps-tools#466]
**Describe the bug**
Approvals are created in an environment that all users do not have access to.

We have the CoE installed in an environment that we use specifically for management and governance of the Power Platform. The new versions of "App Archive and Clean Up" Flows create the approvals within that environment. 

**Component (please tell us which flow or app you are experiencing issues with):**
App Archive and Clean Up Flows

Is there any recommendation or guidance to get around this other than run the Flows in another environment (which I would rather not).

**Comment by JeneferM-MSFT** [comment]
Users are able to do approvals even when they are not explicit members of an environment. This is an exception/special code that has been made within the product code. 
Note also that you cannot use a Security Group to secure the environment and then use the Approvals flow for users not in that Security Group. 
If you have not used as security group or changed the security settings (note: its ok to add/remove users), then you should be fine.

**Comment by JeneferM-MSFT** [comment]
Closing out old issues. Please return if you still see problems here.
