### ISSUE TITLE
CoE Starter kit Power BI Dashboard is not showing apps and flow data

### ISSUE THREAD

**Issue by ScottHemphill** [microsoft/powerapps-tools#469]
**Describe the bug**
The PowerBI is not populated with current app, flow or connector information

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution  oE PowerBI Dashboard from he CoE Starter kit
 - Version Unknown
 - App or Flow N/A

**To Reproduce**
1. Go to 'Launch the PowerBI Dashboard
2. View the results

**Expected behavior**
I expect to see the current apps, flows and connectors in use
![PowerBIReportCoE](https://user-images.githubusercontent.com/71401789/93375519-e3559c00-f81d-11ea-8840-62af24c562aa.png)

**Screenshots**

**Additional context**

**Comment by ScottHemphill** [comment]
Jenefer, this is my first issue to submit. Can you call me at 713-309-3048?

**Comment by JeneferM-MSFT** [comment]
Hi there. I'm afraid we cannot do support calls for our GitHub customers. 
Let's first validate validate that you have run the sync flows and that data exists in the entities? 

- Go to your version of Admin | Sync Template v2 and look at the run history:
![image](https://user-images.githubusercontent.com/62659043/93385337-fb77ec00-f81a-11ea-8a55-6bc308614965.png)
 
- Then go to Entities > All > Power Apps App
 ![image](https://user-images.githubusercontent.com/62659043/93385478-2e21e480-f81b-11ea-9b81-9649f9aad80e.png)
 
- And once you are in the entity, see if there is data
![image](https://user-images.githubusercontent.com/62659043/93385639-60334680-f81b-11ea-8b70-b106def249bf.png)

**Comment by JeneferM-MSFT** [comment]
Closing out old issues. Please return if you still see problems here.
