### ISSUE TITLE
Setup Instructions INSTALL COMMON DATA SERVICE SOLUTION Unmanaged instead of Managed

### ISSUE THREAD

**Issue by gregdegruy** [microsoft/powerapps-tools#47]
For Step 1 in the Setup instructions found in the https://aka.ms/CoEStarterKitDownload documentation, it's call. "Choose the MANAGED Power Platform solution from the file explorer
(PowerPlatformAdmin_x_x_x_xx_managed.zip)." is incorrectly mentioned.

In order to share the Developer Compliance Center canvas app the unmanaged solution must be imported instead.

Can the documentation be updated to reflect this.

**Comment by manuelap-msft** [comment]
We recommend creating a new UNMANAGED solution, choose components from the CoE starter kit to add to your new solution, you decide which ones you want to use and sharing the app from there.

![image](https://user-images.githubusercontent.com/55705669/72264356-89f3f800-3612-11ea-9553-92be56d750c4.png)

**Comment by hovbiebo** [comment]
Thank you @manuelap-msft i created a new unmanaged solution and added the Developer Compliance Center canvas app. i notice 2 issues
1. when i click on the app, it navigates to a page that never loads until it times out
2. when i click on the ellipses, i only see three options - "Remove", "Add Required Components" and "Show Dependencies"

Any pointers?

![DevCompCenter1_Error](https://user-images.githubusercontent.com/30634365/78068736-8a24a980-735e-11ea-884f-c164d650c050.PNG)
![DevCompCenter2_Error](https://user-images.githubusercontent.com/30634365/78068783-a4f71e00-735e-11ea-9101-822ba3c9d2c7.PNG)

**Comment by manuelap-msft** [comment]
You might have to look at this from the maker portal - make.powerapps.com > Apps, rather than from within the solution.
