### ISSUE TITLE
Issue updating Core Component Solution

### ISSUE THREAD

**Issue by williamtsoicenovus** [microsoft/powerapps-tools#470]
I'm had previously installed Core Component version 1.45. Currently on 2020 Wave 1 CDS. 
I tried to upgrade the Core Component to version 1.6 by doing a import, but it failed. I've upgrade all 3 method, Stage, Upgrade, Update, and it all returned a 80040315 error code. 

Error code
80040315
Exception message
Component with name EnvironmentVariableValue is not enabled for import on this organization.
Total operation time
4 m 16 sec
Patch
No
Managed
Yes
Overwrite customizations
No
Activity id
...

**Comment by manuelap-msft** [comment]
Hello, are you still experiencing this issue? There was a bug with Environment Variables in certain geos/locations that got fixed yesterday. If not, please raise a Service Ticket as this is a product issue and nothing to do with the CoE.
