### ISSUE TITLE
Modern solution import experience, CoE installation

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#471]
The modern solution import experience is available: https://powerapps.microsoft.com/en-us/blog/announcing-the-new-solution-import-experience-with-connections-and-environment-variables/
Is it possible to update the documentation of the CoE? I assume we don't have to do the "Save as" anymore?
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components
Thanks

**Comment by JeneferM-MSFT** [comment]
Hi there. This is something we are actively working on. Note that more than the documentation needs to change though, so we are doing some testing to ensure we will release something solid to you. 
Will let you know when this is ready. 

Thanks for following the product so closely, and for using CoE!

**Comment by JeneferM-MSFT** [comment]
The current documentation and bits now have this complete for most of the CoE components. 
For the ones that do not yet support it, you will still need to go and update the connectors manually while we await changes from the product team to support them. 

Thanks for using CoE!
