### ISSUE TITLE
[BUG]: Office 365 Management API: 401 Using Application Account

### ISSUE THREAD

**Issue by kcouck** [microsoft/powerapps-tools#474]
**Describe the bug**
Reading Audit logs with Application account still uses user credentials

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit
 - Version 1.0.0.17
 - Custom Connector: Operation failed (401)

**To Reproduce**
1. Set up Application account and connector as in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-an-azure-app-registration
Remark: in some places I see "ActivityFeed.Read" and "ServiceHealth.Read" selected for both Application and Delegated permissions; would this make a difference? Doc only states ActivityFeed.Read for Delegated...
2. perform the 'StartSubscription' test (same result for 'ListSubscriptions')
3. Get a 401

Bearer token in the request contains my credentials and not those of the Application Account. (And I don't have access myself -> error?)

**Expected behavior**
Integration using the Application account should work

**Screenshots**
/

**Additional context**
Application account has all required rights as the access to the management API was tested via PowerShell:

`
// Create app of type Web app / API in Azure AD, generate a Client Secret, and update the client id and client secret here
$ClientID = "<client ID>"
$ClientSecret = "<client Secret>"
$loginURL = "https://login.microsoftonline.com/"
$tenantdomain = "<tenant>.onmicrosoft.com"
// Get the tenant GUID from Properties | Directory ID under the Azure Active Directory section. For $resource, use one of these endpoint values based on your subscription plan: Enterprise - manage.office.com; GCC - manage-gcc.office.com; GCC High: manage.office365.us; DoD: manage.protection.apps.mil
$TenantGUID = "<tenant ID>"
$resource = "https://manage.office.com"
// auth
$body = @{grant_type="client_credentials";resource=$resource;client_id=$ClientID;client_secret=$ClientSecret}
$oauth = Invoke-RestMethod -Method Post -Uri $loginURL/$tenantdomain/oauth2/token?api-version=1.0 -Body $body
$headerParams = @{'Authorization'="$($oauth.token_type) $($oauth.access_token)"}

Invoke-WebRequest -Headers $headerParams -Uri "$resource/api/v1.0/$tenantGUID/activity/feed/subscriptions/list"
Invoke-WebRequest -Method Post -Headers $headerParams -Uri "$resource/api/v1.0/$tenantGUID/activity/feed/subscriptions/start?contentType=Audit.General&PublisherIdentifier=$clientID"
Invoke-WebRequest -Headers $headerParams -Uri "$resource/api/v1.0/$tenantGUID/activity/feed/subscriptions/list"
`

Correctly gives
[200] empty list
[200] Audit.general enabled
[200] list with Audit.general

**Comment by JeneferM-MSFT** [comment]
These setting have worked for others so I don't think there is a generalized problem here. 
Can you validate that the end state for the API Permissions are shown as in the set up instructions? 
![image](https://user-images.githubusercontent.com/62659043/94030467-b3088300-fd72-11ea-9274-feef0c0595e3.png)

**Comment by kcouck** [comment]
Indeed, I confirm those are the active settings. As mentioned, when using the API via powershell it works fine.
But when I do the test as described in the docs, the JWT in the request contains my personal credentials and no reference at all to the application account.

**Comment by JeneferM-MSFT** [comment]
Given that you started the subscription in PowerShell, then you should be good to go. 
Are you now able to use the connector in the flow?

**Comment by kcouck** [comment]
I've reverted my changes to the flows and updated the subscription via powershell to use the tenantId, but still the same issue. Not surprising, as the API cannot even get called... (401: Unauthorized)

When you say it works for plenty of other users, is it possible they used the 'user' login or at least have the necessary privileges themselves?
![image](https://user-images.githubusercontent.com/18635525/94053506-b2a3d280-fdda-11ea-9c47-f6abcab2b55d.png)
This is the decoded JWT token sent when doing a 'list subscriptions' test from the Connector config. No mention of my application id; it's a user token. Compare to the JWT generated via powershell:
![image](https://user-images.githubusercontent.com/18635525/94054015-568d7e00-fddb-11ea-8810-74e522f4ab08.png)

Might I have downloaded a faulty version of the connector?

**Comment by kcouck** [comment]
Hi, I managed to get it working...
I updated the Core Components from 1.60 to 1.70.2
I tried to upgrade the AuditLogs Solution from 1.0.0.17 to 1.20, but it failed because I could not link the connector.
I then removed AuditLogs 1.0.0.17 to directly import 1.20. This fails as well because of missing dependencies on 'Active'; it seems like the connector is missing from this solution...
Re-installing 1.0.0.17 and then 1.20 worked, but the upgrade can't be applied (because the connector is missing in 1.20, and so 1.0.0.17 can't be removed, because it would delete the connector)

Anyway, with this setup (Core 1.70.2, AuditLogs 1.0.0.17+1.20) I managed to reconfigure and recreate the connector, and now it is working... Very weird.

So I guess you can consider this issue closed; but I'd have a look at the AuditLogs 1.20 Solution because it's missing stuff that makes it impossible to install on an empty environment...
Thanks for your help :)

**Comment by JeneferM-MSFT** [comment]
The missing connector is due to an issue we just discovered with the modern import. 
Thanks for being so capable! And for using CoE!
