### ISSUE TITLE
[BUG]: [Child] Admin | Sync Logs uses tenantId as PublisherId

### ISSUE THREAD

**Issue by kcouck** [microsoft/powerapps-tools#475]
**Describe the bug**
The [Child] Admin | Sync Logs Flow uses the tenantId parameter to fill the publisherId for the Custom Connector call
This is in conflict with the setup process where it is advised to use the Client Id as Publisher Id

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit
 - Version: 1.0.0.17
 - Flow [Child] Admin | Sync Logs

**To Reproduce**
None

**Expected behavior**
PublisherId is an input parameter for the Child flow and a configurable parameter in Admin | Sync Audit Logs

**Screenshots**
/

**Additional context**
/

**Comment by JeneferM-MSFT** [comment]
Thanks for noticing! I've noted this for us to fix in the future. 
In order to ensure we are on the same page wrt urgency, can you validate that the flow works for you? It appears that the call doesnt actually use the publisher id and that the flow works as is today, but I want to ensure you are seeing the same thing.

**Comment by kcouck** [comment]
I've updated the low myself to add another input parameter and ill it in, but I can't test due to my issue described in #474 
But your remark might explain my problem. I think it's not only not using the publisher id, but doesn't use the application account either

**Comment by JeneferM-MSFT** [comment]
it looks like we're doing this correctly after all, and the naming convention is just sub-par: 
[office 365 management activity api reference](https://docs.microsoft.com/office/office-365-management-api/office-365-management-activity-api-reference)

Pasted from that link, it says the PublisherIdentifier = tenant GUID (and not application/client ID)

**PublisherIdentifier**  The tenant GUID of the vendor coding against   the API. This is not the   application GUID or the GUID of the customer using the application, but the   GUID of the company writing the code. This parameter is used for throttling   the request rate. Make sure this parameter is specified in all issued   requests to get a dedicated quota. All requests received without this   parameter will share the same quota.|

**Comment by kcouck** [comment]
Ok, I guess it suffices to update the documentation for the test then? I don't know if the test step to start the subscription is needed or the further correct execution of the flows?
-> https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-the-audit-log-content

**Comment by JeneferM-MSFT** [comment]
It appears the steps as written do work to start the subscription, I succeed in the test and start using the described steps or with tenantid in both. 
But we have added a backlog item to fully understand and then update them for clarity. 

Your instance of not being able to start seems unique, and we can cover in the other bug. 

Thanks for using CoE!
