### ISSUE TITLE
[BUG]: admin_applastlaunchedon in app entity not populated with data

### ISSUE THREAD

**Issue by rsch136** [microsoft/powerapps-tools#478]
**Describe the bug**
The column admin_applastlaunchedon is not populated with data:
![image](https://user-images.githubusercontent.com/44471683/93855471-dc180d80-fcb7-11ea-8848-2a7446948cdf.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core components v1.60
 - Audit logs v1.0.0.17

**To Reproduce**
1. Updated all components
2. Make sure audit log sync flows run properly
3. Check audit log entity to ensure that it is getting data from audit logs via flow
4. App entity (core components) still blank in column last launched on

**Expected behavior**
Expect some flow (which one?) to update app entity with last launched date once a day

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hi there. The audit log flows are the ones that add this information to the PowerApps entity. As such, it only adds the information for launches it reads, and slowly fills the entity as apps are launched. Over time these fill and apps that are never launched after the audit logs start running will always show empty. 

Does that make sense?

**Comment by rsch136** [comment]
Hi @JeneferM-MSFT ,
Yes, that makes sense. It's also kind of what I assumed about the audit log flows. However, I cannot tell _where_ the flow does this. In my set up no apps have a last launched entry even though there are quite a few entries in the Audit Log entity.
![image](https://user-images.githubusercontent.com/44471683/93894889-87908480-fcef-11ea-8183-958d29f92b11.png)

**Comment by JeneferM-MSFT** [comment]
Here is where the call is. Can you validate that this ran? 
![image](https://user-images.githubusercontent.com/62659043/93912065-18e40480-fcb8-11ea-8762-ed0d4b88666f.png)

**Comment by rsch136** [comment]
I cannot confirm. For some reason the version that we have installed does not look like yours:
![image](https://user-images.githubusercontent.com/44471683/94114032-11ebfc00-fe48-11ea-884b-04e837f60f3c.png)
I just saw that there was an update to the audit log components 3 days ago. Maybe this one includes the flow version you have shown.

**Comment by rsch136** [comment]
I cannot update the audit log components from version 1.0.0.17 to 1.2.
![image](https://user-images.githubusercontent.com/44471683/94115420-faae0e00-fe49-11ea-913a-ff2a9f91ece6.png)

**Comment by JeneferM-MSFT** [comment]
Yes the new audit logs have a dependency on a new feature and we had some issues. You will need to stick with 17, 
However 17 does have the flow as shown by me above. My guess is that you did not overwrite when you did the upgrade and were stuck with the old flow. 
Can you confirm, the name of the flow you are using? I can share the correct version with you here.

**Comment by rsch136** [comment]
They are called "Admin | Sync Audit Logs" and "[Child] Admin | Sync Logs"
Would it help to reinstall v17? (It was my intention to overwrite. Perhaps I misclicked?)
![image](https://user-images.githubusercontent.com/44471683/94402701-a8802c00-016c-11eb-8687-c684962484c1.png)

**Comment by JeneferM-MSFT** [comment]
Here you go: 

[CenterofExcellenceAuditLogs_1_0_0_17_managed.zip](https://github.com/microsoft/powerapps-tools/files/5292726/CenterofExcellenceAuditLogs_1_0_0_17_managed.zip)

**Comment by rsch136** [comment]
@JeneferM-MSFT ,
Importing the solution does not seem to work:
![image](https://user-images.githubusercontent.com/44471683/94686488-2f7b0300-032b-11eb-99ff-837f63293f19.png)
When I click on "import" it just closes the sidebar and does nothing. The flows have also apparently not been modified since I imported them originally:
![image](https://user-images.githubusercontent.com/44471683/94686588-55080c80-032b-11eb-85bb-705d5681476e.png)

**Comment by JeneferM-MSFT** [comment]
Can you see if you can install a previous version as an intermediate step? 
https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/PreviousSolutionVersions

**Comment by rsch136** [comment]
Alright. The issue seems to be that when I install 1.0.0.17 over 1.0.0.7 and select upgrade it does not change the existing [Child] Admin | Sync Logs flow. Will try reverting to earlier version and using update.

**Comment by rsch136** [comment]
I cannot install a previous version as an intermediate:
![image](https://user-images.githubusercontent.com/44471683/94783163-93093d00-03cc-11eb-8413-03daf3442639.png)

**Comment by JeneferM-MSFT** [comment]
can you delete the solution and try to install again?

**Comment by rsch136** [comment]
What will happen if I delete the solution, especially as concerns the custom connector? We currently have the solution installed in two environments (one for testing, one for prod). However, if I delete the solution from testing, how will it deal with the custom connector? I believe both solutions are currently using the same connector and I don't want the productive flows to be interrupted in gathering the data.

**Comment by JeneferM-MSFT** [comment]
Closings items without followup for us. Thanks for using CoE!

**Comment by rsch136** [comment]
@JeneferM-MSFT 
Couldn't respond earlier as I was taking some PTO. Using your workaround I was able to overwrite the solution. This also meant that I had to set up the custom connector again (but I'm getting to be a real pro at that). The new child flow is now as expected. I will see if it works by tomorrow.

**Comment by rsch136** [comment]
Audit log flows now work. Had a little bit of a problem debugging why "blob key" error was causing child to fail. Wrong tenant ID: https://github.com/microsoft/powerapps-tools/issues/546

**Comment by JeneferM-MSFT** [comment]
Thank you and sorry about that blob key issue. We have this addressed in an upcoming release.
