### ISSUE TITLE
Setup Audit Log Sync - Connection to "Office 365 Audit Logs Connection"

### ISSUE THREAD

**Issue by Yocomd** [microsoft/powerapps-tools#48]
I'm trying to import the SyncAuditLogs flow.  I've set up the custom connector and am able to reference it during the import process.  I'm also able to select the connection to the CDS, but I'm at a loss as to the third resource that needs to be connected during the flow import process: It is also called "Office 365 Audit Logs", but is of type "Office 365 Audit Logs Connection" (as opposed to "Connector").  

I'm clearly missing something here, but I have no idea what to do.  I am in GCC, but I don't think that's the problem here?

**Comment by manuelap-msft** [comment]
In the test tab of the connector designer, click on the button to create a new connection. 
Enter the credentials of the user account with access to the audit logs.

This connection should then be available when you import the Flow.

**Comment by Yocomd** [comment]
Thank you for the response.  I have already done what you suggested and the connection created with no issues.  I was able to attach the Flow to that connection during import for the first resource and I was able to add the CDS connection.  It’s the third resource of type “Office 365 Audit Logs Connection (circled in the image below) that I’m not sure about.  Nothing shows up in the list of possible connections and I’m not sure what to create for that connection.

[cid:image003.jpg@01D5AFF2.CD94B8C0]

Diane Yocom
Lead, Digital Workplace - Workflows
SEATTLE INFORMATION TECHNOLOGY
O: 206.684.0612 | diane.yocom@seattle.gov<mailto:diane.yocom@seattle.gov>
Best-in-Class Digital Services
Facebook<https://www.facebook.com/SeattleITDept/> l Twitter<https://twitter.com/SeattleITDept> l E-Newsletter<https://public.govdelivery.com/accounts/WASEATTLE/subscriber/topics?qsp=WASEATTLE_10>

**Comment by manuelap-msft** [comment]
If no connection shows up there, try clicking on + New Connection and then searching for your custom connector and Create a connection to that. This should be selected for the third resource.
![image](https://user-images.githubusercontent.com/55705669/70635187-6876a980-1c2b-11ea-94aa-1489f66912ec.png)

**Comment by Yocomd** [comment]
I already have a connection to my Office 365 Audit Logs custom connector.  It's what I referenced for the first resource and it showed up in the list just fine.  The third resource is looking for something different and no matter how many connections I create to the custom connector, they don't show up in the list because it's looking for an "Office 365 Audit Logs Connection" resource, not a "Connector" resource.  I'm including my picture again because it didn't come through via email:

![Audit Flow Import](https://user-images.githubusercontent.com/58749046/70635681-347a9480-1be9-11ea-867c-ab2445698b17.jpg)

**Comment by manuelap-msft** [comment]
For the first resource, you select the Custom Connector. For the third resource, you select a connection to that Custom Connector.

You can create that by selecting Connections under Data, clicking on New Connection
![image](https://user-images.githubusercontent.com/55705669/70636278-29e1ee80-1c2d-11ea-94dd-7a59acfbe60e.png)

And then searching for audit and selecting the connector that says Custom, if you click on the + it will create a connection for you
![image](https://user-images.githubusercontent.com/55705669/70636343-4847ea00-1c2d-11ea-9453-41d51a7b359f.png)

This is the one you can then select in the Import.

**Comment by Yocomd** [comment]
First, I really appreciate your time on this.
Unfortunately, what you state above is exactly what I've been doing.  I now have 3 connections to the "Office 365 Audit Logs" connector but none of them show up in that list for the third resource.

I feel like I'm missing something obvious, but I've recreated the custom connector and reconnected to them several times.

![image](https://user-images.githubusercontent.com/58749046/70638922-8ffb5100-1bee-11ea-9fd4-268fa1ee5859.png)

**Comment by manuelap-msft** [comment]
That's very strange! I've just imported the Flow into a blank new environment, followed the steps and it showed up.  Have you tried re-importing the Flow again, after setting up the connection?

**Comment by Yocomd** [comment]
I just tried it in our Commercial tenant and it worked just fine.  Not so much in the GCC tenant.  Guess I should have tried that first.  So, no problem with the instructions or with the flow import file...just GCC.

**Comment by manuelap-msft** [comment]
I didn't realize there was a limitation in GCC there for custom connector connection; I will follow up this up internally. 
Also, the Flow Management Connector is not available in GCC yet so there are a few other Flows that are part of the solution that currently don't work in GCC. 
I will add a section to the documentation highlighting the limitations in GCC.

**Comment by Yocomd** [comment]
Yes, I'm waiting to enable the Flow Maintenance flows for GCC.  Hoping for the end of the year!

Thank you again for your time!
