### ISSUE TITLE
[BUG]: Admin | Sync Template v2 RPA Validation

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#480]
**Describe the bug**
Admin_rpa entity is a managed entity so I was not able to increase a length of admin_url column. Please increase a length from 100 to max so we cannot have this issue again. 
A validation error occurred.  The length of the 'admin_url' attribute of the 'admin_rpa' entity exceeded the maximum allowed length of '100'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.70
 - Flow Sync Template (v2) RPA

**To Reproduce**
1. Go to - Admin | Sync Template v2 RPA
2. Click on - Run
3. Scroll down to - Check if made by System -> Switch -> 200 Success -> Upsert a record
4. See error - A validation error occurred.  The length of the 'admin_url' attribute of the 'admin_rpa' entity exceeded the maximum allowed length of '100'.

**Expected behavior**
Successful

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/93891104-0c13e080-fcb9-11ea-8bab-e027bc3c4a31.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Good suggestion, thank you. I have updated this locally and it will release with the next version. 

Thanks for using CoE!

**Comment by aakashpatel660** [comment]
Thank you so much

**Comment by JeneferM-MSFT** [comment]
We have just released the fix in CenterofExcellenceCoreComponents_1_70_1_managed

Thanks for helping make CoE great!

**Comment by aakashpatel660** [comment]
Hello

I am not able to import the solution. Having same issue when you published version 1.70. 
![image](https://user-images.githubusercontent.com/59940632/93930362-3c747280-fceb-11ea-91ef-6e2722f4bbd8.png)
