### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (UI Flow Runs) - environment not found

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#481]
**Describe the bug**
This environment was a trial environment and it got deleted after 30 days and not sure why the UI Flow Runs is looking for a deleted environment? When I go to the Environment entity and look for the trail environment the status says **active**, and the status reason also says **active**. I am guessing that once that environment is deleted it should mark as a deleted not active. 
CRM organization with unique name 'org28743a32' not found.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.70
 - Flow - Sync Template (v2) UI Flow Runs

**To Reproduce**

**Expected behavior**
it should not look for a deleted environment. 

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/93892493-9446b580-fcba-11ea-9a59-680151b08fd9.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hi there. Thanks for letting us know. I repro and am investigating.

**Comment by aakashpatel660** [comment]
Thank you

**Comment by JeneferM-MSFT** [comment]
We have just released the fix in CenterofExcellenceCoreComponents_1_70_1_managed

Thanks for helping make CoE great!
