### ISSUE TITLE
[BUG]: Power BI New File does not open

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#482]
**Describe the bug**
When I open a new version of Power BI it does not let me open. I have the august 2020 version and that is the latest version so not sure why it is still said to get a new version.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/93931057-4fd40d80-fcec-11ea-8b00-bfba5c5e8484.png)

![image](https://user-images.githubusercontent.com/59940632/93931330-a80b0f80-fcec-11ea-988e-80ede64ecddf.png)

**Additional context**

**Comment by manuelap-msft** [comment]
We are using the latest published version from Sep 2020 (2.85.681) 
https://www.microsoft.com/en-us/download/details.aspx?id=58494

**Comment by aakashpatel660** [comment]
can you please explain to me what is this error about. when I looked into this it was asking for an app not sure which app. 

![image](https://user-images.githubusercontent.com/59940632/94035363-f96cda80-fd90-11ea-8c47-b4eeeb9fcbe9.png)

**Comment by JeneferM-MSFT** [comment]
In my experience this type of error comes when the data and the PBI dont match. 
In this case, can you please let me know what version of Core you have setup?

**Comment by aakashpatel660** [comment]
i have 1.70.2 core version

**Comment by manuelap-msft** [comment]
The NonProdNameCheck is a function that is executed per App (from the PowerApps App entity) and can't be evaluated at import. You can select continue here and the data will load.

**Comment by aakashpatel660** [comment]
ok Thank you
