### ISSUE TITLE
[BUG]: Unable to import core solution 1_70_1

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#483]
**Describe the bug**
I am not able to import a new version of the core solution into the environment. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.70.1
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/93935115-2322f480-fcf2-11ea-8b62-94739c33c57e.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

sorry, looks like we had a few glitches today - thanks for bearing with us. Can you try the latest release, I just uploaded a version that should work?

Thank you for the patience
Manuela
