### ISSUE TITLE
[BUG]: Dev sku cases not failing gracefully in Core's sync flows

### ISSUE THREAD

**Issue by brunoboucher** [microsoft/powerapps-tools#486]
**Describe the bug**
When a flow have to perform action in 2 of our environments the action fail.
These environments are Developer environments and we dot not have "admin right" on it

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution 1.6

**To Reproduce**
1. Have a Developer Environment
2. Start Check Deleted flow or sync flow

**Expected behavior**
CoE flows continue after fail on this environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/32851166/94302561-696a9480-ff3a-11ea-8a93-f78c77c2f46d.png)

**Comment by brunoboucher** [comment]
We tried to delete these environments, but they always reappear..a support case has been open with Msft support Team for this

**Comment by JeneferM-MSFT** [comment]
I'm not quite following you here. Are you still looking for help from us or are you covered by the MSFT support? 
If you are looking for help from me, can you please share 

1) Which flow (specifically) is failing, and at which step?

**Comment by brunoboucher** [comment]
Hi Jennifer, all flows are impacted.  If an action have to do an action in these environment the result = FAIL
The screen shot o sent you are from SYNC | FLOW
but the flow check DELETED is failing at "detection" flow step....

**Comment by JeneferM-MSFT** [comment]
I kind of understand now. 
Yes you will need to grant yourself access to environments in order to work with them, however we thought that we had this caught to fail gracefully, so if you can please share a larger screenshot for both the sync | flow case and the check deleted case, then we can see where we need to add more catches. 

I cant tell from the information you have given where in the flow (what action) is failing.

**Comment by brunoboucher** [comment]
sorry about that....let me collect the information correctly ;P  it's will be more useful for you !
I give you some news on monday max !

**Comment by JeneferM-MSFT** [comment]
Hi there. Checking in to see if you have some instances for me here to fix up.

**Comment by JeneferM-MSFT** [comment]
closing issues without follow ups. thanks for using CoE!
