### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Check Deleted) terminates halfway after first error

### ISSUE THREAD

**Issue by RebekkaAalbers** [microsoft/powerapps-tools#488]
**Describe the bug**
The set-up of the Admin | Sync Template v2 (Check Deleted) is that when one action in one of the loops errors out, the whole Flow will be terminated due to the terminate action part of the Error Handling scopes. 
This Flow has high chances of getting errors, because it is looping through all resources in sequential order. 

Funny thing is that the scopes next in line after the Error Handling scopes are configured as run to run in all cases (succes, fail, skip or time out). But since there is a terminate action the Flow will cut short. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.70.2
 - Admin | Sync Template v2 (Check Deleted)

**To Reproduce**

**Expected behavior**
My proposal would be to remove the terminate actions in the error handling scopes, and just let the Flow run it's course. Even if there are some errors in the loops. 

**Screenshots**
![image](https://user-images.githubusercontent.com/30928094/94555882-7fd75f80-025c-11eb-8e85-71857e002962.png)

**Comment by JeneferM-MSFT** [comment]
Thanks Rebekka. I'll make this change in time for the next release.

**Comment by JeneferM-MSFT** [comment]
This is now resolved in the new release of Core. 
Thanks for using CoE and providing such great feedback!

**Comment by RebekkaAalbers** [comment]
Awesome!

Thanks, Jenefer
