### ISSUE TITLE
[BUG]: Import of Solution 1.70.2 CoECoreComponents

### ISSUE THREAD

**Issue by iggsn** [microsoft/powerapps-tools#491]
**Describe the bug**
We try to upgrade the CoE Installation. But we are facing an issue with upgrading the solution from 1.45

**Component (please tell us which flow or app you are experiencing issues with):**
 - CenterOfExcellenceCoreComponents
 - Version 1.45 to upgrade with 1.70.2
 - Entity RPA
- seems like the datatype of the field admin_rpamodifiedon changed from string to datetime
- ErrorMessage in import-log: _Attribute admin_rpamodifiedon is a String, but a DateTime type was specified._

**To Reproduce**

**Expected behavior**
To change the datatype of a field we would need to delete the field first in the target and than recreate it. As it is managed, this is not possible without completely uninstalling the solution and the dependecies.

**Screenshots**
Screenshot is also in bug #483 

**Additional context**
Is there a a solution before, that remove that field? So maybe we just need to update to an earlier version, before we can get to 1.70.2.

**Comment by JeneferM-MSFT** [comment]
I created one for you, based on current bits, which just deleted this field. Can you see if this will work as an intermediate step? 
[CenterofExcellenceCoreComponents_1_45_2_managed.zip](https://github.com/microsoft/powerapps-tools/files/5306677/CenterofExcellenceCoreComponents_1_45_2_managed.zip)

**Comment by iggsn** [comment]
Hi @JeneferM-MSFT,

I try that out and come back to you. Thank your the quick response.

Kind regards,
Lars

**Comment by iggsn** [comment]
Hi @JeneferM-MSFT 
the provided solution did the trick. We will continue to upgrade our CoE instance. Thank you for the quick help.

Kind regards,
Lars

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE!
