### ISSUE TITLE
[BUG]: Admin Sync Flow Error for COE Starter Kit

### ISSUE THREAD

**Issue by tabarret** [microsoft/powerapps-tools#492]
**Describe the bug**
An error occurs in multiple environments for the Admin Sync template which is part of the COE starter kit. When referring to the error details I only get the word "unauthorized" and nothing else really to go on. I checked the connections and they seem fine and won't let me refresh them. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow: Admin Sync Template v2 (Model Driven)

**To Reproduce**
(Event happens somewhat randomly)
**Expected behavior**
Successfully complete the condition Check if Environment has CDS for Apps
 
**Screenshots**
![image](https://user-images.githubusercontent.com/52083755/94733284-838ae500-0335-11eb-99d0-4b1aaf84baca.png)
![image](https://user-images.githubusercontent.com/52083755/94733334-956c8800-0335-11eb-864d-878b1bc190e8.png)
![image](https://user-images.githubusercontent.com/52083755/94733455-cb117100-0335-11eb-9471-b85cc921485c.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. This means that you do not have access to that environment. In order to get the information from the entities which store the data you need access. Add the entity which is running the CoE to those environments.

**Comment by m3ngi3** [comment]
Hi @JeneferM-MSFT, I noticed this same issue even though the account of the Flow is a Power Platform Admin so authorization should not be the issue right?

I noticed that this is happening on Environments created from within the new Project Oakdale / Microsoft Teams experience --> maybe these environments have special settings / restrictions?

**Comment by manuelap-msft** [comment]
Hello! We have just seen this today as well - Project Oakdale / Microsoft Teams environments are restricted in that you can't create model driven apps there so we might have to just fail more elegantly here.

**Comment by JeneferM-MSFT** [comment]
Thanks Manuela. And the rest of you for bringing this to us. I have local fixed this on our side to exit explicitly as a success so you wont have to look again. 

To update your own while you await the release, add the following after the trigger in the RPA/PVA/MDA sync flows:
Where the left side of the conditional is @triggerOutputs()?['body/admin_environmentsku']

![image](https://user-images.githubusercontent.com/62659043/94827091-e2477180-03bc-11eb-8c6d-bfca406911df.png)

**Comment by tabarret** [comment]
Thank you all for your helpful responses. I'll see if I can give it a try myself and can let you know of any updates.

**Comment by tabarret** [comment]
![image](https://user-images.githubusercontent.com/52083755/94851552-9a454080-03f6-11eb-9426-7850f8f949fd.png)
I also have this pop up when I first sign into my admin account and look at the solutions. Could this be contributing to the problem as well?

**Comment by JeneferM-MSFT** [comment]
Hello. I dont think that will be related no. Those are just environment variables you will need for other functionality in the toolkit.

**Comment by dudelis** [comment]
> Hello! We have just seen this today as well - Project Oakdale / Microsoft Teams environments are restricted in that you can't create model driven apps there so we might have to just fail more elegantly here.

Actually, whenever I try to use the CDS connector and get a list of any entities from the Teams Environment, I get 401 Unauthorized. I definitely have all the permissions, cause I am a Global Admin for my tenant.
![image](https://user-images.githubusercontent.com/7166141/95965400-2cdbdb80-0e0a-11eb-9680-8b5bd2930d1a.png)

So this relates not only to Model Driven Apps, but to all Entities?

Is there any MS Docs, where it is explained?

**Comment by manuelap-msft** [comment]
Hello,

the issues in this GitHub repo are related to the CoE Starter Kit, and we can only support you on issues with the kit itself - not with underlying product features. I would suggest you raise a Service Ticket for the behaviour you are seeing.

Here's some Project Oakdale FAQs that might be helpful:
FAQs

https://docs.microsoft.com/en-us/powerapps/teams/overview-data-platform#frequently-asked-questions-faqs

 

Power Platform admin experience:

https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment

 

Governance

https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#ability-to-govern-project-oakdale-in-teams

 

Licensing

https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#project-oakdale

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Initial issue described above is fixed in the latest version of CoE. Thanks for helping make CoE great!
