### ISSUE TITLE
[BUG]: Unable to turn on Governance/Core Flows due to DLP policy violation error

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#493]
Hello,

As a Power Platform Administrator, I am in process of upgrading the COE solution with the latest version "1.70.2"  and as of now I am facing DLP policy error with two flows:

**Core Flow "Admin | Sync Template v2 (Custom Connectors)" Error while activating:**
![image](https://user-images.githubusercontent.com/13658386/94801233-becbf900-03b3-11eb-9069-27225f0e5484.png)

**Governance Flow "Admin | App Archive and Clean Up - Check Approvals and Archive" Error while activating:**
![image](https://user-images.githubusercontent.com/13658386/94801466-14080a80-03b4-11eb-8688-7c54acb88202.png)

I confirm that all required connections are available under Business category for COE Environment. 

Can you please suggest what could be the missing part?

Thank you in advance!
**Note :** I am deploying the solution with Power Platform Admin rights.

Regards,
Dipti

**Comment by dips23** [comment]
In addition, I just got an error for one of the Nurture flow:
![image](https://user-images.githubusercontent.com/13658386/94808790-a4981800-03bf-11eb-8098-d073a89cb2fd.png)

Should I exclude COE Environment out of DLP policies?

Thanks,

**Comment by manuelap-msft** [comment]
Here's a list of all the connectors the CoE Starter Kit uses
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

Please note, you could have more DLP policies applied to the same environment. At design and runtime, all policies that are applicable to the environment in which the app or flow resides are evaluated together to decide whether the resource is in compliance or violation of DLP policies. The most restrictive combination will apply. You can read more about the combined effect of multiple DLP policies here:
https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention#combined-effect-of-multiple-dlp-policies

I would not recommend to exclude the CoE environment from your DLP policy, but rather make sure that your DLP policy includes all connectors needed and ensure that there's no conflicting DLP policy applied to the same  environment.

**Comment by dips23** [comment]
Hi @manuelap-msft 

Thank you for your attention and details about multiple DLP policies, however the COE environment was under single DLP policies that has all the COE connectors under Business Category, however it still has thrown an DLP violation error. I assume if other DLP policies are not considering the COE environment, then those DLP policies would not be applicable to  COE Environment at all? Is my understanding correct?

I have excluded COE environment which was applicable to only single DLP policy, and DLP violation error was removed.

However what is missing is "Power Automate Management" connection access - can this connector be responsible for DLP violation error?

Thank you!

Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

yes, all connectors that the CoE Kit uses have to be in the same group of the DLP Policy (business data only) - for Power Automate, we do have two management connectors: Power Automate Management, and Power Automate for Admins - both of them will have to be in the same group.

For the Admin | Newsletter one you highlighted, this flow uses RSS and Office 365 Outlook together so those two connectors again would have to be in the same category. It looks like we're also missing RSS from the pre-requisites list, so I'll get that added!

Thank you for using the CoE Starter Kit,
Manuela

**Comment by manuelap-msft** [comment]
I double checked our connections, and here's the latest list of connectors that need to be in the business data only bucket of a DLP Policy

The environment must have a DLP policy that allows Common Data Service, Common Data Service (current environment), Office 365 Users, Power Platform for Admins, Power Automate Management, Office 365 Outlook, Power Apps for Admins, Power Apps for Makers, SharePoint, Azure AD, Power Automate for Admins, RSS, Office 365 Groups, Approvals and HTTP to be used together. Those connectors must be in the business data–only bucket of the DLP policy for this environment. If you are using the Audit log solution, the custom connector used to connect to the Microsoft 365 Audit Log also must be included in your business data–only bucket.

**Comment by dips23** [comment]
Thank you very much @manuelap-msft for the clarification!

I see that RSS and HTTP is not in Business data group currently.

I assume that you are referring to "HTTP with Azure AD" connector, if not can you please provide the full name of the HTTP connector?

Also, how to add the "Audit log custom connector" in Business Data category under DLP policy as I do not see "DLP Customizer" app in the upgraded version or I miss something?

Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

the full name is HTTP - here's how that should look:
![image](https://user-images.githubusercontent.com/55705669/94922310-e3a69600-04b1-11eb-950c-1ff339820449.png)

**Comment by manuelap-msft** [comment]
Here's the steps for how to add the custom connector to the DLP policy, you will have to use PowerShell cmdlets for this
https://docs.microsoft.com/en-us/power-platform/guidance/coe/limitations#custom-connectors-and-dlp

**Comment by dips23** [comment]
Gotcha! Thank you very much, highly appreciate the prompt response!

We can close this.Thank you again for your time and help!

Best Regards,
Dipti

**Comment by manuelap-msft** [comment]
Anytime, thanks for using the CoE Starter Kit!
