### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Model Driven Apps)

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#494]
**Describe the bug**
I have 2 new Project Oakdale environments where Im getting the same error in the flow.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.60
 - Flow Sync Template v2 (Model Driven Apps)

**Expected behavior**
This flow is generating an error when running against either Project Oakdale environment.  In both cases I'm seeing an error with the Linked Metadata Unique Name

**Screenshots**
![image](https://user-images.githubusercontent.com/52799471/94820363-02c7f980-03c6-11eb-81da-f979e80d650c.png)
![image](https://user-images.githubusercontent.com/52799471/94820382-08254400-03c6-11eb-8788-1a5a6e55c015.png)
![image](https://user-images.githubusercontent.com/52799471/94820412-0e1b2500-03c6-11eb-9168-be846196a4e3.png)
![image](https://user-images.githubusercontent.com/52799471/94820198-cbf1e380-03c5-11eb-982e-5fb2d4447994.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hi there. Thanks for using CoE!

Per #492 , the product does not currently allow access to teams environments wrt MDAs, PVAs and RPAs. 
Future versions of the toolkit will have this explicitly blocked. 

To update your own while you await the release, add the following after the trigger in the RPA/PVA/MDA sync flows:
Where the left side of the conditional is @triggerOutputs()?['body/admin_environmentsku']

![image](https://user-images.githubusercontent.com/62659043/94827091-e2477180-03bc-11eb-8c6d-bfca406911df.png)

**Comment by dchrist27** [comment]
Jenefer...

If I select Environment Sku from the list of dynamic content I see triggerBody()?['admin_environmentsku'].  I'm still relatively new to Flow so I'm not finding how you set the conditional above.
![image](https://user-images.githubusercontent.com/52799471/95220364-02f83880-07bc-11eb-99b2-09c5bd53580a.png)

**Comment by JeneferM-MSFT** [comment]
I believe you are saying that you believe you selected the correct thing on the left side of the condition, which can be validated by hovering over it as shown
![image](https://user-images.githubusercontent.com/62659043/95221640-801bb180-07ac-11eb-92da-ed46365458d2.png)

Then you just write the string **_Teams_** in the right side of the condition. No quotes or anything around it. Just as shown here. 

That should work. 

Happy you are exploring Power Automate. Its a super powerful and efficient tool once you're good at it :) 
These sync flows utilize so many features, its a great place to explore and learn. 

Please let me know if this works for you.

**Comment by dchrist27** [comment]
OK...so I ran a test against a prior failed run that queried the environment with type Microsoft Team but the condition is coming up false.  Here's the raw data and the EnvironmentSku is not Teams.
![image](https://user-images.githubusercontent.com/52799471/95229260-f973ce00-07c5-11eb-81f7-fed8e607e6cb.png)

**Comment by JeneferM-MSFT** [comment]
It looks like this is due to you using an old API version for the "Get Environment as Admin" call. I hadnt noticed you were still on 1.6 which doesn't have that updated. 

You'll need to either update this in yours or upgrade to 1.7_2

You can see this API version below:
![image](https://user-images.githubusercontent.com/62659043/95231494-10abbf00-07b8-11eb-9ec8-162bb774a90c.png)

**Comment by dchrist27** [comment]
Thanks for pointing this out.    Apologies as it is not obvious to me how to update the API version.   Maybe the difference is because the Power Platform for Admins connector is still in preview?

**Comment by JeneferM-MSFT** [comment]
No need to apologize. It is absolutely not obvious! 
This field is populated in the flow that update the environments themselves: **Admin | Sync Template v2**

Go to that flow, and edit it. 
Expand this scope: **Get Environments and store them in the CoE CDS Entity**
And edit the API Version here to be as follows: **2020-06-01**
![image](https://user-images.githubusercontent.com/62659043/95252898-7d33b780-07d2-11eb-8c65-bd65ace59bed.png)

**Comment by JeneferM-MSFT** [comment]
That said, it might be easiest to just upgrade to the newest Core, as I'm not sure there wont be other issues from a mismatch if you just update here: [aka.ms/CoEStarterKitDownload](http://aka.ms/CoEStarterKitDownload)

**Comment by dchrist27** [comment]
Just updated core to 1.70.2  
![image](https://user-images.githubusercontent.com/52799471/95260254-086e7680-07ee-11eb-99ed-4e811ce9fecc.png)
And while it looks like all the templates were modified
![image](https://user-images.githubusercontent.com/52799471/95260347-2d62e980-07ee-11eb-93d0-e654943e0273.png)

When I go to Admin | Sync Template v2, I see that it still has the old API version.
![image](https://user-images.githubusercontent.com/52799471/95260442-58e5d400-07ee-11eb-97bc-ad04f4697262.png)

**Comment by JeneferM-MSFT** [comment]
Our local setup test from the download correctly shows the new API, so lets make sure your upgrade worked. 
Can you go to the Model Driven Apps flow and validate that you see this scope there. its new this release 
![image](https://user-images.githubusercontent.com/62659043/95265742-af4f1480-07e6-11eb-9ddf-8b69c445c276.png)

**Comment by dchrist27** [comment]
Here's what I see...
![image](https://user-images.githubusercontent.com/52799471/95353421-df4ef400-0888-11eb-8af2-34a89368585c.png)

**Comment by JeneferM-MSFT** [comment]
yep, thats what I thought. your solution did not get overwritten, can you please try again like this:
![image](https://user-images.githubusercontent.com/62659043/95356080-2209cf80-087b-11eb-9dc4-bfea4fbd208f.png)

**Comment by dchrist27** [comment]
I now see the updated flow...
![image](https://user-images.githubusercontent.com/52799471/95358804-132d1800-088f-11eb-9e76-ac21338782c6.png)

But I still see the old API
![image](https://user-images.githubusercontent.com/52799471/95358907-2e982300-088f-11eb-9f2e-02ffa700b7c9.png)

**Comment by dchrist27** [comment]
I just checked the Admin | Sync Template v2 and 'Get Environments' does have the updated API
![image](https://user-images.githubusercontent.com/52799471/95359648-04933080-0890-11eb-911a-7237189f6de9.png)

**Comment by JeneferM-MSFT** [comment]
Good. You can now add that check at the top of the flow and you should be able to catch these cases.
Pasting here again for your convenience: 
![image](https://user-images.githubusercontent.com/62659043/95370894-4c18bd00-088e-11eb-8408-1e5445cbe924.png)

**Comment by dchrist27** [comment]
Just to close the loop on this.  Running core 1.70.2 and adding the check for 'Teams' EnvironmentSku worked and gracefully failed the flow during last night's run.   Thanks again for the help!

**Comment by JeneferM-MSFT** [comment]
Great news, thanks for letting me know. 
I'll leave this open until we release the fix generally. 

Thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
This fix is now released. Thanks for providing feedback to help make CoE great!
