### ISSUE TITLE
[BUG]: DLP violation when trying to active [Child] Admin | Sync Logs flow

### ISSUE THREAD

**Issue by jeffrb** [microsoft/powerapps-tools#495]
**Describe the bug**
When trying to activate the flow "[Child] Admin | Sync Logs" in the solution "Center of Excellence - Audit Logs", a "DlpViolation " error appears, although both the Office 365 management API custom connector and the Common Data Service connector are in the business category of the DLP which is applied to the CoE environnment. I have checked that there is only 1 policy which is applied to the CoE environment, so there is not DLP conflict or overlap.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : Audit Logs
 - Version : 10.0.0.17
 - Flow : [Child] Admin | Sync Logs flow

**To Reproduce**
1. Go to Solutions
2. Click on Center of Excellence - Audit Logs
3. Cick on [Child] Admin | Sync Logs flow
4. Click on Activate
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/72251339/94906229-64f42d80-049e-11eb-848a-a467ef002044.png)

**Comment by manuelap-msft** [comment]
The environment must have a DLP policy that allows Common Data Service, Common Data Service (current environment), Office 365 Users, Power Platform for Admins, Power Automate Management, Office 365 Outlook, Power Apps for Admins, Power Apps for Makers, SharePoint, Azure AD, Power Automate for Admins, RSS, Office 365 Groups, Approvals and HTTP to be used together. Those connectors must be in the business data–only bucket of the DLP policy for this environment. If you are using the Audit log solution, the custom connector used to connect to the Microsoft 365 Audit Log also must be included in your business data–only bucket.

Child flows work via HTTP, so the HTTP connector must also be in your business data-only bucket, see https://github.com/microsoft/powerapps-tools/issues/493#issuecomment-702702755

**Comment by jeffrb** [comment]
Hello Manuela, thank you very much for your reply. I had followed the Microsoft documentation [here](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup), please note that Power Automate for Admins and RSS are **not listed** in the official documentation. So, on Friday I have added them to my policy, now I have the same 16 connectors that you listed (including the custom connector), unfortunately even after patiently waiting for couple of days, I still have the same DlpViolation error when trying to activate the "Child flow". 
I really would appreciate if you have other points I could check.

**Comment by JeneferM-MSFT** [comment]
Adding a note from Manuela on another bug. Can you please see if you have multiple DLP's applied?

**Comment by jeffrb** [comment]
Hello Jenefer, thank you for your message. As I wrote in my initial message, I have checked that there is only 1 policy which is applied to the CoE environment, so there is not DLP conflict or overlap. I have 1 policy dedicated to the CoE, which applies only to its environment, and 1 policy for the other environments, which is configured to apply to all environments except the CoE.

**Comment by manuelap-msft** [comment]
Thanks for pointing out the gap in the documentation, we'll make sure to add the missing connectors!

Child Flows specifically use HTTP in the background, so it's important to add the HTTP connector to your business data group of your DLP policy. Can you confirm the below pictured connector is in your policy?
![image](https://user-images.githubusercontent.com/55705669/95743165-31c55180-0c89-11eb-8e02-006a876d8395.png)

**Comment by jeffrb** [comment]
Hello Manuela, I confirm the HTTP connector is in my policy. I even tried to add all exisiting connectors to the business category, and the same error persists. 
![image](https://user-images.githubusercontent.com/72251339/95860258-1711dc00-0d60-11eb-831b-e83a2d381563.png)

**Comment by manuelap-msft** [comment]
If you have added all connectors to business data, and the error still persists that is a clear indicator that you have a conflicting DLP policy.

If you're an environment admin, a tenant admin might have created a conflicting policy or you might have some policies that apply to "All environments"

**Comment by JeneferM-MSFT** [comment]
I saw this error with a customer yesterday, and for us the settings in Azure were not correct. Can you please view the permissions for the app registration in Azure and see if you match here?: 
![image](https://user-images.githubusercontent.com/62659043/97715253-2a2ae880-1a90-11eb-8b7a-3a81754eda67.png)

And if not, can you please redo the permissions steps from here? 
[https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#create-an-azure-ad-app-registration-for-the-office-365-management-api](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#create-an-azure-ad-app-registration-for-the-office-365-management-api)

**Comment by jeffrb** [comment]
Thank you for your advice. Actually, the permissions are the same as in your screenshot : 
![image](https://user-images.githubusercontent.com/72251339/97865867-2ce54200-1d0b-11eb-9dbb-61b83d7b183d.png)

**Comment by JeneferM-MSFT** [comment]
Thanks for the update. This same customer I mentioned, when they returned to the DLP policy, did not see the custom connector listed anymore, even though they had a success from the PowerShell command in the past. 
Can you double check that the custom connector is in the DLP policy as well?

**Comment by jeffrb** [comment]
Yes the custom connector is in the DLP, although it appears by its technical name, not its display name ("Office 365 Management API"), I don't know if that's expected.
![image](https://user-images.githubusercontent.com/72251339/97995780-41970800-1de7-11eb-8b0f-493e76b8d26a.png)
![image](https://user-images.githubusercontent.com/72251339/97996064-9fc3eb00-1de7-11eb-8ed2-0ada59bb52b8.png)

**Comment by JeneferM-MSFT** [comment]
I'm afraid we are out of ideas here. You may need to just delete the solution and try again from scratch.

**Comment by JeneferM-MSFT** [comment]
Closing out issues without active follow up. 

Thanks for using CoE!
