### ISSUE TITLE
[BUG]: Sync Template flows never get completed

### ISSUE THREAD

**Issue by AhmadiRamin** [microsoft/powerapps-tools#497]
**Describe the bug**
We have installed CoE toolkit but the issue we faced since last week is some of the sync template flows never get succeeded and get stuck on Running status:

![image](https://user-images.githubusercontent.com/15119083/95026191-7c423f00-0687-11eb-8043-2a1fdebbfa37.png)

And it happens everyday! 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core Components
 - Version: 1.70.2
 - App or Flow: CoE - Admin | Sync Template v2 (Flows)

**To Reproduce**
1. Go to Power Automate
2. Run the CoE - Admin | Sync Template v2 (Flows)
3. The status never changed from running

**Expected behavior**
We expect the flow to run successfully not randomly

**Screenshots**
This is what I found with debugging the flow:
![image](https://user-images.githubusercontent.com/15119083/95026344-a9432180-0688-11eb-89d5-488db3c61101.png)

**Comment by JeneferM-MSFT** [comment]
Can you please run this flow to see if this repros outside of the context of the CoE? 
[listflows_20201005214929.zip](https://github.com/microsoft/powerapps-tools/files/5330266/listflows_20201005214929.zip)

You will import the flow (from [flow.microsoft.com](https://flow.microsoft.com/)), update this environment dropdown to be one of those environments that are not finishing, and then run

![image](https://user-images.githubusercontent.com/62659043/95135743-c1af4c80-0719-11eb-9138-a1da6d447b5d.png)

**Comment by AhmadiRamin** [comment]
Hi @JeneferM-MSFT, thank you for your solution, but it's not just about getting list of flows, sometimes they get stuck right at the beginning like this one which has been running for 10 hours now!

![image](https://user-images.githubusercontent.com/15119083/95304946-3f3f9d80-087d-11eb-8be8-e967a5768aef.png)

**Comment by AhmadiRamin** [comment]
Isn't it because flows listed below run at the same time?
	
- Admin | Sync Template v2 (Apps)
- Admin | Sync Template v2 (Connectors)
- Admin | Sync Template v2 (PVA)
- Admin | Sync Template v2 (Model Driven Apps)
- Admin | Sync Template v2 (Custom Connectors)
- Admin | Sync Template v2 (Flows)

Which flow trigger the above flows? is it CoE - Admin | Sync Template v2 flow?
This is really strange why it only happens to the Admin | Sync Template v2 (Flows), do you think add a delay action to the flow can help? so it waits until the other flows are done.

**Comment by AhmadiRamin** [comment]
Just to keep you and others which have the same issue updated, we found out that the "List Existing Connection References" returns about 5200 records which is a lot and that causes so many problems:

![image](https://user-images.githubusercontent.com/15119083/95339748-5053d300-08ac-11eb-89b4-af965eae7a70.png)

Is it ok to increase the Threshold?

**Comment by JeneferM-MSFT** [comment]
It does appear there is something wrong here. So thank you so much for raising this. 
Can you please go to the Connection References entity and get a count of how many entries were made in that table before and after you updated? 
I did this by exporting into Excel and making a pivot table, but you may have another way you like exploring your data.

**Comment by AhmadiRamin** [comment]
@JeneferM-MSFT the count for Connection Reference is 100500  and also the count for the Flow is 3000

**Comment by paulculmsee** [comment]
This issue is due to the enforcement of API limits in flow, meaning many enterprise customers will hit this issue. I have had to port some flows to logicapps as a temporary workaround.

**Comment by paulculmsee** [comment]
@JeneferM-MSFT  I've been looking into this for a few days and what is killing us is the excessive "apply to each" loops when checking what to update in CDS.  

The biggest problem area is the audit log solution, as that can do 200,000 api calls per day with all the child flows. But the daily API limit I believe is 10,000 (actually depends on your license)

**Comment by JeneferM-MSFT** [comment]
Thanks Paul for jumping in to help. Appreciated!
I'm not sure why this would start suddenly though. You and Ahmadi both hit this week, and I just found a test environment repro-ing this week too, and it never did before either. So I suspect there may be a regression somewhere, or a product change I was unaware of.

@AhmadiRamin can you confirm that the connection references have not increased dramatically since update? I see you have 100500 now. How many did you have before you updated? I'm trying to ensure we didnt start writing a bunch of junk references.

**Comment by paulculmsee** [comment]
@JeneferM-MSFT  I can confirm that its a service change to flow... I'll forward you some corro from the MVP dl

**Comment by AhmadiRamin** [comment]
@JeneferM-MSFT We haven't updated the CoE, we used the latest version

**Comment by JeneferM-MSFT** [comment]
I had meant before and after you udpated to the latest solution as it was released recently. 
But its ok, Paul has already pointed me to the likely culprit. So I am investigating.

**Comment by JeneferM-MSFT** [comment]
We are investigating but the fix will take some time. 

In the near term, while we investigate, my recommendation is that you reduce the cadence of the runs to weekly.

1. Open your **_Admin | Sync Template v2_** in Edit
1. Expand the recurrence trigger and hit edit
![image](https://user-images.githubusercontent.com/62659043/95582160-80f45380-09f7-11eb-85f2-7f4a6886153e.png)
1. Change the Frequency to Week, and then optionally you can choose which day you want it to run.
![image](https://user-images.githubusercontent.com/62659043/95582287-aa14e400-09f7-11eb-96eb-386e1ff89152.png)

**Comment by AhmadiRamin** [comment]
I will try to amend the flow, will be any impact on the functionally after making this change?

**Comment by JeneferM-MSFT** [comment]
The only impact is that you will only have data up to date each week instead of each day

**Comment by JeneferM-MSFT** [comment]
Hello we have released an update which we believe will mitigate this quite a bit. You will need to update both Core and Audit logs to get the full benefits. I suggest you turn off the main sync template and let these flows "drain", and then upgrade.

**Comment by AhmadiRamin** [comment]
@JeneferM-MSFT Thank you, such a great news :)

**Comment by AhmadiRamin** [comment]
@JeneferM-MSFT should we install v2.2? that update seems to be released before this issue.

**Comment by JeneferM-MSFT** [comment]
The version of core is 70_6
The version of audit logs is 20

Attaching here for your convenience

[Uploading CoEStarterKit flow never ends fix).zip…]()

**Comment by AhmadiRamin** [comment]
Hi @JeneferM-MSFT , I just want to say thank you, that update solved the issue, now it takes around an hour to get completed:

![image](https://user-images.githubusercontent.com/15119083/97181178-e9328b80-1792-11eb-8dbc-d620948119dd.png)

We can close this now :)
