### ISSUE TITLE
[BUG]: How the "Approval Responses" entity records are collected? 

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#499]
Hello,

As per the flow "Admin | App Archive and Clean Up - Check Approvals and Archive" - It checks approval responses, however "Approval Responses" entity has no single records, even though couple of apps/Flows are rejected/approved by user.

While the "Start Approval" flow updates information in "Archive Approval" - Can you please clarify which entities are being updated, when Archival process is Rejected/Approved?

Thank you in advance!

Regrads,
Dipti

**Comment by JeneferM-MSFT** [comment]
The only custom table used in the workflow is **_Archive Approval_**, the others, including **_Approval Responses_**, are the built in tables created by the product itself to track all approvals, not just those from the CoE. 

The **_Approval Responses_** entity (which is owned by the product itself) has a default filter which isnt useful to us. So my guess is that you do have data there and the default filer is just hiding it. 

Go in and change the view to **All fields** and you should see your data. 
![image](https://user-images.githubusercontent.com/62659043/95232829-dba06c00-07b9-11eb-9ca6-3b23549a2515.png)

**Comment by dips23** [comment]
Thanks Jenefer, My bad, forgot to check with "All Fields"! Thank you!
