### ISSUE TITLE
[BUG]: SETUP DLP Flows are not more in the latest package, is that expected?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#500]
Hello,

In the old version of COE Starter kit, there were following flows which are currently unavailable in the latest version, would you please share if that is expected? Is it recommended to delete manually if latest version is upgraded in the Power Platform Environment?

1. SETUP   REQUIRED | Admin | Find and disable flows that leverage certain connectors
2. SETUP REQUIRED | Admin | Find   and add admins as owners for apps that leverage certain connectors

Kindly clarify!

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Yes these were removed as a product change broke them. We will re-enable them when we are able.

**Comment by dips23** [comment]
Thank you for the confirmation, Can you please share if it's recommended to delete them if installed via previous version? Will deletion affect any other CoE actions in the latest version? 

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Deletion is fine. It will not impact other toolkit objects, and if they are re-enabled they will be re-added in an upcoming solution.

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE!
