### ISSUE TITLE
[BUG]: Feedback Reminder flow Process Understanding!

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#501]
Hello,

The Feedback Reminder flow keeps sending an email for the feedback request, it only checks if event is not today -  how flow knows that feedback is already sent? Can you please clarify?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
This is a bug in the flow. Thanks for catching and letting us know.

Per the action title, this should have been asking for **equal to**
Bug:

- ![image](https://user-images.githubusercontent.com/62659043/95227799-65990680-07b3-11eb-88f0-6ec4e831be0c.png)

I have local fixed it in our local tenant and it will ship with the next release. 
New action:

- ![image](https://user-images.githubusercontent.com/62659043/95227912-882b1f80-07b3-11eb-996e-11e121c93277.png)

**Comment by JeneferM-MSFT** [comment]
This fix is released in the new version of CoE. Thanks for providing great feedback to make CoE great!
