### ISSUE TITLE
[BUG]: Admin | Sync Flow Errors - Email Body Understanding!

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#502]
Hello,

Flow "Admin | Sync Template v2 (Sync Flow Errors)" sends daily email about Sync Errors which indicates, which environment is affected with Sync process, but it does not indicate what error has occurred and why that environment was affected.

Can you please clarify about the Email response details which it sends?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hi Dipti. Thanks for checking in. Here is what you should be seeing in the sync flow mails. The URL points you to the failed run for investigation, where the error message will also be 
![image](https://user-images.githubusercontent.com/62659043/95222732-a9890d00-07ad-11eb-9d69-e5a8bcba16f5.png)

I dont know that we have access to the message programmatically. I would have to investigate.  
Are you aware of a way to get that programmatically? And can you share explicitly what you would like to have in the table instead?

**Comment by dips23** [comment]
Thanks Jenefer, for some reason, I got confused with the environment and URL field, thanks to clarify, It's clear!
