### ISSUE TITLE
[BUG]: Issue with the CDS Default Environment in CoE Starter Kit

### ISSUE THREAD

**Issue by matrixzonee** [microsoft/powerapps-tools#505]
**Describe the bug**
There is a bug in the "Admin | Sync Template v2 (Flows)" Power Automate. Currently, the Power Automate fetched the Environment Name from Environment ID which does not have the "default" prefix in the CDS Default environment. I was able to get the correct name after changing the field to Environment Name Field in the CDS Entity.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [[1.70.2]
 - Flow [Admin | Sync Template v2 (Flows)

**To Reproduce**
1. Go to Power Automate
2. Run the "Admin | Sync Template v2 (Flows)"
3. Open the Environment CDS Entity and the default Environment will have an issue in the same

**Expected behavior**
The expectation was the "Admin | Sync Template v2 (Flows) " Power Automate will be able to fetch all the CDS environment from the Tenant including the default environment, Because of the "default" prefix in the name, the "Admin | Sync Template v2 (Flows) runs failed" Power Automate failed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6177057/95330862-10d3b980-08a1-11eb-85a6-639dd8316873.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hey there. Are you on Core version 1.23? If so, that is quite old. I recall a few months ago that we fixed an issue around this. You will need to update to receive a chunk of fixes we have made.

**Comment by matrixzonee** [comment]
The Core Component Version is 1.70.2
Can you please reopen the bug?

**Comment by matrixzonee** [comment]
> Hey there. Are you on Core version 1.23? If so, that is quite old. I recall a few months ago that we fixed an issue around this. You will need to update to receive a chunk of fixes we have made.

The Core Component Version is 1.70.2
Can you please reopen the bug?

**Comment by JeneferM-MSFT** [comment]
This bug is still open. I closed another one as a dupe to this. 
Thanks for that info, the version information before was probably pointing to gov.

**Comment by JeneferM-MSFT** [comment]
1. Can you please share where you are seeing this error message? Can you please share a screenshot ?

1. In order to validate that your update did an overwrite of the flows, can you please validate that you see this scope in this flow?

- open this flow in Edit **_Admin | Sync Template v2 (Flows)_**
- validate that you see this scope **_Set Env Var - PowerAutomateEnvironmentVariable_**
![image](https://user-images.githubusercontent.com/62659043/95581679-a7fe5580-09f6-11eb-8437-c8a586e79d08.png)

**Comment by JeneferM-MSFT** [comment]
closing issues without follow up on msft side.
thanks for using CoE
