### ISSUE TITLE
[BUG]: All flows turned on after solution import governance components

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#506]
**Describe the bug**
Normally the flows should be off after import. The flows were on after import which caused them to run immediately before we could even define the environment variables to the correct apps for the mails the flow send.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Governance components
 - 1.23
 - Flows

**To Reproduce**
1. Go to CoE environment
2. Click on 'Solutions'
3. Import governance components for the first time
4. See that all flows are turned on immediately.

**Expected behavior**
I expected the flows to be off after import like described in the documentation: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#activate-the-flows

**Comment by JeneferM-MSFT** [comment]
Thanks for the feedback. I'll give it to the product team about the modern import

**Comment by JeneferM-MSFT** [comment]
Hello. This is the design for the new modern import technique. We will update the documentation to match this expectation. 

Thanks for using CoE!

**Comment by WouterF** [comment]
Thanks for the information. It would be better if the modern solution import has an option to turn off/on flows after importing. They can be put it by default "on", but also provide the possibility to turn them off after import...

**Comment by JeneferM-MSFT** [comment]
Yep, the basic idea is that if you have them on when you create the solution, they will be on when you import the solution. 
Thanks for using CoE!
