### ISSUE TITLE
Power BI dashboard in AppSource not up to date

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#513]
Is it possible that the CoE Power BI dashboard in AppSource is not up to date?
I have the latest version from AppSource and don't see the "UI Flows" tab for example...

**Comment by JeneferM-MSFT** [comment]
Correct. App Source version is not up to date. 
We are releasing a new version of a the PBI with a few fixes shortly. I'll respond here for you to download it when ready.

**Comment by JeneferM-MSFT** [comment]
Hello, a new version of the PBI template is available. please utilize, and if you see bugs, please post them.
We will not be keeping the version on AppSource up to date. 
Thanks for using CoE!
