### ISSUE TITLE
[BUG]: PowerBI 7-7-20 vs 9-19-20 report differences 

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#514]
**Describe the bug**
I upgraded to 1.70.2 last week and uploaded the new PowerBI report dated 9-19-20.  I was going to post screenshot differences between the two PowerBI templates but I wanted to make sure this was the correct place.

**Comment by JeneferM-MSFT** [comment]
We are releasing a new version of a the PBI with a few fixes shortly. I'll respond here for you to see if this resolves things for you.

**Comment by JeneferM-MSFT** [comment]
Hello, a new version of the PBI template is available. please utilize, and if you see bugs, please post them.

Thanks for using CoE!
