### ISSUE TITLE
[BUG]: Attribute admin_rpamodifiedon is a String, but a DateTime type was specified upgrade from version 1.60

### ISSUE THREAD

**Issue by macvi** [microsoft/powerapps-tools#515]
Hi @JeneferM-MSFT!
I am experiencing the same issue. My current version is 1.60, I tried installing 1.70 and 1.70.2 with same error message.
Unfortunately I cannot install the version from #491 since it is an earleir version from the one I have.
Many thanks for your help !
Victor

**Comment by JeneferM-MSFT** [comment]
Hello. I will get you this in the next day or so. Apologies for the delay.

**Comment by macvi** [comment]
No worries.
Thanks for your help !

**Comment by JeneferM-MSFT** [comment]
ok here is a version ([CenterofExcellenceCoreComponents_1_60_5_managed.zip](https://github.com/microsoft/powerapps-tools/files/5402140/CenterofExcellenceCoreComponents_1_60_5_managed.zip))
with those fields deleted which you should be able to install and then install current bits (70_6)

**Comment by JeneferM-MSFT** [comment]
I will go ahead and close but please re-open if this does not resolve for you.
Thanks for using CoE!

**Comment by macvi** [comment]
Hi !
The upgrade to 1.60.5 went well, but could not go to 1.70.6
Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.

**Comment by JeneferM-MSFT** [comment]
That field is deleted from 60_5, I have just verified. 
Can you please reinstall 60_5 and force an overwrite with the old ux? 

1) ![image](https://user-images.githubusercontent.com/62659043/97011574-7617e380-150c-11eb-8563-f92ff8a5175e.png)

2) ![image](https://user-images.githubusercontent.com/62659043/97011653-96e03900-150c-11eb-97e9-bca3ea7dd505.png)

3) Chose the file (re-attaching here) > Next > Next
[CenterofExcellenceCoreComponents_RPA_field_interim.zip](https://github.com/microsoft/powerapps-tools/files/5429833/CenterofExcellenceCoreComponents_RPA_field_interim.zip)
 
4) Chose Overwrite and Import
![image](https://user-images.githubusercontent.com/62659043/97012040-0e15cd00-150d-11eb-8d16-1210bc486add.png)

**Comment by macvi** [comment]
Just tried again but still getting the same message.
Note that when I installed the version 1.60.5 I got these warnings:
"The original process has been deactivated and replaced with the process included in this solution."
for 2 processes.

**Comment by JeneferM-MSFT** [comment]
Can you open this flow **_Admin | Sync Template v2 (Apps)_** and see if you see this set of actions? That will let me know if your install worked. 
![image](https://user-images.githubusercontent.com/62659043/97024761-c8f99700-151c-11eb-8acf-1e288db1ceb2.png)

**Comment by macvi** [comment]
Hi @Jenefer !
I can see the flow when going to the solution I installed 1.60.5
You will find here a printscreen

Thanks

**Comment by macvi** [comment]
![image](https://user-images.githubusercontent.com/65469875/97273522-c99f6f80-1833-11eb-8eba-64088c5e71dc.png)

**Comment by macvi** [comment]
Hi @JeneferM-MSFT !
Any luck on this subject ?
Many thanks for your help

**Comment by JeneferM-MSFT** [comment]
I can try one more thing, which will be sending you an interim to try before next weeks update. 
I will respond here at that time.

**Comment by JeneferM-MSFT** [comment]
Please try (via the classic import ux as described above) to import the attached core solution. 
Be sure to select overwrite.
[CenterofExcellenceCoreComponents_1_62_managed.zip](https://github.com/microsoft/powerapps-tools/files/5549319/CenterofExcellenceCoreComponents_1_62_managed.zip)

Once updated, please validate that the admin_rpamodifiedon field is missing from the RPA table

Then upgrade to the latest version of core which can be found at [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

If this does not work, I'm afraid you will need to get help from product support or install in a clean environment. 

Thank you for using CoE

**Comment by macvi** [comment]
Hi @JeneferM-MSFT !
That made the trick !!!
Many thanks for your help !

**Comment by JeneferM-MSFT** [comment]
Wonderful news! Thanks for your patience, and for using CoE!
