### ISSUE TITLE
[BUG]: Unable to "Turn On" flows from the solution

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#517]
Hello,

I have deployed and upgraded latest CoE Starter Kit. When I have deployed the kit, I did not have "Power Automate Management" connector connection fixed, therefore I have saved each and every flow and turn the flow, however it was still "Off" into the solution.

Once the connection for "Power Automate Management" connector was fixed, I was able to "Turn On" flows except followings:

1. Admin | Sync Template v2 (Flow Action Details)
2. Admin | Sync Template v2 (Check Deleted)
3. Admin | Sync Template v2 (Flows)
4. Admin | Flow Archive and Clean Up - Start Approval
5. Admin | Flow Archive and Clean Up - Check Approvals and Archive

All of the above flows are throwing following error when I turn on them from the solution:

**Your flow could not turn on: Admin | Sync Template v2 (Flows). Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller with object id 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX' does not have permission for connection '/providers/Microsoft.PowerApps/apis/shared_flowmanagement/connections/shared-flowmanagemen-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX' under Api 'shared_flowmanagement'."}}".**

Can you please help with the root cause?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hello. For Power Automate management connector, you may have an old connection set to third party still which is deprecated. 
Can you please check and re-create if so via Data > Connections and selecting First Party there 
![image](https://user-images.githubusercontent.com/62659043/95895267-a3fc6b80-0d47-11eb-906a-23e90d279214.png)

Then re-import the solution to set the connection references to the new connection

**Comment by dips23** [comment]
Hi Jenefer,

Unfortunately, I could not re-deploy CoE solution which would eventually clear all custom settings of existing flows in the environment.

Is it possible to perform above change without impacting configurations of existing flows in the environment?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
I believe, since its a connection, you should be able to delete it, and then you'll be prompted to create a connector there, at which point you can select the non-deprecated version.

**Comment by JeneferM-MSFT** [comment]
Closing out issues with no follow ups on our side. Thanks for using CoE!
