### ISSUE TITLE
Flow Archive/App and Clean Up

### ISSUE THREAD

**Issue by ssquiresusps** [microsoft/powerapps-tools#518]
The flows associated with the started kit are erroring and I can't figure out why?

They flows fail in the apply to each environment step

I'm getting a 400 error

Approval Type:   Approve/Reject - Everyone must approve

Body:    {
  "title": "Your app App has been flagged for archiving",
  "assignedTo": "Lyle.D.Albright@usps.gov",
  "details": "\nYou own an app that has not been modified since 28 Aug 2020  and has therefore been flagged for archiving.  Please confirm this app can be archived by approving this task; or provide a business justification if you reject. \n\nApp Name: App\nApp ID: 60512497-67a1-437e-9e88-88753a43a189\nEnvironment: Default-f9aa5788-eb33-4a49-8ad0-76101910cac3\n\nNote: If you select approve, the app will be removed from the PowerApps Maker Portal as a file in the archive, from where it can be restored should you need it again. If you select reject, please re-publish your app to avoid receving this email again. \n",
  "enableNotifications": true,
  "enableReassignment": true
}

Title:  Your app App has been flagged for archiving

Details:  App Name: App
App ID: 60512497-67a1-437e-9e88-88753a43a189
Environment: Default-f9aa5788-eb33-4a49-8ad0-76101910cac3

Note: If you select approve, the app will be removed from the PowerApps Maker Portal as a file in the archive, from where it can be restored should you need it again. If you select reject, please re-publish your app to avoid receving this email again. 

Assigned To:  Lyle.D.Albright@usps.gov

Enable Notifications:  true

Enable Reassignment:  true

Outputs:

Status Code:  400
Headers:
Key                                           Value
Pragma                                      no-cache
x-ms-request-id                        usgovvirginia:71676e55-8e43
x-ms-correlation-request-id     71676e55-8e43-47fc-a66a-38028fc04e12
x-ms-flow-mobile-ios-version  1.3.0
x-ms-flow-routing-request-id  USGOVVIRGINIA:20201012T100215Z:71676e55-8e43-47fc-a66a-38028fc04e12
Strict-Transport-Security           max-age=31536000; includeSubDomains
X-Content-Type-Options          nosniff
Timing-Allow-Origin                 *
x-ms-apihub-cached-response  true
Cache-Control                            no-cache
Date                                           Mon, 12 Oct 2020 10:02:15 GMT
Content-Length                          181
Content-Type                             application/json
Expires                                        -1

Body:  {
  "error": {
    "code": "InvalidApprovalCreateRequestAssignedToNoValidUsers",
    "message": "Required field 'assignedTo' contained no valid users in the organization"
  }
}

If you need to reach me my email is Stephen.J.Squires@usps.gov and phone is (612)386-3479

**Comment by JeneferM-MSFT** [comment]
Can you please validate that you set up this environment variable: Admin eMail
That is the fall back email in the event that the owner email cannot be retrieved.
Current versions of the solution fail explicitly when this is the case instead of deep in the flow as you are seeing.
