### ISSUE TITLE
Flow/App Archive & Clean Up -- Last Updated Clarification

### ISSUE THREAD

**Issue by ssquiresusps** [microsoft/powerapps-tools#520]
Would it be possible to further explain the logic used for these flows?  Documentation states the following:  **New** Archive and Clean Up Apps Flow – Crawls the tenant to check which apps have not been modififed over specified period of time, and sends an approval to owner asking to archive the .msapp file and delete the actual app. This is intended to clean up old test apps or apps that are no longer used.

I'm not understanding why modified date would/should trigger an archive action -- shouldn't it be last accessed/used/shared date?

**Comment by JeneferM-MSFT** [comment]
Hello. Different organizations desire different checks and so we cannot make this pattern match all orgs needs.
I've noted your request and we can consider it for the future. However for now, this is something that you can change yourself in your flow though.

Thanks for using CoE!

**Comment by ssquiresusps** [comment]
Hi Jenefer,  I just wanted to make sure I'm not missing something.  The flows are checking for a last modified date within a time window.   Isn't a characteristic of a well functioning/stable app/flow that it isn't being modified?  Is there more background/information that I'm not considering/missing?   Your explanation doesn't make sense to me and I'm worried I'm missing something.

**Comment by JeneferM-MSFT** [comment]
Hi there. I must admit that if I had created this flow, I would have done the same as you are suggesting, and checked last-used for apps. That said, last used for flows doesn't really help as runs happen without user intervention, and other organizations prefer this methodology. 

The CoE Toolkit is intended to be extended by organizations though, so you should be able to make the change on your end.
