### ISSUE TITLE
[BUG]: Unable to locate the PowerPlatformAdminDashboard.pbit in the download package.

### ISSUE THREAD

**Issue by pab-lydon** [microsoft/powerapps-tools#521]
Unable to locate the PowerPlatformAdminDashboard.pbit in the download package.

**Comment by manuelap-msft** [comment]
The file is called and should be in the zip file:
![image](https://user-images.githubusercontent.com/55705669/95968703-af15d100-0e05-11eb-88ec-20e457309cf6.png)

**Comment by manuelap-msft** [comment]
Closing out old issues with no action on us.
