### ISSUE TITLE
[BUG]: Developer Compliance Center Canvas App

### ISSUE THREAD

**Issue by ssquiresusps** [microsoft/powerapps-tools#522]
**Describe the bug** -- Being directed to commercial versus government tenant

when I click the App Settings image at the top of the screen it is going to the commercial url (https://make.powerapps.com) versus the Government url (https://make.gov.powerapps.us/),

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture] -->  Core
 - Version [e.g. 1.29]  -->  Core 1.60, Nuture 1.15
 - App or Flow [e.g. Sync Template (v2)]  -->  Developer Compliance Center

**To Reproduce**

My organization is in a U.S> Government Tenant as opposed to a commercial tenant.  When I click on the details button for an application and want to update the description there is a note that states:  To add a description:  Go to he App Settings > Edit the Aoo > Settings > Add Description > Save and Publish.  Then return here and click the refresh button below,

The url and query string I'm being redirected to is https://make.powerapps.com/environments/c829e5db-09b8-42ce-986f-8a5dfa176900/apps/8aa35653-ba77-4fac-b2ec-0ad191f832a2/details

I could use help/direction in updating the application/cde information to direct to the proper url and query string.

**Expected behavior**

Expect to directed to government tenant versus commercial tenant

**Screenshots**
Tried to attach using edge browser -- did not work

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

you will have to specify that your Tenant is a GCC or GCC High tenant in the CoE Settings. Open the Power Platform Admin View (model driven app) and specify GCC or GCC High (free text) for Tenant Type. This is documented here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#configure-the-coe-settings-entity

Once your Tenant Type is set accordingly, the URLs in any application will be adjusted to your GCC URLs. The default URLs are the commerical ones, but by updating the Tenant Type this is handled in our apps already. By default, the apps don't "know" your Tenant Type so you have to set this once.

Thanks for using the CoE,
Manuela

**Comment by ssquiresusps** [comment]
![Capture](https://user-images.githubusercontent.com/71052204/96025079-438a2e80-0e1a-11eb-917c-beeeb5da8075.JPG)

**Comment by manuelap-msft** [comment]
The tenant type has to be set to just the word GCC.

**Comment by ssquiresusps** [comment]
When I checked the calie of the Tenant Type I had a ")"https://make.gov.powerapps.us at the end from an improper cut and paste.  I've corrected it but still getting the same behavior as before.

**Comment by manuelap-msft** [comment]
We are using calculated fields in the background to calculate the correct URL based on your input in Tenant Type. This fields can take up to 12 hours to refresh after a change.
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/calculated-rollup-attributes

Could you try and see if you're still seeing the issue tomorrow?

**Comment by ssquiresusps** [comment]
You can close this issue.   Thanks for your help!
