### ISSUE TITLE
[BUG]: Power Platform Admin View - Connectors

### ISSUE THREAD

**Issue by edcartner** [microsoft/powerapps-tools#523]
**Describe the bug**
For flows, the Flow entity shows "Connection References" which identify where you have built a connection. However, no where does it clearly identify what _connectors_ are used within the Flow. You can identify these by going into the Flow Action Details and comparing against the available connectors in the PPAC DLP policy center, but it is not easy to identify. This is important when developing DLP policies, especially for existing environments, to fully understand which flows may be suspended by a new DLP policy. 

Originally, I expected that the Connection References referred to all connectors. Only once a DLP policy suspended flows did I come to understand this referred to connections established with other services (e.g., SharePoint, Outlook). 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - App or Flow: Power Platform Admin View MDA

**To Reproduce**
1. Go to the Flow entity
2. Open any Flow with a mix of connectors that do and do not require a Connection
3. View the Connection References and note that Connections are shown, but not all used connectors
4. Click to Related and choose Flow Action Details
5. See that Action Types include additional Connectors that do not require Connections

**Expected behavior**
I would expect that on the general tab of a Flow I would be able to see all Connectors used, even if they do not require a Connection.

**Screenshots**
![COE1-r](https://user-images.githubusercontent.com/57006335/96029925-8cd97e80-0e18-11eb-9d14-8eec0deae6a4.png)
![COE2](https://user-images.githubusercontent.com/57006335/96029927-8d721500-0e18-11eb-8e92-08df077b69b8.png)
![COE1](https://user-images.githubusercontent.com/57006335/96029929-8d721500-0e18-11eb-98ef-510cb833d7d0.png)

**Additional Details**
The Flow Action Details are actually super helpful. I think it would be helpful if this was accessible via the site map.

**Comment by JeneferM-MSFT** [comment]
I believe what you are asking for is covered in the PowerBI dashboard. If you go to the flows view you can filter by the connector or action there. 
![image](https://user-images.githubusercontent.com/62659043/96129122-78968f80-0eb3-11eb-9474-7ea0f44bc6ad.png)

**Comment by edcartner** [comment]
This appears to be a mix of connectors and actions. Perhaps it isn't a "bug" so much as a feature request to be able to cleanly view the connectors being used by flows, thinking of this specifically as a way to inform DLP policy development. The Actions mixed in make it confusing as many connectors can have similarly named actions. I think it's difficult because connectors don't necessarily have "connections" (e.g., HTTPS) and an action isn't necessarily reflective of a specific connector. 

Please let me know if I'm misunderstanding what is coming through in the dashboard! This came up because we were trying to get a list of all Connectors used in an environment and weren't able to cleanly pull a list.

**Comment by manuelap-msft** [comment]
Is the info you are looking for in the Connections tab, where you can filter by environment? You can then see a list of connectors + apps and flow count and list per connector?

![image](https://user-images.githubusercontent.com/55705669/96137804-00e95480-0ef5-11eb-8d35-92b216899b3a.png)

**Comment by JeneferM-MSFT** [comment]
Following up here to be sure you have what you need. 
Thank you for using CoE!

**Comment by edcartner** [comment]
Sorry! I clearly forgot to respond. This technically gets at it, but would be much more useful in the Admin View MDA so that I can more easily manipulate it myself. When I am looking at the connectors in the MDA none of them are showing up as being used in apps and I don't have the option to see how many flows are using them. Perhaps I am missing something? Thanks, appreciate the help!

**Comment by manuelap-msft** [comment]
Maybe I am still misunderstanding - if so, sorry! 

In the MDA if you select a connector, you should also see apps and flows using the connector. 

![image](https://user-images.githubusercontent.com/55705669/97908171-3fc53a00-1d3e-11eb-8074-eb1e8c2b7fc3.png)

**Comment by JeneferM-MSFT** [comment]
Closing out issues without active follow up. 

Thanks for using CoE!
