### ISSUE TITLE
[BUG]: Trouble Adding Description to Developer Compliance Center Canvas App

### ISSUE THREAD

**Issue by ssquiresusps** [microsoft/powerapps-tools#526]
**Describe the bug**
Adding Description to Developer Compliance Center Canvas App.  Instruction say to click on refresh button below -- however the only button visible is a submit button.   

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture] -->  Nature
 - Version [e.g. 1.29]  --> Core 1.60 Nature 1.15
 - App or Flow [e.g. Sync Template (v2)]  -->   Developer Compliance Center Canvas App

**To Reproduce**
1. Go to Developer Compliance Center
2. Click on '.App Catalog' Details button
3. Description says to go to app settings > edit the app > settings > add description > save and publish > return here and hit refresh
4. See screen attached screen shot

**Expected behavior**
Expect description to be populated as stated above
![Capture1](https://user-images.githubusercontent.com/71052204/96052452-37669700-0e43-11eb-915b-09ba11f5559e.JPG)
![Capture2](https://user-images.githubusercontent.com/71052204/96052482-48afa380-0e43-11eb-8647-923d57e69891.JPG)

**Screenshots**

**Additional context**

**Comment by ssquiresusps** [comment]
![Capture 3](https://user-images.githubusercontent.com/71052204/96053724-aa710d00-0e45-11eb-8539-f123023c2791.JPG)

**Comment by JeneferM-MSFT** [comment]
The save button is to the left of the screenshot you have captured. After you hit save you will be surfaced UX to publish
![image](https://user-images.githubusercontent.com/62659043/96125925-35d3b800-0eb1-11eb-9818-0fc971e36b41.png)

**Comment by JeneferM-MSFT** [comment]
Closing out issues with no follow up on our side. Thanks for using CoE!
