### ISSUE TITLE
[BUG]: Unable to see Model Driven Apps list under "Apps" section in Power BI Dashboard

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#529]
Hello,

As a user with Power Platform Administrator and D365 Admin role assigned, I am unable to see list of "Model Driven Apps" under "Apps" section in Power BI Dashboard. Although I see the number of Model Driven Apps, however when I select "Model Driven App" as "App Type" - list doesn't shows any details of Model Driven Apps of Power Platform Environment! 

![image](https://user-images.githubusercontent.com/13658386/96132693-b18d2f00-0ec8-11eb-9398-c56ca05d09ec.png)

I confirm that all the connections are connected successfully and all the flows ran successfully too.

any clue?

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

can you select the table, open the Visualizations tab and select Last Launched > click on the drop down icon and select (tick) "Show items without data" and see if that shows your apps then?
![image](https://user-images.githubusercontent.com/55705669/96137246-55d89b00-0ef4-11eb-888a-ae6b8327842d.png)

We don't have Last Launched data for model driven apps, only for canvas apps and it looks like this setting was set so that only items with data was showing.

Let me know if that helps and I'll upload a new version so others won't stumble over the same issue!

Thanks for using CoE and making it better with your feedback,
Manuela

**Comment by dips23** [comment]
Hi Manuela,

Surprisingly, I do not see now "Model Driven Apps" option in desktop PBI under "App Type" not sure why!!

![image](https://user-images.githubusercontent.com/13658386/96459948-af8cde00-11f0-11eb-8b40-b542f3e0ad19.png)

Although, I have changed the "Last Launched" option as suggested, that seems to be not changing anything.

Any clue?

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
If you  open the model driven app Power Platform Admin View > Navigate to Apps > Switch the view to Model Driven Apps, does it show you any apps there? 
![image](https://user-images.githubusercontent.com/55705669/96461999-f42e6e80-121c-11eb-9dd9-a70aaa0c7f4e.png)

I'm trying to determine if there's a filter in Power BI preventing the model driven apps from being shown, or if they are not in your inventory.

**Comment by dips23** [comment]
Yes, I can see couple of apps there under Power Platform Admin View > Navigate to Apps > Switch the view to Model Driven Apps.

Looking forward to the solution!

Regards,
Dipti

**Comment by challa85** [comment]
I am also facing the similar issue, not able to view the Model driven apps option for some environments and for some environments it is showing Model Driven app option but not showing any app details in BI report.

**Comment by JeneferM-MSFT** [comment]
Dipti: Can you please share a screenshot of the shift you made per Manuela's suggestion? I just want to be sure it applied to the correct object. 

Challa85: There are some environment types for which we are not able to collect the MDA's due to product limitations. Specifically types Developer and Teams
![image](https://user-images.githubusercontent.com/62659043/97480499-7c99c700-1921-11eb-8046-39781530fcd3.png)

**Comment by challa85** [comment]
Thanks for the update Jenefer, I am looking for the apps which are in sandbox and production environments.

![image](https://user-images.githubusercontent.com/33087528/97540671-fac1a080-19e9-11eb-8a07-5ce3a51da913.png)

The below apps which are visible from admin center are not visible in COE dashboard. I think Center of Excellence - Core Components solution is not able to read the Model driven apps.  

![image](https://user-images.githubusercontent.com/33087528/97541035-7cb1c980-19ea-11eb-86e8-61d13eac81cb.png)

**Comment by JeneferM-MSFT** [comment]
We wont show data in those columns (launches/sessions/users) for MDA's as the product does not offer a way to collect that information. It is for Canvas apps only. 

Did you do this step per Manuela above? 
Select the table object > Last Launched > Show items with no data
![image](https://user-images.githubusercontent.com/62659043/97607780-6f431200-19df-11eb-9c56-7f910f5d3e69.png)

**Comment by challa85** [comment]
Thanks for the update Jenefer, but my issue is that I could not able to see the Model driven apps in Power BI report, where as I can see them in admin center. Is there anything I need to modify in the latest COE starter lit solution.

**Comment by JeneferM-MSFT** [comment]
correct, we think that they are filtered out accidently in the PBI by the filter shown above. Can you try to fix that Last Launched filter and see if you see them?

**Comment by challa85** [comment]
Jenefer, basically I could not able to see the Model driven apps for some environments in Power platform Admin view(The app which comes along with COE starter kit). Do I need to change anything in  Admin | Sync Template v2 (Model Driven Apps) flow.

I assume once we get correct data we can filter in PBI report. So can you please let me know do I need to do any modification in the flow.

**Comment by JeneferM-MSFT** [comment]
ok, that is a seperate issue from this one which is about PBI. Can you please post it separately?

**Comment by JeneferM-MSFT** [comment]
Believe this is resolved now for the reason we arent seeing MDAs in PBI, so closing. If other issues are still needed help with, please raise separately.
