### ISSUE TITLE
[BUG]: What is the quickets way to change the CoE Connection reference with different account?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#532]
Hello,

I have assumed that changing the connection reference for the flows/apps would be executable from the Data > Connections > Connection > Switch Account, however somehow it doesn't change the account reference even though that account has already created connection.

Would you please share what is the quickest way to change the CoE Connection reference with different account? Or do I have to go to each and every flow action and change the connection reference ?

Kindly clarify!

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

if you navigate to make.powerapps.com > Solutions > Default Solution > Set the View to "Connection References (preview)" > select the Connection Reference you want to change > Click Edit > Add New Connection there

![image](https://user-images.githubusercontent.com/55705669/96489182-02898400-1237-11eb-94b7-cab466f3e0ea.png)

You will have to change the connection for each connector used, you can easily identify the CoE connections as they'll all have "CoE" in the name. But this way, it will change the connection in all flows the connection reference is used.

Hope that helps,
Manuela

**Comment by dips23** [comment]
Thanks Manuela for your time and help on this!

Consider CoE Starter kit is deployed by "MPP Admin 1" and I require to chnage the all CoE Connection references with "MPP Admin 2"

Earlier, "MPP Admin 1" tried changing the connection reference from the "CoE Solution" and not the default solution as you have suggested, now from the default solution, "MPP Admin 2" was able to update the connection reference, However all the apps and flows are still referring to  "MPP Admin 1" connection references.

While by logging with "MPP Admin 1", "MPP Admin 1" can not change the connection reference referring to "MPP Admin 2" !!

Therefore, currently, It looks like, it's a manual process to change the default connection reference for all CoE flows/apps, I will wait another 1/2 hour to reflect the connection reference as per the latest change, however it still looks like the same - Can you please share what I would be missing?

Regards,
Dipti

**Comment by dips23** [comment]
I confirm, It did not change the default connection reference of the existing flow ( It only adds new connections created by "MPP Admin 2"), so user "MPP Admin 2" has to go ahead and change the connection references for each flow actions manually! :(

**Comment by manuelap-msft** [comment]
Thanks for letting me know. Let me investigate this behaviour with the Engineering Team looking after Connection References!

**Comment by JeneferM-MSFT** [comment]
Hello, the above is the current recommendation. If this doesnt work, please let the product team know via a ticket. 
Thanks for using CoE
