### ISSUE TITLE
[BUG]: Unable to get activity reports in custom Audit Log Search connector

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#533]
Hello,

As explained here - https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-basic-authentication,  User "MPP Admin 1" ( Power Platform Admin Role + D365 Admin Role ) is trying to configure custom connector, however "GetActivitiesByOperation " is throwing an error:

![image](https://user-images.githubusercontent.com/13658386/96560047-c46a7f80-128b-11eb-99fe-9612562fa42f.png)

![image](https://user-images.githubusercontent.com/13658386/96560110-d815e600-128b-11eb-8b38-400d30cc7618.png)

I assume user "MPP Admin 1" requires Audit Log Search Role assigned from "Exchange Online Admin" - is that correct?

Can you please clarify?

Thanks and Regards,
Dipti

**Comment by dips23** [comment]
I confirm that user  "MPP Admin 1"  able to view Audit log reports in Office 365 here - https://protection.office.com/unifiedauditlog 

Even though, same user is facing connection issue!

Any update?

Thanks,

**Comment by dips23** [comment]
Hello, 

Just to check if there is any update on this bug?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Have you already validated the items from the [setup instructions?](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content)

Pasting a few potential issues here inline: 

- Are audit logs enabled, and do you have permission to view the audit logs? Check protection.office.com > Search > Audit Log Search.
- If you don't have permissions, see Requirements to search the audit log. -. Have you enabled the audit log very recently? If so, try again in a few minutes, to give the audit log time to activate.

**Comment by dips23** [comment]
Hi Jenefer,

Absolutely, as mentioned that user "MPP Admin 1" is able to view audit log search report from the M365 Admin center, because that user has required permission to view Audit Log Search Report, however the same user is failed to view activity reports in the CoE connector as mentioned in the question.

**Note:** Audit Log has been enabled 2 months back.

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Can you clarify, which of these two setups are you doing?

Option 1: Connect to the audit log by using an Azure AD app registration
Option 2: Connect to the audit log by using basic authentication

And if option 2, does your organization support basic authentication?

**Comment by dips23** [comment]
Sure, I think this could be the concern, as I am using Option 2 and organization is using MFA, Thank you for your time and help here!

Best Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thanks for using CoE!
