### ISSUE TITLE
[BUG]: Set App Permissions does not show orphaned apps

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#535]
**Describe the bug**
The "Set App Permissions" Power App does not show orphaned Power Apps.
We have an app in our tenant that has an owner that does not exist anymore. 
MS Support informed told us that a Power App will always keep being linked with the owner ID, even if the owner does not exist anymore in AD.
Also if in the Power BI dashboard, we filter on Owner => Blank, the orphaned app is not showed.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 1.70.6
 - App or Flow: Set App Permissions

**To Reproduce**
1. Open the "Set App Permissions" Power App in the CoE environment with an account that has enough permissions
2. Click on 'ORPHANED APP'
3. You see no apps even if the app has an owner that does not exist anymore

**Expected behavior**
I want to see the apps that have no owner anymore (= the apps that have an owner for who the account does not exist anymore like MS support says)

**Comment by JeneferM-MSFT** [comment]
Hi there.  I have a couple of questions: 
1) Can you please look up the app in the CoE data to see if it is correctly marked orphaned there?
     Go to the solution > entities >  PowerApps App > Data > All Fields > And find your app
      (Or Edit data in Excel if you are able, and its easier for you)

1) Is this a generalized problem for you? aka repro for all orphaned apps? Or just some newly orphaned? 

1) If newly orphaned, have you run the orphan flow since the person left the organization? 
    Go to the solution > Flows > CLEANUP - Admin | Sync Template v2 (Orphaned Makers)

**Comment by WouterF** [comment]
Hi,

1. Yes, it is marked as orphaned. "App is Orphaned" field is set to "yes".
2. We currently only have 1 app that is orphaned because the owner is not in AD anymore.
3. Yes, the flow has ran after the person left the organization. The CoE is installed after the person left the organization so definitely. :)

The environment tab also does not show environments for the "Set App Permissions" and "Set Flow Permissions" app. I checked the environment entity just as the "PowerApps App" entity and it contains data
See attachment for screenshots. 
![coe app orphaned screen](https://user-images.githubusercontent.com/5990852/96749029-99d31080-13ca-11eb-8b08-e2695cb2f9b9.PNG)
![coe app no environments](https://user-images.githubusercontent.com/5990852/96749043-9c356a80-13ca-11eb-84d0-e76cbaac64fb.PNG)

**Comment by JeneferM-MSFT** [comment]
The other two filters in the gallery are for app deleted = no and app type = canvas. 
Can you validate that the app is not marked deleted and that it is of type Canvas? 

If those are the case, then lets make sure we have the same filter:
Can you open the app in edit mode, go to this screen: **_OrphanedAppScreen_**
Select the gallery: **_galApps_2_**  
And see what is shown for the _**Items**_ property.
Here is what you should see:

![image](https://user-images.githubusercontent.com/62659043/96750200-4c867d00-1391-11eb-826f-e694d8830853.png)

**Comment by WouterF** [comment]
The app is of type SharePointFormApp and is not deleted. Can't we update this app to also show orphaned SharePointFormApps?
For the environments tab, I discovered another bug:
I have not deleted any environments but the "Environment Deleted On" column is filled in the "Environment" entity:
![coe environment deleted](https://user-images.githubusercontent.com/5990852/96836615-85802980-1445-11eb-9941-f00bfc1b7c57.PNG)
The clearcollect is wrong:
![environment list empty wrong](https://user-images.githubusercontent.com/5990852/96836950-f9223680-1445-11eb-9401-e83c1ac207ce.PNG)
Why not use the "Environment Deleted" field instead of the "Environment Deleted On" field? It works for me like this:
![coe app no env correct](https://user-images.githubusercontent.com/5990852/96837373-9e3d0f00-1446-11eb-8eda-d376945efda2.png)

**Comment by JeneferM-MSFT** [comment]
We do not have access to the SP permissions and so all our solutions that are permissions oriented skip them. 
We can make this more clear in the app. 
Good call on the env't deleted. I had thought we did that already and will fix for re-release 

Thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.
