### ISSUE TITLE
Sync Template (v2) Apps/Flows - trying to delete connection reference which does not exist

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#536]
**Describe the bug**
I have flows running which is trying to delete connection reference which does not exist and its error flow. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.70.6
 - App - Sync Template (v2) Apps

**To Reproduce**

**Expected behavior**

**Screenshots**
{
  "status": 404,
  "message": "admin_ConnectionReference With Id = 7d9556ff-6b12-eb11-a813-0022481ed81f Does Not Exist",
  "error": {
    "message": "admin_ConnectionReference With Id = 7d9556ff-6b12-eb11-a813-0022481ed81f Does Not Exist"
  },
  "source": "org529025b60.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 3296c9c6-47ce-4b2e-a75e-b14380b27fce"
}

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hi there. Can you please provide a screenshot for us when you post? That makes finding the errors much faster.

**Comment by aakashpatel660** [comment]
![image](https://user-images.githubusercontent.com/59940632/96624261-8183c880-12da-11eb-8293-099730fdad8f.png)


![image](https://user-images.githubusercontent.com/59940632/96624336-9a8c7980-12da-11eb-8170-4a23cb8afd45.png)


![image](https://user-images.githubusercontent.com/59940632/96624450-c1e34680-12da-11eb-9450-6dfbc3d9dbaf.png)

**Comment by JeneferM-MSFT** [comment]
I think you may be experiencing a product bug. Can you please try a few thigs for me? 

Can you please import this flow (from [https://flow.microsoft.com](https://flow.microsoft.com)) and see if it passes when run? 

[listandloopconnectionrefs_20201021143950.zip](https://github.com/microsoft/powerapps-tools/files/5416670/listandloopconnectionrefs_20201021143950.zip)

**Comment by aakashpatel660** [comment]
It run successfully.

**Comment by aakashpatel660** [comment]
is there any update on this? it is failing for almost all the environment and not getting the right data. 

Some of the Sync Flows in the CoE Starter Kit have failed. See below and navigate   to the Flow Instance URL to find out more details:
--
Flow                                                | Environment
Admin \| Sync Template v2 (Flows) | Chemours CoE
Admin \| Sync Template v2 (Flows) | Spain
Admin \| Sync Template v2 (Apps) | 個人用
Admin \| Sync Template v2 (Apps) | Other Functions
Admin \| Sync Template v2 (Apps) | アプリテスト
Admin \| Sync Template v2 (Apps) | Other Functions
Admin \| Sync Template v2 (Flows) | Other Functions
Admin \| Sync Template v2 (Apps) | Chemours CoE
Admin \| Sync Template v2 (Flows) | Information Technology
Admin \| Sync Template v2 (Flows) | Finance & Sourcing
Admin \| Sync Template v2 (Apps) | Personal Productivity
Admin \| Sync Template v2 (Apps) | Justin's Team
Admin \| Sync Template v2 (Flows) | Chemours CoE
Admin \| Sync Template v2 (Flows) | Other Functions
Admin \| Sync Template v2 (Flows) | Personal Productivity
Admin \| Sync Template v2 (Flows) | Information Technology
Admin \| Sync Template v2 (Flows) | Businesses
Admin \| Sync Template v2 (Flows) | Personal Productivity
Admin \| Sync Template v2 (Flows) | Personal Productivity
Admin \| Sync Template v2 (Apps) | Testing
Admin \| Sync Template v2 (Apps) | アプリテスト
Admin \| Sync Template v2 (Flows) | Spain
Admin \| Sync Template v2 (Apps) | Build
Admin \| Sync Template v2 (Apps) | Businesses
Admin \| Sync Template v2 (Apps) | Information Technology
Admin \| Sync Template v2 (Apps) | pricing SFDC
Admin \| Sync Template v2 (Apps) | pricing SFDC
Admin \| Sync Template v2 (PVA) |  
Admin \| Sync Template v2 (PVA) |  
Admin \| Sync Template v2 (Apps) | Information Technology
Admin \| Sync Template v2 (PVA) |  
Admin \| Sync Template v2 (Apps) | Chemours CoE
Admin \| Sync Template v2 (Flows) | Chemours CoE
Admin \| Sync Template v2 (Flows) | Information Technology
Admin \| Sync Template v2 (Apps) | Personal Productivity

**Comment by JeneferM-MSFT** [comment]
Hello we aren't able to repro, so I'm having trouble helping you here. 
Couple of things to try please update the call to use pagination in the apps flow to see if that helps? 
 
![image](https://user-images.githubusercontent.com/62659043/97462016-4d2c8f80-190c-11eb-843f-03b3ae2e0fc0.png)
![image](https://user-images.githubusercontent.com/62659043/97462110-66cdd700-190c-11eb-8f1b-d40a13e1467c.png)

**Comment by JeneferM-MSFT** [comment]
And it does appear that you have the incorrect selections for the other objects (Flow / PVA). 
You show as environment default.cds but it should be current as it is for your Apps
![image](https://user-images.githubusercontent.com/62659043/97464705-3cc9e400-190f-11eb-8ba1-279937889719.png)
![image](https://user-images.githubusercontent.com/62659043/97464994-93372280-190f-11eb-80d6-2293b5be2693.png)

It appears that some edits have been made to your flow as a result, so I suggest you re-import before we continue to debug as I'm now unsure of your state,

**Comment by aakashpatel660** [comment]
I cleared all my data and run all flow again and it was successful. But when I go to Power Platform Admin View Model Driven App it does not show me all active environments or Apps. But when I go to the entity it does show all the records.

**Comment by JeneferM-MSFT** [comment]
This sounds like a new issue. can you please post separately with more details. For example which envts / apps are missing, do they have any similar qualities to them when you look at them in the entity? 

Do note also that we cannot collect MDA's for dev/teams envts

**Comment by aakashpatel660** [comment]
Hello

After trying to clear all my data from all the entities I am facing the same issue back. As you suggested me to put pagination on the list record I did put pagination. 

Admin | Sync Template v2(Flows) runs 46 times and out of that, it fails 8 times. 
Admin | Sync Template v2(Apps) runs 46 times and out of that, it fails 11 times.


![image](https://user-images.githubusercontent.com/59940632/97713823-b7713b80-1a96-11eb-8ce9-4bdd16ab8f54.png)

![image](https://user-images.githubusercontent.com/59940632/97713848-bdffb300-1a96-11eb-870d-295db3d8e608.png)

![image](https://user-images.githubusercontent.com/59940632/97715135-66624700-1a98-11eb-84b9-b314b83e74aa.png)

![image](https://user-images.githubusercontent.com/59940632/97715362-ac1f0f80-1a98-11eb-9ca2-c5b4bccbfd68.png)

**Comment by JeneferM-MSFT** [comment]
I believe you are suffering from throttling problem and have multiple flows running for these objects. This from your other issue where it is clear that you upgrade to 70_6 did not work. at did not work as it no longer does an overwrite. 

Can you please upgrade in the following manner? 

> Switch to classic (this could take some time) 
![image](https://user-images.githubusercontent.com/62659043/97719195-cc4ccf80-1a94-11eb-91e4-a798558a8039.png)


> Import
![image](https://user-images.githubusercontent.com/62659043/97720698-90b30500-1a96-11eb-93de-8b8a202455aa.png)


> Choose 70_6 [CenterofExcellenceCoreComponents_1_70_6_managed.zip](https://github.com/microsoft/powerapps-tools/files/5465857/CenterofExcellenceCoreComponents_1_70_6_managed.zip)
![image](https://user-images.githubusercontent.com/62659043/97720944-dd96db80-1a96-11eb-9bb1-fb4369d51125.png)


> Next & Next

> Chose Overwrite and Import
![image](https://user-images.githubusercontent.com/62659043/97721182-1fc01d00-1a97-11eb-8e77-3fea90e05cfe.png)
