### ISSUE TITLE
[BUG]: PowerBI template 10-13 vs 07-07 data differences

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#538]
CoE updated to latest -- core 1.70.6,  audit logs 1.0.0.20
The screenshots below are looking at data from last night's run.

7-7 template 'Overview - Power Apps'
![image](https://user-images.githubusercontent.com/52799471/96737256-13471080-1383-11eb-96d4-50381c877f0a.png)

10-13 template
![image](https://user-images.githubusercontent.com/52799471/96737350-2eb21b80-1383-11eb-98b0-638a072503c9.png)

7-7 Apps tab
![image](https://user-images.githubusercontent.com/52799471/96737450-4e494400-1383-11eb-83d6-ba9e15343540.png)

10-13 Apps tab
![image](https://user-images.githubusercontent.com/52799471/96737518-6325d780-1383-11eb-95b7-0c79339b1012.png)

Seeing that the Canvas Apps and Total Apps is different by 6.  Was there a bug in the old calculation?
Also its strange on the first screenshot why the rest of the environments are not listed in the 10-13 template?

If you need any more info...let me know
Dave

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

there was bug in the previous dashboard where resources deleted from the tenant were not filtered out in the dashboard. if you look at the filter, this is what you should see now where only resources that haven't been deleted show.
![image](https://user-images.githubusercontent.com/55705669/96744908-6e95f480-13bd-11eb-8bb6-685ec72edf63.png)

for Environments, this is the filters you should see - a filter to hide all Environments on all pages is something you should see.
![image](https://user-images.githubusercontent.com/55705669/96745063-9e44fc80-13bd-11eb-98ba-86a8ceb38f23.png)

Do the environments that you see in the first screenshot still exist in your tenant?

**Comment by dchrist27** [comment]
Thanks for clarifying that there was a bug.

As for the list of environments…yes those environments still exist.  If I go to Power Platform Admin center I see 11 environments.

**Comment by JeneferM-MSFT** [comment]
Can you validate that the missing environments still contain apps? It looks like PBI now does not show zeros for top-n filters.

**Comment by dchrist27** [comment]
Ah...so that explains the environments with no apps. I just realized now the 3 environments listed on the 7-7 template that are missing from the 10-13 template are environments of type 'Microsoft Teams' (ie. Project Oakdale).

**Comment by manuelap-msft** [comment]
Thanks for letting us know! I think this filter snuck in by accident, and we'll remove it with the next version. You can also remove this yourself by opening the Filters pane and removing the highlighted "Filters on this visual"
![image](https://user-images.githubusercontent.com/55705669/97435541-73f0c300-1918-11eb-8c77-a0a11da0deff.png)

**Comment by JeneferM-MSFT** [comment]
A new version of the PBI Template is now available in the version of the toolkit releasd today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

Thanks for using CoE, and helping make it great with your feedback.
