### ISSUE TITLE
Execution of Audit Log Child Flow never completes

### ISSUE THREAD

**Issue by DToro83** [microsoft/powerapps-tools#539]
**Describe the bug**
Audit Log, it only brings 100 records, so we understand that you have to launch it several times a day for short periods to obtain data 24 hours a day.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [CoE]
 - Version [CenterofExcellenceAuditLogs_1_0_0_20_managed]
 - App or Flow [Sync | Audit Logs]

**To Reproduce**

**Expected behavior**
custom connector requires any specific configuration? We are launching a Flow so that it sends 1 full day in 3 hour runs and it does not finish

**Screenshots**
![imagen](https://user-images.githubusercontent.com/63851188/96877482-fe00dd80-1479-11eb-9090-000275dfe1a6.png)

**Additional context**
Thank's for your help, at your disposal, regards!

**Comment by JeneferM-MSFT** [comment]
Can you confirm:

1) That you have this filter in the child flow:
![image](https://user-images.githubusercontent.com/62659043/96878417-7054cc00-1440-11eb-9b0c-01f2743fa48e.png)


2) This this flow has run successfully in the past for you. Did this start to repro a few weeks ago? 

3) What does it show for Actions when you view Analytics
![image](https://user-images.githubusercontent.com/62659043/96878744-d17c9f80-1440-11eb-8cdb-0d87ab4ef8e2.png)

**Comment by JeneferM-MSFT** [comment]
One more question, can you please let me know if you are running as a trial license?

**Comment by JeneferM-MSFT** [comment]
Closing out issues with no follow ups on our side. Thanks for using CoE!
