### ISSUE TITLE
customer connector test fails with 401 with global admin access

### ISSUE THREAD

**Issue by ayenampudi** [microsoft/powerapps-tools#54]

**Comment by ayenampudi** [comment]
using basic authentication with global admin rights and it continues to fail.

**Comment by manuelap-msft** [comment]
Is your Admin account protected with MFA?

**Comment by ayenampudi** [comment]
Thank you for your response. Yes, we are MFA protected.
But, I also tested the same in another test tenant that we own that doesnot have any MFA and it still failed.

**Comment by Grant-R** [comment]
I'm getting the same thing. Is MFA a factor? Should an account not enabled be used?

**Comment by ayenampudi** [comment]
I hope not. I have another tenant where there is no mfa and it is a simple 25 user test tenant where I am a GA and I have the same problem.

**Comment by manuelap-msft** [comment]
Yes, MFA is a factor. If your account is MFA protected, using basic authentication won't work. We're just writing the documentation on what to do then, but it will involve creating an App Registration
Without MFA it should work if you provide your email address as user name and password when you create the connection to the custom connector.

**Comment by ayenampudi** [comment]
Update - I tried to perform the same with a cloud only account (we sync acc to auzre ad) and it worked fine. Not sure if this is also a factor. 
The cloud only account is also set to not have MFA.
Looking forward to the documentation update too. May I know if there is an ETA please?

**Comment by Grant-R** [comment]
so, we need to create another account with access to the exchange unified audit logs, that doesn't have MFA enabled.

**Comment by manuelap-msft** [comment]
No, we are working on the documentation on how to support MFA for the connector at the moment. It will involve setting up an Azure AD Application to pass the Bearer Token to rather than using Basic Auth. It's influenced by Kent Weare's blog post https://flow.microsoft.com/en-us/blog/automate-flow-governance/

**Comment by ramu1977** [comment]
@manuelap-msft I have same issue Customer connector test fails, We have MFA enabled. Waiting for the update

**Comment by jskoogsmith** [comment]
I'm also experiencing the same issue and awaiting documentation.  Any update would be great.

**Comment by manuelap-msft** [comment]
Hello,

we have just published a solution and setup instructions to sync the Audit Log with MFA enabled
https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Audit%20Log%20(MFA)

Best Regards,
Manuela
