### ISSUE TITLE
[BUG]: Upgraded to v1.70.6 but the Flows aren't using the Connection References

### ISSUE THREAD

**Issue by jathorpe** [microsoft/powerapps-tools#540]
**Describe the bug**
I updated Center of Excellence - Core Components solution to the latest release (v1.70.6) from v1.54 and none of my previously running "Admin | Sync Template" flows are using connection references. The flows wants me to set an existing connection on all the actions that require a connection.  

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core Components 
 - Version: 1.70.6
 - App or Flow: "Admin | Sync Template" flows

**Expected behavior**
I was expecting the "Establish connections to activate your solution" page to set all the connection references and that all the flows would be using those connection references.

**Screenshots**
![image](https://user-images.githubusercontent.com/10499571/97113156-7227c500-16b6-11eb-9c9e-2e620a4ab388.png)

**Comment by JeneferM-MSFT** [comment]
Hi there. It looks like the connections reverted on our side somehow. I will fix those up for the next release. And in the meantime you will need to connection each manually.

**Comment by JeneferM-MSFT** [comment]
Apologies, I was looking at this incorrectly. These do seem to be in place and the upgrade works for me. 

Can you please validate that the upgrade worked to overwrite the flows? You can test this by opening the main sync flow and seeing if you have this separate scope.
 
![image](https://user-images.githubusercontent.com/62659043/97432227-a1724800-18e9-11eb-8798-fe8998b92632.png)

**Comment by JeneferM-MSFT** [comment]
Closing this issue out. The solution did not upgrade correctly.
