### ISSUE TITLE
[BUG]: little question - What is the best practice to transit CoE workload from one environment to another?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#541]
Hello,

We have deployed and configured latest CoE kit in the dev environment "Environment 1" with few custom configuration in the CoE flows which is requiring now to transit into another environment "Environment 2"

Can you please clarify whether in new environment "Environment 2" - is it best to migrate CoE workload from Environment 1"? OR CoE Starter kit has to be setup and configured from the scratch in the "Environment 2" ?

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

it would be best practice to deploy from Environment 1 to Environment 2 and deploy your customizations as a managed solution. Say Environment 1 is your development environment where you make changes to the solution you then deploy to a Test or Production environments as managed solutions from there.

You can do this manually by exporting the solution as managed and importing it into your target environments, or you can use tools available in Azure DevOps to automate this.

Here's some more info on ALM
https://docs.microsoft.com/en-us/power-platform/alm/

Hope that helps,
Manuela
