### ISSUE TITLE
[BUG]: How to find out list of users shared with Model driven apps via CoE Starter Kit?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#542]
Hello,

I see that PowerApps App Entity stores data related to "App Shared Groups & App Shared Users" which is visible in "Power Platform Admin" app of CoE Starter kit, however the same app, doesn't displays data regarding which users are shared with the Model driven app unlike canvas app.

Can you please share - How to find out list of users shared with Model driven apps via CoE Starter Kit? I assume it's a "PowerApps App" entity that stores all apps 

Thanks and Regards,
Dipti

**Comment by dips23** [comment]
I assume that security concept for the canvas app/model driven apps is different and therefore not sure if this part is considered in this app section for the model driven app, if not - is there any other CoE area where we can see the list of users shared with Model driven apps?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
I'm afraid this information is not exposed to us, so we are unable to gather it for you in the CoE. 

Thanks for using CoE
