### ISSUE TITLE
Link to Theme Editor is incorrect

### ISSUE THREAD

**Issue by Briandh78** [microsoft/powerapps-tools#55]
The link to the Theme Editor on https://github.com/microsoft/powerapps-tools is incorrect and goes to the PowerAppsReviewTool.zip

**Comment by alaakh42** [comment]
I also always get error "try again later" when I try to import PowerAppsReviewTool app

**Comment by manuelap-msft** [comment]
This has been fixed now and updated on the GitHub page to reflect the correct link
