### ISSUE TITLE
Admin | Sync Template v2 (Model Driven Apps) Unauthorized error

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#550]
**Describe the bug**
When Model-Driven Apps flow runs it fails at List Model-Driven Apps and throws an error for unauthorized and this is happening to multiple runs it attempts.  

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.70.6
 - Flow - Sync Template (v2) Model Driven Apps

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/97716034-7cbcd280-1a99-11eb-8a21-0f3514605e38.png)

**Additional context**
{
  "status": 401,
  "message": "Unauthorized",
  "error": {
    "message": "Unauthorized"
  },
  "source": "xyz.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: b8a144e3-ffee-4434-9a78-cc89c7b4bbc6"
}

**Comment by JeneferM-MSFT** [comment]
You do not have the latest version of the flow, where we have fixed the access issue for Teams environments. 
It appears that your upgrade failed to overwrite it when you tried to install 70_6. 

Please upgrade in the following manner.

> Switch to classic (this could take some time) 
![image](https://user-images.githubusercontent.com/62659043/97719195-cc4ccf80-1a94-11eb-91e4-a798558a8039.png)


> Import
![image](https://user-images.githubusercontent.com/62659043/97720698-90b30500-1a96-11eb-93de-8b8a202455aa.png)


> Choose 70_6 [CenterofExcellenceCoreComponents_1_70_6_managed.zip](https://github.com/microsoft/powerapps-tools/files/5465857/CenterofExcellenceCoreComponents_1_70_6_managed.zip)
![image](https://user-images.githubusercontent.com/62659043/97720944-dd96db80-1a96-11eb-9bb1-fb4369d51125.png)


> Next & Next

> Chose Overwrite and Import
![image](https://user-images.githubusercontent.com/62659043/97721182-1fc01d00-1a97-11eb-8e77-3fea90e05cfe.png)
