### ISSUE TITLE
[BUG]: Child Audit Logs Flow invalid URL: Blob key in the url is invalid"

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#552]
**Describe the bug**
When the flow runs it throws the error message at GetContentDetails action because of URL is invalid

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Audit Logs
 - Version - 1.0.0.20
 - Flow - Child Sync Template (v2) Audit Logs

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/97874605-3a88d080-1ce7-11eb-934e-2a9f21e2b419.png)

**Additional context**
{
  "error": {
    "code": "AF20052",
    "message": "Blob key 20201031140910115031061$20201031141052037020628$audit_general$Audit_General$na0020 in the url is invalid"
  }
}

**Comment by manuelap-msft** [comment]
Please edit the Admin | Sync Audit Logs flow (not the child flow) and enter your tenant ID in the variable designated for it
![image](https://user-images.githubusercontent.com/55705669/97887546-fa930f00-1d21-11eb-971a-9469bf28ad9c.png)

**Comment by manuelap-msft** [comment]
Closing this issue as there is no follow-up; the above fix is known to work.

Thanks for using the CoE Starter Kit!

**Comment by JeneferM-MSFT** [comment]
Leaving open for other users to see until documentation is fixed.

**Comment by manuelap-msft** [comment]
Updated with the new release that just went out. The install experience now matches the documentation in that a Tenant ID will be required during import.
