### ISSUE TITLE
Teams (oakdale) Envts: Sync Template V2 Flow Disabled User error if flow is made in a PVA Bot

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#553]
**Describe the bug**
I am a Power Platform Admin and I am receiving an error that I am a disabled user in the Microsoft Teams environment. If I am a Power Platform Admin then I should be able to go inside that environment and get the context details. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.70.6
 - Flow - Sync Template (v2) Flows

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/97874736-71f77d00-1ce7-11eb-994a-735773e6fe4b.png)

**Additional context**
{
  "error": {
    "code": "XrmSystemUserDisabled",
    "message": "The CDS system user record representing user 'Admin Email Address' is disabled. Please ask a database administrator to enable this user."
  }
}

**Comment by JeneferM-MSFT** [comment]
Thank you, I repro this for teams envts as well and we are investigating

**Comment by JeneferM-MSFT** [comment]
Turns out this repros when there is a PVA Bot in Teams which calls a flow. Those flows wont be counted in the CoE until the product team fixes. An ICM has been created on our side. And we'll just allow this failure to stay until that is fixed. 
Thanks for helping make CoE, and the product itself, great!

**Comment by JeneferM-MSFT** [comment]
Can you please let me know if you still repro this issue?

**Comment by JeneferM-MSFT** [comment]
We believe this is now fixed by the product team. 
Please re-open if you still see the error.
