### ISSUE TITLE
[BUG]: Unable to import any of the PowerBI Embedded Apps or Helper Flows Solutions

### ISSUE THREAD

**Issue by farhanmansoor** [microsoft/powerapps-tools#555]
**Describe the bug**
We are unable to import any of the PowerBI Embedded Apps or Helper Flows Solutions. We see an error when we attempt the Import of the solution:

**The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: PowerAppsButtonArchiveApp.zip, Admin-AccessthisApp.zip, Admin-AccessthisFlow.zip, 
 - Version: N/A - latest download dated 3-Nov-2020
 - App or Flow: PowerBI Embedded Apps, SharePoint Helper Flows

**To Reproduce**
1. Go to 'flow.microsoft.com'
2. Click on 'Import'
3. Select any of the .zip Package Files listed above.
4. Click Import
5. See error

**Expected behavior**
The solutions are imported successfully.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/455033/97952160-84a9a900-1df0-11eb-970b-904e35a8fd93.JPG)

**Additional context**
Prevents us from using the included solutions in the CoE Starter Kit

**Comment by manuelap-msft** [comment]
Hello, 

the helper flows and apps are not shipped as a solution but as standalone apps and flows - in order to import them please go to make.powerapps.com > Apps > Import, and flow.microsoft.com > Flows > Import. 

Thank you for using the CoE!
