### ISSUE TITLE
[BUG]: cannot activate sync template flow: The user does not have a service plan adequate for the non-Standard connection

### ISSUE THREAD

**Issue by imtnhw** [microsoft/powerapps-tools#556]
**Describe the bug**
I am trying to create an environment for the CoE toolkit. I followed the steps in here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components . But i failed to activate the sync template flow. My account alreay have powerplatform administrator role. Would you please advice how can I set up the environment?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]:  Center of Excellence - Sore Components
 - Version [e.g. 1.29]: 1.70.3
 - flows: all Admin | Sync Template v2 (...)

**To Reproduce**
1. Go to the solution page
2. Click on "turn on" for all the flows which starts from "Admin \ sybc template"
3. See error

**Expected behavior**
Turn on the flows, as it is required for tool kit environment set up

**Screenshots**
![screenshot2](https://user-images.githubusercontent.com/73816125/97956806-9b4a0300-1de4-11eb-8420-3ee16379f0da.png)

**Comment by manuelap-msft** [comment]
Does your account have a Power Automate per User / Power Apps per User plan? The sync flows use premium connectors, so a premium service plan is required to turn them on.

**Comment by JeneferM-MSFT** [comment]
Here is a link to the full pre-reqs, in addition to the likely culprit that Manuela has identified for you: [prerequisites](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites)

Thanks for using CoE!

**Comment by JeneferM-MSFT** [comment]
Closing out issues with no follow ups on our side. Thanks for using CoE!
