### ISSUE TITLE
[BUG]: How to avoid frequent Archival emails to end user?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#557]
Hello,

The "Start Archival" CoE flows of governance component is having following condition:

![image](https://user-images.githubusercontent.com/13658386/97991055-dcbfbb80-1dae-11eb-8aa9-e13e8fea8ed6.png)

That sends email to Flow maker to approve/reject archive process even if the same flow has been rejected.

Am I missing anything here? Should there be a condition to check "Approval" response along with last modified date of the flow/app here?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
The idea is to force the users to continuously advocate why they want to keep the flow/app in play. We dont want to allow a single "keep" to keep the flow forever. 

Note that in the near future, apps will check both launched and modified, but for flows we will still only check modified. 

Thanks for using CoE!

**Comment by dips23** [comment]
Great, Makes sense! In this case, would flow/app of owner be updated if they provide business justification in the Approval email by rejecting the Archiving process?

Or we should give any sort of instruction to owner to update flow/app, if they reject the archiving process?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Adding a suggestion is a good idea. I will add that as a backlog item. 
Thanks again!

**Comment by dips23** [comment]
Hey Jenefer!

This is my bad, Actually the Archiving flow clearly states below, and therefore this is no more issue, we can close this issue:
![image](https://user-images.githubusercontent.com/13658386/98212838-2d9bf500-1f12-11eb-9913-afd3d8f1262c.png)

Thanks for your help and understanding!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
You are welcome, thanks for using CoE!
