### ISSUE TITLE
Inconsistency in showing the Model driven apps with latest COE tool kit 

### ISSUE THREAD

**Issue by challa85** [microsoft/powerapps-tools#559]
Everytime the Admin | Sync Template v2 (Model Driven Apps)  flow from COE core component solution  run show some apps(but not all) and sometime show no MDA apps.  Below are the screen shots of the outputs from 2 different runs.

![image](https://user-images.githubusercontent.com/33087528/98272345-ffbcbc00-1fb6-11eb-86ae-3059db962d2f.png)

![image](https://user-images.githubusercontent.com/33087528/98272394-0cd9ab00-1fb7-11eb-999d-054abb7d834d.png)

Kindly let me know how to get fix this. Moreover we have 50+ envs and not sure how to check which flow had ran for which env out of those 50+ flow runs, unless  we go and check each and every flow.

COE Coresolution component: CenterofExcellenceCoreComponents_1_70_6_managed

**Comment by JeneferM-MSFT** [comment]
Regarding how to know which of the flows is for this envt, you cannot know without opening each run. 
But you can trigger the flow again for that envt by editing that environment in CoE. 

If you dont know how to edit rows in the COE, this will work for you:

1) Go in to the Environment entity in the Core solution
![image](https://user-images.githubusercontent.com/62659043/98275674-c0a45180-1f49-11eb-8b78-cebacc106dca.png)

2) Got to Data > Select Environment of Choice > Edit > Edit Maker Name (you'll want to change back later) > Save
![image](https://user-images.githubusercontent.com/62659043/98277299-0e21be00-1f4c-11eb-95a8-16cf687a3297.png)
3) Go to Model Driven Apps flow and see it running (may take a few minutes to trigger) 


Can you please do this to trigger your envt of interest? Then let's see what it collects

**Comment by challa85** [comment]
Thanks for update Jenefer. Followed the steps as you mentioned, interestingly this time it showed some more MD apps but not complete list of all apps for that environment.

**Comment by JeneferM-MSFT** [comment]
Can you please:
1) Validate that the flows are finished running (both the Model Driven App and the Apps):
![image](https://user-images.githubusercontent.com/62659043/98284046-65785c00-1f55-11eb-8e87-f45a9286d2ae.png)


2) Then open the data in Excel to see if you have the correct data. From the Powerapps App entity, click Export Data
![image](https://user-images.githubusercontent.com/62659043/98283385-7b395180-1f54-11eb-8110-576226612344.png)

3) When you get that Excel file, filter to the environment of interest and see if all the data is there. I always make it a table fwiw
![image](https://user-images.githubusercontent.com/62659043/98283762-f7339980-1f54-11eb-864d-11644a4b5090.png)

I'm trying to determine if the dashboard or the flow is what is causing the error.

**Comment by challa85** [comment]
Thanks for your quick response Jenefer. Inconsistent apps data is definitely from flow only, as I am observing in  power platform admin app, sometimes the apps are showing and sometimes not after running the flow. Is there any permanent solution to get all the apps info other than the workaround of updating environment maker field as we never knew after which run the data will show correctly.

**Comment by JeneferM-MSFT** [comment]
Sorry, I dont quite follow you. Can you please validate if you see the correct data in the entity itself by the export to Excel method described above? 

The workaround I describe is just a way for you to instigate the flow for the environment of interest. That's not a thing you normally need to do.

**Comment by challa85** [comment]
Entity data is not showing correct data. Today after the schedule run , I have verified the entity data and it did not show all the apps, but after updating the environment maker field it is showing all the apps.

Seems during the schedule run the flow is not picking up all the MDA apps and if we update the maker field then the flow is picking up all the apps.

**Comment by JeneferM-MSFT** [comment]
What do you mean by updating the maker field?

Also, can you see if there are failures in these runs? 
![image](https://user-images.githubusercontent.com/62659043/98371837-a920a380-1ff1-11eb-9073-4bf03462775b.png)

**Comment by challa85** [comment]
Hi Jenefer,

Please find the below response

**What do you mean by updating the maker field?** 

Followed the below steps for one of my environment for which MDA's are not showing correctly. After performing below steps the subsequent flow picked all the  apps.

Go in to the Environment entity in the Core solution

Got to Data > Select Environment of Choice > Edit > Edit Maker Name (you'll want to change back later) > Save

Go to Model Driven Apps flow and see it running (may take a few minutes to trigger)

**can you see if there are failures in these runs?**

Yes there were 2 failures but those were for different environments which I am not bothering at this moment. 

Error 👍  ActionBranchingConditionNotSatisfied. The execution of template action 'Inquiry_not_supported_for_Teams_sku' skipped: the branching condition for this action is not satisfied.

Mainly I am looking for MDA's which are in Prod environment, which are not showing correctly during the schedule period(Although the flow ran successfully for this environment) and the apps are showing correctly after following the steps mentioned above(like editing Maker Name).

**Comment by JeneferM-MSFT** [comment]
OK thank you. This means that **_the flow is working_**, and the data is correctly populating from the flows. 

Again, we were only having you update that field in order to trigger the flow for your environment so that you didn't have to go and find it in the runs. So you triggered the flow, and it correctly populated all the data into Excel 

Is it showing correctly in the dashboard now as well? And if not, can you please see which apps are missing?

**Comment by challa85** [comment]
Nope the flow is not working correctly as it is not picking up all the apps for all the environments, but when  I manually update  filed from Environment entity then only  the triggered flow is picking up all the MDA's. 

To say in short the scheduled flow is not picking all the MDA's and those are not showing in Dashboard.

**Comment by JeneferM-MSFT** [comment]
I'm sorry but I think you dont understand how the flows work. I was really just helping you re-trigger the flow in a way that wouldnt cause it to run for all environments. It was that same scheduled flow that you ran. 

That flows is triggered when the envt record in the CoE is edited. 
Normally it is edited by the main sync flow, but that causes all records to be edited making it hard to find your case. 
We had you manually edit one record instead so that only that environment would run. 

But it is the same flow. 

Is the dashboard correct now?

**Comment by challa85** [comment]
I understand Jenefer. My only question is why the same flow which runs automatically after the main sync flow triggers shows incorrect data and why it is showing correct data after re-triggering the flow for particular environment.

**Comment by JeneferM-MSFT** [comment]
I'm not sure it was incorrect. We are currently investigating. 
Previously I believe you were not validating that they data was correct in the entity itself (by checking excel). And now we know that its correctly populating there. We were doing this to see if the problem was in the flow (aka the entity itself) or the report. 

Can you please answer this question: is it showing correctly in the dashboard now?

**Comment by challa85** [comment]
I understand Jenefer. My only question is why the same flow which runs automatically after the main sync flow triggers shows incorrect data and why it is showing correct data after re-triggering the flow for particular environment.

As I said earlier the schedule flow did not show all apps in dashboard but when I re-trigger the flow for the environment which I am looking for picked up all the apps. The same data is visible in dashboard.

So for now can we please leave about the dashboard and look into the difference of scheduled flow and re-triggering for particular environment

**Comment by JeneferM-MSFT** [comment]
I'm sorry I'm afraid I am unable to offer you the level of support you need here as it appears you need in person debugging in order to explore the issues you are seeing. 

There are many partners that offer help with the CoE.
