### ISSUE TITLE
[BUG]: How to upgrade customized COE 1.70.2 version into 1.70.6?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#560]
Hello,

When 1.70.2 version arrived, I have deployed that into the environment which is a managed version. Later we made couple of changes in the email actions and trigger actions of CoE flows in the same solution (1.70.2)

Now, we require to upgrade that with the latest version, however we afraid of loosing the existing customization we have made in the solution 1.70.2 version in the environment.

Does it mean that we have to every time manually update the customization in the solution on every release?

Can you please clarify?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hello. Yes flows and canvas apps cannot merge changes. 
Here is our recommendation for [extending the starter kit](https://docs.microsoft.com/power-platform/guidance/coe/setup#extending-the-starter-kit)

So yes, if you are augmenting the toolkit and want to continue taking changes from us, you will need to re-apply those changes. 

If you chose to make the changes inline (not from a save-as), here is how to do that in the new modern import. This will be in the documentation once it gets through review. 
![image](https://user-images.githubusercontent.com/62659043/98372216-45e34100-1ff2-11eb-92b2-ae4bfb3fa06c.png)

**Comment by JeneferM-MSFT** [comment]
Closing out issues without active follow up. 

Thanks for using CoE!
