### ISSUE TITLE
Last Launched is note being populated in reports and applications

### ISSUE THREAD

**Issue by ssquiresusps** [microsoft/powerapps-tools#569]
**Describe the bug**
Last Launched is note being populated in reports and applications

 Apps:  
Power Paltform Admin View

**Expected behavior**
Last Launched data being populated.

**Screenshots**
Attached
[last_launched.docx](https://github.com/microsoft/powerapps-tools/files/5539504/last_launched.docx)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. Last launched is populated by the audit solution. 
Generally speaking, the Power BI report covers multiple of the solutions (Core, Govern, Nurture, Audit). 
So you wont see all the features light up unless you complete all of the solution set ups. 

[setup-auditlogs](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog)

Thanks for using CoE

**Comment by ssquiresusps** [comment]
Hi Jenefer,  I've attached additional screen shot showing that the audit logs set up was complete and is running.

**Comment by JeneferM-MSFT** [comment]
That solution is not able to collect information for all the apps to begin with. It will slowly, now that you have it set up, begin collecting launches. You can test this by launching a few apps now, and then on Monday you will see those apps as having last launched dates

**Comment by ssquiresusps** [comment]
Thanks.   I'll try again on Monday
