### ISSUE TITLE
COE Hell

### ISSUE THREAD

**Issue by johnmsaxton** [microsoft/powerapps-tools#57]
I installed version 1.14 and recieved this error: 

Flow client error returned with status code "BadRequest" and details "{"error":{"code":"FlowMissingConnection","message":"The flow is missing a connection for api 'shared_commondataservice'. Reauthenticate the connection or remove from the flow and re-save."}

I went back to GitHib and found 1.15 and attempted to install it, but the installation failed. (Sorry, didn't keep that message) 

I am now trying to delete 1.14 so I can start clean and I keep getting this message: 
Exception type: System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]
Message: During Solution Uninstall of Solution Id 0b463e1f-9231-45d6-9daf-d7b8665aab1d, cannot find any instances of the component with Component Id cb29b3ee-242b-ea11-a810-000d3a31c17f and Component Type 380

So I cannot update to fix the initial install error and I cannot delete the solution. Please don't tell me I have to drop my environment because the install failed.

**Comment by manuelap-msft** [comment]
In your Flow where you are receiving the error message, have you made sure to re-authenticate all actions? You should see a yellow warning triangle next to ones that aren't authenticated yet!

Instead of uninstalling, you can also upgrade the solution - import the newest version and choose "upgrade" on the first screen.

**Comment by johnmsaxton** [comment]
Error messages show up after the installation.

I tried to upgrade. It also failed.

**Comment by manuelap-msft** [comment]
This sounds like a bug to me and I would suggest raising a service ticket; I couldn't replicate this behaviour.

**Comment by johnmsaxton** [comment]
I had the solution removed by support. I am going to try again with 1.15. If I get the error again, I will open a service ticket
