### ISSUE TITLE
[BUG]: Connection Id missing for connection reference logical name 'admin_CDSCoEConnection'.

### ISSUE THREAD

**Issue by sundium** [microsoft/powerapps-tools#570]
**Describe the bug**
After the core solution is imported, when activating the Admin | Sync Template  v2 (...) flows, the connections are not picking up the existing connections in the target environment. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [e.g. 1.70.6]
 - All Sync Flows

**To Reproduce**
1. After imported the core solution
2. In make.powerapps.com
3. Click on Solutions
4. Click on Center of Excellence - Core Components
5. Turn on the Admin | Sync Template v2 (...) flow
6. See error 

Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmConnectionReferenceMissingConnection","message":"Connection Id missing for connection reference logical name 'admin_CDSCoEConnection'."}}".

![image](https://user-images.githubusercontent.com/11729099/99227125-b2aad680-284f-11eb-8f9a-95f25cedf0de.png)

**Expected behavior**
Your Flow is On

**Screenshots**

**Additional context**
Need to Edit each flow and check through the connections are picked up, Flow checker helps.

![image](https://user-images.githubusercontent.com/11729099/99227325-f271be00-284f-11eb-8f62-e1d2c4623b87.png)

**Comment by JeneferM-MSFT** [comment]
Is this a clean install or in import? 
If import, can you please try again using the "Switch to Classic" path?

**Comment by JeneferM-MSFT** [comment]
and when you do the Classic path, please be sure to select "Overwrite"

**Comment by JeneferM-MSFT** [comment]
Closing out issues with no next steps. Thanks for using CoE
