### ISSUE TITLE
Known Issue with Core 1.71: Error turning on Admin | Sync Template v2 (PVA): Failed to activate component(s). An unexpected error occurred.

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/powerapps-tools#571]
1. Install Core 1.71
2. View flows in the solution 
3. Turn on Admin | Sync Template v2 (PVA)

BUG: An unexpected error occurred
![image](https://user-images.githubusercontent.com/62659043/99288887-18b44100-27f1-11eb-8a69-69170744d709.png)

NOTE: 
**The flow is actually turned on,** if you open it to the details page you will see that it is turned on. 
And it will run successfully when you turn on the main sync flow. 
This is just an error in that pages UX for turning on the flow, and product team is investigating.
![image](https://user-images.githubusercontent.com/62659043/99288982-371a3c80-27f1-11eb-9eba-ffde6f6416d4.png)

**Comment by albertocaa1317** [comment]
I have this same issue.

**Comment by JeneferM-MSFT** [comment]
Please do note, the flow is actually turned on, and it will run successfully when you turn on the main sync flow.
If you see something more severe, please let us know. 
Thanks for using CoE!

**Comment by albertocaa1317** [comment]
FYI
After upgrade to core 1.71.5 this flow already have a status ON in the solution screen.

**Comment by JeneferM-MSFT** [comment]
Resolved now.
