### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Custom Connectors) errors on GET_connector_swagger_JSON

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#572]
Hi there,
I just imported Core Components 1.71 and got the flows running.  The "Admin | Sync Template v2 (Custom Connectors)" keeps failing with the error in the attached screenshots.

Is there a workaround maybe?
Thank you,
Christi

![CustomConnectors](https://user-images.githubusercontent.com/50427725/99311455-7c4e6680-2811-11eb-87df-5ef20300998b.jpg)

**Comment by JeneferM-MSFT** [comment]
Hello. Thank you, I do repro. We upped the pagination across the toolkit and it appears you cannot have pagination on this call.
I have local fixed this in our version so it will ship with the next release. If you'd like to fix ahead of that, please update as shown here:

1) Get to the action's settings:
![image](https://user-images.githubusercontent.com/62659043/99312752-588c2000-2813-11eb-9ea2-acfb506237da.png)

2) Turn off pagination, delete the numbers in the "Threshold" field, and hit Done
![image](https://user-images.githubusercontent.com/62659043/99312860-84a7a100-2813-11eb-9310-e0ed83dc2593.png)

**Comment by osbornecc** [comment]
That worked like a charm!  Thank you!

**Comment by JeneferM-MSFT** [comment]
You are so welcome. We will leave this open for others to see until we release the fix. 
Thanks for helping make CoE great!

**Comment by manuelap-msft** [comment]
Thank you for spotting this! I just shipped a new version that fixes this as well.
