### ISSUE TITLE
[FEATURE REQUEST] Have the ability to view the capacity used per environment 

### ISSUE THREAD

**Issue by mwolfaardt** [microsoft/powerapps-tools#578]
It would be great to have a view of how much database space / capacity per user is being utilised

**Comment by manuelap-msft** [comment]
Hello!

Am I right in thinking this is feedback for the CoE Starter Kit? Please note, this repo is used for different solutions and we have notifications set up on labels to ensure question to go to the correct team - when raising a question for a specific solution, please select it from the "new issue" screen. 
![image](https://user-images.githubusercontent.com/55705669/99981119-e5e5ec00-2da0-11eb-87df-ae2da476d086.png)

**Comment by mwolfaardt** [comment]
Thank you for the comment, yes it is for the COE kit.

**Comment by manuelap-msft** [comment]
Great, thanks for confirming!

Yes, that is something we're currently looking into and will hopefully be added soon. In the CoE Starter Kit, we use what's available in the platform - such as the Power Platform for Admins or Power Apps for Admins management connector to get information about environment and apps. We are waiting for the Power Platform for Admins to return capacity per environment, and then we'll include it in the CoE kit. 

I will leave this feature request open and comment on it when we have this available!

**Comment by JeneferM-MSFT** [comment]
We have this tracked on our backlog. Thank you for using CoE
