### ISSUE TITLE
Admin | Sync Template v2 flow throws 403 error (Forbidden) for Team Environment

### ISSUE THREAD

**Issue by xeroOrex** [microsoft/powerapps-tools#579]
**Describe the bug**
Admin | Sync Template v2 flow is showing 403 ERROR when it executes for a Team Environment. The inner exception message says "**Failed to execute Skype backend request GetThreadRequest.**"

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core [e.g. Core, Nurture]
 - 1.71.1
 - Admin | Sync Template v2

**To Reproduce**
1. Execute the the flow manually.

**Expected behavior**
The flow should be executed without any error for any kind of environment.

**Screenshots**
![image](https://user-images.githubusercontent.com/53090923/99499794-74bcc800-299f-11eb-85f7-42455a86e94d.png)

**Additional context**
We have configured the Team connection using service Account which has Power Platform Admin privileges. Could you please let me know if any configuration we are missing here?

**Comment by albertocaa1317** [comment]
I have this same error.

**Comment by manuelap-msft** [comment]
Hello,

this step tries to gather further information about a Microsoft Dataverse for Teams environment. Whilst we investigate this issue, can you help me understand two things

1. Despite the error, has this environment successfully been added to CoE tables - you can check by going to the Power Platform Admin View and selecting Environments to look for this
1. Despite this error, did the flow continue to gather information about other environments and are all your environments present in the CoE table - you can check by going to the Power Platform Admin View and selecting Environments to check if you can see all of them

I'm trying to establish if this error is blocking gathering information for other environments, or if it just means some information for this specific environment is then missing.

Thank you

**Comment by orauch-a** [comment]
I have the same error.
It's on the "Get Teams" action.
I think, it's because the service account must be Teams administrator ?
Can you change this flow so we don't have to add Teams administrator rights in addition to the Power Platform admin rights ?
Thanks

**Comment by manuelap-msft** [comment]
Does your service account have a Teams license?

**Comment by orauch-a** [comment]
No

**Comment by manuelap-msft** [comment]
I think the account will need a Teams license (not Admin) but we are investigating. In the meantime, this error should not be blocking in that all environments should still be collected and shown in the dashboard and admin apps. Can you verify that's true for you?

**Comment by xeroOrex** [comment]
Hi Manuela, PFB my inline comments

1. Despite the error, has this environment successfully been added to CoE tables - you can check by going to the Power Platform Admin View and selecting Environments to look for this. => **_The environment  for which the issue occurred  was not added._**

2. Despite this error, did the flow continue to gather information about other environments and are all your environments present in the CoE table - you can check by going to the Power Platform Admin View and selecting Environments to check if you can see all of them => **_Despite the error the flow continued to work cause all other environments are present inside the Power Platform Admin View_**.

Thank you.

**Comment by orauch-a** [comment]
> I think the account will need a Teams license (not Admin) but we are investigating. In the meantime, this error should not be blocking in that all environments should still be collected and shown in the dashboard and admin apps. Can you verify that's true for you?

I think, if the service account does not have access to the Teams (not Teams admin or not member of the private Teams), the "Get Teams" action will fail.

**Comment by albertocaa1317** [comment]
Hi,
I switch the account of Teams connection with my personal user, than it can be use teams and the flow fails with the same error.

**Comment by WilliamJYoung** [comment]
Hi! We found the same problem and that adding the service account to the Team membership gave us the environment record. Obviously the problem is how do we get access to new environments

**Comment by manuelap-msft** [comment]
Your Power Platform Admin will have access to Microsoft Dataverse for Teams environments to retrieve that information; however getting additional information about the Microsoft Teams the environment is linked to seems to be leading to access issues. But the environment itself you will have access to.

**Comment by manuelap-msft** [comment]
Hello,

thank you for all your feedback on this - we removed the Get a Team action now, and released an update on Friday!

Manuela
