### ISSUE TITLE
Creating unmanaged solution

### ISSUE THREAD

**Issue by shrike94** [microsoft/powerapps-tools#58]
Hello,

In this release, there is no longer an "unmanaged" solution that is provided as part of the kit and the instructions are not overly clear on how to achieve this result.

We have tried a few different techniques but have not been able to achieve an unmanged solution that is the same as the provided managed solution.

Would someone be able to provide more detail and/or a guide on how to create an equivalent unmanaged solution package?

**Comment by manuelap-msft** [comment]
We've updated the documentation to provide more details on how to create unmanaged solutions now.
