### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Flows) | Action 'Get_New_Flow_as_Admin' failed

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/powerapps-tools#581]
Hi,
the flow Admin | Sync Template v2 (Flows) has failed with the error: Action 'Get_New_Flow_as_Admin' failed

Which is the reason of this error? 

Core Components, v.1.71

![image](https://user-images.githubusercontent.com/57954993/99507499-bc355b00-2983-11eb-87d4-2a386b7c684d.png)

Body message:
{
  "error": {
    "code": "FlowNotFound",
    "message": "Could not find flow '5490f993-a331-4f45-8f31-61a5337f7759'."
  }
}

**Comment by JeneferM-MSFT** [comment]
You are failing to get the flow in an apply to each for the list of flows. This sounds like a product bug we have seen in the past.

Can you please go to [flow.microsoft.com](https://flow.microsoft.com/), import the flow below, update to the target environment in the action shown here (your default for this case) and see if it runs successfully? 

![image](https://user-images.githubusercontent.com/62659043/99564471-5cd54c00-297f-11eb-961a-03ebcea4b142.png)

[ListObjects_20201118172334.zip](https://github.com/microsoft/powerapps-tools/files/5561632/ListObjects_20201118172334.zip)

**Comment by albertocaa1317** [comment]
Sorry, but I don't understand your workaround.

**Comment by albertocaa1317** [comment]
The flow attached also fails:

![image](https://user-images.githubusercontent.com/57954993/99804287-0e6cac80-2b3b-11eb-9fd9-c38235fed6bc.png)

{
  "error": {
    "code": "EnvironmentNotFound",
    "message": "The environment 'Default-8a235459-3d2c-415d-8c1e-e2fe133509ad' could not be found in the tenant 'c8e8bdb6-8e7c-41d5-bc41-37fff3c33b75'."
  }
}

{
  "Pragma": "no-cache",
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "x-ms-request-id": "westeurope:6dabd2ee-ebac-4f07-9829-444e2b0a5429",
  "x-ms-correlation-request-id": "6dabd2ee-ebac-4f07-9829-444e2b0a5429",
  "Timing-Allow-Origin": "*",
  "x-ms-apihub-cached-response": "false",
  "Cache-Control": "no-store, no-cache",
  "Date": "Fri, 20 Nov 2020 13:15:38 GMT",
  "Content-Length": "213",
  "Content-Type": "application/json",
  "Expires": "-1"
}

**Comment by JeneferM-MSFT** [comment]
Hello. You did not select your own environment. Your failure is looking for my environment in your tenant.

You need to edit the flow I send above (List Objects) and select the environment from your repro in this action in order to do the test.
![image](https://user-images.githubusercontent.com/62659043/99807686-b612bc00-2af4-11eb-99b6-8bb0f55aade2.png)

**Comment by albertocaa1317** [comment]
Yes, Sorry.

After 20 minutes executing, this flows fails with this error:

![image](https://user-images.githubusercontent.com/57954993/99814562-70341300-2b49-11eb-91de-e92f5df12377.png)

Error Details:
The API 'flowmanagement' returned an invalid response for workflow operation 'Get_Flow_as_Admin' of type 'OpenApiConnection'. Error details: 'The API operation 'AdminGetFlow' requires the property 'body/properties/connectionReferences/0/connectionName' to be of type 'String' but is of type 'Null'.'

One thing that I can see is that the enviroment id of the error in my Admin | Sync Template v2 (Flows) flow not is the same of my Default enviroment: Default-c8e8bdb6-8e7c-41d5-bc41-37fff3c33b75

**Comment by JeneferM-MSFT** [comment]
Is that the same number (83) as you failed in the original loop?

**Comment by albertocaa1317** [comment]
No, in the originial loop fail in the 864.

![image](https://user-images.githubusercontent.com/57954993/99846591-e69b3a00-2b76-11eb-866a-15b8952c07bf.png)

The 83 finish correctly.

I just saw that the previous step doesn't return any data in the output. Maybe the root cause of the issue is here:
![image](https://user-images.githubusercontent.com/57954993/99846929-85c03180-2b77-11eb-9e07-37b03709dd12.png)

**Comment by JeneferM-MSFT** [comment]
No that is expected, that condition is saying: see if the flow is already in the CoE. 
The fact that it returned empty just means the flow has not yet been gathered in the CoE and so it goes down "New Flow" path. 

Do you have access to the flow in question? Can you confirm, if you go there, that the flow itself isnt missing connectors?

**Comment by albertocaa1317** [comment]
How can I found the flow from its ID?

**Comment by JeneferM-MSFT** [comment]
If you go up to the call that listed the flows in the run, you can see all the flows returned.  
![image](https://user-images.githubusercontent.com/62659043/99991238-a6e87400-2d69-11eb-91d9-5aaf41517575.png)

Copy the output into a text editor (if not opened to new browser) and search for the GUID (the 5490r993-etc GUID from above).
From there you will see all the information above the failing flow including name, creator, etc.

**Comment by albertocaa1317** [comment]
OK, thanks for your help:

This is the flow but I can't found it from Admin Portal :(

      {
        "name": "5490f993-a331-4f45-8f31-61a5337f7759",
        "id": "/providers/Microsoft.Flow/environments/Default-c8e8bdb6-8e7c-41d5-bc41-37fff3c33b75/flows/5490f993-a331-4f45-8f31-61a5337f7759",
        "type": "Microsoft.Flow/environments/flows",
        "properties": {
          "apiId": "/providers/Microsoft.PowerApps/apis/shared_logicflows",
          "displayName": "Recibir un recordatorio en 10 minutos",
          "state": "Started",
          "createdTime": "2019-10-27T 10:03:42.0872351Z",
          "lastModifiedTime": "2019-10-27 T10:03:42.3962602Z",
          "flowSuspensionReason": "None",
          "templateName": "2ec8fd1095d711e69e6b05429ec0d0d7",
          "environment": {
            "name": "Default-c8e8bdb6-8e7c-41d5-bc41-37fff3c33b75",
            "type": "Microsoft.Flow/environments",
            "id": "/providers/Microsoft.Flow/environments/Default-c8e8bdb6-8e7c-41d5-bc41-37fff3c33b75"
          },
          "definitionSummary": {
            "triggers": [
              {
                "type": "Request",
                "kind": "Button"
              }
            ],
            "actions": [
              {
                "type": "Wait"
              },
              {
                "type": "OpenApiConnection",
                "swaggerOperationId": "SendNotification"
              }
            ],
            "description": "Use esta plantilla para enviarse un recordatorio retrasado personalizado que se pueda desencadenar con una pulsación de botón, por ejemplo, cuando esté a punto de finalizar una reunión o cuando entre en la oficina."
          },
          "creator": {
            "tenantId": "c8e8bdb6-8e7c-41d5-bc41-37fff3c33b75",
            "objectId": "aae1aae6-7d37-4771-812c-bf9f0a4c3032",
            "userId": "aae1aae6-7d37-4771-812c-bf9f0a4c3032",
            "userType": "ActiveDirectory"
          },
          "provisioningMethod": "FromDefinition",
          "flowFailureAlertSubscribed": true
        }
      },

**Comment by JeneferM-MSFT** [comment]
Got it, thank you for investigating. You seem to have found a product issue then in which List Flows is listing flows that cannot be accessed either form GetFlow action, or from the admin portal. 

Can you please create a support ticket?
