### ISSUE TITLE
[BUG]: Unexpected error (80040216) Uninstalling and Upgrading Core Components from 1.70.2 to 1.71

### ISSUE THREAD

**Issue by Ryn-Ash** [microsoft/powerapps-tools#582]
Unexpected error (80040216) when trying to Uninstall and Upgrade a previous core components solution from 1.70.2 to 1.71 even though the components have remained untouched.

**Componnents**
 - Solution - Core
 - Version - 1.71
 - Import and upgrade previous solution

**To Reproduce**
1. Have Core components v1.70.2
2. Import Core Components 1.71
3. Wait for Uninstall and Upgrade task to complete post import
4. Unexpected error (80040216)

**Expected behavior**
Import of the solution (Which was successful) but to then uninstall and upgrade the previous solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/74664421/99555080-d1c47800-29b7-11eb-875c-0fc3b9c76d70.png)

**Additional context**
I am no coding wizard but usually I can find what has caused the issue through the error log. Logically it doesn't make sense as I have not touched the components within the Solution since I started using it for our environment/org. Please help.

**Comment by manuelap-msft** [comment]
Can you check the solution layers of the flows and canvas apps in the Current 1.70.2 solution and see if there are any unmanaged layers?
See:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

**Comment by Ryn-Ash** [comment]
@manuelap-msft - I will do that and return with a reply!

Thank you!

**Comment by Ryn-Ash** [comment]
@manuelap-msft - I hope I can find my way around not being able to remove the Unmanaged layer.

![image](https://user-images.githubusercontent.com/74664421/99641256-ec433380-2a41-11eb-8d00-f9dce02c6221.png)

**Comment by manuelap-msft** [comment]
Uh oh - whilst we investigate this, could you try one more thing please? Sorry about the back and forth

Could you try to switch to Classic and import the solution from there
![image](https://user-images.githubusercontent.com/55705669/99649172-c6229100-2a4b-11eb-8f42-b5bf9064c87c.png)

During the import please choose "overwrite customizations" when prompted - please note, this will overwrite any changes you have made to any of the components so if there's anything you modified that you need to keep please take a copy of the app or flow before doing that.

Let me know if that works!

**Comment by Ryn-Ash** [comment]
I did try to find the canvas app via the classic view but I Believe that's not functional just yet. I also tried to add the separate component to an unmanaged solution and then try to remove the layer, but unsuccessful.

Here is my failed attempt of an import.
![image](https://user-images.githubusercontent.com/74664421/99652418-b442ed00-2a4f-11eb-8810-f17b2a362e1c.png)

I do have a question though, what would the affects be of deleting the solution all together (as it won't remove components with it but just the solution) and then doing a re-import of the newest version of Core Components?

**Comment by Ryn-Ash** [comment]
And no problem on back and forth, bug reporting is a lifeline to development!

**Comment by manuelap-msft** [comment]
Deleting the solution, as we ship it as managed, would also delete all entities - so any data you already have in the entities would get deleted
1) for entities like Power Apps, Flow, Environments that's not a problem as the first run of the sync flow would populate them again fresh with your tenant data
2) if you have already collected Audit Log data, you would loose that as we can't look back very far with the Audit Log connector

Are you able to download the log file from the classic solution import and share that with me? Could you also let me know what geo your environment is in? 

Thanks for helping us get to the bottom of this!

**Comment by Ryn-Ash** [comment]
Thanks for the information.

Here is the error log of the upgrade attempt
[ErrorDetails_Upgrade Attempt.txt](https://github.com/microsoft/powerapps-tools/files/5566202/ErrorDetails_Upgrade.Attempt.txt)

And the environment details requested
![image](https://user-images.githubusercontent.com/74664421/99656616-09cdc880-2a55-11eb-9b10-a517243e9b1f.png)

I have a security group applied to the environment but that's not caused an issue in the past. I created the environment.

**Comment by manuelap-msft** [comment]
Thank you! Let me look into this and check what release train the UK region is on. I'll get back to you

A security group should not cause issues with the solution install, no.

**Comment by Ryn-Ash** [comment]
Thank you, I hope it isn't too complicated (or that I am just not seeing something)

**Comment by manuelap-msft** [comment]
No, not at all... something has definitely gone awry here. I raised an internal incident for this!

**Comment by manuelap-msft** [comment]
Could you please raise a Service Ticket for this, a support engineer can help get the solution upgrade back to a healthy state? Thank you!

**Comment by Ryn-Ash** [comment]
Thank you very much for the assist @manuelap-msft . 

I will raise a support request once I get past the red-tape of doing that. I will subsequently update here with a resolution once one has been found.

Have a pleasant weekend when you do!

**Comment by manuelap-msft** [comment]
I was able to repo this issue in a new demo tenant - it's likely the same issue you are experiencing so if I get any updates on that thread, I will let you know as well! 

Sorry for the inconvenience you're facing!

**Comment by manuelap-msft** [comment]
It's me again! Hello! It looks like this is a known product issue, impacting some of our early deployment regions like the UK and France - and will be fixed this weekend.

**Comment by Ryn-Ash** [comment]
Thank you for the fantastic news! I really appreciate the good communication!

I have **successfully** upgraded the solution this morning.

**Comment by manuelap-msft** [comment]
That's great news, thank you for confirming and for helping provide valuable repro steps that made finding this product bug easier! I'll close this issue now but please feel free to get back in touch if you see any other issues!
