### ISSUE TITLE
Question about activating "CLEANUP - Admin | Sync Template v2 (Check Deleted)"

### ISSUE THREAD

**Issue by barryanderson** [microsoft/powerapps-tools#583]
Hi,

I have just imported the CoE Core Components 1.71.1.

When turning on the first Flow "CLEANUP - Admin | Sync Template v2 (Check Deleted)" as per the guide [Activate the sync template flows](https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows) I receive an error:

`Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"XrmConnectionReferenceMissingConnection","message":"Connection Id missing for connection reference logical name 'admin_PowerPlatformAdminCoEConnection'."}}".`

I've tried importing again with an overwrite but I continue to get the same error.

I've followed the import documentation in order but continue to get an error.  Am I missing something here?

**Comment by KostyaAfendikov** [comment]
Hi, got same issue as well. Made a copy of this flow and I was able to Turn it on.
After quick investigation can see 
1. that flow in the solution can't get my provided connections.  
2. even if I can refresh connection to all actions like CDS, etc have issue with next one FlowRPCustomConnector (action to get all Flow as Admin) . Again, in my copy of this flow all connections are working and I can enable this flow. 

Do I need to install and overwrite previous version of this CoE solution may be?

**Comment by KostyaAfendikov** [comment]
@barryanderson hi, just found another workaround. I reinstall solution again, but now now with Classic wizard a from https://make.powerapps.com/ and it showed me that one more connection is missing. Added it and now flow could be Turn On ! Try on your env

**Comment by manuelap-msft** [comment]
Hello,

I just saw this issue now - this GitHub repo is used for many different projects, with different teams responsible for different projects. As such, the CoE team only monitors issues that have the "coestarterkit" label which you can automatically get by selecting "CoE Starter Kit Issue" when raising a new issue
![image](https://user-images.githubusercontent.com/55705669/100329471-9af8ee00-2fc5-11eb-94d3-2857cb24806f.png)

This ensures the right people get a notification about this issue.

Are you still experiencing issues here?

**Comment by JeneferM-MSFT** [comment]
Closing out issues whiteout action items. 
Thanks for using the CoE !
