### ISSUE TITLE
[BUG]: Power BI Dashboard Flows "Created this month" showing incorrect data

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#586]
**Describe the bug**
We installed the COE Core Components solution on Friday.. I'm just looking at the Power BI Dashboard and see a difference in what I believe is the same data between different pages.

There is a page called "Overview - Power Automate". The number of Flows "Created this Month" is a much higher number compared to the pages "Overview - Power Apps" and "Overview - Chatbots", which have the same figure for the number of Flows "Create this Month", and a much lower figure. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Dashboard-PowerPlatformAdminDashboard-2020-11-16

**To Reproduce**
1. Go to the page 'Overview - Power Automate'. 
2. In the overview section at the top, look at the blue Power Automate box. The figure in the "Created this Month" section will show a different, higher figure compared to the same section on the "Overview - Power Apps" and "Overview - Chatbots"

**Expected behavior**
I would expect that all three pages show the same figures in the "Created this Month" section. 

**Screenshots**
![image](https://user-images.githubusercontent.com/68440710/99911073-e8393f00-2ce9-11eb-9d04-aa9cfbe45e8d.png)

![image](https://user-images.githubusercontent.com/68440710/99911091-069f3a80-2cea-11eb-9310-eaf05c327f1a.png)

![image](https://user-images.githubusercontent.com/68440710/99911109-1dde2800-2cea-11eb-8422-0e6784da4fbe.png)

**Additional context**
None.

**Comment by manuelap-msft** [comment]
Hello,

thank you for bringing this to our attention! It's looking okay on my side - can you confirm you see this filter when you highlight the visual:
![image](https://user-images.githubusercontent.com/55705669/99955629-9b527880-2d7c-11eb-8134-43218b5cb70b.png)

If not, you can add the filter yourself and we'll make sure to double check it's added when we next deploy the dashboard!

Thank you
Manuela

**Comment by GarryPope** [comment]
Hello Manuela,

Thanks for the speedy reply and good description. Power BI is not my strong point, so I hope I'm doing it correctly. 

I checked the "Overview - Power Apps", the one that is showing correctly, and it has a filter. 
![image](https://user-images.githubusercontent.com/68440710/99969586-9b5d7300-2d92-11eb-947f-741dcb4a7f50.png)

When I checked the "Overview - Power Automate", the one showing incorrectly, and there isn't a filter.
![image](https://user-images.githubusercontent.com/68440710/99969570-913b7480-2d92-11eb-92f9-05329b956208.png)

When I added your suggestion it worked perfectly!
![image](https://user-images.githubusercontent.com/68440710/99971035-926da100-2d94-11eb-9ea8-bdef640a471b.png)

Note: on the screenshot above on my filter I'm not seeing the "Filter type" = "Relative data", although I might just be doing something wrong. 


And finally, if you look at the screenshots at the beginning of this ticket, I just noticed for "Overview - Power Automate" my custom connectors are also showing incorrect data. They are showing 435, where the other two pages are showing 10, which is the correct number. On the "Overview - Power Automate" the filter for adminiscustomapi is set to All, where on the other pages it is set to True.

I'm happy to raise a new issue for this if you want me to?

Thanks,

Garry

**Comment by manuelap-msft** [comment]
Thanks for providing the detailed screenshots - super helpful!

When you go to the Filter pane and select the admin_flowcreatedon, you should be able to select Filer Type: Relative date
![image](https://user-images.githubusercontent.com/55705669/99977024-1414fd00-2d9c-11eb-943d-adf53167607a.png)

Where you can then specify a relative date, such as "in the last 30 days"
![image](https://user-images.githubusercontent.com/55705669/99977098-255e0980-2d9c-11eb-82a0-c20dfd868e7a.png)

Yes, for Custom Connectors the Filter should be set to admin_iscustomapi = true. That's under Basic Filtering, and then you select "true" from there.
![image](https://user-images.githubusercontent.com/55705669/99977220-4161ab00-2d9c-11eb-8ff6-0abb54cd0372.png)

Thanks for highlighting those - I have them fixed locally, and with the next update we'll make those changes!

**Comment by GarryPope** [comment]
Hello Manuela. 

Thanks for the reply.

On my Power BI report I'm not seeing the "Filter type" = "Relative data", but no worries. I've got the filter to work as per your instructions. I'll wait for the update release. 

Anything else, just shout. Happy to help.

Garry

**Comment by manuelap-msft** [comment]
Updated with the new release that just went out. Thank you!
