### ISSUE TITLE
[BUG]: Add permissions button colour on canvas app "Set Flow Permissions"

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#588]
**Describe the bug**
When using the canvas app "Set Flow Permissions" the button "Add Permissions" turns a dark colour and I can't read the button text when a Flow is selected in the gallery. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.71.1
 - App or Flow: Canvas app: Set Flow Permissions 

**To Reproduce**
1. Go to canvas app Set Flow Permissions
2. Click on an environment
3. Look at the button called Add Permissions it is easy to read
4. Select a Flow from the gallery
5. The button turns a dark colour making it impossible to read the name of the button

**Expected behavior**
As this doesn't happen on the canvas app Set App Permissions, I would expect it to work the same. This of course is a minor thing, but thought I'd mention it. App is working correctly, just a minor thing. 

**Screenshots**
![image](https://user-images.githubusercontent.com/68440710/99973072-4708c200-2d97-11eb-80d3-b043a8c03367.png)

**Additional context**
Nothing else to add. Thanks.

**Comment by JeneferM-MSFT** [comment]
Hello. We can update the fill color here, do note that its just the same string as before you selected the flow. It still sayd "Add Permissions"

**Comment by GarryPope** [comment]
Hello Jenefer, 

Great. Just wanted to flag it up. I'll wait for the next release.

Thanks very much,

Garry

**Comment by JeneferM-MSFT** [comment]
Of course! I have this local fixed now. Thanks for using CoE!

**Comment by manuelap-msft** [comment]
Updated with the new release that just went out. Thank you!
