### ISSUE TITLE
App Archive and Clean Up - Check Approvals and Archive Flow

### ISSUE THREAD

**Issue by olthomps** [microsoft/powerapps-tools#59]
After approval, when this flow triggers, I (and another admin) get an error on the "Parse JSON - Archive Approval Item" action: _InvalidTemplate. Unable to process template language expressions in action 'Parse_JSON_-_Archive_Approval_Item' inputs at line '1' and column '10746': 'Required property 'content' expects a value but got null. Path ''.'_. 
The output of the previous action "Filter Archive Approval to get current item" returns an empty object. Looks like there's a mismatch when the Approval Response entity is updated. Somehow the actual approval response does not update the "Approval Response" entity. 

https://make.powerapps.com/environments/c568f516-5ea0-488d-a543-daad946c028c/logicflows

**Comment by audrieMSFT** [comment]
Apologies for the delay in response. Could you confirm that this issue still persists? I'm happy to investigate what might be causing the error/null value if so.

**Comment by JeneferM-MSFT** [comment]
Closing out old issues without existing action. Please let us know if you have issues in the future!
