### ISSUE TITLE
Data missing from Power Platform User Role table

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#590]
Hi,

After applying a fresh version of CoE toolkit 1.71.5 on Friday (Nov 20), and letting the flows run over the weekend, I noticed that the Power Platform User Role table is still missing data.  I enabled the (Power Apps User Shared With) flow, and changed its schedule to run daily after all of the sync flows and the (Check Deleted) flow complete.

There are apps in Power Apps App that do not exist in Power Platform User Role.  There are also apps listed in Power Platform User Role, but not every user/group shared appears.

For this example, I have an app that is active in an environment, it appears in Power Apps App but does not have any "shared with" data.  

Data from CoE shows it exists as an app and counts some sharing, but the list is blank.
![image](https://user-images.githubusercontent.com/50427725/99997967-c637cf00-2d72-11eb-915a-758b804f1daa.png)

As an admin, I can view the sharing info.  This app actually has more shares than what CoE thinks it has.  For reference, all of the users/groups in this screenshot are valid (they still exist in AAD).  Because I blurred things out, here is how it looks:

![image](https://user-images.githubusercontent.com/50427725/99998009-d780db80-2d72-11eb-929f-baf95b2c4a85.png)
User 1 --> individual
User 2 --> group
Owner --> individual
Co-Owner --> group
I can find the app in Power Apps App, but can find no rows in Power Platform User Role.

Also, like we discussed in an earlier issue, my tenant shouldn't be so large that I'm running into timeouts.  Out of 10 environments CoE crawls, there are just over 310 apps (SharePoint, Canvas, Model Driven)

Currently, my Power Platform User Role table has 282 rows, but it should have quite a bit more.

Thoughts?
Thank you!
Christi

**Comment by JeneferM-MSFT** [comment]
Can you please go the runs for the (Power Apps User Shared With) flow and see if they passed successfully? 

<img src="https://user-images.githubusercontent.com/62659043/100002815-ed45cf00-2d79-11eb-8e13-b6ff3dd35a21.png" width="500">

If so, please enter the latest successful run and go to the envt of interest in the run, you can do this by clicking next until you see it (look for "friendlyName:"  in the output as shown here)
![image](https://user-images.githubusercontent.com/62659043/100003412-e4a1c880-2d7a-11eb-8ca8-145ac39a6575.png)

Then walk the apps in that environment until you see the app that is showing incorrectly. 
We have catch statements in there and so we need to see where / if you are catching.

**Comment by osbornecc** [comment]
Hi Jenefer,

OK, I found my environment and the app in question in that section of the flow.  All runs of the flow this weekend were successful.  All items are completed successfully, and none of the "catches" ran.  The results are the same for all 4 shared with (both users and groups).

On the "switch" section (which I did not expand in my screenshots), it ran as expected....It set the "size" to 1 for users and to the actual group size for groups.  

![image](https://user-images.githubusercontent.com/50427725/100014286-04d98380-2d8b-11eb-9743-4acbc812c637.png)
![image](https://user-images.githubusercontent.com/50427725/100014320-0f941880-2d8b-11eb-955b-3c6d4fabdf67.png)

Is there something I'm missing?  I dug into the Switch output and it appears to be trying to update Power Platform User Role instead of inserting a new record.

Thanks,

**Comment by osbornecc** [comment]
Digging into the data further, I may be onto something.  At first glance it looks like Power Platform User Role has one (and only one) row per user/group.  For instance, I know there are many apps shared with a particular group or created by a particular user.  However, Power Platform User Role seems to be only showing one row for that group or user.  In the past it had _at least_ one row per group/user depending on how many apps they owned/were shared with.

I need to make 100% sure this is what I'm seeing so I'll update in a but, but this looks like it may be my problem.

**Comment by osbornecc** [comment]
Hi there,
Yep that seems to be my problem.  Only one row per user/group in Power Platform User Role.

For example, I found the row that said it was shared with the GUID "tenant-xxxx-xxxx-xx".  That pointed to one particular app.  We have multiple apps shared with the tenant, or "everyone" if you look in the app itself.  Those apps do not show up in Power Platform User Role with the shared with GUID of "tenant-xxxx-xxxx-xx".

Does that make sense at all?
Thanks,
Christi

**Comment by manuelap-msft** [comment]
Yep, that makes sense - thanks for the detailed analysis - that's very helpful! We recently moved this flow from running when an environment was created or updated to running on a schedule and may have introduced a bug in the logic there where it performs an update, instead of an insert. 

We'll look into this and run some more tests on our side and get back to you when a fix is available!

Thanks again for your time in analysing the issue you're seeing!

**Comment by osbornecc** [comment]
Glad to be of help!
I find the data that comes from CoE to be extremely useful (and management likes it too :-) ).  Yes, I noticed the flow trigger changes.  Since we must use the "cleanup" flows for now, I make them run daily.

Looking forward to the next update!

**Comment by manuelap-msft** [comment]
THANK YOU! Thanks to your fantastic analysis and noticing that you only see one row per user/group, we were able to find the issue in our flow and are just updating and testing it now. We'll ship a new version addressing this issue either tonight, or early tomorrow morning depending on how our testing goes.

Thanks again - it's so wonderfully useful that you did this analysis!

**Comment by manuelap-msft** [comment]
I've just released a new version where this should be fixed. Here's recommendations on how to install updates: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

I'm closing this issue now but please feel free to get back in touch if you continue to see inconsistencies here! 

Thank you for using the CoE!
