### ISSUE TITLE
[BUG]: Edit Environment variable from managed solution

### ISSUE THREAD

**Issue by m3ngi3** [microsoft/powerapps-tools#591]
**Description**
Updated the Center of Excellence - Nurture Components to V1.23.
Cannot update the variables: "This environment variable definition cannot be edited because it is in a managed solution."

**Reproduce**
I imported the Solution and tried to update Environment Variables.
Tried with **Training In a Day - Feedback Form** but also other Variables behave the same:
1=Edit through Solution interface:
![image](https://user-images.githubusercontent.com/47530580/100088931-3452c380-2e51-11eb-876c-35456e58ce0f.png)
Notification = 

2=Edit through CDS Tables interface:
![image](https://user-images.githubusercontent.com/47530580/100089275-b7741980-2e51-11eb-9b73-10bc5c7667de.png)
Notification = You do not have permission to access these records. Contact your Microsoft Dynamics 365 administrator for help.

How can we update environment variables? I recollect this used to be easy but something changed?
Documentation https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/environmentvariables states that Current Values should be deleted before exporting Unmanaged to Managed --> if this is done, it will popup the environment variable update notification when importing the solution.
But... even if someone did not remove the Current Value --> system admins of an environment should be able to edit these records right?

**Extra**
I also created a very simple unmanaged solution, did not remove the Current Value, exported as managed, imported into clean environment and Environment Variables behave the same as above.
I even updated the unmanaged solution with deleted current values, exported as managed, imported to a new version into existing environment --> behavior stays the same.

Am I missing something here?

**Comment by JeneferM-MSFT** [comment]
Hello. Thanks for using CoE! 
With recent changes, you cannot change the env vars in the managed solution anymore, you either have to change with the flyouts from setup, or you have to go to the Default solution to edit them there.
 
Feedback has been given to the product team about this change.

**Comment by m3ngi3** [comment]
Always a pleasure to see your fast response @JeneferM-MSFT 👍

I can see some advantages in this setup from a Software Vendor point of view to block the edit of solution specific variables... However some variables defintely need to be updated through differente ALM Environments... like in the CoE case where I want to provide a different link to the feedback Forms and **I do not have the unmanaged solution**. 

Any thoughts from your "workaround mindset" 😁

**Comment by manuelap-msft** [comment]
You should be able to update all Environment Variables if you navigate to the **Default Solution** of your environment.
![image](https://user-images.githubusercontent.com/55705669/100104036-94e7fd80-2e5d-11eb-9a35-a23c8fcffab3.png)

Environment Variables without a Default Value can be updated during import, Env Variables with a default value can be updated from the Default Solution.

As you tried this in a solution independent from the CoE Starter Kit and are still experiencing issues, I'm afraid this channel might not be the best to get advice as it's product feedback rather than CoE starter kit feedback. I would suggest raising a Support Ticket if you continue to see issues!

**Comment by JeneferM-MSFT** [comment]
Sorry, yes I think I wasnt verbose enough for a change. So what Manuela said.  :)

**Comment by m3ngi3** [comment]
Will do!
Just to be complete @manuelap-msft in this post:
The Default Value of Environment Variables you are showing is part of the Environment Variable **Definition** Table and I can confirm that records in this table are still possible to change...

However just like you are doing in the CoE kit: I have been promoting to use the Environment Variable **Value** Table to store the actual Value for an Environment Variable in that specific Environment. The records in these table seem to be uneditable in any way for any role.

I have to confirm by testing through different environments but even when you have access to the Unmanaged Solution and change the Value record here --> previously imported Managed Solutions will not accept an upgrade because of this "lock"

For now this looks like a major bug that prevents me from using the full Application Lifecycle Management options of Power Platform...

**Comment by m3ngi3** [comment]
...and you will probably have the same issues when rolling out upgrades to the CoE Kit components...

**Comment by manuelap-msft** [comment]
We once accidentally left the Current Value in the solution when we shipped and that lead to the import failing due to missing dependencies. So I don't think shipping with current values in the managed solution is even possible. 

Jenefer and I are picking this up internally as well!

**Comment by m3ngi3** [comment]
@manuelap-msft --> I thought that you meant to go the Entities / Tables of the Data in the Environment:
![image](https://user-images.githubusercontent.com/47530580/100203387-d41c5a00-2f02-11eb-9e93-379eda72205d.png)
When I try to edit this way it says: "You do not have permission to access these records. Contact your Microsoft Dynamics 365 administrator for help."
![image](https://user-images.githubusercontent.com/47530580/100203706-3e34ff00-2f03-11eb-83b8-8da502c37dfe.png)

I never dared to open up the Default Solution because we have been told by all the Experts: **never touch the Default Solution of an environment**. 😁
So based on your info I opened up the Default Solution and tried to edit the Current Value here:
![image](https://user-images.githubusercontent.com/47530580/100203819-5e64be00-2f03-11eb-9383-a1d1933194e0.png)
but as you can see: "
This variable didn't save properly. Definition with ID 925ebda3-00ca-4655-91e1-b950037fb583 already has a value.
"

**Comment by manuelap-msft** [comment]
What region is your environment in?

**Comment by m3ngi3** [comment]
Our CoE Demo environment is Europe:
![image](https://user-images.githubusercontent.com/47530580/100204266-f5ca1100-2f03-11eb-84c8-1bc58e654daf.png)

**Comment by manuelap-msft** [comment]
And this error is happening for all of your Environment Variables, not just one from a specific solution? e.g. is it also happening for the ones from the Core components for example?

(Sorry for the influx of questions!)

**Comment by m3ngi3** [comment]
No problem at all! I love the way your team is so helpful to a noob like me 💪👍

My last screenshots were with CoE - Nurture Components --> V1.23
![image](https://user-images.githubusercontent.com/47530580/100206118-388ce880-2f06-11eb-99e5-839c5efc4f3b.png)

My next test is with the Power Platform Make Office 365 Group Environment Variable in the same CoE component --> 
![image](https://user-images.githubusercontent.com/47530580/100206298-70942b80-2f06-11eb-9be2-186a4ea75b96.png)
Here it worked!!! 🤔

My next test is with the Admin eMail Environment Variable in the CoE - Core Components --> 
![image](https://user-images.githubusercontent.com/47530580/100206763-0c259c00-2f07-11eb-9409-ff068362e041.png)
Access it through Default Solution for a change -->
![image](https://user-images.githubusercontent.com/47530580/100206822-1c3d7b80-2f07-11eb-8025-1fc5d78c7b47.png)
And it updated -->
![image](https://user-images.githubusercontent.com/47530580/100206918-4000c180-2f07-11eb-8a47-cfa51faa1896.png)

I am going to test with some of my own (un)managed solutionis now. Thank you!!!

**Comment by m3ngi3** [comment]
Added an extensive video here: https://www.youtube.com/watch?v=ba9uLT4S_7c

**Comment by manuelap-msft** [comment]
Thank you! unfortunately we can't support product issues here, so you will have to raise a support ticket to get the right level of support and get this raised accordingly.

**Comment by m3ngi3** [comment]
Yes 👍
Already in contact with Microsoft (Dynamics) Team. Would you like me to close this ticket here or should I update the outcome in time?

**Comment by manuelap-msft** [comment]
Awesome! Thank you! No we can leave it open so others who experience the same issue can read up on it

**Comment by djmc90** [comment]
If you are having trouble setting these values, you can do so in the .ZIP file before you import the Solution.

Using the CoE Core Componenets as an example, to set the 2 variables:

1) Unzip the CoE Starter Kit
2) Open up CenterofExcellenceCoreComponents_1_71_7_managed
3) Open up customizations.xml
4) Search for Power Automate environment variable and set (i.e. for EMEA env):      <DefaultValue>https://emea.flow.microsoft.com/manage/environments/</DefaultValue>
5) Search for Admin eMail and set it's default value accordingly like above
6) Save your changes and replace the existing file in the ZIP.

Now import this ZIP file and your values will be set on import.

I was getting the error, so i had to import in classic mode as above

Hope it helps.

**Comment by m3ngi3** [comment]
Thanx @djmc90 --> you are talking about default value but this post about **current value**.
Your approach however pointed me towards a workaround: In my export there is a JSON file with the Environment Variables Current Values. After changing the values AND the record GUIDs here it is a possibility.

Seee https://powerusers.microsoft.com/t5/Microsoft-Dataverse/Updating-Environment-Variables-in-Managed-Solution/m-p/767262#M8591 for details. Will close this post 👍
