### ISSUE TITLE
[BUG]:office 365 Management APIs has been added to Enterprise Applications Rather then App Registrations

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#592]
**Describe the bug**
Installed  version 1.71.5 on a  development tenancy with version 1,54 on the production Tenancy

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - core
 - Version  - 1.75.1
 - App or Flow Child flow

**To Reproduce**
1,  Update solution on development tenancy  to 1.75.1

**Expected behavior**
I expect updated flows to work.

**Screenshots**

**Additional context**
The connector "Office 365 Management APIs" would have appeared to have moved from App Registrations to Enterprise apps in Azure on the development tenancy.  I cannot now log into the Office 365 Management APIs connector because the REdirect URL presented by the login is not the same as the one on the Enterprise Apps Office 365 Management APIs .

Where there is only one tenancy per enterprise, this works OK and Office 365 Management APIs is in the App registration part of the Azure Active Directory.

**Comment by JeneferM-MSFT** [comment]
CoE doesnt support multi tenant. Audit logs are per tenant as well so we would not be able to address this.

**Comment by NPrice99** [comment]
Hi Jennifer

So what am I supposed to do then ?

I have a situation where I have two Azure tenancies for the one enterprise.

CAn untangle the mess ?

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
I would presume that installing the toolkit anew on the other tenant would work. 
But again, the logs themselves arent even multi-tenant, so there is truly nothing the toolkit could do to support multi-tenancy here.
