### ISSUE TITLE
[BUG]: Last Refresh Date has disappeared in 1.75.1 

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#593]
**Describe the bug**
The Refresh DAte has disappeared when Installing 1.75.1

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - core
 - Version - 1.75.1
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**
1. install version 1.75.1 of core components

**Expected behavior**
I expected the Refresh Date still to be on the Overview - PowerApps page

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/100093242-2ac85c00-2e4f-11eb-8ed2-cbc2baec645a.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
We removed this because it was confusing what it meant was refreshed (data model, access to data model, which tables in data model).

Thanks for using CoE
