### ISSUE TITLE
[BUG]: Power Platform Admin View app - Choice field Finace spelling mistake

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#595]
**Describe the bug**
Hello,
In the "Power Platform Admin View" model-driven app - when editing a "PowerApps App" record, in the "Admin Review" section is a choice field called "Category". One of the values is **Finace**, but I think it is mean to be "Finance", right?

**Component (please tell us which flow or app you are experiencing issues with):**
 - App or Flow: Power Platform Admin View

**To Reproduce**
1. Go to Power Platform Admin View model-driven app
2. Click on Apps down the left hand side
3. Select an app record
4. Select the Audit tab
5. In the "ADMIN REVIEW" section, click the field "Category" and scroll down to the value Finace

**Expected behavior**
I think it should say Finance. I even Googled what does Finace mean, haha,, but couldn't find anything for it, so I think it might be a spelling mistake,

**Screenshots**
![image](https://user-images.githubusercontent.com/68440710/100116502-b9e36d00-2e6b-11eb-9ece-da6fb0b04d87.png)

**Additional context**
Nothing else. Thanks.

**Comment by manuelap-msft** [comment]
Thank you! Haha, it's clearly not something we look at very often - just fixed and will go out with the next release!

**Comment by manuelap-msft** [comment]
Updated with the new version that we just released. Thank you for using the CoE!
