### ISSUE TITLE
Audit Log Solution Import failed

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#596]
**Describe the bug**
Import solution Center of Excellence: Audit Logs failed and also unable to find the connection reference. I have tried as a classic way and modern Import both does not work. Classic import failed and I have attached the screenshot.  Modern Import does not show a connection reference at all.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Audit Logs
 - Version - 1.3.2

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/100153615-5872cc80-2e72-11eb-828d-007bdbed8358.png)

![image](https://user-images.githubusercontent.com/59940632/100153749-8e17b580-2e72-11eb-9736-640a3d15d99f.png)

**Additional context**

**Comment by manuelap-msft** [comment]
You will need to configure the custom connector prior to import, see https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector

**Comment by NPrice99** [comment]
Is your Audit Log just for this tenancy, or is it an enterprise-wide Audit log ? If it is the latter then the Office 365 Management API connector will not work.

**Comment by NPrice99** [comment]
I also had a failure loading the Audit Log Solution :-

![image](https://user-images.githubusercontent.com/8484048/100166437-aad4dd00-2eb4-11eb-92f5-331ffefd964b.png)

I have an XML file generated by the error but GitHub does not support loading XML file types !

THis is for a single tenancy Log File.

**Comment by manuelap-msft** [comment]
@aakashpatel660 It looks like there's an issue with the latest solution we have available in Upgrade scenarios. In the meantime, you can use the previous version still https://github.com/microsoft/powerapps-tools/raw/e1cb95268013fcff06e74c7bc0586f1a40fad401/Administration/CoEStarterKit/PreviousSolutionVersions/CenterofExcellenceAuditLogs_1_0_0_20_managed.zip

**Comment by aakashpatel660** [comment]
Yes, I will use the previous version

**Comment by NPrice99** [comment]
Hi Manuela - so are you going to fix version 1.3.2 ?

**Comment by manuelap-msft** [comment]
There's nothing broken from our side:
Version 1.0.0.20 uses connections (where you have to go and manually configure the flows to point to your connection)
Version 1.3.2 uses connection references (where you specify the connection to use during import)

The flows and functionality are exactly the same. A product issue is causing @aakashpatel660 upgrade issue, but it's not something we have control over, and nothing that is "broken" in the CoE kit.

**Comment by NPrice99** [comment]
I have the same problem but I cannot upload the XML file with the error in it.

**Comment by manuelap-msft** [comment]
If you are experiencing the same error, the old solution https://github.com/microsoft/powerapps-tools/raw/e1cb95268013fcff06e74c7bc0586f1a40fad401/Administration/CoEStarterKit/PreviousSolutionVersions/CenterofExcellenceAuditLogs_1_0_0_20_managed.zip that just uses connections should work for you. We did not change any functionality between the versions.

**Comment by NPrice99** [comment]
I am just trying to upgrade to 1.0.0.20 first.

**Comment by NPrice99** [comment]
Even after to upgrading from 1.0.0.20, upgrading to 1.3.2 still fails

**Comment by manuelap-msft** [comment]
Yes, because of a product issue. A clean install of 1.3.2 in a brand new environment will succeed (if you have Core installed first).

**Comment by NPrice99** [comment]
so delete all versions of Centre_of_Excellence - Audit Logs and then install 1.3.2

**Comment by manuelap-msft** [comment]
Only do that if you are in a test tenant. If you are in a prod tenant, deleting the solution will also delete the tables and all their data - you will loose all your data. 

If 1.0.0.20 works for you, there is no need to upgrade to 1.3.2 - like I said, the functionality is **exactly** the same (we actually haven't changed those flows in months), the only difference is that the flows use connection references which make for a simpler setup experience.

**Comment by NPrice99** [comment]
1.3.2 failed after clearing out Audit Logs - Expected Non-empty GUID
