### ISSUE TITLE
[BUG]: Which are those entities that requires to be migrated in the staging environments first time?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#597]
Hello,

I have a question regarding deployment across the environment.

As an MPP Admin, CoE Starter Kit (1.70.2) was deployed in the "Dev" environment, then switched on all the flows which has updated CoE Entities and "Approval Response" entities for all the users via Sync and Archival flows.

Now, the same solution needs to be deployed in the "Test" environment for the same org users. I assumed "Approval Response", PowerApps App", "Flow" and "PVA" entities needs to be migrated into the "Test" environment, so that it retains current state of data when flows are turned on in the "Test" environment.

Can you please confirm on above steps ? or I am missing any entities data to be migrated?

Thanks and Regards,
Dipti

**Comment by manuelap-msft** [comment]
Data is never migrated when you deploy a solution from a Dev to a Test environment, only solution components and the tables with their fields are installed in the target environment but the data will remain empty. If you require data to be moved from one environment to another, you will have to do that manually although we don't recommend that as Unique IDs may change and cause you to see inconsistency in data.

The assumption is that in your dev / test environments you have test data, and only in your production environment you want clean prod data.

**Comment by dips23** [comment]
Thank you Manuela to clarify this, 

Does it mean that CoE kit should be customised/tested for test/dev environment in the "Test/Trial Tenant" with real test users ( In order to produce test data) instead of "Org Tenant" with real actul users?

Best Regards,
Dipti

**Comment by manuelap-msft** [comment]
This really depends on your organisation setup, and how you are delivering the CoE project and we are unable to provide advice here. 

We would recommend having a Dev environment where you make any customizations in an unmanaged solution ("My CoE Customization" that you then deploy as a managed solution together with the other managed CoE solutions to a test and production environment. Independent of where the kit is installed, the sync flows will always gather data for the entire tenant.

How you do that will really depend on your organisation
e.g. do you have a test team or will real users be testers? are you using a test tenant or a test environment in the same tenant? are you using deployment automation via Azure DevOps including approvals or manually deploying via import/export?

Those are all things to consider, but how you implement this will be up to your organisation!

Thank you for using the CoE!
