### ISSUE TITLE
[QUESTION]: When Welcome Email is considered to be sent to which user?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#598]
Hello,

As I see in the document that "Welcome Email" is sent when user creates new app - does it mean user creates an app "first time"? which is identified from the Maker Table - does it mean, that only users in the maker table are active in the Power Platform regardless the users with power platform license in the organization?

**Admin | Welcome Email**
Sends an email to a user who created an app, flow, custom connector, or environment. This flow gets triggered when a new record is created in the maker table.

Can you please clarify when "Maker" table is updated via CoE  Starter Kit?

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
The welcome email is a welcome to the platform, so it is sent only for new users of the platform. 
We know someone is a new user to the platform when we dont yet find them in the maker table. 

The maker table is the table where we hold all the users that create apps/flows/etc.
The first time you make such an object, you are put in the Maker table and sent a welcome mail. 
Future objects you make do not receive the welcome mail. 

HTH and thanks for using CoE

**Comment by dips23** [comment]
Great!! Thank you for your time clarifying that :)

Regards,
Dipti
