### ISSUE TITLE
[BUG]: DLP Editor and Customiser missing from Core Components solution

### ISSUE THREAD

**Issue by bennyboy23** [microsoft/powerapps-tools#599]
When importing the core components, I have noticed that the DLP Editor and Customiser apps have been removed or are missing from the solution. Is this expected? its still listed in the documentation but it isnt in the deployed solution.

**Comment by manuelap-msft** [comment]
Hello,

yes, these components have been removed due to a limitation with the Power Platform for Admin connector not supporting three way DLP policies (business/non-business/blocked). 

Where in the documentation did you find a reference to them? We thought we had updated it in all places :)

**Comment by bennyboy23** [comment]
Hi Manuela,
Ah apologies I have re-looked in the docs and i mustve been looking at an old / cached version as there no longer is a reference to the DLP Canvas apps. Do we know when these will be restored, if at all? They are really good components and a massive selling point for administrators.
Thanks,
Ben

**Comment by manuelap-msft** [comment]
Great, thanks for confirming!

Here, we are dependent on product features in the https://docs.microsoft.com/en-us/connectors/powerplatformforadmins/ connector but we are working with the connector and DLP team to get the management connector updated to recognize all three DLP groups. Once that update is available, we will work on updating and adding the DLP apps again but I can't provide a timeline at the moment! 

I'll close this issue now, but once we have more details I can give you an update here.
