### ISSUE TITLE
Flow (Power Apps User Shared With) - failing for Default environment

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#601]
Hi there!

I mostly wanted to say THANK YOU for the update yesterday!  The flow is still chugging along, but so far the data looks much better.

There is one thing I wanted to let you know about though.  I did have to make an update to the flow because it was failing on my Default environment.  Similar to the (Check Deleted) flow, it was looking for an environment with an ID of "Default-xxx-xxx-xxx" but inside CoE the ID was just "xxx-xxx-xxx"

I made the following changes to (Power Apps User Shared With) and it stopped failing.....at least for me.  Not sure if my fix is universal.

**Changed API version first....didn't fix, but I left it with my update since the Check Deleted used this API version**
![image](https://user-images.githubusercontent.com/50427725/100269652-bbfd0880-2f0b-11eb-8e8c-2f16dfeb29f6.png)

**Then updated the Compose to strip out the text "Default-" if it was found**
![image](https://user-images.githubusercontent.com/50427725/100269716-d0d99c00-2f0b-11eb-8446-d1cb5cb31570.png)
![image](https://user-images.githubusercontent.com/50427725/100269726-d505b980-2f0b-11eb-9915-6f45c12554f1.png)

Thanks again for the updates!
Christi

**Comment by manuelap-msft** [comment]
You are most wonderful! Thank you for letting us know about this issue, we will test and incorporate that with the next version

**Comment by orauch-a** [comment]
I think the problème is in the "**Get Envt from CoE**" action :

You must replace **admin_environmentid eq @{outputs('Envt_Name')}** by **admin_environmentname eq '@{outputs('Envt_Name')}'**

Do not forget to add the quotes around the output !!!

![image](https://user-images.githubusercontent.com/34766578/100437078-89d0df80-30a0-11eb-96df-6253aa44aa27.png)

**Comment by JeneferM-MSFT** [comment]
I have this local fixed now. Thanks again for helping make CoE great!

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with this fix, as well as a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!
