### ISSUE TITLE
[BUG]: Spelling mistake on "Admin Requirement - Risk Assessment" value "Neglegable"

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#602]
**Describe the bug**
Sorry to be such a pedant, but I saw that the field "Admin Requirement - Risk Assessment" has a value of"Neglegable" and I believe it should be "Negligible".

**Component (please tell us which flow or app you are experiencing issues with):**
 - App: Power Platform Admin View

**To Reproduce**
1. Go to App: Power Platform Admin View
2. Click on a PowerApps App record or a Flow record
3. Click the "Audit" tab
4. On the field "Admin Requirement - Risk Assessment" select the value "Neglegable"

**Expected behavior**
I think the value should be "Negligible". This is on both the Flow form and the Apps form.

**Screenshots**
![image](https://user-images.githubusercontent.com/68440710/100321214-3dab6f80-2fba-11eb-875c-057a0ba6c5b7.png)

![image](https://user-images.githubusercontent.com/68440710/100321279-574cb700-2fba-11eb-987b-d0f247d43cb4.png)

**Additional context**
Sorry I didn't spot this before you sent out the latest release of 1.71.7 with the other change.

**Comment by manuelap-msft** [comment]
We just released a new version now where this is fixed. Thanks for the update, and for using the CoE kit!
