### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Custom Connectors) - missing filter query

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#604]
**Describe the bug**
On "ListDefns-PowerAutomateEnvironmentVariable" action and on "ListCurrents-PowerAutomateEnvironmentVariable" action, filter query is missing :
![image](https://user-images.githubusercontent.com/34766578/100364703-c3e9a500-2ffe-11eb-9ff0-744e9eed3e29.png)

Must be :
For "ListDefns-PowerAutomateEnvironmentVariable" action : schemaname eq 'admin_PowerAutomateEnvironmentVariable'
For "ListCurrents-PowerAutomateEnvironmentVariable" action : _environmentvariabledefinitionid_value eq @{outputs('GetDefnID-PowerAutomateEnvironmentVariable')}

**Comment by JeneferM-MSFT** [comment]
Thank you for posting! This is now local fixed and will ship with the next release.

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with this fix, as well as a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!
