### ISSUE TITLE
[BUG]: Apps Sync Flow does not start on initial run and fails on second when trying to upsert maker 

### ISSUE THREAD

**Issue by petepuu** [microsoft/powerapps-tools#606]
First run after Core import the Apps Sync Flow didn't start for some reason. Started main sync flow again and Apps did run as well this time but failed against default environenment when updating/inserting App Maker to table with error **Action 'Upsert_New_App_Maker_record' failed.** Have seen this behavior many times after Core import and when running first time Sync Flows

{
  "status": 412,
  "message": "--batchresponse_ab70155f-443f-4014-84ec-c2dd408e7650\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 412 Precondition Failed\r\nREQ_ID: da2916b1-381a-4d03-9b98-29ae6f03187f\r\nContent-Type: application/json; odata.metadata=minimal\r\nOData-Version: 4.0\r\n\r\n{\"error\":{\"code\":\"0x80040237\",\"message\":\"**A record with matching key values already exists.**\"}}\r\n--batchresponse_ab70155f-443f-4014-84ec-c2dd408e7650--",
  "error": {
    "message": "--batchresponse_ab70155f-443f-4014-84ec-c2dd408e7650\r\nContent-Type: application/http\r\nContent-Transfer-Encoding: binary\r\n\r\nHTTP/1.1 412 Precondition Failed\r\nREQ_ID: da2916b1-381a-4d03-9b98-29ae6f03187f\r\nContent-Type: application/json; odata.metadata=minimal\r\nOData-Version: 4.0\r\n\r\n{\"error\":{\"code\":\"0x80040237\",\"message\":\"A record with matching key values already exists.\"}}\r\n--batchresponse_ab70155f-443f-4014-84ec-c2dd408e7650--\r\n"
  },
  "source": "org7290ef9f.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 933086a2-232d-432e-8809-793cde380f02"
} 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.71.5
 - Flow Sync Template Apps (v2)

**To Reproduce**
1. Import Core Solution
2. Start Sync Flows
3. Check did Apps Flow start. If not run main sync flow again
4. Check Apps Sync Flow result for default env

**Screenshots**
![image](https://user-images.githubusercontent.com/8307644/100392332-e4395400-303e-11eb-8c0d-47faa1a25047.png)

**Comment by JeneferM-MSFT** [comment]
This appears to be a case where the call to update is behaving as an insert. 
I do not repro but have one more customer experiencing the same error on another flow. 
We have an internal ticket going with the product team, but if you'd like quicker traction perhaps create a support ticket on your side as well.

**Comment by petepuu** [comment]
Thanks @JeneferM-MSFT! Good to know that this handled by your team already. Not a big issue and faced only in my own internal testing, so not critical

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!
