### ISSUE TITLE
[BUG]: Hardcoded group id on Admin | Sync Audit Logs

### ISSUE THREAD

**Issue by ndocosta** [microsoft/powerapps-tools#607]
After importing the solution CenterofExcellenceAuditLogs_1_3_2_managed.zip,
the flow Admin | Sync Audit Logs doesn't run with success, because it have an action "List Group members" with an hardcoded Group Id.
This two actions - Get my profile (V2) and List group members - don't seem to be necessary as they are not used anywhere in the flow.

![image](https://user-images.githubusercontent.com/12910235/100393601-2f993580-3032-11eb-8bf5-511478bbcb14.png)

After choosing a random group from my tenant, the flow completed with success as expected.

Thanks!
Best regards.

**Comment by JeneferM-MSFT** [comment]
Thanks for the note and for using CoE. This was left behind accidently and is removed in our local fix. 

Thanks for helping make CoE great!

**Comment by manuelap-msft** [comment]
Shipped a new version today that fixed this issue!
