### ISSUE TITLE
[BUG]: Teams Connection in Admin | Sync Template v2

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#608]
You removed Teams action in "Admin | Sync Template v2".
But the Teams connection has not been removed !

![image](https://user-images.githubusercontent.com/34766578/100619136-0112a780-331d-11eb-9a4b-9331388dd361.png)

How can we ignore this connection when importing the "Core component" solution ?
Because our service account used for the Starter Kit does not have a Teams license.

**Comment by JeneferM-MSFT** [comment]
We still depend on the connector for the Governance components, so we can move the connection reference to that solution instead. 

Thanks for using CoE.

**Comment by manuelap-msft** [comment]
Shipped a new version today where the Core components won't rely on a Microsoft Teams connection anymore.
