### ISSUE TITLE
[BUG]: Unable to activate Audit log's flow - Admin | Sync Logs!

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#609]
Hello,

I have added "Office 365 Management API" custom connector in the respective DLP policy, and I can see the same reflected in the targeted CoE environment, however when I try to activate the flow, it's throwing DLP Violation error as follows:

![image](https://user-images.githubusercontent.com/13658386/100626093-5d60d180-32f3-11eb-89b4-d3f39c07ee1e.png)

I have tried in couple of different browser after some time, however error remains the same - What could be missing here? 

Thanks and Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
I'm afraid if you've followed all the instructions in the documentation and still have the dlp violation, that you have hit a product bug. 

One thing to try before creating a support ticket is to delete and recreate the dlp policy. Sometimes the powershell adds twice and creates problems.

**Comment by dips23** [comment]
Hello Jenefer,

I apologize if this is not the correct thread to raise question/concern, however the DLP Policy has been created by following the prerequisites provided in the document ( default + custom connectors ) even though I see this error and I was wondering if I am missing anything here.

Probably raising a support ticket would help further, Thanks for the suggestion!

Regards,
Dipti
