### ISSUE TITLE
Setup Instructions: Audit and Report Components: Step 6

### ISSUE THREAD

**Issue by Russel-Thomas** [microsoft/powerapps-tools#61]
Setup instructions for Audit and Report Components: Step 6: INSTALL THE FLOWS should perhaps include clarification on modifying the following Flow

- Admin | Find and disable flows that leverage certain connectors

in that, to exclude Admin flows from this, what is the dynamic content to be added to the exception condition step "Disable app if it uses highlighted connectors" ;

- ['creator']?['objectid'] is not equal to ….  blank

Assume correct entry would be the UPN of the admin flow owner, and assuming this is the same as the environment variable then dynamic content 

- variables('adminMail') 

can be used?
Clarity would be useful :)

**Comment by manuelap-msft** [comment]
We have now clarified in the documentation that this Flow requires setup before running it.
