### ISSUE TITLE
[BUG]: Custom Connectors no longer associated with Apps

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#611]
Hi there,
We're on CoE version 1.71.7 and I noticed that the connection references for apps with Custom Connectors is no longer there.

The Power Platform Admin View app actually has the best representation of my problem.  So for example, the delivered connector Azure AD has apps listed
![image](https://user-images.githubusercontent.com/50427725/100927621-fd585f80-3499-11eb-8ed8-f2942fb29156.png)

However, selecting a Custom Connector in the same screen shows no apps associated
![image](https://user-images.githubusercontent.com/50427725/100928067-9dae8400-349a-11eb-8dad-21e40d25b980.png)

From the Power Platform Admin Center, here is one app that uses that custom connector
![image](https://user-images.githubusercontent.com/50427725/100928139-b323ae00-349a-11eb-9c42-fbfa39956ee8.png)

I believe the problem comes from the Connection Reference table.  The Connector field is blank for references to custom connectors.  The below screenshot is of the first rows in the table, and it so happens a couple of custom connectors appear near the top.
![image](https://user-images.githubusercontent.com/50427725/100928381-fb42d080-349a-11eb-9129-177c3a408286.png)

Because there is no reference to the Connector lookup field, I'm not even sure how it's getting the connector's display name.  But I think if that field gets populated, then I could see app (and eventually flow) references.

Does that make sense?
Thanks!
Christi

**Comment by osbornecc** [comment]
Trying to investigate a little more and saw a reply to another issue where it was suggested to export the table data to Excel.  Sadly, I found that in GCC the export to Excel (even when accessing the table from the Solution) is not available as shown in the screenshots.  Is there something I'm missing?
Thanks!

**Comment by JeneferM-MSFT** [comment]
hello sorry we are swamped here and i havent had time to investigate your issue. 
but you can use the export feature instead I hope
![image](https://user-images.githubusercontent.com/62659043/101829182-80576680-3ae7-11eb-939f-3d80b777c010.png)

**Comment by osbornecc** [comment]
No worries!  I'll keep poking along :)

**Comment by JeneferM-MSFT** [comment]
Hey folks. It looks like we havent ben tracking these in the (apps) flow. I see what is missing now, just not sure how it got removed. I am investigating a fix for next release, just wanted to let you know.

**Comment by JeneferM-MSFT** [comment]
We have this local fixed for apps and will be shipping an udpate soon with this in it.
The fix for flows is understood as well but will not be able to ship this time due to a blockign product issue. 
We will hold this issue open until we can release the flows fix too.

**Comment by JeneferM-MSFT** [comment]
Have a fix for this in place for both Apps and Flows
![image](https://user-images.githubusercontent.com/62659043/103580815-b2ae7680-4e8f-11eb-8822-4a86ea436d8d.png)

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with this fix, as well as a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!

**Comment by osbornecc** [comment]
Can I reopen this issue, please?  I'm now on Core Components 1.78 and am seeing this problem again.  I have more info but want to know if it should be tied to this issue or in a new one.  Thank you.
