### ISSUE TITLE
[BUG]: Multiple issues with custom connector

### ISSUE THREAD

**Issue by Panoone** [microsoft/powerapps-tools#612]
The OAuth 2.0 settings of the custom connector appear not to be saved. After clicking Update Connector. the screen refreshes and shows the fields as being blank. Not sure if this is by design but it makes it hard to know if the changes have actually been applied.

When trying to add the custom connector to the applied DLP policy for the environment I have two issues:

1. Using the provided PowerShell command (below) prompts for the Environment name. I believe this is due to the -ConnectorID param being present.
2. When I _do_ pass in the Environment name I receive an error stating that "The API policy {GUID} could not be found in the tenant {GUID}".

Using the following PS command with GUIDs redacted:

Add-CustomConnectorToPolicy `
-EnvironmentName xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx `
-PolicyName xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx `
-ConnectorName "shared_admin-5foffice-20365-20management-20api-xxxxxxxxxxxxxxxxxx" `
-ConnectorId "/providers/Microsoft.PowerApps/scopes/admin/environments/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/apis/shared_admin-5foffice-20365-20management-20api-xxxxxxxxxxxxxxxxxx" `
-ConnectorType "Custom" `
-GroupName hbi

Could we perhaps get a clearer example of the expected format for these values? There is almost nothing available online.

Components:
 - Core Solution
 - Version 1.71.5

Steps to reproduce Custom Connector changes:

1. Edit the OAuth 2.0 pane of the Custom Connector.
2. Provide required values for Client ID, Client secret and Resource URL.
3. Click Update Connector.

Expected result:
I would expect the newly-applied values to be displayed.

Actual result:
The fields display their previous default values.

Steps to reproduce adding Custom Connector to Policy:
1. Copy the PS command provided.
2. Substitute placeholder values.
3. Run command.
4. Provide Environment name {GUIF} at prompt. 

Expected behaviour:
Meaningful message stating that connector has been successfully added.

Actual behaviour:
Error is thrown. "The API policy {GUID} could not be found in the tenant {GUID}"

**Comment by StefanPlizga** [comment]
Hi, I am experiencing the same issue. Do you have any insights?

**Comment by JeneferM-MSFT** [comment]
Hey there. The first issue you mention around the fields going blank is a product issue and so I'm afraid I cant help there. 

But regarding the PowerShell, we do have a sample in the [Limitations section](https://docs.microsoft.com/power-platform/guidance/coe/limitations#custom-connectors-and-dlp) of the documentation. Pasted here for your convenience. 

`Add-CustomConnectorToPolicy -PolicyName {your policy name GUID} -ConnectorName {the nName you copied from above} -GroupName hbi -ConnectorId /providers/Microsoft.PowerApps/scopes/admin/environments/{your environment GUID{/apis/{your connector name} -ConnectorType "Custom"
`

Note also that the product team is shipping over the next month support for adding / removing custom connectors to DLP in the UX and so this PowerShell work around will no longer be needed.
