### ISSUE TITLE
[BUG]: issue importing AuditLog 1.3.2

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#615]
**Describe the bug**
Im presented the following screen during import:

![image](https://user-images.githubusercontent.com/52799471/101095500-a3cc5f80-3583-11eb-973a-35599886dc26.png)

When I select Office 365 Management API then new connection I see the following popup:

![image](https://user-images.githubusercontent.com/52799471/101096023-877cf280-3584-11eb-9dab-5c9b31f01ed2.png)

My current version of AuditLog is 1.0.0.20

I set up that connector earlier this year to capture O365 audit logs using the flow 
[Child] Admin | Sync Logs.

Going into the connections in the flow I see an error with the custom connector.
![image](https://user-images.githubusercontent.com/52799471/101097874-9618d900-3587-11eb-93a4-2516dfb3eb10.png)

If I try to fix the connection by attempting to reauthenticate using the same account I get:

![image](https://user-images.githubusercontent.com/52799471/101097988-c8c2d180-3587-11eb-9d5c-87384f0b8d53.png)

Any ideas?

**Comment by Panoone** [comment]
@dchrist27 
I had the same issue. This solution includes the customer connector components present in the core solution and seems to overwrite the configurations for Client ID, Secret and Resource URL. Re-applying the values for this field will allow you to connect successfully.

Also, as mentioned in another bug, the configuration fields for this connector do not reflect current values when updated.

This solution is also missing the environment variable for Tenant ID which is documented here: https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-auditlog

As a result you also need to manually update the Tenant ID in the sync flow.

**Comment by dchrist27** [comment]
Sorry for not responding sooner as I was rebuilding my laptop.

I went ahead and added the client ID and client secret and resource URL into the OAuth 2.0 section within the custom connector configs.  Im assuming you meant that I also needed to update the tenant ID within this section, correct?

When I went back under connections the connector associated with the custom connector indicated ‘Fix connection’ and when I clicked it the connector looked to be back online.

One thing that I wasn’t sure is that I also performed a Test within the custom connector and I did not get back a 200 response.  I receive a 400 operation failed.

Headers:
{
  "cache-control": "no-cache",
  "content-length": "97",
  "content-type": "application/json; charset=utf-8",
  "date": "Wed, 09 Dec 2020 22:34:58 GMT",
  "expires": "-1",
  "pragma": "no-cache",
  "x-aspnet-version": "4.0.30319",
  "x-ms-apihub-cached-response": "true",
  "x-powered-by": "ASP.NET"
}


Body:
{
  "error": {
    "code": "AF20024",
    "message": "The subscription is already enabled. No property change."
  }
}



Hopefully this corrects my issue.  If I misinterpreted your response please let me know.

Thanks again
Dave

**Comment by dchrist27** [comment]
Update:
I just checked [Child] Admin | Sync Logs flow and under connections in use I can see that my custom connector is online.  I also looked under Data | Connections and I see that the connector to Azure is also connected.   So I went ahead and made another attempt to update the Audit Logs module from 1.0.0.20 to 1.3.2 but I get the same error.
![image](https://user-images.githubusercontent.com/52799471/101930846-48f7c100-3b9e-11eb-95ab-8a89fcc9df6e.png)

I wonder if its because Im seeing 2 child flows but I have not idea how to remove the duplicate entry.
![image](https://user-images.githubusercontent.com/52799471/101930968-72b0e800-3b9e-11eb-9915-9ecfcc35f3c2.png)

**Comment by hsantan** [comment]
I'm receiving the similar error [400]
![2020-12-21 18_27_10-Manage your custom connectors _ Power Automate](https://user-images.githubusercontent.com/40079239/102823753-45441580-43ba-11eb-947d-79f12873e81f.png)


{
  "error": {
    "code": "StartSubscription [CorrId=1e66f72e-a894-4359-859b-43dc545c104b]",
    "message": "bf94ede-1182-42c2-b949-958401f12f0d] failed. Exception: Microsoft.Office.Compliance.Audit.DataServiceException: Tenant 1b818c16-117f-4bf5-89a7-028fd47f7664 does not exist.\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetSubscriptionTableClientForTenantAsync>d__51.MoveNext() in d:\\dbs\\sh\\nibr\\1214_141956_0\\cmd\\q\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 1953\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.AzureManager.<GetAPISubscriptionAsync>d__22.MoveNext() in d:\\dbs\\sh\\nibr\\1214_141956_0\\cmd\\q\\sources\\dev\\auditing\\src\\auditapiservice\\common\\AzureManager.cs:line 498\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Office.Compliance.Audit.API.StartController.<StartSubscription>d__0.MoveNext() in d:\\dbs\\sh\\nibr\\1214_141956_0\\cmd\\17\\sources\\dev\\auditing\\src\\auditapiservice\\apifrontendservicerole\\Controllers\\StartController.cs:line 76"
  }
}

All configuration its ok!

**Comment by manuelap-msft** [comment]
Typically this error: Tenant 1b818c16-117f-4bf5-89a7-028fd47f7664 does not exist is received when you've either entered the incorrect Tenant ID, or when the Audit Log has been enabled in the tenant in the past 24 hours and is not yet available to be queried via the API. Can you confirm you are still receiving this issue?

**Comment by dchrist27** [comment]
I downloaded the CoE Starter kit (released today) and I am still unable to update the AuditLog module.   I am currently on 1.0.0.20 attempting to upgrade to 1.3.4.   I checked both flows and have removed the unmanaged layers prior to importing the upgrade.  Similar to before I see this screen.

![image](https://user-images.githubusercontent.com/52799471/103820940-d2ca6b00-5032-11eb-8fe1-b2e1ee4dcb8c.png)

I then see this screen after choosing 'select a connection' | new connection.

![image](https://user-images.githubusercontent.com/52799471/103821010-fbeafb80-5032-11eb-881c-1640c8211769.png)

**Comment by manuelap-msft** [comment]
Can you help me verify something on the old version? If you look at the AuditLog 1.0.0.20 solution, does this contain the Audit Log table (entity) or only flows and the custom connector?

**Comment by dchrist27** [comment]
This is what I see in the Audit Log solution:

![image](https://user-images.githubusercontent.com/52799471/103909955-eaa0fe00-50c9-11eb-9271-7f67287e1352.png)

**Comment by dchrist27** [comment]
I see the following tables within Core Components (version 1.72)

![image](https://user-images.githubusercontent.com/52799471/103910483-80d52400-50ca-11eb-9a43-e767e6829674.png)

**Comment by manuelap-msft** [comment]
Great, thank you for confirming! Because the audit log table is part of the Core Components, you can safely delete the Audit Log solution and start setting up from scratch. We have just tried this with multiple customers who had the same upgrade issues you had, and a delete and re-install of the solution worked and didn't compromise the Audit Log data as that is held in a separate solution. 

Thanks for using the CoE!

**Comment by dchrist27** [comment]
Hi....

I deleted the Audit Log solution and proceeded to import version 1.3.4 released back on 1/6/21.   I got to this screen.

![image](https://user-images.githubusercontent.com/52799471/105067000-ed461080-5a44-11eb-9849-f5a85a833a55.png)

3 of the 4 connections refresh but when I go back and select a connection for the first connection I get the same popup error.

![image](https://user-images.githubusercontent.com/52799471/105067332-34cc9c80-5a45-11eb-9dc7-70f680fad164.png)

It looks like that first connector listed is the custom connector.   Does that also have to be deleted prior to importing the new Audit Logs solution?

![image](https://user-images.githubusercontent.com/52799471/105067796-b6242f00-5a45-11eb-8dd0-f89df028b4cf.png)

**Comment by manuelap-msft** [comment]
The Office 365 Management API connector is imported as part of the Core Components solution. You will have to be on the latest version of the Core Components solution to have the correct connector imported, and you will have to configure it first (adding the App Registration etc as per https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog) before importing the Audit Log

**Comment by dchrist27** [comment]
Earlier in this issue thread Panoone on 12/3 mentioned that after updating Core you have to reconfigure the Office 365 Management API connector.   I actually went through the reconfig back on 1/6 after I successfully imported the latest Core Components solution.

![image](https://user-images.githubusercontent.com/52799471/105069826-174d0200-5a48-11eb-8b4b-bb863fe89944.png)


The admin | Sync log flows within the Audit Log 1.0.0.20 solution were successfully running.

**Comment by dchrist27** [comment]
Quick update...

Just to be safe I went ahead and deleted the Office 365 API connection under Data | Connections in the PowerApps left pane and repeated the custom connector setup (I also verified all of the App registration configs).  The configuration is successful after Starting the subscription.

![image](https://user-images.githubusercontent.com/52799471/105200335-5ab97600-5b05-11eb-887e-5279fde276bd.png)

![image](https://user-images.githubusercontent.com/52799471/105200469-7ae93500-5b05-11eb-8be3-6c6241fbb6e3.png)

When I attempt to import the Audit Log 1.3.4 solution...unfortunately I still see the same error when attempting to re-establish the Office 365 Management API connection.

![image](https://user-images.githubusercontent.com/52799471/105200886-e501da00-5b05-11eb-9995-102251071e20.png)

**Comment by dchrist27** [comment]
I just updated to the latest Core Components.  1.98 with no issue but again I'm still unable to import Audit Logs.   As previously directed in this case I deleted the Audit Logs solution that I was unable to upgrade.    I see the same error (in red box in prior post).

I was wondering if its supported to delete the connector associated with the custom connector as well as deleting the custom connector from the custom connector tab as well as within the core components solution?  Once deleted could I then rerun the import of core components to bring in a fresh custom connector?   Please advise.

**Comment by manuelap-msft** [comment]
Hello,

if you delete the Core components solution it will delete all the data the sync flows have gathered up to this date, so would not recommend this approach.

Here's what worked for other customers:
Delete the custom connector from inside of Core
Delete the app registration in Azure
Upgrade to April release of Core when it's coming out (you won't be able to upgrade to the same version you already have)
Redo the audit log solution set up steps entirely, including setting up the app registration.

I would suggest performing these steps, once the April release comes out (we're targeting first week of April with it)

**Comment by dchrist27** [comment]
Manuela...Wanted to let you know that I was finally able to import the Audit Log solution using the steps outlined in your last response.   You can close this issue.

**Comment by manuelap-msft** [comment]
Thank you for letting us know & thanks for using the CoE!
