### ISSUE TITLE
[BUG]: Blob key  $audit_general$Audit_General$apac0012 in the url is invalid

### ISSUE THREAD

**Issue by chrishattonfh** [microsoft/powerapps-tools#616]
**Describe the bug**
Hi, I am installing the CoE Starter Kit and the [Child] Admin | Sync Logs flow is failing with the error message 

"Blob key 20201202212216924035945$20201202212432430065720$audit_general$Audit_General$apac0012 in the url is invalid."

The flow stops on the 'Apply to each Cluster' section. Under the GetContentDetials, the INPUTS has the Tenant Id "8a235459-3d2c-415d-8c1e-e2fe133509ad" which does not match our tenant id.
  
 - Solution Center of Excellence - Audit Logs
 - Version 1.0.0.20
 - App or Flow [Child] Admin | Sync Logs
 
**Expected behavior**
I expect the flow to run as the [Child] Admin | Sync Logs flow has all valid connections and the subscription has started.

**Screenshots**
 
![SyncLogFailure](https://user-images.githubusercontent.com/75407385/101108738-10099a80-363a-11eb-94d0-2b04c2d0347d.png)

**Comment by manuelap-msft** [comment]
Please edit the Admin | Sync Audit Logs and configure the Tenant ID with your Tenant ID
![image](https://user-images.githubusercontent.com/55705669/101181304-9e831980-3644-11eb-88a1-33e0ae45ca99.png)

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE

**Comment by chrishattonfh** [comment]
Updating the tenant id resolved the issue.

Thanks
