### ISSUE TITLE
[IDEA]: Additional System View for PowerApps App: "Canvas Apps"

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#619]
**Describe the idea**
I see that there are four "System Views" for the "Power Apps App" table. One of them is "Model Driven Apps", which is great, but I'd also like one for  "App Type" = "Canvas Apps" please.

**Component (please tell us which flow or app you are experiencing issues with):**
 - App: Power Platform Admin View

**To Reproduce**
N/A

**Expected behavior**
A "System View" that only shows apps with the App Type = "Canvas Apps"

**Screenshots**
N/A

**Additional context**
Of course I know I can create a personal view for this request, but as you already have the "Model-driven Apps" view it would be a nice companion to that, and save everyone having to create the view, share it with their team etc. Also it saves people making an unmanaged change by creating their own system views. This view would be useful as it filters out model-driven apps, which is on the other system view, plus  it filters out SharePoint Forms which, for me, I never look at. 
Thanks very much!

**Comment by JeneferM-MSFT** [comment]
Good suggestion thank you. This has been local fixed for the next release
![image](https://user-images.githubusercontent.com/62659043/102653502-dea5ca00-4123-11eb-89f1-023c43c806e3.png)

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with this fix, as well as a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!
