### ISSUE TITLE
[IDEA]: Hide System View Flow Subgrid View

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#620]
**Describe the idea**
This is not a new idea, maybe more of a request. In the model-driven app "Power Platform Admin View" I have noticed that there is a "System View" available on the Flow table called "Flows Subgrid View". I'm not sure what value this is offering being able to select that within the Model-driven app. There is another View called "Active Flows" that shows the same columns and more. The "Flows Subgrid View" has no filters on it, whereas the "Active Flows" has two filters. I feel the "Flows Subgrid View" is not needed to be shown for selection, unless I'm misunderstanding the reason why it is there.

**Component (please tell us which flow or app you are experiencing issues with):**
 - App: "Power Platform Admin View"

**To Reproduce**
1. Go to '"Power Platform Admin View"'
2. Click on 'Flows'
3. In the View selector, change this to "Flows Subgrid View"

**Expected behaviour**
I don't think this is needed to show as a view in the view selector in the model-driven app

**Screenshots**
![image](https://user-images.githubusercontent.com/68440710/101454542-11341380-3929-11eb-9c9b-0760a4597499.png)

**Additional context**
Nothing else to add. Thanks!

**Comment by JeneferM-MSFT** [comment]
Thanks for the idea, and for using CoE. We have put re-assessing the views offered in the app on the backlog.
