### ISSUE TITLE
[IDEA]: Activities enabled for tables

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#622]
**Describe the idea**
It would be great if activities could be enabled for the key tables: Flows, Environments, Connectors, Chatbots, UK Flows. This is really useful when the COE is being managed by more than 1 person, as they can see what governance actibities has happened with a specific record, such as a Note saying "Spoke with Bob about DLP blocking his connector and he will change this tomorrow" or a Task such as "Call Sue on Friday to improve her trigger" etc etc..

 In our COE we have PowerApps Apps already enabled for Notes. Not sure if we did that ourselves or it was already enabled. Either way, having activities enabled would be great. Thanks.

**Component (please tell us which flow or app you are experiencing issues with):**
 - App: Power Platform Admin View

**Expected behavior**
When opening a record there is a Notes tab where I can create and see activities.

**Screenshots**
![image](https://user-images.githubusercontent.com/68440710/101591618-d55e8400-39e4-11eb-96aa-0b21a71628df.png)

**Comment by JeneferM-MSFT** [comment]
Hi and thanks for the great suggestion. We have put adding the concept of collaboration onto the backlog but it will be a while before we fund. We cannot simply use the "notes" type field because that feature is not, and will not, supported in Dataverse for Teams, something we have a goal of supporting. 

Thanks for using CoE!

**Comment by GarryPope** [comment]
Hello @JeneferM-MSFT,

I hope you are well. 

I was wondering if you would reconsider looking at this idea again please? 

We're desperate to have Notes enabled for the tables in the model-driven app like you have enabled for Power Apps. 

Currently we are making notes either in OneNote or in columns on records that shouldn't have a note in them. It's difficult to keep up to date with what we are doing say for an environment or flow or connector. Often we're duplicating effort where I've spoken with a Maker and wasn't able to add a note to the Flow record, only for my colleagues to contact the Maker and ask them same questions.

For Apps, because it has Notes, we don't have and wasted time or effort, but for other tables, we're either duplicating work, or managing the notes in different applications such as OneNote. 

Sorry to bang on about it, but it would be so helpful it this was enabled for all tables.

Thanks very much,

Garry
