### ISSUE TITLE
[bug]: admin_office column in the Maker table has a small max length

### ISSUE THREAD

**Issue by mpinuel** [microsoft/powerapps-tools#623]
**Describe the bug**
We have some errors in the "Admin | Sync Template v2 (Flows)" execution happened in the "Upsert Flow Maker 2" action. The cause of the errors seems to be the maximum length of the admin_office field in the Maker table.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Solution
 - Version 1.71.1
 - Flow Sync Template (v2)

**To Reproduce**
1. In the Admin | Sync Template v2 (Flows) execution of a particular environment, it has errors in 4 flows of the same maker:
![image](https://user-images.githubusercontent.com/32450895/101739901-7a9e5880-3ac8-11eb-9751-2d4914cebe97.png)

2. The error message is as follows:
_**"A validation error occurred.  The length of the 'admin_office' attribute of the 'admin_maker' entity exceeded the maximum allowed length of '100'"**_

3. Reviewing the maker data, we realized that the admin_office field of this particular maker has 128 characters so it exceeds the 100 max length defined in the solution.

4. We have reviewed the field definition but, since it is defined within a solution, we cannot modify its properties:
![image](https://user-images.githubusercontent.com/32450895/101751198-4b8be500-3ad0-11eb-99f8-dd99f77585f5.png)
![image](https://user-images.githubusercontent.com/32450895/101751323-6f4f2b00-3ad0-11eb-8377-5e165d952cf7.png)

**Expected behavior**
Modify the maximum length of the admin_office field so that the Maker information can be inserted. Maybe the field max length could be extended to 200 in the following versions of Core Components?

Thanks!

Regards,
Miguel.

**Comment by mpinuel** [comment]
In the meantime, to avoid the error in the next flow executions, we have modified the action "Upsert Flow Maker 2" to make a substring of the first 100 characters in the Office Location field:
**_substring(body('Get_New_Flow_Creator_profiles')?['officeLocation'],0,100)_**
![image](https://user-images.githubusercontent.com/32450895/101753190-a292b980-3ad2-11eb-9434-8c4816738f7d.png)

Thanks!

**Comment by JeneferM-MSFT** [comment]
Thanks for raising and for using CoE. I have local fixed this for next release.

**Comment by manuelap-msft** [comment]
This has been fixed in the version that was just released. Thank you for using the CoE!
