### ISSUE TITLE
[BUG]: Power BI Report - Connections Page: "Connection Trend" Visual.

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#627]
**Describe the bug**
I'm not sure if this is a bug or I'm just reading this incorrectly, but when I look at the Power BI Report, and go to the "Page" called "Connections" I'm presented with four visuals. The top left-hand corner visual called "Connection Trend", I understood showed all the connectors in use and the number of apps and flows using them. 

But when I use the filter and filter by a specific connector, the visual doesn't show me only apps and flows that use this connector, but it shows me all the apps and flows that a maker(s) created as long as they used this connector in at least one app or flow.

If you look at the screenshot below, I've filtered this page to a single connector "Microsoft Translator".
In the "Maker Connections" visuals there are two rows, so two makers. If you look their total number of Flows add up to 93, which the visual on the left "Connection Trends" is showing. 
But if you look at the bottom right-hand visual, "Flow Connections" you see that actually there is only 1 Flow created by one of the two makers.
I think the top left-hand visual, "Connection Trend" should only show the number of Flows that is using that connector, not the total number of Flows every maker has made. So in this case: one.

Again, Power BI isn't my strong point, so I might be reading this wrong.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [1.71.7]
 - App or Flow [Power BI Dashboard]

**To Reproduce**
1. Go to 'Power BI Dashboard'
2. Click on '.Connection Page'
3. In the "Slicer" find "Connectors" and select a specific connector.
4. The data on the page will then only show for that connector. 
5. Now look at the visual "Connection Trend" and you'll see it showing the total number of apps and flows those makers created, not just the apps and flows they made using that connector.

**Expected behavior**
I would expect, and again I might be reading this wrong, to see the number of apps and flows that only use that connector in the visual "Connection Trend".

**Screenshots**
![image](https://user-images.githubusercontent.com/68440710/101862659-b38f0980-3b6a-11eb-9315-4eea2029335b.png)

**Additional context**

**Comment by GarryPope** [comment]
I understand the page more now. It is focusing on "App" connectors. So in the visual "Maker Connections" we had two rows, as two of my colleagues created apps using that connector. And the bottom right does show all flows that used that connector. 

But, I think the top left-hand visual still shouldn't show the total number of Flows the App Makers created. It causes confusion. It would be better, I think, if the top two visuals represented apps/flows/makers of the specific connector selected, rather than just focusing on apps.

Thanks very much.

**Comment by manuelap-msft** [comment]
Hello!

thanks for explaining the issue - I see what you mean now. The issue is the relationships in our Power BI data model, where the relationship between connector and flow connection only works one way. I tried changing this just now but looks like that introduces ambiguity and is thus not allowed. We might have to split this tab into two, one for Apps and one for Flows to solve this. 

Thanks for using the CoE!

**Comment by manuelap-msft** [comment]
We have made changes in the just released version of the Power BI dashboard to remove the confusion and focus on App connections only.
