### ISSUE TITLE
[BUG]: Cannot use Connectors flow if dont have admin access to Default

### ISSUE THREAD

**Issue by jpanderson91** [microsoft/powerapps-tools#629]
On this step https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#create-the-library of the coe starter kit setup, wherein you create the SharePoint library, I run the flow contained in the zip file CreateCoETemplateLibaryDocLibraryinSP.zip and the run fails. I received the following error: 

The 'inputs.parameters' of workflow operation 'Add_List_-_Create_the_Document_Library_' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'dataset'

On a seperate note, the Admin | Sync Template v2 (Connectors) Flow contained in the Core Components of the COE Starter Kit also fails to run, error shown:

The environment filter must be set.

![Coe Starter Kit Error_2](https://user-images.githubusercontent.com/74209806/101949739-ae0ce000-3bb9-11eb-9df4-d45a78a190e2.JPG)
Will attach screenshots as well.

![Coe Starter Kit Error](https://user-images.githubusercontent.com/74209806/101949542-5f5f4600-3bb9-11eb-9f04-29ee6d5b9a83.JPG)

**Comment by SteveAsch** [comment]
I'm receiving this exact error myself

**Comment by JeneferM-MSFT** [comment]
Can you please post separate bugs for separate issues? For example of why, I'm not sure which one Steve is referencing when he says he receives it too. 

Regarding the connectors. I don't know what happened to your toolkit, but here is what it looks like locally for us, pointing to the output of the compose above:
![image](https://user-images.githubusercontent.com/62659043/102017219-65206d00-3d1a-11eb-958a-770f8bf339a7.png)

Regarding the doc lib, do you have the site set in the env var described in setup? 
![image](https://user-images.githubusercontent.com/62659043/102017538-779ba600-3d1c-11eb-99ff-0108fe5e15fc.png)


You have a slightly older version of the helper and so you'll need to put the value in the default value (not current) of the env var. I suggest you either manually create the list, or paste your site directly in the action where it says "Site Address". 

Thanks for using CoE

**Comment by jpanderson91** [comment]
That fixed the SharePoint Library issue, thank you! The connectors flow sill doesn’t run, when I edit the flow mine looks like yours, but when I run it the error in the screenshot is returned.

**Comment by JeneferM-MSFT** [comment]
I cannot see your screenshot. Please be sure to respond in GitHub for me to see them.

**Comment by jpanderson91** [comment]
> I cannot see your screenshot. Please be sure to respond in GitHub for me to see them.

Sorry, was replying via email - I was referring to the initial screenshot of the Admin | Sync Template v2 (Connectors) Flow. When I edit the flow mine looks like yours does internally, but when I run it I receive the error in the aforementioned screenshot. I'll include it again below for context. 
![Coe Starter Kit Error_2](https://user-images.githubusercontent.com/74209806/102020390-8e52f480-3d3e-11eb-9b96-340c16d302c3.JPG)

**Comment by jpanderson91** [comment]
Here is a screenshot of what the flow looks like when I'm editing 
![Coe Starter Kit Error_3](https://user-images.githubusercontent.com/74209806/102020463-07524c00-3d3f-11eb-8827-246c8718a9a0.JPG)

**Comment by JeneferM-MSFT** [comment]
I see. It seems your default environment is not coming through when you call Get Environments above. 
Can you validate, if you call this action in a new flow for your tenent's default, do you have access? 
![image](https://user-images.githubusercontent.com/62659043/102020844-af144d80-3d30-11eb-8d1f-76238dcb9af8.png)

And if you call List Environments as Admin, do you have access to default? 
![image](https://user-images.githubusercontent.com/62659043/102020850-be939680-3d30-11eb-970f-7f86242e431a.png)

**Comment by JeneferM-MSFT** [comment]
recently we made the change to get default instead of first as soemtimes first is a type of envt that cannot be accessed. Thats why you ware seeing this now as a regression. I have made a change locally to get default and then first if no access to default. 

Do know though that you will not be able to gather information about default in the CoE unless you have access.

**Comment by jpanderson91** [comment]
It appears I have access to the default environment from make.powerapps.com

![Coe Starter Kit Error_4](https://user-images.githubusercontent.com/74209806/102098867-4a6af880-3ded-11eb-8ea9-8b889bf5fb7d.JPG)

but I can't see it in the admin portal's list of environments.

![Coe Starter Kit Error_5](https://user-images.githubusercontent.com/74209806/102098933-5d7dc880-3ded-11eb-80c9-162895d6c0fc.JPG)

Should I contact an IT admin within my organization to request a role additional permissions? I have the Power Apps Admin role currently I believe.

**Comment by JeneferM-MSFT** [comment]
Yes, per the [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites), here is the information about the admin account:

- Microsoft Power Platform service admin, global tenant admin, or Dynamics 365 service admin for access to all tenant resources through the Power Apps APIs.

- This solution will work for environment admins, but the view will be restricted to only the environments an environment admin has access to.

- Dynamics 365 service admin is required for getting details about model-driven apps and solution-aware flows.

- This account must be email enabled.

**Comment by JeneferM-MSFT** [comment]
We will use this issue to track the issue with default envt and connectors

**Comment by JeneferM-MSFT** [comment]
have this local fixed for next release

**Comment by jpanderson91** [comment]
Thank you, I also found out I don't have the power automate premium license. In the pre-req's it states I need a power automate premium license. Per this screenshot I see a license that includes RPA. Can you please clarify if it is the 15$ or 40$ per user/month license that is "premium"? 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/74209806/102145432-cfc1cd80-3e2c-11eb-83f3-a75b4f06a9b0.png)

**Comment by jpanderson91** [comment]
I was able to fix the Admin | Sync Template v2 (Connectors) Flow by acquiring the Power Automate Premium license as well as the Power Platform Admin and Dynamics 365 admin roles. 

![Coe Starter Kit success](https://user-images.githubusercontent.com/74209806/102640543-3e9a7180-4120-11eb-8d7b-ad9b8e62a3cc.JPG)

**Comment by jpanderson91** [comment]
the 15$ per user per month Power Automate Plan was sufficient.

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with this fix, as well as a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!

**Comment by SteveAsch** [comment]
Hi,

The updates all fails with errors.

Is it working for anyone else?

Thanks

Steve

**Comment by SteveAsch** [comment]
Imports gave errors and overwrote my core components. Errors everywhere now

**Comment by JeneferM-MSFT** [comment]
Steve can you please post issues that you find? And please include pictures to show the specific failures you are seeing. 

Also, be sure that you followed this upgrade path: [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
