### ISSUE TITLE
Cannot see Flows created in the Default environment in CoE

### ISSUE THREAD

**Issue by NizarFIL** [microsoft/powerapps-tools#63]
I have the version 1.0.0.61 installed on CoE.
From the Admin View, PBI Dashboard and CDS and cannot see any trace of the Flows created on the Default environment.
I can see Apps, but no flows. I checked all the CoE Flows and started them manually successfully, but still can't see them.

**Comment by manuelap-msft** [comment]
This is an old version of the CoE Kit, can you please work on using the latest version and check if the error still persists.

**Comment by NizarFIL** [comment]
Thanks Manuel, I created a new environment and installed the latests version it this one did capture the default environment Flows :)
