### ISSUE TITLE
[BUG]: New Flow Activity / New Power App Activity email notifications not working

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#630]
**Describe the bug**
It looks like when I upgraded to the October 2020 release of CoE that I no longer receive any Activity Alert notifications via email.   This would be for Core 1.70.6 and Audit components 1.0.0.20.

At first I thought it might be due to the fact that the custom connector attributes were lost during the import but I have since reconfigured the custom connector and it is connected.    I even created a simple flow to hopefully trigger the generation of an email notification but I never received an email.

I was looking in the Audit Log module and noticed the Admin | Sync Audit Logs flow turned off.  Should this be on?

Appreciate any help in resolving this issue.

Here's an example of an activity alert I used to receive.

![image](https://user-images.githubusercontent.com/52799471/101962369-9ccfcd80-3bd1-11eb-87ea-219006b44a8f.png)

**Comment by JeneferM-MSFT** [comment]
Sorry I'm not quite following you. To my knowledge, our toolkit does not send such alerts to users.

**Comment by dchrist27** [comment]
Apologies for the confusion.   The alert in the screenshot is a custom activity alert I previously created in O365.

Before you close can you answer:  if the flow Admin | Sync Audit Logs should be off or on?

Dave

**Comment by JeneferM-MSFT** [comment]
Yes, if you would like the audit logs to run you will need to have them turned on. 
Thanks for using CoE
