### ISSUE TITLE
[BUG]: API requests Limitations

### ISSUE THREAD

**Issue by baxist** [microsoft/powerapps-tools#631]
**Describe the bug**
What will happen, if Microsoft throttles all Flows that are reaching the API request limitations?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [1.45] (Yes, an old version, but I don't think there has been a change concerning my question)
 - Flow: Sync Template Flows (v2)

**To Reproduce**
Flow Analytics

**Screenshots**
![grafik](https://user-images.githubusercontent.com/67257572/102067120-fcf58800-3dfa-11eb-9a4e-4023b87462e0.png)

**Additional context**
For the Core Components, I need more than 50.000 API request per day. If Microsoft really starts to throttle the flows, the CoE will not work anymore for me. And I don't really want to buy several Capacity AddOns to run it.
[https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations](https://docs.microsoft.com/en-us/power-platform/admin/api-request-limits-allocations)

**Comment by JeneferM-MSFT** [comment]
We have, in fact, addressed this concern in the newer versions of Core. 
Current versions no longer update records unless they are new or modified. This leaves a few things (ex noting orphaned apps) having to be done in 3 long running "Cleanup" flows that we have set to trigger less frequently.

**Comment by baxist** [comment]
Can you give us an estimate how many API runs are needed less?

**Comment by JeneferM-MSFT** [comment]
That varied greatly depending on size and activity level of you tenant. But its on the order of ~90% less for most people it seems. You will have to upgrade to see what your situation in particular looks like. 

Please note that upgrade has changed. You have to manually remove unmanaged layers and setup is much faster now as you no longer need to connect on each individual action. 

[Installing Updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by baxist** [comment]
Thanks a lot!
