### ISSUE TITLE
[BUG]: App Archival Flow has been modified and not working 

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/powerapps-tools#632]
**Issue**
App Archival Flow has been copied and modified but it doesn't work.

**To Reproduce** - Starting from Capture 1 to 6, same actions have been used as COE Archival App Flow :
![Capture6](https://user-images.githubusercontent.com/62638075/102070382-0eec2080-3e25-11eb-8dfd-be4084a74bda.JPG)
![Capture5](https://user-images.githubusercontent.com/62638075/102070389-114e7a80-3e25-11eb-9d15-a741678e3abc.JPG)
![Capture4](https://user-images.githubusercontent.com/62638075/102070392-11e71100-3e25-11eb-9ffc-7214e17d8188.JPG)
![Capture3](https://user-images.githubusercontent.com/62638075/102070398-127fa780-3e25-11eb-8d8a-1992764d30f3.JPG)
![Capture2](https://user-images.githubusercontent.com/62638075/102070400-13183e00-3e25-11eb-88d9-9dbece72fd50.JPG)
![Capture1](https://user-images.githubusercontent.com/62638075/102070402-13b0d480-3e25-11eb-857f-f830782e12cf.JPG)

**Error** - 
1. It just archives only one .msapp file and doesn't process others.
2. It also doesn't show the display name of the App in Archived SharePoint Doc Library.

![Output](https://user-images.githubusercontent.com/62638075/102070686-730ee480-3e25-11eb-8eb8-a54d0d95b9cf.JPG)

**Expected behavior**
It should archive .msapp files to SP Library from for all listed Apps in SharePoint list.

**Comment by JeneferM-MSFT** [comment]
Our governance flows no longer support the archival to SP. Current versions now rely on a reminder system for the user to backup on their own. 

Please read up on the current flows here: [Governance Components](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#admin--app-archive-and-clean-up--start-approval)
