### ISSUE TITLE
[BUG]:Create CoE TemplateLibary Doc Library in SP Fails

### ISSUE THREAD

**Issue by medicineshow** [microsoft/powerapps-tools#634]
When I run the Create CoE TemplateLibary Doc Library in SP flow it errors with the error message "Bad Gateway"

**Component:**
 - Solution : Nurture
 - Version: 1.23
 - Flow: Create CoE TemplateLibary Doc Library in SP

**To Reproduce**
I have updated the "Add list - Create the Document Library" step with the sharepoint site URL and the following 4 steps and then test the flow which reports successful, however when I run it, it runs for approximately 10 minutes then fails with the eror "Bad Gateway"

**Comment by rkrish2020** [comment]
We get the below error when it tries to create a folder in our sharepoint 

Create CoE TemplateLibary Doc Library in SP

WorkflowOperationParametersRuntimeMissingValue. The 'inputs.parameters' of workflow operation 'Add_List_-_Create_the_Document_Library_' of type 'OpenApiConnection' is not valid. Error details: The resolved string values for the following parameters are invalid, they may not be null or empty: 'dataset'

**Comment by JeneferM-MSFT** [comment]
Hello. This was identified in #629 as well, but will use this to track as I made a change to the flow. 

You can put the value of the site for the list directly in the action where it says "Site Address"

**Comment by manuelap-msft** [comment]
This has been fixed in the version that was just released. Thank you for using the CoE!
