### ISSUE TITLE
[BUG]: Admin | Compliance detail request fails when no owner is found

### ISSUE THREAD

**Issue by Panoone** [microsoft/powerapps-tools#635]
**Describe the bug**
This flow appears to fail when an app has no owner.

ActionFailed. An action failed. No dependent actions succeeded.

Error:
Action 'Condition:_Audit_apps_that_are_broadly_shared' failed

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CenterofExcellenceAuditComponents_1_25_managed
 - Version 1.25
 - App: Admin | Compliance detail request

**To Reproduce**
1. Run flow against all apps.
2. Any app with no owner will cause the described error during the Send an email (v2) action.

**Expected behavior**
I would expect the flow to account for this by providing the AdminEmail env var when an owner is not found.

**Screenshots**
![image](https://user-images.githubusercontent.com/9169734/102149194-f7af4080-3ec1-11eb-8d85-2dc7f65cbbe3.png)

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE and for posting such an actionable issue. 
Due to competing priorities we likely wont get this fixed before next release, so I just wanted to be sure you knew about the Set App Ownership canvas app in the Core Solution. 
It will allow you to find and fix up these orphans with a new owner so that you can proceed with the governance while you await a fix to the toolkit. 
Our fix will likely just be assigning out the email to the admin address.

**Comment by JeneferM-MSFT** [comment]
![image](https://user-images.githubusercontent.com/62659043/102150589-c97c2300-3e25-11eb-99fd-06c3f79acb2a.png)

**Comment by Panoone** [comment]
Hi @JeneferM-MSFT ,

Thanks for the response. I did try that but none appear under orphaned.

I think the problem may lie in Dynamics apps, many of which have no owner. But I can't be sure.

![image](https://user-images.githubusercontent.com/9169734/102170522-b2523980-3ee8-11eb-97a5-4e2874c15ffb.png)

**Comment by JeneferM-MSFT** [comment]
Ah that makes sense. Yes we do not support model driven apps in that canvas app as we aren't exposed with a backend to support changing such things as owner. 

Note that the information about what is orphaned is captured in the CoE though, even for model driven apps. 
If you export the data in the PowerApps Apps table, you can filter to orphaned model driven apps. 

Thanks again for posting.

**Comment by Panoone** [comment]
Hi @JeneferM-MSFT,

Thanks for the tip. I have adjusted the filter query in the List Apps action to ignore 'Model Driven' apps.

_admin_appowner_value ne null and admin_appownerdisplayname ne 'SYSTEM' **and admin_powerappstype ne 597910001**

This has resulted in fewer apps but I still received a failed delivery because the app owner is an admin and doesn't have an Outlook license. :\

Is there a simple way to check for this, or simply continue in the event of a single delivery failure?

**Comment by JeneferM-MSFT** [comment]
If you look in the flows we have in Core you will see the solution we have for this, and you can add it here if you'd like while you await our fix:

This example from (Custom Connectors) but its in all these flows
![image](https://user-images.githubusercontent.com/62659043/102366850-f89dac00-3f6d-11eb-9ad9-d37c6e8f825c.png)

Basically you can switch on the status code of that call and do something different when it fails (the user no longer exists)

**Comment by Panoone** [comment]
Thanks Jen.

I wound up just adding a second email action and configured its "run after" settings for skipped or failed. Works like a charm.

![image](https://user-images.githubusercontent.com/9169734/102440802-0853e800-4075-11eb-966e-7daba5e60ad6.png)

**Comment by JeneferM-MSFT** [comment]
Wonderful. We will hold this open until we fix to ship.

**Comment by JeneferM-MSFT** [comment]
I have this local fixed for next release

**Comment by JeneferM-MSFT** [comment]
This fix seems to have gotten lost and is not available in the Feb update. 
Apologies. I will work to re-implement.

**Comment by JeneferM-MSFT** [comment]
ok this is there after all, I hadnt removed my unmanaged layer :)

Thanks again.
