### ISSUE TITLE
[BUG]: Create CoE TemplateLibary Doc Library in SP

### ISSUE THREAD

**Issue by SteveAsch** [microsoft/powerapps-tools#636]
**Describe the bug**
This is the same as 634 and 629 but with trying one of the other suggestions.

 - Version 1_23
 - Flow

**To Reproduce**
1. import the flow
2. Make the change to the value
![image](https://user-images.githubusercontent.com/47640245/102150347-34792a00-3e25-11eb-8e04-e4f43dd8e0cb.png)
3, Put the value directly in the action where it says Site Address
![image](https://user-images.githubusercontent.com/47640245/102150399-5672ac80-3e25-11eb-96fa-1e823be79581.png)
4. Ran the flow and it errors with the message badgateway
![image](https://user-images.githubusercontent.com/47640245/102150502-989bee00-3e25-11eb-8444-558c1eafc24b.png)
![image](https://user-images.githubusercontent.com/47640245/102150533-a782a080-3e25-11eb-9084-3d2b2b9d82a5.png)

**Comment by JeneferM-MSFT** [comment]
Hello. This is just a helper flow on the side of the toolkit. If it isnt working, please create the list by hand. 
From [the documentation](https://docs.microsoft.com/power-platform/guidance/coe/setup-nurture-components#create-the-library), here is what the list structure needs to be:
![image](https://user-images.githubusercontent.com/62659043/102150682-034d2980-3e26-11eb-8312-1e8b06dfbbbc.png)

**Comment by SteveAsch** [comment]
I did this now. The system says Title already exists but it does not exist in edit view columns. All other fields are fine, going to use Name instead of Title
