### ISSUE TITLE
CoE Flows not Working - View when "Get Flow fails - Error Handing" will run after "Configure run after"

### ISSUE THREAD

**Issue by shannonfascendini** [microsoft/powerapps-tools#637]
**Describe the bug**
The CoE Dashboard is up and running but I've recently run into issues with 3 particular flows and them failing. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - CoE Toolkit
 - Flows failing: Admin | Sync Template v2 (Power apps user shared with), Sync Audit Logs, Admin | Sync Template V2 (model driven apps)
 - 
![image](https://user-images.githubusercontent.com/76061272/102243869-a7d47780-3ec9-11eb-86f3-8c2905c7006d.png)

![image](https://user-images.githubusercontent.com/76061272/102243901-b327a300-3ec9-11eb-8eed-e3366f0bfebc.png)

**Comment by JeneferM-MSFT** [comment]
Hello. We will need more information that this. 

What version of Core are you running? 1.71.7 is the latest
![image](https://user-images.githubusercontent.com/62659043/102245600-9c298680-3eb2-11eb-95b5-f0c4d6b70953.png)

If you do not have this latest version please upgrade (see how with [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)) and see if you still repro.

If so, then lets please use a single flow for the next questions:
- which flow in particular should we use? I suggest the MDA's one as it is the oldest and most stable. 
- in that flow, which action is failing? 
- is it failing for all environments and apps or just some?

**Comment by shannonfascendini** [comment]
I am on version 1.54. I will update and let you know.

**Comment by JeneferM-MSFT** [comment]
Thank you. Be sure to remove any unmanaged layers from the flows before you update or you will not receive the updates on each flow. 

See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for details

**Comment by shannonfascendini** [comment]
All of the unmanaged layers are removed. However, I do not see the option to upgrade. I've imported from the github package.

**Comment by JeneferM-MSFT** [comment]
Upgrade is initiated by just importing the solution again, the reference to "Select Upgrade" is once you are in the import UX from the product.

**Comment by shannonfascendini** [comment]
Ok I am on 1.71.7 now. Do you want me to now just see if the flows continue to fail?

**Comment by JeneferM-MSFT** [comment]
yes please, and then if so: 

- which flow in particular should we use? I suggest the MDA's one as it is the oldest and most stable.
- in that flow, which action is failing?
- is it failing for all environments and apps or just some?

**Comment by shannonfascendini** [comment]
So the Admin | Sync Audit logs Flow is still failing and is failing at the GetActivitiesbyOperation action. 
I'm not sure if it's failing for all environments and apps or just some. My guess is all. 

Error Details: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

**Comment by JeneferM-MSFT** [comment]
Let's not repurpose this bug for a new issue please. It makes management of this list a nightmare and makes it not usable for other folks using the CoE. It sounds like the original issue you posted about is no longer occurring, is that accurate?

**Comment by shannonfascendini** [comment]
I'm not sure I understand what you're talking about. Wouldn't this be the same issue? I originally said my flows were failing. This above is one of them after the update you had me do.

**Comment by JeneferM-MSFT** [comment]
"Flows not working" is too broad a description to be actionable. This bug is tracking your original failure, that a subset of flows failed with the Configure Run After issue. 

If that is no longer occuring, then great. We can move on. But we have to address issues granularly like that. 

I've updated your title to reflect.

**Comment by JeneferM-MSFT** [comment]
Closing this out as it seems like the original issue was resolved. 
Regarding new issues for audit logs, please look through all the tips in the [audit logs setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog). There are a bunch of spots where this one can fail so please look through all those tips. 
Permissions might point to this one, for example: Are audit logs enabled, and do you have permission to view the audit logs? Check protection.office.com > Search > Audit Log Search.
