### ISSUE TITLE
(Power Apps User Shared With) flow possibly not removing share data

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#638]
Hi there,

While looking at what users/groups our apps are shared with according to the CoE data, I noticed something interesting.  (CoE Core Components version 1.71.7, "fresh" install instead of an upgrade)

We have one app in particular that was shared with a large number of individuals and a couple of groups.  This information was loaded into the CoE tables with the (Power Apps User Shared With) flow, as shown below.
![image](https://user-images.githubusercontent.com/50427725/102269972-3ea53200-3ed2-11eb-8579-0be45cd21778.png)

About a week later, the team cleaned up the sharing on that app. When I go to the Power Platform Admin Center and look at that app's Details, it shows the below shares.
![image](https://user-images.githubusercontent.com/50427725/102270188-8fb52600-3ed2-11eb-83e0-c4cb2d2d4679.png)

However, the CoE data still shows the app as being shared with the list in the first screenshot, even days after the changes were made.  We run the (Power Apps User Shared With) flow daily.

I wonder if the flow isn't deleting "unshared" with from the tables?
Thank you for the help!
Christi

**Comment by JeneferM-MSFT** [comment]
Hello, thanks for using CoE and posting such an actionable bug. We wont be able to fix before the upcoming next release but your issue is well described and understood, so we will be able to address soon-ish :) 

Thanks again

**Comment by osbornecc** [comment]
Thank you!  We can work around it until then :-)

Thanks for all the work on CoE!

**Comment by manuelap-msft** [comment]
Thank you for letting us know about this bug! We have this fixed locally now, and it will be part of our next release early next year! 

Thanks for using the CoE!

**Comment by manuelap-msft** [comment]
This has been fixed in the version that was just released. Thanks for your patience, we didn't want to release a new version over the holiday period :)
