### ISSUE TITLE
[BUG]: Developer Compliance Center - You don't have permission to view this data.

### ISSUE THREAD

**Issue by SteveAsch** [microsoft/powerapps-tools#639]
When the user tries to access the **Developer Compliance Center Canvas App** they receive the following error

You don't have permission to view this data. Server Response: PowerApps Apps failed: Principal user (Id=927ac3d7-1ec6-ea11-a812-000d3a3ab749, type=8, roleCount=1, privilegeCount=25, accessMode=0), is missing prvReadadmin_App privilege (Id=dc64fe3b-5fb5-4c86-8eb5-c344787c1435) on OTC=10049 for entity 'admin_app'. context.Caller=927ac3d7-1ec6-ea11-a812-000d3a3ab749

 - Solution Governance
 - Version 1.25
 - App or Flow App
 - 
![image](https://user-images.githubusercontent.com/47640245/102395748-678bfc80-3f90-11eb-938f-ef6f25219198.png)

1. Application shared with user
2. Click on URL to access shared APP
3.
![image](https://user-images.githubusercontent.com/47640245/102396366-365ffc00-3f91-11eb-9cab-d3d5f1e0a787.png)

3. The following error is at the top of the window.

You don't have permission to view this data. Server Response: PowerApps Apps failed: Principal user (Id=927ac3d7-1ec6-ea11-a812-000d3a3ab749, type=8, roleCount=1, privilegeCount=25, accessMode=0), is missing prvReadadmin_App privilege (Id=dc64fe3b-5fb5-4c86-8eb5-c344787c1435) on OTC=10049 for entity 'admin_app'. context.Caller=927ac3d7-1ec6-ea11-a812-000d3a3ab749

**Expected behavior**
They should be able to access the app

**Additional context**
When we shared the app with the user we gave her **Approvals User** and **Common Data service** user permissions

**Comment by JeneferM-MSFT** [comment]
Power Apps does not auto grant permissions to backends. You need to grant permissions separately. 
This is detailed in the setup instructions. Please see here: [developer compliance center](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#developer-compliance-center)

**Comment by sagarwalsharepoint** [comment]
I'm having the EAXCT same issue and the instructions provided by JeneferM doesn't help. Something is going on which is not right when the app is shared with the user
