### ISSUE TITLE
Admin | Compliance detail request

### ISSUE THREAD

**Issue by javirivas80** [microsoft/powerapps-tools#64]
Hello in the last release. I have problem with workflow Admin | Compliance detail request.
When I executed this faile with my user (adminr) UPN 7331c3ca-3de3-4f2f-a173-bab6f512eaf6. (The user whith imported the solution)

The error:
Details
Start time
Feb 5, 06:36 PM (59 sec ago)
Duration
00:00:05
Status
Failed
Error
Action 'Condition:_Audit_apps_that_are_broadly_shared' failed
![image](https://user-images.githubusercontent.com/44674421/73885938-673ab500-4847-11ea-8a6f-1230ff9ebed6.png)
![image](https://user-images.githubusercontent.com/44674421/73886002-83d6ed00-4847-11ea-8060-07152d645309.png)

OUT List Apps
{
  "@odata.context": "https://unitedstates-002.azure-apim.net/apim/commondataservice/shared-commondataser-fa21bc39-f62e-4cba-a4cf-4c2adaf789bc/$metadata#datasets('default.cds')/tables('admin_apps')/items",
  "value": [
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(99d1ecd9-5248-ea11-a812-000d3a339ac5)",
      "@odata.etag": "",
      "ItemInternalId": "99d1ecd9-5248-ea11-a812-000d3a339ac5",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-02-05T20:05:36Z",
      "createdon": "2020-02-05T20:42:28Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:30Z",
      "admin_mau_state": 1,
      "versionnumber": 730456,
      "admin_recordmodified": "2020-02-05",
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": "2020-02-05T20:42:23Z",
      "admin_appmodifiedon": "2020-02-05T20:05:36Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "99d1ecd9-5248-ea11-a812-000d3a339ac5",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": true,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910001,
      "_admin_powerappstype_label": "Model Driven",
      "admin_displayname": "Power Platform Admin View",
      "_admin_appowner_value": "7331c3ca-3de3-4f2f-a173-bab6f512eaf6",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "2c6af479-96a2-4c89-aa93-a2b9bb889cb7",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": null,
      "admin_appenvironmentdisplayname": null,
      "admin_sharepointformurl": null,
      "admin_appiconuri": null,
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": null,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": null,
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": null,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": null,
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    },
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(ef72d899-5af3-4aab-a6fd-0e53c414c69b)",
      "@odata.etag": "",
      "ItemInternalId": "ef72d899-5af3-4aab-a6fd-0e53c414c69b",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-01-31T20:13:33Z",
      "createdon": "2020-02-05T20:36:20Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:23Z",
      "admin_mau_state": 1,
      "versionnumber": 730458,
      "admin_recordmodified": null,
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": null,
      "admin_appmodifiedon": "2020-01-31T20:13:33Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "ef72d899-5af3-4aab-a6fd-0e53c414c69b",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": false,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910000,
      "_admin_powerappstype_label": "Canvas",
      "admin_displayname": "dfggfg",
      "_admin_appowner_value": "119b9326-8851-415f-9394-ca96ed8fb5b8",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "3dc31287-4ea4-4836-8dc0-b79832cc6af4",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": "2020-01-31T20:13:33Z",
      "admin_appenvironmentdisplayname": "BeOnConsulting (default) (org64cf54c1)",
      "admin_sharepointformurl": null,
      "admin_appiconuri": "https://pafeblobprodcq.blob.core.windows.net:443/20200131t000000z444a81abce7a41318c984ca5c89f9014/logoSmallFile?sv=2018-03-28&sr=c&sig=VeeD%2FNWWwvO3SCpe2RZEIqBHeNmaZAgOWtov%2BsYGiGE%3D&se=2020-03-09T20%3A19%3A13Z&sp=rl",
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": 0,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": "rgba(0, 176, 240, 1)",
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": 0,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": null,
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    },
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(bda021f6-ab4a-4752-8a66-2e14a7601703)",
      "@odata.etag": "",
      "ItemInternalId": "bda021f6-ab4a-4752-8a66-2e14a7601703",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-02-05T20:05:47Z",
      "createdon": "2020-02-05T20:42:28Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:28Z",
      "admin_mau_state": 1,
      "versionnumber": 730459,
      "admin_recordmodified": null,
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": null,
      "admin_appmodifiedon": "2020-02-05T20:05:47Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "bda021f6-ab4a-4752-8a66-2e14a7601703",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": false,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910000,
      "_admin_powerappstype_label": "Canvas",
      "admin_displayname": "DLP Customizer",
      "_admin_appowner_value": "7331c3ca-3de3-4f2f-a173-bab6f512eaf6",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "2c6af479-96a2-4c89-aa93-a2b9bb889cb7",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": "2020-02-05T20:05:47Z",
      "admin_appenvironmentdisplayname": "DemoGobierno (org93c3b86e)",
      "admin_sharepointformurl": null,
      "admin_appiconuri": "https://pafeblobprodby.blob.core.windows.net:443/20200205t000000z4cf0eca4352b42dabc2fe66491945ebc/admin_dlpcustomizer_3220e_BackgroundImageUri?sv=2018-03-28&sr=c&sig=jaFd2Wl1AmfJN5rDlJOwi%2BjMWDptIzFHm6FR9DJvU0s%3D&se=2020-03-09T19%3A18%3A43Z&sp=rl",
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": 0,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": "rgba(44, 125, 154, 1)",
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": 0,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": "Update DLP policies to add custom connectors and HTTP type connectors",
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    },
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(feb106b2-b279-41c6-810c-2e95d5ab942b)",
      "@odata.etag": "",
      "ItemInternalId": "feb106b2-b279-41c6-810c-2e95d5ab942b",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-02-05T20:05:39Z",
      "createdon": "2020-02-05T20:42:28Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:28Z",
      "admin_mau_state": 1,
      "versionnumber": 730460,
      "admin_recordmodified": null,
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": null,
      "admin_appmodifiedon": "2020-02-05T20:05:39Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "feb106b2-b279-41c6-810c-2e95d5ab942b",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": false,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910000,
      "_admin_powerappstype_label": "Canvas",
      "admin_displayname": "Set New App Owner",
      "_admin_appowner_value": "7331c3ca-3de3-4f2f-a173-bab6f512eaf6",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "2c6af479-96a2-4c89-aa93-a2b9bb889cb7",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": "2020-02-05T20:05:39Z",
      "admin_appenvironmentdisplayname": "DemoGobierno (org93c3b86e)",
      "admin_sharepointformurl": null,
      "admin_appiconuri": "https://pafeblobprodby.blob.core.windows.net:443/20200205t000000z8483becdd9304febbcfce76099435013/admin_powerappsadminsetowner_8b129_BackgroundImageUri?sv=2018-03-28&sr=c&sig=GX8ONKUr2dYyJ1mAOoACmgcmRETInzOIWV6QTPwfheY%3D&se=2020-03-09T19%3A18%3A43Z&sp=rl",
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": 0,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": "rgba(81, 92, 107, 1)",
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": 0,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": "As a Global Admin, Environment Admin or Business Application Admin this app can be used to re-assign app owner roles or add new users to an app.",
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    },
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(e20c05f2-88c0-4c63-8e97-455227085e56)",
      "@odata.etag": "",
      "ItemInternalId": "e20c05f2-88c0-4c63-8e97-455227085e56",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-02-05T20:25:46Z",
      "createdon": "2020-02-05T20:36:20Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:28Z",
      "admin_mau_state": 1,
      "versionnumber": 730461,
      "admin_recordmodified": null,
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": "2020-02-05T20:42:18Z",
      "admin_appmodifiedon": "2020-02-05T20:25:46Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "e20c05f2-88c0-4c63-8e97-455227085e56",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": true,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910000,
      "_admin_powerappstype_label": "Canvas",
      "admin_displayname": "AplicaciónTest",
      "_admin_appowner_value": "d0e50d61-f10f-4349-8ffd-4cf14cd9337b",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "3dc31287-4ea4-4836-8dc0-b79832cc6af4",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": "2020-02-05T20:25:46Z",
      "admin_appenvironmentdisplayname": "BeOnConsulting (default) (org64cf54c1)",
      "admin_sharepointformurl": null,
      "admin_appiconuri": "https://pafeblobprodcq.blob.core.windows.net:443/20200205t000000z99d9a50b0326434ca4b1359f3bc9b7aa/logoSmallFile?sv=2018-03-28&sr=c&sig=bz2S7LMWOFCAxEl%2FWiA05qw5qowHwIZe3LqToHIziwc%3D&se=2020-03-09T10%3A13%3A39Z&sp=rl",
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": 0,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": "rgba(0, 176, 240, 1)",
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": 0,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": null,
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    },
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(78d3a6c5-ac4f-49fa-aeb8-65332d402ccb)",
      "@odata.etag": "",
      "ItemInternalId": "78d3a6c5-ac4f-49fa-aeb8-65332d402ccb",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-01-31T19:17:26Z",
      "createdon": "2020-02-05T20:36:20Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:29Z",
      "admin_mau_state": 1,
      "versionnumber": 730462,
      "admin_recordmodified": null,
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": "2020-02-05T20:42:18Z",
      "admin_appmodifiedon": "2020-01-31T19:17:26Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "78d3a6c5-ac4f-49fa-aeb8-65332d402ccb",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": true,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910000,
      "_admin_powerappstype_label": "Canvas",
      "admin_displayname": "t2",
      "_admin_appowner_value": "d0e50d61-f10f-4349-8ffd-4cf14cd9337b",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "3dc31287-4ea4-4836-8dc0-b79832cc6af4",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": "2020-01-31T19:17:26Z",
      "admin_appenvironmentdisplayname": "BeOnConsulting (default) (org64cf54c1)",
      "admin_sharepointformurl": null,
      "admin_appiconuri": "https://pafeblobprodcq.blob.core.windows.net:443/20200131t000000z75b3e828048f45cb92ff0155eee4c524/logoSmallFile?sv=2018-03-28&sr=c&sig=slnHKmrPtuA9RR%2FZrGBiu9HjuckMs7BUwlsRYvySelA%3D&se=2020-03-09T10%3A13%3A39Z&sp=rl",
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": 0,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": "rgba(0, 176, 240, 1)",
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": 0,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": null,
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    },
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(b02197ea-c612-420a-878b-b5efccd34e2c)",
      "@odata.etag": "",
      "ItemInternalId": "b02197ea-c612-420a-878b-b5efccd34e2c",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-02-05T20:05:44Z",
      "createdon": "2020-02-05T20:42:27Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:27Z",
      "admin_mau_state": 1,
      "versionnumber": 730463,
      "admin_recordmodified": null,
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": null,
      "admin_appmodifiedon": "2020-02-05T20:05:44Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "b02197ea-c612-420a-878b-b5efccd34e2c",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": false,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910000,
      "_admin_powerappstype_label": "Canvas",
      "admin_displayname": "DLP Editor",
      "_admin_appowner_value": "7331c3ca-3de3-4f2f-a173-bab6f512eaf6",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "2c6af479-96a2-4c89-aa93-a2b9bb889cb7",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": "2020-02-05T20:05:44Z",
      "admin_appenvironmentdisplayname": "DemoGobierno (org93c3b86e)",
      "admin_sharepointformurl": null,
      "admin_appiconuri": "https://pafeblobprodby.blob.core.windows.net:443/20200205t000000zc060155916264a308f635d606b290ac6/admin_dlpeditor_a721d_BackgroundImageUri?sv=2018-03-28&sr=c&sig=gXviSP%2BNYKfi%2BPulV%2FN4%2Bd57aQbQwvo%2FYy7clqEWisU%3D&se=2020-03-09T19%3A18%3A43Z&sp=rl",
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": 0,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": "rgba(81, 92, 107, 1)",
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": 0,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": null,
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    },
    {
      "@odata.id": "https://org93c3b86e.crm.dynamics.com/api/data/v9.0/admin_apps(fdabe76c-a74d-497b-b9be-c4cb5f46c149)",
      "@odata.etag": "",
      "ItemInternalId": "fdabe76c-a74d-497b-b9be-c4cb5f46c149",
      "statecode": 0,
      "_statecode_label": "Active",
      "admin_reviewedapp": false,
      "statuscode": 1,
      "_statuscode_label": "Active",
      "admin_appcreatedon": "2020-02-03T18:52:31Z",
      "createdon": "2020-02-05T20:36:21Z",
      "admin_approvalstatus": 597910005,
      "_admin_approvalstatus_label": "Inactive",
      "_ownerid_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_ownerid_type": "systemusers",
      "modifiedon": "2020-02-05T20:42:30Z",
      "admin_mau_state": 1,
      "versionnumber": 730464,
      "admin_recordmodified": null,
      "timezoneruleversionnumber": 4,
      "admin_appdeletedon": "2020-02-05T20:42:18Z",
      "admin_appmodifiedon": "2020-02-03T22:06:14Z",
      "admin_requirement_5": false,
      "_modifiedby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_modifiedby_type": "systemusers",
      "admin_appid": "fdabe76c-a74d-497b-b9be-c4cb5f46c149",
      "admin_makersubmittedrequirements": false,
      "admin_mau_date": "2020-02-05T21:06:09Z",
      "admin_mau": 0,
      "admin_appdeleted": true,
      "admin_inappcatalogfeatured": false,
      "_createdby_value": "ef1db1fe-6c94-4dd9-bc1f-04c9242ae8b8",
      "_createdby_type": "systemusers",
      "_owningbusinessunit_value": "281e3cb2-e044-ea11-a813-000d3a33f176",
      "_owningbusinessunit_type": "businessunits",
      "admin_powerappstype": 597910000,
      "_admin_powerappstype_label": "Canvas",
      "admin_displayname": "Demo1",
      "_admin_appowner_value": "d0e50d61-f10f-4349-8ffd-4cf14cd9337b",
      "_admin_appowner_type": "admin_makers",
      "admin_inappcatalog": false,
      "_admin_appenvironment_value": "3dc31287-4ea4-4836-8dc0-b79832cc6af4",
      "_admin_appenvironment_type": "admin_environments",
      "processid": null,
      "admin_city": null,
      "utcconversiontimezonecode": null,
      "_stageid_value": null,
      "_owningteam_value": null,
      "admin_apppublished": "2020-02-03T18:52:31Z",
      "admin_appenvironmentdisplayname": "BeOnConsulting (default) (org64cf54c1)",
      "admin_sharepointformurl": null,
      "admin_appiconuri": "https://pafeblobprodcq.blob.core.windows.net:443/20200203t000000zd0eea01f6a11494ab8654c64e2bf0106/logoSmallFile?sv=2018-03-28&sr=c&sig=ll5ujhS2hSUygwSoQo%2FgVJvLlZGCwArjxaWbUBNXz%2Fw%3D&se=2020-03-09T10%3A13%3A39Z&sp=rl",
      "admin_appownerdisplayname": null,
      "_createdonbehalfby_value": null,
      "_modifiedonbehalfby_value": null,
      "traversedpath": null,
      "admin_requirement_1": null,
      "admin_appsharedgroups": 0,
      "admin_category": null,
      "_admin_category_label": "",
      "admin_iconbackgroundcolor": "rgba(0, 176, 240, 1)",
      "admin_department": null,
      "admin_requirement_3": null,
      "admin_riskassessment": null,
      "_admin_riskassessment_label": "",
      "admin_appsharedusers": 0,
      "admin_requirement_4": null,
      "_admin_requirement_4_label": "",
      "admin_requirement_6": null,
      "_admin_requirement_6_label": "",
      "admin_appdescription": null,
      "importsequencenumber": null,
      "admin_requirement_2": null,
      "overriddencreatedon": null,
      "admin_country": null
    }
  ]
}

**Comment by javirivas80** [comment]
I updated the error image in English language
![image](https://user-images.githubusercontent.com/44674421/73933652-a99dd980-48bb-11ea-8331-76fbfa834966.png)

**Comment by manuelap-msft** [comment]
Thank you for reporting this issue, I was able to reproduce and fix this. Please find attached a Flow where this issue is fixed, you can import this into your environment.
We will also fix it as part of the next release of the solution.
[AdminCompliancedetailrequest_20200206122731.zip](https://github.com/microsoft/powerapps-tools/files/4165038/AdminCompliancedetailrequest_20200206122731.zip)
