### ISSUE TITLE
[BUG]: Change Power Apps version. 

### ISSUE THREAD

**Issue by SteveAsch** [microsoft/powerapps-tools#643]
**Describe the bug**
When I open the AppTemplatePhone.msapp file in the canvas app designer I get the following error message.
Change the Power Apps version. Something happened to the Power Apps version you were using. Learn more
![image](https://user-images.githubusercontent.com/47640245/102642755-02144900-4113-11eb-8477-76aca31ee649.png)

The learn more button does nothing.
When I click my only option it just brings me back to where I was.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution theming
 - Version 1.0.0.9
 - App

**To Reproduce**
1. Go to make.powerapps.com, open my environment
2. Click on Apps > new App > canvas 
3. Select Blank App > Phone Layout
4. In Power App designer click file > open > browse. find the *.msapp file and click open
5. Click Dont Save
6. Then I get the error message. 

**Expected behavior**
It should open the file and allow me to set the theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/47640245/102643473-31778580-4114-11eb-8d86-20d68859d7c2.png)

**Comment by JeneferM-MSFT** [comment]
What do you mean by this: When I click my only option it just brings me back to where I was.
The product did just make a changes that requires you to upgrade, this would apply to apps outside our toolkit as well.

**Comment by SteveAsch** [comment]
I mean the only option I have is to update to the new version. It just closes when I click it.
Could you provide more information on what needs to be updated? How are you recommending I upgrade?

**Comment by JeneferM-MSFT** [comment]
Upgrade was the wrong word sorry. I meant update, just the words on that button there. 
This is a dialog from the product itself, not our solution. In my experience with this product dialog I just click that button and the product updates underneath me. 

I think you might need to re-save the msapp files from an instance of PowerApps that you've updated.

**Comment by SteveAsch** [comment]
Hi, 
I've resaved the msapp file multiple times.
How do I update PowerApps exactly?

**Comment by JeneferM-MSFT** [comment]
Sorry I can't help you with that. Updating PowerApps is a product thing, and not in my wheelhouse. Normally the single click does the trick but if thats not the case for you then you will need product support.

**Comment by SteveAsch** [comment]
looks like it's the *.msapp file and not my Power Apps installation.
I reinstalled the theming solution and that resolved the error
this item can be closed now

**Comment by JeneferM-MSFT** [comment]
wonderful thanks for letting me know.
