### ISSUE TITLE
Unable to import CenterofExcellenceAuditComponents_1_24_managed.zip - "components missing" error

### ISSUE THREAD

**Issue by craigcliff** [microsoft/powerapps-tools#645]
Hello,

I have successfully managed to import and configure the following components: CenterofExcellenceCoreComponents_1_70_6_managed.zip, however I'm experiencing an issue importing CenterofExcellenceAuditComponents_1_24_managed.zip.  

After switching to classic view and running the import, the following errors appear: 

![image](https://user-images.githubusercontent.com/3979072/102772946-106f9880-4391-11eb-945e-b697653e843e.png)

Any assistance would be greatly appreciated.

**Comment by manuelap-msft** [comment]
Hello,

the latest version of our Core Components is 1.71.7 - typically, the Governance (Audit) and Nurture components have a dependency on the latest Core Components solution, that contains all our tables. Would you be able to upgrade to the latest version of Core and check if you're still experiencing this issue?

Thank you
Manuela

**Comment by craigcliff** [comment]
Perfect, thanks Manuela - works like a charm after upgrading the core components.
