### ISSUE TITLE
Database storage capacity allocation issue 

### ISSUE THREAD

**Issue by justinkumar** [microsoft/powerapps-tools#65]
I followed the document TenantSetup.docx to create a new demo tenant and assigned appropriate license as mentioned in the document, but Start-admininaday-setup script is unable to create new environment because database storage capacity allocated with zero MB (file 20GB and Log 2GB). 
Could you throw some light on where the issue is?

J Justin

**Comment by manuelap-msft** [comment]
You will need 1 GB capacity for each environment that you want to create https://docs.microsoft.com/en-us/power-platform/admin/capacity-storage 

Likely your tenant does not have enough capacity to create the environments required for Admin in a day.
