### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Apps) flow failing for some apps

### ISSUE THREAD

**Issue by dchrist27** [microsoft/powerapps-tools#650]
This is a follow up to BUG #642 that I previously opened.

I went ahead and removed the unmanaged layers within all of the flows for core components and reapplied 1.71.7.  That worked because I now see the correct flow.

![image](https://user-images.githubusercontent.com/52799471/102928127-d61ffd00-445d-11eb-9ef5-855f90357b82.png)

This flow ran last night but I still see two errors and both coincidentally are within the CoE environment.

![image](https://user-images.githubusercontent.com/52799471/102928451-521a4500-445e-11eb-9478-24499fe7df41.png)

Here's one example:

![image](https://user-images.githubusercontent.com/52799471/102927926-82151880-445d-11eb-9579-933ea87844bb.png)

Screenshot of flow:
![image](https://user-images.githubusercontent.com/52799471/102928292-12ebf400-445e-11eb-8df7-13927a2ea34a.png)

I also wanted to ask if someone could look at bug #615 that was opened a couple weeks ago.  I also went through and removed the unmanaged layers within the 2 flows of the audit logs module but still see the red box.   I should also note that I removed the API connection and recreated it but that still didn't help.

**Comment by JeneferM-MSFT** [comment]
Can you please share what is the error you are seeing? 
Click "Next Failed" to get to the failure, go to the failing step. 
Here's what a failure looks like from an unrelated flow. I need the detail in that error body in order to help here.

**Comment by dchrist27** [comment]
Sorry about that...Here's the expanded flow:

![image](https://user-images.githubusercontent.com/52799471/102933630-361ba100-4468-11eb-9bc7-aa1908b7f264.png)

Out of the 8 existing connections.  3 failed.

1- not found and the other 2 were flagged as bad request.

{
  "status": 404,
  "message": "admin_ConnectionReference With Id = 61e74fe0-2543-eb11-a813-000d3a103d9b Does Not Exist",
  "error": {
    "message": "admin_ConnectionReference With Id = 61e74fe0-2543-eb11-a813-000d3a103d9b Does Not Exist"
  },
  "source": "org5e8fb475.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 5268ba1f-1af7-4485-a4db-aa57ba98ef3f"
}

Body of 1st Bad Request
{
  "status": 400,
  "message": "More than one concurrent Delete requests detected for an Entity 6ae74fe0-2543-eb11-a813-000d3a103d9b and ObjectTypeCode 10040.",
  "error": {
    "message": "More than one concurrent Delete requests detected for an Entity 6ae74fe0-2543-eb11-a813-000d3a103d9b and ObjectTypeCode 10040."
  },
  "source": "org5e8fb475.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 12a3267f-cb8e-4f6a-9a91-7285e3a52bb1"
}

Body of 2nd Bad Request 

{
  "status": 400,
  "message": "More than one concurrent Delete requests detected for an Entity e66893e1-2543-eb11-a813-000d3a9dd42d and ObjectTypeCode 10040.",
  "error": {
    "message": "More than one concurrent Delete requests detected for an Entity e66893e1-2543-eb11-a813-000d3a9dd42d and ObjectTypeCode 10040."
  },
  "source": "org5e8fb475.crm.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 6845a534-6c92-40e4-88ea-cb8641091a3e"
}

Let me know if you need anything else.

**Comment by JeneferM-MSFT** [comment]
This seems to fall along the generalized reliability issues we are seeing from the old CDS connector. 
Our team is currently investing in a rewrite of these to the new CDS connector. 
Expected to ship sometime in January.

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!
