### ISSUE TITLE
[IDEA]: issue title

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#651]
**Describe the idea**
For the "PowerApps App" table and the "Flow" table the "Audit" tabs are quite different. The "PowerApps App" table has more options on it, such as ROI. It would be good if they could be more aligned with the same type of wording/layout even controls, such as the PowerApps App" table shows a column called "Business Impact" which looks like the below: 
![image](https://user-images.githubusercontent.com/68440710/102969075-f9de5400-44ec-11eb-9cef-c07eac42134c.png)

Whereas the Flow table shows a column called "Business Impact" which looks like the below:
![image](https://user-images.githubusercontent.com/68440710/102969171-25613e80-44ed-11eb-8ee7-45c1942b3e00.png)

It's nothing major, but a mirroring between the two forms would be welcomed, as it makes it easier to govern the platform.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.71.7
 - App: Power Platform Admin View

**To Reproduce**
1. Go to the Power Platform Admin View app
2. Open up an App and in another tab a Flow
3. Click the "Audit" tab on both and look at the differences

**Expected behavior**
I would like the look, feel and controls to be more aligned.

**Screenshots**
Added these above..

**Additional context**
Nothing from me, thanks.

**Comment by JeneferM-MSFT** [comment]
Thanks Gary. These features are not available for other objects. So the tables cannot be aligned. 
Thanks for using CoE

**Comment by GarryPope** [comment]
Hello Jenefer,

Happy New Year! Thanks for the reply, and sorry for the delay. I'm not sure what you mean by the features are not available on other objects, sorry. 

Thanks,

Garry
