### ISSUE TITLE
[BUG]: Unable to execute Admin | Sync Template v2 (Check Deleted)

### ISSUE THREAD

**Issue by bhabhat** [microsoft/powerapps-tools#652]
**Description of the bug**
Following the steps in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows, getting the following error while executing Admin | Sync Template v2 (Check Deleted)
Error Message - 
Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidFlow","message":"The pagination policy of workflow run action 'Get_Environments' of type 'ApiConnection' at line '1' and column '2029' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '100000'. Maximum: '5000'."}}".

 - Solution - Core
 - Version --
 - App or Flow - Admin | Sync Template v2 (Check Deleted)

**To Reproduce**
1. Follow steps mentioned in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows 
2. Invoke Admin | Sync Template v2 (Check Deleted)

**Expected behavior**
As per link above- 
Turn on: CLEANUP - Admin | Sync Template v2 (Check Deleted)
Wait until it finishes before you turn on any other flows.
Ensure the Sync Template flows are already turned on for the following object types:
Apps, Connectors, Custom Connectors, Flows, Model Driven Apps, PVA, RPA
Turn on Admin | Sync Template v2. When it completes, turn it back off.
This will cause the flows for the objects listed in step 3 to run. Wait until all of these complete.
Turn back on Admin | Sync Template v2.
Turn on the rest of the flows listed in the solution

**Screenshots**
![image](https://user-images.githubusercontent.com/68844942/102979785-907e3580-452c-11eb-9e5c-721230d63e0e.png)

**Comment by JeneferM-MSFT** [comment]
Hello. All the flows have this pagination policy. It indicates that you are using an insufficient license. 
Note that we do not support trial licenses for the toolkit any longer due to some product changes that upped the requirements for throttling purposes.

**Comment by JeneferM-MSFT** [comment]
See here for the license types: [Performance profiles](https://docs.microsoft.com/power-automate/limits-and-config#performance-profiles)
And here for pagination limits: [Paginated items](https://docs.microsoft.com/power-automate/limits-and-config#concurrency-looping-and-debatching-limits)

And hence our requirements for licenses. [What licenses do I need to run this solution?](https://docs.microsoft.com/power-platform/guidance/coe/setup#what-licenses-do-i-need-to-run-this-solution)
