### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (Model Driven Apps)

### ISSUE THREAD

**Issue by SteveAsch** [microsoft/powerapps-tools#654]
**Describe the bug**
I get an email with that looks as follows:
![image](https://user-images.githubusercontent.com/47640245/103015383-30b86800-44f5-11eb-9a31-9fbf1365969f.png)

When I look at the flow run it shows this:
![image](https://user-images.githubusercontent.com/47640245/103015439-488fec00-44f5-11eb-8aea-0bbb39ed930d.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.71.7
 - FLOW Admin | Sync Template v2 (Model Driven Apps)

**To Reproduce**

**Expected behavior**
The flow should complete without issue 

**Screenshots**
See above

**Comment by JeneferM-MSFT** [comment]
As you can see the terminate is a catch here so this is an intentional failure. If you look at the title of the scope it shows you why. We intentionally fail here if you are unable to get the values for Model Driven Apps as it indicates you dont have correct permissions for that environment. 
As shown in #629 , you lack permissions to other environments like Default as well. 
So this is expected and indicates that you need higher permissions to accurately gather information about the tenant.

**Comment by SteveAsch** [comment]
Here are my roles in Azure
![image](https://user-images.githubusercontent.com/47640245/103019943-74fb3680-44fc-11eb-9858-d30dd5021cc9.png)
Am I missing anything?

**Comment by SteveAsch** [comment]
This looks alot like issue #550
Note the environments are Teams environments

**Comment by JeneferM-MSFT** [comment]
Issue 550 is caught in the condition above where you are failing here. You see the one that checks for Teams sku.
A Global admin can definately run our solution and collect all environments. 
Here is what the role as a whole looks like, perhaps you have a setting incorrect. 
![image](https://user-images.githubusercontent.com/62659043/103022829-96aaec80-4501-11eb-9f6c-fa57c05962bd.png)

**Comment by SteveAsch** [comment]
It's on failing on the Teams environments. All others are fine (expect for the wrong app bug already identified).
PP Admin role is the same as what I have. Not sure what more is needed. I'll try removing the role and re-adding. Not sure what else to try

**Comment by JeneferM-MSFT** [comment]
If the flow is not correctly catching teams sku, then your main sync flow didn't update correctly when you updated to _7. Likely you had unmanaged layers on Admin | Sync Template v2 

Please go to Admin | Sync Template v2 and see what API Version is listed for the Get Environments call
![image](https://user-images.githubusercontent.com/62659043/103024531-dde6ac80-4504-11eb-86c5-e65b6e95f2b7.png)

If it shows a different value, you will need to remove the unmanaged layers from all flows and update again.
See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by SteveAsch** [comment]
![image](https://user-images.githubusercontent.com/47640245/103025007-cbb93e00-4505-11eb-8c86-a3230c617668.png)

**Comment by SteveAsch** [comment]
After removing and readding the PP Admin role from the  Azure Portal user. The flow **Admin | Sync Template v2 (Model Driven Apps)** completed without issue
I will monitor over the next few days
Thanks

**Comment by JeneferM-MSFT** [comment]
great news

**Comment by SteveAsch** [comment]
unfortunately, the error is not gone
![image](https://user-images.githubusercontent.com/47640245/103098554-07184300-45c0-11eb-9b34-bc4affa9c443.png)

![image](https://user-images.githubusercontent.com/47640245/103098599-3464f100-45c0-11eb-97f4-5be2c914246d.png)

If I run it manually it succeeds without error.
Any ideas?

**Comment by SteveAsch** [comment]
Any updates on this issue?
Thanks
