### ISSUE TITLE
Admin | App Archive and Clean Up - Start Approval

### ISSUE THREAD

**Issue by paleman74** [microsoft/powerapps-tools#656]
**Describe the bug**
We have created an environment for the CoE and added an Security Group that include all the Power Platform administrators of our organization.
When testing "Admin | App Archive and Clean Up - Start Approval" runs into this error:
"error": {
    "code": "UserNotMemberOfCdsSecurityGroup",
    "message": "The user 'xxx' cannot be created in CDS because the account is not a member of group 'Power Platform Administrators'. Please ask an administrator to add user to the group."
  }
Question 1)- We would like to know if a solution or workaround already exist or if it is possible to create an Approval for the CoE environment, without sharing the CoE Env with the entire organization (all users) what is consider a security issue by our security department. 
Question 2)- We have found that when removing the CoE Environment security group the two Model driven applications in CoE toolkit,  Power Platform Admin View and  App Archive and Clean up View can be are presented to all users. Is it possible these Model driven apps being "visible" to all users.
**Component (please tell us which flow or app you are experiencing issues with):**
 - Center of Excellence - Governance Components
 - Version 1.25
 - Admin | App Archive and Clean Up - Start Approval

**To Reproduce**
1.Flow Run in step: Create approval.
Output Body:
"error": {
    "code": "UserNotMemberOfCdsSecurityGroup",
    "message": "The user 'xxx' cannot be created in CDS because the account is not a member of group 'Power Platform Administrators'. Please ask an administrator to add user to the group."
  }
**Expected behavior**
Approvals reaching all users when CoE Env is limited to a security group of Admins. If not possible how to avoid Mode driven apps being visible to all users.

**Comment by JeneferM-MSFT** [comment]
Hello. Please see the following from our limitations page [security groups and approvals](https://docs.microsoft.com/power-platform/guidance/coe/limitations#security-groups-and-approvals)
