### ISSUE TITLE
Cannot turn on first flow - error - MissingAdequateQuotaPolicy

### ISSUE THREAD

**Issue by philsilvio** [microsoft/powerapps-tools#657]
I am trying to set up the CoE Starter kit.  First in our Test Tenant.  I am a full admin in the test tenant and have all the licenses that I think I need.  However, when I try to turn on the first flow - CLEANUP - Admin | Sync Template v2 (Check Deleted)  I get what appears to be a licensing issue:

Your flow could not turn on: CLEANUP - Admin | Sync Template v2 (Check Deleted). Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"MissingAdequateQuotaPolicy","message":"The user 'guid here' does not have a service plan adequate for the non-Standard connection. https://go.microsoft.com/fwlink/?linkid=2123710"}}".

I have tried and looked at everything and cannot determine what the issue is.  We have an E5 licensing with Microsoft.    I have checked the connectors based on the instructions, the connections are all established and I have admin and maker permissions in the environment.   I have been searching the internet for assistance, but can't find anything relevant for this error.  Any help to point me in the right direction.

Here is a list of the licenses that have been granted in the tenant:

**Office 365 E3**
Power Virtual Agents for Office 365
Common Data Service for Teams
Project for Office (Plan E3)
Common Data Service
Microsoft Kaizala Pro
Whiteboard (Plan 2)
Information Protection for Office 365 - Standard
Insights by MyAnalytics
To-Do (Plan 2)
Microsoft Stream for O365 E3 SKU
Microsoft Teams
Sway
Yammer Enterprise
SharePoint (Plan 2)
Microsoft 365 E5
Power Virtual Agents for Office 365
Common Data Service for Teams
Project for Office (Plan E5)
Microsoft Endpoint DLP
Common Data Service
Premium Encryption in Office 365
Whiteboard (Plan 3)
Information Protection for Office 365 - Premium
Information Protection for Office 365 - Standard
Insights by MyAnalytics
To-Do (Plan 3)
Power Automate for Office 365
PowerApps for Office 365
Microsoft Forms (Plan E5)
Microsoft StaffHub
Microsoft Teams
Windows 10 Enterprise
Azure Information Protection Premium P2
Azure Active Directory Premium P2
Azure Information Protection Premium P1
Azure Rights Management
Microsoft Azure Multi-Factor Authentication
Microsoft Intune
Azure Active Directory Premium P1
Office for the web
SharePoint (Plan 2)
Microsoft Planner
The latest desktop version of Office
Exchange Online (Plan 2)
Microsoft MyAnalytics (Full)
Power BI Pro
Enterprise Mobility + Security E3
Cloud App Security Discovery
Azure Information Protection Premium P1
Microsoft Intune
Azure Rights Management
Azure Active Directory Premium P1
Microsoft Azure Multi-Factor Authentication
Power Virtual Agents for Office 365
Common Data Service for Teams
Project for Office (Plan E3)
Common Data Service
Microsoft Kaizala Pro
Whiteboard (Plan 2)
Information Protection for Office 365 - Standard
Insights by MyAnalytics
To-Do (Plan 2)
Microsoft Stream for O365 E3 SKU
Microsoft Teams
Sway
Yammer Enterprise
SharePoint (Plan 2)

**Microsoft 365 E5**
Power Virtual Agents for Office 365
Common Data Service for Teams
Project for Office (Plan E5)
Microsoft Endpoint DLP
Common Data Service
Premium Encryption in Office 365
Whiteboard (Plan 3)
Information Protection for Office 365 - Premium
Information Protection for Office 365 - Standard
Insights by MyAnalytics
To-Do (Plan 3)
Power Automate for Office 365
PowerApps for Office 365
Microsoft Forms (Plan E5)
Microsoft StaffHub
Microsoft Teams
Windows 10 Enterprise
Azure Information Protection Premium P2
Azure Active Directory Premium P2
Azure Information Protection Premium P1
Azure Rights Management
Microsoft Azure Multi-Factor Authentication
Microsoft Intune
Azure Active Directory Premium P1
Office for the web
SharePoint (Plan 2)
Microsoft Planner
The latest desktop version of Office
Exchange Online (Plan 2)
Microsoft MyAnalytics (Full)
Power BI Pro
Enterprise Mobility + Security E3
Cloud App Security Discovery
Azure Information Protection Premium P1
Microsoft Intune
Azure Rights Management
Azure Active Directory Premium P1
Microsoft Azure Multi-Factor Authentication

**Comment by manuelap-msft** [comment]
Our flows require a Power Apps or Power Automate premium license, see limits and configurations per license here: https://docs.microsoft.com/en-us/power-automate/limits-and-config

Most of our flows require pagination of 10,000, as well as the throughput and API call limits associated with premium licenses, thus are not able to run with a seeded Office 365 license. 

Hope this helps and thank you for using the CoE!

**Comment by philsilvio** [comment]
@manuelap-msft  - not sure we understand what you are saying about the licenses.  I have an E5 license for both PowerApps and PowerAutomate and we don't see any other licenses to be able to select.  Our Power Automate license, being E5 should allow for unlimited queries.

**Comment by manuelap-msft** [comment]
That is not correct, different throttling, quota and API call limits apply for different licenses.

Any Microsoft 365 License - so an E5 license - falls in the Low Performance Profile (see https://docs.microsoft.com/en-us/power-automate/limits-and-config). A Low Performance Profile only allows for a pagination setting of 5,000.

A dedicated Power Automate per user or per flow license (premium license) allows for pagination settings of up to 100,000. Many of our flows require these higher pagination settings, and thus a premium license is required. See https://flow.microsoft.com/en-us/pricing/
