### ISSUE TITLE
[BUG]: issue Blob key 20201220045738176001058$20201220051009720011291$audit_general$Audit_General$emea0012 in the url is invalidtitle

### ISSUE THREAD

**Issue by AAnkitaAswal** [microsoft/powerapps-tools#658]
**Describe the bug**We are trying to set up COE kit in our environment.
 While setting Audit log components .

The flow fails with error-Blob key 20201220045738176001058$20201220051009720011291$audit_general$Audit_General$emea0012 in the url is invalid.

**Comment by JeneferM-MSFT** [comment]
Please see #616 
Duplicate of #616

**Comment by AAnkitaAswal** [comment]
Thank you Jenefer. it was really stupid :)
Happy New Year.
