### ISSUE TITLE
[BUG]: Can not see UI Flow data in the Power BI dashboard and Power Platform Admin App

### ISSUE THREAD

**Issue by Jl-seo** [microsoft/powerapps-tools#659]
**Describe the bug**
Can not connect any data of Ui flows at the Power BI dashboard and Power Platform admin view apps
'Admin\Sync Template v2 (UI Flow Runs)' flow history status have been succeeded but when I choose edit mode, flow have an issue. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture] : Core
 - Version [e.g. 1.29] : 1.71
 - App or Flow [e.g. Sync Template (v2)] : Sync Template (v2) (UI Flow Runs)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/76484790/103207865-b9466680-4942-11eb-9e3b-316954569789.png)
![image](https://user-images.githubusercontent.com/76484790/103208053-16dab300-4943-11eb-9978-6da745986f03.png)

**Additional context**
and i can't see anything audit logs Part, too. is it bug or did i miss something when i installed CoE Starter kit?
please give me some advice.
FYI, my region is South Korea, Central.

**Comment by manuelap-msft** [comment]
For the Audit Log, you will need to have set up the Audit Log solution - did you complete that? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog - if you are still experiencing issues, please raise a separate issue for that. 

For the UI flow issue, can you confirm you have environments where UI flows have been created and your user has System Administrator access to those environments?

**Comment by Jl-seo** [comment]
> For the Audit Log, you will need to have set up the Audit Log solution - did you complete that? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog - if you are still experiencing issues, please raise a separate issue for that.
> 

https://user-images.githubusercontent.com/76484790/103504525-06728d00-4e9b-11eb-851b-4619fa7003aa.mp4

**I have set up the Audit Log Solution but it didn't work. why this happened?**

> For the UI flow issue, can you confirm you have environments where UI flows have been created and your user has System Administrator access to those environments?

yes. my user is System Administrator access to those environments but it happened again. can u explain it?

**Comment by JeneferM-MSFT** [comment]
Let's please cover 1 issue per GitHub issue, that makes it easier to track and for others to read. This on will cover the issue with the UI flows as described in the title. 

Can you confirm you have environments where UI flows have been created and your user has System Administrator access to those environments?

**Comment by JeneferM-MSFT** [comment]
Hello. Checking in again. 
Can you confirm you have environments where UI flows have been created and your user has System Administrator access to those environments?

**Comment by JeneferM-MSFT** [comment]
Closing out issues with no action items for our team.
