### ISSUE TITLE
Connection References are only being logged for Flows, not Apps

### ISSUE THREAD

**Issue by bartsneary** [microsoft/powerapps-tools#66]
It appears to me that in the sync templates (v2) for Apps and Model Driven Apps, we just aren't creating/updating the connection references with the App information that would allow you to see all the Apps and all the Flows any particular connector is being used for across a tenant.  Flow Connection References are being created/updated just fine.  Am I just missing it or is it missing from the Apps templates?

**Comment by manuelap-msft** [comment]
Connection references are being logged for Canvas Apps as well.
