### ISSUE TITLE
[BUG]: Office 365 Management APIs Custom Connector disappears from App Registrations in Azure AD after about 2 weeks

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#662]
**Describe the bug**
Since Installing Center of Excellence - Core Components v1.71.7 the Custom Connector Office 365 Management APIs keeps disappearing from APP Registrations in Azure Active Directory

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version  - 1.71.7
 - App or Flow - Custom Connector

**To Reproduce**
1. Install Core Components v1.71.7
2. Install the Office 365 Management APIs in App Registrations in Azure Active Directory
3. Wait 2 weeks
4. See error - notice that Office 365 Management APIs has disappeared from App Registrations

**Expected behavior**
Office 365 Management APIs remains in APP Registrations

**Screenshots**

**Additional context**
I have raised an incident with Microsoft Premier Support and they have come back saying that they cannot find anything wrong with Azure AD and therefore it would seem to be a problem with the Centre of Excellence.
This has now happened on two different tenancies.

**Comment by manuelap-msft** [comment]
If you've shared a screenshot above, I'm afraid that didn't come through - what's the error message you're seeing?

The App Registration is set up to enable connecting to the Audit Log - it's completely separate from the CoE starter kit, and nothing we do in the kit would remove or delete an App Registration - it's just a way to connect to the API, as an alternative to connect via basic auth (with your username and password). 

We don't set up or delete the registration in the kit - all that has to be done manually.

Learn more: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

**Comment by NPrice99** [comment]
So if Microsoft premier support says it's not them and you say it's not you, where do I go next ?

**Comment by manuelap-msft** [comment]
Unfortunately, we can only support issues related to the CoE Starter Kit, not the Power Platform or Azure products. As I said, we neither set up nor delete the App Registration as part of the kit - it's something you do manually during setup. I don't think there's even connectors available to automatically delete an app registration - in any case, it's certainly not something we do. 

I would get back to Premier Support and discuss this further with them.
