### ISSUE TITLE
[BUG]: Unable to update "admin_AdminMail" environment variable value

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#663]
Hello Team,

Hope you are doing well!

This is regarding updating the existing environment variable value of the core component. During the first import, I have set "email1@mail.com" which require to be updated as "email2@mail.com" - To do so, I have tried updating the value from the default solution, however CoE flow still fetches the "email1@mail.com" value from the environment variable as in data table "Environment Values" it still reflects the value "email1@mail.com".

Further, I have checked as follows:

Unable to delete the "Core" solution to setup the variable again during re-import
Unable to delete "admin_AdminMail" environment variable from the solution as well.

Any suggestion, how can I re-update  "admin_AdminMail" environment variable value for the CoE Flows to work with newly updated value?

Looking forward to hearing from you soon!

Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

1. Please navigate to make.powerapps.com
2. Select "Solutions"
3. Select "Default Solution" (you might have to scroll down a bit to find this one)
4. Change the filter from showing All to only showing Environment Variables
5. Find the Admin eMail variable and update it there

This is called out here in the second "Important" box I think we can make that a bit more obvious by including the steps I just mentioned here.
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

**Comment by manuelap-msft** [comment]
Closing out issues with no further action on us. Please let us know if you continue to face issues! Thanks for using the CoE!
