### ISSUE TITLE
[BUG]: DLP Editor Doesn't check all applications

### ISSUE THREAD

**Issue by raphaelcharreyron-bib** [microsoft/powerapps-tools#664]
**Describe the bug**
Application DLP Editor: Limitation on the number of applications returned for control. We 've more than 4000 application for 1 environment. Connector PowerAppsforAdmins is limited to 1100 apps to return.
PowerAppsforAdmins.GetAdminApps(galEnvironments.Selected.name,{'$top':1100})

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [**Core Components**]
 - Version [**1.45**]
 - App or Flow [**DLP Editor**]

**To Reproduce**
1. You must have more than 1100 applications in one environment
2. Check DLP rules will check compliance only on first 1100 apps.

**Expected behavior**
We would like DLP rules are checked on all applications independently the number of apps in one environment.

**Screenshots**
No screenshot

**Additional context**
This happens in all COE applications which use the connector to get applications (It's limited to 1100 apps). You have to implement pagination. Same issue with application "Set App owner".

**Comment by manuelap-msft** [comment]
Due to product changes, the DLP Editor has been deprecated in v 1.70 of the CoE Starter Kit, and we therefore no longer support it. See https://docs.microsoft.com/en-us/power-platform/guidance/coe/release-notes/core-1.70#deprecation
