### ISSUE TITLE
Power BI Desktop Monitor Flows View Missing Display Names

### ISSUE THREAD

**Issue by medicineshow** [microsoft/powerapps-tools#665]
**Describe the bug**
In the monitor Flows page, the display name of the flows is not being displayed in the window even though in the filter table, all of the available flows are present.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : Core
 - Version: 1.71.7
 - Flows page in the Monitor component

![image](https://user-images.githubusercontent.com/17124284/103545674-cc54bb80-4e99-11eb-9337-a55e6badf079.png)

**Comment by medicineshow** [comment]
![image](https://user-images.githubusercontent.com/17124284/103546284-a4b22300-4e9a-11eb-88ff-db26c41f42bf.png)

**Comment by JeneferM-MSFT** [comment]
Can you please expand the filter pane and see what you have filtered? 
![image](https://user-images.githubusercontent.com/62659043/103550934-757dc080-4e5e-11eb-82f0-2a775d848782.png)

**Comment by medicineshow** [comment]
Hi, thanks for the response. Filters look OK

![image](https://user-images.githubusercontent.com/17124284/103579832-f37aaf80-4ed0-11eb-8863-e7fb71d83f09.png)

**Comment by JeneferM-MSFT** [comment]
Can you please go to the flows table and export it? Once you have it in Excel, please see if the data there looks correct, like what you would have expected to see in the table in the Power BI. 

![image](https://user-images.githubusercontent.com/62659043/103587247-afb98300-4e9b-11eb-8b3e-8f24c5f3fdca.png)
![image](https://user-images.githubusercontent.com/62659043/103587312-d8da1380-4e9b-11eb-86b9-1c1281ee8413.png)

**Comment by medicineshow** [comment]
The exported data contains the admin_displayname fields

![image](https://user-images.githubusercontent.com/17124284/103628567-2192da80-4f37-11eb-8691-34cddd9b0084.png)

**Comment by JeneferM-MSFT** [comment]
In the powerbi report, can you sort by something besides creator? Perhaps you have some blanks.

**Comment by medicineshow** [comment]
None of the fields show in the display window despite the fact that they are present in the filter. I can see no blanks either.

**Comment by manuelap-msft** [comment]
Can you share what filters you have selected on the page itself (in the grey area)?
![image](https://user-images.githubusercontent.com/55705669/103893203-cbfc3080-50e4-11eb-96db-f82c6bc96195.png)

**Comment by medicineshow** [comment]
I have the same.

![image](https://user-images.githubusercontent.com/17124284/103896970-b68a0500-50ea-11eb-976f-d0241168045d.png)

**Comment by medicineshow** [comment]
These are the fields selected for the table
![image](https://user-images.githubusercontent.com/17124284/103897162-05379f00-50eb-11eb-9a8f-457b67dbb35f.png)

**Comment by medicineshow** [comment]
as you can see. They are available but are not displaying in the window

![image](https://user-images.githubusercontent.com/17124284/103897293-3617d400-50eb-11eb-8730-3646bc2d1808.png)

**Comment by medicineshow** [comment]
I have solved it. The display was set to Don't Summarize. Once I changed it to First, all of the display names appeared along with the rest of the data. Worth noting that this was how it was out of the box.

![image](https://user-images.githubusercontent.com/17124284/103918699-0676c500-5107-11eb-93d2-42dd25ebd2d7.png)
