### ISSUE TITLE
[BUG]: Admin | Flow Archive and Clean Up - Start Approval - Failed due to invalid schema

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#667]
**Describe the bug**
I was checking that if the archival flow is getting deleted and I came across that this flow is kept failing because of the invalid schema. 
[
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0].admin_appenvironmentname",
    "schemaId": "#/items/properties/admin_appenvironmentname",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0].admin_appdisplayname",
    "schemaId": "#/items/properties/admin_appdisplayname",
    "errorType": "type",
    "childErrors": []
  }
]

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Governance Component 
 - Version - e.g. 1.25
 - Flow -  Admin | Flow Archive and Clean Up - Start Approval

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/103691659-83b60480-4f64-11eb-9506-fabe2e1736ca.png)
![image](https://user-images.githubusercontent.com/75992078/103691832-d8f21600-4f64-11eb-91ca-4c14b9382791.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
It looks like you might not have the environment information for whatever reason in the Archive Approval table. This might be due to old entries from previous iterations of the flow where bugs existed. 

Can you please run the Admin | Approval Clean Up flow, it has a scope that deletes old approvals, and then see if you still repro this.
![image](https://user-images.githubusercontent.com/62659043/103694944-9aeaf700-4f50-11eb-8317-b900f6ce2e4f.png)

**Comment by AkashPatel136** [comment]
Admin | Approval Clean Up Flow is getting failed for me. I have opened another case #666. Once that is resolved I will try this and update it here.

**Comment by JeneferM-MSFT** [comment]
The cleanup occurs above where you are failing there. Can you lookin your failure and validate that the scope I show above passed? If so, then you should be unblocked form seeing if this passes now.

**Comment by AkashPatel136** [comment]
![image](https://user-images.githubusercontent.com/75992078/103780701-566c6380-5003-11eb-8575-bf19dc2742ea.png)

**Comment by JeneferM-MSFT** [comment]
perfect. looks like either my guess was wrong (didnt find any to clean) or it had cleaned them in a previous run. 
Can you please see if you still repro this issue now in Start Approval?

**Comment by AkashPatel136** [comment]
Flow Start Approval is getting failed

![image](https://user-images.githubusercontent.com/75992078/103788557-f37fca00-500c-11eb-846a-7f883b44603e.png)


[
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0].admin_appenvironmentname",
    "schemaId": "#/items/properties/admin_appenvironmentname",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0].admin_appdisplayname",
    "schemaId": "#/items/properties/admin_appdisplayname",
    "errorType": "type",
    "childErrors": []
  }
]

**Comment by JeneferM-MSFT** [comment]
Can you please export the data from the Archive Approval table? 
Then see if there are any rows with no value in the App Environment Name column? 
If so, delete those rows, they are old and corrupt.

**Comment by JeneferM-MSFT** [comment]
For clarity, delete them from the Table in Power Platform, not from the exported Excel table

**Comment by AkashPatel136** [comment]
I had 2 records where the app environment name column was empty. I have run the Admin | Flow Archive and Clean Up flow and it will take some time to complete. I will update once it is complete.

**Comment by AkashPatel136** [comment]
Flow run successfully.
