### ISSUE TITLE
[BUG]: More than one concurrent Delete requests detected for an Entity

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#668]
**Describe the bug**
Admin | Sync Template v2 (Apps) fails - More than one concurrent Delete requests detected for an Entity 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core Components
 - Version - 1.71.5
 - Flow -  Admin | Sync Template v2 (Apps)

**To Reproduce**
Run nightly 

**Expected behavior**
I do not expect it to fail

**Screenshots**
{
  "status": 400,
  "message": "More than one concurrent Delete requests detected for an Entity ce51d399-ea4e-eb11-a812-000d3a29426f and ObjectTypeCode 10052.",
  "error": {
    "message": "More than one concurrent Delete requests detected for an Entity ce51d399-ea4e-eb11-a812-000d3a29426f and ObjectTypeCode 10052."
  },
  "source": "xxxxxxxxx.crm4.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: 91b7ec19-b47b-4c4d-8f2c-9134f0189301"
}

**Additional context**
![image](https://user-images.githubusercontent.com/8484048/103754490-528d1100-5004-11eb-8667-110a4a5b5270.png)

**Comment by JeneferM-MSFT** [comment]
Hey Nigel, this is not in the flow you mention, so presumably you are referring to a failure in a different flow? 

You may have a copy of the main sync flow running running or you may have a duplicate callbacks registered on the environment table. Neither of these are things which we can assist with. 

We are about to ship a v3 of the sync templates. My suggestion is that you upgrade to that, and then if you still repro this issue you will either need to get a support ticket to resolve the duplicate callbacks, or recreate the CoE in a new environemnt.

**Comment by NPrice99** [comment]
[Admin sync template screenshot.docx](https://github.com/microsoft/powerapps-tools/files/5775989/Admin.sync.template.screenshot.docx)

Hi Jenefer here is the proof that it was the flow I mentioned Regards  Nigel

**Comment by JeneferM-MSFT** [comment]
Aw apologies, I had just seen the v2, not the (apps).
