### ISSUE TITLE
[BUG]: Permissions missing in Power Platform Admin SR

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#671]
**Describe the bug**
I set up the CoE with an Application User and noticed that few privileges are missing in Power Platform Admin SR for the following custom entities which lead to flows failures :
- Connection Reference
- Power Platform User
- Power Platform User Role
- Sync Flow Errors

Also, there isn't no permissions for BPF processes in this security role.

I checked in other security roles, in case of we need to combine them, but these permissions are nowhere.

By reviewing the Security Role permissions and existing custom entities, I also found missing permissions for the following entities. But I didn't experiment issues in the flows :
- Chatbot
- Flow Action Detail
- Flow Resource
- PVA Component
- PVA Component Flow Lookup
- RPA
- RPA Sessions

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - v1.71.7
 - Security Role - Power Platform Admin SR

**Expected behavior**
My expectation is : when user has the Power Platform Admin SR, he should have full control on everything. Correct me if I'm wrong.

**Comment by JeneferM-MSFT** [comment]
Thank you for posting! We have fixed this up locally for release with the next version.

**Comment by JeneferM-MSFT** [comment]
We have just released a version today with this fix, as well as a major rewrite for reliability of the inventory suite. 
Be sure to follow the new steps for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)
And thanks for using CoE!
