### ISSUE TITLE
[BUG]: Power BI Admin Report shows over time data wrong

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#673]
**Describe the bug**
I was looking at the data in the Power BI report and it shows me overtime data for Jul 2021 through Nov 2021 and it does not show me current data. I have attached the screenshot of my report. Based on my knowledge to should show current time data. 

I have added @topness-msft since we discussed and he suggested me to tell you and get your thoughts on it. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/103817355-8a13b180-5034-11eb-887a-11d11eac801f.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

thanks for reporting this! Looks like we had a formatting issue in the MMM-YYYY part that caused this behaviour. Would you be able to try this report: https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-01-07.pbit

And let me know if that looks better?

Thank you
Manuela

**Comment by AkashPatel136** [comment]
Hi @manuelap-msft 

This report looks better. Thank You so much for your help.

**Comment by AkashPatel136** [comment]
Probably want to fix this issue in Overview - Power Automate Tab

![image](https://user-images.githubusercontent.com/75992078/103904222-ff31c600-50ca-11eb-808b-0fb90d56bf77.png)

**Comment by manuelap-msft** [comment]
Looks like the relationship between maker and flow dropped, can you try this file? https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-01-07.pbit

**Comment by AkashPatel136** [comment]
issue resolved
