### ISSUE TITLE
[Request]: for error 429 : Add retries to get operations

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#676]
**Describe the bug**
Starter Kit flows can sometimes fail with 429 errors (on CDS actions)
For example : Admin | Sync Template v2 (Flows)
We changed parameter of some CDS actions of the flow, it works better. But I don't think it's the right solution to change the settings of all CDS related actions.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Core Components
 - Version 1.71.7
 - App or Flow : "Admin | Sync Template v2 (Flows)" for example

**To Reproduce**
Run Flow Sync Template V2

**Screenshots**
429 error :
![image](https://user-images.githubusercontent.com/34766578/103906273-fc04fd00-50ff-11eb-8269-0dc4918fa116.png)

Changed parameters :
![image](https://user-images.githubusercontent.com/34766578/103906032-ab8d9f80-50ff-11eb-888a-dac85766ba87.png)

**Comment by JeneferM-MSFT** [comment]
Hello. We have not added this to gets for some reason. Let me explore to be sure it doesnt somehow conflict with pagination and if not, we can add these. 
Thanks for using CoE

**Comment by orauch-a** [comment]
Sometimes we have the same problem on other actions (when requesting CDS) in the flow. Is there no other solution than adding it to all CDS actions ?

**Comment by JeneferM-MSFT** [comment]
Not to our knowledge, no. This is a feature each backend may or may not implement to protect it from DNS type calls.
[limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#timeouts-in-the-admin--sync-template-v3)

**Comment by JeneferM-MSFT** [comment]
Thanks for your suggestion, and for using CoE!
The newest version of Core has this complete, if I missed any individual calls which bite you, please just pose another issue.
