### ISSUE TITLE
Trying to delete solutions

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#677]
Hello there,

Yesterday, I updated both the Core Components and the Audit Logs solutions to the latest versions.  On the previous version of Core Components, I had made changes to the CLEANUP - Admin | Sync Template **_v2_** (Power Apps User Shared With) flow. 
 Also, I was seeing that the data bug from #638 was not resolved in my instance.  

When I updated the Core Components, I noticed that the flow still says **v2** while the ones that updated say **v3**.  I tried to follow the steps to remove unmanaged layers as shown in https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates.  But I believe that because I'm in GCC, I cannot see that option
![image](https://user-images.githubusercontent.com/50427725/103930117-1c6a9280-50d3-11eb-8c25-889105d356bc.png)

So I attempted to delete the Core Components solution so I could re-import it fresh (like I've done before).  It has a dependency of the Audit Log solution so it wouldn't delete.  OK, so I try to delete the Audit Log solution and it won't delete.  It has a dependency.  The "tenant" environment variable is used by the Power Platform Admin View app.  Because that app is part of a managed solution, the delete option is grayed out.
![image](https://user-images.githubusercontent.com/50427725/103930094-11affd80-50d3-11eb-83fb-ca7689a12799.png)

I'm stuck.  Do you have any tricks I could try that might help?
Thanks!

**Comment by JeneferM-MSFT** [comment]
I'm sorry I dont have help for you here. Deleting solutions is something that doesnt work very well. You may be in a terrible state at this point and have to just start from a fresh environment. 
I'm really sorry about this. 
If you'd like to persue help from the product team first, you can create a ticket. 
Once you get the update working, or you fresh install, if 638 still repros, please re-post and the engineer that fixed will take a look.

**Comment by osbornecc** [comment]
I was afraid of that.  I will create a ticket and reference this issue for details.
Thank you.

**Comment by JeneferM-MSFT** [comment]
Of course, and I'm terribly sorry about the pain.
