### ISSUE TITLE
[BUG]: After latest update duplicate core components

### ISSUE THREAD

**Issue by SteveAsch** [microsoft/powerapps-tools#678]
**Describe the bug**
After importing the update to the core components we have duplicate solutions

![image](https://user-images.githubusercontent.com/47640245/103956392-48027280-50fd-11eb-8bfd-6ad48f26de1e.png)

**To Reproduce**
1. Go to solutions
2. Import solution, it mentioned that this is an update
3. After installation look in the solutions area

**Expected behavior**
The existing solution should have been updated as in the past

**Screenshots**
see above

**Comment by SteveAsch** [comment]
Please advise if I should uninstall the older managed solution

**Comment by JeneferM-MSFT** [comment]
If you wait, does one of them go away? When I install often both show up for a small period of time and then the old one goes away after (presumably) some clean up or something occurs.

**Comment by SteveAsch** [comment]
Just checked this morning, they are both still there

**Comment by JeneferM-MSFT** [comment]
I see. You have hit some product issue then, and I'm afraid I cannot assist. We just use the install path that the product provides. You will need to reach out to product support with a support ticket, or try install in a fresh location. 
Given the issues you were facing in your desciption, a fresh install might help.
