### ISSUE TITLE
[BUG]: Error when update "Center of Excellence - Core Components"

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#680]
**Describe the bug**
When we import the lastest version of the starter kit, we get the following error :
![image](https://user-images.githubusercontent.com/34766578/104027706-10acc800-51c8-11eb-9306-971fa4550fc2.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Core Components
 - Version 1.71.7 update to 1.73

**To Reproduce**
1. Solution Center of Excellence - Core Components Version 1.71.7 installed
2. ImportCenterofExcellenceCoreComponents_1_73_managed.zip
3. Error
4. 2 solutions "Center of Excellence - Core Components"  installed on the environment

![image](https://user-images.githubusercontent.com/34766578/104028174-b829fa80-51c8-11eb-9483-e19c405c8fc7.png)

**Comment by manuelap-msft** [comment]
Could you try and first upgrade the Governance components solution to the latest version? https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceAuditComponents_1_28_managed.zip

**Comment by orauch-a** [comment]
Sorry, but to correct my problem I deleted the "Governance components solution" and then I deleted the old version v1.71.7 of the core components solution.

**Comment by manuelap-msft** [comment]
I see, did you try upgrading the Governance components first and that failed as well?

**Comment by JeneferM-MSFT** [comment]
New version with this fixed is now live. Thanks for using CoE
