### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Apps) Error when no modified date on app

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#681]
**Describe the bug**
Admin | Sync Template v3 (Apps) is in error.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Core Components
 - Version 1.73
 - Flow Admin | Sync Template v3 (Apps)

**To Reproduce**
1. Launch Admin | Sync Template v3
1. Go to 'Admin | Sync Template v3 (Apps) History'
2. See Error
![image](https://user-images.githubusercontent.com/34766578/104164048-a0848900-53f7-11eb-8360-9feb81d012e0.png)

**Comment by JeneferM-MSFT** [comment]
I believe you are in a state where you don't have a modified date on the app. 
Apps made now come with an automatic modified date, so this is likely a very old app. 
Can you please explore that using the Set App Permissions app?

**Comment by JeneferM-MSFT** [comment]
I believe I found a way to fix this for you automatically. Can you please install the latest version of Core and let me know if it resolves for you?

**Comment by JeneferM-MSFT** [comment]
Closing issue as fixed. Thanks for using CoE

**Comment by orauch-a** [comment]
Sorry for the delay in my response, but it's still failing :

![image](https://user-images.githubusercontent.com/34766578/105195188-ac302800-5b3a-11eb-9387-e60b57f39a57.png)

![image](https://user-images.githubusercontent.com/34766578/105195244-c23de880-5b3a-11eb-9243-7f5c33735969.png)

**Comment by JeneferM-MSFT** [comment]
if you move this comparison to the bottom (to as shown here) does it pass? Wondering if it short circuits and wont run that one.
![image](https://user-images.githubusercontent.com/62659043/105197302-b251e480-5af9-11eb-8891-5821eefb7967.png)

**Comment by orauch-a** [comment]
Now, it's ok !
Thank you so much !

**Comment by JeneferM-MSFT** [comment]
Thank you! I have made this change and so next release will have this tweak in there.

**Comment by JeneferM-MSFT** [comment]
Re-opening to dupe to this until ship that new fix.

**Comment by tsegato** [comment]
@JeneferM-MSFT what will happen to updates if you reorder this? Can you later still update the starter kit?

**Comment by JeneferM-MSFT** [comment]
Yes, you'll just need to remove the unmanaged layer that is created in the solution by the edit before you update. 
This is explained here: [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by tsegato** [comment]
Thanks. Highly appreciated. And btw great job on this starter kit, good to see Microsoft takes ownership on the governance part too.

**Comment by JeneferM-MSFT** [comment]
Hello. This fix is now released. 

In order to update be sure to remove any unmanaged layer created by edits as shown in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

Thanks for helping make CoE great!
