### ISSUE TITLE
[BUG]: Wrong Flow Names in Sync Flow Errors

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#682]
**Describe the bug**
Flow names are wrong in Flows Errors report due to hard-coded values when Flow Errors records are created.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.73
 - All Admin | Sync Flows

**Expected behavior**
Names in Flow Error reports match with real Flows names.
Must be **Admin | Sync Template v3** instead of **Admin | Sync Template v2**.

**Screenshots**
![image](https://user-images.githubusercontent.com/22662809/104182316-928f3200-5410-11eb-995f-eb2c64570075.png)
![image](https://user-images.githubusercontent.com/22662809/104182454-c702ee00-5410-11eb-828b-28848a3e63b0.png)
![image](https://user-images.githubusercontent.com/22662809/104182472-cff3bf80-5410-11eb-8065-045b8f588bde.png)

**Comment by JeneferM-MSFT** [comment]
Can you please tell me, does this impact the link created when sync flow errors runs?

**Comment by lcimon** [comment]
Links work well. This issue is very minor, it is just matter to not confuse the users during the analysis of the root cause.

**Comment by JeneferM-MSFT** [comment]
Wonderful. Thank for for replying. I was just hoping to understand for urgency of change. 

Appreciate your help, and that you are using CoE!

**Comment by JeneferM-MSFT** [comment]
This is resolved in the new version that just shipped, if I missed one please just let me know.
