### ISSUE TITLE
[BUG]: Audit Logs - DLP Violation in Flow "[Child] Admin | Sync Logs" with Custom O365 Audit Log Connector

### ISSUE THREAD

**Issue by milo4u** [microsoft/powerapps-tools#684]
[BUG]: Audit Logs - DLP Violation in Flow "[Child] Admin | Sync Logs" with Custom O365 Audit Log Connector
----------------------------------------------------------------------------------------------------------

**Describe the bug**
The Flow "[Child] Admin | Sync Logs" went from status "On" to status "Suspended"  (Turned Off) during Christmas.
Until then we we're able to collect audit logs from the tenant successfully.

Now when I'm trying to "Turn On" the flow again, I get this error message:
-> Your flow could not turn on: [Child] Admin | Sync Logs. Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow 'b3f632f1-6bd7-a337-86ee-15d181a2f275' cannot be activated due to admin API policies."}}".

The strange thing is
---------------------
The Custom Audit log connector is still in the corresponding DLP policy's "Business Data" section.
   - You can't see the connector in the Power Platform Admin Center anymore ... ?
   - But If I use the Power Platform Admin Connector to get the Details of this policy, I can find the Connector looking at the JSON response for this
     
apiGroups: hbi 

{ "id": "/providers/Microsoft.PowerApps/scopes/admin/environments/9f849632-d348-41e3-b82b-b40ef9a32bee/apis/shared_admin-5foffice-20365-20management-20api-5f439b5d80b7cda036",
  "name": "Office 365 Management API (CoE PROD)",
  "type": "Microsoft.PowerApps/apis"
}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Center of Excellence - Audit Logs
 - Version 1.0.0.17
 - Flow:     [Child] Admin | Sync Logs

**To Reproduce**
1. Go to the flow '[Child] Admin | Sync Logs'
2. Click on 'Turn On'
3. See error

**Expected behavior**
The flow could be "Turned On" again

**Screenshots**
Screenshot 1 - Flow Error.PNG
Screenshot 2 - DLP - Custom Connector not shown
Screenshot 3 - DLP - Custom Connector is still in policy (JSON).PNG
Screenshot 4a - Custom Connector is still there.PNG
Screenshot 4b - Custom Connector is still working.PNG

![Screenshot 1 - Flow Error](https://user-images.githubusercontent.com/77280340/104324659-02bcb700-54e8-11eb-8c00-6ae8b62e9a19.PNG)
![Screenshot 2 - DLP - Custom Connector not shown](https://user-images.githubusercontent.com/77280340/104324675-07816b00-54e8-11eb-992c-d7b04f6e8374.PNG)
![Screenshot 3 - DLP - Custom Connector is still in policy (JSON)](https://user-images.githubusercontent.com/77280340/104324684-0a7c5b80-54e8-11eb-8b6b-a0f0dd924f58.PNG)
![Screenshot 4a - Custom Connector is still there](https://user-images.githubusercontent.com/77280340/104324691-0e0fe280-54e8-11eb-979e-a5bb66e4b8b1.PNG)
![Screenshot 4b - Custom Connector is still working](https://user-images.githubusercontent.com/77280340/104324704-10723c80-54e8-11eb-84d0-88a829b70973.PNG)

**Additional context**

**Comment by manuelap-msft** [comment]
Please refer to the comms shared in the Message Center MC231184 for guidance on the update that has happened (copied excerpt below for reference). Please note that while custom connectors are not visible on the tenant admin UI anymore, it is still visible on PPAC UI for environment admins (as custom connectors are associated with specific environments).

**Title:**  
Power Platform - Update to Add-CustomConnectorToPolicy data loss prevention (DLP) PowerShell cmdlet   

**Description:**  
Beginning December, 2020, data loss prevention (DLP) policies’ Powershell cmdlet Add-CustomConnectorToPolicy will no longer support the addition of custom connectors to tenant level policies. Additionally, custom connectors added to tenant level policies will not be shown on the data loss prevention page (DLP UI) in the Power Platform admin center.  

**What specifically is changing?**  
Beginning December, 2020, the Powershell cmdlet Add-CustomConnectorToPolicy will no longer support the addition of custom connectors to tenant level policies. 

Legacy policies that were created with this feature will continue to function, however custom connectors added from the PowerShell cmdlet will not appear show on the Power Platform admin center user interface for tenant level policies. This cmdlet will be deprecated in Q1 2021, and environment admins should begin migrating to the data loss prevention cmdlets New-DlpPolicy, Get-DlpPolicy, Set-DlpPolicy and Remove-DlpPolicy to create and manage DLP policies with all types of connectors including custom connectors. 

**How can you manage custom connectors after this change?**  
If you were leveraging this gap as a by-design method to manage the DLP policies, then you can switch to using environment level DLP policies to manage custom connectors. We recommend keeping tenant level policies in place and copy these settings to environment level policies, then add custom connector classification as an add-on setting using the same PowerShell cmdlet along with the environment name as a parameter.   

Only Environment Admins will now see the custom connector in the UI, even if it has successfully been added. If you have reviewed your custom connector has been added with the right ConnectorId, and all other connectors used in the app or flow are present in the business data only group of the policy and you are still experiencing issues, please raise a support ticket so a support engineer can take a look. As this is a DLP issue, and not an issue with the CoE Starter Kit we are unable to help here.

If you require assistance with the new DLP cmdlets, sample implementations are available here PowerApps-Samples/powershell/admin-center at master · microsoft/PowerApps-Samples (github.com), one of the sample implementations shows how to now add a custom connector to a policy, see: 

```
Add-CustomConnectorToPolicySample -EnvironmentName Default-02c201b0-db76-4a6a-b3e1-a69202b479e6 -PolicyName 7b914a18-ad8b-4f15-8da5-3155c77aa70a -ConnectorName BloopBlop -ConnectorId /providers/Microsoft.PowerApps/apis/BloopBlop -ConnectorType Microsoft.PowerApps/apis -GroupName hbi
