### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Connection Status) cannot delete flow/app permission error

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#685]
**Describe the bug**
Hi @JeneferM-MSFT 

I am having the same issue with another flow where my default environment does have permission because the environment is stored as a unique ID and it does not start with Default-unique id. I have attached the screenshot below. 

Error - You are not permitted to make flows in this 'Environment unique ID'. Please switch to the default environment, or to one of your own environment(s), where you have maker permissions.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.73
 - Flow  - CLEANUP - Admin | Sync Template v3 (Connection Status)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/104341429-ca0ce580-54c7-11eb-9b62-a3efe16c074a.png)

![image](https://user-images.githubusercontent.com/75992078/104341541-e90b7780-54c7-11eb-9254-f1f19e8befc3.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
The update that just shipped has what I believe to be a fix for this. 
Thanks for posting!
