### ISSUE TITLE
[QUERY]: Adapting the "Set Flow Permissions" app

### ISSUE THREAD

**Issue by WilliamJYoung** [microsoft/powerapps-tools#687]
I'm trying to adapt the "Set Flow Permissions" app to delete existing Flow Owners but can't quite work out the right "delete" options:
Here's what I have:
PowerAutomateforAdmins.EditAdminFlowOwnerRole(
    galFlowsMaker.Selected.'Flow Environment'.Name,
    galFlowsMaker.Selected.Flow,
    {
        delete: Table(
            {
                properties: {
                    principal: {
                        id: ThisItem.properties.principal.id, //ThisItem.properties.principal.id, //Office365Users.UserProfileV2(ThisItem.UserPrincipalName).id,
                        type: "User"
                        //email: ThisItem.UserPrincipalName,
                        //displayName: ThisItem.DisplayName,
                        //tenantId: "null"
                    }
                }
            }
        )
    }
);
...but it doesn't like the principal: id:
Can anyone point me in the right direction? I can't find much documentation on this option.
Sorry if this is the wrong place to post this query
Thanks

**Comment by manuelap-msft** [comment]
If you open the app in Edit mode, the removing permissions is already implemented in the FlowDetailsScreen
![image](https://user-images.githubusercontent.com/55705669/104488420-3a9a2c00-55c6-11eb-8961-14f405c1b80b.png)

The call is
```
PowerAutomateforAdmins.EditAdminFlowOwnerRole(
    galFlows.Selected.'Flow Environment'.Name,
    galFlows.Selected.Flow,
    {
        delete: Table(
            {
                id: ThisItem.id
            }
        )
    }
);
```

Let me know if that works for you!

**Comment by WilliamJYoung** [comment]
That's great. Thanks for the detailed guidance and speedy response Manuela
This is fabulous and great work!
