### ISSUE TITLE
Invalid Arguement error when importing COE components

### ISSUE THREAD

**Issue by craigballinger11** [microsoft/powerapps-tools#69]
The below temp fix has been supplied for the Core Components, However not for the Audit or Nurture Components. 

Some users have reported getting an Invalid argument error on importing the solution. This is due to a breaking change on the CDS side. A permanent fix is being worked on, in the meantime if you are getting this error please use the solution file in the TEMP FIX for Invalid Argument Error file instead

![COEError](https://user-images.githubusercontent.com/61011226/74434339-2996e700-4e5a-11ea-9042-052f3aadb818.PNG)

**Comment by firozozman** [comment]
I get this error on all the three components. Core component in the Temp Fix folder works.

**Comment by craigballinger11** [comment]
Seems the temp fix is alright for the Core, but there isn't any available for the other 2 components.

**Comment by manuelap-msft** [comment]
Yes, we are still working on a fix for the other two components.

**Comment by manuelap-msft** [comment]
We have just uploaded the new solutions for the other two components
https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/TEMP%20FIX%20for%20Invalid%20Argument%20Error
