### ISSUE TITLE
Understanding audit log flow [Child] | Admin Sync Logs

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#690]
Hello there,

I'm looking at the Audit Logs and was trying to understand something.  In the [Child] | Admin Sync Logs flow, the Filter Array step has this code:
@or(equals(item()?['Operation'], 'LaunchPowerApp'), equals(item()?['Operation'], 'DeletePowerApp'), equals(item()?['Operation'], 'DeleteFlow'), equals(item()?['Operation'], '**PowerAppPermissionEdited**'))

However, the Switch action right below it only handles LaunchPowerApp, DeletePowerApp and DeleteFlow.
![image](https://user-images.githubusercontent.com/50427725/104620654-17ae5d00-5644-11eb-85a0-a13b56cbe9dc.png)

Was there a reason why PowerAppPermissionEdited was not included as one of the cases?
Thank you.

**Comment by manuelap-msft** [comment]
Hello,

thanks for pointing this out! Our plan was to check for events for Power Apps permissions were edited and update the relevant tables (Power Users Shared With) to accurately reflect when permissions change. Unfortunately the Audit Log event didn't return all the information we needed so we removed the switch case but must have left this in the filter. This should not have an impact on how the Child Flow runs and works, but we will remove this extra condition with the next upgrade. 

Thanks for letting us know
Manuela
