### ISSUE TITLE
Issue with initial App and Flow sync routines

### ISSUE THREAD

**Issue by prvanbeek** [microsoft/powerapps-tools#691]
So I’m at https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows Step 5 and holding. 

Both the Admin|Sync Template v3 (Apps) and the Admin|Sync Template v3 (Flows)  flows failed on my default environment, where most of our current apps and Flows are implemented. Details below.

Admin | Sync Template v3 (Apps)

Error Details
Start time
Jan 12, 04:23 PM (14 h ago)
Duration
00:40:23
Error
Action 'Get_Power_App' failed

Error Details
admin_app With Id = abf6d6c8-15b8-494f-a4c1-7c096f52231b Does Not Exist
Flow to Send Reminder From Customer Voice Invite Entity Modified 12/07/20

{
  "error": {
    "code": "0x80040217",
    "message": "admin_app With Id = fed1ceb7-4101-40bf-99d5-5af5a5141a8a Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "c6b3f563-e454-eb11-bb23-000d3a539515",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "e9112f42-bbf4-4f5e-a200-1da5b922ef18",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_app With Id = fed1ceb7-4101-40bf-99d5-5af5a5141a8a Does Not Exist"
  }
}

Admin | Sync Template v3 (Flows)

Error Details

Start time
Jan 12, 04:24 PM (15 h ago)
Duration
01:04:10
Error
Action 'Get_Flow_from_CoE' failed

Error Details
admin_flow With Id = 221a5f75-1cf2-4b67-a58c-1c70aeacc605 Does Not Exist
Flow to Send Reminder From Customer Voice Invite Entity Modified 12/07/20

{
  "error": {
    "code": "0x80040217",
    "message": "admin_flow With Id = f5e8d7c9-4a7d-4591-89e8-f2010038986d Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "d2b4f563-e454-eb11-bb23-000d3a539515",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "4017ae3c-50a4-4b7b-977a-ed96672caa19",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_flow With Id = f5e8d7c9-4a7d-4591-89e8-f2010038986d Does Not Exist"
  }
}

Any help would be appreciated.

Thanks.

**Comment by JeneferM-MSFT** [comment]
Hi there. It would be helpful if you could show where these are failing in the flow with a picture, as that saves me from looking through the flows for specific calls. 

I believe you failed here, and at the equivalent spot in the flows one, is that correct? 

If so, this is an expected failure, when an app/flow is not yet in the CoE, and the failure is caught by the next call
![image](https://user-images.githubusercontent.com/62659043/104646627-ee0a2b80-566d-11eb-814e-07f3980c86ed.png)

Can you share a picture of your run so I can see if its not catching correctly, or what is happening?

**Comment by prvanbeek** [comment]
![image](https://user-images.githubusercontent.com/20642786/104648990-9b367100-5679-11eb-921b-9fe68279f72d.png)

**Comment by prvanbeek** [comment]
![image](https://user-images.githubusercontent.com/20642786/104649088-c28d3e00-5679-11eb-8bdb-f1947436933f.png)

**Comment by prvanbeek** [comment]
Just concerned as it showed that the Flow failed and the last item was the failed record which seemed to indicate that it dropped out of the Flows after the errors. Didn't want to proceed with faulty data if it didn't complete correctly.

**Comment by JeneferM-MSFT** [comment]
Yes your flow failed somewhere, but this isnt the spot. This failure is caught and handled, so it shouldnt be what is causing the flow to fail. 

Can you expand the next section "See if app already in the CoE" and then continue to dive in until you find another failure? 
If there isnt one, then surfacing the flow as failed would be a product bug, which doesnt seem very likely to me.

**Comment by prvanbeek** [comment]
Don't see any more red, but the last step Terminates the flow with a Failure. 

![image](https://user-images.githubusercontent.com/20642786/104650579-02edbb80-567c-11eb-85ac-d185c6e5dd88.png)

Output from previous step Create New Record - Sync Flow Errors

![image](https://user-images.githubusercontent.com/20642786/104650740-47795700-567c-11eb-8730-c6cb4caee646.png)
![image](https://user-images.githubusercontent.com/20642786/104650781-5cee8100-567c-11eb-8d6e-318e3ec69a4c.png)
![image](https://user-images.githubusercontent.com/20642786/104650833-6e378d80-567c-11eb-83c0-331542c3610c.png)

**Comment by prvanbeek** [comment]
Contents of body field: 
{
  "@odata.context": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/$metadata#admin_syncflowerrorses/$entity",
  "@odata.type": "#Microsoft.Dynamics.CRM.admin_syncflowerrors",
  "@odata.id": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)",
  "@odata.etag": "W/\"765122\"",
  "@odata.editLink": "admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)",
  "_owningbusinessunit_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "owningbusinessunit",
  "_owningbusinessunit_value@Microsoft.Dynamics.CRM.lookuplogicalname": "businessunit",
  "_owningbusinessunit_value@odata.type": "#Guid",
  "_owningbusinessunit_value": "992877cc-a152-eb11-bb24-000d3a9c3679",
  "statecode@OData.Community.Display.V1.FormattedValue": "Active",
  "statecode": 0,
  "statuscode@OData.Community.Display.V1.FormattedValue": "Active",
  "statuscode": 1,
  "admin_syncflowerrorsid@odata.type": "#Guid",
  "admin_syncflowerrorsid": "d239bb71-2a55-eb11-a812-000d3a55d542",
  "_createdby_value@OData.Community.Display.V1.FormattedValue": "Paul Van Beek",
  "_createdby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_createdby_value@odata.type": "#Guid",
  "_createdby_value": "12766fd2-a152-eb11-bb24-000d3a9c3679",
  "admin_name": "Admin | Sync Template v2 (Apps)",
  "createdon@OData.Community.Display.V1.FormattedValue": "1/12/2021 5:03 PM",
  "createdon@odata.type": "#DateTimeOffset",
  "createdon": "2021-01-12T23:03:56Z",
  "modifiedon@OData.Community.Display.V1.FormattedValue": "1/12/2021 5:03 PM",
  "modifiedon@odata.type": "#DateTimeOffset",
  "modifiedon": "2021-01-12T23:03:56Z",
  "admin_flowinstanceurl": "https://us.flow.microsoft.com/manage/environments/8e9129d8-9295-4864-97ab-13d2e9caad29/flows/c8cbbfce-03ee-d507-5e9d-76ad2b20129b/runs/08585911166698710225812092504CU78",
  "_owninguser_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_owninguser_value@odata.type": "#Guid",
  "_owninguser_value": "12766fd2-a152-eb11-bb24-000d3a9c3679",
  "_modifiedby_value@OData.Community.Display.V1.FormattedValue": "Paul Van Beek",
  "_modifiedby_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_modifiedby_value@odata.type": "#Guid",
  "_modifiedby_value": "12766fd2-a152-eb11-bb24-000d3a9c3679",
  "versionnumber@OData.Community.Display.V1.FormattedValue": "765,122",
  "versionnumber@odata.type": "#Int64",
  "versionnumber": 765122,
  "admin_environmentname": "Pella Corporation (default) (Upgrade)",
  "_ownerid_value@OData.Community.Display.V1.FormattedValue": "Paul Van Beek",
  "_ownerid_value@Microsoft.Dynamics.CRM.associatednavigationproperty": "ownerid",
  "_ownerid_value@Microsoft.Dynamics.CRM.lookuplogicalname": "systemuser",
  "_ownerid_value@odata.type": "#Guid",
  "_ownerid_value": "12766fd2-a152-eb11-bb24-000d3a9c3679",
  "owningbusinessunit@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/owningbusinessunit/$ref",
  "owningbusinessunit@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/owningbusinessunit",
  "ownerid@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/ownerid/$ref",
  "ownerid@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/ownerid",
  "createdby@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/createdby/$ref",
  "createdby@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/createdby",
  "createdonbehalfby@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/createdonbehalfby/$ref",
  "createdonbehalfby@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/createdonbehalfby",
  "modifiedby@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/modifiedby/$ref",
  "modifiedby@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/modifiedby",
  "modifiedonbehalfby@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/modifiedonbehalfby/$ref",
  "modifiedonbehalfby@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/modifiedonbehalfby",
  "owninguser@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/owninguser/$ref",
  "owninguser@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/owninguser",
  "owningteam@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/owningteam/$ref",
  "owningteam@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/owningteam",
  "admin_syncflowerrors_SyncErrors@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_SyncErrors/$ref",
  "admin_syncflowerrors_SyncErrors@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_SyncErrors",
  "admin_syncflowerrors_DuplicateMatchingRecord@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_DuplicateMatchingRecord/$ref",
  "admin_syncflowerrors_DuplicateMatchingRecord@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_DuplicateMatchingRecord",
  "admin_syncflowerrors_DuplicateBaseRecord@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_DuplicateBaseRecord/$ref",
  "admin_syncflowerrors_DuplicateBaseRecord@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_DuplicateBaseRecord",
  "admin_syncflowerrors_AsyncOperations@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_AsyncOperations/$ref",
  "admin_syncflowerrors_AsyncOperations@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_AsyncOperations",
  "admin_syncflowerrors_MailboxTrackingFolders@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_MailboxTrackingFolders/$ref",
  "admin_syncflowerrors_MailboxTrackingFolders@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_MailboxTrackingFolders",
  "admin_syncflowerrors_UserEntityInstanceDatas@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_UserEntityInstanceDatas/$ref",
  "admin_syncflowerrors_UserEntityInstanceDatas@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_UserEntityInstanceDatas",
  "admin_syncflowerrors_ProcessSession@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_ProcessSession/$ref",
  "admin_syncflowerrors_ProcessSession@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_ProcessSession",
  "admin_syncflowerrors_BulkDeleteFailures@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_BulkDeleteFailures/$ref",
  "admin_syncflowerrors_BulkDeleteFailures@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_BulkDeleteFailures",
  "admin_syncflowerrors_PrincipalObjectAttributeAccesses@odata.associationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_PrincipalObjectAttributeAccesses/$ref",
  "admin_syncflowerrors_PrincipalObjectAttributeAccesses@odata.navigationLink": "https://pellapowerplatformcoe.crm.dynamics.com/api/data/v9.1/admin_syncflowerrorses(d239bb71-2a55-eb11-a812-000d3a55d542)/admin_syncflowerrors_PrincipalObjectAttributeAccesses"
}

**Comment by JeneferM-MSFT** [comment]
Yes, that is the last catch, in order to report that the flow failed, so that one is also expected, and not a failure, you can see that both calls succeeded by their green check mark.
If you look at the configure run after for that call, you'll see that its set to run when the scope above fails
![image](https://user-images.githubusercontent.com/62659043/104741955-1b56e800-5707-11eb-956f-f73a8f139a9a.png)
![image](https://user-images.githubusercontent.com/62659043/104742003-2742aa00-5707-11eb-90a9-5411a8a5e524.png)
 
Can you please expand every action of the "See if app already in the CoE"? 
You must have another failure in there.

**Comment by JeneferM-MSFT** [comment]
I just went to make sure we didnt have a bug where caught failures show as flow failed, and we are ok. So there is definately another failure someone in the your for-each. Until you find it, I'm afraid I cant help deduce the problem

Here is what a new-app to the CoE looks like when no un-caught failures occur later on
![image](https://user-images.githubusercontent.com/62659043/104747363-a935d180-570d-11eb-9077-3f8296e04f9f.png)

**Comment by prvanbeek** [comment]
OK. Sorry for missing this, but there are three items in error in the apply to each loop. 
Output from each of the failed Get Power App calls below. 

Item 1
======================================
{
  "error": {
    "code": "0x80040217",
    "message": "admin_app With Id = abf6d6c8-15b8-494f-a4c1-7c096f52231b Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "c6b3f563-e454-eb11-bb23-000d3a539515",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "8861f719-9575-4ce6-b88e-2458c12c8f41",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_app With Id = abf6d6c8-15b8-494f-a4c1-7c096f52231b Does Not Exist"
  }
}
Next step to fail is Get App Role Assignments as Admin - Not found

Item 2
===============================
{
  "error": {
    "code": "0x80040217",
    "message": "admin_app With Id = c23b2ad3-6e79-3726-df1c-7061fba65df7 Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "c6b3f563-e454-eb11-bb23-000d3a539515",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "98262526-0a16-4d8e-8aec-24746471a485",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_app With Id = c23b2ad3-6e79-3726-df1c-7061fba65df7 Does Not Exist"
  }
}

Next step to fail is Parse Connection Ref JSON 2:
[
  {
    "message": "Required properties are missing from object: apiTier.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0]",
    "value": [
      "apiTier"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  }
]

Item 3
=============================================
{
  "error": {
    "code": "0x80040217",
    "message": "admin_app With Id = e4950cd2-37bf-4678-b1e0-3ad3a566ed76 Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "c6b3f563-e454-eb11-bb23-000d3a539515",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "4598784e-3466-4000-8ef2-c07d244b1f19",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_app With Id = e4950cd2-37bf-4678-b1e0-3ad3a566ed76 Does Not Exist"
  }
}

Next step to fail is Parse Connection Ref JSON 2:
[
  {
    "message": "Required properties are missing from object: apiTier.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0]",
    "value": [
      "apiTier"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  }
]

**Comment by JeneferM-MSFT** [comment]
can you please share these as a picture as I show above? You will need to add them in GitHub itself, not in email. 
I believe some of these are expected and I wont be able to detect that without pictures

**Comment by JeneferM-MSFT** [comment]
and then can you also please delete this string from the call shown and see if your flow runs successfully afterwards? 
![image](https://user-images.githubusercontent.com/62659043/104844391-35223780-588d-11eb-82bf-09f573f43c64.png)

**Comment by prvanbeek** [comment]
BTW - now I only find one failure instead of 3. Note also that this is in the Apps sync Flow. I had also received errors in the Flow sync. 
![image](https://user-images.githubusercontent.com/20642786/104919791-6fa6d580-595c-11eb-8ecc-3a9976b64b79.png)

**Comment by JeneferM-MSFT** [comment]
Hello. You need to expand that failure and see what is failing within that scope, the above picture does not give me information about what is failing.

**Comment by prvanbeek** [comment]
![Uploading image.png…]()

output of last failed step
{"statusCode":404,"headers":{"Strict-Transport-Security":"max-age=31536000; includeSubDomains","x-ms-request-id":"westus:33c68018-9313-49e3-84c6-abde83fe6330","x-ms-correlation-request-id":"33c68018-9313-49e3-84c6-abde83fe6330","x-ms-client-request-id":"4354e5b6-b9de-4991-a794-f4399e0e1f60","Timing-Allow-Origin":"*","x-ms-apihub-cached-response":"true","Cache-Control":"no-store, no-cache","Date":"Mon, 18 Jan 2021 16:02:11 GMT","Content-Length":"205","Content-Type":"application/json"},"body":{"error":{"code":"ApplicationNotFound","message":"The application 'abf6d6c8-15b8-494f-a4c1-7c096f52231b' could not be found in the tenant 'a66b0f6b-d953-4f09-95b7-5213bd230c18'."}}}

**Comment by JeneferM-MSFT** [comment]
Hello pictures don't come through if you respond in email, you need to add them in GitHub.

**Comment by prvanbeek** [comment]
I did put it in GitHub. It said it was uploading, but apparently not. 

![image](https://user-images.githubusercontent.com/20642786/105038090-81ec4680-5a24-11eb-9af8-f186eb5884b4.png)

**Comment by prvanbeek** [comment]
Subsequent scheduled runs of the Admin Sync Flows (both for Apps and Flows) have completed successfully. Does that mean we're OK or should I still rerun again?

Also have a question for you to ask outside this thread, if possible.

**Comment by JeneferM-MSFT** [comment]
great. We are good then and can close this issue. You are welcome to post another question as a new GitHub issue.

Thanks for using CoE
