### ISSUE TITLE
[BUG]: Custom Connector not showing in CoE

### ISSUE THREAD

**Issue by StephenCouch** [microsoft/powerapps-tools#697]
**Describe the bug**
The custom connector that is provided with the Core components, "Office 365 Management API", that is created for OAuth access to the audit logs does not show as a custom connector either through discovery by the CoE flows or within PowerShell. This prevents be from getting the underlying "ConnectorId" so that it can be added to a DLP. 

This ultimately prevents me from using a DLP on the environment that the CoE is installed in.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.73
 - App or Flow - Custom Connector "Office 365 Management API"

**To Reproduce**
1. Install the Core solution

**Expected behavior**
The custom connector provided should be enumerated with either PowerShell or with the Management Connector provided in Flow. 

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Connectors shipped in a solution currently don't enumerate with the PowerShell cmdlets That's a known product gap.

**Comment by StephenCouch** [comment]
Is there a way that you can include the underlying ConnectorId so that it can be added to a DLP? I can guess, but I would probably be wrong.. (/providers/Microsoft.PowerApps/apis/...).

**Comment by manuelap-msft** [comment]
If you go to flow.microsoft.com > Data > Custom Connectors > Edit the Custom Connector and look at the URL, that will give you the ConnectorID
