### ISSUE TITLE
BUG]: Issue connecting to the new COE via PowerBI- ERROR MESSAGE LOADING BLOCK FAILURE

### ISSUE THREAD

**Issue by margolee56** [microsoft/powerapps-tools#698]
**Describe the bug**
Eror: "Loading Block by failure with others"
![COE CONNECTION IKSSUE](https://user-images.githubusercontent.com/77509998/104771376-32fe9280-5740-11eb-9404-a4daaba8c90e.PNG)

See attach screenshot. 

I can be reach at 786 923632 or email margo_lee@mednax.com. 

thanks

**Comment by JeneferM-MSFT** [comment]
Can you please share 
1) What version of Core you are running
2) What version of (the appoximate date of download) the PBI?

**Comment by margolee56** [comment]
See attach dashboard I’m trying to connect to

See below screenshot with Power BI version

[cid:image001.png@01D6EB59.87095200]
Not sure what you means by what version of core I’m using.

**Comment by manuelap-msft** [comment]
Where it says "Loading blocked by failures in other queries" can you scroll all the way down to find the actual query that is failing?

If you navigate to make.powerapps.com > Solutions > next to the Center of Excellence - Core Components there will be a version number, can you let us know which one it is?

**Comment by margolee56** [comment]
Hi Support,
Please see the full error via connecting to the COE environment via Power BI. As to the solution being used I am validating that info and will send it to you as soon as possible.

Where it says "Loading blocked by failures in other queries" can you scroll all the way down to find the actual query that is failing? See the below error
OrgUrl
Loading blocked by failures with other queries.
Environment
Loading blocked by failures with other queries.
App
Loading blocked by failures with other queries.
Flow
Loading blocked by failures with other queries.
Maker
Loading blocked by failures with other queries.
App Connection Reference
Loading blocked by failures with other queries.
Flow Connection Reference
Loading blocked by failures with other queries.
Audit Log
Loading blocked by failures with other queries.
Connector
Loading blocked by failures with other queries.
Flow Action Details
Loading blocked by failures with other queries.
NonProdWords
Loading blocked by failures with other queries.
CoE Settings
Loading blocked by failures with other queries.
Virtual Agent
The key didn't match any rows in the table.
Virtual Agent Component
The key didn't match any rows in the table.
Virtual Agent Flows
The key didn't match any rows in the table.
Virtual Agent Makers
Loading blocked by failures with other queries.
RPA
Loading blocked by failures with other queries.
RPA Sessions
The key didn't match any rows in the table.
Environment Maker
Loading blocked by failures with other queries.
Date Last Refreshed
Loading blocked by failures with other queries.

**Comment by JeneferM-MSFT** [comment]
Hello it appears that you did not have the latest core bits that are required for the PBI to load. Please install the latest version of core (see [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)) and then use the latest version of the PBI.

**Comment by margolee56** [comment]
Please reopen this ticket

**Comment by JeneferM-MSFT** [comment]
Hello. If you still see this issue after update of Core and PBI, please let us know. But your error indicates that you do not have the PVA or RPA components, something that was put in core months ago. 
We just shipped the Feb release today so you should be good to go. 
Please be sure to remove unmanaged layers on update as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by margolee56** [comment]
Hi support,

I followed the steps and still having issues. Can you please give me a call or can you setup a remote session.

**Comment by JeneferM-MSFT** [comment]
To set expectations, this toolkit is not a supported product. It is a starter kit to get you going. So we are not support. We are here to help with issues that Power Platofrm customer see as budget allows.  And as such we are not able to offer calls or remote sessions for our github users. 

Can you please share here a screenshot showing the version of core you have installed? Please note that screenshots only work if you paste them in github, they will not show up if you paste in an email reply. 

Here is what I am looking for:
![image](https://user-images.githubusercontent.com/62659043/106504092-57b27400-647b-11eb-891d-cb7177fb6ff8.png)

**Comment by margolee56** [comment]
Hi Support,

Upon imported the most recent COE Toolkit the below error was received, the update toolkit was being imported at Power Apps<https://make.powerapps.com/environments/c5ed9853-e3fa-4692-a60e-f2574f7432d9/history> URL

Note: the following steps was performed via the URL noted "The import of solution: [solution name] failed" error occurs in Dynamics 365 (microsoft.com)<https://support.microsoft.com/en-us/topic/-the-import-of-solution-solution-name-failed-error-occurs-in-dynamics-365-011afe49-3aa1-db40-566b-e4f27d1e7375> for the
Error code 80041A06<http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=80041A06&de=online> failure.


Information
Details
Name
CenterofExcellenceCoreComponents
Start time
3/2/2021, 11:32 AM
End time
3/2/2021, 11:34 AM
Version
1.89
Publisher
powerplatformadmin
Operation
Import
Suboperation
None
Result
Failure
More details
Error code
80041A06<http://go.microsoft.com/fwlink/?LinkID=398563&client=Solutions&Error=80041A06&de=online>
Exception message
Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.
Total operation time
1 m 41 sec
Patch
No
Managed
Yes
Overwrite customizations
No
Activity id
697badc8-0107-425b-a7dd-280a732b4623

Please let me know if you have any further questions.

Thanks

**Comment by JeneferM-MSFT** [comment]
Again, we are not support, this is not a supported toolkit, and we cannot do calls with Github customers. 

In the future please share screenshots of issues, you need to be logged in to Github for them to work they will not work by replying in email. 

But I can see from your text that what you are experiencing is a known old issue, so I can help you here. 

You need to install the itermediate solution found here #491 and #515 depending on your current version of Core.

And then you can update to the latest version. Be sure to follow the instructions in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) when doing so.

**Comment by margolee56** [comment]
Adding new IM+ @Aakanksha Sinha (Accenture Solutions Private Li)<mailto:v-aakasi@microsoft.com> for visibility.


From: Margo Lee <Margo_Lee@mednax.com>
Sent: Tuesday, March 2, 2021 10:19 PM
To: microsoft/powerapps-tools <reply@reply.github.com>; microsoft/powerapps-tools <powerapps-tools@noreply.github.com>
Cc: Author <author@noreply.github.com>; Sai Abhishek Balla (MINDTREE LIMITED) <v-saball@microsoft.com>; Chaitanya R (Accenture Solutions Private Li) <v-chr1@microsoft.com>; Kiran Reddy <kiranb@microsoft.com>; Veera Venkata Satya Narayana Murty Peetha (MINDTREE LIMITED) <v-vepeet@microsoft.com>; Aakanksha Sinha (Accenture Solutions Private Li) <v-aakasi@microsoft.com>
Subject: [EXTERNAL] RE: [microsoft/powerapps-tools] BUG]: Issue connecting to the new COE via PowerBI- ERROR MESSAGE LOADING BLOCK FAILURE (#698)

Hi Support,

Upon imported the most recent COE Toolkit the below error was received, the update toolkit was being imported at Power Apps<https://make.powerapps.com/environments/c5ed9853-e3fa-4692-a60e-f2574f7432d9/history> URL

Note: the following steps was performed via the URL noted "The import of solution: [solution name] failed" error occurs in Dynamics 365 (microsoft.com)<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Ftopic%2F-the-import-of-solution-solution-name-failed-error-occurs-in-dynamics-365-011afe49-3aa1-db40-566b-e4f27d1e7375&data=04%7C01%7Cv-chr1%40microsoft.com%7Cb55b66916af1427ad09d08d8dd9b0e5e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637503005807285717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=1gKNdJO%2BBnoDMcHWZKxgiTD0m%2B0t0KOk6w0AgHDvrZQ%3D&reserved=0> for the
Error code 80041A06<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkID%3D398563%26client%3DSolutions%26Error%3D80041A06%26de%3Donline&data=04%7C01%7Cv-chr1%40microsoft.com%7Cb55b66916af1427ad09d08d8dd9b0e5e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637503005807285717%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=oSvMHOUvNX9SooEqpXw5kET2oooG8vbe5UtTRiJuGRw%3D&reserved=0> failure.


Information
Details
Name
CenterofExcellenceCoreComponents
Start time
3/2/2021, 11:32 AM
End time
3/2/2021, 11:34 AM
Version
1.89
Publisher
powerplatformadmin
Operation
Import
Suboperation
None
Result
Failure
More details
Error code
80041A06<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgo.microsoft.com%2Ffwlink%2F%3FLinkID%3D398563%26client%3DSolutions%26Error%3D80041A06%26de%3Donline&data=04%7C01%7Cv-chr1%40microsoft.com%7Cb55b66916af1427ad09d08d8dd9b0e5e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637503005807295673%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000&sdata=wYCG3axGeVqyeKCCYk4HY1UcCY5u57KSNEnn0wYHNGY%3D&reserved=0>
Exception message
Attribute admin_rpamodifiedon is a String, but a DateTime type was specified.
Total operation time
1 m 41 sec
Patch
No
Managed
Yes
Overwrite customizations
No
Activity id
697badc8-0107-425b-a7dd-280a732b4623

Please let me know if you have any further questions.

Thanks
