### ISSUE TITLE
Last Launched Date Not Populating

### ISSUE THREAD

**Issue by ssquiresusps** [microsoft/powerapps-tools#699]
**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit Logs
 - Version:  1.0.0.20
[Last Lanched.docx](https://github.com/microsoft/powerapps-tools/files/5822889/Last.Lanched.docx)

 - Flow:  [Child Admin | Sync Logs

**To Reproduce**
Please see attachment

**Expected behavior**
Last Launched Date Populated

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Know that we cannot go back in time and populate this field for all apps, it is something that fills over time. And that this only works for type canvas.
Please go manually launch several canvas apps yourself, and then wait for the flow to run for that timeframe. 
Look up those apps specifically in the table to see if it is filled

**Comment by JeneferM-MSFT** [comment]
Hello, I see we have been through this together before. Duping to #568 and please let me know if something has changed. You likely need to either create a support ticket or hire a partner for assistance.

**Comment by ssquiresusps** [comment]
[Last Lanched.docx](https://github.com/microsoft/powerapps-tools/files/5852108/Last.Lanched.docx)
As shown in the attachment in the excel spreadsheet the Office 365 audit log events for canvas apps is being populated  in the O365 event logs.   Also shown in the attachment the ability of the power automate job to read the O365 log events -- however no  launched events are making it into the dataverse audit log table at all despite successful daily runs.
