### ISSUE TITLE
Cannot make Audit log custom connector working. Using oauth2.0 security, keep throwing access denied. have GA rights. Is the swagger file available with kit is not compatible for oauth? 

### ISSUE THREAD

**Issue by P2020-c** [microsoft/powerapps-tools#70]

**Comment by manuelap-msft** [comment]
It works with basic authentication only at the moment. Does your account have MFA enabled?

**Comment by P2020-c** [comment]
Yes, MFA enabled. What other option do we have to access Audit log?

**Comment by manuelap-msft** [comment]
To use an account with MFA, you need to create an app registration so that you can pass in a Bearer token instead of using Basic Auth. It's a similar solution to the one posted in this blog https://flow.microsoft.com/en-us/blog/automate-flow-governance/
We are working on updating the documentation with those steps.

**Comment by P2020-c** [comment]
Tried that but keep getting 401. I have GA rights. Assigned APi permission same mentioned in article shared above. Passing this `https://manage.office.com/ActivityReports.Read` as resource url. is it correct?

**Comment by P2020-c** [comment]
> To use an account with MFA, you need to create an app registration so that you can pass in a Bearer token instead of using Basic Auth. It's a similar solution to the one posted in this blog https://flow.microsoft.com/en-us/blog/automate-flow-governance/
> We are working on updating the documentation with those steps.



> To use an account with MFA, you need to create an app registration so that you can pass in a Bearer token instead of using Basic Auth. It's a similar solution to the one posted in this blog https://flow.microsoft.com/en-us/blog/automate-flow-governance/
> We are working on updating the documentation with those steps.

We are trying with Oauth only. With basic it works, tried in Test. But while using oauth, keep getting 401. I have GA rights. Assigned APi permission (O365 management api)same mentioned in article shared above. But then keep getting error with below
The audience claim value is invalid for current resource. Audience claim is 'https://manage.office.com',request url is 'https://outlook.office365.com/psws/service.svc/UnifiedAuditLog
