### ISSUE TITLE
[BUG]: [Question] How to access DLP.All content from the Audit log connector?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#702]
Hello Team,

This is not a bug, rather a question regarding the Child Audit log flow that accessing O365 Management Activity API. Currently it only stores "PowerAppsAppLaunch" operation, while we require to log other activities as well, especially related to DLP.All content which is already mentioned in the Audit log action as follows:

![image](https://user-images.githubusercontent.com/13658386/104920544-eeecd700-5965-11eb-941d-4908fa0395f2.png)

However, while configuring this action, it throws an error: - The permission set (ActivityFeed.Read ServiceHealth.Read) sent in the request does not include the expected permission.

I assume, it require subscription to start, however does it mean that each content type action might require separate connector? Could you please guide on possibilities of accessing other O365 Audit log activities available in the connector?

Thank you for your time in advance!

Best Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid this is outside of our scope. You will need to work with a partner or your Microsoft Technical support for assistance. 

Appreciate you using CoE
