### ISSUE TITLE
Connectors by flow and app catalog in SP list 

### ISSUE THREAD

**Issue by MarinaHadzi** [microsoft/powerapps-tools#703]
**BUG 1**
I don't see the part for Connections by flow and I can not filter flow connections by flow or by maker in any dashboard connected with info about flow connectors
![image](https://user-images.githubusercontent.com/71693895/104921583-d26a9200-5999-11eb-9a55-b14f1ca435b2.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core solution, dashboard
 - Version  1.73
-  dashboard

**BUG 2**
App catalog canvas app in Nurture component doesn't have SharePoint connector, where do you store app templates? I followed the set up information form Microsoft and its not working:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/modify-components#set-up-the-template-catalog-and-upload-components

**Comment by JeneferM-MSFT** [comment]
Issue 1, we have removed this screen due to technical limitations. 
Issue 2,  App catalog stores in Dataverse not SP. The link you are referencing is for template catelog. 

Hope the above makes sense, and thanks for using CoE

**Comment by MarinaHadzi** [comment]
Hi @JeneferM-MSFT so there is an issue in entire core solution and in power bi dashboards regarding the flow connectors or?

**Comment by JeneferM-MSFT** [comment]
Hello, no Power Bi has some issues around relationships such that we couldn't correctly show the pages you show above and so we cut them.

**Comment by MarinaHadzi** [comment]
Hi @JeneferM-MSFT,
Yes but there is still some things on the dashboards that doesn't show correct data, for example, when it comes to app connectors there is this view and that's fine
![image](https://user-images.githubusercontent.com/71693895/104951949-d4494b00-59c3-11eb-827f-05fd6247ec67.png)

but for Cloud flow maker insights this is not available and it can be filtered by the maker and connector
![image](https://user-images.githubusercontent.com/71693895/104952040-065aad00-59c4-11eb-87a6-5b297b1a4b16.png)

Can I or you fix this in any way?

**Comment by JeneferM-MSFT** [comment]
We missed that one, thank you. Re-opening for the fix to this page. The fix will likely end up just being removal though if we cannot get around the above mentioned relationship problem

**Comment by MarinaHadzi** [comment]
Can you please try to fix this because there is a lot of things you removed from the starter kit (dlp editor, customizer, related flows, flow when environment is created) so it's not correct to see all this information for apps but no information for flows. Or please instruct us in any way how can we fix this?

**Comment by JeneferM-MSFT** [comment]
If there were a way that we knew to fix it, we would. If you are able to figure something out, please let us know and we can apply generally. The problem is in the way PBI does relationships.

As a reminder, the CoE Starter Toolkit is an unsupported set of starter apps/flows/reports/etc. It is not intended to be the end all solution for governance, but to get you started.

**Comment by JeneferM-MSFT** [comment]
We missed removing this report this time, but please do know (per your comment above) that a DLP editor has been re-added now that we have overcome the product change that caused us to remove it. 
You need to install to the latest version of Core to see it. 
See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by MarinaHadzi** [comment]
I just saw it moment ago, great gor DLP.  thank you
