### ISSUE TITLE
[BUG]: Developer Compliance Centre App Description Update 

### ISSUE THREAD

**Issue by binaryjam** [microsoft/powerapps-tools#704]
**Describe the bug**
In the Dev Compliance App details screen, if you have no description on the app then it informs you to

"To Add Description: Go to the App Settings > Edit the App > Settings > Add Description > Save and Publish. Then return here and  click the refresh button below"

In the version I have, there is no Refresh button as the text says, 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Governance Components
 - Version 1.21
 - Developer Compliance Center

**To Reproduce**
1. Go to App
2. Click on an app that has no description
3. Scroll down to Look at the hint text for the description
4. There is not refresh button.

**Expected behavior**
Not sure what you expected here,  but as the user ccould change this description and its not currently synced, the refresh button
should exists and it should fetch the real description from the App , update the CDS with it and refresh the control data

**Comment by JeneferM-MSFT** [comment]
Thank you for using CoE and for posting. I just deleted the reference to a refresh icon, the Compliance Center app will need to be restarted in order to fetch new data.

**Comment by binaryjam** [comment]
Hi,

At least in version 1.21,   this doesn't solve the problem, When the user goes to their app, edits the description, it is only changed in the App,   the Compliance Center app gets its description from the CDS description field,  which is only updated daily.

So Refreshing the App will not drag the new data from the app and update the CDS field.   A button could do that.

If the compliance centre is not getting the description directly from the app, then it needs to tell the user to wait till the following day to see the changes.

**Comment by JeneferM-MSFT** [comment]
Hello. The new version of the Audit Components has just released. 
Please be sure to remove any unmanaged layers before updating as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

And thanks for helping make CoE great!

**Comment by binaryjam** [comment]
How did you address this bug in the end ?  I couldnt see it in the release note, but there was a lot ?

Did you go with your original suggestion of changing just the text ? Or did you take note of my follow up comment regarding the 24hr latency of the data and refreshing the page will not change the content ?

Thanks

**Comment by JeneferM-MSFT** [comment]
I just changed the text. We do not have bandwidth for a larger change at this time. 
Thank you
