### ISSUE TITLE
[BUG]: broken icon links in e-mails from Nurture Components solution

### ISSUE THREAD

**Issue by poppynka** [microsoft/powerapps-tools#707]
**Describe the bug**
E-mail templates sent from Nurture Components solution contain broken link to Power Automate logo in 
 the top ribbon (http://powerplatformconference.com/wp-content/uploads/2019/05/FlowIcon256x256.png). 

Our client asked us to fix this somehow, but then it would be potentially overwritten by the upgrade and we would need to handle it again and again. That's why we're reporting this. We know it's just a cosmetic issue, but it doesn't make a good impression.

Talking about the logos, the Power Apps one is older version (https://higherlogicdownload.s3.amazonaws.com/PBIUSERGROUP/0dd17701-ca4a-49ad-9e12-8a3458d663ba/UploadedImages/World_Tour/2019/PowerApps.png), but at least it's not displayed like the missing one:
![image](https://user-images.githubusercontent.com/6829792/105047468-a8cd6b80-5a6a-11eb-87d9-94bdef7458d8.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Nurture
 - Version 1.23
 - App or Flow Training In A Day | Reminder 3 days prior event
                        Training In A Day | Registration Confirmation
                        Training In A Day | Feedback Reminder
                        Admin | Welcome Email

**To Reproduce**
I believe not needed, it's sufficient to open the flow, find the Outlook action and check the image links.

**Expected behavior**
Ribbon either containing no Power Apps/Automate logo, or correctly linked.

**Comment by JeneferM-MSFT** [comment]
Hello. Did you fill in the logo field during setup? [configure the coe settings table](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#configure-the-coe-settings-table)

**Comment by JeneferM-MSFT** [comment]
Sorry from above perhaps I've mis-read. Is your concern about the PowerApps logo or the missing customer logo? 
If missing customer logo, then please be sure you've set up the logo field.

**Comment by poppynka** [comment]
Hi :) no, I am not talking about the customer logo, but the power apps and power automate logos in nurturing e-mails. Marked at the screenshot:
![image](https://user-images.githubusercontent.com/6829792/105071250-9ceea300-5a84-11eb-8b63-7096b26e9246.png)

**Comment by JeneferM-MSFT** [comment]
Got it, thanks so much!

**Comment by poppynka** [comment]
Our customer also wanted us to change the ribbon color from purple to dark blue (still talking about the screenshot above)
- I have done that in CSS used in the environment variable used for e-mail headers. But then the purple powerapps logo looked really... not good (purple logo on a dark blue ribbon) 😃 so I this way I learned that the logo actually is purple, not grayscale transparent 😄 but that's just FYI, that such requests also happen

**Comment by JeneferM-MSFT** [comment]
We have removed these from the email locally and the fix will ship with our next monthly update. 
Will hold to let you know when that occurs. 
Thanks for using CoE!

**Comment by poppynka** [comment]
thank you! 👍

**Comment by JeneferM-MSFT** [comment]
Hello. This change in the release today. 

Please be sure to remove any unmanaged layers before updating as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

And thanks for helping make CoE great!
