### ISSUE TITLE
[BUG]: Data missing from the BI dashboard

### ISSUE THREAD

**Issue by tsegato** [microsoft/powerapps-tools#709]
I have installed CenterofExcellenceCoreComponents_1_78_managed.zip
I get most of the content in the BI dashboard but not data like last launched, unique users etc:

![image](https://user-images.githubusercontent.com/43033640/105157013-d66af100-5b0c-11eb-9972-a5901793bcc8.png)

![image](https://user-images.githubusercontent.com/43033640/105157144-fa2e3700-5b0c-11eb-9cf5-f118c5e025f1.png)

Any suggestions what to do?

**Comment by tsegato** [comment]
I can see the auditlog table is empty.

**Comment by manuelap-msft** [comment]
You will have to install the Audit Log solution, to capture Audit Log events and populate last launched information and unique users/sessions

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
