### ISSUE TITLE
Environment Type for CoE

### ISSUE THREAD

**Issue by gjones926** [microsoft/powerapps-tools#71]
Good afternoon,

I am attempting to setup the CoE starter kit and want to make sure I am doing this correctly. For Type, under New Environment, the screenshot in the Setup Instructions has Sandbox selected. Nothing explicitly says this is the environment type that should be selected. Could someone please tell me which environment is best for this setup?

Thank you.

**Comment by manuelap-msft** [comment]
A Production environment would be best for the CoE Setup! We'll make sure to update that in the documentation as well.
