### ISSUE TITLE
[BUG]: Power Platform dashboard is empty

### ISSUE THREAD

**Issue by yingying96** [microsoft/powerapps-tools#711]
**Describe the bug**
Power Platform dashboard is empty

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 1_28
 - App or Flow: Power Platform dashboard

**To Reproduce**
1. Go to Power Apps
2. Click on Power Platform Admin view
3. It will direct you to power platform dashboard but it is empty

**Expected behavior**
The expected behavior would be loaded data.

**Screenshots**
![error](https://user-images.githubusercontent.com/19566726/105269094-41303100-5bce-11eb-87a9-23f9cfb002e4.png)

**Comment by JeneferM-MSFT** [comment]
Hello, you are on a very old install of the CoE, you will need to update. And you will also need to be sure that you run the sync flows in order to see data. 

Please see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for how to upgrade.
