### ISSUE TITLE
[BUG]: Archival Record without App Owner Name if app/flow is orphelan

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#714]
**Describe the bug**
In the Archival process when an application or a flow is reassigned to Admin, the archival process creates an archival record with a blank App Owner Name. Email is well the one of admin but not the name. This information is then required in the 'Admin | Check Approvals'. So it failed.
This issue happens when the 'ProductionEnvironment' variable is set to No or if an app/flow is orphelan.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Governance
 - Version - 1.28
 - Flow - Admin | App Archive and Clean Up - Start Approval / Admin | Flow Archive and Clean Up - Start Approval / Admin | Check Approvals

**To Reproduce**

1. Set the ProductionEnviroment to 'No'
2. Run the 'Admin | App Archive and Clean Up - Start Approval'or 'Admin | Flow Archive and Clean Up - Start Approval' flows
3. Run the 'Admin | Check Approvals'
4. See error in 'Parse JSON - Archive Approval Item' step of 'Admin | Check Approvals'

**Expected behavior**
When an app/flow is reassigned to admin in archival process, the display name should be the admin name, not blank.

**Screenshots**
Way uses in Admin | App Archive and Clean Up - Start Approval' flow when ProductionEnviroment is set to 'No'. This highlight that 'Recheck Orphan Status' is ignored in this case. So the field App Owner Name is empty when Archive Approvals record is created.
![image](https://user-images.githubusercontent.com/22662809/105372349-cbe05280-5c05-11eb-90be-598bafb3079d.png)

Notice that in case, the app/flow is orphelin another way is used. As the 'Recheck Orphan Status' failed (normal behavior as the owner as left the compagny), the Display name is also empty and lead to the same failure at the end.

In the Admin | Check Approvals, we see that App Owner Name is required to parse the result. Without this information, the 'Parse JSON - Archive Approval Item' step failed.
![image](https://user-images.githubusercontent.com/22662809/105371436-e8c85600-5c04-11eb-8721-8f7b99036b55.png)

**Comment by JeneferM-MSFT** [comment]
Thank you, this is a great catch, and very helpful debugging. I have fixed this, and your other issue locally.

**Comment by JeneferM-MSFT** [comment]
Hello. This fix for this was released today. 
Please be sure to remove any unmanaged layers before updating as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

And thanks for helping make CoE great!
