### ISSUE TITLE
[BUG]: Approval creation fails in Archival Process when Admin Email is a distribution list.

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#715]
**Describe the bug**
When the Admin email environment variable is set with a distribution list or an O365 group, creation of approval in archival process failed with the following error:

{
  "error": {
    "code": "InvalidApprovalCreateRequestAssignedToNoValidUsers",
    "message": "Required field 'assignedTo' contained no valid users in the organization"
  }
}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Governance
 - Version - 1.28
- Flows Admin | App Archive and Clean Up - Start Approval / Admin | Flow Archive and Clean Up - Start Approval

**Expected behavior**

**Screenshots**
In this screenshot, varAssignee varible is set with the value of Admin email environment variable. So the approval creation failed.
![image](https://user-images.githubusercontent.com/22662809/105373279-d0f1d180-5c06-11eb-9a32-d97cbc49a5ab.png)
![image](https://user-images.githubusercontent.com/22662809/105373577-1d3d1180-5c07-11eb-8d00-881eedcde41a.png)

**Additional context**
In the documentation, it is well mentionned that Admin Email can be a distribution list.

![image](https://user-images.githubusercontent.com/22662809/105373741-478ecf00-5c07-11eb-8029-01043de5ca0f.png)

**Comment by JeneferM-MSFT** [comment]
Thank you, this is a great catch, and very helpful debugging. I have fixed this, and your other issue locally. 

Because we cannot change product code to force Approvals to accept a distribution list, we have instead added a new, optional, environmental variable called **_Approval Admin_**. You will need to put in that variable the name of an individual who will be able to be charged with the approvals for this flow.  

Will hold this issue until we ship

**Comment by lcimon** [comment]
Sounds great. Waiting the next release so.

**Comment by JeneferM-MSFT** [comment]
Hello. The new version of the Audit Components has just released. 
Please be sure to remove any unmanaged layers before updating as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

You will see a new environment variable offered to you **_Approval Admin_**. 
You will need to put the email of a person who will be charged with the approvals in the event that an app/flow is orphaned. 
Note that if you leave this blank it will fall back to the admin email, a distribution list in your case.  
![image](https://user-images.githubusercontent.com/62659043/106499405-672ebe80-6475-11eb-9215-1641876adcc3.png)


And thanks for helping make CoE great!
