### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by NGseb** [microsoft/powerapps-tools#719]
**Describe the bug**
I have a bug with the flows in the CoE. 
If i compare the number of flows retrieved with Powershell using Get-AdminFlow, i retrieve two times more flows than the one that are in the one that are in "admin_flows" table of the dataverse

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [1.70.6]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**
1. Go to https://make.powerapps.com/environments/{guid}/entities/{GUID}/admin_Flow#data
2. Click on '**export data**' button
3. open with editor 

**Expected behavior**
It should be the same number of flows

**Comment by JeneferM-MSFT** [comment]
Hello. We did a major update recently to a v3 version of the sync flows. This relies on the new and more reliable CDS Native connector as we have seen writes fail in the past with the old CDS connector.
 
I suggest you update (see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)), turn the env var **_Full Inventory_** to true, run the sync flows, and then see where you are at. 
If the numbers are still different, please call Get Flows as Admin in a separate test flow and see if it returns the correct number.
