### ISSUE TITLE
Facing Issue (token is invalid )while using Auditlog custom connector with MFA enabled in tenant.

### ISSUE THREAD

**Issue by P2020-c** [microsoft/powerapps-tools#72]
To use auditlog custom conentor with an account with MFa. Registerd an app for token & using oauth in security instead of basic but keep getting 401. Having GA rights. Assigned API permission (O365 management api)same mentioned here https://flow.microsoft.com/en-us/blog/automate-flow-governance/.   Error is The audience claim value is invalid for current resource. Audience claim is 'https://manage.office.com',request url is 'https://outlook.office365.com/psws/service.svc/UnifiedAuditLog

**Comment by P2020-c** [comment]
Any update on this issue?

**Comment by gregdegruy** [comment]
@P2020-c can you edit this issue and provide and short title and move this text to the body of the issue?

> To use auditlog custom conentor with an account with MFa. Registerd an app for token & using oauth in security instead of basic but keep getting 401. Having GA rights. Assigned API permission (O365 management api)same mentioned here https://flow.microsoft.com/en-us/blog/automate-flow-governance/. Error is The audience claim value is invalid for current resource. Audience claim is 'https://manage.office.com',request url is 'https://outlook.office365.com/psws/service.svc/UnifiedAuditLog

**Comment by P2020-c** [comment]
@gregdegruy : is that ok now?

**Comment by ltwlf** [comment]
I have the same issue. I guess using this service is not optimal (https://outlook.office365.com/psws/service.svc/UnifiedAuditLog). It seems to be an internal service for an older PowerShell command and seems it doesn't support OAuth. Basic Auth with GA is an absolut no go for production environments!
Any help would be appreciated.
Best wishes!
Christian

**Comment by manuelap-msft** [comment]
Hello,

we have just published a solution and setup instructions to sync the Audit Log with MFA enabled
https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/Audit%20Log%20(MFA)

Best Regards,
Manuela

**Comment by ltwlf** [comment]
Thanks Manuela! 
I'll give it a try. The approach looks great.

**Comment by manuelap-msft** [comment]
Please let me know if you find any issues with it, it's a v1!

**Comment by ltwlf** [comment]
Hey Manuela,

it works - good job! :)

Suggestion for an security improvement. For the current CoE setup you only need the following permissions App Permissions from Management API:
ActivityFeed.Read (delegated)
![image](https://user-images.githubusercontent.com/965766/77200883-c0a32e80-6aeb-11ea-8146-29d67237654d.png)

Best wishes 
Christian

**Comment by manuelap-msft** [comment]
Awesome, thanks for confirming!

Good point, I will make the update! Also, we are hopeful to have the CoE documentation in a dedicated area under docs.microsoft.com by end of next week which should allow you to contribute and make pull requests from there then. Will keep you updated!
