### ISSUE TITLE
[BUG]:  Your flow could not turn on: [Child] Admin | Sync Logs. 

### ISSUE THREAD

**Issue by yingying96** [microsoft/powerapps-tools#721]
**Describe the bug**
Tried to turn on sync logs but it isn't working for me.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit logs
 - Version: 1.3.4
 - App or Flow: [Child] Admin | Sync Logs. 

**To Reproduce**
Click on turn on

Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow 'ac851b66-8e0b-8e8f-f137-bd1c116e4ca7' cannot be activated due to admin API policies."}}".

Before turning on, i have already completed the pre-req of updating the azure ad app and getting 200 response for the custom connector.

**Expected behavior**
Flow is turned on

**Comment by manuelap-msft** [comment]
Hello,

the reason your flow can not be turned on is because DLP policies in the environment are preventing it from being used. Learn more about DLP policies https://docs.microsoft.com/en-us/power-platform/admin/wp-data-loss-prevention and find the DLP requirements of the CoE Starter Kit  here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

**Comment by yingying96** [comment]
Thanks! Looks like that's the case. If i have >> Your flow could not turn on: CLEANUP - Admin | Sync Template v3 (Check Deleted). Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"MissingAdequateQuotaPolicy","message":"The user '7560bba7-6599-476d-b55f-a80e16fcabfa' does not have a service plan adequate for the non-Standard connection. https://go.microsoft.com/fwlink/?linkid=2123710"}}". 

Does that mean that it's a licensing issue? We have E3 license. But not too sure if that is sufficient. I tried it on my test tenant and it works. But implementation in production will have the error message above.

**Comment by manuelap-msft** [comment]
Yes, the CoE Starter Kit flows use premium connectors such as Dataverse and HTTP, thus a premium license is required to run them - this can be a Power Apps per user, or Power Automate per user or Power Automate per flow license. Often the best license fit depends on what you have in your organisation already.
