### ISSUE TITLE
[BUG]: Core Components fails to import.

### ISSUE THREAD

**Issue by madshaun1984** [microsoft/powerapps-tools#722]
**Describe the bug**
Importing core components fails with error.

`"Connector import: FAILURE: The API call failed with http status code 'InternalServerError' and response content '{"error":{"code":"InternalServerError","message":"Encountered internal server error. [tracking ID redacted]"}}'" `
 
Error Status Code: 80048020.

Update: The detailed log pinpoints the error down to an unhandled exception being thrown by 
`Microsoft.Crm.ObjectModel.PowerAppsDataProvider.&lt;&gt;c__DisplayClass64_0`2.&lt;&lt;CallPowerAppsEndpoint&gt;b__0&gt;d.MoveNext()`

I am not being presented with the option to set the "Power Automate environment variable" as detailed in the setup guide.  

**Component (please tell us which flow or app you are experiencing issues with):**
 - CoE Starter Kit Core Components
 - Version 1.78

**To Reproduce**
1: Follow setup guide to install Core Components.
2: Wait for the import task to complete.
3: Note the task fails with the error described.

**Expected behavior**
The import succeeds.

**Comment by manuelap-msft** [comment]
Hello,

it looks like you are experiencing an issue with the solution import itself, rather than the CoE Starter Kit. I'm afraid that is beyond the scope of what we can help with here - I would suggest trying again, and if it still fails raising a support ticket.


Thank you for using the CoE!

**Comment by madshaun1984** [comment]
After a hell of a lot of pain, it turns out was missing a "premium" feature enabled power apps plan. Adding a plan 2 trial + logging out and back in solved it. 

The solution import error messaging could of made this much easier to identify, but that's an issue for MS. Hopefully if anyone else spots this error, this post will make it easier to identify & resolve.

The Power Automate environment variable not being presented during import was solved by extracting the core components and deleting the string entered for the variables default value in the "customizations.xml" file.

**Comment by manuelap-msft** [comment]
Thanks for the update! The requirement for a Premium plan is mentioned in our pre-requisites here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

We do not recommend modifying the customizations.xml, it is not a supported technique and can lead to many issues further down the line. Environment Variables can be modified after import - see https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

**Comment by noorsyyed** [comment]
> After a hell of a lot of pain, it turns out my admin account was missing a "premium" feature enabled power apps plan. Adding a plan 2 trial + logging out and back in solved it.
> 
> The solution import error messaging could of made this much easier to identify, but that's an issue for MS. Hopefully if anyone else spots this error, this post will make it easier to identify & resolve.
> 
> The Power Automate environment variable not being presented during import was solved by extracting the core components and deleting the string entered for the variables default value in the "customizations.xml" file.

thanks @madshaun1984 , after burning out for 4 hours I saw this, I'm grateful you put it out here.
