### ISSUE TITLE
[BUG]: Duplicate key error in [Child] Admin | Sync Logs

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#723]
**Describe the bug**
[Child] Admin | Sync Logs fails with this following error: "message": "A record with matching key values already exists.".
Main Admin | Sync Logs is configured as following:
![image](https://user-images.githubusercontent.com/22662809/105719893-18d46980-5f23-11eb-8f18-5eb03f8ef408.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Audit Logs
 - Version - 1.3.4
 - Flow - [Child] Admin | Sync Logs

**To Reproduce**

**Expected behavior**
Failure let's feel that something doesn't works well. In this case, I guess it just matter of Audit Logs records already created as the flow is configured to get the 2 last days of Audit.
In case of duplication, record could be skipped or update, or the error can be just managed to avoid that the flow fails.

**Screenshots**
![image](https://user-images.githubusercontent.com/22662809/105719738-ef1b4280-5f22-11eb-8b1e-ef1a52534f4a.png)

**Comment by JeneferM-MSFT** [comment]
Hello we saw this the other day with another customer. It appears that the time overlap can sometimes bring back records already inserted, and upsert is no longer supported. 

Here is a picture of the fix we sent to them to test, if you are familiar enough with flow to update things like "Configure Run After", can you please try? Its a pretty simple fix. 

![image](https://user-images.githubusercontent.com/62659043/105724801-1818e480-5edd-11eb-9d62-242636697705.png)

**Comment by lcimon** [comment]
I had implemented this fix. Thanks for your quick help!

**Comment by JeneferM-MSFT** [comment]
Hello. This change in the release today. 

Please be sure to remove any unmanaged layers before updating as described in [installing upates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

And thanks for helping make CoE great!
