### ISSUE TITLE
[BUG]: App Is Orphaned column created outside of the solution

### ISSUE THREAD

**Issue by tchinnin** [microsoft/powerapps-tools#724]
**Describe the bug**
In the table PowerApps App, the column 'App is orphaned" has a wrong prefix, meaning it has been created outside of the Core solution

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core solution
 - As far as I know 1.71.1 but might be also true for the next ones
 - Table PowerApps App

**To Reproduce**
1. Go to Core solution
2. Click on PowerApps App table
3. Scroll down to "Apps is orphaned" column
4. See the technical name : "cr5d5_appisorphaned"

**Expected behavior**
the technical name should be "admin_appisorphaned"

**Screenshots**
![image](https://user-images.githubusercontent.com/46782173/106009312-7b12a300-60b8-11eb-88d4-40f94b4f0e1c.png)

**Comment by JeneferM-MSFT** [comment]
Hello. Can you please explain in what way this is impacting your usage of the toolkit? As far as we know, its only the awkward naming and hence not something worth the pain of testing around upgrade etc.

**Comment by tchinnin** [comment]
Hi, this was just a "remark", there is no impact on the way the solution is working. As you said, just awkward

**Comment by JeneferM-MSFT** [comment]
Glad to hear we didnt miss a spot where this results in issues. 

Thanks for using CoE
