### ISSUE TITLE
Admin | App Archive and Clean Up - Check Approvals and Archive | Flow error

### ISSUE THREAD

**Issue by craig-lund** [microsoft/powerapps-tools#73]
Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'commondataservice' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: { "status": 404, "message": "Table with name 'msdyn_flow_approvalresponses' does not exist", "source": "commondataservice-wus.azconn-wus.p.azurewebsites.net", "debugInfo": "clientRequestId: 73747c5d-964b-4231-ae87-aa552cbe3b49" }'.

**msdyn_flow_approvalresponse** entity does not exists in my environment... 

![image](https://user-images.githubusercontent.com/54556910/74696458-6e998100-51ac-11ea-88ee-d192f773804b.png)

What solution is that part of?

**Comment by manuelap-msft** [comment]
Please refer to the Setup Instructions https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/CoE%20Starter%20Kit%20-%20Setup%20Instructions.docx

Page 22, STEP 5: INITIALIZE FLOW APPROVAL ENTITIES IN YOUR ENVIRONMENT 

walks you step by step through this.
