### ISSUE TITLE
[BUG]: Common Data Services connector not showing in Canvas Apps

### ISSUE THREAD

**Issue by statto1974** [microsoft/powerapps-tools#730]
Canvas apps are being flagged as using Premium connectors, but when looking at connectors for an app no premium connectors are shown.

Further investigation shows that these apps have a Common Data Service connection to an entity called "SharePoint Sites". The people I've spoken to, have no knowledge of creating this connection in the app, so assuming that it was created from a template. (Have not been able to find said template yet)

 - Core
 - 1.71.7 
 - Admin | Sync Template v2 (Apps)

**Expected behavior**
App should show this CDS Connection

**Comment by JeneferM-MSFT** [comment]
Hello. CDS not showing as a connector is a product team decision. I encourage you to give feedback to the product team in the [Power Apps Ideas forum](https://powerusers.microsoft.com/t5/Power-Apps-Ideas/idb-p/PowerAppsIdeas/status-key/Started) for them to consider changing this.
