### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Flows) - Failed to run issue (Retry Policy issue)

### ISSUE THREAD

**Issue by madshaun1984** [microsoft/powerapps-tools#731]
**Describe the bug**
I believe there is an issue with this flow.

I have noted that the flow has multiple failed runs (mixed with successful runs).

Having investigated, I believe I have found and fixed the cause of the issue.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core Components
 - Version 1.78
 - Admin | Sync Template v3 (Flows)

**Expected behavior**
In my case, the flow exists past this failure (IE: it wasn't deleted during flow run), so I would expect this stage to find the flow and proceed to the next action.

**Screenshots**
![image](https://user-images.githubusercontent.com/432107/106284618-598df480-623b-11eb-8d6f-d30679f4eac5.png)

**Additional context**
By creating another flow and calling the "Get Flow as Admin" action populated with the items from the error, I found it runs to success.

However, I found that the Admin | Sync Template v3 (Flows) settings, have the Retry Policy set to "Exponential Interval", with customized settings.

Mirroring this Retry Policy in my test flow, I started to encounter the failure.

Setting the actions Retry Policy back to its "Default", solves the problem.

**Comment by JeneferM-MSFT** [comment]
Hello and thank you for this very interesting note. We have been tracking the failure you see a product issue with Github bug #669. But your workaround is very interesting and I did validate that it works.

I will not make the change you suggest in our release on Monday as the product fix is expected in the next week, but will keep this open to track in the event that the product fix takes longer than expected for other folks to use. 

Thanks for using CoE and contributing your findings!

**Comment by JeneferM-MSFT** [comment]
ok it turns out there is a new bug in the error propagation. What you are seeing is (mostly likely) just a 429 retry error misbranded at the top as the other failure I was referencing (which is now fixed).

You can validate this by diving in to the point of failure where you will see its true nature as shown here:
![image](https://user-images.githubusercontent.com/62659043/106332330-71657880-623b-11eb-9c4e-32a0ea6bae9d.png)

And your retry with the settings changed worked by happenstance of the resource was no longer being overloaded during rerun. 

Really appreciate your work to help us here though, and thanks again for using CoE!

**Comment by madshaun1984** [comment]
@JeneferM-MSFT, I could be doing something wrong here, but when I deep dive to the point of failure, I'm definitely not seeing the same error descriptors / summaries as you. Is there any way I can check this?

![image](https://user-images.githubusercontent.com/432107/106335056-e3fa4680-6283-11eb-8672-8878870fe956.png)

The expanded "Get New Flow as Admin" is the last action item to error in the chain the overall flow error reports, as shown in the screenshot attached. All other actions in this chain have been hand checked to determine output / paths are correct and as expected.

The flow has failed multiple times over several days, all with the same error from this same action. 

The flow seems to run several times in parallel when triggered, so of 4 parallel runs, 1 has failed each time with this error.

The only time this action has successfully run during the time upto my discovering the failures and taking action to rectify it, is when the chain doesn't hit this action. 

In our case, the CoEStarterKit was installed on Monday of this week, so has run this flow daily for 4+ days now. Todays run is the only successful one as I caught the error before it was triggered.

**Comment by JeneferM-MSFT** [comment]
ok then yes. this is the product bug #669  that I was refencing above, and not the 429 issue. Roll out of fix to #669 is to be complete on Monday. If you repro on a rerun on Tuesday, please let me know.
