### ISSUE TITLE
[BUG]: List Flows as Admin doesnt work for legacy- environments

### ISSUE THREAD

**Issue by raj835** [microsoft/powerapps-tools#734]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)
Admin | Sync Template v2 (Flow Action Details)
 - Solution [Core Components]
 - Version [latest which is available on MS link]
 - App or Flow :CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)
Admin | Sync Template v2 (Flow Action Details)

**To Reproduce**
1. Go to '.Flow..'
2. Click on '..run..'
3. Scroll down to '..last step..'

While running the flow ,getting below error .I have all rights .
**Error**
Error :Cannot read property 'push' of undefined  
Flow: CLEANUP - Admin | Sync Template v2 (Power Apps User Shared With)

Error:Action 'List_Flows_as_Admin' failed
Flow :Admin | Sync Template v2 (Flow Action Details

**Comment by JeneferM-MSFT** [comment]
Hello I believe you are hitting this known product issue #669  but in order to be sure, can you please capture screenshots of the failure you are seeing? 
Please know that screenshots will only come through if you add them from within Github, not if you send in email

**Comment by JeneferM-MSFT** [comment]
Actually it appears there may be an error propagation bug here. If you drill down and look at the actual error message, does it show 429? If so that is the retry issue and you just have to rerun the flow.

**Comment by raj835** [comment]
Hello ,
PFA the error message for Admin | Sync Template v2 (Flow Action Details) ,will attach the error message for the other flow soon .
![Admin-Sync Teamplate v2 (Flow Action Details)](https://user-images.githubusercontent.com/66004078/106439014-3b273380-649d-11eb-8a33-a47872d0fb3d.PNG)

I am Admin of the environment .

Regards
Rajanee

**Comment by JeneferM-MSFT** [comment]
Hello. Can you please create a new test flow and just run List Flows as Admin with that Legacy-<guid> in the environment name? 

To do this you would go to "enter custom value"
![image](https://user-images.githubusercontent.com/62659043/106467769-f5914900-6451-11eb-8d3b-0871104c0374.png)

And then enter the name, shown here with default as the example which has a similar naming convention
![image](https://user-images.githubusercontent.com/62659043/106467885-1a85bc00-6452-11eb-9f66-e7ed89857da7.png)

**Comment by raj835** [comment]
Hello ,
PFA the screenshot of my test flow .It is working perfectly  fine .
![TestFlow_ListflowAsAdmin](https://user-images.githubusercontent.com/66004078/106614787-bff37980-6591-11eb-9e45-da491d168e69.PNG)

**Comment by JeneferM-MSFT** [comment]
Hello. And you can confirm that the CoE-Admin Center shown in your test run is the same one from the error above: "Legacy-76a2..."?

That seems odd as my understanding of these legacy environments is that they were made a few years ago

**Comment by raj835** [comment]
CoE Admin Center in the screenshot of testflow is the environment created to deploy CoE kit .

 The error above: "Legacy-76a2..." is my default Tenant .

Do i need to change it in the Flow .

**Comment by JeneferM-MSFT** [comment]
Yes my ask above was to see if, in your test flow, you could fetch that legcy-76a2... environment. 

So please go to that test flow and re-run with the legacy- environment instead of CoE - Admin Center

**Comment by raj835** [comment]
![ListFlowasAdmin](https://user-images.githubusercontent.com/66004078/106621436-9427c200-6598-11eb-8613-1ae12cbe335e.PNG)


Got the same error again in my test flow .

**Comment by JeneferM-MSFT** [comment]
A few follow up questions:

1) Did you enter it with the Legacy-76a2. prefix when you entered the guid? 
    If not, can you please try that? 
2) You can confirm that this legacy environment is also your default environment?
3) Please call Get Environment as Admin for this legacy envt by selecting its display name. 
    What is returned for Name field?
![image](https://user-images.githubusercontent.com/62659043/106623296-53449480-6529-11eb-9416-3b6e294edab8.png)

**Comment by raj835** [comment]
![Legacy](https://user-images.githubusercontent.com/66004078/106628447-d3a5dc80-659f-11eb-81c6-1db5fcd4e1a4.PNG)
![DefaultEnv](https://user-images.githubusercontent.com/66004078/106628515-e1f3f880-659f-11eb-96c2-fd1b1db88d5b.PNG)
![GetEnvAsAdmin](https://user-images.githubusercontent.com/66004078/106628544-e91b0680-659f-11eb-893b-8aafc2f9bfd5.PNG)


PFA screenshots for above mentioned steps.

When I tried to search "Capgemini (from preview)"  ,its throwing error in Power Platform Admin center.

**Comment by JeneferM-MSFT** [comment]
Thank you. It looks like this environment is not in a good state then from the product pov, and you will have to either migrate its contents and delete it, or reach out to product support in order to get it into a good state. 
Sorry that I am unable to assist further, but this is not an issue with the toolkit.
