### ISSUE TITLE
[BUG]: Power BI - Cloud flow Archive showing deleted Flows

### ISSUE THREAD

**Issue by GarryPope** [microsoft/powerapps-tools#735]
**Describe the bug**
On the Power BI Dashboard is a page called "Cloud flow Archive". It is showing Flows that have been deleted. I believe this should only show Flows that have not been deleted.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Power BI Dashboard
 - Version 2021-01-07
 - App or Flow Power BI Dashboard - page called "Cloud flow Archive"

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Power BI dashboard
2. Click on Cloud flow Archive
3. See Flows that have been deleted are still showing.

**Expected behaviour**
I would expect deleted Flows not to show. In our implementation of COE we are not hard deleting any records for reporting purposes. So I believe the page just needs an additional filter of "Flow Deleted" = "No"

**Screenshots**
N/A

**Additional context**
Nothing else, thanks!

**Comment by manuelap-msft** [comment]
Thanks for letting us know, well spotted! We were just in the middle of preparing a release for today, so I have quickly made this change as well and an updated version of the Power BI template is now available.
