### ISSUE TITLE
[BUG]: Audit Component Solution Missing Dependency 

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#737]
**Describe the bug**
Hi @JeneferM-MSFT new AuditComponent solution is missing some dependency. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - AuditComponent
 - Version 1.30
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello your pictures did not come through, can you please show what you see? I have tested upgrade of audit components and it worked so I will need more information to assist. 

And can you please tell me, did you do this step from setup? 
[initialize flow approvals in your environment](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment)

**Comment by AkashPatel136** [comment]
sry for the inconvenience, but tried again and it worked this time.

**Comment by JeneferM-MSFT** [comment]
Wonderful news. Thanks for using CoE
