### ISSUE TITLE
Edit the DLP Editor app to also show affected flows

### ISSUE THREAD

**Issue by NizarFIL** [microsoft/powerapps-tools#74]
Is it possible to edit the DLP Editor app to also show affected flows?
I tried to do that by copying the affected PowerApps group and try to make changes, but couldn't figure out how to create the required collection for Flows.

**Comment by alaakh42** [comment]
Also, to do the same with the Set App Owner App to include also taking ownership over flows

**Comment by manuelap-msft** [comment]
Thanks for your input! At the moment, the management connectors (https://powerapps.microsoft.com/en-us/blog/new-connectors-for-powerapps-and-flow-resources/) that the CoE Starter Kit is built on top don't have functions to support getting and updating this information for Flows but I've added your feature requests to the roadmap for once the connectors support this.
