### ISSUE TITLE
COE Starter Kit Update Fail

### ISSUE THREAD

**Issue by kundan76** [microsoft/powerapps-tools#740]
Hello, 
We try to update the COE starter Kit and we are receiving the error
![image](https://user-images.githubusercontent.com/43321102/106524174-2e600b00-64b0-11eb-81ff-f7fa939d6b23.png)

Any suggestion will be appreciated

**Comment by manuelap-msft** [comment]
Hello,

sorry, looks like we didn't test this release as thoroughly as we should have and accidently introduced a dependency issue. Can you try this version: https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_88_managed.zip and see if it works (1.88)? 

Thank you and apologies for the inconvenience,
Manuela

**Comment by manuelap-msft** [comment]
Closing as per #742 where we have confirmation that the import/upgrade now works
