### ISSUE TITLE
Admin Components Solution Import Failure

### ISSUE THREAD

**Issue by bartsneary** [microsoft/powerapps-tools#741]
When attempting to upgrade this solution in my environment, it failed.  I deleted the previous solution version from my environment and now have successfully updated the environment with today's released versions of core, audit logs, and nurture.  This one should have been named "CenterofExcellenceGovernanceComponents_1_30_managed.zip", but I digress.  When I attempt to add the CenterofExcellenceAuditComponents_1_30_managed.zip solution to my environment, if fails because there are missing fields in my environment that a Flow requires that aren't in the solution.  Can you include those 2 fields in the solution file?  They are admin_flowexcusedfromarchival and admin_appexcusedfromarchival.  It does't tell me which tables they are supposed to be in.  Here's a screen shot of the error in case it helps (hopefully this turns into something the renders):
![image](https://user-images.githubusercontent.com/41799380/106532669-36bb4480-64b6-11eb-8fd0-c936512c1676.png)

**Comment by bartsneary** [comment]
OK, my bad.  I just noticed that the issue is back with the core solution.  It looks like its upgrade failed.  I'm going to try to take a run at updating it now by deleting other stuff, but get this message when attempting:
![image](https://user-images.githubusercontent.com/41799380/106533344-96feb600-64b7-11eb-8d9c-3479040a3049.png)

**Comment by bartsneary** [comment]
I also just attempted to import core v85 on a brand new environment and it failed there.  I'm pretty sure the Archive Approval entity is just missing from the solution.

**Comment by manuelap-msft** [comment]
Hello,

sorry, looks like we didn't test this release as thoroughly as we should have and accidently introduced a dependency issue. Can you try this version: https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_88_managed.zip and see if it works (1.88)? 

Thank you and apologies for the inconvenience,
Manuela

**Comment by manuelap-msft** [comment]
Closing as per #742 where we have confirmation that the import/upgrade now works
