### ISSUE TITLE
[BUG]: Unable to import Core Components (v1.85)

### ISSUE THREAD

**Issue by hitendra72** [microsoft/powerapps-tools#742]
**Describe the bug**
Solution Import of Core Component fails

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.85
 - App or Flow - solution import 

**To Reproduce**
Import the solution "CenterofExcellenceCoreComponents_1_85_managed.zip"

**Expected behavior**
Expect solution to be imported 

**Screenshots**
![image](https://user-images.githubusercontent.com/46102183/106549350-bd6e3100-654b-11eb-8a75-ceb9350816dc.png)

**Additional context**
Brand new and clean/empty environment.
Following documented steps

I see similar issue but the error seems different hence posting this issue

**Comment by MahendraRanaweera** [comment]
I see the same error message There are missing dependencies. Install the following solutions before installing this one: "Active"
if I use CenterofExcellenceCoreComponents_1_85_managed.zip
But if I use a previous version like   
CenterofExcellenceCoreComponents_1_78_managed.zip
I don't see the same error message

**Comment by GarryPope** [comment]
Same with me. We recently installed CenterofExcellenceCoreComponents_1_78_managed.zip and now when trying to install CenterofExcellenceCoreComponents_1_85_managed.zip we're getting the same error. Thanks.

**Comment by manuelap-msft** [comment]
Hello,

sorry, looks like we didn't test this release as thoroughly as we should have and accidently introduced a dependency issue. Can you try this version: https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_88_managed.zip and see if it works (1.88)? 

Thank you and apologies for the inconvenience,
Manuela

**Comment by hitendra72** [comment]
v1.88 was imported successfully.

**Comment by manuelap-msft** [comment]
Fantastic, thanks for confirming so quickly and sorry again for the inconvenience! We were keen to get this release out, and missed to clean up some dependencies.
