### ISSUE TITLE
[BUG]: PP Admin View MDA dashboard doesn't show charts but data is present

### ISSUE THREAD

**Issue by hitendra72** [microsoft/powerapps-tools#744]
**Describe the bug**
The PP Admin View MDA dashboard doesn't show charts but data is present

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core components
 - Version v1.88
 - App or Flow  App - Power Platform Admin View

**To Reproduce**
1. Go to 'Overview Dashboard.' It shows number of apps/flows as zero but associated views show there are records
2. Click on any environment. 3. It will list the apps or flows but again charts dont refresh/sync with the actual records

**Expected behavior**
Expect the charts to reflect the actual data rows

**Screenshots**
![image](https://user-images.githubusercontent.com/46102183/106592163-21174f00-658a-11eb-8e1f-4115c90801c7.png)

**Additional context**
The flow "Admin | Sync Template v3" has run successfully. Not sure what I'm missing.

**Comment by manuelap-msft** [comment]
This dashboard is using calculated columns which will automatically be scheduled to run approximately 12 hours from the time that the rollup field is saved. If you have just imported the kit, it may take 12 hrs to show this data.

![image](https://user-images.githubusercontent.com/55705669/106594185-ac242500-6549-11eb-9d9e-c9cd75bf5161.png)

**Comment by hitendra72** [comment]
yes - that was it ... the caclculated columns look ok

**Comment by JeneferM-MSFT** [comment]
Wonderful news. Thanks for the update, and for using CoE
