### ISSUE TITLE
Copy of - Admin | Sync Template v2 (Check Deleted) Failed

### ISSUE THREAD

**Issue by kundan76** [microsoft/powerapps-tools#745]
We  updated the latest version of the COE tool kit and Copy of - Admin | Sync Template v2 (Check Deleted) flow is still failing 
![image](https://user-images.githubusercontent.com/43321102/106605228-a836d980-652e-11eb-8d5f-882a835a773e.png)

here is where it is failing
![image](https://user-images.githubusercontent.com/43321102/106605347-cac8f280-652e-11eb-8ec8-6558092ad62f.png)

![image](https://user-images.githubusercontent.com/43321102/106605392-d9afa500-652e-11eb-831e-c1dc5b4e32f1.png)

Thanks

**Comment by manuelap-msft** [comment]
Hello,

this GitHub repo is used for many different projects and solutions which are maintained by different teams. To ensure your issue is tagged and assigned correctly, please pick CoE Starter Kit issue when you raise a new issue. Otherwise, the CoE team might miss your question.
![image](https://user-images.githubusercontent.com/55705669/106625990-25823e80-656f-11eb-94f0-4d4f07068b35.png)

Thank you

**Comment by JeneferM-MSFT** [comment]
Hello I'm afraid we need more detail. What we need is for you to dive in to each of the individual failures and find where its failing in order for me to help. 

Let's start with Newly Deleted Environments. Please open that scope and drive in until you find where the failure exists. Then share here the screen capture of it with all output shown

**Comment by kundan76** [comment]
Thank you JeneferM, 
Here is the screen shot of the error

![image](https://user-images.githubusercontent.com/43321102/106630202-a2022680-6549-11eb-91ea-c6047f6c8b71.png)

**Comment by JeneferM-MSFT** [comment]
Hello. This is a 429 error, something we cannot repair for you I'm afraid. Rerun is the only repair available. 

Couple questions
1) Is this the error you are seeing across the other objects? 
2) How many times have you run this flow? We expect the first run to be the longest. 
3) Have you set the env variable **_Also Delete from CoE_** to yes? I would suggest you do to make these flows (eventually) run faster.

**Comment by kundan76** [comment]
These areo ther error we see
![image](https://user-images.githubusercontent.com/43321102/106633215-949a6b80-654c-11eb-909e-3bcd2ac30679.png)

**Comment by JeneferM-MSFT** [comment]
can you please dive down until you get to the actual action that failed? similar to what you did above?

**Comment by JeneferM-MSFT** [comment]
Hello, I just noticed that you are using an old version of the toolkit, per the v2 designations. You will need to get up to date in order to proceed. 

Please see the notes at the bottom of #748 for tips on upgrading.
