### ISSUE TITLE
[BUG]: Power BI Admin Dashboard

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#746]
**Describe the bug**
When I try to load data in Power BI, I receive the below error. 

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/106619290-6e6dcf00-653e-11eb-996c-b880f9d30ce8.png)

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid we need more infromation:

1) What version of Core do you have installed? 
2) What version of the PBI desktop are you using?
3) What is the name of the PBI template you are trying to open?

**Comment by AkashPatel136** [comment]
Core - 1.85
PBI Desktop - 2.88.1385.0 latest version]
PBI Template - 2021-02-01

**Comment by JeneferM-MSFT** [comment]
Would you mind trying with the version just shipped today?
[2021-02-02.pbit](https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/Dashboard-PowerPlatformAdminDashboard-2021-02-02.pbit)

I dont repro the issue but perhaps someone else did and already fixed wit that update.

**Comment by AkashPatel136** [comment]
Issue resolved. Thank You @JeneferM-MSFT
