### ISSUE TITLE
[BUG]: Assignee Display Name is wrong in Archival flows

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#747]
**Describe the bug**
Variable varAssigneeDisplayName is set to Approval Admin email instead of its display name.
![image](https://user-images.githubusercontent.com/22662809/106630183-e6a6b580-657b-11eb-8d61-e45a1353ecd8.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Governance
 - Version - 1.30
 - Admin | Archive and Clean Up v2 (Start Approval for Apps) / Admin | Archive and Clean Up v2 (Start Approval for Flows)

**Comment by JeneferM-MSFT** [comment]
Hello. That is in the fork where you are re-assigning to the admin. So we expect that to be the value. 
![image](https://user-images.githubusercontent.com/62659043/106631802-f6011100-6531-11eb-8a17-375c9ec8ec64.png)

In the other side of that comparison, you will see we assign to the non-admin when expected.  
![image](https://user-images.githubusercontent.com/62659043/106631918-13ce7600-6532-11eb-93f1-d123c6aee608.png)

**Comment by lcimon** [comment]
Should I understand that ApprovalAdmin should be a Display Name instead of eMail ?

In your first screenshot, we see that the same variable (ApprovalAdmin) is used to populate varAssignee and varAssigneeDisplayName.
So when the record is created in Archive Approvals table, it is confusing to have the same value for App Owner eMail & App Owner Name, even if it is only for Admin. 

![image](https://user-images.githubusercontent.com/22662809/106633605-45b9f980-657f-11eb-878f-93444fa358a3.png)

**Comment by JeneferM-MSFT** [comment]
I see. Yes this was just a simplification for us. We did not do the work to differentiate between email and display name. So in the case of a re-assign you will just see the email address there. 

I have added making this better to the backlog, but dont expect to fund soon due to competing priorities, so you would need to update on your side if this is bothersome. 

If you come up with and test out a good solution and would like to share here, then fixing would be more likely.

**Comment by lcimon** [comment]
Indeed, it isn't a real issue, more a nice to have. 

I will work on it and let you once I found a proper solution.

**Comment by JeneferM-MSFT** [comment]
Closing this out for now, but replies will come to my inbox in the event you have something for us later. 
Thanks for using CoE!

**Comment by lcimon** [comment]
Hi @JeneferM-MSFT,

I just made the following quite update to have the proper display name when approval is assigned to admin:
![image](https://user-images.githubusercontent.com/22662809/108997968-8e596400-76a0-11eb-94a7-3a4a497837fe.png)
