### ISSUE TITLE
Audit Log Solution does not delete

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#749]
**Describe the bug**
Hi @JeneferM-MSFT 

I am trying to import a new version of the Audit Log solution in my tenant. The previous version I had was 1.0.0.20 and trying to update it to 1.3.5 current version. When I imported the new solution after that it throws the error which is pasted below. In the newer version of the Audit Log solution, there is no custom connector included in the solution. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Audit Logs
 - Version - 1.3.5

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/106662025-e43e5e80-656f-11eb-99e2-ccfbd6a89956.png)

![image](https://user-images.githubusercontent.com/75992078/106662080-f1f3e400-656f-11eb-992e-361112e003b7.png)

**Additional context**
Failed deleting solution. Solution dependencies exist, cannot uninstall. DependencyCount : 2 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: [Child] Admin | Sync Logs, Id: 751183fc-db68-ea11-a811-000d3a31cf04, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connector, ObjectName: Office 365 Management API, Id: de4da0c8-bd02-41df-b0da-bbe0290e8fb4, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: connectionreference, ObjectName: admin_sharedadmin5foffice2036520management20api5f691c36f6fa56d15c_a4b81, Id: f6af52b4-b07f-465d-b6bc-8b46905b6d58, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

**Comment by JeneferM-MSFT** [comment]
hello, the custom connector is in the Core components solution. 
You will need to upgrade your version of core and then audit log

**Comment by AkashPatel136** [comment]
I have updated my core solution to 1.88 already

**Comment by JeneferM-MSFT** [comment]
I'm afraid I've tested both clean install and upgrade and the custom connector is there for me. You seem to have gotten into a strange state. You may need to re-install into a clean envt to get to a good state. 

Sorry that we cannot be of more assistance.
