### ISSUE TITLE
[BUG]: Audit Components missing dependencies

### ISSUE THREAD

**Issue by davidolley** [microsoft/powerapps-tools#750]
**Describe the bug**
Trying to import the Audit Components, but getting the following error: 
There are missing dependencies. Install the following solutions before installing this one: "msdyn_FlowApprovalsCore (2.0.1.0)"

**Component (please tell us which flow or app you are experiencing issues with):**
 - Governance
 - 1.30
 - Solution Import

**To Reproduce**
1. Go to Power Apps Solutions
2. Click on 'Import
3. Select the CenterofExcellenceAuditComponents zip file

**Expected behavior**
The solution should be imported

**Comment by hitendra72** [comment]
create a simple flow to do an approval - that should provision the pre-requisite flow approval solution

**Comment by davidolley** [comment]
Thanks, that fixed this issue

**Comment by JeneferM-MSFT** [comment]
Thanks for the assist hitendra72!
