### ISSUE TITLE
[FEATURE REQUEST]: Innovation backlog app not responsive yet

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#751]
**Describe the bug**
Hi, the new DLP editor app in the new version of the CoE is very nice. Certainly because it is responsive.
For the innovation backlog app, there is a lot on a single "tablet" screen that is small.
Is it possible to make the "Innvotation backlog" app responsive for the next CoE version?

**Comment by manuelap-msft** [comment]
Hello! When we started working on the Innovation Backlog, responsive layouts were not yet available. As there is no easy way to upgrade to responsive layouts, we would have to re-do the Innovation Backlog screen by screen to make it responsive. Whilst we are certainly looking to make all apps responsive, it will likely take some more time to achieve that.
