### ISSUE TITLE
[BUG]: There are missing dependencies. Install the following solutions before installing this one: "msdyn_FlowApprovalsCore (2.0.1.0)

### ISSUE THREAD

**Issue by tsegato** [microsoft/powerapps-tools#753]
We have been running the core core components for a while now and has agreed to continue with the governance components. However when we import the Audit Components we get following error. Any pointers?

![image](https://user-images.githubusercontent.com/43033640/106763222-e91a1580-6636-11eb-807e-5bfaf7c794e5.png)

**Comment by JeneferM-MSFT** [comment]
Hello. Per the setup instructions, you need to [initialize the flow approval tables in your environment](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment)

Thanks for using CoE

**Comment by tsegato** [comment]
But don't I need to install the CenterofExcellenceAuditComponents_1_30_managed.zip before I can do those steps?

**Comment by JeneferM-MSFT** [comment]
Aw yes, I see. It seems the product code has changed slightly and the order of these steps needs to be reversed. 
It appears you now have to do the initialization before import.
I will update the setup documentation. Thanks for pointing that out!

**Comment by tsegato** [comment]
Please let me know when updated. I will try to follow it.

Hent Outlook til Android<https://aka.ms/ghei36>

________________________________

**Comment by JeneferM-MSFT** [comment]
Hello, the documentation will not ship for quite a while (we do a monthly update) but you should not be blocked.

Simply do this step first: [initialize the flow approval tables in your environment](https://docs.microsoft.com/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment)

And then do the import of the solution.

**Comment by tsegato** [comment]
Roger I will try.

Hent Outlook til Android<https://aka.ms/ghei36>

________________________________

**Comment by tsegato** [comment]
Hi Jenefer. I cant find anywhere in the documentation what archived actually means? Can we risk components just being deleted without any chance of restoring it, or how does that work?

Best R, Thomas

**Comment by JeneferM-MSFT** [comment]
Archive refers to the object owners optionally backing up their own work. In the approval mail, and in the reminder mails before delete, we encourage them to back up if they'd like to restore later.
