### ISSUE TITLE
Error running flows in CoE

### ISSUE THREAD

**Issue by raj835** [microsoft/powerapps-tools#754]
![Error1V3](https://user-images.githubusercontent.com/66004078/106787789-2356d780-6676-11eb-8f9d-9c7651100f72.PNG)
![Error2V3](https://user-images.githubusercontent.com/66004078/106787793-25209b00-6676-11eb-9d8e-6a7fa931396b.PNG)

Downloaded the current version as suggested by you in my old ticket ,getting the attached error in while turning ON the flows .

**Comment by JeneferM-MSFT** [comment]
Hello, you are experiencing a product issue and not an issue with the toolkit. That said I might be able to offer some help. 

In this same page where you tried to turn this on you should see the connection references. Go in there and fix up your connections. 
![image](https://user-images.githubusercontent.com/62659043/106788854-5e212700-6606-11eb-8187-9b114c5a4ce7.png)

**Comment by raj835** [comment]
![ConnectionRefer1](https://user-images.githubusercontent.com/66004078/106878556-1b437a00-6700-11eb-90c4-3fbba98a5936.PNG)
![ConnectionRefer2](https://user-images.githubusercontent.com/66004078/106878561-1d0d3d80-6700-11eb-8fc0-4e7b0173fd14.PNG)


Blank Connection References .,Please check .

**Comment by JeneferM-MSFT** [comment]
Something went wrong with your setup. If you edit the flow you should be prompted to create the connections.  

Closing out as these issues are not issues with the toolkit and we cannot stretch to also be product support.

You may benefit from recruiting someone familiar with Power Automate and the Power Platform to run your CoE.
