### ISSUE TITLE
[BUG]: Sync Flows fails on new orphelin apps

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#755]
**Describe the bug**
When an orphelin items is discovered by the Sync Flow the first time, the User record associated doesn't contain value for **azureactivedirectoryobjectid**. I guess it is because original AAD account has been removed.
As this value is null, the step 'Get Power App Owner profile 2' failed without returning any error. So, the next switch condition fails.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - v1.88
 - Sync Flows

**To Reproduce**

**Expected behavior**

**Screenshots**
Raw output of 'Get MDD App Creator': Column azureactivedirectoryobjectid is missing.
![image](https://user-images.githubusercontent.com/22662809/106909601-bccacb80-6700-11eb-94fe-b766f9d8e5fd.png)
![image](https://user-images.githubusercontent.com/22662809/106909858-f8659580-6700-11eb-8ff9-037348dd8452.png)

Below the error messages return by 'Get PowerApp Owner profile 2' and 'Switch 2'
![image](https://user-images.githubusercontent.com/22662809/106908359-8771ae00-66ff-11eb-80e2-3d38a0ad7d70.png)

**Additional context**
Not sure if it is bug or something related to my old data.
Screenshots come from 'Admin | Sync Template v3 (Model Driven Apps)', but found the same to the others Sync Flows.

**Comment by JeneferM-MSFT** [comment]
I do think this is from old data, but I have seen one other person with a lot of old data hit this, so lets see if we can address. 

Since I don't have a repro, can you explore for me?
If you move that action (**_Insert Model Driven App (Abandoned)_**) into the default case, and then delete the 404 case, can you validate that you pass then? 

And dont worry, editing the flow wont prevent you from upgrading later, you'll just need to remove the managed layer.

**Comment by lcimon** [comment]
Moving the action you mentioned doesn't fix the issue: the flow do not enter in the switch (**_Switch 2_**) as there are no output in **_Get PowerApp owner profile 2_**.
![image](https://user-images.githubusercontent.com/22662809/107009335-301e1d00-6795-11eb-9842-ff15d681630e.png)

I made some tests to understand why the **_status code_** isn't populate when **_Get PowerApp owner profile 2_** failed. It seems that as the input of this step **_Get PowerApp owner profile 2_** is a correct one, the call isn't performed.

**Comment by JeneferM-MSFT** [comment]
I think I found a solution, can you import this version of core and see if it works for you? 
[CenterofExcellenceCoreComponents_1_90_managed.zip](https://github.com/microsoft/powerapps-tools/files/5947314/CenterofExcellenceCoreComponents_1_90_managed.zip)

Here is how to [install updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates).

I guessed that its null that would be returned, we can tweak a little if this doesn't work. 
![image](https://user-images.githubusercontent.com/62659043/107292580-f06a6600-6a1e-11eb-9b83-8401879a08ae.png)

**Comment by lcimon** [comment]
I will import this and let you know. Thanks for your help.

**Comment by lcimon** [comment]
New solution is imported. It made first run on a limited number of environment as first check. For now it is ok. I will try on all the environments and let you know after a couple of runs.

**Comment by JeneferM-MSFT** [comment]
Hi there. Checking in to see if this issue was resolved for you with that solution.

**Comment by lcimon** [comment]
Hi @JeneferM-MSFT,
Sync flows are running from a couple of days without any issues. I guess it should be ok. Thanks a lot.

**Comment by JeneferM-MSFT** [comment]
Wonderful news. I will hold this open until we ship the fix (likely with the March update) so that others can follow as well. 

Thanks for your help in making CoE great!

**Comment by JeneferM-MSFT** [comment]
This fix is now released. Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.
