### ISSUE TITLE
Make CoE toolkit fully available on Dataverse for Teams

### ISSUE THREAD

**Issue by dylanwauters** [microsoft/powerapps-tools#758]
Make CoE toolkit fully available on Dataverse for Teams.
We would like to upscale as we like instead of pushing directly a big contract to use the CoE toolkit. We would like to do small customizations here and there so it fits our company.

Until now we are not able to import the solution in Dataverse for Teams because the solutions is using some Dataverse Pro entities.

Failed to create entity with logical name admin_app and object type code -1. Exception: Microsoft.Crm.CrmException: Entity admin_app cannot be processed because it includes property HasRelatedNotes which has a dependency on an unsupported entity Annotation in your organization

**Comment by manuelap-msft** [comment]
It is true that the CoE Core solution is currently not available for Dataverse for Teams; the Core solution uses many components that are currently not supported in Teams such as model driven apps, business process flows and custom connectors so it's not just the Notes entity that is stopping the import.

Whilst we are thinking of clever ways of making some parts of the CoE Starter Kit available in Dataverse for Teams, there's too many considerations to work through at the moment to provide any info on what will be feasible. Currently this effort is not funded.

**Comment by dylanwauters** [comment]
Thanks for the heads up! The most important part which should be available in dataverse for teams I think is DEV compliance center & app catalog because those ones impact the IT governance level of the whole company. The cost is a blocking factor here. Apps like theme gallery, templates gallery are only for pro devs which can handle with premiums for the pro devs. I am thinking of just keeping the tables needed for the DCC & app catalog in sync with the dataverse for teams tables, then import the apps in there. Will consume a lot more but for that a per workflow could do the trick I think. Would be nice tho to have a full version of the CoE for teams. Anyway thank you Manuela for creating the CoE, hope it will evolve a lot in the coming months! :D

**Comment by manuelap-msft** [comment]
Thank you for the feedback, and thanks for using the CoE :)

It is definitely one of my goals to make the CoE kit more approachable and available - unfortunately there's only so many hours in the day to work on it! 

Yes, the Dev Compliance center and App Catalog would be our priority as well - but they have a dependency on the model driven app for an Admin to toggle things on/off so at a minimum we would have to build a lightweight canvas app for those, as model driven apps aren't available.

**Comment by JeneferM-MSFT** [comment]
Hello. Just following up here to let you know that this is available in the April upgrade.
