### ISSUE TITLE
Admin | Sync Template v2 (Flows) Failed  'Get_Flow_as_Admin' failed

### ISSUE THREAD

**Issue by ramu1977** [microsoft/powerapps-tools#76]
I am getting Following error  

Error
Action 'Get_Flow_as_Admin' failed

Request to Azure Resource Manager failed with error: '{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Logic/workflows/309ee3ee-e87f-41ea-85f5-eee562e1ec17' under resource group '99F50799AF0E43B6BBAF45CA7A794644-ECBBDFB9CD8B4E708C2A685A65290C54' was not found."}}'.

**Comment by Solarfinder** [comment]
I have the same issue, and trying to identify a step to accomodate for the 404, hasn't been too successful.  You have any replies to you elsewhere?

**Comment by manuelap-msft** [comment]
Could you share some more details here, what type of environment is it, do you have access to see the environment through the admin center aka.ms/ppac?

**Comment by ramu1977** [comment]
Hello
It's  default environment this 3 flow is failing every day 

Admin   \| Sync Template v2 (Model Driven Apps) |    (Upgrade) (org443205d3)
Admin   \| Sync Template v2 (Custom Connectors) |  (Upgrade) (org443205d3)
Admin   \| Sync Template v2 (Flows) | J(Upgrade) (org443205d3)

Error for Model Driven Apps 'Get_user_profile_(V2)' failed
"internalemailaddress": "provisionapp@fabrikam.com",

Error for Custom Connectors
Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown.

Error in Flows
Request to Azure Resource Manager failed with error: '{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Logic/workflows/309ee3ee-e87f-41ea-85f5-eee562e1ec17' under resource group '99F50799AF0E43B6BBAF45CA7A794644-ECBBDFB9CD8B4E708C2A685A65290C54' was not found."}}'.

I have full access to all the environment.

**Comment by manuelap-msft** [comment]
For the model driven app, unless provisionapp@fabrikam.com is a valid email address in your organisation it looks like there's an issue with a model driven app being created by an invalid email address. 

For the custom connector and Flow, can you open the failed run and see what step is failing and provide a more detailed error message?

**Comment by ramu1977** [comment]
Custom Connectors Failing at Action 'Get_Connector_creators_user_profile' failed
Error detail
Exception of type 'Microsoft.SharePoint.Client.ResourceNotFoundException' was thrown.

Flow 
Action 'Get_Flow_as_Admin' failed
Request to Azure Resource Manager failed with error: '{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.Logic/workflows/309ee3ee-e87f-41ea-85f5-eee562e1ec17' under resource group '99F50799AF0E43B6BBAF45CA7A794644-ECBBDFB9CD8B4E708C2A685A65290C54' was not found."}}'.

**Comment by manuelap-msft** [comment]
Closing out old issues without existing action. 
Please be sure to read the new and updated documentation
https://docs.microsoft.com/en-us/power-platform/guidance/coe/starter-kit

And raise issues using this template, providing as much information as you can about the error you are experiencing
https://aka.ms/coe-starter-kit-issues

Please let us know if you have issues in the future!
