### ISSUE TITLE
Modify OOB Email communication template, sending on assignment of Solution Ownership to Power Apps and Power Automate

### ISSUE THREAD

**Issue by Vijaykumarsburali** [microsoft/powerapps-tools#762]
**Describe the bug**
Do we have an capability/feasibility to modify OOB Email communication template, which COE toolkit sends out an email on  assignment of Solution Ownership to Power Apps and Power Automate.

We have an option to ownership for orphaned Power Apps/Automate in COE toolkit dashboard, so once we assign ownership it is triggering an email to new owners, do we have an option to modify that email template to include additional details.

**Comment by manuelap-msft** [comment]
Hello,

this is not an email that the CoE Starter Kit sends out, it is part of the product to notify new owners with this email. At present, this email can't be modified but you could raise this an idea in the Power Apps User Voice forum https://powerusers.microsoft.com/t5/Ideas/ct-p/PA_Comm_Ideas

**Comment by Vijaykumarsburali** [comment]
Hi Manuelap,

Thank you for your response.
As we can see there is flow/Automate "COE Admin | Sync Template v2 (Power Apps User Shared With)" as part of COE toolkit, does this helps us in achieving our requirement, and do we have similar Flow available for **Power Automate User Shared With** as well as part COE for Power Automate?

**Comment by manuelap-msft** [comment]
As per https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#cleanup---admin--sync-template-v3-power-apps-user-shared-with, this flow **gathers** information about who an app is shared with for reporting. It does not send out any emails.

**Comment by Vijaykumarsburali** [comment]
May be its repeated question...
I am not talking about the Apps which we have for setting permission "Set App Permissions" or "Set Flow Permissions", there we are invoking Admin connector to notify the owners.
I am referring the assign Solution Ownership section which we have in Power BI Dashboard, when we drill through orphaned Flow/App. At present we don't have HTTP connector enabled to take screenshot of that section to share. Hope you got the place which I'm looking for/referring.

COE Toolkit -> Power BI Dashboard -> Apps/Flow -> Orphaned Flows/Apps -> Drill Through -> We can see user who accessed/opened and also an option to assign solution ownership. 
Could you please help me in understanding what will be invoked/called when you assign solution Ownership at this place?

**Comment by manuelap-msft** [comment]
I'm not sure what you mean by solution sharing - from this app, also only individual apps or flows are shared via the same connector.

**Comment by Vijaykumarsburali** [comment]
I'm referring this below location, where you can assign ownership of Apps/Flows to other users(who opened/accessed) displayed over there in dashboard.
COE Toolkit -> Power BI Dashboard -> Display all Apps/Flow -> Orphaned Flows/Apps -> Drill Through -> We can see user who accessed/opened and also an option to assign solution ownership.

**Comment by manuelap-msft** [comment]
There is no option to assign solution ownership where you are describing. From where you are describing, you can assign ownership for a single app or a single flow to another user. It works the same way as the Set Flow permission and Set App permission app, and uses the admin connector in the background.

**Comment by Vijaykumarsburali** [comment]
As you mentioned, even dash board also uses the same admin connector in the background to assign permission to app/flow. Is there any flow runs in the background and invokes this admin connector OR
Directly invoking this connector in Power BI itself?

**Comment by Vijaykumarsburali** [comment]
Also, May I know the data source from which you are pulling and displaying data in Power BI dashboard under section "COE Toolkit -> Power BI Dashboard -> Display all Apps/Flow -> Orphaned Flows/Apps -> Drill Through -> We can see user who accessed/opened and also an option to assign ownership". to see who used the apps/flows most.
Like Data verse table name etc...

**Comment by manuelap-msft** [comment]
The dashboard is based on Dataverse tables - see https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#tables
