### ISSUE TITLE
[BUG]: Teams environment deletion throws 404 error but successfully deleted it

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#764]
**Describe the bug**
When an environment in deleted in Teams clean up flow, the delete environment step throw an 404 error even if the environment is successfully deleted.
As the flow fails, user isn't notify and admins don't received the list of environments to review.

**Component:**
 - Solution - Governance
 - Version - 1.30
 - Flow - Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

**Screenshots**
![image](https://user-images.githubusercontent.com/22662809/107502803-75798a80-6b99-11eb-9af4-b02c3db9da4e.png)

**Additional context**
I suppose that _'Delete Environment'_ uses the same logic that PowerShell cmdlet.
According to the [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/remove-adminpowerappenvironment?view=pa-ps-latest#description), the operation returns a 404 NotFound, the environment was successfully deleted. 

I performed some tests. If we pass an wrong environment GUID, error **isn't** thrown and the 204 - No content code is returned.
![image](https://user-images.githubusercontent.com/22662809/107504372-76abb700-6b9b-11eb-83cb-7087df277000.png)

With a real environment GUID, error **is** thrown and the 404-NotFound code is returned
![image](https://user-images.githubusercontent.com/22662809/107504888-3c8ee500-6b9c-11eb-87c6-74cd5ffca901.png)

**Comment by manuelap-msft** [comment]
Hello! Thank you for pointing this out, we didn't realize! I just made a quick fix for the flow to continue running even if this action fails and shipped this now.
![image](https://user-images.githubusercontent.com/55705669/107519659-6e0dad80-6ba8-11eb-90c8-ded19d589d9b.png)

I will look into getting the status to better handle the error, but wanted to unblock customers from not receiving the notifications with a quick fix.

Thank you!

**Comment by lcimon** [comment]
I did also a quick fix as below:
![image](https://user-images.githubusercontent.com/22662809/107619534-99010b80-6c53-11eb-9ec4-38861060e7e3.png)
![image](https://user-images.githubusercontent.com/22662809/107619729-e54c4b80-6c53-11eb-9413-7e6325fa0bd8.png)

Condition Formula: 
@outputs('Delete_Environment')['statusCode']

Assuming that when something is really deleted, 404 error is throw, user is notify only when needed.

Note that this must be apply for the 2 branches: **Apply to each Teams Environment** and **Apply to each Teams Environment - 90 days**

**Comment by manuelap-msft** [comment]
Thank you for helping make the CoE great! We'll incorporate appropriate error handling in the next release, I think we can assume that if the status is 404 it succeeded and any other error codes should be handled and surfaced to the admin via the email.

Thank you again!

**Comment by JeneferM-MSFT** [comment]
This fix is now released. Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.
