### ISSUE TITLE
Admin | Sync Template v2 (Apps) Errors

### ISSUE THREAD

**Issue by keharrin** [microsoft/powerapps-tools#768]
**Describe the bug**

Since latest update of core component's we are receiving this error in the Admin | Sync Template v2 (Apps) flow
Action 'Get_App_Role_Assignments' failed 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Can you please share a screenshot and the detailed error message? Note that you will need to add the picture in github, pictures added via email wont work

**Comment by JeneferM-MSFT** [comment]
also, can you clarify the version you are using? because the names of the flows have changed and you do not appear to have the latest flows

**Comment by keharrin** [comment]
HI Jenefer
Here is the version of core components
Center of Excellence - Core Components
More Commands
CenterofExcellenceCoreComponents
7/28/2020
1.89

Attached image of error [
<img width="779" alt="flow error" src="https://user-images.githubusercontent.com/77410660/107682254-b7700280-6c65-11eb-8493-574baed64976.PNG">
<img width="374" alt="body of error" src="https://user-images.githubusercontent.com/77410660/107682290-c2c32e00-6c65-11eb-9cea-9acaf9569f3e.PNG">

](url)

**Comment by JeneferM-MSFT** [comment]
You are not using the latest version of the flow, the bug you are hitting was fixed a while ago by adding a condition to check for the app being a SharepointFormApp. It now looks like this

![image](https://user-images.githubusercontent.com/62659043/107690137-90620280-6c5e-11eb-90ed-d03b76c124f0.png)


I do see you are on the correct version number for the latest core, but you did not get the updated flow. I suspect one of two things happened here:
1) You are running a copy of the flow which you created in the past. 
2) You did not remove the unmanaged layers when you upgraded to 1.89. See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for how to remove those.

**Comment by keharrin** [comment]
Thanks Jenefer.

I am assuming I can repeat the import and follow the instructions for removing unmanaged layers?

**Comment by JeneferM-MSFT** [comment]
The product design is even once the new solution installed if you just remove the old unmanaged layers then you will see the new solution. 

See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for how to remove unmanaged layers.
And then once you do that, see if you the logic above (with the condition for SP Forms) in the flow.

**Comment by JeneferM-MSFT** [comment]
closing out issues without action items.
