### ISSUE TITLE
[Feature]: Training in a Day App

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#769]
**Describe the bug**
Currently, users get an email with a confirmation notification but the user does not receive a calendar invitation. Is this a plan to add a feature where we can add a Microsoft Team meeting link when we create an event and it will send out to users when they register for the event? Also Since the Common data service connector is old it does not let us change to the Common data service(current environment) connector. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Nurture
 - Version - 1.24

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
That's a great idea! We are just reworking this app to be more responsive so we will look at adding this as well. Thank you for the feedback. We are also updating all of our flows to use the Current Environment connector, we are almost done with the Core and Governance solutions there so are now working on Nurture. We should be able to get that finished for our March release.

Thanks for the great feedback and using the CoE!

**Comment by JeneferM-MSFT** [comment]
Added to our backlog
