### ISSUE TITLE
Managed vs Unmanaged

### ISSUE THREAD

**Issue by Craig-Humphrey** [microsoft/powerapps-tools#77]
This was originally raise here: https://github.com/microsoft/powerapps-tools/issues/14

But as I've gone back to install in a new tenant, I've realised that the documentation gives the option of installing the Managed or Unmanaged solution, but reality is that because you have to modify parts of it (e.g. the connections in the Power Automate flows) you really can only install the Unmanaged solution.

I'm wondering if guidance around installing the the Unmanaged solution into a temporary Environment, modifying it (fixing the connections), repackaging as a Solution and then uploading the solution into a production Environment, would be more useful.

**Comment by manuelap-msft** [comment]
This is a common misconception: Managed does not mean not editable. It just means that managed layer in CDS is locked (although that layer can be patched via solution patch). You can still edit managed components. Several components allow launching designers from a managed solution, like Flows for example to update the connections.

If you are making customisation, we recommend creating your own unmanaged solution on top and bringing in managed solution components into your own unmanaged solution. Entities etc allow customisation in a new unmanaged layer. You can then export your unmanaged solution as a managed solution and install that in your prod environment.

**Comment by Craig-Humphrey** [comment]
Good point. My bad.  I was getting locked from saving Flows due to a separate issue, which I figured out...
Thanks!
