### ISSUE TITLE
[BUG]: Team environment deletion time logic

### ISSUE THREAD

**Issue by StephenCouch** [microsoft/powerapps-tools#775]
**Describe the bug**
It seems that the logic for the select query for environments that have not submitted a business justification within 7 days has a flaw. The filter query is:

admin_environmentsku eq 'Teams' and admin_environmentdeleted eq false and  admin_environmentcreatedon **le** @{body('Get_7_days_in_the_past')}

Assuming this runs every Monday: This will return all environments that have been created in the last 7 days. Since there is no check for actual environment age after this, any environment created within the last week (whether it is 1 day old or 7 days old) that has not given a justification will be deleted.

**Component:**
 - Solution: Governance
 - Version: 1.03
 - App or Flow: Microsoft Teams Admin  | Weekly Clean Up of Microsoft Teams environments

**Expected behavior**
The expected behavior is that environments that are only 7 days old or older with no business justification would be deleted. This could be accomplished by either changing the query to 'ge' rather than 'le' or by defining an age range.

**Comment by JeneferM-MSFT** [comment]
Hello. I don't quite follow you here. 
The action **_List 7 day environments_** returns teams environments that were created 1 week ago or older. Later in the flow we loop through these returned environments in the loop **_Apply to each Teams Environment_** so only these environments are subject to the actions in that loop. 

Can you please let me know, did you see us deleting new environments? Or are you just interpreting the flow?

**Comment by JeneferM-MSFT** [comment]
Closing out items without further action items
