### ISSUE TITLE
[BUG]: Does not show App Last Launched Date

### ISSUE THREAD

**Issue by RamitK** [microsoft/powerapps-tools#777]
**Describe the bug**
When I see the Power Platform Admin View, in the apps tab, I do not see App Last Launched Date value. For most of them it's blank. For some of them there is a date, but it is incorrect. It shows a date of last year which I definitely know is not correct. When I checked the Admin Sync Template (Apps) flow, I see the App Last Launched Date value is not set to any variable which is collected from Admin connector.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.78
 - App Power Platform Admin View

**To Reproduce**
1. Go to Power Platform Admin
2. Click on Apps
3. Check on App Last Launched Date
4. Either the date is wrong or blank

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
This field is filled by the audit log solution. Please note that it cannot go back in time and get old values, it catches launches in the date range each time it runs. 

So you will need to go and view your audit log solution and see
1) What version are you running there? 
1) Has it been running and passing? 

Note also, that your core is a little old, so you may be using the prior version for your flows generally speaking (do your core flows still have v2 in the name?). 
You will want to update both core and audit if that is the case as we re-wrote all the flows to use a more modern and reliable connector a few months ago.

**Comment by RamitK** [comment]
Hi @JeneferM-MSFT,

Thanks for your guidance. I just discovered that audit logs were not even configured in our test tenant. In prod it shows enabled but it does not show any owner, also I am not able to share it with myself or anyone. I see both v2 and v3 flows but I think only v2 flows are working. All v3 flows are enabled but they neither have an owner nor I can share it with anybody.

Does that mean the update (which was recently done) has some issues? Can you please guide me?

**Comment by JeneferM-MSFT** [comment]
**_In prod it shows enabled but it does not show any owner:_**
We just discovered that if you have a service principle do the install (for example by using our ALM Accelerators) then apps at least show without an owner. You should be able to use the Set Permissions apps from Core to assign yourself ownership of apps and flows. And if not I'm afraid you may need to raise a ticket or reach out to a local global admin for help. 
But I also installed a solution the other day manually and no owner was assigned to the apps, I could not repro for the product team. You may have hit a product bug and need to post a ticket. 

**_I see both v2 and v3 flows but I think only v2 flows are working. All v3 flows are enabled but they neither have an owner nor I can share it with anybody._**
Same answer as above for ownership, and you will want to transition to the v3 flows as soon as possible, as well as new version of the audit logs. 

Can you please tell me, did you use the [ALM accelerators](https://docs.microsoft.com/power-platform/guidance/coe/setup-almaccelerator) to install the different test/prod/etc solutions or did you do it manually?

**Comment by RamitK** [comment]
> This field is filled by the audit log solution. Please note that it cannot go back in time and get old values, it catches launches in the date range each time it runs.
> 
> So you will need to go and view your audit log solution and see
> 
> 1. What version are you running there?
> 2. Has it been running and passing?
> 
> Note also, that your core is a little old, so you may be using the prior version for your flows generally speaking (do your core flows still have v2 in the name?).
> You will want to update both core and audit if that is the case as we re-wrote all the flows to use a more modern and reliable connector a few months ago.

Hi @JeneferM-MSFT,

Thanks for your guidance. I just discovered that audit logs were not even configured in our test tenant. In prod it shows enabled but it does not show any owner, also I am not able to share it with myself or anyone. I see both v2 and v3 flows but I think only v2 flows are working. All v3 flows are enabled but they neither have an owner nor I can share it with anybody.

Does that mean the update (which was recently done) has some issues? Can you please guide me?

**Comment by RamitK** [comment]
> **_In prod it shows enabled but it does not show any owner:_**
> We just discovered that if you have a service principle do the install (for example by using our ALM Accelerators) then apps at least show without an owner. You should be able to use the Set Permissions apps from Core to assign yourself ownership of apps and flows. And if not I'm afraid you may need to raise a ticket or reach out to a local global admin for help.
> But I also installed a solution the other day manually and no owner was assigned to the apps, I could not repro for the product team. You may have hit a product bug and need to post a ticket.
> 
> **_I see both v2 and v3 flows but I think only v2 flows are working. All v3 flows are enabled but they neither have an owner nor I can share it with anybody._**
> Same answer as above for ownership, and you will want to transition to the v3 flows as soon as possible, as well as new version of the audit logs.
> 
> Can you please tell me, did you use the [ALM accelerators](https://docs.microsoft.com/power-platform/guidance/coe/setup-almaccelerator) to install the different test/prod/etc solutions or did you do it manually?

**Set Permissions apps from Core to assign yourself ownership of apps**:
When I try it from there it shows 'Flows in solutions cannot yet have their permissions edited programmatically', from Admin Portal when I try the same it shows 'There was an error while updating the users.'

The solution was updated recently, I heard from global admin that he had just updated the solution from portal but had not done any additional configuration what was done for the first time installation, like saving flows, setting environment variables, enabling them etc. Is it possible that there is something wrong with how it got updated?

**Did you use the ALM accelerators to install the different test/prod/etc solutions or did you do it manually**:
We did it manually.

**Comment by JeneferM-MSFT** [comment]
I'm afraid you may have hit a product bug then wrt ownership. I repro'd myself this week one time. I will try to get another repro on my side, and can you please create a support ticket and get me the number? That will help me push. 

In case you are unfamiliar with support, please see [Get Support](https://docs.microsoft.com/en-us/power-platform/admin/get-help-support)

**Comment by RamitK** [comment]
@JeneferM-MSFT Thanks for your help and guidance! I was mistaking it with older flows where we have saved the flows out of the solution and shared. But since now we do not need to do that anymore, we will try to configure the Audit log flows and see if we can see Launch Date.

**Comment by JeneferM-MSFT** [comment]
great. thanks for using CoE!
