### ISSUE TITLE
Error Code 80040203

### ISSUE THREAD

**Issue by KristianBubalo** [microsoft/powerapps-tools#78]
Hi
I'm getting an error code 80040203 trying to import the Core Component Solution. I created a new Environment to test it and have still the same issue. Looking at the help section (https://support.microsoft.com/en-us/help/4514229/error-code-80040203-invalid-argument-error-occurs-when-attempting-to-i) it says I would need to remove the relationship or the relationship has to be removed from the source. Can you help here? Thanks

**Comment by jcook-bci** [comment]
Same issue here, tried removing bpf_admin_app_new_bpf_ffa183a676d64ec9aee6a558129651a2 from customisations.xml and no change.

**Comment by KristianBubalo** [comment]
There is a note within the setup instruction document:
NOTE: Some users may get an Invalid Argument on trying to import the solution. This is due to a breaking change on the CDS side for pre-existing solutions on an older version that use Environment Variables. A fix is being rolled out and should be in all tenants in the next two weeks. In the meantime, if you are experiencing this issue, please import the solution in this folder: https://github.com/microsoft/powerapps-tools/tree/master/Administration/CoEStarterKit/TEMP%20FIX%20for%20Invalid%20Argument%20Error 
It works now. A typical RTFM :D
