### ISSUE TITLE
[BUG]: User keeps receiving archival approval after it has been approved

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#780]
**Describe the bug**
The user keeps receiving archival approval after the user has responded to the archival and submit their decision. I have attached a screenshot of the approval keeps receiving an archival status. Also when I look for the same archival approval in the Power Platform Admin view model-driven app it does not have an approval response stored after the user has submitted their decision. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Governance
 - Version - 1.38
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**
If the user submitted their response then it should not resend the archival approval to the user. 

**Screenshots**
![image](https://user-images.githubusercontent.com/75992078/108395275-9f5b2e80-71e3-11eb-9113-1adf6645b9d9.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/75992078/108395308-a71ad300-71e3-11eb-870c-af2f2439a20d.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. Old records in the Archive Approval table, from before the last update, need to be deleted as those will not be perceived as being the same flow. Please see #763

**Comment by AkashPatel136** [comment]
Hi Jenefer, 

I will delete all the records from Archive Approval Table but what I find out is that on Feb 15 when the flow (Admin | Archive and Clean up V2 Start Approval for flows) run it send out to 1 of the user and he responded to the approval as you can see on the above picture I have. But when I look into the data, I do not see the response saved for that flow. It supposes to save a response.


 
![image](https://user-images.githubusercontent.com/75992078/108427043-929e0100-720a-11eb-88f9-0301c2e5a6a9.png)

**Comment by JeneferM-MSFT** [comment]
There is a second flow which runs to take the response and put it into the archive approval table. 
[Check Approval](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#admin--archive-and-clean-up-v2-check-approval) looks through recent approvals and updates the archive approval table.

**Comment by JeneferM-MSFT** [comment]
And then note that a 3rd flow, [Clean up and Delete](https://docs.microsoft.com/power-platform/guidance/coe/governance-components#admin--archive-and-clean-up-v2-clean-up-and-delete) actually does the work to delete when ready.

**Comment by AkashPatel136** [comment]
Hi Jenefer, 

I did look through the Check Approval Flow and did not find anything related to the flow. As you can see below approval was sent on Feb 15 and check approval flow run on 16th. It has not updated the record yet in the Power Platform Admin view model-driven app or not in the Archival Approval table. 

Approval Sent on Feb 15
![image](https://user-images.githubusercontent.com/75992078/108532890-561fe300-72a6-11eb-99d2-54a03c681c39.png)

Admin | Archive and Clen Up v2 (Start Approval for Flows)
![image](https://user-images.githubusercontent.com/75992078/108534683-66d15880-72a8-11eb-85a4-5b3f87cf908c.png)

Admin | Archive and Clean Up v2 (Check Approval)
![image](https://user-images.githubusercontent.com/75992078/108533477-04c42380-72a7-11eb-81d1-4b5debecdd7e.png)

As of today do not see a record updated in Power Platform Admin View Model-Driven App
![image](https://user-images.githubusercontent.com/75992078/108532647-0d682a00-72a6-11eb-98c8-732c688406fc.png)

Archival Approval Table
![image](https://user-images.githubusercontent.com/75992078/108535219-15759900-72a9-11eb-93c5-ad048f31ea5c.png)

**Comment by JeneferM-MSFT** [comment]
I just validated that this is working correctly, both for default envts and not. 
Do you know, do you have the solution running in multiple environments? Because this only works within one environment. 
You can know for sure by going to the product's approval response table and see if it is there, for the enviroment where you are expecting to see this
![image](https://user-images.githubusercontent.com/62659043/108571186-76f73100-72c4-11eb-93a9-0e0c7c25493c.png)

**Comment by AkashPatel136** [comment]
I went to the Approval Response table and looked for the approval id and the response is approved. if it is approved then why it is not reflecting in Model-Driven app or archival approval table?

**Comment by JeneferM-MSFT** [comment]
closing the loop here for others that may be reading along.
it looks like there is sometimes a delay in when the approval hits the product table, and so we have increased the frequency of the Check Approvals flow to make up for any disaprity.
