### ISSUE TITLE
Microsoft Teams Admin | Ask for Business Justification - Flow not triggering

### ISSUE THREAD

**Issue by Grant-R** [microsoft/powerapps-tools#781]
**Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created**

This flow is not triggering when environments are created. 

new environments being created, both Teams and Prod (there were some others, but I deleted them)

Trigger: 
![image](https://user-images.githubusercontent.com/60246683/108433840-60d07d00-7292-11eb-9518-1198c9223e32.png)

no runs: 
![image](https://user-images.githubusercontent.com/60246683/108433894-76de3d80-7292-11eb-9b5b-a80f61e8fe4b.png)

**Comment by manuelap-msft** [comment]
Hello,

this flow is triggered by the Admin | Sync Template v3 flow of the Core Components https://docs.microsoft.com/en-us/power-platform/guidance/coe/core-components#admin--sync-template-v3 detecting a new environment - this main flow typically runs daily, and once a new environment is written to the Environments table of your CoE Dataverse instance, the Microsoft Teams - Ask for Business Justification flow is triggered.

There are no "When an environment is created" triggers available from the Power Platform for Admins connector, so we rely on this sync to detect new environments. If you would like the team to consider including triggers in our management connectors, you can raise this in the Ideas forum https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas

Thank you for using the CoE
Manuela

**Comment by JeneferM-MSFT** [comment]
This trigger is based on the inventory tables in Core. So "Environments" in your snapshot refers to the Environments table in the Core solution of the CoE install. 
When your **_Admin | Sync Template v3_** flow runs next (default is to run daily), if any environments are added to the table of sku type "Teams", then the trigger will run for each of those. 
It will only run for environments of the Teams sku due to the filter on the trigger.

**Comment by Grant-R** [comment]
Hi Manuela

Thanks for your quick response as always.  This is resolved.

regards
Grant

**Comment by manuelap-msft** [comment]
Great, thank you! We will make sure to call this out more prominently in the docs as well next time we update our documentation.

Thanks again for using the CoE
Manuela
