### ISSUE TITLE
COE toolkit upgradation issue

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#782]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Aparna-Mutalik** [comment]
I want to know what is the correct method to update COE toolkit in our environment.

In our environment, we have recently upgraded COE toolkit and now we have both V2 and V3 flows. I am now confused on which flow should run to get correct data. Should both version of flows run or only one of them should run? 

Please let me know.

**Comment by JeneferM-MSFT** [comment]
Hello. In the past, you used to make copies of flows to make install easier, but with the creation of the Connection References product feature, you no longer need to do this. This is likely how you ended up with v2 and v3. 

You should disable and delete the old v2 flows, and you can keep the v3 flows in place now, making [installing udpates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) in the future easier

**Comment by JeneferM-MSFT** [comment]
Closing out items without further action items
