### ISSUE TITLE
[BUG]: [Child] Admin | Sync Logs does not copy all audit logs

### ISSUE THREAD

**Issue by dudelis** [microsoft/powerapps-tools#785]
**Describe the bug**
On of my customers noticed, that not all Audit Logs are being copied to the CoE environment. We compared the number of log entries from the Office 365 and from CoE and noticed, that there are much more entries available in the Office 365 Logs.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Audit Logs
 - Version 1.3.5
 - App or Flow **[Child] Admin | Sync Logs**

**To Reproduce**
I am not able to reprdocue it, cause you need a really busy environment to get the paged contents.

**Expected behavior**
The expected behaviour is to have the matched log entries from both - Office 365 and CoE DB.

**Screenshots**
No screenshots, cause I cannot reproduce it on my environment and I cannot paste the customer data.

**Additional context**
When we copy the Audit Logs into the Dataverse, we use 2 Actions in the flow for that:
- **List Audit Log Content** - we get an array of log blocks.
- **GetContentDetails** - we execute it for every log block from the previous step to get the real log content, which we then save into the Dataverse DB.

So the problem I noticed for that big customer is that the **List Audit Log Content** step returns the paged results, i.e.  we obtain only 600 items and in the headers you have the _NextPageUrl_ value, which indicates, that you have to call that url to get the next portion of results.
I assume we need to modify the flow with Do Until loop, which will check the NextPageUrl header in the ***List Audit Log Content*. If it is present, we can get the new portion of contents and parse them again.
The reference can be obtained from the MS Docs:
[Paging Contents for busy tenants](https://docs.microsoft.com/en-us/office/office-365-management-api/troubleshooting-the-office-365-management-activity-api#paging-contents-for-busy-tenants)

PS. We have planned to implement this workaround with the customer (i.e. Do Until Loop). I can update you on the results later on.

**Comment by manuelap-msft** [comment]
Hello,

thanks for the great description of this issue! The custom connector does not support paging at the moment. 

In the Admin | Sync Audit Logs you can specify the interval in which chunks of the Audit Logs are retrieved - I would advice making this 1 Hour initially to see if that grabs everything
![image](https://user-images.githubusercontent.com/55705669/108990841-49790180-768f-11eb-8f94-6e1cac9f46b2.png)

They way it works is that those chunks are delegated to the child flow - so if your audit log flow runs daily, and your time interval is 1 hour then the child flow will process Audit Log chunks from 09:00 to 10:00, 10:00 to 11:00 etc.

Let me know if that helps,
Manuela

**Comment by dudelis** [comment]
Hi Manuela,
thanks for the hint. We tried to make the segments smaller, i.e. 1 hour. So in the end 24 child workflows were started. However, even 1 hour segments seem to contain that _NextPageUrl_ header, meaning that not all the results are obtained. Making segments smaller we still cannot be 100% sure, that all logs are received. Do Until loop would be the better solution for that, however, since the customer generates so much data, Power Automate might not be the best solution to copy the logs. I can only imagine how many API Calls are generated in this case :)
Unless the logs can be scoped to PowerPlatform ones and not to Audit.General, we might need to find another solution for the customer and not to use the CoE Audit Log part.
So the problem seems clear, the solution should be also clear, if you consider this to be a valid requirement.

Thanks for your help.

**Comment by manuelap-msft** [comment]
Hello,

unfortunately, the CoE Kit / Audit Log might  not be the best solution for this customer then. Here's the scopes available for the Office 365 Management API https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference#working-with-the-office-365-management-activity-api - as you can see, there is no Power Platform scope and there are no plans currently to add one.

Once available, this feature might be a better fit for the customer
https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-platform-governance-administration/custom-reporting-bring-own-azure-data-lake-power-apps-power-automate

Thanks for the feedback
Manuela

**Comment by BroxCJ** [comment]
Hi, we have managed to edit the flow -and the connector- to send in the queryString the nexpage value obtained in the previous call (substring, and so on in the header Uri obtained). Anyway, we are now facing problems with timing, as it seems MSFt consideres that this flow consumes too much resources, and sometimes it waits until Timeout is expired (currently, 12 hours) and there are more pages to be processed, after we divided the execution in 6, now seemed it worked (5:48 hs), although I still believe it might have something to do with the not too much load at that moment (In the servers).

So, a few  questions are: 1st) If we had to continue with this "customized flow", and expected more than 150K  Action Requests per day, how many Per Flow licenses would it be necessary?

2nd) As we may need to save our development not to be erased with future changes, we were trying to create our own Repository inside AzureDevPos based on the current one in here, but we don't see the "unmanaged" versions, so we could create our managed ones and be able to move if between environments easily. Is there any plan to have the "src" (unmanaged) anywhere?.

Thanks.

**Comment by manuelap-msft** [comment]
Hello,

you can learn more about request and API call limits per license here:
https://docs.microsoft.com/en-us/power-automate/limits-and-config

You can also purchase API call capacity add ons that can be assigned to the environment, see https://go.microsoft.com/fwlink/?linkid=2085130
![image](https://user-images.githubusercontent.com/55705669/110127379-7929b700-7dbd-11eb-8a0f-06da03bb42d3.png)

I couldn't comment on what licenses or add-ons you need, as I'm not an expert in this area.

Yes, we are planning on making the source code of the CoE Starter Kit available soon.
