### ISSUE TITLE
[BUG]: Missing filter value in Archival flow for Apps

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#786]
**Describe the bug**
Conditions to check if current app is already approved or rejected ('_Filter to this one approved_' or '_Filter to this one rejected_') are empty instead of having the current App ID.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Govern
 - Version - 1.30
 - Flow - Admin | Archive and Clean Up v2 (Start Approval for Apps) / 

**Screenshots**
![image](https://user-images.githubusercontent.com/22662809/108995483-77fdd900-769d-11eb-9e4c-b397188062f5.png)
![image](https://user-images.githubusercontent.com/22662809/108997074-7a613280-769f-11eb-9afa-d3653d06962d.png)

**Additional context**
I well checked, there is no unmanaged layers on these flows.

**Comment by JeneferM-MSFT** [comment]
Hello, thanks for posting. This is known and fixed in the current version of Gov that is out there now (1.35)
Thanks for using CoE
