### ISSUE TITLE
[BUG]: The audit log creates empty items in the "PowerApps apps" and "Flows" tables

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#788]
**Describe the bug**

In the "Power apps" table, some records all have empty columns except for the "admin_appid" and "admin_appdeletedon" and / or "admin_applastlaunchedon" columns.

Same thing in the "Flows" table.

See screenshot :

![image](https://user-images.githubusercontent.com/34766578/109136317-45fd7d00-7758-11eb-8625-6731c2919486.png)

I think it's the audit log flow.
For example if an apps was created and deleted on the same day.
Or the problem is elsewhere ...

**Comment by JeneferM-MSFT** [comment]
What version of the audit logs solution do you have?

**Comment by JeneferM-MSFT** [comment]
What version of Core do you have running?

**Comment by orauch-a** [comment]
Sorry, the version used is 1.3.2

**Comment by JeneferM-MSFT** [comment]
Is that the version of Core? Or the version of the Audit logs? 
We did some work recently around reliability of the Core suite with a shift to a new connector. 
Please follow the steps outlined in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) to get to the latest version, clean up this bad data, and see if you still repro with latest bits. 
Thanks for using CoE

**Comment by orauch-a** [comment]
This is the version of the Audit logs

**Comment by JeneferM-MSFT** [comment]
And what is the version of core?

**Comment by orauch-a** [comment]
The version of the core component is 1.71.7

**Comment by JeneferM-MSFT** [comment]
Yes you have likely hit the reliability issues described above. 
Please follow the steps outlined in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) to get to the latest version, clean up this bad data, and see if you still repro with latest bits.

**Comment by JeneferM-MSFT** [comment]
closing out issues without further action items on our side
