### ISSUE TITLE
Developer Compliance Center Canvas App

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#79]
Hello 

I imported the new solution and in Developer Compliance Center app is getting too many errors. The second screen it cannot get the choices for the dropdown filed and getting few error on Home screen. I have attched a pictures of the errors. can you please guide me. 

Thank you
![Capture](https://user-images.githubusercontent.com/59940632/75902734-827cee00-5e0e-11ea-8ba4-e72ac3b536fa.PNG)
![Capture1](https://user-images.githubusercontent.com/59940632/75902740-8577de80-5e0e-11ea-88e2-0f2ebb769460.PNG)
![Capture2](https://user-images.githubusercontent.com/59940632/75902742-8741a200-5e0e-11ea-81d5-4459a495674d.PNG)

**Comment by manuelap-msft** [comment]
Are you still experiencing this issue? Could you try and save and re-publish the app, then close and open it again in edit mode to see if that helps refresh the connections?

**Comment by aakashpatel660** [comment]
It is working after refreshing.
