### ISSUE TITLE
[BUG]: GCC High Error with Pagination Limitation Set to 10000

### ISSUE THREAD

**Issue by rocamp** [microsoft/powerapps-tools#790]
**Describe the bug**

In commercial, there seems to be no issue with the pagination limit being set above 5000 (the expected CDS connector limit) for pagination, but in GCC High, the Flows in the solution can't be saved because this exceeds the limit. 

Is this expected? Is there a separate solution for GCC High to import that has pagination set to 5000?

**To Reproduce**
Import CoreComponents solution into GCC High environment.

Edit a Flow, and then try to save it. You will receive an error saying the pagination limit is too high. Maximum is 5000.

**Comment by JeneferM-MSFT** [comment]
Hello. Are you installing with a trial license?

**Comment by JeneferM-MSFT** [comment]
Hello we just confirmed that GCC supports the 10000 pagination so likely you are using a trial license which does not. Thank you for using CoE

**Comment by rocamp** [comment]
Hi Jenefer,

Can you clarify if you confirmed for GCC or GCC High?

Best regards,

Robert Camp
Support Engineer
Microsoft Dynamics 365
Customer Services and Support
Manager: Kathy Swallow
Office: +1 (469) 775-2200 ext. 2200
rocamp@microsoft.com<mailto:rocamp@microsoft.com>
Working hours: Monday-Friday 8AM-5PM CST
kswallow@microsoft.com
[Microsoft Logo]

**Comment by JeneferM-MSFT** [comment]
Apologies on my typo, yes we confirmed on GCC High today, but have been able to use these flows on both in the past.
