### ISSUE TITLE
DLP Editor App Issue

### ISSUE THREAD

**Issue by challa85** [microsoft/powerapps-tools#791]
Hi Team,

when we tried to create new environment DLP policy from DLP Editor App for some reason not able to create the policy.

The issue what we are facing is that after entering all the details for new policy and  hit Create Policy in the Review screen, it doesn’t show us any prompt whether it is created or errored out. It just stays in the Review screen and once we go back and look in the  main screen it’s not visible there as well. 

CoE Starter Tool kit Version :CenterofExcellenceCoreComponents_1_89_managed

Thanks

**Comment by JeneferM-MSFT** [comment]
Hello. Its just the envt level policy you cant create yes? You are able to create tenant level?

**Comment by challa85** [comment]
It's the envt level policy and I haven't tried Tenant level.

**Comment by JeneferM-MSFT** [comment]
Thanks. I have confirmed that we cannot edit or add envt dlp policies in the tool today. 
So that you are not blocked, please note that these steps are possible from the product team ux today. 
And we appreciate you posting this.

**Comment by JeneferM-MSFT** [comment]
Hello we removed the ability to add envt dlp policies from the app, but you can still use the features to determine impact.
You will need to use the product UX in order to create envt policies
