### ISSUE TITLE
[BUG]: Another "Warrington" in the USA

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#792]
**Describe the bug**
The "Makers" screen has Warrington in the USA.  It should be in the UK - similar to previous bugs I have raised.  Manuela found the issue on the Overview - PowerApps page and fixed

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
Dashboard dated 07/01/2021 provided by Manuela

**To Reproduce**
show Makers Screen 

**Expected behavior**
Warrington is this particular instance is in Cheshire, England,

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

I have fixed this locally, but as we're just planning a big release for April I may not be able to upload the new version before then.

To fix this yourself, select the Map visual and change it to use the "Country, City" measure (that has the little globe next to it) from the Makers table. It is currently using the City measure which doesn't include the country code and hence is incorrect on the map.
![image](https://user-images.githubusercontent.com/55705669/109946343-0bec2800-7cd0-11eb-93f7-f2c51660b9cc.png)

Thank you for spotting this!
Manuela

**Comment by NPrice99** [comment]
Thanks Manuela
________________________________

**Comment by manuelap-msft** [comment]
FINALLY fixed with the current release, shipped today. Thank you for using the CoE!
