### ISSUE TITLE
Not able to on the status of the audit log flow in COE Solution

### ISSUE THREAD

**Issue by Naresh111-spec** [microsoft/powerapps-tools#793]
**Describe the bug**
Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowUnsupportedForInvokerConnections","message":"The workflow with id '751183fc-db68-ea11-a811-000d3a31cf04', name [Child] Admin | Sync Logs cannot be used as a child workflow because child workflows only support embedded connections."}}".

**Component (please tell us which flow or app you are experiencing issues with):**[Child] Admin | Sync Logs,Admin | Sync Audit Logs
 - Solution Center of Excellence - Audit Logs
 - Version [e.g. 1.29]
 - App or Flow [[Child] Admin | Sync Logs,Admin | Sync Audit ]

**To Reproduce**
Failed to activate component(s). Flow client error returned with status code "BadRequest" and details "{"error":{"code":"ChildFlowUnsupportedForInvokerConnections","message":"The workflow with id '751183fc-db68-ea11-a811-000d3a31cf04', name [Child] Admin | Sync Logs cannot be used as a child workflow because child workflows only support embedded connections."}}".
**Expected behavior**
As shown in the below screenshot getting JSON Parse error 
**Screenshots**
![image](https://user-images.githubusercontent.com/79651628/109530032-4a20f600-7adc-11eb-9147-536f639da8ee.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello, did you run steps 6-9 of the [Set up the Power Automate flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow) steps in setup? 
Here is a screenshot as a reminder too:
![image](https://user-images.githubusercontent.com/62659043/109530750-e8c13e80-7a6b-11eb-84cb-34255bab9ace.png)

**Comment by Naresh111-spec** [comment]
Hi,

As suggested above edited both the connections with the UserPrincipalName. Still getting same JSON parse issue 
Please find the below screenshot.


![image](https://user-images.githubusercontent.com/79651628/109630266-bb0eef00-7b6a-11eb-9154-6e7adbba1467.png)
![Screenshot](https://user-images.githubusercontent.com/79651628/109630396-df6acb80-7b6a-11eb-86c4-fb009ff4dc55.PNG)

**Comment by JeneferM-MSFT** [comment]
Can you clarify, it seems like you are getting a different error now yes? It seems like you are now seeing #672 which is fixed in the current version of the audit logs.

**Comment by Naresh111-spec** [comment]
No.. I am getting same issue which is JSON Parse failed in the child admin/Sync Logs flow.
To run this flow i am passing input parameters as tenant id and start/end dates to run the flow.
After getting content details step next step is Parse JSON. While executing Parse JSON for some of the records we are getting JSON parse error as shown in the above screenshot. Could to please sort the issue ASAP.

**Comment by JeneferM-MSFT** [comment]
Given your last sentence, I woud like to set expectations here. 
The toolkit is not a supported solution. It is a set of starter templates for folks to use to get their CoE going. 
We monitor GitHub and fix issues as budget allows.

**Comment by JeneferM-MSFT** [comment]
I just noticed your version. As stated above, this is a known issue already fixed. #672 

Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.

**Comment by Naresh111-spec** [comment]
Thank you.. I am able to run child admin sync log with the help of #672..
But i am not able to run Admin | Sync Audit ] flow. Below is the error message
Your flow could not turn on: Admin | Sync Audit Logs. Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"ConnectionAuthorizationFailed","message":"The caller with object id '1276a428-15e3-4a7f-93b8-cf4f047d3909' does not have permission for connection '/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps/connections/4b6e160bd7924fb2906ea0911c412aad' under Api 'shared_commondataserviceforapps'."}}".
