### ISSUE TITLE
How to manage late approval response for the App/Flow Archival process?

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#794]
Hello,

I am looking for the help on understanding the Archival process management by users in Governance Component (1.23) solution.

There are 2 flows to manage app archival:

**Start Approval -** Sends approval email to makers, if app is not modified in last 6 months, and add the record in Archival Response Table. Let's assume, this flow starts at : 1:00 AM every month 1'st date. --> this flow does not store "Approval Responses" from user in the archive table "Archive Approvals", but only Approval ID.

**Check Approval** - Checks table "Archive Approvals" approval status for the app - if it's approved, app will be deleted, else, approval email will be sent to app maker again. Let's assume, this flow starts at : 1:00 PM every month 1'st date.  --> this flow stores "Approval Responses" from user in the archive table, but only Approval ID.

Now, "User1" approves an app to be deleted let's say on 5th date of the month, meaning after the first batch of "Start and Check" approval flows have ran. In that case, user receives an approval email for the same App which was approved earlier to be deleted. --> I assume this could be the case, because "Approval Response" in the Archive table is never stored after user approves it? or am I missing anything here to understand? 

Could you please help clarifying when "Approval Response" is stored in "Archive Approvals" table as soon as user approve/rejects it before it's being checked if app is approved/reject?

Thanks a ton in advance!

Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Check Approvals is the flow that updates the custom table Archive Approval. 
The March update of the toolkit (estimated to ship this week) has increased the frequency of this run to daily, to help with late approvals.
This is because you cannot have a trigger on the products approval response table due to some nuanced technical issues. 
Hope that helps. And thanks for using CoE

**Comment by JeneferM-MSFT** [comment]
The change I describe above about the increased cadence of **_Check Deleted_** is now released. Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.
