### ISSUE TITLE
[BUG]: Check Deleted Flow has marked 2400 Flows deleted that exist

### ISSUE THREAD

**Issue by binaryjam** [microsoft/powerapps-tools#795]
I have been running tests on the Platform, we have 33 envs, but we concentrate on 2 of them, the default and an Advanced.
In these environments there are over 3k flows, the Dashboard reports 903.

In our default env, there are 2462 Flows marked as deleted that all exist in the platform, I checked by running the PowerShell cmdlet for this and also getting the output from a current GetAllFlows as Admin  action (they match up).

However that Action isnt always reliable, we have had a ticket open with MS about this, got some response that is essentially, "yeh it can do that, cos reasons"  (what sound like good technical reasons, but not for something you rely on).

If that action doesn't report correctly this delete flow compares it with the CDS data for not-deleted flows and then is its missing(which it would be in a broken response)  continues to mark them as deleted.

**Component (please tell us which flow or app you are experiencing issues with):**
Center of Excellence - Core Components - Version [e.g. 1.29]
CoE - Admin | Sync Template v2 (Check Deleted)
14/09/2020   1.60

So right now I have a problem,   How do I fix the data  ?  How do I restore those Flows ?
Do I need to write a flow that reads my export with the FlowIds (the guid) and can I just update the deleted flag,
is that enough, is there something else I need to update ?

I have been looking through the results of a number of runs that do this getallflows and lately it seems to be returning
the right number of values, so reproducing is difficult, if you have not got as many flows or envs it would be difficult
and especially on an intermittent problem, possibly a problem MS fixed recently since we reported it last year.

If there is a problem there are no checks in the current version of the flow, not sure what v3 does,  Would you expect on any given day that there are 100s of deletions ?  Could you not check the status of the flows to delete before marking them deleted ?
Might this need this flow splitting up and having different schedules because of the api calls?

**Comment by JeneferM-MSFT** [comment]
Hello. You have run into a problem with the old versions of the toolkit. 

Basically there are two connectors for Dataverse, an old one (upon which we wrote the toolkit originally) which is being depracated, and a new one. 

A few months ago reliability issues started popping up for the old connector, as you are noting, and so we re-wrote the toolkit to use the new connector, hence the V3 versions of the sync flows.

You will need to [update Core](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) to see these changes, and note that we have the March release of the toolkit coming this week sometime, in the event you want to wait for that. 

To restore those flows, simply turn the new v3 flows on in the order specified in [Activate the sync template flows](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components#activate-the-sync-template-flows) and be sure, if you created a copy of the v2 ones, that you turn them off or delete them. 

Hope that helps, and thanks for using CoE

**Comment by binaryjam** [comment]
Hi Jenefer,  thats going to be a big upgrade for us cos of customisations.

So can I just reset the deleted flag on apps and flows or are there some other flags related Im missing here ?

Thanks.
Simon

**Comment by JeneferM-MSFT** [comment]
I'm afraid I'm not sure. I can't predict what state you are in. There may be a "fullinventory" environment variable that you could use to look for deleted instead of using this (check deleted) flow. But then you would be hitting API throttling. 

That said, the product will soon start throttling memory usage too, something the v3 versions have fixed up. So you will need to upgrade soon. 

If you'd like to share your customizations, I could review to see if they would be of benefit to the community generally, but its unlikely that they all would be.

**Comment by JeneferM-MSFT** [comment]
Closing out issues without additional steps on our side.
