### ISSUE TITLE
[BUG]: Governance Components - Broken connection objects and unable to start flows

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/powerapps-tools#796]
**Describe the bug**
After the governance component module is uploaded we are unable to start the flows per the documentation. The connection objects are blank within the flows. Almost all of the flows are impacted. When inspecting the JSON files there are mismatched connection reference names. For example, the connectionReference property is called "shared_officeusers_1", where as the api name is called "shared_officeusers".

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Governance components
 - Version: 1.38
 - Flows: Please inspect all flows in this component library. These seem to be impacted:
      Admin | Archive and Clean Up v2 (Start Approval for Flows)
      Admin | Archive and Clean Up v2 (Clean Up and Delete)
      Admin | Archive and Clean Up v2 (Check Approval)
      Admin | Compliance detail request
      Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created
      Microsoft Teams Admin | Weekly Clean Up of Microsoft Teams environments

**To Reproduce**
1. Go to Solutions -> Center of Excellence - Governance Components
2. Find the flow titled "Admin | Archive and Clean Up v2 (Clean Up and Delete)"
3. Click on '...'
4. Click 'Turn on'
5. See attached screenshot of error.

**Expected behavior**
The expectation is the flows should start without requiring any kind of connection object repair. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1613085/109697578-04077900-7b54-11eb-9645-d959e5d86fb6.png)

**Additional context**
The flows can be repaired by editing them, confirming the connection objects, then saving. However that creates a new solution layer. According the documentation this will cause issues down the road when attempting to upgrade.

**Comment by JeneferM-MSFT** [comment]
Hello. Have you installed core already? This solution has a dependency on the Core solution being installed.

**Comment by robertcaretta** [comment]
@JeneferM-MSFT  - We did install the Core solution prior to this. We were able to navigate to the CoE Power Platform Dashboard successfully as well.   https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

We did skip these 2 pieces temporarily due to getting other internal resources lined up.
- Set up audit log sync
- Set up the Power BI dashboard

**Comment by JeneferM-MSFT** [comment]
Please note that you can be unblocked by doing the edit and save, you just need to remove the unmanaged later before upgrade. 
I will take a look here.

**Comment by JeneferM-MSFT** [comment]
thanks, this happened to a few flows in core too and we somehow lost our connection references. I am fixing this up for March update

**Comment by robertcaretta** [comment]
Understood. However, we'd like to avoid having that though as that appears
to be against upgrade best practices.

**Comment by JeneferM-MSFT** [comment]
This is local fixed for the next release. 
Thanks for catching.

**Comment by JeneferM-MSFT** [comment]
This fix is now released. Please be sure to remove any unmanaged layers from flows before you update as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you will not see the changes. 

Thanks for using CoE.
