### ISSUE TITLE
COE starter kit issue with audit logs and some reports data

### ISSUE THREAD

**Issue by mohammad-tabrej** [microsoft/powerapps-tools#802]
Hi Team,

We did recently setup COE Starter kit and has issue with multiple parts where in the main is audit logs not getting populated.

Thanks,
Tabrej

**Comment by manuelap-msft** [comment]
Hello,

we will need a little bit more information to help you:
Can you confirm you have also installed the Audit Log solution? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
If yes, can you open the solution and confirm both flows in there are turned on? 
Can you check the run history on those flows to see if they are running successfully?

Thank you
Manuela

**Comment by mohammad-tabrej** [comment]
Hi Manuela,

Let me check and get back to you on this.

Regards,
Mohammad Tabrej
Workplace CoE

Email: Mohammad.tabrej@diageo.com<mailto:Mohammad.tabrej@diageo.com> | M: 9742901588 | IPT:
DIAGEO<http://www.diageo.com/> | Karle Special Economic Zone, Bangalore 560 045
[cid:image001.png@01D7110F.5B91C360]
Advance Leave notice: N/A

**Comment by BandyCh** [comment]
I'm having the same issue.  When I get to the Start a subscription to audit log content section Step 2 and create a connection with my account, i get an error:

Sorry, but we’re having trouble signing you in.

AADSTS700016: Application with identifier 'd94c19aa-1596-41d0-xxxx-a34b77408a0f' was not found in the directory '3596192b-fdf5-4e2c-xxxx-acb706c963d8'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**Comment by manuelap-msft** [comment]
Hello, I'm not sure if that would be the same issue - Mohammad did not mention  any issues with Starting the subscription so we need to track these separately. Could you please raise a separate issue?

Also note that if you have only just enabled the Audit Log in your tenant, it can take up to 24 hours to activate and for the API to become available which will cause the start subscription to fail. If you have very recently enabled the Audit Log, would advise you try this step again in 24 hours.

Thank you
Manuela

**Comment by BandyCh** [comment]
Thank you I will submit as new.  We are using the audit log and search for quite some time.
