### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Connectors) not running

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#803]
**Describe the bug**
I updated the Core components from version 1.78 to version 1.89.
The Admin | Sync Template v3 (Connectors) flow not running

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Core Components
 - Version 1.89
 - Admin | Sync Template v3 (Connectors)

**To Reproduce**
1. Go to 'Admin | Sync Template v3 (Connectors)' details 
2. Click on 'Run'
3. See error
![image](https://user-images.githubusercontent.com/34766578/109940491-6d14fb00-7cd2-11eb-8f22-091059d900f2.png)
4. Edit the flow
5. Check connection references for all actions
![image](https://user-images.githubusercontent.com/34766578/109940884-d3018280-7cd2-11eb-9b42-f46d78e63f40.png)
6. Save the flow
7. ReRun the flow
8. Always the same error

**Additional context**
No connection is displayed on the flow detail page.
![image](https://user-images.githubusercontent.com/34766578/109941643-a863f980-7cd3-11eb-8eb3-e54de58f7553.png)

**Comment by manuelap-msft** [comment]
Hello,

our latest version of the Core Components is 1.98 (https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_98_managed.zip) - did you upgrade to this one?

Thank you
Manuela

**Comment by orauch-a** [comment]
I had downloaded the starter kit on February 24.
And I had the following versions:
![image](https://user-images.githubusercontent.com/34766578/109951321-d5b5a500-7cdd-11eb-9539-af2cbb9fc0a2.png)

I just got the latest version and I'm going to test. But for your information, there are (1) and (2) on some of the .zip files: 
![image](https://user-images.githubusercontent.com/34766578/109952266-ee728a80-7cde-11eb-8299-eede0fc678e2.png)

**Comment by manuelap-msft** [comment]
Hello,

we have a cadence of monthly releases, typically we release a new version with bug fixes or new features once a month and we try to do it in the first week of the month.

Each solution should only be in the CoEStarterKit.zip file once, but because I exported them a few times they will have the (1) and (2) at the end - that should not impact the experience but thanks for pointing it out, I'll rename the files with the next update.

Let me know if you still experience issues with the latest version!

Thank you
Manuela

**Comment by orauch-a** [comment]
Same problem with the 1.98 version.

For additional information, this is the only flow for which I have this problem

**Comment by orauch-a** [comment]
Finally: same problem for the "Admin | Sync Template v3 (PVA)" flow
![image](https://user-images.githubusercontent.com/34766578/109982628-5e463c80-7d02-11eb-8d1f-5631be1719bd.png)

**Comment by JeneferM-MSFT** [comment]
Hello, when you did the upgrade, did you do so following the instructions at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)?

If you do not do this, and have unmanaged layers, you will not see the changes in the flow.

**Comment by JeneferM-MSFT** [comment]
closing out issues without action items on us

**Comment by orauch-a** [comment]
we deleted all the solutions and reinstall only the core component (v1.98) and the problem is still present for the 2 flows: no connection reference on the flow detail page and no hystory
