### ISSUE TITLE
[BUG]: Audit Log Component Child Flow

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powerapps-tools#804]
Hi,
we are getting the below error. When we try to run the child audit log.

It is really urgent can you please help us to fix this issue

**Failed to parse invoker connections from trigger 'manual' outputs. Exception: Could not find property 'headers.X-MS-APIM-Tokens' in the trigger outputs. Workflow has connection references '["shared_admin-5foffice-20365-20management-20api-5f656d4006af872ade","shared_commondataservice_1","shared_commondataservice_2"]' with invoker runtime source.**

**Comment by manuelap-msft** [comment]
Hello,

I'm sorry you're experiencing issues with the CoE Starter Kit. Just to set expectations - the CoE Starter Kit is an unsupported set of templates, and we don't have an SLA or official support process to help.

Can you confirm what solution version of the Audit Log solution you are on?
When are you receiving this issue - when you turn on the flow, during a flow run, during import of the solution? 
If possible could you share a screenshot of the error and where you are seeing it - please note that screenshots do not come through if you reply to this via email, but you have to open GitHub and paste the screenshot in directly there.

Thank you
Manuela

**Comment by ApoorvaKantale** [comment]
Hi,

Thank you for the reply 

Can you confirm what solution version of the Audit Log solution you are on?
![image](https://user-images.githubusercontent.com/78148795/110128513-de48d100-7dec-11eb-995c-ffd17017c709.png)

When are you receiving this issue - **During a flow run**

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/78148795/110128815-3c75b400-7ded-11eb-9bb7-061ca0b1dbf4.png)

**Comment by manuelap-msft** [comment]
Hello,

can you confirm that the [Child] Admin Sync Audit Log flow is turned on and has all connections connected and authorized?

Can you confirm that the parent flow and child flow are running under the same owner, and that connections in both flows are using the same owner?

Thank you
Manuela

**Comment by ApoorvaKantale** [comment]
Hi,

Yes [Child] Admin Sync Audit Log is turned on . While authorizing , we are getting the error.

![image](https://user-images.githubusercontent.com/78148795/110133097-e6573f80-7df1-11eb-94e2-cf2345084d51.png)

Can you confirm that the parent flow and child flow are running under the same owner, and that connections in both flows are using the same owner? --> **Yes same owner for both**

**Comment by manuelap-msft** [comment]
Hello,

you will have to fix the connection to the custom connector in order to run the flow successfully - you can find instructions here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

Only when all connections are fixed will you be able to run these flows.

Thank you
Manuela

**Comment by ApoorvaKantale** [comment]
Hi

The flow has failed again
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/78148795/110200638-f9ffb600-7e84-11eb-863f-f0021a191204.png)

Can you please look into it

**Comment by manuelap-msft** [comment]
Hello 

The main flow is failing because of an issue with the child flow. Can you please open a run from the child flow and check for the where the error is coming from there and come back with a screenshot of the error message so I can look into it. 

Thank you

**Comment by ApoorvaKantale** [comment]
Hi,

Child flow we are getting the below error

But the child flow yet times it runs successful and yet times it fails. Currently it has failed with the below error

![image](https://user-images.githubusercontent.com/78148795/110326576-d84a2e80-803e-11eb-8e38-636704e38002.png)

**Comment by manuelap-msft** [comment]
Thank you for providing those details!

We had a similar issue earlier that was closed with the last release

Can you verify that you're on the latest release?

Can you look at this thread to see what further information we would need to help solve this, if you're on the latest release and still experiencing issues
#672

If you have recently upgraded, can you confirm you have followed the steps here to remove unmanaged layers. this is required to receive the latest upgrade
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

Thank you
Manuela

**Comment by ApoorvaKantale** [comment]
May I know the what is the latest version ?

This is our version
![image](https://user-images.githubusercontent.com/78148795/110328336-3f68e280-8041-11eb-9b03-a4863d184b7b.png)

**Comment by manuelap-msft** [comment]
It's 1.3.6:
https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceAuditLogs_1_3_6_managed%20(1).zip

**Comment by ApoorvaKantale** [comment]
Thank you. :)

I shall install and get back to you if in case of any issue. Please don't close this ticket

**Comment by JeneferM-MSFT** [comment]
Please be sure to follow the [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) instructions, if you have changes in the flows and do not remove them as shown in these steps, you will not get the updates.

**Comment by ApoorvaKantale** [comment]
Hi,

We have still not update the solutions. But the flow fails always. We had three questions 
1. We have not done any changes in the flows other then connections of flow, So before updating the solution should we need to remove the unmanaged layer from the solution
2. And before updating any solution should we need to turn off all the flows in the solutions
3. Is it mandatory to remove the unmanaged layer .Why we should remove and how will it help us

**Comment by manuelap-msft** [comment]
Unmanaged layers get created when you make any changes to the flows - if you are on an old version of the kit, even updating connections would have created an unmanaged layer and that layer stores your changes to our solution. If you perform an upgrade, unmanaged layers will not get overwritten so you will always remain on your older version of the flow. Removing the unmanaged layer will ensure you get the latest version with all our bug fixes and performance improvements. We can also only help with the latest version of the CoE kit, so upgrading again ensures we are able to help you.

**Comment by ApoorvaKantale** [comment]
Thank you 

Before updating any solutions should we need to turn off all the flows within the solution

**Comment by manuelap-msft** [comment]
No, that is not required

**Comment by ApoorvaKantale** [comment]
Hi,

If we have done any changes to flow in the solutions. Either it would be modification of the flow or connection. 

If we have to retain back the changes in flows even after the upgrade of the solutions. How can we do it ?

Because as per above details , we have to remove unmanaged layer and then update. So all changes are gone and after update again we have change manually all the flows.

Is there any process to manage such kind of flows even after upgrade the flows should have the changes we have made.

**Comment by manuelap-msft** [comment]
Hello,

this is not possible in the product at the moment, the only thing you could do is:

You make a copy of the flow to create your changes in, you then receive the upgrades we make in the original flow. After an upgrade you compare our flow to yours and if there are any bug fixes, you make them to your version as well.

Thanks for using the CoE
Manuela

**Comment by ApoorvaKantale** [comment]
Thank you so much Manuelap :)
