### ISSUE TITLE
[BUG]: Action 'Parse_JSON' failed - Audit Log Components

### ISSUE THREAD

**Issue by tsegato** [microsoft/powerapps-tools#809]
I get following error "Action 'Parse_JSON' failed". Any pointers how to solve this?

![image](https://user-images.githubusercontent.com/43033640/110132089-1808e000-7dcb-11eb-959d-33bca5fcc2ca.png)

**Comment by manuelap-msft** [comment]
We had a similar issue earlier that was closed with the last release

Can you verify that you're on the latest release?

Can you look at this thread to see what further information we would need to help solve this, if you're on the latest release and still experiencing issues
https://github.com/microsoft/powerapps-tools/issues/672

If you have recently upgraded, can you confirm you have followed the steps here to remove unmanaged layers. this is required to receive the latest upgrade
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

Thank you
Manuela

**Comment by tsegato** [comment]
After last update error was gone. A new is introduced, but I make another thread for that. Thanks appreciated.

**Comment by manuelap-msft** [comment]
Great thank you - I will close this issue for now, but let me know if it occurs again so we can look into it!

Thank you for using the CoE
Manuela
