### ISSUE TITLE
[BUG] Not all flows are showed in the CoE

### ISSUE THREAD

**Issue by WouterF** [microsoft/powerapps-tools#81]
Hi,
Not all flows are showing up in the "Power Platform Admin View" model-driven Power App and probably also not in the other CoE components.
The cause of this is the "List Flows as Admin" connector that does not return all flows if you have many.
This can be solved as follows:

1. In the flows of the CoE search for the "List Flows as Admin" connectors
2. Go to "Settings"
3. Enable "Pagination"
4. For "Threshold", fill in: 100000
5. Don't forget to click on the "Done" button in the bottom
6. Save your flow(s)

![flowasadminpagination](https://user-images.githubusercontent.com/5990852/75989329-59825900-5ef3-11ea-8db9-1ec0f2049635.PNG)

Please also fix this in the next version of the CoE.
Thanks

Kr,
Wouter

**Comment by manuelap-msft** [comment]
Thanks for spotting this, I've just made the change in the development environment and it will be published with the next release.
