### ISSUE TITLE
Admin | Sync Template v3 (Apps): admin_app With Id = 83aa0ab5-04c4-e911-a85d-000d3ab0d65d Does Not Exist

### ISSUE THREAD

**Issue by tsegato** [microsoft/powerapps-tools#810]
I get following error. Anything I can do to troubleshoot this?

![image](https://user-images.githubusercontent.com/43033640/110285606-c8e9c780-7fe3-11eb-8684-135b0e83a56d.png)

**Comment by JeneferM-MSFT** [comment]
That is an expected and caught error, indicating the the Model Driven App is new to your inventory. 
You will have to go further down in the flow to find the actual error. 

1) Can you please hit "Next Failed", and then see if "Previous Failed" is enabled? If not, this app didnt actually result in a faiulre, it was a pass (after this caught new one)

2) When you hit "NExt Failed" can you please find the failure?

**Comment by JeneferM-MSFT** [comment]
closing out issues without action items on us
