### ISSUE TITLE
Admin | Sync Template v3 (Desktop flows): CRM organization with unique name 'orgx2dxx98x' not found.

### ISSUE THREAD

**Issue by tsegato** [microsoft/powerapps-tools#811]
Get following error. Anything I can do to help troubleshoot?

![image](https://user-images.githubusercontent.com/43033640/110285870-34339980-7fe4-11eb-9f46-46862c0a5203.png)

**Comment by manuelap-msft** [comment]
Hello,

can you look at the trigger for this flow and scroll down under Outputs to 
 "admin_displayname": "Github-ABC",
  "admin_environmentcdsinstanceurl": "https://githubabcxysyasdf.dynamics.com/"

![image](https://user-images.githubusercontent.com/55705669/110352967-6e298d80-802e-11eb-918b-f02cc5831a35.png)

And then can you
1. Go to the Environment URL and see if that exists?
2. Go to PPAC > Environments and see if you can find the Environment Name there? If you can find it there, can you check if the Instance URL there matches what's in the CoE starter kit (with .crm4.dynamics.com) at the end.
3. Go to https://admin.powerplatform.microsoft.com/environments/deleted to see if the environment is listed here under Deleted environments 

It looks like the either the Environment info in the CoE is wrong, or the Environment got deleted. 

Thank you 
Manuela

**Comment by tsegato** [comment]
When I go to the url I see below. 
The Env is not in the deleted.
I can see the env. in the list.

Let me know if I in anyway can support further. Maybe a teams call?


![image](https://user-images.githubusercontent.com/43033640/110373474-d3da4180-804f-11eb-9fd2-a1378034acf4.png)

**Comment by JeneferM-MSFT** [comment]
Hello we cannot meet with our GitHub customers, we can only assist here as budget permits. 
Can you please see if this repros on rerun?

**Comment by tsegato** [comment]
No worries your help here is appreciated. I just followed up on the run history and there is no errors last 3 days. So feel free to close this.

**Comment by JeneferM-MSFT** [comment]
Thank you. Yes we have seen this repro for other folks too but only intermittently. So glad it is resolved and thanks for using CoE!
