### ISSUE TITLE
Admin | Sync Template v3 (Apps): Action 'Parse_Connection_Ref_JSON_2' failed

### ISSUE THREAD

**Issue by tsegato** [microsoft/powerapps-tools#812]
I get following error. Anything I can do from my side to troubleshoot?

![image](https://user-images.githubusercontent.com/43033640/110286034-82489d00-7fe4-11eb-951c-18564cfc09a4.png)

**Comment by manuelap-msft** [comment]
Hello,

if you scroll a little bit lower you can see the purple Parse JSON action that is failing - are there more details in that action on what exactly is failing? Or are you able to share the input for the Parse JSON so we can see why the schema doesn't match our expectation?

Thank you
Manuela

**Comment by tsegato** [comment]
This is from the Get Apps as Admin (Output):
[
  {
    "name": "x-2623-xx-ac01-xx",
    "id": "/providers/Microsoft.PowerApps/scopes/admin/environments/Legacy-xx-x-x-xx-x/apps/x-x-x-x-x",
    "type": "Microsoft.PowerApps/scopes/admin/apps",
    "tags": {
      "localConnectionReferencesJSON": "{\"a2a44bca-22b0-01b7-x-x\":{\"connectionRef\":{\"displayName\":\"Office 365 Users\",\"iconUri\":\"https://tip1icons.azureedge.net/office365users.png\",\"id\":\"/providers/microsoft.powerapps/apis/shared_office365users\",\"isOnPremiseConnection\":false},\"dataSources\":[\"Office365Users\"],\"dependencies\":{},\"dependents\":[],\"id\":\"a2a44bca-22b0-01b7-32ea-2a544be10e96\",\"connectionInstanceId\":\"/providers/microsoft.powerapps/apis/shared_office365users/connections/3489fa9ae99741c7aa4c9224e8376276\"}}",
      "publisherVersion": "2.0.481",
      "sourceGalleryTemplate": "Microsoft.OrgBrowserO365Prod.0.0.12",
      "sienaVersion": "20170118T112315Z-3.19091.21.0"
    },
    "properties": {
      "appVersion": "2017-01-18T11:23:15Z",
      "status": "Ready",
      "createdByClientVersion": {
        "major": 0,
        "minor": 0,
        "build": 0,
        "revision": 0,
        "majorRevision": 0,
        "minorRevision": 0
      },
      "minClientVersion": {
        "major": 0,
        "minor": 0,
        "build": 0,
        "revision": 0,
        "majorRevision": 0,
        "minorRevision": 0
      },x-x-x-x-x",
        "displayName": "x x",
        "email": "stgr@bws.dk",
        "type": "User",
        "tenantId": "x-x-x-x-x",
        "userPrincipalName": "x@x.DK"
      },
      "createdBy": {
        "id": "bae9e41b-db2b-4de5-9106-3fdf80bfff30",
        "displayName": "x x",
        "email": "x@x.dk",
        "type": "User",
        "tenantId": "x-x-x-a8a8-cbc764470b8f",
        "userPrincipalName": "x@x.DK"
      },
      "lastModifiedBy": {
        "id": "x-x-x-x-x",
        "displayName": "xGreig",
        "email": "x@x.dk",
        "type": "User",
        "tenantId": "x-x-421c-a8a8-x",
        "userPrincipalName": "x@x.DK"
      },
      "backgroundColor": "rgba(0, 80, 239, 1)",
      "backgroundImageUri": "https://106c4.wpc.azureedge.net/80106C4/Gallery-Prod/cdn/2015-02-24/prod20161101-microsoft-windowsazure-gallery/Microsoft.OrgBrowserO365Prod.0.0.12/screenshots/icon.png",
      "displayName": "Org Browser",
      "appUris": {
        "documentUri": {
          "value": "https://pafeblobprodby.blob.core.windows.net:443/20170118t000000zab91ae8f18c647d48ca3fe521572c031/document.msapp?sv=2018-03-28&sr=c&sig=x%2FWFaw%3D&se=2021-03-09T08%3A00%3A00Z&sp=rl",
          "readonlyValue": "https://pafeblobprodby-secondary.blob.core.windows.net/xx/document.msapp?sv=2018-03-28&sr=c&sig=LSXCMiNM5Ksfc9szTYul5qFLMAaO0c1nb1Ufcw%2FWFaw%3D&se=2021-03-09T08%3A00%3A00Z&sp=rl"
        },
        "imageUris": []
      },
      "createdTime": "2017-01-18T11:23:16.0087123Z",
      "lastModifiedTime": "2017-01-18T11:23:17.0496441Z",
      "sharedGroupsCount": 0,
      "sharedUsersCount": 0,
      "appOpenProtocolUri": "ms-apps:///providers/Microsoft.PowerApps/apps/x-2623-x-ac01-x",
      "appOpenUri": "https://web.powerapps.com/apps/x-2623-4484-x-x",
      "connectionReferences": [
        {
          "iconUri": "https://tip1icons.azureedge.net/office365users.png",
          "displayName": "Office 365 Users",
          "isOnPremiseConnection": false,
          "isCustomApiConnection": false,
          "bypassConsent": false,
          "id": "/providers/Microsoft.PowerApps/scopes/admin/apis/shared_office365users"
        }
      ],
      "userAppMetadata": {
        "favorite": "NotSpecified",
        "includeInAppsList": false
      },
      "isFeaturedApp": false,
      "bypassConsent": false,
      "isHeroApp": false,
      "environment": {
        "id": "/providers/Microsoft.PowerApps/environments/Legacy-x-5dc2-421c-x-x",
        "name": "Legacy-x-x-421c-x-x"
      },
      "appPlanClassification": "Standard",
      "usesPremiumApi": false,
      "usesOnlyGrandfatheredPremiumApis": true,
      "usesCustomApi": false,
      "usesOnPremiseGateway": false,
      "usesPcfExternalServiceUsage": false,
      "isCustomizable": true
    },
    "appType": "ClassicCanvasApp"
  }
]

I think this is where it goes wrong:
![image](https://user-images.githubusercontent.com/43033640/110375072-c1610780-8051-11eb-8193-79aee67a7d69.png)

**Comment by JeneferM-MSFT** [comment]
Hello. The thing you have highlighted in the red box is not a failure, It is a skipped step. In this case skipped because **Get the App** did not fail, and hence the object is not new to the CoE.

The failure is right below your original picture in the action called **Parse_Connection_Ref_JSON_2**
![image](https://user-images.githubusercontent.com/62659043/111073786-54100500-849d-11eb-8272-759c0c3bfd54.png)


Are there more details in that action on what exactly is failing? Or are you able to share the input for the Parse JSON so we can see why the schema doesn't match our expectation?

**Comment by tsegato** [comment]
Just test run history. Error remains daily. Here is more details:
![image](https://user-images.githubusercontent.com/43033640/111080086-12af4200-84fd-11eb-972f-4ad1f6f3ffd0.png)

Inputs
[
  {
    "iconUri": "https://tip1icons.azureedge.net/office365users.png",
    "displayName": "Office 365 Users",
    "isOnPremiseConnection": false,
    "isCustomApiConnection": false,
    "bypassConsent": false,
    "id": "/providers/Microsoft.PowerApps/scopes/admin/apis/shared_office365users"
  }
]

Schema:
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "iconUri": {
        "type": "string"
      },
      "displayName": {
        "type": "string"
      },
      "apiTier": {
        "type": "string"
      },
      "isOnPremiseConnection": {
        "type": "boolean"
      },
      "isCustomApiConnection": {
        "type": "boolean"
      },
      "bypassConsent": {
        "type": "boolean"
      },
      "id": {
        "type": "string"
      }
    },
    "required": [
      "iconUri",
      "displayName",
      "apiTier",
      "isOnPremiseConnection",
      "isCustomApiConnection",
      "bypassConsent",
      "id"
    ]
  }
}

Errors:
[
  {
    "message": "Required properties are missing from object: apiTier.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[0]",
    "value": [
      "apiTier"
    ],
    "schemaId": "#/items",
    "errorType": "required",
    "childErrors": []
  }
]

**Comment by JeneferM-MSFT** [comment]
It is strange that tier doesn't come through for you for that connector, it does for us, so I dont repro. 
That said, we dont use this property so it is likely safe to remove from the required list. Can you please make the following edit to your flow and see if it works? Note that you will need to remove the unmanaged layer created by this edit later, but I can show you how. 

Open the flow in edit, select the line shown here and delete it
![image](https://user-images.githubusercontent.com/62659043/111326945-97e84300-8632-11eb-8994-5ee60684fa5f.png)

**Comment by apoorvakasbekar** [comment]
I have edited the Flow and re-run it. Waiting for it to complete execution.

**Comment by apoorvakasbekar** [comment]
The Flow run was successful 

![image](https://user-images.githubusercontent.com/69908205/111805061-b2ead980-88f6-11eb-9e79-a089c386f06a.png)

**Comment by JeneferM-MSFT** [comment]
Thank you for testing that. I have made this change locally, tested for side effects, and it now ready for next release.

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
