### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Check Deleted) flow is failing

### ISSUE THREAD

**Issue by RamitK** [microsoft/powerapps-tools#813]
**Description**
CLEANUP - Admin | Sync Template v3 (Check Deleted) flow is failing in "List PVA Component Flows with Missing Flow" step inside the "Delete items from CoE". It is failing with error 400. "code":"0x0","message":"A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'."

The input of the step was the default one (not changed):

{
    "host": {
        "connectionReferenceName": "shared_commondataserviceforapps_1",
        "operationId": "ListRecords"
    },
    "parameters": {
        "entityName": "admin_pvacomponentflowlookups",
        "$select": "admin_pvacomponentflowlookupid",
        "$filter": "_admin_flow_value eq ''"
    }
}

**Component:**
 - Solution Core Component
 - Version 1.78
 - CLEANUP - Admin | Sync Template v3 (Check Deleted) flow

**To Reproduce**
1. Go to CLEANUP - Admin | Sync Template v3 (Check Deleted) flow inside Core Solutoons
2. Click on Run
3. After two days of continuous running
4. it shows above mentioned error

**Screenshots**
Input
![image](https://user-images.githubusercontent.com/39703138/110286720-63113600-800b-11eb-8565-8c06688bbe9f.png)

Output
![image](https://user-images.githubusercontent.com/39703138/110286589-32310100-800b-11eb-8d06-5e539714727c.png)

**Comment by manuelap-msft** [comment]
I think you're a few versions behind our latest version - we have recently fixed some issues related to this in the recent update (1.98) so if you are not on the latest version would recommend upgrading https://github.com/microsoft/powerapps-tools/raw/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_1_98_managed%20(1).zip

Please follow the steps here for installing updates:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

**Comment by RamitK** [comment]
@manuelap-msft Thanks for your reply! I will try upgrading it and check if it resolves the issue.

**Comment by JeneferM-MSFT** [comment]
Closing out issues without further action

**Comment by RamitK** [comment]
The flow still fails with multiple errors. First it fails for "Newly Deleted Canvas App" step for Get Apps as Admin connector. I verified that the environment was deleted:
![image](https://user-images.githubusercontent.com/39703138/111987619-71943d00-8b35-11eb-901e-68faf687c8af.png)
and it is possible it was deleted when the flow was in the middle (as it took more than 5 days to run). My question is, shouldn't there be error handling for this flow in case the environment does not exist anymore?

Also it failed for PVAs:

![image](https://user-images.githubusercontent.com/39703138/111987854-ba4bf600-8b35-11eb-9172-316b96f0c089.png)

The error being (status: 400): {"code":"0x0","message":"A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'."}

Not sure why it is also failing. Could you please advise?

Solution version for Core Components: 1.98
