### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Connection Status) flow is failing

### ISSUE THREAD

**Issue by RamitK** [microsoft/powerapps-tools#814]
**Description**
CLEANUP - Admin | Sync Template v3 (Connection Status) flow is failing in "Get App as Admin" step or "Parse JSON" step under "Clean App Connection Status" "Apply to each" loop. The instances of the loop for which it is failing, I can see two types of error: 

- "statusCode":404 "message":"The response is not in a JSON format.","innerError":"Cannot read server response." I searched for some of these apps using Get-AdminPowerApp cmdlet and it seems they really do not exist anymore.
- In the second case "Get App as Admin" is successful. But "Parse JSON" step fails with error: 'Parse_Connection_Ref_JSON' inputs at line '1' and column '54070': 'Required property 'content' expects a value but got null. Path ''.'. I took ownership of one of those apps and it had only one connection (which is active). And in the output 

**Component:**
 - Solution Core Component
 - Version 1.78
 - App or Flow CLEANUP - Admin | Sync Template v3 (Connection Status) 

**To Reproduce**
1. Go to CLEANUP - Admin | Sync Template v3 (Connection Status) flow inside Core Solutions
2. Click on Run
3. Wait for 6-8 minutes
4. Flow will fail with the mentioned error

**Screenshots**

App Not Found error:
![image](https://user-images.githubusercontent.com/39703138/110296473-6232d100-8018-11eb-8249-6163f970dff2.png)

Parse Connection error:
![image](https://user-images.githubusercontent.com/39703138/110296651-91e1d900-8018-11eb-99ae-615b96257387.png)

**Comment by manuelap-msft** [comment]
Hello,

for the first one, this is a product bug. We have occasionally seen issues where if an app that was in a solution is deleted, the Get-AdminPowerApp still returns it. In the CoE kit, we depend on what the product connectors return - in this case, you can raise a Support Ticket and the Support Engineers can perform a clean up. In the Support Ticket, if you mention the cmdlet itself vs the CoE starter kit this will help get to a solution faster (sometimes when the CoE kit is mentioned in the support ticket, they redirect it back to me and we go in circles)

for the second one, can you confirm if the one connection the app that failed uses is the CDS native connector (Common Data Service connector) or could you share the JSON input that failed to parse so I can have a look at this further?

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Be sure to follow the steps in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) to remove unmanaged layers before you update, or else you wont see the changes.

**Comment by JeneferM-MSFT** [comment]
Closing out issues without further action
