### ISSUE TITLE
[FEEDBACK]: "Admin | Sync Template v3 (Sync Flow Errors)" flow : no more email notifications

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#815]
**Describe the bug**
In the "Admin | Sync Template v3 (Sync Flow Errors)" flow :
Before an email (with Outlook 365 connector) was sent when an error has occured in a flow.
Now, it is an email notification which is sent using the "Notifications" connector.

Our service account used for the Starter Kit is a licensed administrator account that cannot receive mail from outside.
Notification emails are sent by "Microsoft Flow" which is an external account.
Therefore, we no longer receive notification emails if an error has occured in a flow.

Why did you change the notification system and wouldn't it be possible to keep the old method of notifications (with the outlook connector) ?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Core Components
 - Version 1.98
 - Flow Admin | Sync Template v3 (Sync Flow Errors)

**Comment by manuelap-msft** [comment]
Hello,

thanks for this feedback! We had an increasing amount of customers who do not use Outlook and wanted to use the CoE Starter Kit so we tried to come up with an approach using Notifications that would work for those customers as well - we thought Notifications would work for most customers, but thank you for sharing the feedback about your use case in which case it doesn't work. We'll go back to the drawing board on this now. We might have to introduce to separate flows - one using Outlook and one using Notifications where the customer can pick which one to use.

In the meantime, you can edit the flow and replace the Notification action with the Send an Email Outlook action again.

Thank you for letting us know this feedback,
Manuela

**Comment by orauch-a** [comment]
Thank you for your answer and I had planned to override the notification action

**Comment by manuelap-msft** [comment]
Great, thank you for confirming! We'll look further into how to make this work for all customers with the next release which should come out beginning of April!

**Comment by JeneferM-MSFT** [comment]
This is local fixed for April release.

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
