### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Check Deleted) - Lost deletion date

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#816]
**Describe the bug**
All deletion dates are set to the date of the last execution of the flow (environment, App, Flow, ...)
We lose the real date of deletion which could be defined by the audit log flow for example.

Would it be possible to keep the "Deleted On" date if it has already been set before.
This would allow us to clean the Starter Kit data ourselves if the item was deleted more than 6 months ago for example.

For example in "Newly Deleted Environments" scope :
In the "Mark Environment as deleted" action :
for the "DeletedOn" field, replace @{variables('today')} by @{coalesce(items('For_Each_non_del_env_in_CoE')?['admin_environmentdeletedon'],variables('today'))}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Core Components
 - Version 1.89
 - Flow CLEANUP - Admin | Sync Template v3 (Check Deleted)

**Comment by orauch-a** [comment]
My example of correction that I gave is for the action "Mark Environment as deleted", it would obviously be necessary to do the same thing for the other objects : apps, flows, ...

**Comment by JeneferM-MSFT** [comment]
April release is now live. Please be sure to remove any unmanaged layers before updating or you will not receive the update. 
See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for details.
