### ISSUE TITLE
[BUG]: "Admin | Sync Flow Issues

### ISSUE THREAD

**Issue by NickPettijohn** [microsoft/powerapps-tools#817]
**Describe the bug**
Since installing the CoE kit, I get daily E-mails titled, "Admin | Sync Flow Errors".
Body:  Some of the Sync Flows in the CoE Starter Kit have failed. See below and navigate to the Flow Instance URL to find out more details:

FLOW:  Admin | Sync Template v2 (Flows)
FLOW:  Admin | Sync Template v2 (Apps)

Environment (both Flows) Wilbur-Ellis Company (default) (Upgrade)

URL:  
PowerApps-CoE North Americaeae39ec0-484e-412d-98de-f79c02a7ce77/flows/27068e3c-6c42-15f7-c068-d5bed4007dc2/runs/08585873935108147158179802583CU53
URL:
PowerApps-CoE North Americaeae39ec0-484e-412d-98de-f79c02a7ce77/flows/269dd05e-c86b-dad9-3c01-384e41235ea0/runs/08585873935104954239986203574CU18

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by NickPettijohn** [comment]
Clicking the hyperlinks does not work for me.  Thank you.  Nick Pettijohn, Wilbur-Ellis Company

**Comment by manuelap-msft** [comment]
Hello,

the link in the Sync flow errors is stitched together based on the value you set for Power Automate Environment Variable and the flow run / ID we have. 

Can you look at the documentation here to update the **Power Automate environment variable** which then would mean the links should come through correctly:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

Once the links come through correctly you can click on them and dive into why the flow is failing, and if you share the error you get there here we can help analyse that.

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
closing out issues without action items on us
