### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 - Two flows missing connectors

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/powerapps-tools#819]
**Describe the bug**
Two flows appear to have missing connectors. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core Components
 - Version: 1.98
 - App or Flow:
CLEANUP - Admin | Sync Template v3 (Connection Status)
CLEANUP - Admin | Sync Template v3 (Orphaned Makers)

**To Reproduce**
1. Go to 'Solutions > Center of Excellence - Core Components'
2. Click on either of the impacted flows. 
3. Review the screenshots.

**Expected behavior**
Required connections should be configured.

**Screenshots**
![BrokenConnectionReferences01](https://user-images.githubusercontent.com/1613085/110708496-61d53a00-81c0-11eb-961c-71fd5d5abdbd.png)

![BrokenConnectionReferences02](https://user-images.githubusercontent.com/1613085/110708505-6568c100-81c0-11eb-98ce-c1a2b1512112.png)

**Additional context**
[This seems to be similar to report posted earlier](https://github.com/microsoft/powerapps-tools/issues/796).

**Comment by JeneferM-MSFT** [comment]
Hello. this was fixed in this version of the toolkit, can you validate, did you follow the steps in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) when you upgraded? If not, then you may be blocked from seeing updates by managed layers.

**Comment by robertcaretta** [comment]
Strange, I checked it later and the connectors are showing up now and I could start the flows.  So I guess this is a non issue.
