### ISSUE TITLE
CoE Starter Kit with Core Components 1_98 generates an error on import

### ISSUE THREAD

**Issue by colinching-msft** [microsoft/powerapps-tools#822]
When importing the CoE Starter Kit downloaded on 3/10/2021, the following error is generated when the solution is imported

" The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and Customization files exported from previous versions of Dynamics 365 are not supported. "

**Comment by JeneferM-MSFT** [comment]
Hello. You likely tried to import the entire download, you need to unzip the CoE Download and chose just the solution file. 

![image](https://user-images.githubusercontent.com/62659043/110791739-2ece8d00-8238-11eb-98be-0ce2cb10ea9f.png)

**Comment by JeneferM-MSFT** [comment]
We recommend following along with the [setup steps](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) to avoid small issues like this which will block you.
