### ISSUE TITLE
CoE - admin | sync template v3 "sync flow errors"  status code "Forbidden" and detail

### ISSUE THREAD

**Issue by tkudya** [microsoft/powerapps-tools#823]
Admin | Sync Template v3 (Sync Flow Errors)

Your flow could not turn on: Admin | Sync Template v3 (Sync Flow Errors). Error: Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Flow '' cannot be activated due to admin API policies."}}".

I am not sure which connector i need to add, could someone advise which connector i need to enable for this to work? I have the office 365 connectors enable.

**Comment by manuelap-msft** [comment]
Hello,

our DLP requirements are listed here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

Additionally, the Notifications connector has to be in the Business data only bucket as of the latest release which is not yet reflected in our docs and may be the one you are missing.

Thank you
Manuela

**Comment by tkudya** [comment]
Hi Manuela, 

Thank you that worked with the Notification App added
