### ISSUE TITLE
[Product Bug] Admin | Sync Template v3 (Apps)

### ISSUE THREAD

**Issue by AHmajid** [microsoft/powerapps-tools#824]
I get following error: Flow run failed.
![1](https://user-images.githubusercontent.com/80525833/110944593-f2388980-833c-11eb-867f-ed490c6144bc.PNG)

**Comment by manuelap-msft** [comment]
Hello,

we will need a little more information to help you - can you let us know what version of the solution you are on?

In the flow, can you click on the grey block "only if not SP App New" and it should show a more detailed error message that we would need to see what's causing this? You may have to pop open all the actions in this statement to get to the error message.

Thank you
Manuela

**Comment by AHmajid** [comment]
Hello
![4](https://user-images.githubusercontent.com/80525833/111433555-b3b91b00-86fe-11eb-8d1e-dd7f3a645106.PNG)

Center of Excellence - Core Components  Version 1.98
Center of Excellence - Audit Logs Version 1.3.6

**Comment by JeneferM-MSFT** [comment]
Hello can you please 

1) Get the output of that failure here for us to see? 
1) Create a separate flow and see if you pass there for the same environment and app? You simply enter those values you show in the parameters as shown here
![image](https://user-images.githubusercontent.com/62659043/111474032-dc361a80-86e8-11eb-9208-23eb13796fb8.png)

**Comment by AHmajid** [comment]
Her The output of the failure:

{"statusCode":404,"headers":{"Vary":"Accept-Encoding","x-ms-coregateway":"core000004","Strict-Transport-Security":"max-age=15724800; includeSubDomains","x-ms-request-id":"northeurope:dff7ec4d- xxxx - xxxx - xxxx -efc81a79d565","x-ms-correlation-request-id":"dff7ec4d- xxxx - xxxx - xxxx -efc81a79d565","x-ms-client-request-id":"ecabb892- xxxx - xxxx - xxxx -63517398a6f3","x-ms-service-request-id":"f11654f0- xxxx - xxxx - xxxx -b764be5c2e4e","x-ms-correlation-id":"ecabb892- xxxx - xxxx - xxxx -63517398a6f3","X-ServiceFabric":"ResourceNotFound","Server-Timing":"x-ms-cgw-downstream-headers;dur=178.5,x-ms-cgw-downstream-total;dur=178.5","X-Content-Type-Options":"nosniff","x-ms-activity-vector":"IN.06.00","Timing-Allow-Origin":"*","x-ms-apihub-cached-response":"true","Cache-Control":"no-store, no-cache","Date":"Sun, 21 Mar 2021 09:11:40 GMT","Content-Length":"205","Content-Type":"application/json"},"body":{"error":{"code":"ApplicationNotFound","message":"The application 'xxxxe9a5-xxxx-xxxx-xxxx-6f000xxxxb62' could not be found in the tenant 'xxxxxxxx-xxxx-xxxx-xxxx-f4b4xxxxedd7'."}}}

**Comment by AHmajid** [comment]
Hello
I did a test with a flow and did pass there for the same environment and app ID.

**Comment by JeneferM-MSFT** [comment]
Can you please paste here showing your passing run?

**Comment by JeneferM-MSFT** [comment]
And can you please validate, if you hit resubmit does this flow pass on rerun?

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid you have hit a product bug then. You will need to contact product support and let them know about your repro outside of the toolkit.

**Comment by JeneferM-MSFT** [comment]
closing out since no issues to fix for the toolkit
