### ISSUE TITLE
[Child] Admin | Sync Logs - fail to parse ResultStatus

### ISSUE THREAD

**Issue by AHmajid** [microsoft/powerapps-tools#825]
I get following error: Action 'Parse JSON' failed
![2](https://user-images.githubusercontent.com/80525833/110945007-7a1e9380-833d-11eb-8647-485a61c03de7.PNG)

**Comment by manuelap-msft** [comment]
Hello

We had a similar issue earlier that was closed with the last release

Can you verify that you're on the latest release? (version 1.3.6 of Audit Logs)

Can you look at this thread to see what further information we would need to help solve this, if you're on the latest release and still experiencing issues
#672

If you have recently upgraded, can you confirm you have followed the steps here to remove unmanaged layers. this is required to receive the latest upgrade
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates

Thank you
Manuela

**Comment by AHmajid** [comment]
Hello
Yes, we have the latest release:
Center of Excellence - Core Components  Version 1.98
Center of Excellence - Audit Logs Version 1.3.6
It was a new clean install & not upgrade.
Thanks.

**Comment by JeneferM-MSFT** [comment]
Can you please paste the entire failure message here since its cut off in the screenshot

**Comment by AHmajid** [comment]
Her the entire failure output:
[
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[11].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[12].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[13].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[14].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[15].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[16].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[17].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[18].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  },
  {
    "message": "Invalid type. Expected String but got Null.",
    "lineNumber": 0,
    "linePosition": 0,
    "path": "[19].ResultStatus",
    "schemaId": "#/items/properties/ResultStatus",
    "errorType": "type",
    "childErrors": []
  }
]

**Comment by JeneferM-MSFT** [comment]
It looks like the second part of the fix to 672 didnt ship. Since we dont repro this failure, can you please do the following to ensure this works for you? I'll show you how to upgrade with the fix so you can get back to unedited state. 

Please edit the child flow and into this spot:
![image](https://user-images.githubusercontent.com/62659043/111996067-e1bfa600-8ad6-11eb-9e1e-1b70fdbe7710.png)


Please replace the contents with this: 
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "CreationTime": {
                "type": "string"
            },
            "Id": {
                "type": "string"
            },
            "Operation": {
                "type": "string"
            },
            "Workload": {
                "type": "string"
            },
            "AppName": {
                "type": "string"
            },
            "ObjectId": {
                "type": "string"
            },
            "UserId": {
                "type": "string"
            },
            "UserKey": {
                "type": "string"
            }
        }
    }
}

And then run the parent to see if you pass.

**Comment by AHmajid** [comment]
I did & it pass with status Succeeded, Thanks 👍 .

**Comment by manuelap-msft** [comment]
Fixed in the release today. 

Thank you for using the CoE Starter Kit
Manuela
