### ISSUE TITLE
[BUG]: Developer Compliance Center navigation broken

### ISSUE THREAD

**Issue by LawrenceHarvey123** [microsoft/powerapps-tools#827]
**Describe the bug**
The navigation at the top of the Developer Compliance Center appears to broken even on new installs of COE

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Govern
 - Version: Audit Components 1.43
 - App: Developer Compliance Center

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Developer compliance center as an environment admin'
2. Click on 'an app'
3. Notice how the top navigation doesn't allow you to go back/use the icon options at the top. Clicks but does nothing.

**Expected behavior**
Navigating

**Screenshots**
![image](https://user-images.githubusercontent.com/77730268/110950370-ab965f80-833b-11eb-84c1-4f2c8233731a.png)

None of the icons featured above work but the text next to them does link successfully.

On the flows page the "flow details" has a partially hard coded URL that misses the /manage/ from the url path and jumps straight to /environments/. Just checked and this isn't reflecting the environment variable for Power Automate that you think it would.

The app detail screen is also shared between model driven apps, and sharepoint form apps. It brings with it the broken navigation icons without the text seen on canvas apps. This seems to have been coded into the items property to only show the text in the menus of canvas apps:

visible: galApps.Selected.'App Type' = 'PowerApps Type'.Canvas

I've gone in and fixed all these things in our local version but they could do with being addressed for the next build?

**Comment by JeneferM-MSFT** [comment]
Thanks for catching! I have local fixed this for next release.

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
