### ISSUE TITLE
[BUG]: Office 365 Management API - Custom Connector Does Not Save

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/powerapps-tools#829]
**Describe the bug**
We have followed the directions multiple times and the information on 2. Security regarding Client id, Secret and Resource URL does not save. Then when we go to the section 4. Test we are unable to create a connection. Setup has been attempted from within both the Power Apps and Flow sites. Neither works.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 1.98
 - App or Flow: Office 365 Management API custom connector

**To Reproduce**
1. Go to 2. Security
2. Fill in Client id, Secret, Resource URL.
3. Click 'Update connector'
4. The connector says it saves, but data does not appear to persist.  (Issue #1)
5. Go to 4. Test
6. Create connection. 
7. Doesn't work.  (Issue #2)

**Expected behavior**
Setup should work per instructions.

**Screenshots**
![Error](https://user-images.githubusercontent.com/1613085/111006693-dfc94a80-8352-11eb-839b-970512be9358.png)

**Additional context**
Highly unlikely our InfoSec team gave us the wrong secret.

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid the issue you are seeing is with the product itself and not the toolkit. We are only funded to help with toolkit issues. You will need to create a product ticket to assist.
