### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Desktop flows) failed

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/powerapps-tools#831]
Admin | Sync Template v3 (Desktop flows) failed
**Unable to process template language expressions in action 'Parse_RPA_JSON' inputs at line '1' and column '50502': 'Required property 'content' expects a value but got null. Path ''.'.**

Solution - Core
Version - 1.98
Admin | Sync Template v3 (Desktop flows)

![image](https://user-images.githubusercontent.com/69908205/111015847-c1099900-83d0-11eb-80c4-1a430de5301c.png)

**Comment by JeneferM-MSFT** [comment]
Hello, similarly to your other issue, in order to help you will need to first find the failed instance (by clicking next failed) and then dive down into the failure until you find the failing action. Then we will explore.

The item you show at the bottom here (with the gray x) is not a failure, it represents a skipped step. In this case because **Get Desktop Flow from CoE** succeeded, therefore the flow is already in the CoE and not new.

**Comment by apoorvakasbekar** [comment]
![image](https://user-images.githubusercontent.com/69908205/111095744-1b872e80-8564-11eb-9e58-231b383f17cf.png)

**Below is the error:** 
InvalidTemplate. Unable to process template language expressions in action 'Parse_RPA_JSON' inputs at line '1' and column '50503': 'Required property 'content' expects a value but got null. Path ''.'.

**Comment by apoorvakasbekar** [comment]
![image](https://user-images.githubusercontent.com/69908205/111095859-5721f880-8564-11eb-918b-e9230283e85f.png)

**Error:** 
InvalidTemplate. Unable to process template language expressions in action 'CoE_ModifiedOn' inputs at line '1' and column '50503': 'The template language function 'formatDateTime' expects its first parameter to be of type string. The provided value is of type 'Null'. Please see https://aka.ms/logicexpressions#formatdatetime for usage details.'.

**Comment by apoorvakasbekar** [comment]
@JeneferM-MSFT I hope your doing well. Can you please have a look at this one? 

Thanks

**Comment by JeneferM-MSFT** [comment]
To set expectations, this is not a supported toolkit. 

We do work hard to keep things in high quality and to track bugs, but opportunistically and as budget permits. 

We try to look at all bugs before the next release though so I'll do what I can. 

Thanks for using CoE

**Comment by JeneferM-MSFT** [comment]
You have two separate issues here. The second one, where the CoEModifiedOn variable fails to set, it because the product is some weird cases returns blank instead of a date. We fixed this in other spots in the product and so I can apply that here too

For the first one, the failure to parse, I do not have **_content_** in the schema as required. Can you please paste here what the schema looks like for you at that step? 
Edit the flow, browse to that step, and capture here:
![image](https://user-images.githubusercontent.com/62659043/111661786-92befb80-87cc-11eb-9f5e-057cf0c0c8f8.png)

**Comment by JeneferM-MSFT** [comment]
I have this issue local fixed for April release
![image](https://user-images.githubusercontent.com/62659043/111668765-504ced00-87d3-11eb-9ee0-4d385fb044ef.png)

Parse issue I do not repro locally, see note above.

**Comment by apoorvakasbekar** [comment]
{
    "type": "object",
    "properties": {
        "schemaVersion": {
            "type": "string"
        },
        "targets": {
            "type": "object",
            "properties": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "properties": {
                            "type": "object",
                            "properties": {
                                "XD22JMjhEkyAAS8lVpFe+w==": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "path": {
                                            "type": "string"
                                        },
                                        "version": {
                                            "type": "string"
                                        },
                                        "processId": {
                                            "type": "integer"
                                        },
                                        "icon": {
                                            "type": "string"
                                        },
                                        "mainWindowTitle": {
                                            "type": "string"
                                        },
                                        "systemConfiguration": {
                                            "type": "object",
                                            "properties": {
                                                "keyboard": {
                                                    "type": "object",
                                                    "properties": {
                                                        "layoutId": {
                                                            "type": "string"
                                                        }
                                                    }
                                                },
                                                "screen": {
                                                    "type": "object",
                                                    "properties": {
                                                        "width": {
                                                            "type": "integer"
                                                        },
                                                        "height": {
                                                            "type": "integer"
                                                        },
                                                        "scale": {
                                                            "type": "integer"
                                                        }
                                                    }
                                                }
                                            }
                                        },
                                        "automationType": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

**Comment by apoorvakasbekar** [comment]
@JeneferM-MSFT can you please have a look at this one?

**Comment by JeneferM-MSFT** [comment]
Can you please post the issue with parse separately? This one will track the issue with COEModifiedOn and is local fixed

**Comment by JeneferM-MSFT** [comment]
April release is now live. Please be sure to remove any unmanaged layers before updating or you will not receive the update. 
See [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) for details.
