### ISSUE TITLE
[BUG]: Office 365 Management API Custom Connector

### ISSUE THREAD

**Issue by tkudya** [microsoft/powerapps-tools#833]
When trying to add theOffice 365 Management API Custom Connector to a DLP, it doesn't show up within powershell - Get-AdminPowerAppConnector. If you add a new connector this shows up. So when you try and run the audit_log flows it fails because of the Environment DLP that's in place. I am not sure how to resolve this issue. 
I have tried to re-import it but the IDs are different so I can't import the audit logs.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: CORE Audit Log
 - Version 1.36
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Powershell
2. Run the following command Get-AdminPowerAppConnector to pick up the connector
3. A connector should be showing as part of the COE

**Expected behavior**

**Screenshots**

**Additional context**
The Office 365 Management Api that comes with the COE kit, works and you can import the Audit flow solution but I have tried to create a new environment. then I recreated the connector to try and add it to the "Environment" this new connector shows up in Powershell and i can add it to DLPs but I couldn't Import the AuditLOgs_1.36 because it's missing the dependencies. now i am stuck with 2 environments without Audit logs.

Could you please assist?

**Comment by JeneferM-MSFT** [comment]
Hello. We have a write up to help with the custom connectors and DLP in review to be published but its not yet released. Here I've just created a PDF version of it and attached. Hope this helps
[Custom Connector into DLP.pdf](https://github.com/microsoft/powerapps-tools/files/6136826/Custom.Connector.into.DLP.pdf)

**Comment by tchagan** [comment]
Hi, I've been struggling with this issue, I solved it previously but something must have changed? 

I followed your documentation, there are a couple of issues. The Add-CustomConnectorToPolicy cmdlet requires the -Environment parameter as you're adding to an Environment scoped DLP. 

You can also get the custom connector details by using the Get-AdminPowerAppConnection -Environment <env> cmdlet. The ConnectorName and ConnectorId returned can be used or just use ConnectorName and append to your string as in the instructions.

Also, to get the policy I had to use the Get-AdminDlpPolicy not Get-DlpPolicy, though I suppose that will work if I'm just the environment owner?

Other than those issues the solution works, so thank you for that!

**Comment by JeneferM-MSFT** [comment]
Thanks tchagan, it sounds like you used the CustomConnectorToPolicy cmdlet directly and not the sample functions, is that accurate? 
![image](https://user-images.githubusercontent.com/62659043/111315508-1095d200-8628-11eb-9040-24ed915c444b.png)

I ask because I have been informed that those are being deprecated due to the big recent changes around DLP (to include blocked for example), this PDF describes the new way of doing it. 

So glad you got unblocked!

**Comment by tchagan** [comment]
Yes, you're correct, I didn't use the Samples. I'll have a look at those though, thank you!

**Comment by tkudya** [comment]
That has worked for me. thank you

**Comment by JeneferM-MSFT** [comment]
Wonderful news. Thanks all for using CoE

**Comment by jconnor2209** [comment]
Thank you for this, I have been trying to figure this out for a while now too. One issue I have ran into is with the step where you Get-DlpPolicy it doesn't return all of the policies, and therefore I cannot obtain the ID of the policy I need to update. We have multiple policies, so I don't want to update the first one. Any advice anyone has regarding this would be greatly appreciated. Thank you!
