### ISSUE TITLE
[BUG]: Admin | Sync Template v3 (Flows) fails due to invalid character in description

### ISSUE THREAD

**Issue by jaspervoskuilen** [microsoft/powerapps-tools#834]
**Describe the bug**
Apparently someone managed to introduce a vertical tab into the description of a flow. This character cannot be inserted in the CDS record.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.98
 - App or Flow: Admin | Sync Template v3 (Flows)

**To Reproduce**
Not sure how they managed to do this, maybe by copying something from Word... For now I asked them to rewrite the description

**Expected behavior**
Invalid characters will be scrubbed before inserting them

**Screenshots**

**Additional context**
`"error": {
            "code": "0x80040278",
            "message": "Invalid character in field 'admin_flowdescription': '\u000b', hexadecimal value 0x0B, is an invalid character.",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "26ff8257-e381-eb11-b1ab-000d3abaa326",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "dc326fa0-a86c-4add-b70b-a27cb9fda677",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "InvalidCharactersInField",
            "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "400",
            "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040278&client=platform",
            "@Microsoft.PowerApps.CDS.InnerError.Message": "Invalid character in field 'admin_flowdescription': '\u000b', hexadecimal value 0x0B, is an invalid character."
        }`

**Comment by JeneferM-MSFT** [comment]
Hello. We do not yet support Core import into Dataverse for Teams. This is something we are actively working on thought. I will retitle and hold this open to help folks see availability when ready.

**Comment by JeneferM-MSFT** [comment]
Apologies I marked the wrong bug here before.

**Comment by JeneferM-MSFT** [comment]
Hello. I do not repro in 1.98. I was able to save a flow with the following description into the inventory 
**Abcd | efg description with vert bar**

Do you happen to have the string still that repro'd for you?

**Comment by jaspervoskuilen** [comment]
`"item/admin_flowdescription": "Wanneer een taak wordt gemaakt of gewijzigd dan controleert deze flow of deze voldoet aan een aantal voorwaardes: InhoudsType en Actie waarde.\u000bAls deze voldoen dan wordt via een HTTP request de Flow opgestart om te archiveren.",`
The above is from the CDS insert.

The descriptions in the flows are already 'fixed' so I can't provide those examples. It were older flows (created 1-2 years ago) and the offending characters seemed to be fancy quotes, probably copied from Word or something like that.

I tried writing some text in Word and pasting it in the description, but that seemed to work, so maybe utf handling for the description field has improved over the years and we are just unfortunate to have some older descriptions

**Comment by JeneferM-MSFT** [comment]
Glad you were able to resolve by fixing up the data. I will go ahead and close then. 
Thanks for using CoE!
