### ISSUE TITLE
[BUG]: Tracking Prevention blocked access to storage for <URL>.le

### ISSUE THREAD

**Issue by JusticeMatarutse** [microsoft/powerapps-tools#835]
**Describe the bug**
Tracking Prevention blocked access to storage for https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.6&x-apikey=a7238&client-time-epoch-millis=16393771&time-delta-to-apply-millis=214.
**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

could you please provide some more details about what is failing - which app, which flow? And provide screenshots of where you are seeing the error message?

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
also which solution and the version of that solution

**Comment by manuelap-msft** [comment]
Closing out issues with no action
