### ISSUE TITLE
[BUG]: Inconsistent Power Platform Connector information in CoE 

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/powerapps-tools#836]
**Inconsistent Power Platform Connector information in CoE** 
Center of Excellence Power Platform Admin View App = **473** 
PowerShell = **463**
PowerPlatform Admin center = **467**

Solution - Core
Version - 1.98

**Comment by JeneferM-MSFT** [comment]
There are product limitations in the connectors which make some objects inaccessible to the CoE (ex custom connectors in a solution). That along with the other items like the snapshot concept in which we have a picture of the inventory only on a daily basis. And you end up with slight differences. 

And as you see there is even inconsistency between admin center and powershell, which is outside of the scope of our toolkit. 

Thanks for using CoE
