### ISSUE TITLE
[BUG]: Inconsistent information about Total number of Flows in CoE

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/powerapps-tools#838]
Inconsistent information about Total number of Flows in CoE

Total Flows 
PowerShell = 2258
CoE = 2253 

Solution - Core
Version - 1.98

**Comment by JeneferM-MSFT** [comment]
Hello. The CoE will have slightly different numbers than powershell for many reasons. 

1. CoE is a snapshot in time (from last run)
2. CoE includes things like deleted flows unless you filter them out explicitly.

Thanks for using CoE
