### ISSUE TITLE
CI_Employee Status list is not populating

### ISSUE THREAD

**Issue by JohnCarter8481** [microsoft/powerapps-tools#84]
**Describe the bug**

**To Reproduce**

- Steps to reproduce the behavior:
- sign into the crisis communication 
- select "status"
-fill out the "out of office" or "wfh"

**Expected behavior**
Whenever I submit "Out of Office" or "WFH" I expect the CI_Employee Status list to populate with data. it is not

**Screenshots**
![image](https://user-images.githubusercontent.com/41119108/76111583-89426700-5fae-11ea-8f83-2dd32d6434a8.png)

**Interface(please complete the following information):**
Edge and Chrome

**Comment by JohnCarter8481** [comment]
as suggested, I was able to unhide the Latitude, Longiture, and Presence Status but the data is still not populating correctly 

![image](https://user-images.githubusercontent.com/41119108/76112104-901da980-5faf-11ea-9ee2-b29d40f68223.png)

**Comment by denisem-msft** [comment]
@JohnCarter8481 can you please update the Crisis Communication canvas app with the most recent version available on GitHub? We deployed a fix yesterday that might fix your issue with writing to the table, which was a formula error in the app.

Please confirm when you have tried this.

**Comment by mr-dang-msft** [comment]
@JohnCarter8481,
Sorry for the issue, the calendar had some issues that we have fixed. We had a fix shortly thereafter and the latest version has the correct function as well. Please confirm on your side.

**Comment by ricky-rivera** [comment]
Has the issue with the powerbi connection to the status list error "The column 'Id' of the table wasn't found" been resolved. I pulled code yesterday.
![image](https://user-images.githubusercontent.com/61850328/76563273-78e22e80-647d-11ea-9324-018f0c7013d5.png)

I'm also having the issue reported above that after selecting WFH or OOO and selecting a date, nothing happens and no records are been added to the list.

**Comment by nicez30** [comment]
> Has the issue with the powerbi connection to the status list error "The column 'Id' of the table wasn't found" been resolved. I pulled code yesterday.
> ![image](https://user-images.githubusercontent.com/61850328/76563273-78e22e80-647d-11ea-9324-018f0c7013d5.png)
> 
> I'm also having the issue reported above that after selecting WFH or OOO and selecting a date, nothing happens and no records are been added to the list.

I am having the same issues

**Comment by mr-dang-msft** [comment]
As mentioned on Issue #112, please make sure you've signed into your Microsoft account and not viewing the report as anonymous.

And it is best to populate the list before viewing it in the report.

Link: https://github.com/microsoft/powerapps-tools/issues/112
