### ISSUE TITLE
CoE -1.89

### ISSUE THREAD

**Issue by raj835** [microsoft/powerapps-tools#840]
I have installed core components version 1.89 .I found that ,below flows are part of core components which should be part of Governance section instead .
Please check : https://docs.microsoft.com/en-us/power-platform/guidance/coe/governance-components#business-process-flows

Flow :
Power Apps App Approval BPF
Flow Approval BPF
Custom Connector Approval BPF
Chatbot Approval BPF

Why this is so .

**Comment by JeneferM-MSFT** [comment]
Hello, I believe these have migrated in order to make our future work towards supporting Dataverse for Teams easier. 
There should be no impact on you folks for this move though. Please let us know if this is incorrect.

And thanks for using CoE!
