### ISSUE TITLE
[BUG]: Audit Log - Custom Connector - Schema Validation Type Mismatch

### ISSUE THREAD

**Issue by robertcaretta** [microsoft/powerapps-tools#843]
**Describe the bug**
When testing the connector I receive a schema validation warning that states "Property .webhook type mismatch, Expected: object, Actual: string"

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Audit Log Components
 - Version 1.36 from 2021-03-03
 - App or Flow: Custom connector "Office 365 Management API"

**To Reproduce**
1. Go to Custom Connectors
2. Edit 'Office 365 Management API'
3. Go to Test screen
4. Select Operation 5 Start Subscription
5. Fill in the required information for "tenant", "PublisherIdentifier"
6. Click "Test operation"

**Expected behavior**
Schema should validate without warnings or errors.

**Screenshots**
![SchemaValidation](https://user-images.githubusercontent.com/1613085/111383621-7741dc80-8676-11eb-89d0-55b9e0140938.png)

**Additional context**
Unknown if this will impact the associated flow setup [documented here](https://docs.microsoft.com/en-gb/power-platform/guidance/coe/setup-auditlog#create-an-azure-ad-app-registration-for-the-office-365-management-api).

**Comment by manuelap-msft** [comment]
Hello,

as you got a 200 OK response back from the request, this should not impact the flow setup. Please let us know if you experience otherwise.

Thank you
Manuela

**Comment by robertcaretta** [comment]
Seems to be okay. We were able to get the 2 flows running, however we had a rough time getting the environment DLP set up.  Found this document in another ticket "Custom.Connector.into.DLP.pdf".  We struggled also with the ConnectorID info.

**Comment by manuelap-msft** [comment]
Thanks for letting us know! The product investments rolling out in the next month will make it easier to work with custom connectors and DLP policies: https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-platform-governance-administration/data-loss-prevention-enhancements-manage-custom-connectors-seamlessly-at-tenant-environment-level

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
