### ISSUE TITLE
Unable to get output of a powerapps powershell command

### ISSUE THREAD

**Issue by rajaug3** [microsoft/powerapps-tools#844]
Following https://docs.microsoft.com/en-us/powershell/module/microsoft.powerapps.administration.powershell/add-powerappsaccount?view=pa-ps-latest link and able to connect powerapps environment through SPN/certificate. But unable to get output when run get-adminflow command. I need suggestion

**Comment by manuelap-msft** [comment]
Hello! We do not support the PowerShell cmdlets via this GitHub. Please raise a support ticket for your query.
