### ISSUE TITLE
[PRODUCT BUG]: App not found

### ISSUE THREAD

**Issue by lcimon** [microsoft/powerapps-tools#845]
**Describe the bug**
Admin | Sync Template v3 (Apps) on few apps. Those are found by **_Get Apps as Admin_** action and later not found by **_Get App Role Assignments as Admin Editted_** action in the same run (ie. same environment/app names).

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.98
 - Flow Admin | Sync Template v3 (Apps)

**Additional context**
I created a separate flow to understand this behavior.
I found out that if I use the action **_Get Apps as Admin_** with pagination my app is found. However, for the same app, with **_Get App Role Assignments as Admin Editted_** & **_Get App as Admin_** throw an error (respectively _ApplicationNotFound_ and _The response is not in a JSON format._).

I tested with API version 2020-07-01 and 2016-11-01: same result. I have the same behavior with powershell cmdlet.
So I suppose it is a product issue.

![image](https://user-images.githubusercontent.com/22662809/111447272-8f186f80-870d-11eb-9c09-2624c899713d.png)
![image](https://user-images.githubusercontent.com/22662809/111447316-9dff2200-870d-11eb-8244-fb684d58f10e.png)

**Comment by manuelap-msft** [comment]
Hello,

yes, this is a product issue - could you please raise a support ticket for this?

We have noticed this some time ago, and the team is aware of this issue - when we had this in our tenant, it was to do with apps being deleted from within solutions, which didn't set the correct flags in the background for the Get Apps as Admin call. There's a clean-up in the background the support team can run that tidies this up for your tenant.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Closing out issues with no action required from the CoE team.
