### ISSUE TITLE
Clean up- Admin  Sync Template V3 check deleted

### ISSUE THREAD

**Issue by raj835** [microsoft/powerapps-tools#847]
![CheckDeleted1](https://user-images.githubusercontent.com/66004078/111599142-fad60780-87f5-11eb-96ee-d71bb79d87ff.PNG)

We were getting performance issue on this flow .
We turned this OFF ,but the flow still shows as running .

We raised a case with Microsoft ,they mentioned that this a bug in CoE kit .

Could you please let us know  .

**Comment by manuelap-msft** [comment]
Hello,

due to heavy lifting some of these flows do, for larger tenants these flows will require a Per Flow plan assigned to complete in a timely fashion. 

Thank you for using the CoE,
Manuela

**Comment by JeneferM-MSFT** [comment]
You can open the flow run (by clicking on the time stamp) and cancel it if you would like. 
And for more information on Manuela's suggestion please see our documentation on [long running flows](https://docs.microsoft.com/power-platform/guidance/coe/limitations#long-running-flows) in our limitations documentation.
