### ISSUE TITLE
[BUG]: Developer Compliance Center query

### ISSUE THREAD

**Issue by tkudya** [microsoft/powerapps-tools#849]
I have the Governance Kit installed but when i launch the  Developer Compliance Center, I can only see applications from my own COE Starter Kit, so i can Canvas Apps, Model Driven Apps, Flows, Custom Conenctors. I can't anything else from another environments.  Is this how its meant to be? 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Audit Compoenents
 - Version 1_4_3

**Expected behavior**
I was expecting to see all the applications in there from different environments

**Additional context**
I have ran the Sync Audit Logs, Core Components flows within the past hour and it still hasn't updated. they have all run successfully expect for one. 
![image](https://user-images.githubusercontent.com/78653328/111624047-184da600-87e3-11eb-85ee-d55370967a49.png)
![image](https://user-images.githubusercontent.com/78653328/111624080-226fa480-87e3-11eb-83a2-dec4f5ffbb34.png)
![image](https://user-images.githubusercontent.com/78653328/111624104-2dc2d000-87e3-11eb-886e-fa78d820dfb7.png)
![image](https://user-images.githubusercontent.com/78653328/111624156-3b785580-87e3-11eb-9294-2c30dfe6b6a0.png)

**Comment by manuelap-msft** [comment]
Hello,

the Developer Compliance Center is a Maker facing app, it will only show you your own apps and flows - not all apps in the tenant. Are you seeing all your own apps from different environments, or only from one environment?

Could you please raise a separate ticket for the other issue, thank you.

Thank you
Manuela

**Comment by tkudya** [comment]
Hi Manuela, 

I am only see the apps from one environment which is the only one I have created Apps. makes sense it will try in different  environment

**Comment by manuelap-msft** [comment]
Great, thank you! As this is expected behaviour, I will close this issue now.
