### ISSUE TITLE
 DeploySPLists is creating lists but not columns

### ISSUE THREAD

**Issue by Rhyneaux** [microsoft/powerapps-tools#85]
**Describe the bug**
When I run the DeploySPLists flow it runs successfully and creates the lists, however when opening the lists in SharePoint all of the CI_***** lists they do not contain any columns other than "title".

**Expected behavior**
I was expecting in the CI_configAdminSetup and other lists to populate columns for which the Admin app can submit data.

**Screenshots**
![image](https://user-images.githubusercontent.com/57495922/76129691-a63a6280-5fcd-11ea-87ba-eafa7026e9ab.png)
![image](https://user-images.githubusercontent.com/57495922/76129741-ce29c600-5fcd-11ea-8930-211ea0f6d8b5.png)

**Interface(please complete the following information):**
 - Browser  - Chrome 
 - Build - 80.0.3987.122 (Official Build) (32-bit)

**Additional context**
n/a

**Comment by devwheel** [comment]
you might look at modify the view - I thought this first as well - you can add the fields to the view

**Comment by Snowfox05** [comment]
As above, open the list and select **"Edit Current view"** from the **"All item"** menu.
I have added the following columns to my view.

![image](https://user-images.githubusercontent.com/13246004/76162022-32df4f00-618d-11ea-88e4-b20da57531ff.png)

**Comment by Rhyneaux** [comment]
Thank you, simple!
