### ISSUE TITLE
[BUG]: CoE Power BI dashboard does not reflect Flow connections 

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/powerapps-tools#854]
**CoE Power BI dashboard does not reflect Flow connections**

Solution - Core
Version - 1.98

The article https://docs.microsoft.com/en-us/power-platform/guidance/coe/power-bi-monitor#connections shows that the CoE Power BI dashboard displays both the Power Apps and Flows connections. 

![image](https://user-images.githubusercontent.com/69908205/111759975-33dcad80-88c4-11eb-939f-1a3abba67ead.png)

However, we configured the BI dashboard and it only shows us the App connections: 

![image](https://user-images.githubusercontent.com/69908205/111760189-6f777780-88c4-11eb-9745-8a4139f825c6.png)

**Comment by manuelap-msft** [comment]
Hello,

see #627, we had to remove Flow connections due to some issues with the Power BI Data model. We will update the screenshot in docs with our  next release.

Thank you
Manuela

**Comment by apoorvakasbekar** [comment]
Is there a work around to see the Flow connections instead of going to 'Connectors' in the 'Power Platform Admin view' app and checking each connector individually for Flows using the specific connector?

**Comment by manuelap-msft** [comment]
Not at this time, no.

**Comment by apoorvakasbekar** [comment]
Alright, thank you for your assistance and prompt response. Appreciate it. 

Have a pleasant day ahead 👍🏼
