### ISSUE TITLE
[BUG]: DLP Editor V2 not showing any impacted flows / apps

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#856]
**Describe the bug**
When using the DLP Editor V2 canvas app to determine impact of DLP policy, no apps or flows are showing as impacted even though they should.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - Version 1.98
 - DLP Editor V2

**To Reproduce**
1. Create a DLP policy with Common Data Service connectors in Business Data, non blockable connectors in Non Business Data and all other connectors in Blocked
2. Launch the DLP Editor V2 canvas app
3. Navigate to Impact Analysis
4. No flows or apps are shown as impacted and no connectors show in business data, non business data or blocked 

**Expected behavior**
As I have installed the CoE toolkit with apps and flows using connectors such as Power Automate for Admins, etc., the impacted flows and apps should be seen.

**Screenshots**
Added document
[DLP Editor V2.docx](https://github.com/microsoft/powerapps-tools/files/6170550/DLP.Editor.V2.docx)

**Additional context**
N/A

**Comment by manuelap-msft** [comment]
Hello,

the DLP Editor depends on apps and flows being present in the PowerApps App and Flow table of the CoE Starter Kit solution, can you confirm you have run all the sync flows and the apps you are expected to see under impacted show up in those tables?

Thank you
Manuela

**Comment by marcster** [comment]
Hi,

  All sync flows were run and the apps and flows expected show up in the tables. 

Thanks.

**Comment by JeneferM-MSFT** [comment]
Do you only repro for DLP policies involving CDS Connector? It's treated differently in the background and so wonder if you found that edge case.

**Comment by manuelap-msft** [comment]
Fixed locally for the next release.

**Comment by marcster** [comment]
Thanks look forward to using it in the next release.

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!

**Comment by Sulomania** [comment]
Hello Manuela,
we are tying to see the impacted apps and flows when blocking the SQL Connector with the DLP Editor V2. 
We received a result of some impacted apps and flows. We compared the results with CoE Dashboard and see a difference. 
Within the CoE Dashboard we can see more impacted apps/flows. Is there a reason for the difference?

**Comment by manuelap-msft** [comment]
@Sulomania this repo is no longer used for the CoE Starter Kit, please raise a new issue in the dedicated CoE Starter Kit repo: https://github.com/microsoft/coe-starter-kit/issues
