### ISSUE TITLE
[BUG]: Spelling and Grammar Issues in Innovation Backlog App

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#857]
**Describe the bug**
Spelling and grammatical queries in Innovation Backlog Canvas App

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Innovation Backlog
 - Version 1.17
 - Innovation Backlog Canvas App

**To Reproduce**
1. Launch Innovation Backlog Canvas App
2. Go to the Measure ROI page and add time
3. Go to the Complexity Score page

**Expected behavior**
For 2, Whose time rather than Who's time?
For 3
people rather than peoople
Is the data accessible only to the user who created it? rather than Is the data accessible only to the user to created it?

**Screenshots**
Document attached
[Innovation Backlog.docx](https://github.com/microsoft/powerapps-tools/files/6170715/Innovation.Backlog.docx)

**Additional context**
N/A

**Comment by JeneferM-MSFT** [comment]
Can you please share screenshots so we know where you have spotted these?

**Comment by marcster** [comment]
Hi, screenshots are within the document which has been attached  to the issue already.

**Comment by JeneferM-MSFT** [comment]
Can you please paste them within GitHub so they appear directly? We avoid opening attachments.

**Comment by marcster** [comment]
This is strange as there is no mention of this as the form says we can attach files.

![image](https://user-images.githubusercontent.com/1025102/111820189-1cf48600-88d9-11eb-946d-12771506025c.png)

![image](https://user-images.githubusercontent.com/1025102/111820211-2251d080-88d9-11eb-8221-7325bfe44249.png)

**Comment by JeneferM-MSFT** [comment]
Blocked from fixing by the bug described in #879 .

**Comment by JeneferM-MSFT** [comment]
Alright, we have a workaround to the product bug and can release with these fixes. Marking local fixed.

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
