### ISSUE TITLE
Core component variables are not prompted during import

### ISSUE THREAD

**Issue by petepuu** [microsoft/powerapps-tools#858]
I have noticed that some version of CoE does not prompt admin email and power platform environment variables during the import. I've been testing using 1.98 version downloaded when it was released and that prompts the variables but now downloaded again the same version and there it is not possible to set variables during import. Is this some

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 1.98
 

1.98 downloaded on 19th of March
![image](https://user-images.githubusercontent.com/8307644/111775479-7baa0780-88b9-11eb-94c0-d9e1e9c10667.png)

1.98 download on 3rd of March
![image](https://user-images.githubusercontent.com/8307644/111775083-f6265780-88b8-11eb-9095-99e0682f8c93.png)

![image](https://user-images.githubusercontent.com/8307644/111775214-22da6f00-88b9-11eb-8259-34620f7b6794.png)

**Comment by manuelap-msft** [comment]
Hello,

it looks like we accidentally shipped this version with some of our Default values, which means you won't get prompted from them during import. You can update them after import via the Default solution in the environment, see: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables

Thank you for raising this, we'll make sure to tidy our default values before shipping the next version!
Manuela

**Comment by JeneferM-MSFT** [comment]
We have introduced a staging environment in our ship cycle to make sure this doesnt happen again. Marking as local fixed as a result.

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
