### ISSUE TITLE
[BUG]: "Admin | Sync Audit Logs - 2" - Access is denied due to invalid credentials

### ISSUE THREAD

**Issue by apoorvakasbekar** [microsoft/powerapps-tools#859]
**Describe the bug**

Solution - Core
Version - 1.98
Flow - Admin | Sync Audit Logs - 2

![image](https://user-images.githubusercontent.com/69908205/111776927-9c358a00-88d8-11eb-93cc-623d15d49a6c.png)

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

The custom connector connection is ok, and so are the connections in the Flow. The user I am using does have View-only and Audit logs permission applied through Exchange online.

**Comment by manuelap-msft** [comment]
Hello,

when you navigate to **https://protection.office.com/,** can you see the Audit Log there?

Thank you
Manuela

**Comment by apoorvakasbekar** [comment]
Yes I can 

![image](https://user-images.githubusercontent.com/69908205/111780741-cb9ac580-88dd-11eb-8711-0aefefe3bc78.png)

**Comment by JeneferM-MSFT** [comment]
Can you confirm that you got a success when you started the subscription? [start a subscription to audit log content](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#start-a-subscription-to-audit-log-content)

Can you confirm that you updated the tenant id and set up the child flow to run via the service principle as described in [setup the power automate flow](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow)?

**Comment by apoorvakasbekar** [comment]
I have the used Option 2

**Comment by manuelap-msft** [comment]
Do you have MFA enabled on your account?

**Comment by apoorvakasbekar** [comment]
Nope

**Comment by JeneferM-MSFT** [comment]
Hello. I just found that there was an AD outage last week that caused some of these connectors to be destroyed. 
On my test tenant I had to go and redo some of the setup as the connection on the security table was no longer present. Please redo this part: [setup the custom connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector)

**Comment by JeneferM-MSFT** [comment]
closing out since this was a product issue and now resolved.

**Comment by apoorvakasbekar** [comment]
Since I am using Option 2, I have installed a Custom Connector like mentioned in the article below: 

https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#option-2-connect-to-the-audit-log-by-using-basic-authentication

**Comment by JeneferM-MSFT** [comment]
And now if you hit Edit for the child flow you can select this new connection. Did you do that?

**Comment by apoorvakasbekar** [comment]
Yes, and it gives me the exact same error.

**Comment by manuelap-msft** [comment]
Hello,

there could be other conditional access policies impacting the use of basic authentication for this - "Unauthorized" as an error message is quite clear in that you are not authorized to use this - this could be either due to your access, invalid credentials or conditional access policies - unfortunately, we are unable to know what exactly is causing this error message and would propose you use Option 1 to avoid authorization issues. 

Thank you
Manuela

**Comment by apoorvakasbekar** [comment]
@manuelap-msft can you share the link for the steps to setup using option 1 please.

**Comment by manuelap-msft** [comment]
Hello, our setup instructions have changed quite a bit since a year ago - you can find the audit log setup instructions here: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog
