### ISSUE TITLE
[BUG]: Action 'GetActivitiesByOperation' failed on the

### ISSUE THREAD

**Issue by keharrin** [microsoft/powerapps-tools#860]
**Describe the bug**
Flow fails with the error message below.  My admin has assured me the account has access to audit logs

**Component (please tell us which flow or app you are experiencing issues with):**
 Admin | Sync Audit Logs

**Error Message**
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Did you setup with option 1 or option 2 here? [setup audit logs](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog)

**Comment by keharrin** [comment]
Option 2

**Comment by JeneferM-MSFT** [comment]
Gotcha. Option 2 requires that you have basic authentication and not MFA. Can you confirm that your organization does not use MFA? 

Can you confirm that you got the 200 response from Test Operation in the step to [Install the custom connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#install-the-custom-connector)?

**Comment by keharrin** [comment]
I am using an account that does not have MFA active.  I got a 401 message when running the test

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
<div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
</fieldset></div>
</div>
</body>
</html>

**Comment by JeneferM-MSFT** [comment]
Hello. I just found that there was an AD outage last week that caused some of these connectors to be destroyed. 
On my test tenant I had to go and redo some of the setup as the connection on the security table was no longer present. Please redo this part: [setup the custom connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector)

**Comment by keharrin** [comment]
Is this needed if using Option 2 for setting up audit log data? I am not familiar with the Azure portal and not sure where to find the areas under
Update Azure AD app registration with the redirect URL

**Comment by JeneferM-MSFT** [comment]
Yes, whomever setup the connector for you will need to redo those steps, you'll need to get the secret and such again from the Azure person you worked with. 

Closing out since the issue was a product one.
