### ISSUE TITLE
flag for archival

### ISSUE THREAD

**Issue by remembermicky** [microsoft/powerapps-tools#864]
**Describe the bug**

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid we will need more information here. Can you please 

1) State what solution and version of that solution you are using
1) What issue are you seeing?

**Comment by JeneferM-MSFT** [comment]
closing out issue as its not described.
