### ISSUE TITLE
Apps and flows from default soltuion not available in COE

### ISSUE THREAD

**Issue by abdulsattar121** [microsoft/powerapps-tools#865]
**Describe the bug**
I've installed the COE in an environment, all the environments are listed except the default environment. The starter kit is the most recent one.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Can you confirm if you are running the toolkit with an identity that has the Power Platform Admin role?

**Comment by abdulsattar121** [comment]
Yes, I'm running the COE toolkit with the same Id I used to create the environment. I can see all other environments in the COE except default environment

**Comment by JeneferM-MSFT** [comment]
Sorry I wasn't clear enough. 

Can you validate specifically, do you have admin access to the Default environment? You can determine this by

1) Validating you have the Power Platform Admin role. Note that this is a tenant wide role not an environment role. People without it can create environments. 

1) Browsing to [https://admin.powerplatform.microsoft.com/](https://admin.powerplatform.microsoft.com/) and see if the default environment is listed there.

**Comment by JeneferM-MSFT** [comment]
And please also specify what version of Core you have installed.

**Comment by abdulsattar121** [comment]
Thanks for the clear information, Jennifer. Looks like I don't have admin access to default environment.

**Comment by JeneferM-MSFT** [comment]
Thank you for letting me know!
