### ISSUE TITLE
Follow up on case 847

### ISSUE THREAD

**Issue by raj835** [microsoft/powerapps-tools#867]
We are using PowerApps Plan 2 license .To use per flow license will incur a lot of cost  .Could you please provide me the list of Flows which might require Per Flow license .

**Comment by JeneferM-MSFT** [comment]
This really depends on the tenant shape and the way you use the toolkit I'm afraid. We have only had a few tenants need them and they needed it for this one (Check Deleted)

My recommendation is that you buy the per-flow license, it comes with 5 if I understand correctly, and then you can assign them as your tenant sees a need.
