### ISSUE TITLE
Unable to get owner and users shared details for a PowerAutomate flow

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#868]
How to get owner, co-owner and users with whom a PowerAutomate flow shared using COE toolkit or PowerShell.

**Comment by manuelap-msft** [comment]
This information is currently not available in the Management Connector or Cmdlets. You can raise this as an idea in the User Voice https://powerusers.microsoft.com/t5/Power-Automate-Ideas/idb-p/MPAIdeas

Thank you
Manuela
