### ISSUE TITLE
CLEANUP - Admin | Sync Template v3 (Check Deleted)

### ISSUE THREAD

**Issue by raj835** [microsoft/powerapps-tools#869]
Hello ,
We were having performance issue on this flow ,we raised a ticket with Microsoft Team to check  .
Microsoft has updated us that there is bug/known issue  with this flow and gitHub team is already working on it .

Also ,I see only one Run history for this flow   but it has ran successfully  earlier  and had many entries in Run history .Microsoft is saying this is also a bug .

Can you please confirm me about this Bug reported .If yes ,do we have the fix applied   ?

How can i apply the fix in my environment ,do i need to reinstall the whole package ?

**Comment by JeneferM-MSFT** [comment]
I am unaware of any product fixes you can apply. But I do know that this is one of our long running flows and sometimes requires a per-flow license for large tenants. Please see [long running flows](https://docs.microsoft.com/power-platform/guidance/coe/limitations#long-running-flows)

Note also that for this particular long running flow, there is an environment variable that might help streamline. If you set **Also Delete From CoE** to **yes**, then there are a set of steps that wont run (they will run once more after you change the setting)

**Comment by JeneferM-MSFT** [comment]
Closing out as there is no toolkit work here.
