### ISSUE TITLE
[BUG]: Permissions prompt

### ISSUE THREAD

**Issue by ashrafuddinsyed** [microsoft/powerapps-tools#870]
**Describe the bug**
While browsing the cloud flow and cloud app, it prompts for permissions every time. Need to get rid of the permissions prompt.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : Core
 - Version : 1.89
 - App - Admin - Access this App ; Admin - Access this Flow

**To Reproduce**

This comes after all the instructions are followed

**Expected behavior**
Not sure, but ideally it keeps prompting for permissions every time we load the PowerBI report

**Screenshots**
Attached COE1 on this issue
![COE1](https://user-images.githubusercontent.com/81230889/112156188-036e7980-8c0c-11eb-8715-5924051ec123.PNG)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

this may be do to conditional access policies or your internal setup - but has nothing to do with the CoE Starter Kit itself. If you feel this is a bug, please go through your regular support channels to raise this.

Thank you
Manuela

**Comment by ashrafuddinsyed** [comment]
Thanks Manuela.

I did go through regular support channel and they advised me to raise the issue on this forum.

FYI, this is a test tenant without any policies enforced on it.

Thanks.


Regards,
Syed Ashrafuddin.

**Comment by manuelap-msft** [comment]
Thank you. However, the Power BI report is just published using standard parts of the Power Platform. There is nothing different done here that should prompt you for credentials.

**Comment by ashrafuddinsyed** [comment]
Thanks. I'll take it up with the support team.



Regards,
Syed Ashrafuddin.

**Comment by ashrafuddinsyed** [comment]
Hi Manuela,

Is this related to the canvas app which has in-built conditional access to grant permissions to the users or is this related to PowerBI dashboard which is not supporting these permissions/access when embed in the tile and its revoking the already granted access? Also we have identified that once the access is granted in canvas app, it works as expected and the access is stable. However, it is revoking the granted access when embed in the PowerBI dashboard tile.

Could you kindly provide me suggestions on how to fix this or reach out the right Microsoft support team?

Thanks.
