### ISSUE TITLE
Power Platform Admin View/ App

### ISSUE THREAD

**Issue by kast2L** [microsoft/powerapps-tools#872]
I am attempting to reassign or make myself an owner of a Flow via the App and it appears like it is working but then I check and I do not see it underneath my shared with me flows or underneath cloud flows. Did I miss something during installation possibly?

**Comment by manuelap-msft** [comment]
Hello,

could you provide some screenshots of what you are doing? There is no functionality in the Power Platform Admin View app to re-assign or change ownership, it only supports viewing the existing inventory.

Thank you for using the CoE
Manuela

**Comment by kast2L** [comment]
[image: image.png]

**Comment by kast2L** [comment]
![image](https://user-images.githubusercontent.com/79542230/112367063-b5eb1e80-8c96-11eb-8236-37d0c0302744.png)

**Comment by kast2L** [comment]
here is another
![image](https://user-images.githubusercontent.com/79542230/112368623-85a47f80-8c98-11eb-9a13-6952ae89594c.png)

**Comment by JeneferM-MSFT** [comment]
Hello. That is the product's UX and not ours and references the record in the Dataverse, not the flow. 
In other words, you are there assigning rights to that record in the Dataverse. Not the flow itself. 


The tools we provide for assigning permissions are the Set Permissions apps in Core. 
![image](https://user-images.githubusercontent.com/62659043/112483119-f8176d00-8d35-11eb-8d16-12570f13a9f4.png)

**Comment by JeneferM-MSFT** [comment]
Thanks for using CoE
