### ISSUE TITLE
Audit Logs in the CoE Starter Kit are not aligned with the real Power Platform usage 

### ISSUE THREAD

**Issue by JMM-CDS** [microsoft/powerapps-tools#873]
Hello Expert,

We are currently using the CoE Starter Kit to track & monitor all the Power Platform initiatives across the whole organization (major road and railroad construction company). We have identified an issue with the Kit, and the classic Microsoft Support redirected us to this stream to have some help. Please find issue details below:

Details:
We have noticed that the Log data inserted in the kit is not aligned with the real usage (not complete). As an example, we are using a “DARCInventory” Canvas Application shared with end users to provide them the ability to perform spare parts inventories on the field. Each user needs to connect to this Canvas App and perform the inventory (technically a line is added in an Azure SQL (action + user name) and please note that it is not possible to add any line other than using the Canvas app).

By making a simple extraction of the Azure SQL (real usage), we noticed that the result is completely different compared to the data inserted in the Kit:
![2021-03-25_09h17_25](https://user-images.githubusercontent.com/81332119/112440778-fc9a5080-8d4a-11eb-966f-ac4a8ebff630.png)

The difference between the two datasets is huge which is not normal since we did not notice any issue on the synchronization flows linked to Power Apps usage (included in the Starter Kit Package):
•	Admin | Sync Audit Logs
•	[Child] Admin | Sync Logs

Could you please help us to clearly understand the following points:
•	How the “Office 365 Management API” custom connector is working (the one used to retrieve the Audit Logs)? What kind of data is it retrieving?
•	What is the clear definition of a “Session” and a “Unique User” (the 2 metrics tracked in the Kit)?
•	How could we explain the difference between the real usage and the result in the Kit ?

Please note that this issue is critical for us as we would like to use the CoE Starter Kit as the real Governance tool to track the platform, and for now this situation is blocking us in all our initiatives.

Thanks for your answer.

**Comment by JeneferM-MSFT** [comment]
Hello. The audit logs are just those from the [Office 365 audit logs](https://compliance.microsoft.com/auditlogsearch?viewid=Search) and store things like that the app was launched. It sounds like you are looking for logs on row level entry, is that correct?

**Comment by manuelap-msft** [comment]
Hello,

we retrieve the Audit Logs in chunks (start time to end time) but the connector has a limitation in that it can only return 200 audit events per call. If the specified "chunk" is more than 200 events it will be truncated, which is likely the case for you.

You will have to update the Admin | Sync Audit Logs flow to retrieve the data in smaller chunks. Follow these steps here https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog#set-up-the-power-automate-flow and update the Time Interval to be 1 Hour.

Thank you for using the CoE
Manuela

**Comment by JMM-CDS** [comment]
Hello,
If we understood well, the issue is due to the limit of audit lines that we can retrieve per calls (max is 200). So by decreasing the trigger interval of the flow, we will reduce the risk to reach this limit.
Can you confirm that ?
We are going to test that today and come back to you with the result after one week.
Thanks for your answer,
JMi

**Comment by manuelap-msft** [comment]
Hello,

exactly, if the interval is set to 1 Day, the Audit Log will be retrieved for the past day (2021-03-28 to 2021-03-27) and you may miss audit events due to hitting the limit. If you set the interval to 1 Hour, the Audit Log will be retrieved in hourly chunks (2021-03-28 09:00 to 2021-03-28 10:00) and you are less likely to miss audit events and it should then collect all the information.

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
Closing out issues without follow up on our side. 
Thanks for using CoE
