### ISSUE TITLE
Login Issue creating Connector

### ISSUE THREAD

**Issue by llrowland** [microsoft/powerapps-tools#875]
**Describe the bug**
Creating the Audit Log Connector in GCC-H using App registration.  At stepv4 'test' when creating the 'New Connection'  Receive a error  after entering in account/password

{"error":"invalid_request","error_description":"AADSTS900432: Confidential Client is not supported in Cross Cloud request.\r\nTrace ID: c05501c2-07ed-4689-8cee-6114339a7400\r\nCorrelation ID: 437909bf-9050-460d-ba57-7cd921c0870c\r\nTimestamp: 2021-03-26 11:51:07Z","error_codes":[900432],"timestamp":"2021-03-26 11:51:07Z","trace_id":"c05501c2-07ed-4689-8cee-6114339a7400","correlation_id":"437909bf-9050-460d-ba57-7cd921c0870c"} 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core, Nurture]
 - Version [e.g. 1.98]
 - Custom Connector - Office 365 Management API

**To Reproduce**
1. Edit Custom connector Office 365 Management API
2. On Security tab. Enter in App registration App and Secret and response URL for GCC-H
3. Save connector
4. Click next
5. on Test, Click + New Connection, Ener in GCC-H account info
6. Error occurs

**Expected behavior**
The logon would be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/4930892/112627722-f6b27700-8dff-11eb-925b-a6a4aa5a8925.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid you are experiencing a problem outside of the toolkit with the product itself. Sorry we cannot scale to help with that.

**Comment by llrowland** [comment]
When I contact Premier Support they told me, they don't support the PowerApps COE Tool, go through the GitHub App support.

Is their anything unique to GCC-H that would change how the tool is installed?   Is it expected that the connector should work in GCC-H?

**Comment by JeneferM-MSFT** [comment]
If you talk with them again, let them know that you aren't looking for help with the toolkit, just that you are unable to correctly setup a custom connector. Presumably you would repro with any custom connector. 
There are certain setting for GCC an GCC High when setting up a custom connector. We have listed them in the setup instructions. I presume you already saw those though: [setup the custom connector](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#set-up-the-custom-connector)
