### ISSUE TITLE
[Product BUG]: Innovation Backlog Canvas App Load Toolset Collection Error - Option 2 Install

### ISSUE THREAD

**Issue by remenator** [microsoft/powerapps-tools#879]
At step 19 of the Option 2 set up
I am not able to publish due to an error under section //load toolset. The error is "Multiple levels of many-to-one relationship expansion aren't supported

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution CenterofExcellenceInnovationBacklog_1_17_managed
 - Version 1.17
 - Innovation Backlog

**To Reproduce**
1. Follow steps to install the InnovationBacklog solution using Option 2: install in MS Teams
2. On Step 19 Open Innovation Backlog canvas app and select Publish
3. Look at the canvas app, you will see two errors. select one and select Edit in the formula bar
4. See error under section //load toolset

**Expected behavior**
Based on the instructions I should be able to publish

**Screenshots**
![loadtoolseterror](https://user-images.githubusercontent.com/60788944/112673401-4a39ba80-8e2a-11eb-8cac-ecfb85b597c2.png)
![PublishError](https://user-images.githubusercontent.com/60788944/112673488-63426b80-8e2a-11eb-9c4f-f9d10258b82f.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Thanks for posting. There is a product bug causing this error to pop up even though it doesn't actually block the app from working in the player. I hadn't understood that this blocks installation in Teams though until you posted, so thanks for letting us know. 

We will hold this open even though its a product bug since its so impactful.

**Comment by manuelap-msft** [comment]
Fixed with the current release, shipped today. Thank you for using the CoE!
