### ISSUE TITLE
[BUG]: Admin | Sync Template v3 : Two flows missing connectors

### ISSUE THREAD

**Issue by orauch-a** [microsoft/powerapps-tools#880]
**Describe the bug**
Two flows appear to have missing connectors.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 1.98
 - Flow :
Admin | Sync Template v3 (Connectors)
Admin | Sync Template v3 (PVA)

**To Reproduce**
1. Go to 'Solutions > Center of Excellence - Core Components'
2. Click on either of the impacted flows.
3. Review the screenshots.

I removed all others old solutions before installing the core component 

**Screenshots**
![image](https://user-images.githubusercontent.com/34766578/112861912-89c80700-90b5-11eb-86d6-fef873e61439.png)
![image](https://user-images.githubusercontent.com/34766578/112862054-aa905c80-90b5-11eb-8828-ecf3b9c440a1.png)

**No managed Layers**
![image](https://user-images.githubusercontent.com/34766578/112862562-31453980-90b6-11eb-9d5f-1e7259f9188a.png)

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid I dont repro on install of that build. You can re-create the connections by editing the flow. You will just need to remove the unmanaged layers that are generated (as described in [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)) on upgrade when you install the next version.

**Comment by JeneferM-MSFT** [comment]
closing out issues without next steps on our side.
