### ISSUE TITLE
[BUG]: There is no link to the flow in approval email from "Admin | Archive and Clean Up v2 (Start Approval for Flows)"

### ISSUE THREAD

**Issue by briangre** [microsoft/powerapps-tools#884]
**Describe the bug**
When one receives an approval email stating that a flow has been flagged for archivial (note that is a mis-spelling in the email text) there is no link to the flow in question. In my case the flow was part of a solution and in order to find it I needed to explore every flow to find the one in question. Would it be possible to include a link to these flows for easier location/identification?

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Governance
 - Version: 1.38
 - Flow: Admin | Archive and Clean Up v2 (Start Approval for Flows)

**To Reproduce**
1. have a flow within a solution that doesn't get modified within the specified time frame
2. receive the email from this flow
3. Note that there is no link so you now need to hunt through every solution to find the flow in question

**Expected behavior**
Instead of just having the flow Id in the approval email, it would be nice to have a link to it like we do in other COE emails

**Comment by JeneferM-MSFT** [comment]
I fixed the spelling mistake. Thanks! And I put your suggestion on our backlog. 

Thanks for using CoE!
