### ISSUE TITLE
[BUG]: Error in Add pain points flow in Innovation Backlog 

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/powerapps-tools#885]
I installed the Innovation Backlog solution and when I ran the Add pain points flow I got the error in the screenshot below.

**Problem**
Looks like the flow is corrupt around the name of the Innovation Backlog Pain Points entity in the See if already exists and Create a new record actions. 

**Solution**
I refreshed the Table name parameter in both of those actions and this seemed to fix the issue.

Issue screenshot
![image](https://user-images.githubusercontent.com/41050216/113056641-87c28d00-9208-11eb-8808-3e770d18ac9b.png)

Solution screenshot
![image](https://user-images.githubusercontent.com/41050216/113056663-914bf500-9208-11eb-8636-cc391e1515e7.png)

**Comment by JeneferM-MSFT** [comment]
Interesting. I do not repro this in my installs. I'm glad you were able to resolve it on your side. I'll go ahead and close since you are no longer blocked but will keep this in mind in the event anyone else has the issue. 

Thanks for using CoE!

**Comment by HamishSheild** [comment]
Thanks @JeneferM-MSFT , it was a couple of weeks back when I reported this on the new CoE github site and I was asked to log the issue here.  Might have been resolved in the meantime.
