### ISSUE TITLE
Cannot import the Code Review tool (v1.0.0.9) - "something went wrong. Please try again later"

### ISSUE THREAD

**Issue by spg-iwilson** [microsoft/powerapps-tools#886]
When trying to upload the "Power Apps ArchitectureReview_1_0_0_9.zip" file into Power Apps, it displays the following error:

"Something went wrong. Please try again later"

**Comment by manuelap-msft** [comment]
Hello,

this is a solution file - are you importing under Solutions > Import?

Thank you
Manuela
