### ISSUE TITLE
Difference in number of apps when checked from PowerShell and COE tool

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#889]
We are seeing more number of apps in COE tool when compared to the report for all apps in our default environment, Avanade(PRODUCTION). Below are few examples of apps we see in COE but not in PowerShell report:

91c18836-e0c3-4097-8313-3cc7f90b6f9a -- [LAMA] Catalogue de Formations MVP 2
250a9242-a60b-4317-a882-9623ae40f8ad -- PMT on Growth Market Deal Desk & Financials Team Site forms

Upon checking, check deleted flow is running successfully for this environment. Can you please check on this and let us know what else might be the reason for this inconsistency,

**Comment by JeneferM-MSFT** [comment]
Sorry we cannot diagnose with this information. Can you please check, for both of your examples:
1) What version of Core are you running? 
1) The table has a column called **App Deleted**, can you please see if it's marked as Yes for these two apps?
1) Is the app actually there? You can check by giving yourself permissions in the **Set App Permissions** app and then browsing there.

**Comment by Aparna-Mutalik** [comment]
Hi,

Thanks for your reply. Below are my responses for your questions:

1. Version is 1.98
2. It is marked as FALSE for the above mentioned apps.
3. I tried giving permissions but it says not found. 

I am unbale to find app in Power platform admin center. Please check and let us know if there is any other dependency which needs to be checked for this.

.

**Comment by JeneferM-MSFT** [comment]
It sounds like the app is, in fact, deleted. We cannot do the work to cross reference against the powershell as it has its own peculiarities and we are not product support. 

When you run Check Deleted next, it should mark the app as deleted in the CoE.
