### ISSUE TITLE
[BUG]: CLEANUP - Admin | Sync Template v3 (Connection Status) is failing

### ISSUE THREAD

**Issue by RamitK** [microsoft/powerapps-tools#892]
**Description**
CLEANUP - Admin | Sync Template v3 (Connection Status) is failing with sometimes "App not found" error (which might be because the app got deleted after the sync flow ran) for a few apps and for below error for others (InvalidTemplate. Unable to process template language expressions in action 'Parse_Connection_Ref_JSON' inputs at line '1' and column '54071': 'Required property 'content' expects a value but got null. Path ''.'.):

![image](https://user-images.githubusercontent.com/39703138/113546108-08b6c580-9609-11eb-8aec-a3a01db40f21.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.98
 - App or Flow CLEANUP - Admin | Sync Template v3 (Connection Status)

**Comment by RamitK** [comment]
We tried upgrading the solution (with removing all unmanaged layers) to latest version 1.98, but still the issue is present.

**Comment by JeneferM-MSFT** [comment]
Hello. Connecting this to the duplicate #814

**Comment by JeneferM-MSFT** [comment]
I'm afraid you dont have the latest bits, even though you upgraded. This is what should be in that scope. 
Likely you didn't delete the unmanaged layer from this flow when you did the upgrade, or you are looking at a copy. 
![image](https://user-images.githubusercontent.com/62659043/113579794-068d4080-95e2-11eb-81d7-c708bc51e99c.png)

I'm afraid we cannot help you as the issue you raise here is already addressed.
