### ISSUE TITLE
[Issue]: Set up the audit log connector

### ISSUE THREAD

**Issue by cdt2021** [microsoft/powerapps-tools#893]
I'm attempting to install the "Center of Excellence - Nurture Components" version 1.27 in GCC High.

I'm trying to perform the instructions based on the documentation from the following link.  - https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog 

I'm working with our Corporate IT Office and I'm told the app registration cannot be completed because the app will have access to the entire enterprise.  This is where I need your expertise.  Can this application registration be setup by our corporate IT and limited to the audit logs specific to my business unit?  I believe the biggest concern is corporate thinks I will have access to the logs and my understand from the documentation is the opposite.  The app registration has access but my personal ID does not.  I need to use this feature in order to use and take advantage of the Governance Starter Kit.  I’d prefer that we do not rely on corporate to monitor our applications and enforce policies that I believe my business unit should support.   Please advise.

**Comment by JeneferM-MSFT** [comment]
I'm afraid that the connector cannot filter by org. We are relying on the filtering capabilities of the backend here, Office 365 Audit Logs, and they offer no such filtering capabilities. 

What ever identity installs and runs the flow will need access to the logs. And then the flow will filter down to the logs that are relevant to Power Platform for the entire tenant. 

Without doing audit logs, your biggest miss from the toolkit will be the ability to track app lauches.

I hope that helps.

**Comment by cdt2021** [comment]
Thank you.  I think the question I need answered by our Corporate IT is the level of access.  If the app registration is setup, can I do anything with the API outside of what PowerApps is going to use it for?  I think their biggest concern is my portal ID will have access to the logs and I can do as I see fit.  However that is not the approach I'm looking to implement, I want to implement the app registration approach.  If we put in place the use of an app registration the application will pull what it needs to support and administer PowerApps.  I cannot manipulate anything.  Do I understand this correctly?

**Comment by cdt2021** [comment]
@JeneferM-MSFT can you confirm how the setup of the audit logs work?  Meaning what it does and how it works.  I think I may have enough information to talk to corporate to allow the app registration to be setup.  Along with the description of what the process supports I'm going to provide them with the following.

I’m not requesting personal access to the logs.  I’m requesting that an application have access to the logs in order to support administrative functions of PowerApps/Power Platform.   I will not have access to the underlying PowerApps flow that accesses the logs.  Therefore I cannot freely manipulate or read the logs for information.

**Comment by JeneferM-MSFT** [comment]
I'm afraid the question is rather broad so I'm not sure how to answer. 

There is a custom connector the to the O365 Audit Logs. This connector brings in all of the logs from office and dynamics. We have a flow that uses this custom connector to pull these in. It them filters them down to the Power Platform related ones and then we write them to the CoE's audit log table. 

Any entity/person that has admin access to the CoE environment will be able to view the logs from within office. Any viewer of the resulting reports (ex the Power BI report from CoE) will only see those results surfaced, ex the last time apps were launched.
