### ISSUE TITLE
unable to import SyncAuditLogs.zip

### ISSUE THREAD

**Issue by KSwantnerPPG** [microsoft/powerapps-tools#894]
**Describe the bug**
We are installing the CoE Started Kit core components. We are currently on the step to import the Flow-SyncAuditLogs, however we are running into an error (listed below). We are running into this issue when trying to import Flow-SyncAuditLogs.zip.  This is odd because we created the Office 365  Management Api connector using the account that matches this object ID 'a3627bde-1a0f-42e9-9dff-ccd9e9966341”.

Error message: The caller with object id 'a3627bde-1a0f-42e9-9dff-ccd9e9966341' does not have permission to custom connector 'admin-5foffice-20365-20management-20api-5f5ff1b2d471f32746'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core 
 - Version 1.98
 - App or Flow Flow-SyncAuditLogs.zip

**To Reproduce**
Go to flow.microsoft.com, and set the current environment to the same environment where the CoE solution is installed.

On the left pane, go to the My Flows tab.

Select Import.

Select the Flow-SyncAuditLogs.zip package, and then select Import.

Update the connections by following these steps:

For Admin | Sync Audit Logs, select Create as new, and then select Save.

For the Office 365 Audit Logs connector, Dataverse connection, and Office 365 Audit Logs Connection, select Select during import, and then choose your connection.

Once we do this we get the error below.

**Expected behavior**
We should be able to import this solution without any issues. 

**Screenshots**
Attached

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello audit logs are setup using the audit logs solution and not this zip file. We are removing the zip file this month as it causes confusion. 
Please see [audit log setup](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog#option-1-connect-to-the-audit-log-by-using-an-azure-ad-app-registration)

**Comment by KSwantnerPPG** [comment]
Hello Jenefer,

                The document you provided still tells me to install the zip package.  Is there something else I should install? If so, Can you please provide instructions?


***@***.***D72AF6.C8CCDEF0]


Thanks,
Kevin Swantner
Systems Software Analyst II
Global Application Services - Web
Corporate IT

General Office
1 PPG Place
Pittsburgh, PA, United States 15272
Tel: 412-434-2561
E-Mail: ***@***.******@***.***>
Team: *GAS Web ***@***.***>

[ppg_lg_rgb_email]

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, April 6, 2021 2:49 PM
To: microsoft/powerapps-tools
Cc: Swantner, Kevin; Author
Subject: <EXT>Re: [microsoft/powerapps-tools] unable to import SyncAuditLogs.zip (#894)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hello audit logs are setup using the audit logs solution and not this zip file. We are removing the zip file this month as it causes confusion.
Please see audit log setup<https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.microsoft.com_power-2Dplatform_guidance_coe_setup-2Dauditlog-23option-2D1-2Dconnect-2Dto-2Dthe-2Daudit-2Dlog-2Dby-2Dusing-2Dan-2Dazure-2Dad-2Dapp-2Dregistration&d=DwMCaQ&c=zwPfxOisiRWGoGc9Pq9Wrg&r=uXbwTtGIDHKZ8CIbIP4O_g&m=60zTMpOVxX8YHBJMDdfxLub6n2CLEDy2gBLEEqCvbZc&s=1VV73HYvJDwAbYlPI8rkOtGFBw0AV2yv2b_ouR-AAhQ&e=>

**Comment by JeneferM-MSFT** [comment]
We are removing Option 2. You must follow the steps outlined in Option 1 which instructs you to install the Audit Logs solution for the flows.

**Comment by KSwantnerPPG** [comment]
Jenefer,

                So you are saying that since we did option 1 already we have no need to follow the steps to import the flow template compressed (.zip) package named SyncAuditLogs.zip?

Thanks,
Kevin Swantner
Systems Software Analyst II
Global Application Services - Web
Corporate IT

General Office
1 PPG Place
Pittsburgh, PA, United States 15272
Tel: 412-434-2561
E-Mail: ***@***.******@***.***>
Team: *GAS Web ***@***.***>

[ppg_lg_rgb_email]

From: Jenefer Monroe ***@***.***>
Sent: Tuesday, April 6, 2021 2:50 PM
To: microsoft/powerapps-tools
Cc: Swantner, Kevin; Author
Subject: <EXT>Re: [microsoft/powerapps-tools] unable to import SyncAuditLogs.zip (#894)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


will hold this open to track us removing that zip file in this months release.

**Comment by JeneferM-MSFT** [comment]
You do not need to install those flows, no.
