### ISSUE TITLE
Microsoft PowerApps Code Review - Creating reviews issue

### ISSUE THREAD

**Issue by 19JoaoPereira97** [microsoft/powerapps-tools#895]
Hello,
Our team is starting to work with the Code Review app, however we encountered some errors while creating new reviews. When we try to create a new review with an App ID it gets stuck on processing. Also when we try to create a review with the .msapp file, sometimes it also gets stuck on processing. We tried the unpack locally and it displayed a warning but the unpack was successful. Is this supposed to happen?

It would also be great if we could get an overview of the workflow of the reviews, is that possible?

Thank you for your time.

**Comment by slaouist** [comment]
Hello,  AppID is optional but msapp file is required for the review to work. We will update the tool to reflect this better. if you provide an MSAPP file and the review remains stuck in processing. please get in touch with me directly at mehdis@microsoft.com and we will help debug the issue

**Comment by RajeevPentyala** [comment]
Closing this issue as there was no active conversation from a while. FYI @slaouist
