### ISSUE TITLE
[Feature Request]: UPN vs Mail address - guest users

### ISSUE THREAD

**Issue by ogiraud** [microsoft/powerapps-tools#897]
Hello,

When we tried to filter the app having Guest users in a dedicated view, we experienced an issue because of a strange display around the UPN field:
- in the detail of the PP user is mentioned the mail address as UPN (e.g: name@domain.com)
- whereas the User Principal Name in Azure AD is actually much more longer, with "#EXT#" inside (e.g: name_domain.com#EXT#@tenant.onmicrosoft.com)
(see enclosed picture)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.98
 
**To Reproduce**
1. Go to the app view
2. Click on an app
3. Select a user (e.g. the Owner) in the App Shared With (list)
4. See the User Principal Name field

In Azure AD:
1. Go to AAD
2. Select the same previous user
3. See the User Principal Name field 

**Expected behavior**
having the same value in these 2 UPN fields; hence that the value in the Admin View > ...> User reflects the one existing in AAD

Thanks for your reply
![DisplayNameUPN](https://user-images.githubusercontent.com/81678979/113907375-934c2000-97d5-11eb-8153-3b8d07a57a4a.png)

**Comment by JeneferM-MSFT** [comment]
Is there a different field within Azure that seems like it would be a better fix for these folks?

**Comment by ogiraud** [comment]
yes, aim is to retrieve app/flows shared with guest users; any idea to retrieve this info easily from the admin view / filtered report ?

But I think the best could be fine to have both UPN fields filled with the same value : is this planned in a future release ?

**Comment by JeneferM-MSFT** [comment]
I have added this to our backlog. Thanks for using CoE!

**Comment by ogiraud** [comment]
Hello Jenefer,
I know this thread is closed (and that this project has moved to another location), but can you confirm this enhancement has been taken into account from the backlog in a given release yet ?
Thanks for the precision
