### ISSUE TITLE
Old flow sitting around

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#899]
**Describe the bug**
After Upgrading to 1.98 Core Components I get this error in my inbox - 

Admin   \| Sync Template v2 (Flows) | PowerAppsEnvironment   (Upgrade) | https://emea.flow.microsoft.com/manage/environments/38fb8156-cd30-4127-b92c-916f18deda87/flows/2df2e1da-9a04-4790-88ba-78b0314c60d3/runs/08585837642178814992629799301CU148
-- | -- | --
Admin   \| Sync Template v2 (Flows) | PowerAppsEnvironment   (Upgrade) | https://emea.flow.microsoft.com/manage/environments/38fb8156-cd30-4127-b92c-916f18deda87/flows/2df2e1da-9a04-4790-88ba-78b0314c60d3/runs/08585837642157786238551604758CU246

If I click on the links - I get this error message - The caller with object id '3b756550-4641-468c-9e77-bd03f923f959' does not have permission for connection '2df2e1da-9a04-4790-88ba-78b0314c60d3' under Api 'shared_logicflows'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 1.98
 - App or Flow  Sync Template (v3)

**To Reproduce**
Let Sync Template V3 run.

**Expected behavior**
I dont expect this error

I expected only V3 versions to run.  I cannot find where this (V2) error is coming from.

**Comment by JeneferM-MSFT** [comment]
It appears that you have a copy of an old version of the toolkit or just this flow sitting in your **_PowerAppsEnvironment (Upgrade)_** environment. You can use the Set Flow Permissions app to delete it.

**Comment by JeneferM-MSFT** [comment]
No action for the toolkit so closing out.
