### ISSUE TITLE
Tab control appears to errors

### ISSUE THREAD

**Issue by Jaycee75** [microsoft/powerapps-tools#9]
Tab Control errors both in the standalone component and the component demoapp  -with errors against the table used.
![Capture](https://user-images.githubusercontent.com/49173254/55645641-febb1b80-57d0-11e9-934f-e86c8a122674.PNG)

**Comment by pingunet** [comment]
I have exactly the same issue. Any tip on how to solve it?

**Comment by devinprejean** [comment]
Is this still occurring for you? I downloaded today and don't see any squiggly lines showing now.
