### ISSUE TITLE
[BUG]: issue title Just tried to Upload v2_0 of Core Components and got different Environment Variables not in the Documentatron

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#900]
**Describe the bug**
Importing Core Components v2_0 - I gett these environment variable 👎 
![image](https://user-images.githubusercontent.com/8484048/114033688-60f1ff80-9875-11eb-81bd-fa02a8975e62.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - SolutionCore
 - Version 2.0
 - N/A 

**To Reproduce**
download V2_9 of Core Components and try and Import Solution

**Expected behavior**
I did not expect thse envioronment variables - I could not find them in the docs.microsoft.com documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/114033901-98f94280-9875-11eb-8771-b6e3d8feadd9.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello!

We released version 2.0 today just a few minutes ago, but the docs are still pending docs approval - once they're live the Environment Variables will be accurately documented there. It's hard timing it all to go live at the same time, but docs update should happen today.

Thank you
Manuela

**Comment by manuelap-msft** [comment]
The docs have now been updated
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components

**Comment by NPrice99** [comment]
Hi Manuela

I don’t think so.

***@***.***D72C9E.2E83E650]
Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
It is live for us at least. Here is the description of the env vars from the document
![image](https://user-images.githubusercontent.com/62659043/114065225-a7d0fc80-9857-11eb-87f4-17681a75ce1a.png)
