### ISSUE TITLE
Best way to cleanup flows in an environment

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#903]
We have many flows in an environment and we are planning to cleanup those. Can someone suggest best approach to do that.

**Comment by manuelap-msft** [comment]
Hello!

Can you please ask this question in the Power Automate Community 
https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity

In this GitHub, we only support solutions released by our team but aren't able to help with more general questions.

Thank you
Manuela
