### ISSUE TITLE
Enquiry on Check deleted flow

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powerapps-tools#904]
**Describe the bug**
In our environment we have divide the check deleted flow into different environments.

Can you let us know in which step in **check delete flow** the delete operation is performed.

If **check deleted flow**  there is not delete operation only it will mark as deleted , thwn which the orther flow in COE which deletes the data from COE.

And how do we validate if the check deleted flow is update the details correctly , post the flow has run successfully

**Comment by JeneferM-MSFT** [comment]
Hello I'm afraid we cannot scale to assisting people with customizations. However I can point you to the area for this one as its pretty clear. Basically there is a scope at the bottom that does the actual delete, though the variables used are above in the flow so you will need to explore to find those. 

![image](https://user-images.githubusercontent.com/62659043/114054550-32f8c500-984d-11eb-9804-745762e6b394.png)


Be careful with the configure-run-after properties when splitting.
Also note that if they are actually in different environments (vs solutions or flows) then by default they wont be interacting with the same data.
