### ISSUE TITLE
Power BI April Template data loading Error

### ISSUE THREAD

**Issue by AkashPatel136** [microsoft/powerapps-tools#908]
**Describe the bug**
Data loading error on 2021-04-08 version. 

![image](https://user-images.githubusercontent.com/75992078/114116187-32464a00-98b2-11eb-9568-2b9641ad6976.png)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version [e.g. 1.29]
 - App or Flow [e.g. Sync Template (v2)]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Can you please let me know
1. Did you update your Core solution with the update already? (V2.0)
2. When you entered the URL, did you ensure you removed beginning and ending slashes?
    Note that this is a change from how you used to enter it. 
    so if your URL is **_https://mycoe.crm.dynamics.com/_** you need to enter as **_mycoe.crm.dynamics.com_**

**Comment by AkashPatel136** [comment]
Yes I did upgrade core to 2.0 and I did remove the prefix and slash in the end.

Thank You,
Akash Patel
________________________________
From: Jenefer Monroe ***@***.***>
Sent: Thursday, April 8, 2021 10:10:16 PM
To: microsoft/powerapps-tools ***@***.***>
Cc: Patel, Akash ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [microsoft/powerapps-tools] Power BI April Template data loading Error (#908)


External email. Confirm links and attachments before opening.


Can you please let me know

  1.  Did you update your Core solution with the update already? (V2.0)
  2.  When you entered the URL, did you ensure you removed beginning and ending slashes?
Note that this is a change from how you used to enter it.
so if your URL is https://mycoe.crm.dynamics.com/<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmycoe.crm.dynamics.com%2F&data=04%7C01%7Cakash.patel1%40chemours.com%7C6af7a6179b9a44e9e9e908d8fafc9e3c%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637535310206322387%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0pggMlx0hBRo62uCOqYq9oHJ61rvU9Y9Q4j95VC3h2Y%3D&reserved=0> you need to enter as mycoe.crm.dynamics.com

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fpowerapps-tools%2Fissues%2F908%23issuecomment-816350595&data=04%7C01%7Cakash.patel1%40chemours.com%7C6af7a6179b9a44e9e9e908d8fafc9e3c%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637535310206332378%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4GtHuiVRYAE6LvspuZ%2FgG6%2FWDzMvafdN59Sbv%2FQ9910%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASDYYDTBA23NZTYZNFKXTJ3THZOYRANCNFSM42T74NXA&data=04%7C01%7Cakash.patel1%40chemours.com%7C6af7a6179b9a44e9e9e908d8fafc9e3c%7C68a7ff20812f473890ea0b1051846f74%7C0%7C0%7C637535310206332378%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=J%2FaWFMmxuUnrm%2FiB00NKN7RTDWzkkbC76Z7K5NdMXP0%3D&reserved=0>.

This communication is for use by the intended recipient and contains information that may be privileged, confidential or copyrighted under applicable law. If you are not the intended recipient, you are hereby formally notified that any use, copying or distribution of this e-mail, in whole or in part, is strictly prohibited. Please notify the sender by return e-mail and delete this e-mail from your system. Unless explicitly and conspicuously designated as "E-Contract Intended”, this e-mail does not constitute a contract offer, a contract amendment, or an acceptance of a contract offer. This e-mail does not constitute a consent to the use of sender's contact information for direct marketing purposes or for transfers of data to third parties.


https://www.chemours.com/en/email-disclaimer

**Comment by JeneferM-MSFT** [comment]
We are not Power BI team members so we cannot advise deeply, but a quick internet search of this sting **_power bi references other queries or steps_** led me to some suggestions around privacy settings you may need to play with. 

With the change to use the PBI Direct Query feature, this may surface a few things like that for people. 

I have my privacy setting at **_Combine data according to each file's Privacy Level settings_** and it is working for me.

**Comment by AkashPatel136** [comment]
Hi Jenefer, 

My Privacy level is set to Combine data according to each files.

![image](https://user-images.githubusercontent.com/75992078/114201311-0cf22400-9924-11eb-83a1-61cdad4458a4.png)

**Comment by JeneferM-MSFT** [comment]
From reading online, you will need to play around with these privacy settings in order to resolve this.

**Comment by AkashPatel136** [comment]
Had to clear out my previous attempt to dataverse connection and tried again it worked.

**Comment by JeneferM-MSFT** [comment]
Wonderful news!
