### ISSUE TITLE
[BUG]: issue - Import of V2.0 of Core Components failed

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#911]
**Describe the bug**
An Import of V2.0 of the Core components failed - 
[Unconfirmed 76047.txt](https://github.com/microsoft/powerapps-tools/files/6284518/Unconfirmed.76047.txt)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 2.0
 - Solution

**To Reproduce**
Download V2.0 of Core Components 
Navigate to Solutions on Make.PowerApps.com
Select Solutions
Select Import
Navigate to downloaded solution and press OK

**Expected behavior**
I expected the Solution to Import

**Screenshots**
See above output

**Additional context**

**Comment by NPrice99** [comment]
v1.98 was already Installed

**Comment by NPrice99** [comment]
I retried and got this - Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

**Comment by JeneferM-MSFT** [comment]
Hello. This import from 1.98 is working for most people so you likely hit a product issue. 
Note also that the first text you shared references the audit logs solution in it, not sure why. 

Please also tell us, are you using the modern import and leaving it as Upgrade as shown here? 
![image](https://user-images.githubusercontent.com/62659043/114184179-c4297380-9901-11eb-8f06-177cf9b96aef.png)

**Comment by NPrice99** [comment]
Hi Jenefer 
As a result of the previous issue, I decided to install v2.0 of the core components.

THis is when I hit the current issue.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
Oh i see. So the text document is your notes. 

Can you please let us know if you are following the path shown in the image for upgrade?

**Comment by NPrice99** [comment]
Hi Jenefer
![image](https://user-images.githubusercontent.com/8484048/114189891-9b759e00-9942-11eb-849a-736a5d755ff6.png)

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
Thanks. You seem to have hit a product issue then. I suggest you try again in a little while, sometimes there are service issues when you attempt to upgrade. And if that doesnt work you will have to contact support.

**Comment by NPrice99** [comment]
Hi Jenefer

I have tried three or four times and all fail.  I can import other solutions so I suspect it is not a product issue, but the way the CoE solution has been built.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
Other users have upgraded successfully. If you share the full error you received I may see something else, but with the information above I cannot help further I'm afraid.

**Comment by NPrice99** [comment]
Hi Jenefer 

The full error text is in the file Unconfirmed 76047.txt at the start of this thread.

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
per your notes that has several steps in it yes? since there are notes about audit logs involved?

**Comment by JeneferM-MSFT** [comment]
Please share just the error download from the failure to upgrade. and if I can see something there to help I will try.

**Comment by NPrice99** [comment]
Hi Jenefer
There is nothing there about audit logs - ***@***.***D72D53.0EEA2380]



Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
perhaps you shared the wrong file accidently. 
![image](https://user-images.githubusercontent.com/62659043/114193544-e0321280-990b-11eb-8e9b-d0e069f6034e.png)

**Comment by JeneferM-MSFT** [comment]
Oh you are sharing an xl file's xml? Not sure but I'm afraid I cannot assist here further. 
If others see the same issue as you we may be able to see a pattern and help. 
You will need to try to reach out to support.
