### ISSUE TITLE
[BUG]: issue I think the year is wrong here in PowerApps Adoption Deep Dive / PowerApps Premium MAU Over Time

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#912]
**Describe the bug**
PowerApps Adoption Deep Dive Screen - bottom right hand corner graph has the wrong year on it 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Core, Nurture]
 - Version 1.71.5
 - App

**To Reproduce**
1. Go to PowerApps Adoption Deep Dive screen
2. See error in bottom right hand corner

**Expected behavior**
I thik the year should be 2020 not 2021

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/114162710-45dcc980-9921-11eb-8ea4-4495bfdd96c9.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
I don't repro this for 2020 data. Can you please go look at your Audit Log data itself to see how the date is presenting there?

**Comment by NPrice99** [comment]
Hi Jenefer 
I have just checked and it is still the same graphic with the same x axis.
The format of the date in the Audit logs is 2021-04-19T11:22:23
Regards
Nigel

**Comment by JeneferM-MSFT** [comment]
Hi Nigel. Sorry I wasn't clear. I'm not asking for the format of the date, I'm asking if you can please check the dates themselves from the audit log. I'm wondering if the data is correct there. Meaning your data from September, is it showing as 2020 or 2021 in the table itself.

**Comment by NPrice99** [comment]
Hi Jenefer
I have checked the date in the CDS field "Audit Log" and the dates are year = 2021, Quarter= QTR 1, Month = January, Day=1
Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
I'm a little lost here. I'm trying to understand about the data for which you posted this issue, not other data. Do you have data in the audit logs table dated either Sept 2020 or Sept 2021?

**Comment by JeneferM-MSFT** [comment]
closing this out as we dont have a repro.
