### ISSUE TITLE
After uploading COE Core Component, unable to fetch any data within PowerBI Report

### ISSUE THREAD

**Issue by vishal4bhosale** [microsoft/powerapps-tools#914]
**Describe the bug**
 Sorry we dont find any app for any app and everything is blank

**Component (please tell us which flow or app you are experiencing issues with):** : Core Component
 - Solution [e.g. Core, Nurture]: Core Component
 - Version [e.g. 1.29]: 1.98
 - 
**To Reproduce**
I have created new env for  deploying COE starter kit and upload the Core .zip component to it.

After launching Dashboard-PowerPlatformAdminDashboard-2021-02-02, it prompt for Org URL which I have added for COE Env however its unable to fetch any details into PowerBI.

As soon as Power BI gets loaded we cant see any details

 Sorry we dont find any app for any app and everything is blank

**Expected behavior**
Ideally it should load all the Power platform details into PowerBI Reporting.

**Screenshots**

**Comment by vishal4bhosale** [comment]
Describe the bug
A clear and concise description of what the bug is.

Component (please tell us which flow or app you are experiencing issues with):

Solution [e.g. Core, Nurture] Core Component 
Version [e.g. 1.29] 1.98
App or Flow [e.g. Sync Template (v2)] 
To Reproduce
Steps to reproduce the behavior: I have created new env for COE kit and upload the Core .zip component to it
After launching Dashboard-PowerPlatformAdminDashboard-2021-02-02, it prompt for Org URL which I have added for COE Env however its unable to fetch any details into PowerBI.

Getting an error
Sorry we dont find any app for any app and everything is blank

**Comment by JeneferM-MSFT** [comment]
Did you run the sync flows? Please see this note from the [setup instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-powerbi)
![image](https://user-images.githubusercontent.com/62659043/114226117-69f3d700-9930-11eb-8d75-06527719a370.png)

**Comment by vishal4bhosale** [comment]
Thanks a lot for your comment
I did tried to Turn ON them but hitting another error[![image](https://user-images.githubusercontent.com/82226691/114373200-43c17780-9b7a-11eb-92cb-3322636145e8.jpeg)]()

**Comment by vishal4bhosale** [comment]
![image](https://user-images.githubusercontent.com/82226691/114373447-7b302400-9b7a-11eb-8dbb-b7a7cd9b93f7.jpeg)

**Comment by manuelap-msft** [comment]
Hello,

as per our documentation, a premium license (e.g. Power Automate Per User) license is required to run our flows due to action request limits and pagination settings in our flows. You can learn more about Power Automate limits here https://docs.microsoft.com/en-us/power-automate/limits-and-config

All of our flows have pagination policies configured that require a license that falls into the MediumLow1 or above performance profile.

Thank you
Manuela

**Comment by vishal4bhosale** [comment]
Thanks a lot
In the past around Oct-Nov 2020
I did manage to stood up COE kit in our Dev tenant without premium licence
Has it been changed recently

**Comment by manuelap-msft** [comment]
No, the CoE Starter Kit has used premium connectors (like HTTP and Dataverse) from the beginning so always required a premium license. 

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
It used to work with trial versions of the per-user license, and no longer does. That might be where the confusion came in.

**Comment by vishal4bhosale** [comment]
I have assigned relevant licence to it however while activating sync flow's getting below error

failed to activate components flow client error returned with status code forbidden cannot be activated due to admin api policies

**Comment by JeneferM-MSFT** [comment]
That is a DLP violation which is outlined in the [toolkit prereqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites). Please look through the full pre-reqs list before continuing to attempt to setup the toolkit, and then give it a try.
