### ISSUE TITLE
[BUG]: Not able to add the entry in COE Setting table in Dataverse for Teams version

### ISSUE THREAD

**Issue by krishnaVSU2020** [microsoft/powerapps-tools#915]
Hi Team,

I am trying to add the entry for the COE Settings table in the Dataverse Teams COE setup. I want to set only the company name and the rest I want to leave blank. I see the below error:

I see the Version is a read-only and auto-increment number.

**Note:**
In old COE, we use to set this COE setting with the help of the Model-Driven app and in that version number, we need to specify.

**Expected behavior**
I should be able to save a record without any issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/70860420/114290370-30fd5480-9a4d-11eb-813d-eb5a5f715517.png)

**Additional context**
Please advise if I am doing anything wrong here.

Thank You,
Krishna Vandanapu

**Comment by manuelap-msft** [comment]
Hello,

the Version number is an Autonumber - looks like a Product change has thrown in some issues with this type in Dataverse for Teams. 

Please go to Build > Installed Apps > Center of Excellence - Core Components > See All > Tables > Open the CoE Settings Table > Change Version (primary name) to Text from Auto Number > Save Table. And then add data again.
![image](https://user-images.githubusercontent.com/55705669/114361737-664d9380-9b6e-11eb-8362-b139e1d4ca9b.png)

**Comment by manuelap-msft** [comment]
(Keeping open. We will fix this with a bug fix release shortly.)

**Comment by krishnaVSU2020** [comment]
I have managed this with a Cloud-Flow, surprisingly with Cloud flow, I am able to add a record though the datatype is Auto number. Thank you for looking into this Manuela.

**Comment by manuelap-msft** [comment]
Shipped a quick fix release just now that addresses this issue.

**Comment by krishnaVSU2020** [comment]
that was super quick!
