### ISSUE TITLE
[BUG]: Not able to configure Power BI report for COE D4T

### ISSUE THREAD

**Issue by krishnaVSU2020** [microsoft/powerapps-tools#916]
**Describe the bug**
As per the documentation while configuring the Power BI Dashboard we should take the ORGURL of the environment, refer Step-3 on the below article:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#get-the-environment-url

But for D4T environment we can't see the ORGURL itself so how we can associate the env to Power BI Desktop to create the Dashboard.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Configure Power BI Dashboard for D4T
 - BI Dashboard

**Expected behavior**
It will be handy if we explain the process in the documentation for configuring Power BI Dashboard for D4T environment.

**Screenshots**
**Data verse for teams Environment**
![image](https://user-images.githubusercontent.com/70860420/114318195-f7bef600-9ad9-11eb-9ec3-d14f9f8f6bdb.png)

**Regular Environment**
![image](https://user-images.githubusercontent.com/70860420/114318187-e675e980-9ad9-11eb-81bf-0e68bcef9ea0.png)

**Additional context**
Looking forward to see the required help as I need to demo this to my client at the earliest.

**Comment by manuelap-msft** [comment]
You can find the Org Url for Dataverse for Teams environments in the About tab of the Power Apps app in Teams. You first have to select the Build tab and your environment and then select the About tab.

Thanks for using the CoE 
Manuela

**Comment by krishnaVSU2020** [comment]
Thank you a ton for this.

**Comment by krishnaVSU2020** [comment]
Hi Manula,

I was getting this error while configuring the Power BI Report for COE-D4T:
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

Regards,
Krishna Vandanapu

**Comment by manuelap-msft** [comment]
You have to enter the URL without the https:// at the beginning and the trailing / at the end.

**Comment by krishnaVSU2020** [comment]
Tried multiple times but no luck :(

**Comment by krishnaVSU2020** [comment]
By the way, I see the same issue while I configure the BI report with the regular environments also. However, the old version PowerBI report is working as expected with regular environments.

**Comment by manuelap-msft** [comment]
Have you enabled the TDS endpoint on the environment?

**Comment by krishnaVSU2020** [comment]
There is no way I can enable the TDS for D4T environment from the admin center all I could see is:
![image](https://user-images.githubusercontent.com/70860420/114356827-08558780-9b3f-11eb-9693-0bfb6b8c7085.png)
I have also tried by constructing the URL as below:
https://admin.powerplatform.microsoft.com/environments/<ENV-ID>/settings/Features
but no luck

**Comment by krishnaVSU2020** [comment]
I have tried to search for TDS Setting as explained in the below article but no luck :(
http://powerappsguide.com/blog/post/dataverse-setup-tds-for-management-studio-powerbi#:~:text=To%20enable%20TDS%2C%20we%20visit%20the%20Power%20Platform%20admin%20centre.&text=From%20here%2C%20we%20select%20the,option%20to%20enable%20the%20endpoint.

![image](https://user-images.githubusercontent.com/70860420/114359500-0a6d1580-9b42-11eb-8249-632283d31a94.png)

**Comment by krishnaVSU2020** [comment]
ok I have resolved the issue now I can render the Power BI report on my side. thank you for your patience and support. We are good to close this case.

**Comment by krishnaVSU2020** [comment]
By the way, I have not enabled the TDS explicitly looks like TDS comes on by default for new environments. In my case, the issue is with the / at the end of the URL.
Maybe the team needs to document how to enable TDS for old D4T environments because I don't see this option at the settings:
![image](https://user-images.githubusercontent.com/70860420/114362694-9fbdd900-9b45-11eb-84c8-addb4c61de9c.png)

![image](https://user-images.githubusercontent.com/70860420/114362715-a64c5080-9b45-11eb-9de9-f1926ce52cb0.png)
