### ISSUE TITLE
[BUG]: Not able to turn on the Flow "Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created"

### ISSUE THREAD

**Issue by krishnaVSU2020** [microsoft/powerapps-tools#917]
**Describe the bug**
I am not able to turn on the Flow, Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created under governance components.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - **Governance**
 - Version 2.0
 - Flow **Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created**

**To Reproduce**
1. Go to Governance component
2. Select Colud Flows
3. Select the Flow **Microsoft Teams Admin | Ask for Business Justification when Microsoft Teams environment is created**
4. Click on **Turn on** flow

**Expected behavior**
I should be able to turn this flow on without any issues

**Screenshots**
I see the below error:
![image](https://user-images.githubusercontent.com/70860420/114361763-88322080-9b44-11eb-9555-907762592ffa.png)

**Note:**
I am a tenant admin and I have full access on my tenant, this is happening with D4T COE setup only.

**Comment by krishnaVSU2020** [comment]
It says as "**There aren't any connection references for this flow.**"
see the below:
![image](https://user-images.githubusercontent.com/70860420/114409838-da8d3480-9b78-11eb-9f45-093fd225bc65.png)
Not sure why the connections were not associated :( all the other flows are getting all the connections properly.  It didn't even ask me to authenticate for the connection when I try to edit the flow. 
I have Teams, Outlook and Dataverse connections intact.
![image](https://user-images.githubusercontent.com/70860420/114410508-6e5f0080-9b79-11eb-9691-448a0232cddf.png)

**Comment by JeneferM-MSFT** [comment]
Yes it looks like those didnt import into the flow for whatever reason. If you hit edit on the flow it will create them, and then if you save you will be able to turn on. This will create an unmanaged layer though which you will need to delete on upgrade next time

**Comment by krishnaVSU2020** [comment]
agreed did many times but didn't work for me :(

**Comment by JeneferM-MSFT** [comment]
Did you update Core to 2.0 already? The only thing I can think of is that perhaps we used a new connector in there that you didnt install yet.

**Comment by krishnaVSU2020** [comment]
hmm as of I know I can't use 2.0 for D4T because I see 1.5 for D4T approach, see the solution as part of the solution package. 2.0 is for Production not for D4T.
![image](https://user-images.githubusercontent.com/70860420/114418432-7f5f4000-9b80-11eb-8d39-85fff919b5b0.png)

**Comment by JeneferM-MSFT** [comment]
oh you are in a teams environment? I didnt see that above
So you installed CoreTeams 1.5 and AuditComponents 1.5 both into the same dataverse for teams environment?

**Comment by krishnaVSU2020** [comment]
Yes I did installed both of them

**Comment by JeneferM-MSFT** [comment]
ok thank you I will investigate now that I understand this to be a teams repro

**Comment by krishnaVSU2020** [comment]
Yes please, Thank you for your time.

**Comment by krishnaVSU2020** [comment]
Hi Jenefer,

Any luck on this?

**Comment by manuelap-msft** [comment]
We have this fixed locally, and are just in the final stages of testing. We will likely release a bug fix update either later today or tomorrow.

**Comment by manuelap-msft** [comment]
Fixed with current release.
