### ISSUE TITLE
[BUG]: Missing Dependency - msdyn_FlowApprovalsCore (2.0.1.2)

### ISSUE THREAD

**Issue by jazizka** [microsoft/powerapps-tools#919]
**Describe the bug**
We are trying to upgrade Governance component from 1.25 to 1.5. The Core and Nurture components are already upgraded. Audit log component cannot be upgraded due to "The original workflow definition has been deactivated and replaced."

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Governance Component
 - Version: 1.25 -> 1.5

**Screenshots**
![image](https://user-images.githubusercontent.com/75126976/114398300-edffc600-9b9f-11eb-9185-5496eeed70ac.png)

**Additional context**
What is that missing part. Where do we get it? We use the latest package of CoE.

Thank you,
Jakub

**Comment by manuelap-msft** [comment]
Hello,

this is a Product dependency, not a CoE Starter Kit dependency - flows in this solution use Approvals, which will need to be initialized in the environment first. Please follow the first step of these setup instructions to get Approvals in your environment: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment

Thank you for using the CoE
Manuela
