### ISSUE TITLE
[BUG]: Can't hide "World News" feature

### ISSUE THREAD

**Issue by bhaub78** [microsoft/powerapps-tools#92]
From the Admin App, disabling the "World News" feature doesn't actually hide the "Word News" section in the main app.  This is what I have configured for the "Government RSS Feed" link:
https://www.usa.gov/rss/updates.xml

Note that RSS feed isn't populating the World News feature either.  There's nothing showing in World News with that URL configured.

**Comment by mr-dang-msft** [comment]
Hi @bhaub78,
The first version of the Crisis Communication app mismatched the feature flags. This has been fixed in later versions. Can you update to the most recent version for the fix?
