### ISSUE TITLE
Not able to import the COE Starter Kit core solution into a Dataverse for Teams environment

### ISSUE THREAD

**Issue by vidyasagaralti** [microsoft/powerapps-tools#922]
**Describe the bug**
Got the following error when tried to import the core solution onto a Dataverse for Teams environment. 
"Customizations from the file  CenterofExcellenceCoreComponentsTeams_1_5_managed.zip failed to import."

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution ExcellenceCoreComponentsTeams_1_5_managed.zip
 -
**To Reproduce**
Import Solution into Dataverse for Teams environment. 

**Expected behavior**
Solution should be imported

**Screenshots**
![CoEforDataverseforTeamsError](https://user-images.githubusercontent.com/28040714/114406873-82c8ea80-9bc5-11eb-9298-8706648513d4.png)

**Additional context**
We tried in two different tenants. We have got the same issue in both instances.

**Comment by manuelap-msft** [comment]
Hello,

could you select Download Log and share that here?

Thank you
Manuela

**Comment by vidyasagaralti** [comment]
Hi Manuela, 

Log file is attached. Please remove .txt extension.
 
[CenterofExcellenceCoreComponentsTeams_1_5_managed.zip_import.xml.txt](https://github.com/microsoft/powerapps-tools/files/6297427/CenterofExcellenceCoreComponentsTeams_1_5_managed.zip_import.xml.txt)

Regards
Vidya Sagar Alti

**Comment by JeneferM-MSFT** [comment]
CanvasApp import: FAILURE: Code: GraphUserDetailNotFound Message: The user '00000000-0000-0000-0000-000000000000' was not found in Graph

**Comment by manuelap-msft** [comment]
Are you importing the solution with a regular user that's a member of the team? I'm afraid this looks like a Product bug, so I would suggest you raise a Support Ticket on this.

**Comment by vidyasagaralti** [comment]
We are importing the core solution using the Team owner login. He is also the Global admin.  We are also able to import other solutions into the Dataverse for Teams.

**Comment by manuelap-msft** [comment]
Hello,

please raise a support ticket via your usual support channels. We have many customers who have successfully installed the released version in Teams, so unfortunately you may be experiencing a product bug here. It might be worth trying the import again as it may have just been a temporary issue. 

In your xml file, if you parse through it the error message is the below, which is nothing to do with the CoE kit itself:
CanvasApp import: FAILURE: Code: GraphUserDetailNotFound Message: The user '00000000-0000-0000-0000-000000000000' was not found in Graph

**Comment by HelmutWimmer** [comment]
Same issue here

**Comment by manuelap-msft** [comment]
@HelmutWimmer This is a closed issue. Please open a new issue with your details and error message for us to track.
