### ISSUE TITLE
Question on Admin | Welcome Email flow

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#923]
Hello there,

I have Core Components 1.89 and am getting ready to update to 2.0.  In the update, there is the new flow Admin | Welcome Email.  Because it is an automated flow, will it import as "on" or "off?"   I'm trying to determine the impact of adding this flow to the mix.  (my hope is that it will import as "off")  It's been a long time since I've imported one of these that had new automated flows.

Thank you.

**Comment by JeneferM-MSFT** [comment]
The flow is turned off on initial import. Note that this is the same flow that used to reside within the Nurture solution. We moved it as part of the effort to decouple nurture from Core.

**Comment by osbornecc** [comment]
Thank you for confirming!
