### ISSUE TITLE
Custom Connector DlpViolation issue

### ISSUE THREAD

**Issue by xrmcloud** [microsoft/powerapps-tools#928]
**Describe the bug**
Flow coudnt be activated: [Child] Admin | Sync Logs. Error: Flow client error returned with status code "Forbidden" and details "{​​"error":{​​"code":"DlpViolation","message":"Flow '231e2aae-09e0-eb8e-9d6e-628197c149a8' cannot be activated due to admin API policies."}​​}​​".

**Component **
 - Solution [Nurture]
 - Version [1.40]
 - Flow

**Comment by manuelap-msft** [comment]
Hello,

our pre-requisites for DLP policies are listed here:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#prerequisites

Thank you
Manuela

**Comment by manuelap-msft** [comment]
If the custom connector is missing from the DLP policy here is a walkthrough of how to get this added to your policy https://github.com/microsoft/powerapps-tools/files/6136826/Custom.Connector.into.DLP.pdf 

Hope this helps and thank you for using the CoE
Manuela
