### ISSUE TITLE
Admin | Sync Audit Logs - Failing

### ISSUE THREAD

**Issue by keharrin** [microsoft/powerapps-tools#929]
**Describe the bug**
This flow is failing on the run child flow action with error:
The server did not receive a response from an upstream server. Request tracking id '08585832859295131647460931508CU187'.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Center of Excellence - Audit Logs
 - Version [e.g. 1.29] 1.3.6
 - App or Flow [e.g. Sync Template (v2)] Admin | Sync Audit Log

The child flow [Child] Admin | Sync Logs
is failing with error:
Blob key 20210412133417563000696$20210412133503971000947$audit_general$Audit_General$na0025 in the url is invalid

**Comment by manuelap-msft** [comment]
Please ensure you've correctly set the Tenant ID to your Tenant's ID:
![image](https://user-images.githubusercontent.com/55705669/114707258-e9631b00-9d21-11eb-90c1-a186b1a5d41a.png)

Our setup instructions will walk you through that:
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

**Comment by keharrin** [comment]
We followed those instructions yesterday and when we tested the connector we got a 200 response.

**Comment by manuelap-msft** [comment]
You will be able to test the connector even if your DLP policies are incorrect. No DLP validation takes place when you test a connector, only when you turn on or run a flow.

**Comment by manuelap-msft** [comment]
You will be able to test the connector even if the Tenant ID is incorrect, as the connector test does not pull information from the Environment Variable. Only the flow does. 

Can you send us some screenshots of the error and we may be able to help investigate further?

**Comment by JeneferM-MSFT** [comment]
Please also see what value you have for the env var right now. 
Go to Solutions > Default Solution > Filter to Environment Variables > Open the Tenant ID

You should have here as your current value your tenant id. If you do not, then your flow will not pass. 

You can check for what your tenant ID is as shown in the [set up instructions](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog)
![image](https://user-images.githubusercontent.com/62659043/114712412-4bedf400-9ced-11eb-89d2-ab1483479554.png)

**Comment by keharrin** [comment]
When I go to Default Solution,  I do not see Environment Variable as an option in the filter field
***@***.***D73104.0BC32E90]

I reviewed the instructions sent but I do not see specific steps on how to find tenant id

**Comment by JeneferM-MSFT** [comment]
I pasted a picture for you above of the spot in the instructions. You needed to do this step in order to set up the custom connector. 

I cannot help you further if you can't do these steps, you may need to seek some help from a Power Platform partner.

**Comment by keharrin** [comment]
Ok.  I have confirmed our tenant id is correct as well.

**Comment by manuelap-msft** [comment]
Can you open the Admin | Sync Audit Log flow (NOT the child flow) and verify you have the highlighted scope at the top of the flow:
![image](https://user-images.githubusercontent.com/55705669/114717299-d3a72300-9d2c-11eb-86d0-75ad9cdd2bc1.png)

**Comment by keharrin** [comment]
Yes here is a screen print from our flow
![image](https://user-images.githubusercontent.com/77410660/114717789-033d3780-9cfb-11eb-95ff-14acb789e4c5.png)

**Comment by JeneferM-MSFT** [comment]
Can you please share a screenshot showing the env variable being correctly set? Just mark out most (but not all) of the GUID shown so that we can validate it isnt ours.

**Comment by keharrin** [comment]
Is this the step you are referencing?
![image](https://user-images.githubusercontent.com/77410660/114742891-c7fa3300-9d11-11eb-9964-66bcab2db649.png)

**Comment by JeneferM-MSFT** [comment]
No, above you said that you validated the tenant id was set correctly. The spot you show is not a tenant id. 
Where did you validate that? And can you please share a screenshot.

**Comment by keharrin** [comment]
We have split responsibilities at our company.  I received the tenant id from the O365 admin and used it to setup the Office 365 Management API.  I only Power Admin rights not O365 admin or Dynamics Admin 

In our COE Environment, in the Default Solution, Tenant Id here is what we have:
![image](https://user-images.githubusercontent.com/77410660/114746757-b450cb80-9d15-11eb-85a7-89a95940bc68.png)

**Comment by JeneferM-MSFT** [comment]
yes that is not a tenant GUID. You need to have the tenant GUID here. You will need to get the tenant GUID from your counterpart and put it in that spot.
I suggest you get the person that setup the Azure and custom connector side and do this work together. 
Alternatively you may benefit from hiring out a Power Platform partner to assist. 
Thanks and best of luck.

**Comment by keharrin** [comment]
Thanks for your help and feedback today.  I have a successful run on the flows!  I will pick back up setting up other components and hope it is ok to reach out if I run into any issues.

**Comment by eromerof** [comment]
Hello, 

I have the same error. I think that I configured all parameters. In the Power Automate [Child] Admin | Sync Logs the 'List audit log content' is right but the step 'GetContentDetails' throw this error:

Blob key 20221116151407516019044$20221116151407516019044$audit_general$Audit_General$emea9034 in the url is invalid

![image](https://user-images.githubusercontent.com/39483747/202490937-52cc6921-16ed-40c5-8069-a8f4369c35a2.png)

What I can be doing wrong? 😥

**Comment by manuelap-msft** [comment]
@eromerof Can you please open a new GitHub issue for this so we can accurately track and triage open issues? Thank you!

**Comment by manuelap-msft** [comment]
[eromerof](https://github.com/eromerof) The CoE kit has moved to it's own repo https://github.com/microsoft/coe-starter-kit/issues and we no longer actively triage issues in this repo. Can you please open a new issue under here https://github.com/microsoft/coe-starter-kit/issues so we can accurately triage open issues? Thank you
