### ISSUE TITLE
[BUG]: Notification Flow error: "InvalidTemplate"

### ISSUE THREAD

**Issue by NickElniff** [microsoft/powerapps-tools#93]
**Describe the bug**
The Flow to "Notify users on new crisis communication news" fails with the following error.
InvalidTemplate. Unable to process template language expressions in action 'Set_App_Link_Variable' inputs at line '1' and column '2818': 'The template language function 'indexOf' expects its first parameter to be of type string. The provided value is of type 'Null'. Please see https://aka.ms/logicexpressions#indexof for usage details.'.

**To Reproduce**
Followed the documentation https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#prerequisites

**Expected behavior**
Expected no errors when running the flow

**Screenshots**

![image](https://user-images.githubusercontent.com/39538334/76280920-77d4b580-6261-11ea-8f4f-c00a9ec86254.png)

**Interface(please complete the following information):**
 - Browser - Edge
 - Version date: Version 82.0.439.1 (Official build) dev (64-bit)

**Additional context**
Following Guide - https://docs.microsoft.com/en-us/powerapps/maker/canvas-apps/sample-crisis-communication-app#prerequisites

**Comment by mr-dang-msft** [comment]
Hi @NickElniff,
The error is saying that the App Url is returning null. That means it's empty. You will need to have configured the app's url in the admin app:
![image](https://user-images.githubusercontent.com/39354102/76367724-1e18cd80-62eb-11ea-874a-e154522f9f47.png)

Let me know once you have put in the app's url and tested out the flow successfully.
