### ISSUE TITLE
[BUG]: Can't launch apps from Developer Compliance Center

### ISSUE THREAD

**Issue by bch920** [microsoft/powerapps-tools#930]
**Describe the bug**
Can't launch apps from Developer Compliance Center

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Governance]
 - Version [1.50]
 - App  [Developer Compliance Center]
 - Teams Dataverse 

**To Reproduce**
1. Go to any app in Developer Compliance Center
2. Click on details
3. Click Launch
4. Edge opens
4. See error5. "Failed to obtain authoring session token from RP. [InvalidAuthenticationResult] AuthenticationResult is not valid. Error: Safe cast for AuthenticationResult failed."

**Expected behavior**
The app to launch in Edge

**Screenshots**
![image](https://user-images.githubusercontent.com/394776/114719756-fa377f00-9d69-11eb-8c87-0032017106c1.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello that is an error from the product which seems to indicate an intermittent service issue, not related to our toolkit. You will need to wait and try again later.
