### ISSUE TITLE
[BUG]: No refresh button in the Developer Compliance Center

### ISSUE THREAD

**Issue by medicineshow** [microsoft/powerapps-tools#931]
**Describe the bug**
In the Developer Compliance Center App overview page, the prompt text in the description field does not go away after inputting a description and it also refers to a Refresh button below that does not exist

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Governance
 - Version: 1.17
 - App: Developer Compliance Center

**To Reproduce**
1. when a user responds to a request to provide app detail they are presented with the App overview form

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17124284/114738132-9a2be300-9d3f-11eb-829e-a09539edfabd.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello this was fixed via #704
Thanks for using CoE
