### ISSUE TITLE
[BUG]: Not Getting Capacity Alerts if Approved Capacity is Null

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#932]
**Describe the bug**
If the Approved Capacity is null, then you do not get any Capacity Alerts

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 2.0
 - App or Flow Get Capacity Alerts

**To Reproduce**
set the Approved Capacity to null

**Expected behavior**
If the actual capacity is > 0 and is less than the approved capacity is null, then I would have expected there to have been a Capacity Alert.  There is no capacity alert if the approved capacity is null.  This is because the "List Environment Capacity Information" has a filter in it which filters out record where the approved capacity is null (See screenshot below)

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/114745850-00683400-9d47-11eb-828f-03986015aa95.png)

![image](https://user-images.githubusercontent.com/8484048/114746399-9d2ad180-9d47-11eb-948d-c160a9d9ad73.png)

**Comment by JeneferM-MSFT** [comment]
Hello. This is by design. We do not want to send alerts unless the admin has explicitly decided to add capacity limits for the environments. You just need to enter these to be some default value if you want to have alerts for all your environments. 
Thanks for using CoE

**Comment by NPrice99** [comment]
How do you add these default values ?
________________________________

**Comment by manuelap-msft** [comment]
If you're looking for a daily capacity report, you may find it easier to set up a separate flow following these steps: https://docs.microsoft.com/en-us/power-platform/admin/programmability-tutorial-create-daily-capacity-report
