### ISSUE TITLE
[BUG]: Flow Admin | Sync Template v3 does not update environments created after 30th of March. All of the CoE flows got turned off for some reason but after turning them on env. updates are not appearing despite there is no errors on the flow.

### ISSUE THREAD

**Issue by IzabelaStachurka** [microsoft/powerapps-tools#934]
**Describe the bug**
For whatever reason, most of the Flows in the CoE were turned off. We have turned them on now but we have noticed that there is no new information being brought in about newly created environments since the 30th of March. I have ran the flows again, the one that I think has to do with Environments, but I am not seeing environments created beyond the 30th of March.
So I believe the issue is from this Flow that sits in Center of Excellence environment, under the Center of Excellence - Core Components solution: Admin | Sync Template v3. The flow runs with no errors, but Environments are still not being brought in past the 30th of March. All other tables are up to date from what I've checked

**Component (please tell us which flow or app you are experiencing issues with):**
 - Center of Excellence - Core Components
 - Admin | Sync Template v3

**Comment by JeneferM-MSFT** [comment]
Hello. Can you please let me know, did you do an upgrade or a new install of the toolkit? New installs we expect to see all the flows turned off, if this was an upgrade and it turned off flows that were previously on, that would be a product bug. We have never seen this though so I will assume this is a new install.  

Please be sure to follow the steps in the [setup documentation](https://docs.microsoft.com/power-platform/guidance/coe/setup-core-components) which outline turning on the sync flows. 
Please also read through the [pre-reqs](https://docs.microsoft.com/power-platform/guidance/coe/setup#prerequisites) and note that the flows need to be installed / running in the context of an entity with the Power Platform Admin role or you will only see environments to which your identity (the identity running the flows) have personal access.

**Comment by IzabelaStachurka** [comment]
Hello,

Thank you for contacting me. 
We have switched the connections in the flow to another account to get it working.
