### ISSUE TITLE
Admin | Sync Template v3 (Apps) fails but passes on rerun - due to hard coded dataverse guid

### ISSUE THREAD

**Issue by osbornecc** [microsoft/powerapps-tools#935]
Hi,

I am having some weird failures with the Admin | Sync Template v3 (Apps) flow after updating to Core Components 2.0 and happened to notice there is now a Core Components 2.0.10 out there.  Just curious what the changes were, in case they might help.

Thank you.

**Comment by JeneferM-MSFT** [comment]
We had to remake the prod version of Core (from 2.0 to 2.0.10) for an issue in the teams version of Core so there wont be any sync flow impacts for you. 
What issue are you seeing in the apps sync flow?

**Comment by osbornecc** [comment]
OK thanks for the info!

As for my sync issues, it's really weird.  After updating, the sync apps flow for two environments consistently failed when updating an edited app.  (if I remember the step correctly)

Each time, the error was "admin_Connector With Id = 412368f1-c62f-4012-87f2-23e6a061204a Does Not Exist"

Well, that is correct.  A connector with that ID does not exist.  And my investigations on one app that is reporting that error doesn't show any reference to a connector with that ID.  One of the apps was the DLP Editor V2 that came with CoE coincidentally.

So to try to fix the data, I set the Full Inventory to "yes" but that ended up making it worse ha!  This time every environment had that failure on at least one app.

When I resubmit the failed flows they run fine though.  So yeah, very strange.

**Comment by osbornecc** [comment]
Oh, also I did make sure to remove unmanaged layers on everything I had touched.

**Comment by osbornecc** [comment]
Ah I think I found it.  Is it possible there is a default value left in the flow?

Under the Edit Updated Apps section

![image](https://user-images.githubusercontent.com/50427725/115086689-9de77300-9ec1-11eb-893d-def907bc30d5.png)
![image](https://user-images.githubusercontent.com/50427725/115086704-a3dd5400-9ec1-11eb-8a57-96cc60c6e73a.png)

**Comment by osbornecc** [comment]
Looks like it might be in the "new apps" section as well.  This is a partial screenshot.

![image](https://user-images.githubusercontent.com/50427725/115087500-1c90e000-9ec3-11eb-844b-8caa2cb46b27.png)

But removing the value from the "edit apps" section seemed to fix my issue.  I'm going to remove it from the "new apps" section and rerun.
Thanks.

**Comment by JeneferM-MSFT** [comment]
yep it looks like there was an assumption tha tthis GUID would be the same cross tenant and I see that it is not. I'll see what we can do about it here.

**Comment by JeneferM-MSFT** [comment]
Local fixed to now look for the connector guid as an explicit step and then use it in the calls instead.

![image](https://user-images.githubusercontent.com/62659043/115091476-dc3a5d80-9ed4-11eb-97f8-5f4677a5fe84.png)

**Comment by osbornecc** [comment]
Hi Jenefer,
Where in the flow did you add that section?  Should I try that as well?  I simply removed the GUID from the failing steps so it may be possible my data is messed up now.

Thanks.

**Comment by JeneferM-MSFT** [comment]
We aren't using the data yet, its something we put out to start gathering the data, and then target using the data in the May release. You are welcome to test it out though! 

We collect and fill the variable at the top:
![image](https://user-images.githubusercontent.com/62659043/115264028-2dc03380-a0f3-11eb-907a-9ce2fc247046.png)


And then use it where you used to see the GUID today:
![image](https://user-images.githubusercontent.com/62659043/115264396-8099eb00-a0f3-11eb-8b0e-7b803369c9af.png)

**Comment by JeneferM-MSFT** [comment]
Hello. We have just released the May edition of the toolkit and it contains this fix. 
Please be sure to follow the instructions at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) in order to remove any unmanaged layers you have in place, or you will not receive the update. 

Thank you for helping make CoE great!

**Comment by JakubZizka** [comment]
Hello friends,
we just upgraded Starter Kit to December 2022 and we still get this issue. I had to apply workaround with the variable you described here.

Will this be fixed?

Thank you
