### ISSUE TITLE
Wrong Title When importing CenterofExcellenceAuditComponents_1_51_5_managed

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#938]
**Describe the bug**
I am importing  CenterofExcellenceAuditComponents_1_51_5_managed and when importing the message is Importing "Centre of Excellence - Governance Components"

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Audit Components
 - Version 1.51.5
 - App or Flow Neither Solution

**To Reproduce**
Download Center o f excellence Audit Components_1_51_5_managed 
import solution
see message at the top of the screen.

**Expected behavior**
I expected the solution to be CentreOfExcellenceAuditComponents_1_51_5_managed

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/115210421-762d2080-a0f6-11eb-82eb-c2e455b056d7.png)

**Additional context**

**Comment by NPrice99** [comment]
Also with version 1_50

**Comment by NPrice99** [comment]
If I use "Upgrade" option when importing the package I get this - 
![image](https://user-images.githubusercontent.com/8484048/115212225-2fd8c100-a0f8-11eb-9afc-b077dbfe07d0.png)

**Comment by JeneferM-MSFT** [comment]
Governance is what its called in all our documentation, for example: 
![image](https://user-images.githubusercontent.com/62659043/115304668-7216f800-a122-11eb-8119-f70e5119a43e.png)

So we are just trying to match that up. Do you have a concern or were you just being sure we didnt mess up? (we do mess up sometimes :))

**Comment by NPrice99** [comment]
Hi @JeneferM-MSFT 
so does solution CenterofEXcellence AuditComponents_1_51_5_mamanged.zip = Centre of Excellence - Governance Components ?

Regards

Nigel

**Comment by JeneferM-MSFT** [comment]
Correct.
