### ISSUE TITLE
Tips for creating CDS/Dataverse API swagger json

### ISSUE THREAD

**Issue by malaker** [microsoft/powerapps-tools#939]
Hi

I am wondering how did you create this https://github.com/microsoft/powerapps-tools/blob/master/Apps/BusinessProcessFlow/CDS-API.swagger.json

Did you create it manually or somehow you converted odata to openapi swagger like format ? Could you describe the process of creating this? I would like to also create custom connector for dataverse using similar approach.

**Comment by manuelap-msft** [comment]
Hello,

in this GitHub forum, we are only able to assist with issues related to the solutions uploaded to this repo. For more general questions, please raise them in the Power Automate community forum: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity

Thank you
Manuela
