### ISSUE TITLE
[QUESTION] : Why does CenterofExcellenceCoreComponents_2_0_10_managed.zip require 3 new Environment Variables ?

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#940]
**Describe the bug**
When Importing - CenterofExcellenceCoreComponents_2_0_10_managed.zip you asked to fill in values for Approval Admin, Developer Compliance Centre URL and Power Platform Make Office 365 Group

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 2.0.10
 - App or Flow - Solution

**To Reproduce**
1. Goto Solutions
2. Click On Import
3. Select CenterofExcellenceCoreComponents_2_0_10_managed.zip
4.  See request to fill in environment variables

**Expected behavior**
I did not expect to be asked for Compliance Developer Canvas App, Approval Admin and Maker Office 3675 Group

**Screenshots**
![image](https://user-images.githubusercontent.com/8484048/115370798-4eef5580-a1c1-11eb-8f83-ce2a90204532.png)

**Additional context**
We only run the Core Components, the Audit Logs and the PowerBI Dashboard to monitor the PowerPlatform on our production environment so would rather not have these other things in the Core Components.

**Comment by JeneferM-MSFT** [comment]
Agree its not ideal but we had to move these items in to Core in order to reliably support the Teams platform. You can ignore them and just not turn on the Welcome flow in Core and you will not be impacted.

**Comment by NPrice99** [comment]
Thanks - Thats reassuring that you can ignore them @JeneferM-MSFT
