### ISSUE TITLE
[BLOCKED PORTS] Error message when setting up dashboard report

### ISSUE THREAD

**Issue by keharrin** [microsoft/powerapps-tools#942]
**Describe the bug**
I am attempting to setup the power bi dashboard.  On initial load this error is happening for each of the sections

Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
**To Reproduce**

1

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77410660/115422988-09cc2300-a1c3-11eb-9a15-d8277ad5d4cb.png)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

this typically happens for two reasons:
- TDS endpoint is not enabled on your environment
- you entered the Org URL incorrectly when prompted - it has to be entered in this format: org23423.crm.cynamics.com without the https:// at the beginning or / at the end.

Let me know if this helps,
Manuela

**Comment by keharrin** [comment]
Hi Manuela,

I confirmed the Org URL.  Please guide me to the correct section on the COE Toolkit setup that indicates the need for TDS EndPoint.  

Thanks!
Karen

**Comment by manuelap-msft** [comment]
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#get-the-environment-url
![image](https://user-images.githubusercontent.com/55705669/115441242-89301580-a208-11eb-8e0a-df540b3db4af.png)

https://docs.microsoft.com/en-us/power-platform/admin/settings-features

**Comment by keharrin** [comment]
Thanks!  I will go to my Global Admins to confirm.

**Comment by keharrin** [comment]
Hi Manuela,

We confirmed TDS enabled
![image](https://user-images.githubusercontent.com/77410660/115554637-4c9a0380-a274-11eb-96b4-8929f6a28555.png)

Confirmed  I am using the correct format of the environment URL coe-lyondellbasell.crm.dynamics.com

**Comment by manuelap-msft** [comment]
Hello,

can you share a screenshot of how you put in the Org URL? And can you confirm you're using the latest version of the Power BI named Dashboard-PowerPlatformAdminDashboard-2021-04-08.pbit or a previous version?

Thank you
Manuela

**Comment by keharrin** [comment]
Yes this is the version I am using 
![image](https://user-images.githubusercontent.com/77410660/115561606-596e2580-a27b-11eb-98b4-8a6abd6e5ab9.png)

![image](https://user-images.githubusercontent.com/77410660/115562206-e2855c80-a27b-11eb-823d-200d1c5e6e86.png)

**Comment by manuelap-msft** [comment]
Strange - can you confirm you are logged in to Power BI and have access to the underlying data tables as well? The Power BI dashboard now uses DirectQuery which honours security roles and access set on the tables in Dataverse - the user loading the Power BI would therefore need to have access to the data source as well.

**Comment by sharmajitendralal** [comment]
I am getting same issue ...Org URL is correct as per MS Doc and TDS end point enabled ... struggling since last week no solution yet
 
![CeOIssue](https://user-images.githubusercontent.com/30046543/115698776-9ec94a80-a382-11eb-8309-fa43c05b75e0.PNG)

**Comment by sharmajitendralal** [comment]
Here I am going to attach details report of this issue
[CoE Error Report.docx](https://github.com/microsoft/powerapps-tools/files/6357657/CoE.Error.Report.docx)

**Comment by sharmajitendralal** [comment]
> Strange - can you confirm you are logged in to Power BI and have access to the underlying data tables as well? The Power BI dashboard now uses DirectQuery which honours security roles and access set on the tables in Dataverse - the user loading the Power BI would therefore need to have access to the data source as well.

Yes, my account have System Administrator role for specific environment  and Power Platform admin role as well but still same issue, going through the dataverse with same account can access each table in CoE Installed Environment

**Comment by JeneferM-MSFT** [comment]
Hello we believe this issue is not particular to our toolkit dashboard. It seems to repro for other folks generally as well: 
[View table data in Power BI Desktop](https://docs.microsoft.com/powerapps/maker/data-platform/view-entity-data-power-bi)

You will need to create a support ticket to get assistance as a result.

**Comment by keharrin** [comment]
Hi Jenefer,

Just clarifying, as I was told this was where I get support for the COE Toolkit :-)

Do I need to open a support ticket with Microsoft regarding an issue with the toolkit or an issue with our environment?

I followed the steps in the link above and got the same error
![image](https://user-images.githubusercontent.com/77410660/115758162-6f0b4a00-a364-11eb-8a5e-a94823dd550b.png)

**Comment by JeneferM-MSFT** [comment]
Yes this issue has nothing to do with the toolkit. We just hit a product bug. 
You will need to tell support that you followed the steps in [View table data in Power BI Desktop](https://docs.microsoft.com/powerapps/maker/data-platform/view-entity-data-power-bi) and got that error

**Comment by manuelap-msft** [comment]
Hello, we did some further investigation and likely this bug is related to blocked ports: https://docs.microsoft.com/en-us/powerapps/developer/data-platform/dataverse-sql-query#blocked-ports

**Comment by sharmajitendralal** [comment]
> Yes this issue has nothing to do with the toolkit. We just hit a product bug.
> You will need to tell support that you followed the steps in [View table data in Power BI Desktop](https://docs.microsoft.com/powerapps/maker/data-platform/view-entity-data-power-bi) and got that error

I am already in discussion with MS but did not get any resolution till now, I will keep posting about the update

**Comment by JeneferM-MSFT** [comment]
Per Manuela above, after further investigation she thinks this is likely related to blocked ports: https://docs.microsoft.com/powerapps/developer/data-platform/dataverse-sql-query#blocked-ports

**Comment by JeneferM-MSFT** [comment]
closing this out since there is nothing further we can do to assist.
