### ISSUE TITLE
[BUG]: Navigation from the first page to the details page of the Platform Training Registration not working correctly

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#943]
**Describe the bug**
Clicking on event on first page of Platform Training Registration does not select correct event on the second page

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Nurture
 - Version 1.40
 - Platform Training Registration

**To Reproduce**
1. Create two events using the Platform Training Management app
2. Log into the Platform Training Registration app
3. Click on the second event created
4. User is taken to the first event created

**Expected behavior**
Clicking on the event on the first page should take me to the correct information on the details page

**Screenshots**
![image](https://user-images.githubusercontent.com/1025102/115429216-1bc9b800-a1fb-11eb-969c-13aec0330acd.png)
![image](https://user-images.githubusercontent.com/1025102/115429263-284e1080-a1fb-11eb-970e-5fe243447b0c.png)

**Additional context**
Need to add a filter on the items on the details page
![image](https://user-images.githubusercontent.com/1025102/115430433-46684080-a1fc-11eb-9af7-b3d1bddd2b90.png)

**Comment by JeneferM-MSFT** [comment]
Thank you for posting. While I agree this would be better ux, the end to end flow of the app needs reconsidered all up for this to help (ex easy way to get back to the list). I have put this on our backlog and we will consider in the future. Wont fix for now. 

Thanks for using CoE.
