### ISSUE TITLE
[BUG]: Few spelling issues within the Maker Assessment App

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#945]
**Describe the bug**
Clicking on event on first page of Platform Training Registration does not select correct event on the second page

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Nurture
 - Version 1.40
 - Maker Assessment

**To Reproduce**
1. Log into the Maker Assesment App
2. Spelling issue on the first page
3. Go to the second page
4.  Spelling issue on the first page
5. Click on Data stage - select "What data will you be using in the app?"
6. Spelling issue

**Expected behavior**
On first page, "questionarre" should be "questionnaire"
On second page, "Soltution Type" should be "Solution Type"
On Data stage - select "What data will you be using in the app?Option "I need a data base" should be "I need a database".

**Screenshots**
![image](https://user-images.githubusercontent.com/1025102/115432049-dfe42200-a1fd-11eb-882e-6bff32af8147.png)
![image](https://user-images.githubusercontent.com/1025102/115432086-e83c5d00-a1fd-11eb-9a8e-b26583910454.png)
![image](https://user-images.githubusercontent.com/1025102/115432458-49fcc700-a1fe-11eb-920b-86a3ea778dea.png)

**Additional context**
Soltution Type error comes from one of the excel files which is imported.
I think the data base issue also comes from one of the excel files which is imported.

**Comment by JeneferM-MSFT** [comment]
I have fixed the questionnaire typo but the others are in the sample data. You will need to fix those yourself using the Admin app. Thanks

**Comment by marcster** [comment]
Thanks Jenefer I will do that but this affect all customers who use the sample data provided by yourselves. Is this going to be updated in a later release?

**Comment by JeneferM-MSFT** [comment]
We likely will not reship the sample data.

**Comment by JeneferM-MSFT** [comment]
We have to reship most components this time anyway so I went ahead and fixed the spelling mistakes in the sample data too. Thanks for posting them!

**Comment by JeneferM-MSFT** [comment]
Hello. We have just released the May edition of the toolkit and it contains this fix. 
Please be sure to follow the instructions at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) in order to remove any unmanaged layers you have in place, or you will not receive the update. 

Thank you for helping make CoE great!
