### ISSUE TITLE
[BUG]: Some values not being saved within the Maker Assessment app when moving between stages

### ISSUE THREAD

**Issue by marcster** [microsoft/powerapps-tools#946]
**Describe the bug**
Some values not being saved within the Maker Assessment app when moving between stages

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Nurture
 - Version 1.40
 - Maker Assessment app

**To Reproduce**
1.  Log into the Maker Assessment App
2. Fill in the first page
3. Click on start
4. On Use Case stage, select more than one option for Solution Type
5. Go to next stage "Audience"
6. Click back on Use Case stage
7. Only one value is selected
8. Click on Audience stage
9. Fill in all the values on this stage
10. Click on the Data stage
11. Navigate back to Audience stage
12. How often will the app be used? field value not saved

**Expected behavior**
Values should remain if more than one value is selected for Solution Type field.
Value should remain for How often will the app be used? field

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Thanks somehow this regressed but I was able to restore my previous version and it works now. Thanks for pointing it out.

**Comment by JeneferM-MSFT** [comment]
Thanks for pointing this out. It persists in some workflows and not others. I will investigate.

**Comment by JeneferM-MSFT** [comment]
This is a good catch but after playing with it a bit more, it appears there is a limitation in the control between the onchange and defaultselected items. The good news is that the data is put into the collection correctly so chatbots (in your example) is included in the assessment, it just wont display for the user. 

At this time I'm afraid this will have to be a WF unless you have a suggested fix.
