### ISSUE TITLE
CoE Starter Kit April 08 Release Missing Flows in install packages

### ISSUE THREAD

**Issue by drace3000** [microsoft/powerapps-tools#951]
Missing MS Power Platform CoE kit Components

Contact Info:
Don Race
donald.race@tiaa.org
phL 585.787.2405

1)    Missing Governance Flow Component ‘- “Admin | Compliance Detail Request”

a.    This flow is critical to monitoring App established governance thresholds

b.    Should be in the solution installation file

CenterOfExcellenceAuditComponents_1_40_managed.zip

c.     This flow was in the previous release and is listed in the current CoE Starter Kit documentation

d.     Need to determine how to get this implemented in our TAD environment

 

2)    Missing Nurturing Component ‘- “Admin | Welcome Email”

a.    Should be in the solution installation file

CenterOfExcellenceNurtureComponents_1_40_3_managed.zip

b.     Need to determine how to get this implemented in our TAD environment

**Comment by JeneferM-MSFT** [comment]
We moved some flows around in order to support Teams deployment. These are both now in the Core solution install

**Comment by JeneferM-MSFT** [comment]
You will need to update Core. It is called 
[CenterofExcellenceCoreComponents_2_0_10_managed.zip](https://github.com/microsoft/powerapps-tools/blob/master/Administration/CoEStarterKit/Individual%20Components/CenterofExcellenceCoreComponents_2_0_10_managed.zip)

**Comment by drace3000** [comment]
Thank you Jenefer for the assist as all missing components have now been accounted for.
