### ISSUE TITLE
CeE Kit - PowerBI Dashboard data - confusion around column names

### ISSUE THREAD

**Issue by ArbabsClayco** [microsoft/powerapps-tools#952]
We need to fill out what is actually occurring after we run the flow.
After running the Sync Audit Logs flow, it doesn't appear to be bringing over accurate information. The created on date and the modified date for instance doesn’t match the details view page in Power Apps and the Power Automate. Also, we need info for last run date and time.

**Component (please tell us which flow or app you are experiencing issues with):**
- Solution [e.g. Core, Nurture]
- Version [e.g. 1.29]
- Sync Audit Logs flow / PowerPlatform Admin Dashboard / CoE
**To Reproduce**
1. Go to ' Dashboard-PowerPlatformAdminDashboard-2021-02-02 ' Source: CoEStarterKit.zip
2. Click on 'Apps page & Cloud flows'
**Expected behavior**
Based on the info in the PowerBI report the last run date should match to the last run date on the Power Automate 
**Screenshots**
 See attached File.

Thanks,
[CoE.docx](https://github.com/microsoft/powerapps-tools/files/6358977/CoE.docx)

**Comment by JeneferM-MSFT** [comment]
Our audit logs do not gather data for Power Automate. They only gather data for Power Apps. This data is stored in the Last Launched field of the Power Apps table.
Further they do not gather the created/modified dates, we get that from the product connectors themselves. And each row in dataverse for us has 2 entries for created and modified, one for the object (the flow_created date for example) and one for the row in the table (the date the flow was entered into inventory)

![image](https://user-images.githubusercontent.com/62659043/115732479-43c53280-a345-11eb-9d90-f1006586d54f.png)

Hope that helps

**Comment by ArbabsClayco** [comment]
Does the Audit log [admin_userupn] collect the value of the user who launched the app?
![image](https://user-images.githubusercontent.com/82961086/116130648-18b64800-a691-11eb-94bb-4ea23eb90720.png)

**Comment by JeneferM-MSFT** [comment]
Yes that is correct. That represents the person that launched the app in the case of LaunchPowerApp 

I'm going to close this out as there isnt anything further to do here to assist. 

Thanks for using CoE
