### ISSUE TITLE
[BUG]: There is no active transaction.

### ISSUE THREAD

**Issue by drinklikachamp** [microsoft/powerapps-tools#954]
**Describe the bug**
During the initial import step of the Core Components I received the following error: "There is no active transaction. This error is usually caused by custom plug-ins that ignore errors from service calls and continue processing."

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core Components
 - Version 2.0

**To Reproduce**
1. Go to Import Solution
2. Browse to File
3. Click Import
4. Configure Connections
5. Configure Environmental Variables
6. Click Import

**Expected behavior**
The following solution was successfully imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/5606752/115744376-22ba0d00-a358-11eb-9034-9931ef75dd3f.png)

**Additional context**
I tried it a second time and I did not receive the same error.

I am looking for insights on why this error might have occurred?

**Comment by manuelap-msft** [comment]
Hello! Are you able to install other solutions, and is just the CoE one failing?

**Comment by drinklikachamp** [comment]
In case you missed it, I wanted to point out that when I tried it a second time it worked without issue. I was just researching what may have caused it.

**Comment by manuelap-msft** [comment]
So are you saying you are unblocked and can import it now?

**Comment by drinklikachamp** [comment]
Yes

**Comment by manuelap-msft** [comment]
Then I'm afraid we can't help you - as you've hit the issue before the Import of the kit even started, you are likely to have experienced a small service hiccup or similar. The CoE Starter Kit doesn't use custom plugins.
