### ISSUE TITLE
[BUG]: Flows appear in the Power Platform Admin View but not in the Power BI Desktop View

### ISSUE THREAD

**Issue by medicineshow** [microsoft/powerapps-tools#956]
I can view a specific Flow and Maker in the Power Platform Admin view but when I open Flows in the Power BI desktop, the specific flow is not listed.

 - Solution : Governance
 - Version : 1.71
 - Flows table

**Comment by JeneferM-MSFT** [comment]
Hello can you please let us know what version you are using of both Core and Gov? There isnt a gov v 1.71 out there so I think that is some mistake. 

Also, please note that the filters are likely different on these two reports, so you will want to look and see what filters may be different. For example perhaps 1 is filtering out flows marked deleted and the other isnt.

**Comment by medicineshow** [comment]
Sorry, it is 1.71.7

Kind Regards

Mark Enfield
Mark Enfield | System Architect | HS2/Fujitsu
Cloud Transformation and Development
Application & Multi-Cloud Services

***@***.***D4F167.F8FE2E00]High Speed Two (HS2), 1st  Floor, The Podium Euston, One Eversholt Street, London, NW1 2DN

Advanced Notice Annual Leave:
17th May – 28th May
23rd Aug – 27th Aug

Tel: +44 (0)207 944 6302
Mob: +44 (0)7867 825 281

Web: uk.fujitsu.com<http://uk.fujitsu.com/>
[youtube-icon.gif]<http://www.youtube.com/user/fujitsuUK>[Facebook-icon.gif]<http://www.facebook.com/fujitsuuk> [twitter-icon.gif] <http://twitter.com/#!/fujitsu_uk>  [linkedin-icon.gif] <http://www.linkedin.com/company/fujitsu-uk-and-ireland>  [blogger.png] <http://blog.uk.fujitsu.com/>  ***@***.***D56C84.E4379B30] <https://plus.google.com/103287532874520008913/posts>
***@***.***D56C84.E4379B30]
Fujitsu is proud to partner with Action for Children<http://www.actionforchildren.org.uk/>

**Comment by JeneferM-MSFT** [comment]
Sorry thats still not a version we have for gov, we are only at ~1.5 for Gov. Perhaps you are on an old version of core and sharing its version. 

Regardless, you will need to compare the filters in the PBI and the MDA. 

If you would like my help, please find the row that shows the flow in the table and share that record here

**Comment by medicineshow** [comment]
Apologies, the version for the Audit Components is 1.25

I will check the filters


Kind Regards

Mark Enfield
Mark Enfield | System Architect | HS2/Fujitsu
Cloud Transformation and Development
Application & Multi-Cloud Services

***@***.***D4F167.F8FE2E00]High Speed Two (HS2), 1st  Floor, The Podium Euston, One Eversholt Street, London, NW1 2DN

Advanced Notice Annual Leave:
17th May – 28th May
23rd Aug – 27th Aug

Tel: +44 (0)207 944 6302
Mob: +44 (0)7867 825 281

Web: uk.fujitsu.com<http://uk.fujitsu.com/>
[youtube-icon.gif]<http://www.youtube.com/user/fujitsuUK>[Facebook-icon.gif]<http://www.facebook.com/fujitsuuk> [twitter-icon.gif] <http://twitter.com/#!/fujitsu_uk>  [linkedin-icon.gif] <http://www.linkedin.com/company/fujitsu-uk-and-ireland>  [blogger.png] <http://blog.uk.fujitsu.com/>  ***@***.***D56C84.E4379B30] <https://plus.google.com/103287532874520008913/posts>
***@***.***D56C84.E4379B30]
Fujitsu is proud to partner with Action for Children<http://www.actionforchildren.org.uk/>

**Comment by medicineshow** [comment]
![image](https://user-images.githubusercontent.com/17124284/115856678-b35e1f00-a424-11eb-9fc4-c8410bf1c3df.png)

**Comment by medicineshow** [comment]
This is a screenshot of the filters applied.

**Comment by JeneferM-MSFT** [comment]
Hello I'm afraid I may not be able to scale to help you as we don't seem to be communicating quite sufficiently. You may need to reach out to someone who is familiar with Power Platform, like a partner or a champion within your organization. And as a reminder, the CoE Starter Kit is not a supported product from Microsoft but a set of starter tools for you to use. 

I can try one more set of questions here though and if we still arent able to cross paths, will have to send you to look for help elsewhere.

As far as I can tell, nothing you are asking about is in the Governance (Audit-Components) solution. Just in Core. So if you can please find your version of Core. 

Regarding this individual flow that is in one spot and not the other.  What you need to do is to find that record and see what properties might make it show up in one and not the other due to the filters in place. The fact that it shows up means its in the table. I cannot do this step for you, but I can guess if I see the data record. So you will need to go to the table itself, find that record and return with it here. 

![image](https://user-images.githubusercontent.com/62659043/115879916-66b81b00-a407-11eb-9547-3a7779945052.png)

![image](https://user-images.githubusercontent.com/62659043/115880142-a121b800-a407-11eb-9a13-f5bb33127eeb.png)

**Comment by medicineshow** [comment]
Hi, i think we are getting confused. To clarify: If I open the Power Platform Admin View, I can see the Maker in the list of Makers and the Flow is listed in the Active Flows list. However, in the Power BI dashboard, that has no filters as I attached earlier, Neither the Flow or the Maker are displayed.
I have attached the exported data for the specific flow and maker. If you can give me any assistance as to how I can resolve this that would be appreciated.
Core version is 1.71.7 and Gov is 1.25

**Comment by medicineshow** [comment]
[admin_makers.zip](https://github.com/microsoft/powerapps-tools/files/6366300/admin_makers.zip)

**Comment by JeneferM-MSFT** [comment]
can you please share screenshots of the pbi and the model driven app wehre you are seeing this or not seeing this? note that images need shared from within github they will not work if shared in email.

**Comment by medicineshow** [comment]
This is the view in the pbi. The Flow is in the Personal Productivity environment and I have sorted the Makers by name
![image](https://user-images.githubusercontent.com/17124284/116058214-82c1f380-a677-11eb-898f-8a5c3573a2c2.png)

This is the view in the Power Platform Admin View of Makers:
![image](https://user-images.githubusercontent.com/17124284/116058610-e9dfa800-a677-11eb-82c6-b7e94df9ec9f.png)

And here is the Active Flows view in the Admin View
![image](https://user-images.githubusercontent.com/17124284/116058919-3925d880-a678-11eb-825f-a8750ae2c8e5.png)

**Comment by JeneferM-MSFT** [comment]
Is the dataset under the PBI up to date? If you are in the desktop you can just hit refresh, if you are in the browser, you will need to go to the workspace and see when it was last refreshed.
![image](https://user-images.githubusercontent.com/62659043/116153579-c97a1280-a6a4-11eb-86c6-011a9df42295.png)

**Comment by medicineshow** [comment]
Thank you. The refresh had failed due to bad credentials. Re-entered the credentials data has now refreshed and I can see the missing data. Thanks for the assistance.
