### ISSUE TITLE
[BUG]: Blank Data - Power BI Dashboard 

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/powerapps-tools#958]
**Describe the bug**

I have been unable to view certain tabs of data under my dashboard in Power BI. More importantly, my App Usage tab is blank. I am able to view other related data such as App Shares and App Makers Insight. Can you please assist in this? We're trying to figure out how to confirm Power Platform environment activity and thought App Usage would be a place to start. If it's not, could you please assist in showing another way to verify environment/user activity over a span of at least six months?

 We have recently applied the Center of Excellence as well, and was able to verify that the solutions behind the CoE Core Components are on according to the MSFT documentation on how to implement and run through the solution & flows. Any additional assistance as to why areas of the dashboard are blank would be greatly appreciated.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [1.71]
 - App or Flow [Not sure which flow it could be, maybe Sync Template v2 (Apps)?]

**To Reproduce**
1. Go to 'app.powerbi.com'
2. Click on 'CoE Dashboard Commercial PRODUCTION Report'
3. Scroll down to 'App Usage'
4. See error (in this case, appropriate fields with white space - there is no "(Blank)"

**Expected behavior**
I was expecting to see populated data in the "App Usage" tab of my CoE Dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/83036044/115775234-9ec84b00-a380-11eb-8e99-13e11e0e7405.png)

**Additional context**
I am also running into an issue where if I refresh my datasets, the numbers in my analytics go down. When I first implemented CoE and plugged it into the Power BI dashboard I have 130+ environments which was correct. However, upon refreshing my data I got 86 environments showing instead of 130+. Numbers going down happened to be the case in other areas like Connections, Microsoft Teams environments, etc. I do not have an image to provide the before and after of that unfortunately. Any help on that matter as well would be greatly appreciated. Thank you!

**Comment by JeneferM-MSFT** [comment]
Hello. Here is what you expect to see on this page: [App Usage](https://docs.microsoft.com/power-platform/guidance/coe/power-bi-nurture#app-usage)

App usage requires setup of the audit logs solution. It is separate from Core as it is a little more difficult to setup. 
Please see [Collect audit log data](https://docs.microsoft.com/power-platform/guidance/coe/setup-auditlog)

I suggest you also upgrade Core as you are on a very old version which uses an old and unreliable connector. Please see how to do this at [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

**Comment by yearwoodm15** [comment]
Hello Jenefer, that makes sense thank you! Could you provide any assistance on finding analytics or other information regarding environment/user activity? I'm trying to clean up older environments that may not be active anymore.

**Comment by yearwoodm15** [comment]
Sorry, other follow up question. Will updating the Core assist in the issues I'm seeing where refreshing the data results in accurate (lower) numbers?

**Comment by JeneferM-MSFT** [comment]
It will be hard for me to help with the data inconsistencies you mention without specifics but yes I believe it is likely one of these things:
1) The old version of Core that used a deprecated connector
2) Items being deleted from the tenant and cleaned up from your inventory
3) The permissions being used to run the flows changing or being subject to PIM and hence failing some times. 

User activity it typically creating/editing apps and flows, or launching apps. 
For launching apps, you need to install audit logs
For everything else, the dashboard and the Set XX Permissions apps in Core are intended to help understand usage. 

HTH

**Comment by yearwoodm15** [comment]
Hello, thank for you providing this! I'm going to try updating the Core and report back with info on that as well.

For specifics on data inconsistencies, I had issues with getting the correct number of environments show up in the Power BI dashboard after I had refreshed the data. The number of total environments is over 110, but in the dashboard it is showing roughly 85 environments. It also effected the MSFT Teams environment tab, as well as showing an incorrect amount of connectors. Looks to be a trickle down effect of all data I could see in the dashboard. No one else has access to my environment except myself and a few other folks who have not touched the environment in question.

**Comment by JeneferM-MSFT** [comment]
yes the old version of core did not yet track teams related environments. looks like these are the two main causes. 

- no audit logs
- no teams envts because old version of core. 
-
Please be sure to follow the instructions at  [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates) or you wont receive the changes. 

I will close this issue now as a result.

**Comment by yearwoodm15** [comment]
Hi Jenefer,

I know this was closed, but can we re-open? I'm getting a DLP error when attempting to turn on on some the Admin | Sync Templates (Apps, Connectors, Custom Connectors, Flows, Model Driven Apps, PVA. RPA is no longer present in V3??), but it's not super helpful with which connector I need to identify - can you assist?

Failed to activate component(s). Flow client error returned with status code "Forbidden" and details "{"error":{"code":"DlpViolation","message":"Admin data policy '(environment name)' restricts use of these apis: Http."}}".

At first I thought it was the HTTP connector, but it doesn't look like that's the case. I added in all the connectors under my Data Policy that were required for setting up [MSFT CoE](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#import-the-solution). Is there something else I need to add in?

**Comment by JeneferM-MSFT** [comment]
You likely have more than 1 DLP policy impacting the environment. And one of them restricts HTTP. 

I'm afraid what you need is hands on assistance in setup and we cant scale to assisting with this type of setup for our GitHub customers. 

Do you have a contact in Microsoft with whom you work regularly? They may be able to get you assistance. Or you my need to reach out to a partner to help with setup.

**Comment by yearwoodm15** [comment]
Hi Jenefer, thank you. I was able to confirm that the environment is associated to only one data policy. I do have a contact at MSFT that I can reach out to in order to assist me. Thanks again!
