### ISSUE TITLE
Power Automate Management Connection is not working for one of the CoE Environments

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#959]
Hello Team,

We are facing an issue with the "Power Platform Management" connection in the CoE development environment, while all other CoE environment and other environments it gets connected as expected. All CoE staging environments are in the single DLP policy where "Power Automate Management" connector is a part of "Business" category, meaning there is no issue with DLP policy.

**Error :** FlowRPCustomConnector needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it.

We have connected to Microsoft Support as this sounds an issue for the Power Platform to us and not CoE kit , however they have mentioned that this is related to CoE Kit, therefore it has to be raised in the Git Hub forum.

Would you please suggest, what could be the root cause of this connection error, while it works for the same account in the same tenant for other environments except CoE Dev Environment?

Thank you for your time in advance!

Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

when you establish the connection to Power Automate Management, please ensure you select First Party as Authentication:
![image](https://user-images.githubusercontent.com/55705669/115844782-19907500-a418-11eb-87a6-a84f58e8694a.png)

Also, you will have to have the Power Platform service admin role to access and use this connector.

Thank you
Manuela

**Comment by dips23** [comment]
Ahha, We did miss this point, Thank you Manuela for addressing - However I was wondering, would it be possible to change the existing connector as "First Party" or we should re-create this connector?

Regards,
Dipti

**Comment by manuelap-msft** [comment]
Hello,

you will have to re-create the connection - I may be wrong but I think you could this for all flows in one go by:

1. Go to make.powerapps.com
2. Go to Solutions
3. Open the **Default Solution**
4. Filter to see Connection References
5. Look for the Power Automate Management CoE Connection
6. Select and Edit it
7. Select + New Connection 
![image](https://user-images.githubusercontent.com/55705669/115851472-e56c8280-a41e-11eb-8ff7-501b8859d34f.png)
8. And when that pops up, select First Party there


Hope that helps
Manuela

**Comment by dips23** [comment]
Thank you for the clarification, we can close this ticket, Happy Weekend!

**Comment by manuelap-msft** [comment]
Great, thanks for letting me know! Happy weekend to you too :)
