### ISSUE TITLE
[BUG]: List Flows As Admin Fails with 401

### ISSUE THREAD

**Issue by indyness** [microsoft/powerapps-tools#961]
**Describe the bug**
Admin | Sync Template v3 (Flows) fails with a 401 on the List Flows as Admin action. 

We are using an account with Power Platform Admin with no PIM. All the Flows in core solution work fine, except Admin | Sync Template v3 (Flows). Fails with a 401 on the List Flows as Admin action. This connector seems to only work for the current environment where the Flow is being run. This action does not seem to be able to reach into other environments and retrieve Flows even when using a Power Platform Admin account. The last time this worked was 3/30. I just upgraded to recent release (which rocks BTW) to see if that would help but it's not working.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution Core
 - Version 2.0.10
 - Flow Sync Template v3 (Flows)

Error: (abbreviated) 
{
    "statusCode": 401,
    "headers": {
        "Pragma": "no-cache",
        "x-ms-request-id": "usgovvirginia:",
        "Date": "Sat, 24 Apr 2021 10:09:49 GMT",
        "WWW-Authenticate": "Bearer authorization_uri=\"https://login.windows.net/\", error=\"invalid_token\", error_description=\"Could not find identity for access token.\"",
    },
    "body": {
        "error": {
            "code": "AuthenticationFailed",
            "message": "Authentication failed. "
        }
    }
}

**Additional context**
We are in GCC moderate.

If this Flow is working for other customers who are using a PP Admin Account, then I'll open a case with Microsoft. But I found older documentation for the Power Automate Management connector that states that global admin is required. That is a non-starter for us. Thanks

**Comment by JeneferM-MSFT** [comment]
Hello, yes this is working for others just fine. You do not need global admin anymore for that connector though this used to be the case. 

One thing to check before contacting support, when you created established the connection to Power Automate Management, did you select First Party as Authentication:
![image](https://user-images.githubusercontent.com/62659043/116103183-97e55500-a66c-11eb-9c17-5d97e81f1943.png)

**Comment by JeneferM-MSFT** [comment]
Closing out issue as no further action for us to take.
