### ISSUE TITLE
How to get a flow zip file from JSON files

### ISSUE THREAD

**Issue by Aparna-Mutalik** [microsoft/powerapps-tools#962]
Hi Team,

I have exported JSON files for connection references and flow definition for the flows. I want to import the flow using these JSON files. 

Can you guide me how to do that.

**Comment by manuelap-msft** [comment]
Hello,

in this GitHub forum, we are only able to assist with queries and issues related to the CoE Starter Kit solution (https://aka.ms/coestarterkit). For more general questions, please raise them in the Power Automate community forum: https://powerusers.microsoft.com/t5/Microsoft-Power-Automate/ct-p/MPACommunity

Thank you
Manuela
