### ISSUE TITLE
"List Flow Owners" action is not working to archive flows for the default environment

### ISSUE THREAD

**Issue by dips23** [microsoft/powerapps-tools#963]
Hello,

We have CoE Starter kit installed with version 1.70.2 last year, And we have noticed that flows are not archived due to following error at "List Flow Owners" action:

{
  "error": {
    "code": "ConnectionAuthorizationFailed",
    "message": "The caller with object id 'XXX' does not have permission for connection 'XXX' under Api 'shared_logicflows'."
  }
}

This is happening for the user who is Power Platform/D365/Power BI Administrator in the tenant. We have raised support ticket with MS to help us on this thinking, it could be the issue with the action, however just came across [this ](https://github.com/microsoft/powerapps-tools/issues/459) discussion and thought of raising the similar concern here.

We have then tried checking the same action under same user for the same environment and flow, however it still throws this error:

![image](https://user-images.githubusercontent.com/13658386/116079191-7fbe0780-a665-11eb-882b-25e1a8de2dc4.png)

while "Power Automate Management Connection" is active and functional. This error seems to be happening only for the default environment. We are not sure whether it's a limitation of the "List Flow Owners" action or Archival flow for the installed version.

Would you please help, what should we do?

Thank you for your time in advance!

Best Regards,
Dipti

**Comment by JeneferM-MSFT** [comment]
Hello. I dont quite follow. 

First note that if you are in the Core version 1.70.2 then you will need to upgrade before we can assist further. 
Secondly, the failure you show does not appear to be from the toolkit but from a test flow of your own. 

Please upgrade Core to the latest (2.0.10), if your issues still persist in the toolkit itself then return with the failures from within the toolkit. 

Thank you.

**Comment by JeneferM-MSFT** [comment]
Sorry didnt mean to close.

**Comment by JeneferM-MSFT** [comment]
Oh I follow here. Yes this is behavior from the archival flows that we no longer support do to changes in the way flow works. 
So you should upgrade Core and Governance. And any issues you are seeing around this particular call no longer impact the toolkit. 
Thanks for using CoE

**Comment by dips23** [comment]
Thank you Jenefer for the clarification, We will plan accordingly!

Best Regards,
Dipti
