### ISSUE TITLE
DLP Editor V2 cannot create Single Environment DLP Policy

### ISSUE THREAD

**Issue by Freesky0605** [microsoft/powerapps-tools#964]
**Describe the bug**
In DLP Editor V2 App creating a Single Environment policy ends with an error, so that the DLP policy for Single Environment cannot be created.  

**To Reproduce**
1. Go to Power App  'DLP Editor V2'
2. Click on '+ New Tenant Policy'
3. Add policy name and select "Next"
4. Select "Next" on the page of Connectors
5. On the page of Scope, select "Single environment" and select "Next"
6. On the page of Environments, add the Default environment to this policy and then select "Next"
7. On Review page it shows that one environment is selected
8. Click button "Create Env Policy"

**Expected behavior**
Error appears with a message "The provided data loss prevention policy's type only allows selection of one environment". This policy cannot be created.

**Screenshots**
![DLP_Editor_Error](https://user-images.githubusercontent.com/15806999/116043580-23acb080-a670-11eb-84fd-1686178cc956.PNG)

**Comment by JeneferM-MSFT** [comment]
Hello. This is known and the option to create envt level policies was removed from the tool as a result. When you update you will see this to be the case. 
The product is the best place to create new policies and our toolkit really only offers the ability to check impact of changes. 
Thanks for using CoE
