### ISSUE TITLE
[BUG]: Updating CoE Core Components to 2.0.10 version fails

### ISSUE THREAD

**Issue by AbdoulatifAv** [microsoft/powerapps-tools#969]
**Describe the bug**
Updating the CoreComonents solution from version 1.89 to 2.0.10 fails with the following error:
Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution : Center of Excellence - Core Components
 - Version 2.0.10

**To Reproduce**
1. Download version 2.0.10 of Core Components
2. Navigate to Solutions on make.powerapps.com
3. Select Solutions
4. Select Import
5. Navigate to downloaded solution (Version 2.0.10 of Core Components) and press OK -> Importing
6. See error while import : Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

**Expected behavior**
I expected the Core Components to be updated from 1.89 to 2.0.10 successfully.

**Screenshots**
<img width="838" alt="Update" src="https://user-images.githubusercontent.com/83294679/116263025-5393ab00-a779-11eb-8f14-c60ad2f291d3.png">

**Comment by JeneferM-MSFT** [comment]
Hello. Other folks have seen this and it has gone away with time. Unfortunately it appears to be a product issue though, not an issue with the toolkit, and so you will need to contact product support if it persists. 

Most folks were able to upgrade the next day when they hit this,

**Comment by AbdoulatifAv** [comment]
Hello! We are still experiencing this issue. How long does it usually take to go away?

**Comment by JeneferM-MSFT** [comment]
I'm afraid this is a product issue and so I really cannot assist further. For most people this went away the next day on its own.
