### ISSUE TITLE
[BUG]: Error when selecting Submit Button on send status Screen

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#97]
**Describe the bug**
When selecting the Submit button you get an error that the notification has failed.

**To Reproduce**
1. Go to 'Status Screen.'
2. Click on '.Submit.'
3. See error

**Expected behavior**
After clicking on the Submit button, I expected to have a successful sending of the notification

**Screenshots**

**Interface(please complete the following information):**
 - Browser Microsoft Edge
 - Version date Microsoft Edge 44.18362.449.0

**Smartphone (please complete the following information):**

**Additional context**
To fix change 👎 
// Notify selected users.
UpdateContext({
    locEmailSuccess:
    Office365Outlook.SendEmailV2(
        Concat(colNotify,Coalesce(Mail,userPrincipalName) & ";"),     <---
        "Work status: " & selectedWorkStatus.Value & " starting on " & Date(Year(varStartDate),Month(varStartDate),Day(varStartDate)),

To 👎 
// Notify selected users.
UpdateContext({
    locEmailSuccess:
    Office365Outlook.SendEmailV2(
        Concat(colNotify,Coalesce(Mail,varUser.userPrincipalName) & ";"),   <---
        "Work status: " & selectedWorkStatus.Value & " starting on " & Date(Year(varStartDate),Month(varStartDate),Day(varStartDate)),

**Comment by mr-dang-msft** [comment]
Hi @NPrice99,
Can you state the error you were receiving?

Regarding this part:
`Coalesce(Mail,userPrincipalName)`
The formula will fall back to the user principal name of the recipient if they do not have a Mail address on file. Your change would make it add the logged-in user in those situations. 

If you had received an error, it might be that the recipient did not have an applicable email address, but I would need to see the error to confirm. Would you be able to share the error?

**Comment by mr-dang-msft** [comment]
I think I may have found the error. The Contacts screen collected people as well. I've removed the function from that gallery. Let me know if that was the case.

**Comment by mr-dang-msft** [comment]
As mentioned in my previous response, I've removed the function from the Contacts gallery that also contributed to the list of people to notify. 

Please let me know if this resolves the issue for you.
Link: https://github.com/microsoft/powerapps-tools/commit/b48c746ee5d96884efc5ec6654a696dac6c2b8de#diff-b31cdce1a7fc4de5376d4341db3de27b

**Comment by NPrice99** [comment]
Hi Brian - Now works in V2 so I will close Regards  Nigel
