### ISSUE TITLE
Admin | Compliance detail request flow missing from governance components

### ISSUE THREAD

**Issue by pmatthe1** [microsoft/powerapps-tools#974]
Hi, I downloaded the latest version of the CoE Starter Kit this morning and installed the Core and Governance components.  However when I looked at the governance solution I noticed that the "Admin | Compliance detail request" flow is missing.  I checked the solution

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Govern (CenterofExcellenceAuditComponents_1_51_5_managed.zip)
 - App - Admin | Compliance detail request

**To Reproduce**
Install the solution and navigate to the solution, filter by cloud flows.

**Expected behavior**
I would have expected the flow to be in the solution.

Has this flow been moved to another component, or the functionality changed in any way.

thanks

**Comment by manuelap-msft** [comment]
Hello,

we had to move this solution to the Core Components solution, and the latest version of Core will include this together with the Environment Variables needed for this solution.

We had to make this change in our efforts to increase support for Dataverse for Teams environments. 

Thank you
Manuela
