### ISSUE TITLE
[BUG]: Not able to import the COE Starter Kit core solution into a Dataverse for Teams environment

### ISSUE THREAD

**Issue by HelmutWimmer** [microsoft/powerapps-tools#977]
**Describe the bug**
New day, new error. This time, the solution import fails with the error message "The imported solution and the existing solution must both be managed for upgrade.", see screenshot

![image](https://user-images.githubusercontent.com/50572186/116515824-16403200-a8cd-11eb-8327-ec0e0bde4ac7.png)

The log file shows an error about missing capacity, but this is wrong as the next screenshot shows:
![image](https://user-images.githubusercontent.com/50572186/116515907-366ff100-a8cd-11eb-8426-4efac90f766d.png)

[CenterofExcellenceCoreComponentsTeams_1_9_managed.zip_import (1).txt](https://github.com/microsoft/powerapps-tools/files/6396926/CenterofExcellenceCoreComponentsTeams_1_9_managed.zip_import.1.txt)

Somehow the CoE Kit and Teams don't like each other in my environments...

**Comment by manuelap-msft** [comment]
Dataverse for Teams environments don't consume capacity from your tenant capacity, instead capacity is allocated based on user licenses in the tenants. If you select Microsoft Teams on the the screenshot you showed above, how many environments and capacity does it say you have available?

**Comment by HelmutWimmer** [comment]
![image](https://user-images.githubusercontent.com/50572186/116517971-fa8a5b00-a8cf-11eb-8a33-a6132e45102e.png)

**Comment by manuelap-msft** [comment]
It looks like you have 0 capacity and 0 environments allocated to your tenant. 

Are you able to import other solutions and is only the CoE one failing? Would you be able to try importing another managed solution and see if that succeeds? As your failure happens before import, we need to confirm if its something in the kit or something in your tenant/product causing the issue.

**Comment by manuelap-msft** [comment]
You can learn more about Teams capacity enforcements here https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#enforcement as to me it looks like you are hitting those limits.

**Comment by HelmutWimmer** [comment]
Well, as a Microsoft employee I need to show this to partners and customers. I only have access to Demo and Trial environments (e.g. from demos.microsoft.com) so I think I've hit a barrier here which limits us in showing the CoE kit to anyone who would be interested.

**Comment by manuelap-msft** [comment]
Unfortunately that may be true. We have many customers who are now using the CoE in Teams and have been able to import the solution, so I'm afraid the issues you're experiencing are likely not with the solution itself. Sorry we've not been able to help you further!
