### ISSUE TITLE
[BUG]: If Link is Updated WHilst someone is logged in, then they dont get that link

### ISSUE THREAD

**Issue by NPrice99** [microsoft/powerapps-tools#98]
**Describe the bug**
A user logged in who looks at a screen such as the "Links" Screen and the administrator updates the Links, the user does not get the new link until they log out and log back in again.

**To Reproduce**
1. Go to 'Home Screen.'
2. Click on '.Links Item' and go to the Links Screen.  Note the number of Links.
3. The administrator adds a new Link
4. Click the back button on the links screen and then click "Links" note that the number of links has not changed.

**Expected behavior**
After clicking on the Links button a second time I would expect the new Link to be displayed.

**Screenshots**

**Interface(please complete the following information):**
 - Browser Microsoft Edge
 - Version date 44.18362.449.0

**Smartphone (please complete the following information):**

**Additional context**
To fix :- on the OnVisible event of the Links Screen add Refresh(CI_Usefulinks)

**Comment by mr-dang-msft** [comment]
Each screen is currently using collections. Upon returning to the same screen, the app will refresh the data source and recollect the list. A log-out is not required.

With the galleries directly tied to the SharePoint lists, the list would still need a refresh to appear in the gallery. 

Would you like a manual refresh icon on the screen so you do not need to leave and return?

**Comment by NPrice99** [comment]
Hi Brian I added a Refresh(<datasource>) to the onvisible event of the screen to fix the problem. Regards Nigel

**Comment by NPrice99** [comment]
Refresh(‘datasource’)

**Comment by mr-dang-msft** [comment]
What version of the app are you running? V2 should have the Refresh() action on each screen already. Let me know if you're still on version 1.

**Comment by NPrice99** [comment]
Hi Brian

I was using V1.

Now I have upgraded to V2 I can see the  Refresh(<datasource>) statements in the OnVisible events.

Regards

Nigel

**Comment by NPrice99** [comment]
Hi Brian - Now works with V2 - I was running V1.  So I will close Regards  Nigel
