### ISSUE TITLE
Importing solutions into Dataverse for Teams environment fails

### ISSUE THREAD

**Issue by mschaefer85** [microsoft/powerapps-tools#983]
**Describe the bug**
When trying to install the solutions in a Dataverse for Teams (DV4T) environment, importing the 2nd solution (CenterofExcellenceAuditComponents_1_51_5_managed.zip) fails with the error message: "Solution manifest import: FAILURE: The operation Install Solution CenterofExcellenceAuditComponents was blocked since the tenant is over maximum number of environments allowed per tenant. Please work with your administrator to resolve this issue."

This is the content of the XML log. In the frontend it says: "The imported solution and the existing solution must both be managed for upgrade."

**To Reproduce**
1. Go to Teams, there to the Power Apps App and import CenterofExcellenceCoreComponentsTeams_1_9_managed.
2. After having configured the Core Components, import CenterofExcellenceAuditComponents_1_51_5_managed.
3. After selecting the connections, the import starts.
4. The error appears.

**Expected behavior**
I'd expect the solution to import just fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/10259284/116668806-1b20e680-a99e-11eb-97b0-1354fc50bad7.png)

**Additional context**
Indeed, I do only have a demo environment, but I have a trial premium license for the user installing the app. As far as I now, a DV4T environment does not consume any capacity, so I cannot figure out, why this error keeps appearing.

**Comment by manuelap-msft** [comment]
Hello,

can you confirm you have the Core components already installed in that environment? Based on your description, you are importing the Governance solution now which has a dependency on Core, so can I assume your import of Core succeeded?

Thank you,
Manuela

**Comment by manuelap-msft** [comment]
Hello,

and you also have a dummy approval flow to import the Approvals solution, and that has finished running? https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment

Thank you
Manuela

**Comment by manuelap-msft** [comment]
Hello

The error you are seeing is to do with Dataverse for Teams capacity enforcement https://docs.microsoft.com/en-us/power-platform/admin/about-teams-environment#enforcement

As demo / trial tenants are not granted D4T capacity, this resulted in the error you are seeing. I believe the team is looking at how to disable enforcement or grant capacity for demo tenants but this is out of scope of what we're able to support or track here on GitHub.

Thank you 
Manuela
