### ISSUE TITLE
[BUG]: Error on updating Core Components

### ISSUE THREAD

**Issue by SimonPiquer** [microsoft/powerapps-tools#984]
**Describe the bug**
When I installed the update for the CoE Core Components 2.0, apparently something must've gone wrong because instead of updating, it created another "Core Components Solution", with the name CenterofExcellenceCoreComponents_Upgrade, and the component named CenterofExcellenceCoreComponents is still at my old version (1.98). 

I did not notice this until now, when I tried to install version 2.0.10 and I got the following error:

> Solution "Center of Excellence - Core Components" failed to import: ImportAsHolding Exception during StageAndUpgrade

Here is the log file:
[Center of Excellence - Core Components_import.txt](https://github.com/microsoft/powerapps-tools/files/6404750/Center.of.Excellence.-.Core.Components_import.txt)

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - Version 2.0+

**Screenshots**
![image](https://user-images.githubusercontent.com/80743138/116685113-2120c280-a9b2-11eb-9639-8042349fcc5b.png)

**Additional context**
AFAIK everything has been working since I updated to 2.0 on the 11th of April. I can't delete either version because of dependencies and I don't want to risk breaking anything. Any tips on how to get past this and upgrade to newer versions?

**Comment by JeneferM-MSFT** [comment]
Can you please share a picture of what this error says in Excel rather than sharing the file?

**Comment by SimonPiquer** [comment]
Absolutely, sorry about that, here it is. I also saved it as an .xlsx instead if that helps.

![image](https://user-images.githubusercontent.com/80743138/116709990-8afc9480-a9d1-11eb-87bf-c3bc94652e85.png)
[Center of Excellence - Core Components_import.xlsx](https://github.com/microsoft/powerapps-tools/files/6406054/Center.of.Excellence.-.Core.Components_import.xlsx)

**Comment by JeneferM-MSFT** [comment]
Hello. I'm afraid that is a product issue with upgrade. A few others have seen this and it was temporal and went away after a delay. 

You might try switching to classic and doing an overwrite. Or waiting and trying again later. Else you may need to contact product support. 

Sorry that we cannot be of more help.
