### ISSUE TITLE
Unable to activate Maker Assessment | Import starter data flow

### ISSUE THREAD

**Issue by kaalen** [microsoft/powerapps-tools#985]
I'm not able to save the necessary modifications to run Import starter data flow. I attempted to modify the flow by specifying the SharePoint site and library to which I've uploaded the Excel spreadsheets. I verified the excel spreadsheets are uploaded and can be opened.

I get the following error that doesn't tell me much:
`Your flow could not turn on: Maker Assessment | Import starter data. Error: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'MultipleErrorsOccurred' and message 'The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n "status": 404,\r\n "message": "Item not found\r\nclientRequestId: 6a5914a7-e4ae-4f61-908b-c464d99810af\r\nserviceRequestId: 75203132-3fc0-47d8-b87b-a67a42000121",\r\n "error": {\r\n "message": "Item not found"\r\n },\r\n "source": "excelonline-ae.azconn-ae.p.azurewebsites.net"\r\n};The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n "status": 404,\r\n "message": "Item not found\r\nclientRequestId: 6a5914a7-e4ae-4f61-908b-c464d99810af\r\nserviceRequestId: 3bdbc9c9-f4a2-42ec-a020-e85650a7dab6",\r\n "error": {\r\n "message": "Item not found"\r\n },\r\n "source": "excelonline-ae.azconn-ae.p.azurewebsites.net"\r\n};The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n "status": 404,\r\n "message": "Item not found\r\nclientRequestId: 6a5914a7-e4ae-4f61-908b-c464d99810af\r\nserviceRequestId: 2d260d2f-d801-4c47-bb30-8f91c2bd0d02",\r\n "error": {\r\n "message": "Item not found"\r\n },\r\n "source": "excelonline-ae.azconn-ae.p.azurewebsites.net"\r\n}'."}}".`

**Comment by JeneferM-MSFT** [comment]
When you first open the flow all the calls to Excel look like this and need to be manually adjusted
![image](https://user-images.githubusercontent.com/62659043/116710538-1a348880-a98f-11eb-839b-1d5f2d83fcb4.png)

You need to:
1) Ensure that you entered the environment variable to the site per step 4 of [import](https://docs.microsoft.com/power-platform/guidance/coe/setup-nurture-components#import-the-solution)
![image](https://user-images.githubusercontent.com/62659043/116710989-9cbd4800-a98f-11eb-8c65-24290fd60372.png)

1) X out the Document Library listed (b!USLFzgurgEysC29fEYaZFim4J_jtwnpBkzFasjrdKSz3-2KM6fvTSqj0EE1N9dCR) and choose the correct library (Documents for me)
![image](https://user-images.githubusercontent.com/62659043/116711203-daba6c00-a98f-11eb-80d3-cd5e680db7f9.png)

1) hit the folder icon and choose the correct file 
     - Categories = assessmentcategories.xlsx
     - Questions = assessments.xlsx
     - Answers = answeroptions.xlsx

1) Hit the drop down on Table and chose the correct Table (Table1 if you do not change the files)

In the end they will look like this, with your library name:
![image](https://user-images.githubusercontent.com/62659043/116711618-41d82080-a990-11eb-996a-5e37ca24e6e8.png)

**Comment by JeneferM-MSFT** [comment]
I have made all those more explicit in the upcoming version of the documentation. 
Thanks for using CoE
