### ISSUE TITLE
Unable to import AuditComponents(Governance)

### ISSUE THREAD

**Issue by achaganti** [microsoft/powerapps-tools#987]
Receiving the error 

There are missing dependencies. Install the following solutions before installing this one: "msdyn_FlowApprovalsCore (2.0.1.1)".

Governance Solution Version: 1.50
Core Solution Version: 2.0.10
![image](https://user-images.githubusercontent.com/34516164/116860024-8aa50900-ac1e-11eb-9533-19f1ddbd2932.png)

**Comment by manuelap-msft** [comment]
Please follow step 1 in our documentation to initialize Approvals in the environment: https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-governance-components#initialize-flow-approval-tables-in-your-environment
