### ISSUE TITLE
[BUG]: issue title

### ISSUE THREAD

**Issue by ApoorvaKantale** [microsoft/powerapps-tools#988]
The flow is failing with 

**OpenApiOperationParameterValidationFailed. The 'inputs.parameters' of workflow operation 'Update_a_row' of type 'OpenApiConnection' is not valid. Error details: The API operation 'PatchItem_V2' requires the property 'Column ID' to be a string of maximum length '100' but is of length '233'.**

I have went and changed the column length to 1000 in COE table. After that also the flow is failing with the same. 

Kindly let me know how do we change the length of single line of text (Data stored in it is SharePoint  URl)
and in other column it is also single line of text (Data stored App Name and the name is too long)

Else How do I fix the flow. 
Please look into it urgently

**Comment by JeneferM-MSFT** [comment]
I dont quite follow the issue. Can you please share which flow and which action is failing?

**Comment by ApoorvaKantale** [comment]
Hi,

We have created a custom flow for governance compliance in COE. That is were the flow is failing with the below error
![image](https://user-images.githubusercontent.com/78148795/116966604-36f1f880-acce-11eb-8396-45bedf66ea2f.png)

**Comment by manuelap-msft** [comment]
Hello,

Jenefer and I are only able to support flows that are part of the CoE Starter Kit. We are not product support, but only the developers behind the CoE Starter Kit. For Product issues or issues with your own flows, you will need to raise a support ticket.

Thank you
Manuela
