### ISSUE TITLE
[PRODUCT BUG]: Fail to run Maker Assessment | Import starter data cloud flow: XRM API failed: Flow not found

### ISSUE THREAD

**Issue by rahul9226** [microsoft/powerapps-tools#989]
**Describe the bug**
Maker Assessment | Import starter data cloud flow not working.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [e.g. Nurture]
 - Version [e.g. 1.40]
 - App or Flow [e.g. Maker Assessment | Import starter data cloud flow )]

**To Reproduce**
1. Go to '..Maker Assessment | Import starter data cloud flow .'
2. Click on ' each Online Excel Business connector to update location of Excel file residing in SharePoint'
3. Save and test flow, give it a run.
4. Getting error as below,
 **Request to XRM API failed with error: 'Message: Flow client error returned with status code "NotFound" and details "{"error":{"code":"AzureResourceManagerRequestFailed","message":"Request to Azure Resource Manager failed with error: '{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Logic/workflows/6bc8b3a2-849e-be0d-643e-af31612be85d' under resource group 'b18d9f6f0743460da19b0b3297eeeb89-87eee8955456444a9550c703cfa5a074-env' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}'."}}". Code: 0x80060467 InnerError: '.**

5. Checked with connections and access to SharePoint. Everything was in place.

**Expected behavior**
Flow should run and reflect questioner in Makers assessment app. 

**Screenshots**

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. This is a product bug. If you exit from the flow and return it will work.

**Comment by JeneferM-MSFT** [comment]
I added a note about this to the documentation, including picture. 
You close the browser window, re-open the flow, and it works. 
![image](https://user-images.githubusercontent.com/62659043/116941312-af07e200-ac2c-11eb-892f-a18b9df88dcd.png)

**Comment by danielstaleyedf** [comment]
I'm getting a similar error but the suggested resolution does not work.

`Request to XRM API failed with error: 'Message: Flow client error returned with status code "BadRequest" and details "{"error":{"code":"InvalidOpenApiFlow","message":"Flow save failed with code 'MultipleErrorsOccurred' and message 'The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n \"status\": 404,\r\n \"message\": \"The resource could not be found.\\r\\nclientRequestId: 2ebea0be-1197-4164-aa04-c8e9607405a3\\r\\nserviceRequestId: 163cf0d7-a1b8-42ca-8b23-676db9b6815d\",\r\n \"error\": {\r\n \"message\": \"The resource could not be found.\"\r\n },\r\n \"source\": \"excelonline-uks.logic-ase-uksouth.p.azurewebsites.net\"\r\n};The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n \"status\": 404,\r\n \"message\": \"The resource could not be found.\\r\\nclientRequestId: 2ebea0be-1197-4164-aa04-c8e9607405a3\\r\\nserviceRequestId: 31771376-ab00-4da5-99f8-4100b5b8dcc4\",\r\n \"error\": {\r\n \"message\": \"The resource could not be found.\"\r\n },\r\n \"source\": \"excelonline-uks.logic-ase-uksouth.p.azurewebsites.net\"\r\n};The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code 'NotFound'. This may indicate invalid input parameters. Error response: {\r\n \"status\": 404,\r\n \"message\": \"The resource could not be found.\\r\\nclientRequestId: 2ebea0be-1197-4164-aa04-c8e9607405a3\\r\\nserviceRequestId: a3e80769-6214-46bc-9b09-4372c6b5b528\",\r\n \"error\": {\r\n \"message\": \"The resource could not be found.\"\r\n },\r\n \"source\": \"excelonline-uks.logic-ase-uksouth.p.azurewebsites.net\"\r\n}'."}}". Code: 0x80060467 InnerError: '.`

**Comment by JeneferM-MSFT** [comment]
Flow saved is a different error than fail to run. We have just released the documentation. Note that you need to touch all of the fields (location/doc lib/file/table) in order for them to resolve
https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-nurture-components#import-default-data-set-for-the-maker-assessment-app
