### ISSUE TITLE
[BUG]:Raw data html value is not converting to htmltext control 

### ISSUE THREAD

**Issue by parthkarry** [microsoft/powerapps-tools#99]
In the company detail news screen we have htmltext control to display html formatted data in text area . But it is not converting into html and displaying as plane text with html code .
 It is using global variable of selectedNews.Details .

Have any one encounter this issue .

I also followed standard way of datacard but on this screen layout not found datacard

Followed this :
https://powerusers.microsoft.com/t5/Webinars-and-Video-Gallery/Handling-SPO-Rich-Text-Columns-in-PowerApps/td-p/138498

When I am directly putting the html data in text property it is getting converted properly .
 I have made my own form with keyvalue and card and their it is converting .

**Comment by mr-dang-msft** [comment]
Resolved on an earlier call. 

Summary:
If you want to paste HTML content into the article of Company News via the admin app, the rich text editor does not consume raw HTML in tags (<b>text</b>). You are able to paste in rendered, previewed HTML instead, but it may not render it well depending on what's inside.

For raw HTML it is best to go to the source SharePoint list for company news and add the raw HTML there.
