### ISSUE TITLE
[BUG]: Configuring custom connector fails with Invalid client secret is provided

### ISSUE THREAD

**Issue by dynamic-pindar** [microsoft/powerapps-tools#990]
**Describe the bug**
When creating the connection for the Office 365 Management API in the Test page for the custom connector, I receive the following error message

****OAuth2 authorization flow failed for service 'Azure Active Directory'. OAuth 2 sign in failed to exchange code for access token. Client ID and secret sent in form body.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 4dc9e9d2-9080-40d4-ab4e-a2db5a423703\r\nCorrelation ID: eb20f0cf-f0f4-4ce4-8120-5f41f13f41b0\r\nTimestamp: 2021-05-04 03:55:43Z","error_codes":[7000215],"timestamp":"2021-05-04 03:55:43Z","trace_id":"4dc9e9d2-9080-40d4-ab4e-a2db5a423703","correlation_id":"eb20f0cf-f0f4-4ce4-8120-5f41f13f41b0","error_uri":"https://login.windows.net/error?code=7000215"} Client ID and secret sent in Basic authorization header.. Response status code=Unauthorized. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 23f0c60e-3ab4-4a43-8971-9c86d9e52c03\r\nCorrelation ID: 7236be6e-e384-47f5-aa43-888593405714\r\nTimestamp: 2021-05-04 03:55:43Z","error_codes":[7000215],"timestamp":"2021-05-04 03:55:43Z","trace_id":"23f0c60e-3ab4-4a43-8971-9c86d9e52c03","correlation_id":"7236be6e-e384-47f5-aa43-888593405714","error_uri":"https://login.windows.net/error?code=7000215"}****

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 2.0.10
 - Custom Connector: Office 365 Management API

**To Reproduce**
1. Go to Custom Connectors
2. Select Edit for the Office 365 Management API
3. Go to Security and Enter the necessary details
4. Go to Test and select 'New connection' and click Create
5. Sign in to create the connection
6. Error appears

**Expected behavior**
The connection should create w/o any issues.

**Screenshots**
![error](https://user-images.githubusercontent.com/54971004/116959637-25780480-ac6c-11eb-9648-d92a98a35b27.JPG)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

the error message in the red pop up: **Invalid client secret is provided** - please verify you have entered the correct client id and secret.

Thank you
Manuela

**Comment by dynamic-pindar** [comment]
Thank you!  Copy-paste error from doing this in the middle of the night.
