### ISSUE TITLE
[BUG]: CoE Power BI Dashboard Cannot Export Underlying Data

### ISSUE THREAD

**Issue by drace3000** [microsoft/powerapps-tools#994]
**Describe the bug**
This BI Dashboard provides the capability to export the details of the underlying data for a given aggregate value

**To Reproduce**
1. Go To An Dashboard screen
2. Select an Aggregate Total until a popup menu appears
3. Select Export option
4. The export Popup window does not allow the selection of underlying data (see attached screen shot)

**Expected behavior**
Ability to select underlying data

**Screenshots**
 
![BI Overview Export](https://user-images.githubusercontent.com/22414379/116996228-19f6fe80-aca9-11eb-9939-691267102536.JPG)

**Additional context**

**Comment by manuelap-msft** [comment]
Hello,

the Power BI dashboard is built on top of Dataverse - you will have to have access to all the tables in Dataverse to export the table. If the data is displayed correctly in the dashboard, but certain product functionality like exports is not working, then I'm afraid that's beyond the scope of what we are able to support here. We are not product support, but simply the developers of the CoE Starter Kit and thus can only support what we have developed ourselves.

Please raise a support ticket through your usual support channels to have a Support Engineer look at this with you.

Thank you
Manuela
