### ISSUE TITLE
Cannot see Custom Connector in DLP Policy editor

### ISSUE THREAD

**Issue by pmatthe1** [microsoft/powerapps-tools#995]
Hi

I have installed the CoE Starter Kit and also set-up the Audit Log connector following the instructions detailed here - https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-auditlog

This has all been set up successfully without error and the Custom Connector is appearing in the "Custom Connector" option in the Maker Portal, and there is a matching connection in the "Connections" section.

However the connector is
1. Not appearing in Custom Connectors section of the Power BI Dashboard
2. I am not able to add this connector to the Business-Only section of my DLP Policy as per the instructions because it is not available.

Many thanks in advance
Paul

**Comment by JeneferM-MSFT** [comment]
Hello. Unfortunately the work to make custom connectors work nicely with DLP is a feature still in progress for Power Platform. Its coming soon but in the meantime you need to use PowerShell to make it happen. 

Please use this document to setup DLP for the custom connector
[Custom Connector into DLP.docx](https://github.com/microsoft/powerapps-tools/files/6427694/Custom.Connector.into.DLP.docx)

**Comment by JeneferM-MSFT** [comment]
Regarding the Power BI
1) Can you please make sure that the Dataset has been refreshed? 
![image](https://user-images.githubusercontent.com/62659043/117154516-26e32300-ad79-11eb-8eeb-6eeb86b9087e.png)

1) Do you see other custom connectors? And where is it that you are seeing it missing?

**Comment by pmatthe1** [comment]
Hi Jenefer

Thanks for this information.  I have followed the instructions and everything has successfully run, however I cannot see the custom connector available in the DLP Policy.

Is there any other step that I should do to make it appear.

Thanks
Paul

**Comment by JeneferM-MSFT** [comment]
No unfortunately part of the product work mentioned above it so show the custom connectors in the DLP. 
We do show them in the DLP Editor tool (which is in Core)
![image](https://user-images.githubusercontent.com/62659043/117305707-41320500-ae3c-11eb-8d3d-bf39eb2c1548.png)

Or you can have a flow reference the CC in the envt and turn it on. Showing that it is enabled.

**Comment by gcusworth** [comment]
> Hello. Unfortunately the work to make custom connectors work nicely with DLP is a feature still in progress for Power Platform. Its coming soon but in the meantime you need to use PowerShell to make it happen.
> 
> Please use this document to setup DLP for the custom connector
> [Custom Connector into DLP.docx](https://github.com/microsoft/powerapps-tools/files/6427694/Custom.Connector.into.DLP.docx)

Are you able to give an approximate timescale for the custom connector updates being released please?

**Comment by manuelap-msft** [comment]
https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-platform-governance-administration/data-loss-prevention-enhancements-manage-custom-connectors-seamlessly-at-tenant-environment-level

It should be this month.

**Comment by gcusworth** [comment]
> https://docs.microsoft.com/en-us/power-platform-release-plan/2021wave1/power-platform-governance-administration/data-loss-prevention-enhancements-manage-custom-connectors-seamlessly-at-tenant-environment-level
> 
> It should be this month.

Thank you, can you confirm whether these updates have been applied please?
