### ISSUE TITLE
[Product BUG]: Admin | Sync Template v3 (Apps) issue - "admin_app With Id = xxxxxx-xxxxx-xxxxxxx-xxxx Does Not Exist"

### ISSUE THREAD

**Issue by ddmregistration** [microsoft/powerapps-tools#999]
**Describe the bug**
The COE Starter Kit **Admin | Sync Template v3 (Apps)** flow always returns the following exception on several apps.
The **Get Apps as Admin** connector extracts several apps GUIDs that the **Get Power App** connector is not able to find and return the following exception :
{
  "error": {
    "code": "0x80040217",
    "message": "admin_app With Id = 4b690dd0-42a0-4937-ab87-9664a711ce5f Does Not Exist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Plugin/Microsoft.Crm.ObjectModel.CustomBusinessEntityService",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "b2d7683e-947a-eb11-b1ac-000d3a23c6ad",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "1",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "0cb7acd1-45bf-4e14-b076-571dc17ead0b",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "ObjectDoesNotExist",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "404",
    "@Microsoft.PowerApps.CDS.HelpLink": http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040217&client=platform,
    "@Microsoft.PowerApps.CDS.InnerError.Message": "admin_app With Id = 4b690dd0-42a0-4937-ab87-9664a711ce5f Does Not Exist"
  }
}

**Component (please tell us which flow or app you are experiencing issues with):**
 - Core
 - API version 2020-07-01
 - Admin | Sync Template v3 (Apps)

**To Reproduce**
The App GUID 4b690dd0-42a0-4937-ab87-9664a711ce5f reproduces the error.
You can reproduce the issue also with the following PowerShell commands:
Get-AdminPowerAppEnvironment  |%{
Get-AdminPowerApp -EnvironmentName $_.EnvironmentName | %{
Write-output “powerapps data”
}

**Expected behavior**
No Exceptions, the Get Apps as Admin should retrieve only valid apps

**Screenshots**

![Admin Sync Template v3 (Apps)](https://user-images.githubusercontent.com/83663925/117044960-46456600-ad0f-11eb-851b-e9465b3d8e42.png)

**Additional context**

**Comment by JeneferM-MSFT** [comment]
Hello. The action **_Get Power App_** is a check to see if the app already exists in the inventory. As you can see, the failure is caught by the next action **_Set isNewToCoE to true_**. This is an expected failure for new items to the inventory. 

If the flow failed on this iteration (565) then it failed later down in the flow. Can you please look for the uncaught failure?

**Comment by ddmregistration** [comment]
Hi Jenefer,
I attach to this response more drill down debug images, I hope it could be helpful for your analysis
Let me know if you need anything else.
![Flow debug 1](https://user-images.githubusercontent.com/83663925/117545709-37b8c080-b027-11eb-8ab7-ce5ef304e8d6.png)
![Flow debug 2](https://user-images.githubusercontent.com/83663925/117545710-38515700-b027-11eb-84eb-f4226399244f.png)


Thanks

**Comment by JeneferM-MSFT** [comment]
That is the failing action it seems. Can you please get the output?

**Comment by ddmregistration** [comment]
Hi,
I attached the json file downloaded
thanks
[Output.txt](https://github.com/microsoft/powerapps-tools/files/6467875/Output.txt)

**Comment by JeneferM-MSFT** [comment]
Unfortunately you have hit a product bug in which Get Apps as Admin is returning deleted apps, while later calls to get at that app fail (correctly) in that the app no longer exists. 

You can validate that this is the case outside of the toolkit using the attached flow.
Simply select the environment from your repro above, save, and run the flow. Then you will have to create a support ticket for them to clear the cache in your tenant. 
![image](https://user-images.githubusercontent.com/62659043/118021995-17d01800-b319-11eb-97b3-d569217cce08.png)

**Comment by JeneferM-MSFT** [comment]
Here is that flow for you to use. 

[ProductBug-GetAppfails-TheresponseisnotinaJSONformat.zip](https://github.com/microsoft/powerapps-tools/files/6468199/ProductBug-GetAppfails-TheresponseisnotinaJSONformat.zip)

Closing issue as there is nothing the toolkit can do to help

**Comment by andersidahl** [comment]
The productbug flow fails as well when running here.
![image](https://user-images.githubusercontent.com/10434858/119644563-453eba80-be1d-11eb-8c22-fbda4f6dad69.png)

**Comment by JeneferM-MSFT** [comment]
Please create a support ticket with this flow as it shows the repro in a simple case without the toolkit involved. 
Thanks for using CoE
